### ISSUE TITLE
CMI Mysql Error 

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#100]
Hi, I used the latest version of plug-in, I uploaded it to the server but the server crashes and always drops, the console shows error with mysql (probably missing a table on jail or what)

```
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded 3 portals into memory.[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mPEX permission plugin will be used[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (2) custom text's![m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22m[0;31;1mCould not initialize database!  Could not determine schema version![m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mVault was found - Enabling capabilities.[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22m[0;32;22mCMI economy been taken from vault[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (7) kits[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (2) cooldowns[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoading user data files.[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (7) kits[m
[02:27:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (7) ranks[m
[02:27:37] [Server thread/WARN]: java.sql.SQLException: Column 'Jail' not found.
[02:27:37] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[02:27:37] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[02:27:37] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[02:27:37] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[02:27:37] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
[02:27:37] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
[02:27:37] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1543)
[02:27:37] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1191)
[02:27:37] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:666)
[02:27:37] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:550)
[02:27:37] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1189)
[02:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[02:27:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[02:27:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[02:27:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[02:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[02:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[02:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[02:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[02:27:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[02:27:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zrips** [comment]
Strange, will remove deprecated schema version check, but why its failed in first place is really strange.
