### ISSUE TITLE
AccountHolderFactory 1.13.2

### ISSUE THREAD

**Issue by Icalave** [Zrips/CMI#1028]
Issue: Seems to run this every 1 minute on the dot

---

**ERROR**

```
[22:44:39 WARN]: [CMI] Plugin CMI v8.0.21.2 generated an exception while executing task 939
java.lang.NoSuchFieldError: accountHolderFactory
	at net.milkbowl.vault.economy.plugins.Economy_Gringotts.hasAccount(Economy_Gringotts.java:125) ~[?:?]
	at net.milkbowl.vault.economy.AbstractEconomy.hasAccount(AbstractEconomy.java:10) ~[?:?]
	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:85) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1571) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1565) ~[?:?]
	at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:754) ~[?:?]
	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:668) ~[?:?]
	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:286) ~[?:?]
	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:230) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-e4d0c66-72c3617]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-e4d0c66-72c3617]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

---

**Cmi Version (8.0.21.2):** 

**Server Type (Spigot):** 

**Server Version (1.13.2-R0.1-SNAPSHOT):** 

Might be something i'm missing in my config to disable the task that its trying to run. Not affecting anything on the plugin that i am requiring but would still like to know the cause of the error if anyone is able to assist me.

**Comment by mercurialmusic** [comment]
It looks like you're trying to run two economies at once -- Gringotts and CMI -- and they're fighting. Set CMI's economy to Enabled: false in the CMI config and restart.

```
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  Enabled: false
```

**Comment by Icalave** [comment]
I do already have that setting set to false yet this error is still running. That is why i was confused

**Comment by Zrips** [comment]
Its actually issue with your Economy Gringotts/Vault plugin, as CMI uses Vault as middle man to get players balance, but for some reason you have failure with Gringotts and Vault not communicating correctly. Missing accountHolderFactory method, to be more precise. Update one or another to appropriate version.
