### ISSUE TITLE
Console Error since today

### ISSUE THREAD

**Issue by HomeLandingsDE** [Zrips/CMI#103]
```
08.03 16:04:57 [Server] WARN [CMI] Plugin CMI v7.4.0.0 generated an exception while executing task 3878188
08.03 16:04:57 [Server] INFO java.lang.NullPointerException: null
08.03 16:04:57 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
08.03 16:04:57 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
08.03 16:04:57 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20) ~[Vault.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getFormatedBalance(CMIEconomyAcount.java:103) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Containers.CMIUser.getFormatedBalance(CMIUser.java:1234) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Containers.CMIUser.getFormatedBalance(CMIUser.java:1226) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:296) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:183) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:121) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:114) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:283) ~[CMI7.4.0.0.jar:?]
08.03 16:04:57 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3d850ec-809c399]
08.03 16:04:57 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-3d850ec-809c399]
08.03 16:04:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
08.03 16:04:57 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
08.03 16:04:57 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

**Comment by Ew9304** [comment]
You should try 7.4.1.0

**Comment by Zrips** [comment]
You should try 7.4.1.1 :)
