### ISSUE TITLE
[ERROR] errors spam after UltraPermissions update

### ISSUE THREAD

**Issue by user127001** [Zrips/CMI#1040]
**Most command not working with latest UltraPermissions**

At first I turned to the developer of UltraPerms plugin. He answered me:
"The update just came out. You would have to wait till the update is made by the cmi dev"

Result using ```cmi gm 1``` command:
**ERROR**
```
[22:45:08 INFO]: kassad issued server command: /cmi gm 1
[22:45:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.21.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [mcs.jar:git-Spigot-2474d93-e693496]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [mcs.jar:git-Spigot-2474d93-e693496]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoClassDefFoundError: me/TechXcrafter/UltraPermissions/UltraPermissions
        at com.Zrips.CMI.Modules.Permissions.UltraPermissions3Handler.getPrefix(UltraPermissions3Handler.java:43) ~[?:?]
        at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPrefix(PermissionsManager.java:596) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.updatePrefix(CMIUser.java:481) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getPrefix(CMIUser.java:556) ~[?:?]
        at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:286) ~[?:?]
        at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:176) ~[?:?]
        at com.Zrips.CMI.Locale.Language.getMessage(Language.java:106) ~[?:?]
        at com.Zrips.CMI.CMI.info(CMI.java:1869) ~[?:?]
        at com.Zrips.CMI.CMI.info(CMI.java:1884) ~[?:?]
        at com.Zrips.CMI.commands.list.gm.perform(gm.java:102) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[mcs.jar:git-Spigot-2474d93-e693496]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: me.TechXcrafter.UltraPermissions.UltraPermissions
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[mcs.jar:git-Spigot-2474d93-e693496]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at com.Zrips.CMI.Modules.Permissions.UltraPermissions3Handler.getPrefix(UltraPermissions3Handler.java:43) ~[?:?]
        at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPrefix(PermissionsManager.java:596) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.updatePrefix(CMIUser.java:481) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getPrefix(CMIUser.java:556) ~[?:?]
        at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:286) ~[?:?]
        at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:176) ~[?:?]
        at com.Zrips.CMI.Locale.Language.getMessage(Language.java:106) ~[?:?]
        at com.Zrips.CMI.CMI.info(CMI.java:1869) ~[?:?]
        at com.Zrips.CMI.CMI.info(CMI.java:1884) ~[?:?]
        at com.Zrips.CMI.commands.list.gm.perform(gm.java:102) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[mcs.jar:git-Spigot-2474d93-e693496]
        ... 15 more
---

**Cmi Version 8.0.21.4** 

**Spigot** 

**1.13.2 latest build** 


Best regards.

**Comment by DeadIntermediate** [comment]
I agree. I get errors with typing /time day.

Here is my error: https://pastebin.com/Qy4XZx4g

**Comment by Guddina-tim** [comment]
I also get errors during the startup sequence relating to Uperms.

`[03:37:21] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v8.0.21.4
java.lang.NoClassDefFoundError: me/TechXcrafter/UltraPermissions/UltraPermissions
	at com.Zrips.CMI.Modules.Permissions.UltraPermissions3Handler.getPrefix(UltraPermissions3Handler.java:43) ~[?:?]
	at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPrefix(PermissionsManager.java:596) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.updatePrefix(CMIUser.java:481) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.getPrefix(CMIUser.java:556) ~[?:?]
	at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:286) ~[?:?]
	at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:176) ~[?:?]
	at com.Zrips.CMI.Modules.TabList.TabListManager.updateTablistName(TabListManager.java:326) ~[?:?]
	at com.Zrips.CMI.Modules.TabList.TabListListener.onPlayerMove(TabListListener.java:36) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[Paper-latest.jar:git-Paper-409]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[Paper-latest.jar:git-Paper-409]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Paper-latest.jar:git-Paper-409]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:369) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:180) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:170) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:66) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:253) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:130) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[Paper-latest.jar:git-Paper-409]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[Paper-latest.jar:git-Paper-409]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: me.TechXcrafter.UltraPermissions.UltraPermissions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[Paper-latest.jar:git-Paper-409]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper-latest.jar:git-Paper-409]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	... 24 more`

**Comment by user127001** [comment]
Updates comment from UltraPermissions dev (11.04):
"All Plugins hooking into Uperms will have to be updated"

**Comment by linuxhus** [comment]
hi is there a dev version ?

**Comment by Zrips** [comment]
Will be updated with next version of CMI
