### ISSUE TITLE
CMI&BungeeCord  issue

### ISSUE THREAD

**Issue by shaokeyibb** [Zrips/CMI#1047]
**When I try to use TAB completion command，BungeeCord will throw an exception and kick me out**
（Some sentences use Google Translate,sorry!）

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####
```[22:47:01 ERROR]: [Dar_Worl] <-> ServerConnector [登录服] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
0d01
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:152) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [BungeeCord.jar:git:BungeeCord-Bootstrap:1.13-SNAPSHOT:367a127:222]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```

---

**Cmi Version (using`/cmi version`):8.0.21.4** 

**Server Type (Spigot/Paperspigot/etc):Paper** 

**Server Version (using `/ver`):git-Paper-1584 (MC: 1.12.2) & HexaCord**

**Comment by Zrips** [comment]
Should be ok with latest builds
