### ISSUE TITLE
Broken /spawnmob horse:skeleton ps:skeleton in 1.12.2

### ISSUE THREAD

**Issue by quorn23** [Zrips/CMI#1090]
**Description of issue or feature request:**

Tried the example from the spigot page to spawn a horse with Skeleton on it, error below

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[23:50:24 INFO]: quorn23 issued server command: /spawnmob horse:skeleton ps:skeleton
[23:50:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.UnsupportedOperationException: Not supported.
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftAbstractHorse.setVariant(CraftAbstractHorse.java:26) ~[spigot.jar:git-Spigot-2cf50f0-2b93d83]
        at com.Zrips.CMI.commands.list.spawnmob.proccessMob(spawnmob.java:766) ~[?:?]
        at com.Zrips.CMI.commands.list.spawnmob.perform(spawnmob.java:286) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2cf50f0-2b93d83]
        ... 15 more
```

--

**Cmi Version (using`/cmi version`):** 

8.1.0.0

**Server Type (Spigot/Paperspigot/etc):** 

Spigot

**Server Version (using `/ver`):** 

1.12.2-R0.1-SNAPSHOT

**Comment by LogGits** [comment]
Ok apparently this isnt a bug. You should be using `SKELETON_HORSE`, checkout https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html for more info.

**Comment by LogGits** [comment]
Woops accidentally closed,@Zrips this should probably be caught to see if the entity exists before attempting to spawn it.

**Comment by Zrips** [comment]
Will add exception catcher, but as of 1.12 version SkeletonHorse entity type should be used instead of deprecated horse:skeleton
