### ISSUE TITLE
bug/ Custom Alias has vector error 1.13.2

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1093]
Using custom alias /regionremove NAME, which works in 1.12.2, spigot out exception error in 1.13.2
"region removemember %worldguard_region_name% $1" == regionremove bobtheplayer

---

**ERROR:**
Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.23.0
org.bukkit.event.EventException: null

```
[23:09:10 INFO]: mrfloris issued server command: /regionremove vloop
[23:09:10 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.23.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1640) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.BukkitUtil.toVector(Lorg/bukkit/Location;)Lcom/sk89q/worldedit/Vector;
	at com.extendedclip.papi.expansion.worldguard.WorldGuardExpansion.getRegion(WorldGuardExpansion.java:122) ~[?:?]
	at com.extendedclip.papi.expansion.worldguard.WorldGuardExpansion.onPlaceholderRequest(WorldGuardExpansion.java:64) ~[?:?]
	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:237) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:377) ~[?:?]
	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:362) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:380) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
	at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:84) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor490.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2-java11.jar:git-Spigot-a1f2566-8cd538e]
	... 16 more
[23:09:52 INFO]:
```

**COMMAND:**
```
/cmi aliaseditor used to create : /regionremove NAME for worldguard region shortcut
region removemember %worldguard_region_name% $1
```

---

**Cmi Version (using`/cmi version`):** 
>about cmi
[23:14:52 INFO]: CMI version 8.0.23.0
[23:14:52 INFO]: Powerfull server management tool
[23:14:52 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[23:14:52 INFO]: Author: Zrips
>

**Server Type (Spigot/Paperspigot/etc):** 
>ver
[23:15:01 INFO]: This server is running CraftBukkit version git-Spigot-a1f2566-8cd538e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[23:15:01 INFO]: Checking version, please wait...
[23:15:01 INFO]: You are 1 version(s) behind
>

**Server Version (using `/ver`):** 
>ver
[23:15:01 INFO]: This server is running CraftBukkit version git-Spigot-a1f2566-8cd538e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[23:15:01 INFO]: Checking version, please wait...
[23:15:01 INFO]: You are 1 version(s) behind
>

**Relevant plugins (Delete if this isn't needed):** 
>about worldguard
[23:15:25 INFO]: WorldGuard version 7.0.0-SNAPSHOT;0dc5781
>about placeholderapi
[23:15:28 INFO]: PlaceholderAPI version 2.9.2
[23:15:28 INFO]: An awesome placeholder provider!
[23:15:28 INFO]: Author: [extended_clip]
>

**Comment by LogGits** [comment]
Yeah this Worldguard update broke all compatible plugins. Can you try using this for now and let me know how it goes:
https://dev.bukkit.org/projects/worldguard/files/2621118

**Comment by mrfloris** [comment]
This combination currently works for us, we do not get these errors at the moment;
```>about
[04:36:53 INFO]: This server is running CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[04:36:53 INFO]: Checking version, please wait...
[04:36:53 INFO]: You are 8 version(s) behind
>about worldguard
[04:36:55 INFO]: WorldGuard version 7.0.0-SNAPSHOT;1763-80aec37
>about worldedit
[04:36:57 INFO]: WorldEdit version 7.0.0-SNAPSHOT;3963-700e41b
>about cmi
[04:36:59 INFO]: CMI version 8.2.6.0
[04:36:59 INFO]: Powerful server management tool
[04:36:59 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[04:36:59 INFO]: Author: Zrips
>```

**Comment by mrfloris** [comment]
I think this one can be closed, because at least for me I no longer have these issues.

**Comment by mrfloris** [comment]
Welp, this keeps breaking now, I guess the papi ecloud package author has to update it to better support it. Not cmi related, i assume. More a placeholder api thing (which will say it's the worldguard package for papi author that needs to sort this)...

so closing this.
