### ISSUE TITLE
/tp /home /back /dback broken

### ISSUE THREAD

**Issue by thomasdaley2** [Zrips/CMI#1103]
**Description of issue or feature request:**

---
When using 8.2.0.1 back tp home etc aren't working (internal error) downgrade back to 8.0.*.* Fixed it.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
 [14:29:35 INFO]: BusinessSkeleton issued server command: /back
> [14:29:35 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.2.0.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [server.jar:git-Spigot-f6a273b-8ab46ff]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [server.jar:git-Spigot-f6a273b-8ab46ff]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.isPassable()Z
at com.Zrips.CMI.Modules.tp.Teleportations.isEmpty(Teleportations.java:750) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:819) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:603) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:305) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:294) ~[?:?]
at com.Zrips.CMI.commands.list.back.perform(back.java:48) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-f6a273b-8ab46ff]
... 15 more
``
---

**Cmi Version (using`/cmi version`):** 
2.8.0.1 & 2.8.0.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.13.1

**Comment by LogGits** [comment]
Thanks for the report. I highly recommend updating ur server to 1.13.2. 1.13.1 has a bunch of native issues in it. 1.13.2 build would also fix this issue.

**Comment by Zrips** [comment]
Will be fixed with next build.
