### ISSUE TITLE
WARN java.sql.SQLException:

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#111]
```
[Server] WARN java.sql.SQLException: No value specified for parameter 3 09.03 03:28:05
[Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) 09.03 03:28:05
[Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898) 09.03 03:28:05
[Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887) 09.03 03:28:05 
[Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861) 09.03 03:28:05
[Server] WARN at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2211) 09.03 03:28:05
[Server] WARN at com.mysql.jdbc.PreparedStatement.addBatch(PreparedStatement.java:898) 09.03 03:28:05
[Server] WARN at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:466) 09.03 03:28:05
[Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:223) 09.03 03:28:05
[Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:202) 09.03 03:28:05
[Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) 09.03 03:28:05
[Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) 09.03 03:28:05
[Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) 09.03 03:28:05
[Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 09.03 03:28:05
[Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 09.03 03:28:05
[Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zrips** [comment]
Try new build and inform if issue persists, for now will close this ticket
