### ISSUE TITLE
Aliases doesn´t work....

### ISSUE THREAD

**Issue by Skyfighter1** [Zrips/CMI#1119]
**Description of issue or feature request:**
Aliases doesn´t work....

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## 30.11 16:32:58 [Server] INFO _Supreme_Hero_ issued server command: /afk
30.11 16:32:58 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.23.0
30.11 16:32:58 [Server] INFO org.bukkit.event.EventException: null
30.11 16:32:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
30.11 16:32:58 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-642f6d2-57ab4cf]
30.11 16:32:58 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_191] ##
####################


---

**Cmi Version (using`/cmi version`):** 
8.0.23.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.12.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by DeadIntermediate** [comment]
Have you tried using the new version?

**Comment by Skyfighter1** [comment]
Yes now all things works
