### ISSUE TITLE
CMI 2.1.0 Spawner error

### ISSUE THREAD

**Issue by AKATONYEXILE** [Zrips/CMI#1127]
CMI update 2.1.0 is throwing errors when the /cmi spawner <any> is used.
```
[18:33:57 INFO]: AKATONYMC issued server command: /cmi spawner cow
[18:33:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.2.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.commands.list.spawner.perform(spawner.java:53) ~[CMI8.2.1.0.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[CMI8.2.1.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        ... 15 more
[18:34:04 INFO]: AKATONYMC issued server command: /cmi spawner armor_stand
[18:34:04 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.2.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.commands.list.spawner.perform(spawner.java:53) ~[CMI8.2.1.0.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[CMI8.2.1.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        ... 15 more
[18:34:09 INFO]: AKATONYMC issued server command: /cmi spawner cod
[18:34:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.2.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-282dad1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.commands.list.spawner.perform(spawner.java:53) ~[CMI8.2.1.0.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[CMI8.2.1.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-a1f2566-282dad1]
        ... 15 more
>version
[18:34:21 INFO]: This server is running CraftBukkit version git-Spigot-a1f2566-282dad1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:34:21 INFO]: Checking version, please wait...
[18:34:22 INFO]: You are 1 version(s) behind
>cmi version
[18:34:25 INFO]: ? [playerDisplayName] ?
[18:34:25 INFO]: CMI plugin version: 8.2.1.0
[18:34:25 INFO]: Server version: Spigot 1.13.2-R0.1-SNAPSHOT
[18:34:25 INFO]: Vault version: 1.6.11(+)
[18:34:25 INFO]: ? [playerDisplayName] ?
```

**CMI plugin version: 8.2.1.0** 

**Spigot 1.13.2-R0.1-SNAPSHOT:**

**Comment by AKATONYEXILE** [comment]
This issue happens if you click into air. Not if you click on a block.

**Comment by Zrips** [comment]
Will be fixed with next build
