### ISSUE TITLE
Error No Hit and no pick from chest.

### ISSUE THREAD

**Issue by Saldhfasodif** [Zrips/CMI#1141]
**Description of issue or feature request:**
When try to hit someone or pick any weapon enchanted appears this error and the action is cancelled. I can't pick anything in chest or put if is a enchanted weapon or tool and sometimes I can't hit another player.

**ERROR:**
```
[Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.2.1.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:191) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1200) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:18) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.CmiItems.ItemManager$CMIMaterial.get(ItemManager.java:2245) ~[?:?]
	at com.Zrips.CMI.Modules.Afk.AfkListener.PlayerInteractEvent(AfkListener.java:234) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot_1_8_8.jar:git-Spigot-db6de12-18fbb24]
	... 18 more
```

**Cmi Version:** 8.2.1.0

**Server Type:** Spigot 

**Server Version:** 1.8.8-R0.1-SNAPSHOT

**Comment by LogGits** [comment]
Do you still have this issue on `8.2.2.0`?

**Comment by Saldhfasodif** [comment]
Yes... the same issue.

**Comment by Saldhfasodif** [comment]
This error maybe is another plugin picking the Player Interact Event. I have another plugin new and do the same error and obviously CMI too!. In the first Report is a bedwars plugin and now is a custom guns plugin.

Could it be that CMI did not stop using the PlayerInteractEvent to other Plugins?  It's a possibility.

**Comment by Zrips** [comment]
Should be fixed with next build.
