### ISSUE TITLE
huge issues with /home, /back, and /tpa

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1147]
Latest nightly of Spigot, latest 8.2 builds of CMI, all have these errors on /home, /tpa, /back, and other teleports. Unless the person is rock solid on a full block, and not in the water, slightly moved, or near a string, or a snowslab, anything.. it will not teleport.
```
[04:54:09 INFO]: TidalDawn issued server command: /back
[04:54:09 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.2.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_13_R2.MovingObjectPosition.a()Lnet/minecraft/server/v1_13_R2/BlockPosition;
        at com.Zrips.CMI.NBT.v1_13_R2.getBlockLookingAt(v1_13_R2.java:1881) ~[?:?]
        at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:357) ~[?:?]
        at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:346) ~[?:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:855) ~[?:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:616) ~[?:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:305) ~[?:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:294) ~[?:?]
        at com.Zrips.CMI.commands.list.back.perform(back.java:48) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2-java11.jar:git-Spigot-e769fe4-5f5a676]
        ... 15 more```

**Comment by mrfloris** [comment]
Thank you for marking this as a bug report, I've tried to downgrade like all the way to 8.2.0.0 and still have this issue. I am scared if I go any lower that i cause database corruption or whatever. 

Players can go to a new block of cobble, type: /sethome test
and type /home test, and it errors. Even though it's like completely safe, no obstruction etc.

**Comment by mrfloris** [comment]
Is there anything i can do in the meantime, run a patch or a custom build, or change data in the .db file?

**Comment by Zrips** [comment]
@mrfloris 
Question would be which mc version are you running exactly?

**Comment by mrfloris** [comment]
Nice to hear from you, hopefully we can get this sorted out. 

I am on 1.13.2 Spigot;

>about
[15:48:03 INFO]: This server is running CraftBukkit version git-Spigot-e769fe4-5f5a676 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[15:48:03 INFO]: Checking version, please wait...
[15:48:04 INFO]: You are 2 version(s) behind

**Comment by Zrips** [comment]
Let me test it out and will come back with what i found. But it should not be issue with protocolSupport

**Comment by mrfloris** [comment]
Anything I can do or run to help you debug this more? Want a dump of some /home entries from the sqlite db fields? Some command I can run? It happens with any 8.2.x build, I haven't tried 8.1 yet, but something changed in the last week. we haven't had issues until suddenly yesterday, and it's quite the gameplay-killer.

So.. THANK YOU for replying, and THANK YOU for looking into it. I hope you can figure out what's up.

**Comment by Zrips** [comment]
Yea, for some reason they renamed method from **a()** to **getBlockPosition()** in latest builds, will add fix for it and it should work with today's update.

**Comment by mrfloris** [comment]
Insert 7000x thank you here.. I can't wait to test it.

**Comment by Zrips** [comment]
New version should come out in next hour or two. But all works as expected now with newest version.
