### ISSUE TITLE
Error with Citizens plugin

### ISSUE THREAD

**Issue by minhthanh920** [Zrips/CMI#1158]
When i hitting citizens by bow ,it will be give me below error

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Could not pass event ProjectileHitEvent to CMI v8.2.2.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1589]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1589]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1589]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1589]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:879) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:268) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:203) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1795) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1765) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1572) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1589]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1589]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.Vanish.VanishListener.EntityDamageByEntityEvent(VanishListener.java:81) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor677.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1589]
	... 16 more
```

---

**Cmi Version (using`/cmi version`):** 
8.2.2.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.12.2
**Server Version (using `/ver`):** 
git-Paper-1589
**Relevant plugins (Delete if this isn't needed):** 
Citizens

**Comment by x1p** [comment]
Confirmed: I have this too with snowballs.

**Comment by Zrips** [comment]
Should be ok with next build.
