### ISSUE TITLE
Could not pass event EntityTargetLivingEntityEvent to CMI v8.2.2.0

### ISSUE THREAD

**Issue by winnyok2042** [Zrips/CMI#1161]
```
[Server thread/ERROR]: Could not pass event EntityTargetLivingEntityEvent to CMI v8.2.2.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-475]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-475]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-475]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityInsentient.setGoalTarget(EntityInsentient.java:159) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.PathfinderGoalNearestAttackableTarget.c(PathfinderGoalNearestAttackableTarget.java:73) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:73) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:681) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityLiving.k(EntityLiving.java:2337) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityInsentient.k(EntityInsentient.java:522) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityMonster.k(EntityMonster.java:23) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityZombie.k(EntityZombie.java:219) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2134) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:260) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityMonster.tick(EntityMonster.java:27) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.EntityZombie.tick(EntityZombie.java:186) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1620) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1587) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1394) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:614) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-475]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-475]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.Vanish.VanishListener.onEntityTarget(VanishListener.java:170) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1126.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-475]
	... 24 more
```
**Cmi Version (using`/cmi version`): 8.2.2.0

**Server Type (Spigot/Paperspigot/etc): Paperspigot

**Server Version (using `/ver`):** 475

**Comment by Swede37** [comment]
I'm getting the same thing, except with Spigot

**Comment by Zrips** [comment]
Will be fixed with next update.
