### ISSUE TITLE
Generating exception while executing task 896878

### ISSUE THREAD

**Issue by iTemmy** [Zrips/CMI#1162]
**Description of issue or feature request:**
Constantly spamming console with this error, can't see anything else in console due to this error spamming.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
09.12 17:10:12 [Server] WARN [CMI] Plugin CMI v8.2.2.0 generated an exception while executing task 896878
09.12 17:10:12 [Server] INFO java.lang.NullPointerException: null
09.12 17:10:12 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.proccess(EssentialsConverter.java:168) ~[?:?]
09.12 17:10:12 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.access$0(EssentialsConverter.java:102) ~[?:?]
09.12 17:10:12 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter$1.run(EssentialsConverter.java:61) ~[?:?]
09.12 17:10:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
09.12 17:10:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
09.12 17:10:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
09.12 17:10:12 [Server] ERROR Could not pass event PlayerInteractEvent to CMI v8.2.2.0
09.12 17:10:12 [Server] INFO org.bukkit.event.EventException: null
09.12 17:10:12 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPressurePlateBinary.e(BlockPressurePlateBinary.java:75) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:96) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:89) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.checkBlockCollisions(Entity.java:1015) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.Entity.move(Entity.java:596) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.a(EntityLiving.java:1886) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.a(EntityHuman.java:1454) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.a(EntityHumanNPC.java:120) ~[?:?]
09.12 17:10:12 [Server] INFO at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:150) ~[?:?]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1015) ~[?:?]
09.12 17:10:12 [Server] INFO at net.citizensnpcs.util.NMS.tick(NMS.java:290) ~[?:?]
09.12 17:10:12 [Server] INFO at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
09.12 17:10:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:10:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
09.12 17:10:12 [Server] INFO Caused by: java.lang.NullPointerException
```

---

**Cmi Version (using`/cmi version`):** 
8.2.2.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper 1593 mc 1.12.2

**Comment by Zrips** [comment]
Will be fixed with next build.
