### ISSUE TITLE
unable to import anything other than warps from essentials

### ISSUE THREAD

**Issue by iTemmy** [Zrips/CMI#1163]
**Description of issue or feature request:**
I try to import the essentials data from console, can import the warps from essentials fine though.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

```
09.12 17:23:53 [Server] WARN [CMI] Plugin CMI v8.2.2.0 generated an exception while executing task 1063446
09.12 17:23:53 [Server] INFO java.lang.NullPointerException: null
09.12 17:23:53 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.proccess(EssentialsConverter.java:168) ~[?:?]
09.12 17:23:53 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.access$0(EssentialsConverter.java:102) ~[?:?]
09.12 17:23:53 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter$1.run(EssentialsConverter.java:61) ~[?:?]
09.12 17:23:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:23:53 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:23:53 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:23:53 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
09.12 17:23:53 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
09.12 17:23:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
09.12 17:24:49 [Server] WARN [CMI] Plugin CMI v8.2.2.0 generated an exception while executing task 1073021
09.12 17:24:49 [Server] INFO java.lang.NullPointerException: null
09.12 17:24:49 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.proccess(EssentialsConverter.java:168) ~[?:?]
09.12 17:24:49 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.access$0(EssentialsConverter.java:102) ~[?:?]
09.12 17:24:49 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter$1.run(EssentialsConverter.java:61) ~[?:?]
09.12 17:24:49 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:24:49 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:24:49 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:24:49 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
09.12 17:24:49 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
09.12 17:24:49 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
09.12 17:25:33 [Server] WARN [CMI] Plugin CMI v8.2.2.0 generated an exception while executing task 1080313
09.12 17:25:33 [Server] INFO java.lang.NullPointerException: null
09.12 17:25:33 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.proccess(EssentialsConverter.java:168) ~[?:?]
09.12 17:25:33 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.access$0(EssentialsConverter.java:102) ~[?:?]
09.12 17:25:33 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter$1.run(EssentialsConverter.java:61) ~[?:?]
09.12 17:25:33 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:25:33 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:25:33 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:25:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
09.12 17:25:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
09.12 17:25:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
09.12 17:37:19 [Server] WARN [CMI] Plugin CMI v8.2.2.0 generated an exception while executing task 134983
09.12 17:37:19 [Server] INFO java.lang.NullPointerException: null
09.12 17:37:19 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.proccess(EssentialsConverter.java:168) ~[?:?]
09.12 17:37:19 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.access$0(EssentialsConverter.java:102) ~[?:?]
09.12 17:37:19 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter$1.run(EssentialsConverter.java:61) ~[?:?]
09.12 17:37:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:37:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:37:19 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:37:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
09.12 17:37:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
09.12 17:37:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
09.12 17:38:19 [Server] WARN [CMI] Plugin CMI v8.2.2.0 generated an exception while executing task 142950
09.12 17:38:19 [Server] INFO java.lang.NullPointerException: null
09.12 17:38:19 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.proccess(EssentialsConverter.java:168) ~[?:?]
09.12 17:38:19 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter.access$0(EssentialsConverter.java:102) ~[?:?]
09.12 17:38:19 [Server] INFO at com.Zrips.CMI.utils.EssentialsConverter$1.run(EssentialsConverter.java:61) ~[?:?]
09.12 17:38:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:38:19 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:38:19 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1593]
09.12 17:38:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
09.12 17:38:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
09.12 17:38:19 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

---

**Cmi Version (using`/cmi version`):** 
8.2.2.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
paper(1593) 1.12.2

**Comment by 1425115471** [comment]
So do I.

**Comment by JokerLiuPro** [comment]
same problem in 
CMI 8.2.4.0
Paperspigot
paper(451) 1.13.2
