### ISSUE TITLE
Skins not working on Bungeecord

### ISSUE THREAD

**Issue by Zenya4** [Zrips/CMI#1165]
`/skin` does not work on Bungeecord (skins do not show).

Using `/skin update` also generates this error in log. Using CMI 8.2.2.0
`[18:32:44 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.2.2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper%201.13.2.jar:git-Paper-455]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[Paper%201.13.2.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1798) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[Paper%201.13.2.jar:git-Paper-455]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[Paper%201.13.2.jar:git-Paper-455]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[Paper%201.13.2.jar:git-Paper-455]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:65) ~[?:?]
	at com.Zrips.CMI.commands.list.skin.perform(skin.java:113) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper%201.13.2.jar:git-Paper-455]
	... 15 more
`

**Comment by minhthanh920** [comment]
me too

**Comment by Zrips** [comment]
Its known "issue" as bungee cord requires completely different skin handling then regular servers do. So for now only regular servers support this feature.
