### ISSUE TITLE
Ride error

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#1179]
**Description of issue or feature request:** error when trying to /ride an npc from citizens.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
ERROR 15/12/2018 16:09:02
16:09:02null
Console 15/12/2018 16:09:02
16:09:02org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.2.4.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-475]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-475]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-475]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-475]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:261) ~[?:?]
at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:239) ~[?:?]
at com.Zrips.CMI.Locale.Language.getMessage(Language.java:106) ~[?:?]
at com.Zrips.CMI.CMI.info(CMI.java:1854) ~[?:?]
at com.Zrips.CMI.commands.list.ride.perform(ride.java:84) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-475]
... 15 more
```
---

**Cmi Version (using`/cmi version`):** 8.2.4.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** build 470

**Comment by Zrips** [comment]
Will be fixed with next build
