### ISSUE TITLE
ProjectileHitEvent error

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#1180]
**Description of issue or feature request:** Random error appeared in console

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
ERROR 15/12/2018 16:14:33
16:14:33Could not pass event ProjectileHitEvent to CMI v8.2.4.0
Console 15/12/2018 16:14:33
16:14:33org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-475]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-475]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-475]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-475]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:988) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.EntityProjectile.tick(EntityProjectile.java:163) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1620) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.World.g(World.java:1587) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1394) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:614) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-475]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-475]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.Modules.Vanish.VanishListener.EntityDamageByEntityEvent(VanishListener.java:81) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor938.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-475]
... 14 more
```
---

**Cmi Version (using`/cmi version`):** 8.2.4.0

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** build 470 1.13.2

**Comment by Zrips** [comment]
Will be fixed with next build
