### ISSUE TITLE
Essentials import failing

### ISSUE THREAD

**Issue by kennans** [Zrips/CMI#1182]
Import of essentials data gives this error, I've tried console and ingame, I've tried importing data one by one and none of it worked.
```
[11:49:23 WARN]: [CMI] Plugin CMI v8.2.4.0 generated an exception while executing task 357
java.lang.NullPointerException: null
        at com.Zrips.CMI.utils.EssentialsConverter.proccess(EssentialsConverter.java:138) ~[?:?]
        at com.Zrips.CMI.utils.EssentialsConverter.access$0(EssentialsConverter.java:102) ~[?:?]
        at com.Zrips.CMI.utils.EssentialsConverter$1.run(EssentialsConverter.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[towny.jar:git-Spigot-140f654-b446cb5]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [towny.jar:git-Spigot-140f654-b446cb5]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Cmi Version (using`/cmi version`):** 
[16:16:03 INFO]: --------------------------------------------------
[16:16:03 INFO]: CMI plugin version: 8.2.4.0
[16:16:03 INFO]: Server version: Spigot 1.13.2-R0.1-SNAPSHOT
[16:16:03 INFO]: Vault version: 1.6.11(+)
[16:16:03 INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
[16:16:28 INFO]: This server is running CraftBukkit version git-Spigot-140f654-b446cb5 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:16:28 INFO]: Checking version, please wait...
[16:16:28 INFO]: You are running the latest version

**Comment by Zrips** [comment]
Will be fixed with next build
