### ISSUE TITLE
Condense error 1.13

### ISSUE THREAD

**Issue by ArathiaMC** [Zrips/CMI#1228]
CMI VERSION: 8.2.8.0
Paperspigot 474

Condense error: https://pastebin.com/nr5306MB

**Comment by Zrips** [comment]
Its failing while checking recipe. Its not a CMI issue in particular as its failing on Bukkit code level. Would suggest to check your custom recipes as one of them seems to be faulty. Will add some error catchers to allow code to be continued even if it fails to check some particular recipes.

**Comment by ArathiaMC** [comment]
I have no custom recipes whatsoever, though.

**Comment by ArathiaMC** [comment]
My recipes.yml is blank like default

**Comment by ArathiaMC** [comment]
@Zrips 
With latest version I now get this when trying to condense gold ingots


[08:41:13 INFO]: [CMI] Failed to check recipe for GOLD_INGOT
[08:41:13 WARN]: java.lang.IllegalArgumentException: Must have at least one choice
[08:41:13 WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[08:41:13 WARN]: at org.bukkit.inventory.RecipeChoice$MaterialChoice.<init>(RecipeChoice.java:39)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.FurnaceRecipe.toBukkitRecipe(FurnaceRecipe.java:80)
[08:41:13 WARN]: at org.bukkit.craftbukkit.v1_13_R2.inventory.RecipeIterator.next(RecipeIterator.java:22)
[08:41:13 WARN]: at org.bukkit.craftbukkit.v1_13_R2.inventory.RecipeIterator.next(RecipeIterator.java:10)
[08:41:13 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getRecipesFor(CraftServer.java:1224)
[08:41:13 WARN]: at com.Zrips.CMI.commands.list.condense.getPosibleCondense(condense.java:125)
[08:41:13 WARN]: at com.Zrips.CMI.commands.list.condense.condenseStack(condense.java:75)
[08:41:13 WARN]: at com.Zrips.CMI.commands.list.condense.perform(condense.java:55)
[08:41:13 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248)
[08:41:13 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[08:41:13 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[08:41:13 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1792)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1595)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[08:41:13 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08:41:13 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[08:41:13 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[08:41:13 WARN]: at java.lang.Thread.run(Thread.java:748)
