### ISSUE TITLE
[Bug?] Can't use [i] in /cmi msg

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1244]
latest cmi from today and spigot from 2 weeks ago (im behind on spigot, i hope to fix that soon!)

```[20:32:45 INFO]: mrfloris issued server command: /msg cite hold item in hand and type literally [i] it will get replaced
[20:32:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.3.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.utils.RawMessage.addItem(RawMessage.java:392) ~[?:?]
        at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.convertHoverOver(ChatFormatManager.java:440) ~[?:?]
        at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:267) ~[?:?]
        at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:198) ~[?:?]
        at com.Zrips.CMI.commands.list.msg.perform(msg.java:96) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2-java11.jar:git-Spigot-140f654-b446cb5]
        ... 15 more```

doing
/cmi msg playername hi use [i] to blah blah
* internal error, check console

**Comment by Zrips** [comment]
What type of item you tried to show? Will add some extra checks, but it does work for me, so its item specific issue and would be nice to know which one was that.

**Comment by mrfloris** [comment]
> What type of item you tried to show? Will add some extra checks, but it does work for me, so its item specific issue and would be nice to know which one was that.

In this case i was telling them how to use the [i] by holding nothing in my hand and giving them a msg like

"you can display what you are holding by using [i]" 

Normally in global chat this would just visually display the [i] for example, doing it with a /cmi msg, it gives internal error

**Comment by Zrips** [comment]
Och ok, will prevent changing [i] if you are not holding item.
