### ISSUE TITLE
java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.BlockData.g

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1253]
**Description of issue or feature request:**

---

**Cmi Version (using`/cmi version`): CMI8.3.2.0.jar

**Server Type (Spigot/Paperspigot/etc): Spigot

**Server Version (using `/ver`): CraftBukkit version git-Spigot-8173d06-7560d3b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** 
[14:31:28] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.BlockData.g(net.minecraft.server.v1_13_R2.WorldServer, net.minecraft.server.v1_13_R2.BlockPosition)
[14:31:28] [Server thread/WARN]: 	at java.lang.Class.getMethod(Class.java:1786)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_13_R2.getBlockHitBox(v1_13_R2.java:1933)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.<init>(CMIHitBox.java:32)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getHeightAtLocation(CMIHitBox.java:76)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:887)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:613)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:310)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.home.perform(home.java:122)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248)
[14:31:28] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:31:28] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[14:31:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[14:31:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:31:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728)
[14:31:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[14:31:28] [Server thread/WARN]: java.lang.UnsupportedOperationException: No bounds for empty shape.
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.VoxelShape.getBoundingBox(SourceFile:44)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_13_R2.getBlockHitBox(v1_13_R2.java:1927)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.<init>(CMIHitBox.java:32)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getHeightAtLocation(CMIHitBox.java:76)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:887)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:613)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:310)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.home.perform(home.java:122)
[14:31:28] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248)
[14:31:28] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:31:28] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[14:31:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[14:31:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:31:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830)
[14:31:28] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728)
[14:31:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[14:31:33] [Server thread/INFO]: [Stew] Cauldrons have been saved to file!
[14:31:55] [Server thread/INFO]: King__K007 issued server command: /spawn
[14:33:44] [Server thread/INFO]: MagnaTeiwaz issued server command: /home Home
[14:33:44] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.BlockData.g(net.minecraft.server.v1_13_R2.WorldServer, net.minecraft.server.v1_13_R2.BlockPosition)
[14:33:44] [Server thread/WARN]: 	at java.lang.Class.getMethod(Class.java:1786)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_13_R2.getBlockHitBox(v1_13_R2.java:1933)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.<init>(CMIHitBox.java:32)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getHeightAtLocation(CMIHitBox.java:76)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:887)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:613)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:310)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.home.perform(home.java:122)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248)
[14:33:44] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:33:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[14:33:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[14:33:44] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:33:44] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728)
[14:33:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[14:33:44] [Server thread/WARN]: java.lang.UnsupportedOperationException: No bounds for empty shape.
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.VoxelShape.getBoundingBox(SourceFile:44)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_13_R2.getBlockHitBox(v1_13_R2.java:1927)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.<init>(CMIHitBox.java:32)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getHeightAtLocation(CMIHitBox.java:76)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:887)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:613)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:310)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.home.perform(home.java:122)
[14:33:44] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248)
[14:33:44] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:33:44] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[14:33:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1641)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[14:33:44] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:33:44] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:895)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:830)
[14:33:44] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728)
[14:33:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Zrips** [comment]
Will be fixed with next update, today.
