### ISSUE TITLE
[Bug] Warning when I enable AFK StopPlayTime

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1259]
**Description of issue or feature request:**
---
When I enable the new feature to stop playtime count when a player goes to afk mode, the console spams the warning message shown under. When I set the feature to false everything works fine.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:12:35] [Craft Scheduler Thread - 3/WARN]: [CMI] Plugin CMI v8.3.3.0 generated an exception while executing task 315232
java.lang.IllegalArgumentException: Age must be at least 1 tick
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftEntity.setTicksLived(CraftEntity.java:511) ~[patched_1.13.2.jar:git-Paper-493]
	at com.Zrips.CMI.Modules.Afk.AfkManager$2$1.run(AfkManager.java:368) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-493]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-493]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-493]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```YAML
StopPlayTime: true
```

---

**Cmi Version (using`/cmi version`):** 8.3.3.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper(493) 1.13.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be ok with latest builds.
