### ISSUE TITLE
Error - Cannot pass EntityDamageByEntityEvent

### ISSUE THREAD

**Issue by Swede37** [Zrips/CMI#1269]
Console warnings-not sure what it effects or exactly what triggered it?

####################
##
`
[15:24:37] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to CMI v8.3.3.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:101) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:757) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:656) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:789) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1445) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:879) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:967) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:792) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:625) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:152) [Citizens-2.0.24-b1605.jar:?]
	at net.minecraft.server.v1_13_R2.EntityInsentient.B(EntityInsentient.java:1221) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityPhantom$i.e(EntityPhantom.java:285) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(SourceFile:129) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:659) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2253) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:510) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityPhantom.movementTick(EntityPhantom.java:110) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2097) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:248) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.EntityPhantom.tick(EntityPhantom.java:81) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1326) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.World.g(World.java:1293) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1127) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerCombatEvent(PlayerListeners.java:495) ~[CMI8.3.3.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-9dc5658]
	... 32 more
`##
####################
```
---


**CMI plugin version: 8.3.3.0**
08.01 15:36:10 [Server] INFO Server version: Spigot 1.13.2-R0.1-SNAPSHOT
08.01 15:36:10 [Server] INFO Vault version: 1.7.1-b91(CMIEInjector)

**Server Type **Spigot** 

**Server Version **CraftBukkit version git-Spigot-f56e2e7-9dc5658 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**
**

**Comment by Zrips** [comment]
Will be fixed with next build
