### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#127]
Updated to the latest CMI. Receiving this error

```
13.03 22:17:23 [Server] WARN java.sql.SQLException: Can't call commit when autocommit=true 
13.03 22:17:23 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:869)
13.03 22:17:23 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:865)
13.03 22:17:23 [Server] WARN at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1537)
13.03 22:17:23 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBConnection.commit(DBConnection.java:54) 
13.03 22:17:23 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:576)
13.03 22:17:23 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:235)
13.03 22:17:23 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:202)
13.03 22:17:23 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
13.03 22:17:23 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
13.03 22:17:23 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
13.03 22:17:23 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13.03 22:17:23 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13.03 22:17:23 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

/afk also doesn't seem to be working (may have caused this error) since I noticed it after i ran /afk.

**Comment by Zrips** [comment]
Which exactly version of CMI is this?

**Comment by Ew9304** [comment]
I had this error too, but seems to have been fixed in the latest CMI 

You sure you have the latest version :O
