### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by ArathiaMC** [Zrips/CMI#1271]
####################
[12:26:06 INFO]: Draconios issued server command: /recipe chest
[12:26:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.3.3.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-498]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-498]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1790) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1598) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.2.jar:git-Paper-498]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-498]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-498]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NullPointerException
at org.bukkit.inventory.FurnaceRecipe.getInput(FurnaceRecipe.java:117) ~[patched_1.13.2.jar:git-Paper-498]
at com.Zrips.CMI.Modules.Recipes.RecipeManager.getIngredientsList(RecipeManager.java:539) ~[?:?]
at com.Zrips.CMI.Modules.CmiItems.CMIItemStack.getRecipesFrom(CMIItemStack.java:514) ~[?:?]
at com.Zrips.CMI.commands.list.recipe.perform(recipe.java:78) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:248) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-498]
... 15 more

CMI 8.3.4.0 (latest)

PaperSpigot 498 (latest)

This error happens whenever someone does /recipe
Running no custom recipes either. The recipe.yml is blank.

**Comment by Zrips** [comment]
In general this originates not in CMI but in org.bukkit.inventory.FurnaceRecipe.getInput method, will add some extra checks, but this should run correctly with latest MC versions.

**Comment by ArathiaMC** [comment]
@Zrips 

I am still getting the same errors.
CMI version: 8.3.7.0
Paperspigot: Paper-501 (MC 1.13.2.)
