### ISSUE TITLE
MySQL Error on first start

### ISSUE THREAD

**Issue by Seeroh** [Zrips/CMI#1306]
CMI doesn't create the `users` table. (Also, typo. Console says `[CMI] Creating culumn etcetcetc`, when it should say `[CMI] Creating column etcetcetc`)

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/vtR2XKJk

[05:21:29] [Server thread/INFO]: [CMI] Creating culumn |ALTER TABLE `users` ADD COLUMN `player_uuid` text;|
[05:21:29] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'cmi_a.users' doesn't exist
[05:21:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:21:29] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:21:29] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:21:29] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[05:21:29] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBMySQL.addCollumn(DBMySQL.java:155)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.checkDefaultUserCollumns(DBDAO.java:1362)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.setUp(DBDAO.java:461)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBMySQL.initialize(DBMySQL.java:25)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.startMysql(DBManager.java:130)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.start(DBManager.java:76)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Config.load(Config.java:637)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.Config.load(Config.java:619)
[05:21:29] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1392)
[05:21:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[05:21:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[05:21:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[05:21:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[05:21:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[05:21:29] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:607)
[05:21:29] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:569)
[05:21:29] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:430)
[05:21:29] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[05:21:29] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:785)
[05:21:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Cmi Version (using`/cmi version`):** 

8.3.7.2

**Server Type (Spigot/Paperspigot/etc):** 

Paper

**Server Version (using `/ver`):** 

Paper-492 (MC: 1.13.2)

---

For some reason, CMI isn't creating the users table (and all the columns). I actually forgot to create the database on my first start, and CMI stated that it was trying to create the users table 
```
[04:24:59] [Server thread/INFO]: [CMI] Unable to connect to the database: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
CREATE TABLE `users` (`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `player_uuid` text, `username` text, `nickname` text, `LogOutLocation` text, `DeathLocation` text, `TeleportLocation` text, `teleportToggled` boolean, `Homes` text, `LastLoginTime` bigint, `LastLogoffTime` bigint, `TotalPlayTime` bigint, `tFly` bigint, `tGod` bigint, `Glow` text, `Ips` text, `Cuffed` boolean, `AlertUntil` bigint, `AlertReason` text, `JoinedCounter` boolean, `LockedIps` text, `pTime` bigint, `Kits` text, `Charges` text, `Cooldowns` longtext, `Balance` double, `Notes` text, `Rank` text, `TagSound` boolean, `SignShiftEdit` boolean, `Spy` boolean, `CommandSpy` boolean, `BannedUntil` bigint, `BannedAt` bigint, `BannedBy` text, `BanReason` text, `Ignores` text, `Vanish` text, `Economy` text, `Mail` text, `FlightCharge` double, `UserMeta` text, `Flying` boolean, `Votifier` int, `Jail` text, `JailedUntil` bigint, `FakeAccount` boolean, `PlaytimeOptimized` bigint, `flightChargeEnabled` boolean, `noPayToggled` boolean, `JailReason` text, `Skin` text, `SignSpy` boolean, `Collision` boolean, `NamePrefix` text, `NameSuffix` text, `Warnings` text, `msgToggle` boolean);
[04:24:59] [Server thread/INFO]: [CMI] Unable to connect to the database: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
```

But after I created the database, it didn't run this SQL command, and so it threw a boatload of errors into the console (2000+ lines). I then tested this by deleting the database, and recreating it, and CMI makes the other three tables. but still throws the 2000 line error spam. I actually even deleted the config files, and replaced them with a backup from before I started the server the first time, and got the same issue.

If I run the SQL command manually, it no longer gives this error though. (I also got this error back on version 8.3.1.0, but I updated to the latest version, just to check that it wasn't already fixed.)

**Comment by Zrips** [comment]
Will post new version today which should solve this issue and correctly create database tables.
