### ISSUE TITLE
CMI 4.4.3.0 towny fix err... borked it

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#131]
Hey there, so I have not switched to CMI for my economy yet (so no cmi injector right now).

I updated to CMI 4.4.3.0 yesterday and today ALL new towns cannot put any money into their balance. I have also noticed that essentials is now having issues with the economy.

[Craft Scheduler Thread - 1934/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 170.362ms!

I am also getting this, not sure if it is related

```
[20:04:39] [Server thread/WARN]: com.palmergames.bukkit.towny.exceptions.NotRegisteredException: The resident 'UserName-Removed' is not registered.
[20:04:39] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.db.TownyDatabaseHandler.getResident(TownyDatabaseHandler.java:123)
[20:04:39] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.permissions.TownyPerms.assignPermissions(TownyPerms.java:98)
[20:04:39] [Server thread/WARN]: 	at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerChangeWorld(TownyPlayerListener.java:681)
[20:04:39] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1003.execute(Unknown Source)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[20:04:39] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.moveToWorld(PlayerList.java:753)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:648)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:303)
[20:04:39] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners.onPlayerFirstJoin(PlayerListeners.java:604)
[20:04:39] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1316.execute(Unknown Source)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[20:04:39] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[20:04:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:175)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:65)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[20:04:39] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[20:04:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zrips** [comment]
Will do some optimizations for that long response time issue.
But cant reproduce issue with towny. Money are being deposited and withdraw from old and new towns. Is town entry being created in data base? It should look like town-[townName] with random UUID
For error, its not related but its still interesting one. Caused by player being teleported to first spawn location on his first login, but it seem to originate from Towny it self failing to find some strange user with name of "UserName-Removed", this dint originated from CMI as it seems.

**Comment by Kbryst** [comment]
I actually redacted the username in  "UserName-Removed". 

I'm not actually in town so I can't get into our MySQL, I can only get logs off the ftp. But I will note that the new towns stayed at $0 balance when the default starting is like 1750. Today with the rolled back version both towns I was monitoring are now at $1750 on their own. 


`[19:44:21] [Server thread/INFO]: NAME issued server command: /t new TOWN_NAME
[19:44:21] [pool-14-thread-1/INFO]: [Essentials] Creating empty config: /home/minecraft/server/plugins/Essentials/userdata/c8516120-3045-37d8-85fe-16556b3063a8.yml
[19:44:21] [Server thread/INFO]: [Essentials] Lag Notice - Slow Economy Response - Request took over 144.689ms!
[19:44:21] [Server thread/INFO]: [com.palmergames.bukkit.towny.log] [Global Msg] NAME created a new town called TOWN_NAME`

**Comment by Kbryst** [comment]
Small update,

I rolled back to 7.4.3.0. And it broke every town. I had to roll back to 7.4.2.0 and everything started working again. Could it be something with the balance save feature in 7.4.3.0?

**Comment by Kbryst** [comment]
So I can't update right? I'm just wondering lol

**Comment by LogGits** [comment]
This issue should be resolved. If you are still experiencing this issue please reopen another ticket.
