### ISSUE TITLE
Homes and warps are removed after restart

### ISSUE THREAD

**Issue by mab-ru** [Zrips/CMI#1351]
Homes and warps are removed after restart and /cmi reload (when player joined).

At startup:

```
[07:47:27] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "-195,86"
[07:47:27] [Server thread/WARN]: 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
[07:47:27] [Server thread/WARN]: 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[07:47:27] [Server thread/WARN]: 	at java.lang.Double.parseDouble(Double.java:538)
[07:47:27] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getLocationFromString(PlayerManager.java:1843)
[07:47:27] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1701)
[07:47:27] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1245)
[07:47:27] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1049)
[07:47:27] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:450)
[07:47:27] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1411)
[07:47:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[07:47:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[07:47:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[07:47:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[07:47:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[07:47:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[07:47:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[07:47:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[07:47:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[07:47:27] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[07:47:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```
(and more)

CMI: 8.3.9.0
Server: paperspigot(507)

**Comment by xXJustXx** [comment]
I have the same issue. But warps are working for me
