### ISSUE TITLE
[Error] Error message when players disconnect from the server

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1355]
**Description of issue or feature request:**
When players disconnect from the server an error message are shown in the console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:08:41 ERROR]: Could not pass event PlayerQuitEvent to CMI v8.3.9.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-509]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-509]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-509]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1479) ~[patched_1.13.2.jar:git-Paper-509]
        at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_13_R2.a(AbstractListenerPlayIn_v1_13_R2.java:281) ~[?:?]
        at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:358) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:153) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1124) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Containers.CMIUser.hideBossBars(CMIUser.java:1706) ~[?:?]
        at com.Zrips.CMI.Modules.Vanish.VanishListener.onQuit(VanishListener.java:273) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor796.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-509]
        ... 13 more
```
---

**Cmi Version (using`/cmi version`):** 8.3.9.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper(509) 1.13.2-R0.1-SNAPSHOT

**Comment by Baktus79** [comment]
#1352

**Comment by Zrips** [comment]
Will be fixed with next update
