### ISSUE TITLE
Critical HomeBug

### ISSUE THREAD

**Issue by xXJustXx** [Zrips/CMI#1360]
**Description of issue or feature request:**
Homes doesn't get saved after server restart. They are missing in the database!
Also I'm getting a strange bug on startup. Seems to be an issue with parsing doubles.

---
**ERROR:**
```
[15:47:10] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "-334,44"
[15:47:10] [Server thread/WARN]: 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
[15:47:10] [Server thread/WARN]: 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[15:47:10] [Server thread/WARN]: 	at java.lang.Double.parseDouble(Double.java:538)
[15:47:10] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getLocationFromString(PlayerManager.java:1843)
[15:47:10] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1701)
[15:47:10] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1245)
[15:47:10] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1049)
[15:47:10] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:450)
[15:47:10] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1411)
[15:47:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[15:47:10] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[15:47:10] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:47:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441)
[15:47:10] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355)
[15:47:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[15:47:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[15:47:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[15:47:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[15:47:10] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[15:47:10] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 8.3.9.0

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-500 (MC: 1.13.2)

**Comment by Zrips** [comment]
This will be fixed with next build.
