### ISSUE TITLE
Scan error: y out of range

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1372]
**Description of issue or feature request:**

---
Trying to execute scan.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:57:22] [Server thread/INFO]: player123 issued server command: /cmi scan id elytra r 100
[12:57:22] [Server thread/WARN]: [CMI] Task #1514 for CMI v8.3.9.2 generated an exception
java.lang.IllegalArgumentException: y out of range (expected 0-255, got 256)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[patched_1.13.2.jar:git-Paper-513]
	at org.bukkit.craftbukkit.v1_13_R2.CraftChunk.validateChunkCoordinates(CraftChunk.java:298) ~[patched_1.13.2.jar:git-Paper-513]
	at org.bukkit.craftbukkit.v1_13_R2.CraftChunk.getBlock(CraftChunk.java:73) ~[patched_1.13.2.jar:git-Paper-513]
	at com.Zrips.CMI.Modules.Scan.Scan$1.run(Scan.java:155) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-513]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-513]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-513]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-513]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-513]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-513]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.3.9.2
**Server Type (Spigot/Paperspigot/etc):** 
 Paper(513) 1.13.2-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
1.13.2 build

**Comment by Zrips** [comment]
Will get fixed with next build

**Comment by x1p** [comment]
> Fix for scan command error when y coordinate gets over 255. Basically, an issue when you are getting too high...
My server.properties.max-build-height was just default 256
