### ISSUE TITLE
Cmi unban and cmi checkban dosen't work.

### ISSUE THREAD

**Issue by Saldhfasodif** [Zrips/CMI#1380]
**Description of issue or feature request: When try to use /cmi checkban and /cmi unban [Name] not works**

The user was banned early and I can't unban him. It's weird.

**ERROR:**
```
03.02 19:10:00 [Server] INFO Saldh issued server command: /cmi checkban Mandaburras6666
03.02 19:10:00 [Server] ERROR null
03.02 19:10:00 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.3.9.4
03.02 19:10:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
03.02 19:10:00 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
03.02 19:10:00 [Server] INFO Caused by: java.lang.IllegalArgumentException: Target cannot be null
03.02 19:10:00 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftIpBanList.pardon(CraftIpBanList.java:75) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO at com.Zrips.CMI.Containers.CMIUser.unBan(CMIUser.java:1426) ~[?:?]
03.02 19:10:00 [Server] INFO at com.Zrips.CMI.commands.list.checkban.perform(checkban.java:144) ~[?:?]
03.02 19:10:00 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:249) ~[?:?]
03.02 19:10:00 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:00 [Server] INFO ... 15 more
03.02 19:10:04 [Multicraft] Waiting for log file...
03.02 19:10:25 [Server] INFO Saldh issued server command: /cmi unban Mandaburras6666
03.02 19:10:25 [Server] ERROR null
03.02 19:10:25 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.3.9.4
03.02 19:10:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
03.02 19:10:25 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
03.02 19:10:25 [Server] INFO Caused by: java.lang.IllegalArgumentException: Target cannot be null
03.02 19:10:25 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftIpBanList.pardon(CraftIpBanList.java:75) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO at com.Zrips.CMI.Containers.CMIUser.unBan(CMIUser.java:1426) ~[?:?]
03.02 19:10:25 [Server] INFO at com.Zrips.CMI.commands.list.unban.perform(unban.java:65) ~[?:?]
03.02 19:10:25 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:249) ~[?:?]
03.02 19:10:25 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot_1_12_2.jar:git-Spigot-dcd1643-e60fc34]
03.02 19:10:25 [Server] INFO ... 15 more
```
---

**Cmi Version: 8.3.9.4** 

**Server Type: Spigot** 

**Server Version: git-Spigot-dcd1643-e60fc34 (1.12.2) (last version)**

**Comment by Zrips** [comment]
Its error from same unban command, for which i will issue fix thingy. But checkban works correctly or you have not provided error log for it.
