### ISSUE TITLE
Holograms bug if in unloaded multiverse world

### ISSUE THREAD

**Issue by Endothelium** [Zrips/CMI#1397]
Hello,

When you unload a multiverse world ( to reduce server load etc...) and that world contain a hologram, holograms in the holograms.yml after the one in the non existing map will not be loaded at server start.

```
[12:32:36] [Server thread/ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
	at org.bukkit.Location.deserialize(Location.java:612) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:81) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:121) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:199) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:364) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:348) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:499) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:222) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:43) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:35) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandManager.load(InteractiveCommandManager.java:382) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.Config.reload(Config.java:2083) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.commands.list.reload.perform(reload.java:21) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252) ~[CMI8.3.10.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

For example, i have 30 holograms. I created one in the christmas map called "Santa" and it is the 10th in the hologram list, if i unload the christmas map (because it's an event map), when i restart the server holograms from 11 to 30 will not be loaded.

I dont want to delete holograms in my config or let the world loaded because it take ressources for nothing. But i still want to use this world in a next event.
The plugin should skip the wrong hologram and still load the others.

Cmi version : 8.3.10.0

Spigot 1.13.2

Relevant plugins : Multiverse

**Comment by Zrips** [comment]
This actually was fixed, well, atleast it was converted into more stable format which would not throw error message when world is missing at that moment and keeps entry. Simple fix for you would be to load that world, make some simple change to any IC (Yes, its error from intractable commands, not from portals) to force save cycle and it will convert into new format which will change location into one liner. Which should solve issue once and for all.
