### ISSUE TITLE
/cmi reload internal error

### ISSUE THREAD

**Issue by Endothelium** [Zrips/CMI#1398]
When i use /cmi reload, i have an internal error.

```
[12:32:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.3.10.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1483) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandManager.addInteractiveCommand(InteractiveCommandManager.java:88) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandManager.load(InteractiveCommandManager.java:463) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.Config.reload(Config.java:2083) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.commands.list.reload.perform(reload.java:21) ~[CMI8.3.10.0.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252) ~[CMI8.3.10.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-947a8e7-3a91182]
	... 15 more
```

Cmi version: 8.3.10.0
Spigot 1.13.2

**Comment by Zrips** [comment]
Will fix it, tho check your interactiveCommands.yml for some strange entries for locations.
