### ISSUE TITLE
Mirror 1.12.2 not working (error)

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/CMI#1404]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
`Could not pass event BlockPlaceEvent to CMI v8.3.10.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Integer
at com.Zrips.CMI.Containers.CMIBlock.setData(CMIBlock.java:1814) ~[CMI8.3.10.0.jar:?]
at com.Zrips.CMI.Modules.Mirror.MirrorManager.getMirroredXYMap(MirrorManager.java:819) ~[CMI8.3.10.0.jar:?]
at com.Zrips.CMI.Modules.Mirror.MirrorManager.getMapLocations(MirrorManager.java:182) ~[CMI8.3.10.0.jar:?]
at com.Zrips.CMI.Modules.Mirror.MirrorManager.MirrorPlace(MirrorManager.java:374) ~[CMI8.3.10.0.jar:?]
at com.Zrips.CMI.Modules.Mirror.MirrorListener.BlockPlaceEvent(MirrorListener.java:22) ~[CMI8.3.10.0.jar:?]
at sun.reflect.GeneratedMethodAccessor623.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
... 18 more`

---

**Cmi Version (using`/cmi version`):** 
8.3.10.0
**Server Type (Spigot/Paperspigot/etc):** 
1.12.2-R0.1-SNAPSHOT
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Could you say which block was that exactly? As i cant determine which one exactly failed while setting data value.

**Comment by Zrips** [comment]
Anyhow, made some changes which should solve issue, if not reopen this ticket after next update comes out.
