### ISSUE TITLE
CMI and PlotSquared: null java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1410]
**Description of issue or feature request:**

CMI has trouble working in conjunction with PlotSquared v. 4
The plot world is not recognized by CMI without Multiverse

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:17:21] [Server thread/INFO]: [CMI] Enabling CMI v8.3.10.0
[14:17:22] [Server thread/INFO]: [CMI] Citizens found.
[14:17:22] [Server thread/INFO]: [CMI] PEX permission plugin will be used
[14:17:22] [Server thread/INFO]: [CMI] Loaded (46) regular alias into memory. Took 19ms
[14:17:22] [Server thread/INFO]: [CMI] Loaded (12) custom text's into memory. Took 2ms
[14:17:22] [Server thread/INFO]: [CMI] Started (SqLite) data base. Took 217ms
[14:17:22] [Server thread/INFO]: [CMI] Vault was found - Enabling capabilities. Economy: CMIEconomy
[14:17:22] [Server thread/INFO]: [CMI] Loaded (5) warning categories into memory. Took 0ms
[14:17:22] [Server thread/INFO]: [CMI] Loaded (3) warning commands into memory. Took 1ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (5) kits into memory. Took 22ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (109) custom mob heads
[14:17:23] [Server thread/INFO]: [CMI] Loaded (0) cooldowns into memory. Took 47ms
[14:17:23] [Server thread/INFO]:  Failed to load jail (jail)! Reason:null Error Log:
[14:17:23] [Server thread/ERROR]: [com.Zrips.CMI.Modules.Jail.JailManager] null
java.lang.NullPointerException: null
	at com.Zrips.CMI.Modules.Jail.JailManager.recalculateChunks(JailManager.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Jail.JailManager.addJail(JailManager.java:132) ~[?:?]
	at com.Zrips.CMI.Modules.Jail.JailManager.loadMap(JailManager.java:343) ~[?:?]
	at com.Zrips.CMI.Modules.Jail.JailManager.load(JailManager.java:274) ~[?:?]
	at com.Zrips.CMI.Modules.Jail.JailManager.<init>(JailManager.java:57) ~[?:?]
	at com.Zrips.CMI.CMI.getJailManager(CMI.java:755) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:1704) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:619) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1392) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-521]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-521]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-521]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-521]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-521]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-521]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[14:17:23] [Server thread/INFO]: [CMI] Loaded (1) jails into memory. Took 15ms
[14:17:23] [Server thread/INFO]: [CMI] Can't find world with (plot) name
[14:17:23] [Server thread/INFO]: [CMI] Loaded (5) kits into memory. Took 3ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (7) ranks into memory. Took 52ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (1) playtime rewards into memory. Took 2ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (13) Player data into memory. Took 26ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (155) playtime records into memory. Took 8ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (4) playtime reward records into memory. Took 0ms
[14:17:23] [Server thread/INFO]: [CMI] Duplicated alias found which could cause some strange (harmless) behavior: server
[14:17:23] [Server thread/INFO]: [CMI] Loaded (27) custom alias into memory. Took 3ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (1) interactive commands into memory. Took 29ms
[14:17:23] [Server thread/INFO]: [CMI] Found dynmap
[14:17:23] [Server thread/INFO]: [CMI] Registered events. Took 599ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (245) worth values into memory. Took 21ms
[14:17:23] [Server thread/INFO]: [CMI] Loaded (0) event action commands into memory. Took 23ms
[14:17:24] [Server thread/INFO]: [CMI] Updated (EN) language file. Took 145ms
[14:17:24] [Server thread/INFO]: [CMI] Updated (NL) language file. Took 132ms
[14:17:24] [Server thread/INFO]: [CMI] Loaded (3) warps into memory. Took 3ms
[14:17:24] [Server thread/INFO]: [CMI] Vault permissions was found - Enabling capabilities.
[14:17:24] [Server thread/INFO]: [CMI] PlaceholderAPI hooked.
[14:17:24] [Server thread/INFO]: [CMI] PlaceholderAPI was found - Enabling capabilities.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Jail made in the world "plot"

---

**Cmi Version (using`/cmi version`):** 
8.3.10.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.13.2 build 521
**Server Version (using `/ver`):** 
1.13.2
**Relevant plugins (Delete if this isn't needed):** 
PlotSquared-19.2.8-17027e6-152
http://ci.athion.net/job/PlotSquared-Breaking/

**Comment by Zrips** [comment]
Will add softdepend for PlotSquared which should solve this issue.
