### ISSUE TITLE
bug with head command

### ISSUE THREAD

**Issue by Maevaen** [Zrips/CMI#1411]
**Description of issue or feature request:**
im trying to create a command to make the player pay when getting a head, but when the player do /paidhead there is error because there is no name given, it look like to hard or weird to create something like this with customalias, can you add a command different then "/cmi head" like "/cmi paidhead" who will print help message like "/cmi paidhead [playername] - get the head of a player for 100 money" ? and add config option and local section for feedback message when player have get the head ect
---
**ERROR:**
```
[15:54:07 INFO]: Maevaen issued server command: /paidhead
[15:54:07 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.3.10.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1377) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.3.10.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:577) ~[CMI.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:531) ~[CMI.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[CMI.jar:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:84) ~[CMI.jar:?]
at sun.reflect.GeneratedMethodAccessor848.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
... 16 more
```

**CONFIG SECTION :**
```
CustomAlias:
  paidhead:
  - fromConsole! moneycost:250#?! cmi head $1- [playerName]
```

---

**Cmi Version (using`/cmi version`):** 
[16:14:03 INFO]: --------------------------------------------------
[16:14:03 INFO]: CMI plugin version: 8.3.10.0
[16:14:03 INFO]: Server version: Spigot 1.12-R0.1-SNAPSHOT
[16:14:03 INFO]: Vault version: 1.7.1-b91(CMIEInjector)
[16:14:03 INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
[16:14:49 INFO]: This server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next build.
