### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by TeeKay1** [Zrips/CMI#1419]
**Description of issue or feature request:**

Basically everytime i login i get this error.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:20:09 WARN]: [CMI] Task #178 for CMI v8.4.0.0 generated an exception
java.lang.NullPointerException: null
        at me.TechsCode.UltraPermissions.internal.ModifiedPermissible.getEffectivePermissions(ModifiedPermissible.java:254) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.getEffectivePermissions(CraftHumanEntity.java:251) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getAll(PermissionsManager.java:658) ~[?:?]
        at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPermissionInfo(PermissionsManager.java:748) ~[?:?]
        at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getPermissionInfo(PermissionsManager.java:716) ~[?:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager.getTL(TabListManager.java:293) ~[?:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager.updateTabListAsync(TabListManager.java:365) ~[?:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:334) ~[?:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:315) ~[?:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager$2.run(TabListManager.java:306) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.4.0.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
Latest 1.13.2
**Relevant plugins (Delete if this isn't needed):** 
UltraPermissions 4.3.

**Comment by Zrips** [comment]
Issue is at me.TechsCode.UltraPermissions.internal.ModifiedPermissible.getEffectivePermissions aka UltraPermissions is the source of issue. CMI only tried to get players permissions. Inform UltraPermissions dev about this issue.
