### ISSUE TITLE
Could not pass event ServerCommandEvent to CMI v8.4.0.1 and CMI v8.4.0.2

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1428]
Spigot: CraftBukkit version git-Spigot-b0f4c22-a2dd0e3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

CMI Vers: CMI v8.4.0.1

[17:44:41] [Server thread/ERROR]: Could not pass event ServerCommandEvent to CMI v8.4.0.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:548) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:81) ~[?:?]
	at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:84) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor633.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1628) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-b0f4c22-a2dd0e3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException

**Comment by Blueeyestar** [comment]
no one has any idea how to fix the problem? 
we use a CustomAlias speedstop command to shut down the server including saving. But we can't use this anymore.

**Comment by Zrips** [comment]
You have strange error, will make some changes for it, but you should not be getting this error in normal situations. What exact command and you performing that that time?

**Comment by Blueeyestar** [comment]
CustomAlias:
  passwordcommand:
    Cmds:
    - fromConsole! cmi rankset [playerName] Spieler
  serverstop:
    Cmds:
    - perm:cmi.command.customalias.serverstop! asConsole! serverstop2
  serverstop2:
    Cmds:
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Noch
      30 Sekunden %subtitle% &4&lBitte loggt euch in Kürze aus.
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi bossbarmsg all -s:20
      -a:6 -t:1 -n:Serverneustart &eDer Server wird in &6[autoTimeLeft] &eneugestartet
      -p:-1 -c:red
    - delay! 10
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Noch
      20 Sekunden %subtitle% &4&lBitte loggt euch in Kürze aus.
    - delay! 10
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Noch
      10 Sekunden %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 5
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Noch
      5 Sekunden %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Noch
      4 Sekunden %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Noch
      3 Sekunden %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Noch
      2 Sekunden %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Serverneustart!
      %subtitle% &4&lDer Server startet nun neu.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! rp save-all
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! minecraft:save-all
    - delay! 5
    - perm:cmi.command.customalias.serverstop! kickall! &eDer Server ist gleich wieder
      online!
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! minecraft:stop
  speedstop:
    Cmds:
    - perm:cmi.command.customalias.serverstop! asConsole! speedstop2
  speedstop2:
    Cmds:
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Neustart
      in 5 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Neustart
      in 4 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Neustart
      in 3 %subtitle% &4&lBitte loggt euch jetzt aus.

**Comment by Blueeyestar** [comment]
The bug has been fixed with CMI version 8.4.0.4. It runs again. Many thanks for fixing the problem.
