### ISSUE TITLE
[Bug] /cmi fixchunk causes exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1429]
```
[08:41:31 INFO]: mrfloris issued server command: /cmi fixchunk w end
[08:41:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.4.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at java.util.Arrays$ArrayList.<init>(Arrays.java:4323) ~[?:?]
        at java.util.Arrays.asList(Arrays.java:4310) ~[?:?]
        at com.Zrips.CMI.commands.list.fixchunk.perform(fixchunk.java:441) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-51c118b]
        ... 15 more
>
```

```
>about
[08:42:03 INFO]: This server is running CraftBukkit version git-Spigot-b0f4c22-51c118b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[08:42:03 INFO]: Checking version, please wait...
[08:42:03 INFO]: You are running the latest version
>about cmi
[08:42:04 INFO]: CMI version 8.4.0.2
[08:42:04 INFO]: Powerful server management tool
[08:42:04 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[08:42:04 INFO]: Author: Zrips
>
```

**Comment by Zrips** [comment]
Interesting, this error is because plugin failed to find correct path to world region files. Could you give me example of a path they are contained in for that End world of yours? Default is [worldName]\region

**Comment by mrfloris** [comment]
Apologies for the delay,

https://imgur.com/7pC5iKO
https://imgur.com/cdpNOe7

```
$ pwd
/Sandbox/mc/server-003/live-1mb-2.6.3-mc-1.13.2/end/DIM1/region
```

**Comment by mrfloris** [comment]
All overworlds have [worldName]\region\*
Nether and end worlds on all servers 1.13.2 have [worldName]\DIM1\region\*

We upgraded from 1.8 to 1.12.2 to 1.13.2 in the past on various servers, we use Multiverse-Core for 1.13.2 to handle our nether/end worlds. Maybe they set it up diff than default perhaps?

**Comment by mrfloris** [comment]
I haven't been getting this error since, so it's fixed or no longer an issue. I can run this just fine in 1.15.2 closing ticket.
