### ISSUE TITLE
[Bug] helpop from console causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1436]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
Executing `cmi helpop test` from the console causes error and is not performed.
Command executed by player does not cause error.
```
[21:39:42] [Server thread/WARN]: [CMI] Task #27455 for CMI v8.4.0.2 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.4.0.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-523]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-523]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-523]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:659) ~[patched_1.13.2.jar:git-Paper-523]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:596) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:550) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:120) ~[?:?]
	at com.Zrips.CMI.Modules.Afk.AfkManager$1.run(AfkManager.java:186) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-523]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-523]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-523]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-523]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-523]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-523]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
```
The bug was introduced in CMI v8.4.0.1
Problem is related to Bungee staff messages

---

**Cmi Version (using`/cmi version`):** 
CMI v8.4.0.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.13.2 build 523
**Server Version (using `/ver`):** 
Paper 1.13.2 build 523

**Comment by x1p** [comment]
Version 8.4.0.3 seems not affected.

**Comment by Zrips** [comment]
Should be fixed now
