### ISSUE TITLE
javax.script.ScriptException: <eval>:1:3 Expected 

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1441]
**when you send a message this error always occurs since the latest update**

**Spigot-Ver: CraftBukkit version git-Spigot-e8d3881-c24abab (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)**

**CMI-Ver. 8.4.0.3**

[23:03:17] [Server thread/WARN]: javax.script.ScriptException: <eval>:1:3 Expected ; but found hab
ja hab ich ja grad gesagt
   ^ in <eval> at line number 1 at column number 3
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[23:03:17] [Server thread/WARN]: 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[23:03:17] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.msg.perform(msg.java:58)
[23:03:17] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252)
[23:03:17] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:03:17] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[23:03:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[23:03:17] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:03:17] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[23:03:17] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[23:03:17] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:03:17] [Server thread/WARN]: Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:1:3 Expected ; but found hab
ja hab ich ja grad gesagt
   ^
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:350)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:337)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.endOfLine(Parser.java:3372)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1160)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
[23:03:17] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
[23:03:17] [Server thread/WARN]: 	... 22 more
[23:03:24] [Server thread/INFO]: Sirfakn lost connection: Disconnected
[23:03:24] [Server thread/INFO]: [Thirst] Saving player Sirfakn
[23:03:24] [Server thread/INFO]: Sirfakn hat Lululand verlassen.
[23:03:26] [Server thread/INFO]: Po_Ppy issued server command: /msg MagnaTeiwaz war n kleiner bums und fertig
[23:03:26] [Server thread/WARN]: javax.script.ScriptException: <eval>:1:4 Expected ; but found n
war n kleiner bums und fertig
    ^ in <eval> at line number 1 at column number 4
[23:03:26] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
[23:03:26] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
[23:03:26] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
[23:03:26] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[23:03:26] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[23:03:26] [Server thread/WARN]: 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[23:03:26] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.msg.perform(msg.java:58)
[23:03:26] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252)
[23:03:26] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:03:26] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[23:03:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[23:03:26] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:03:26] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[23:03:26] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[23:03:26] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:03:26] [Server thread/WARN]: Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:1:4 Expected ; but found n
war n kleiner bums und fertig
    ^

**Comment by x1p** [comment]
Same shit here
Happens after a `/msg` command.

Please fix this quickly

**Comment by x1p** [comment]
Perhaps better to read:
```
[14:22:04] [Server thread/INFO]: Player123 issued server command: /cmi msg PlayerABC Bla
[14:22:04] [Server thread/WARN]: javax.script.ScriptException: ReferenceError: "Bla" is not defined in <eval> at line number 1
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[14:22:04] [Server thread/WARN]: 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[14:22:04] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.msg.perform(msg.java:58)
[14:22:04] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252)
[14:22:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:22:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[14:22:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[14:22:04] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:22:04] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[14:22:04] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[14:22:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:22:04] [Server thread/WARN]: Caused by: <eval>:1 ReferenceError: "Bla" is not defined
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program(<eval>:1)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
[14:22:04] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
[14:22:04] [Server thread/WARN]: 	... 22 more
```

**Comment by x1p** [comment]
@Zrips (sorry for the ping but this has to get solved soonish)

**Comment by Zrips** [comment]
This should be addressed with todays update. If issue persists, as i could not reproduce it to properly test it out, but have general idea what could go wrong, give me a shout over here or throw Discord
