### ISSUE TITLE
[Bug] Console errors spam "javax.script.ScriptException: <eval>:1:5 Expected ; but found xd"

### ISSUE THREAD

**Issue by 4c5458** [Zrips/CMI#1447]
**Description of issue or feature request:**

20.000 lines of error spam
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[18:59:18] [Server thread/INFO]: player49234 issued server command: /msg secret haai xd
[18:59:18] [Server thread/WARN]: javax.script.ScriptException: <eval>:1:5 Expected ; but found xd
[18:59:18] [Server thread/WARN]: haai xd
[18:59:18] [Server thread/WARN]:      ^ in <eval> at line number 1 at column number 5
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
[18:59:18] [Server thread/WARN]: 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
[18:59:18] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.msg.perform(msg.java:58)
[18:59:18] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252)
[18:59:18] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:59:18] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[18:59:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1797)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1605)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[18:59:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:59:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[18:59:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[18:59:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:59:18] [Server thread/WARN]: Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:1:5 Expected ; but found xd
[18:59:18] [Server thread/WARN]: haai xd
[18:59:18] [Server thread/WARN]:      ^
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:350)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:337)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.endOfLine(Parser.java:3372)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1160)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
[18:59:18] [Server thread/WARN]: 	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
[18:59:18] [Server thread/WARN]: 	... 22 more
```

---

**Cmi Version (using`/cmi version`):** 
8.4.0.3

**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.13.2 build 524

**Comment by Blueeyestar** [comment]
https://github.com/Zrips/CMI/issues/1441

**Comment by Baktus79** [comment]
Same here

**Comment by Maevaen** [comment]
me too !!

**Comment by x1p** [comment]
Will be updated today. See issue 1441

**Comment by Zrips** [comment]
Will be fixed today.
