### ISSUE TITLE
Error when /cmi reload

### ISSUE THREAD

**Issue by XArcadeXx** [Zrips/CMI#1459]
**Description of issue or feature request:**
When i do /cmi reload it will do error in console.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
> [18:16:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.4.0.6
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.IllegalArgumentException: Cannot set to an empty path
at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:168) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:202) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.configuration.MemoryConfiguration.addDefault(MemoryConfiguration.java:40) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at com.Zrips.CMI.FileHandler.ConfigReader.process(ConfigReader.java:308) ~[?:?]
at com.Zrips.CMI.FileHandler.ConfigReader.get(ConfigReader.java:330) ~[?:?]
at com.Zrips.CMI.Modules.Enchants.EnchantManager.loadConfig(EnchantManager.java:107) ~[?:?]
at com.Zrips.CMI.Config.load(Config.java:2011) ~[?:?]
at com.Zrips.CMI.Config.reload(Config.java:2115) ~[?:?]
at com.Zrips.CMI.commands.list.reload.perform(reload.java:21) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:252) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-dcd1643-e60fc34]
... 15 more
```

---

**Cmi Version (using`/cmi version`):** 
8.4.0.6
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Issue with plugin which creates new enchants, but will make some adjustments to avoid this error
