### ISSUE TITLE
Persistent error on console

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1495]
**Description of issue or feature request:**
This error is spamming the console like crazy!
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
[22:03:38] [Craft Scheduler Thread - 393/WARN]: Exception in thread "Craft Scheduler Thread - 393" 
[22:03:38] [Craft Scheduler Thread - 393/WARN]: org.apache.commons.lang.UnhandledException: Plugin CMI v8.5.1.1 generated an exception while executing task 272325
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Age must be at least 1 tick
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setTicksLived(CraftEntity.java:361)
	at com.Zrips.CMI.Modules.Afk.AfkManager$2$1.run(AfkManager.java:373)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.5.1.1
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
spigot 1.8.8 R01 snapshot
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will be fixed with next build
