### ISSUE TITLE
[Error] Respawn event

### ISSUE THREAD

**Issue by Tyz3** [Zrips/CMI#1508]
**Description of issue or feature request:**
Issue with every respawn event.
---

**ERROR:**
```
[23:03:19 WARN]: [CMI] Task #6556 for CMI v8.4.0.5 generated an exception
java.lang.NullPointerException
        at com.Zrips.CMI.Reflections.respawn(Reflections.java:1091) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.respawn(CMIUser.java:1640) ~[?:?]
        at com.Zrips.CMI.AllListeners.UserEvents$4.run(UserEvents.java:203) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

---

**Cmi Version (using`/cmi version`):8.4.0.5** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): 1.7.10 R4**

**Comment by Zrips** [comment]
Should be working correctly with latest build
