### ISSUE TITLE
/cmi homes <playername> fails with an internal error for one specific player, who is offline

### ISSUE THREAD

**Issue by runelynx** [Zrips/CMI#1509]
**Description of issue or feature request:**
/cmi homes <playername> fails with an internal error for one specific player, who is offline

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Console 03/08/2019 20:46:04
20:46:04 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:172) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:114) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:267) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:263) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.World.getType(World.java:658) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getType(CraftBlock.java:182) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:351) ~[?:?]
at com.Zrips.CMI.commands.list.homes.perform(homes.java:55) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
... 15 more
Caused by: java.lang.RuntimeException: Batch already started.
at net.minecraft.server.v1_13_R2.SchedulerBatch.b(SourceFile:27) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:108) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:267) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:263) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at net.minecraft.server.v1_13_R2.World.getType(World.java:658) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getType(CraftBlock.java:182) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:351) ~[?:?]
at com.Zrips.CMI.commands.list.homes.perform(homes.java:55) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-e5e5c7c-6430d9c]
... 15 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.5.1.0-> 8.5.1.2
Server version: Spigot 1.13.2-R0.1-SNAPSHOT
Vault version: 1.6.10(+)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-e5e5c7c-6430d9c (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are 14 version(s) behind

**Comment by runelynx** [comment]
Resolved in a recent patch.
