### ISSUE TITLE
CMI not enabling on statup

### ISSUE THREAD

**Issue by SharkSE** [Zrips/CMI#1519]
**Description of issue or feature request:**

So in version 8.x I simply don't get any reaction from the plugin at all. I'm not sure why that is. In version 7.x I see it trying to activate itself, but for some reason it can generate all files, for example the config file is simply not existent. 
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:420)
[]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:379)
[]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:620)
[]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:581)
[]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:537)
[]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:711)
[]: at java.lang.Thread.run(Thread.java:748)
[]: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.ServerStatisticManager
[]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99)
[]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[]: at java.lang.Class.forName0(Native Method)
[]: at java.lang.Class.forName(Class.java:264)
[]: at com.Zrips.CMI.Reflections.getMinecraftClass(Reflections.java:227)
[]: at com.Zrips.CMI.Reflections.initialize(Reflections.java:109)
[]: at com.Zrips.CMI.Reflections.<init>(Reflections.java:69)
[]: at com.Zrips.CMI.CMI.getRef(CMI.java:429)
[]: at com.Zrips.CMI.CMI.onEnable(CMI.java:1164)
[]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256)
[]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:420)
[]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:379)
[]: at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:620)
[]: at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:581)
[]: at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:537)
[]: at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:711)
[]: at java.lang.Thread.run(Thread.java:748)
[]: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.PropertyManager
[]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:99)
[]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[]: at java.lang.Class.forName0(Native Method)
[]: at java.lang.Class.forName(Class.java:264)
[]: at com.Zrips.CMI.Reflections.getMinecraftClass(Reflections.java:227)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**

Very Relevant...but not existent

---

Cmi Version (using`/cmi version`):
7.9/7.7/8.3/8.5 (I tried a few...)

Server Type (Spigot/Paperspigot/etc):
Kettle (something like Cauldron)

Server Version (using `/ver`):
Minecraft Version 1.12.2

**Comment by spannerman79** [comment]
> Server Type (Spigot/Paperspigot/etc):
> Kettle (something like Cauldron)

Take it up with the Kettle devs.

**Comment by Zrips** [comment]
CMI was not made to support Kettle in any shape or form. Tho those errors should not prevent plugin load in general. It will show error messages, but it should startup. I would need all of the errors related to CMI on server startup to maybe resolve this issue. Maybe.
