### ISSUE TITLE
/whois shows an arror

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#1550]
**Description of issue or feature request:**

--- /whois shows an error

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## [12:24:25 INFO]: gilles666 issued server command: /whois gilles666
[12:24:26 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -16776960 out of bounds for length 256
[12:24:26 WARN]:        at com.Zrips.CMI.Modules.GeoIP.LookupService.readCityRecord(LookupService.java:415)
[12:24:26 WARN]:        at com.Zrips.CMI.Modules.GeoIP.LookupService.getLocation(LookupService.java:390)
[12:24:26 WARN]:        at com.Zrips.CMI.Modules.GeoIP.LookupService.getLocation(LookupService.java:365)
[12:24:26 WARN]:        at com.Zrips.CMI.Modules.GeoIP.LookupService.getLocation(LookupService.java:378)
[12:24:26 WARN]:        at com.Zrips.CMI.commands.list.info$1$1.run(info.java:448)
[12:24:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[12:24:26 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[12:24:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[12:24:26 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[12:24:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[12:24:26 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[12:24:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
 ##
####################
```

---

**Cmi Version (using`/cmi version`):** 5.5.1.4

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Error should be gone with next update
