### ISSUE TITLE
When the sign is placed in the long grass square, the console has an error.

### ISSUE THREAD

**Issue by Zoelleradada** [Zrips/CMI#1563]
When the sign is placed in the long grass square, the console has an error. sign can be used normally, but I don't know what the consequences of this error will be.
Please fix this error, thank you
CMI Version: 8.5.3.0
Server Core: Spigot 1.13.2 (Implementing API version 1.13.2-R0.1SNAPSHOT)
```
Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:200) [spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_13_R2.EntityPlayer.openSign(EntityPlayer.java:794) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:279) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:506) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1221) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-51100db]
	... 5 more
```

**Comment by Zrips** [comment]
This was an error from minecraft itself, but should be working correctly now.
