### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by TopCZE** [Zrips/CMI#159]
Enabling CMI v7.5.1.1
[23:38:10 ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
at org.bukkit.Location.deserialize(Location.java:612) ~[minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:35) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:26) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at com.Zrips.CMI.Modules.Portals.PortalManager.load(PortalManager.java:316) [CMI7.5.1.1.jar:?]
at com.Zrips.CMI.Modules.Portals.PortalManager.<init>(PortalManager.java:60) [CMI7.5.1.1.jar:?]
at com.Zrips.CMI.CMI.getPortalManager(CMI.java:583) [CMI7.5.1.1.jar:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java:1075) [CMI7.5.1.1.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [minecraft_server.jar:git-Spigot-c3093ef-29705a0]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

CraftBukkit version git-Spigot-c3093ef-29705a0 (MC: 1.12.2)

**Comment by stashenko** [comment]
unknown world

**Comment by LogGits** [comment]
What multiworld plugin are you using?

**Comment by TopCZE** [comment]
Multiverse core but it was my error I deleted the world after regenerating the error no longer displayed

**Comment by LogGits** [comment]
Is this still an issue @TopCZE?
