### ISSUE TITLE
Cant's create mysql column NameColor automatically

### ISSUE THREAD

**Issue by smartmadio** [Zrips/CMI#1610]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
This error message shows in a crazy speed,only 12 seconds,the log file increased to 15MB.
```
[20:21:35] [Server thread/WARN]: java.sql.SQLException: Column 'NameColor' not found.
[20:21:35] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[20:21:35] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[20:21:35] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[20:21:35] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[20:21:35] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
[20:21:35] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
[20:21:35] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1665)
[20:21:35] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1183)
[20:21:35] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1052)
[20:21:35] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:450)
[20:21:35] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1371)
[20:21:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:21:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[20:21:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:21:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[20:21:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[20:21:36] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[20:21:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[20:21:36] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[20:21:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[20:21:36] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[20:21:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[20:21:36] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[20:21:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[20:21:36] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1080)
[20:21:35] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[20:21:36] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
[20:21:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 
8.5.6.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper(1612) 1.12.2-R0.1
**Relevant plugins (Delete if this isn't needed):**

**Comment by smartmadio** [comment]
I added this column by myself,but hope this issue could be fixed.

**Comment by ipozow** [comment]
Having the same issue. I have also had like a rollback of the entire plugin. Have this happened to you too?

**Comment by Zrips** [comment]
Should be working correctly with latest builds
