### ISSUE TITLE
Regen'ing a world in multiverse breaks /homes command

### ISSUE THREAD

**Issue by runelynx** [Zrips/CMI#1638]
**Description of issue or feature request:**

We have a resource world (using Multiverse) that we regenerate every week or so. Any players who have a home in that world, after we regen it, lose access to all their homes. They get an error when they try to load their home.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
--------------------------------------------------
CMI plugin version: 8.5.6.0-> 8.5.6.1
Server version: Spigot 1.13.2-R0.1-SNAPSHOT
Vault version: 1.6.10(+)
--------------------------------------------------

```
[13:43:31] [Server thread/INFO]: iDeb issued server command: /homes
[13:43:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.5.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:172) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:114) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:267) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:263) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.World.getType(World.java:658) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getType(CraftBlock.java:182) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:357) ~[?:?]
	at com.Zrips.CMI.commands.list.homes.perform(homes.java:55) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	... 15 more
Caused by: java.lang.RuntimeException: Batch already started.
	at net.minecraft.server.v1_13_R2.SchedulerBatch.b(SourceFile:27) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:108) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:267) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:263) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at net.minecraft.server.v1_13_R2.World.getType(World.java:658) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getType(CraftBlock.java:182) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:357) ~[?:?]
	at com.Zrips.CMI.commands.list.homes.perform(homes.java:55) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
	... 15 more
```

**Comment by runelynx** [comment]
Any news on this one?

**Comment by runelynx** [comment]
This is still broken in 8.6.1.3

 16:04:13
16:04:13org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.1.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: y out of range (expected 0-255, got -1)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.craftbukkit.v1_13_R2.CraftChunk.validateChunkCoordinates(CraftChunk.java:293) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.craftbukkit.v1_13_R2.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:61) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at com.Zrips.CMI.Containers.CMILocation.getBlockCMIType(CMILocation.java:184) ~[?:?]
at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:375) ~[?:?]
at com.Zrips.CMI.commands.list.homes.perform(homes.java:55) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
... 15 more

**Comment by Zrips** [comment]
This will be fixed with today's update. if you gonna still experience this issue, set new Homes.PickRealBlock to false in config file

**Comment by runelynx** [comment]
Works in 8614, thank you :)
