### ISSUE TITLE
Bug Report: Toast errors on certain items.

### ISSUE THREAD

**Issue by the456gamer** [Zrips/CMI#1640]
**Description of issue:**
when using /cmi toast with the icon being redstone dust, redstone repeater or a comparator, there is an internal error message and the command does not perform. there may be more items affected by this but but these are those i found.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
redstone_dust using bukkit name:
```
[18:17:38] [Server thread/INFO]: the456gamer issued server command: /toast all -t:task -icon:redstone big\nmultiline
[18:17:38] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.5.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-621]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-621]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-621]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-621]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'minecraft:redstone_dust'
	at net.minecraft.server.v1_13_R2.ChatDeserializer.b(SourceFile:129) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.i(SourceFile:140) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:110) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:97) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.Advancement$SerializedAdvancement.a(Advancement.java:323) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDataWorld.lambda$static$0(AdvancementDataWorld.java:27) ~[patched_1.13.2.jar:git-Paper-621]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:542) ~[patched_1.13.2.jar:git-Paper-621]
	at com.Zrips.CMI.NBT.v1_13_R2.loadAdvancement(v1_13_R2.java:1753) ~[?:?]
	at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.add(CMIAdvancement.java:137) ~[?:?]
	at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.show(CMIAdvancement.java:122) ~[?:?]
	at com.Zrips.CMI.commands.list.toast.perform(toast.java:108) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-621]
	... 15 more
```

redstone_repeater using id:
```
[18:13:45] [Server thread/INFO]: the456gamer issued server command: /toast all -t:task -icon:28823 big\nmultiline
[18:13:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.5.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-621]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-621]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-621]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-621]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'minecraft:redstone_repeater'
	at net.minecraft.server.v1_13_R2.ChatDeserializer.b(SourceFile:129) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.i(SourceFile:140) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:110) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:97) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.Advancement$SerializedAdvancement.a(Advancement.java:323) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDataWorld.lambda$static$0(AdvancementDataWorld.java:27) ~[patched_1.13.2.jar:git-Paper-621]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:542) ~[patched_1.13.2.jar:git-Paper-621]
	at com.Zrips.CMI.NBT.v1_13_R2.loadAdvancement(v1_13_R2.java:1753) ~[?:?]
	at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.add(CMIAdvancement.java:137) ~[?:?]
	at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.show(CMIAdvancement.java:122) ~[?:?]
	at com.Zrips.CMI.commands.list.toast.perform(toast.java:108) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-621]
	... 15 more
```
redstone_comparator using id:
```
[18:17:28] [Server thread/INFO]: the456gamer issued server command: /toast all -t:task -icon:18911 big\nmultiline
[18:17:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.5.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-621]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-621]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-621]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-621]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'minecraft:redstone_comparator'
	at net.minecraft.server.v1_13_R2.ChatDeserializer.b(SourceFile:129) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.i(SourceFile:140) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:110) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:97) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.Advancement$SerializedAdvancement.a(Advancement.java:323) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.AdvancementDataWorld.lambda$static$0(AdvancementDataWorld.java:27) ~[patched_1.13.2.jar:git-Paper-621]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522) ~[patched_1.13.2.jar:git-Paper-621]
	at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:542) ~[patched_1.13.2.jar:git-Paper-621]
	at com.Zrips.CMI.NBT.v1_13_R2.loadAdvancement(v1_13_R2.java:1753) ~[?:?]
	at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.add(CMIAdvancement.java:137) ~[?:?]
	at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.show(CMIAdvancement.java:122) ~[?:?]
	at com.Zrips.CMI.commands.list.toast.perform(toast.java:108) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-621]
	... 15 more
```
---

**Cmi Version (using`/cmi version`):** 

\> cmi version
[18:51:00 INFO]: --------------------------------------------------
[18:51:00 INFO]: CMI plugin version: 8.5.6.0-> 8.5.6.1
[18:51:00 INFO]: Server version: Paper(621) 1.13.2-R0.1-SNAPSHOT
[18:51:00 INFO]: Vault version: 1.6.11(+)
[18:51:00 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
PaperMc

**Server Version (using `/ver`):** 
\> ver
[18:51:53 INFO]: This server is running Paper version git-Paper-621 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:51:53 INFO]: Checking version, please wait...
[18:51:54 INFO]: You are 1 version(s) behind

**Relevant plugins (Delete if this isn't needed):** 
- CMI (Duh)

**Comment by the456gamer** [comment]
I am going to test this on a later version now.

**Comment by the456gamer** [comment]
> I am going to test this on a later version now.
just updated it, still the same

**Comment by Zrips** [comment]
Should be fixed with next update.
