### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zeuzi** [Zrips/CMI#1641]
Descirption 

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR:**
```
Error occurred while enabling CMI v8.5.6.1 (Is it up to date?)
java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
        at org.sqlite.core.NativeDB._open_utf8(Native Method) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.core.NativeDB._open(NativeDB.java:78) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.core.DB.open(DB.java:195) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:243) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:61) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.JDBC.createConnection(JDBC.java:116) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.sqlite.JDBC.connect(JDBC.java:90) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_212]
        at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_212]
        at com.Zrips.CMI.Modules.DataBase.DBConnectionPool.getConnection(DBConnectionPool.java:34) ~[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBDAO.getConnection(DBDAO.java:546) ~[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBSQLite.isTable(DBSQLite.java:81) ~[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBDAO.createDefaultTable(DBDAO.java:1395) ~[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBDAO.setUp(DBDAO.java:460) ~[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBSQLite.initialize(DBSQLite.java:18) ~[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBManager.startSqlite(DBManager.java:143) ~[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBManager.start(DBManager.java:80) ~[?:?]
        at com.Zrips.CMI.Config.load(Config.java:675) ~[?:?]
        at com.Zrips.CMI.Config.load(Config.java:657) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1353) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot.jar:git-Spigot-f09662d-3697519]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) [spigot.jar:git-Spigot-f09662d-3697519]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [spigot.jar:git-Spigot-f09662d-3697519]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot.jar:git-Spigot-f09662d-3697519]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-f09662d-3697519]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot.jar:git-Spigot-f09662d-3697519]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
not relevant / no config created first time starting with cmi
```

---

**Latest 4/23/2019** 

**Craftbukkit:** 

**1.13.2**

**Comment by zeuzi** [comment]
found a fix 
: sudo mount /tmp -o remount,exec
this command remounts the tmp folder

**Comment by Zrips** [comment]
Well this seems to be issue with your server SqLite setup not recognizing correctly utf-8 format. But if this one is fixed, then i can close this report.
