### ISSUE TITLE
Little Error On Loading CMI_8.6.0.1-Experimental - Spigot 1.14

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#1649]
`[22:24:24] [Server thread/ERROR]: Error occurred while enabling CMI v8.6.0.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Zrips.CMI.Modules.CmiItems.ItemManager.getItem(ItemManager.java:254) ~[?:?]
	at com.Zrips.CMI.Modules.CmiItems.ItemManager.getMaterial(ItemManager.java:469) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:821) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:657) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1353) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:346) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar:git-Spigot-e4be9b0-5736cdc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]`

**Comment by mrfloris** [comment]
You have to get the latest Spigot 1.14 (not pre5) with the latest CMI build. 
This should work. It's no longer for pre5.

**Comment by CloudeLecaw** [comment]
Oh i have not noticed that the spigot 1.14 Release is out allready :-)

I will compile and test is today

**Comment by CloudeLecaw** [comment]
Even with latest Spigot 1.14 server this error appears on my server on loading :(
