### ISSUE TITLE
Erroer with GUI on Updating to latest Devbuild

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#1653]
**Spigot Version:** 1.14
**Redprotect Version:** RedProtect-7.6.0-Build189
**language:** 'DE-DE'

When You setted the Plugin to an other lang like me (De in my case)
The GUI File gets no new langfile. This result in an error after the next load when tryping to use /rp flag

`[23:38:27] [Server thread/INFO]: Cloude_Lecaw issued server command: /rp flag
[23:38:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rp' in plugin RedProtect v7.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:145) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1667) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1507) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.h(SourceFile:135) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.h(SourceFile:23) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.p(SourceFile:114) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:876) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.p(MinecraftServer.java:869) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.c(SourceFile:123) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:853) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:793) [spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalStateException: Title not set
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at net.minecraft.server.v1_14_R1.Container.getTitle(Container.java:48) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	at br.net.fabiozumbi12.RedProtect.Bukkit.helpers.RPGui.open(RPGui.java:293) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.SubCommands.RegionHandlers.FlagCommand.onCommand(FlagCommand.java:63) ~[?:?]
	at br.net.fabiozumbi12.RedProtect.Bukkit.commands.CommandHandler.onCommand(CommandHandler.java:158) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14-pre5.jar:git-Spigot-6dbf995-364b6fb]
	... 17 more`

what a luck that Redprotect created the bakups correctly.

![27-04-_2019_22-42-12](https://user-images.githubusercontent.com/12080017/56854902-2029a600-693e-11e9-9eb5-a36dee462e80.jpg)
Like you can see in the pic. the needed langfile: guiDE-DE.properties was not created
(ignore the files with the unterscores ( _ ) these are my manually created backups, mostly for faster checking differences on fileediting)

**Note:**
What currently worked fine is creating the guiDE-DE.properties manually.
Once it is created manually after updating the rp flag gui works fine aggain.

**Comment by CloudeLecaw** [comment]
Sorry this
