### ISSUE TITLE
Compatibility issues with the Groupmanager+ plugin

### ISSUE THREAD

**Issue by BackWheel** [Zrips/CMI#1657]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####
Error occurred while enabling CMI v8.6.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/anjocaido/groupmanager/GroupManager
at com.Zrips.CMI.Modules.Permissions.GroupManagerXHandler.<init>(GroupManagerXHandler.java:21) ~[?:?]
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.checkPermissions(PermissionsManager.java:543) ~[?:?]
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.<init>(PermissionsManager.java:32) ~[?:?]
at com.Zrips.CMI.CMI.getPermissionsManager(CMI.java:658) ~[?:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java:1322) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:346) [spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408) [spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: org.anjocaido.groupmanager.GroupManager
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.jar:git-Spigot-fa07878-c9fa596]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
... 14 more
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Which version of GroupManaget+ you are using exactly?

**Comment by mrfloris** [comment]
```
>about GroupManager
[14:55:18 INFO]: GroupManager version GMBuildVer (Phoenix)
[14:55:18 INFO]: Provides on-the-fly system for permissions system created by Nijikokun. But all in memory, and with flat-file saving schedule.
[14:55:18 INFO]: Website: http://ess.khhq.net/wiki/Group_Manager
[14:55:18 INFO]: Authors: AnjoCaido, Gabriel Couto and ElgarL
>ver
[14:55:22 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[14:55:22 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
>
```

For the @op, this is the version I am using on 1.13.2 with latest CMI and it's working great for me. 

I see there's a GM+ on Spigot, but I believe we're using this one:
https://www.spigotmc.org/resources/groupmanager.38875/

I hope that helps op.

**Comment by BackWheel** [comment]
> 您正在使用哪个版本的GroupManaget +？

Version 3.1 GroupManager+
https://www.spigotmc.org/resources/groupmanager-fully-support-spigot-1-7-1-14.40615/

**Comment by mrfloris** [comment]
As far as I can tell that's an unofficial fork of GroupManager, I recommend to upgrade to the other one for 1.13.2 and 1.14.x and see if the issue goes away?
