### ISSUE TITLE
/rt cause an exception error

### ISSUE THREAD

**Issue by cdmvirt** [Zrips/CMI#1668]
**Description of issue or feature request:**

when using /rt causes this exception error
and in chat in chat says

"could not find correct teleport location, please wait one minute and try again."

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
`[Craft Scheduler Thread - 2/WARN]: [CMI] Plugin CMI v8.6.0.3 generated an exception while executing task 1948
java.lang.IllegalStateException: Chunk not there when requested: Unloaded ticket level [42, 210]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.lambda$1(ChunkProviderServer.java:72) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:68) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:100) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.World.getType(World.java:548) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.IBlockAccess.a(SourceFile:52) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.IBlockAccess.a(SourceFile:113) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at net.minecraft.server.v1_14_R1.IBlockAccess.rayTrace(SourceFile:51) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at com.Zrips.CMI.NBT.v1_14_R1.getBlockLookingAt(v1_14_R1.java:1889) ~[?:?]
at com.Zrips.CMI.Containers.CMIHitBox.getCollidingdBlock(CMIHitBox.java:369) ~[?:?]
at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:352) ~[?:?]
at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:344) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:641) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:399) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.getRandomLocation(Teleportations.java:985) ~[?:?]
at com.Zrips.CMI.commands.list.rt$1.run(rt.java:92) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar:git-Spigot-1eece4f-dadc539]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

---

**Cmi Version (using`/cmi version`): 8.6.0.3

**Server Type (Spigot/Paperspigot/etc): spigot 

**Server Version (using `/ver`): git-Spigot-1eece4f-dadc539 (MC: 1.14)

**Comment by SmallSansSerif** [comment]
Also experience similar problem with 8.6.0.3 using RTP only with PaperSpigot 1.13.2 #624

**Comment by Rukes** [comment]
Same https://pastebin.com/3xurUDV0

**Comment by FestusDM** [comment]
Same issue, though I didn't get warnings after the command is issued. Using portal set up with rt command did not send error/warning either, player just stand there instead of being rt to somewhere.

I only receive "could not find correct teleport location, please wait ___ minute and try again." message.

**Comment by Baktus79** [comment]
Same here, I dont get any warning messages at all, but I get this ingame
![image](https://user-images.githubusercontent.com/19745447/57016227-50f92c00-6c19-11e9-8973-fe7ca940aa75.png)

**Comment by Rukes** [comment]
I dont receive any feedback message.

**Comment by AntoineHrn** [comment]
Same here

**Comment by SeDark** [comment]
Same, I cant update to latest version because of this...

**Comment by DonSensiLeone** [comment]
> 
> 
> Also experience similar problem with 8.6.0.3 using RTP only with PaperSpigot 1.13.2 #624
> 
> Was previously using 8.5.6.1 with working rtp config.

same thing for me but with no errors in logs

**Comment by Zrips** [comment]
Should be fixed with next build today
