### ISSUE TITLE
AsyncPlayerChatEvent error on 1.14

### ISSUE THREAD

**Issue by DaveDevil** [Zrips/CMI#1696]
**Description of issue or feature request:**

Could not pass event AsyncPlayerChatEvent to CMI

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[Async Chat Thread - #88/ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.6.1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalStateException: CMIAfkLeaveEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	at com.Zrips.CMI.Containers.CMIUser.setAfk(CMIUser.java:1346) ~[?:?]
	at com.Zrips.CMI.Modules.Afk.AfkListener.onAsyncPlayerChatEvent(AfkListener.java:346) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor405.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-1eece4f-7861651]
	... 11 more
```

---

**Cmi Version (using`/cmi version`):** 8.6.1.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-1eece4f-7861651 (MC: 1.14)

**Comment by Zrips** [comment]
Will be fixed with next build
