### ISSUE TITLE
AsyncPlayerChatEvent to CMI v8.6.1.0

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1702]
[19:17:58] [Async Chat Thread - #32/ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.6.1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IllegalStateException: CMIAfkLeaveEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	at com.Zrips.CMI.Containers.CMIUser.setAfk(CMIUser.java:1346) ~[?:?]
	at com.Zrips.CMI.Modules.Afk.AfkListener.onAsyncPlayerChatEvent(AfkListener.java:346) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor442.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-1eece4f-0d76f86]
	... 11 more

**Comment by Zrips** [comment]
This was fixed in 8.6.1.1
