### ISSUE TITLE
CMI not saving data in MySQL

### ISSUE THREAD

**Issue by ipozow** [Zrips/CMI#1704]
**Description of issue or feature request:**
Users gets money, new nicknames and homes and then all stuff goes back to how it was before the server start. It only happens with CMI, because Towny data is being saved and I am using MySQL in both
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[Server thread/WARN]: java.sql.SQLException: Column 'NameColor' not found.
[19:01:31] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[19:01:31] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[19:01:31] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[19:01:31] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[19:01:31] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1078)
[19:01:31] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5175)
[19:01:31] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1665)
[19:01:31] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1183)
[19:01:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1052)
[19:01:31] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:450)
[19:01:31] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1371)
[19:01:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[19:01:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[19:01:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[19:01:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[19:01:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[19:01:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[19:01:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[19:01:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[19:01:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[19:01:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[19:01:31] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
There is already an issue with this but I don't know if it's related… The main issue is that CMI does not saves the data after a /stop

---

**Cmi Version (using`/cmi version`):** 
8.6.1.1
**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.13.2
**Server Version (using `/ver`):** 
git-Spigot-1a3504a-dfa7583 (is the last Spigot build and I know, last ≠ latest)

**Comment by ipozow** [comment]
it's solved in another issue, but seems like that it also works adding the column manually
