### ISSUE TITLE
<Bug> /home doesn't work

### ISSUE THREAD

**Issue by cdmvirt** [Zrips/CMI#1710]
**Description of issue or feature request:**

when trying to go home either via the GUI or command errors accur

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[15:33:02 ERROR]: Could not pass event InventoryClickEvent to CMI v8.6.0.3
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.0.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:455) ~[patched_1.14.jar:git-Paper-7]
at com.Zrips.CMI.utils.Util.performCommand(Util.java:612) ~[?:?]
at com.Zrips.CMI.utils.Util.performCommand(Util.java:596) ~[?:?]
at com.Zrips.CMI.CMI.performCommand(CMI.java:2217) ~[?:?]
at com.Zrips.CMI.Modules.Homes.HomeManager$1.click(HomeManager.java:398) ~[?:?]
at com.Zrips.CMI.Modules.GUI.GUIManager.processClick(GUIManager.java:157) ~[?:?]
at com.Zrips.CMI.Modules.GUI.GUIListener.onInventoryClick(GUIListener.java:123) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor953.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.jar:git-Paper-7]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2335) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:972) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.jar:git-Paper-7]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: y out of range (expected 0-255, got -1)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.craftbukkit.v1_14_R1.CraftChunk.validateChunkCoordinates(CraftChunk.java:326) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.craftbukkit.v1_14_R1.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:62) ~[patched_1.14.jar:git-Paper-7]
at com.Zrips.CMI.Modules.tp.Teleportations.isEmpty(Teleportations.java:549) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:643) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:399) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:310) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299) ~[?:?]
at com.Zrips.CMI.commands.list.home.perform(home.java:146) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.jar:git-Paper-7]
... 28 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 8.6.0.3

**Server Type (Spigot/Paperspigot/etc):**  paper 1.14

**Server Version (using `/ver`):** git-Paper-7 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

**Comment by LogGits** [comment]
Have you tried testing this on `8.6.1.1`, some improvements were made to rtp.

**Comment by cdmvirt** [comment]
same issue
