### ISSUE TITLE
CMI Help Page not showing

### ISSUE THREAD

**Issue by Plastic-Card** [Zrips/CMI#1719]
**Description of issue or feature request:**

--- I have just downloaded CMI. I only have 10 other plugins including cmi. They are Luck perms, plugman, worldedit, pluginconstuctorAPI, jEssentials, Vouchers {Premium} Vault {given from the CMI bukkit page) Multiverse core, Crates reloaded (Premium) 

I am unable to do /cmi it will not open up the help page, or show me any commands possible. It is loaded and enabled and i don't know what has happened  

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## [CMI] Enabling CMI v8.6.1.2
[02:43:44] [Server thread/INFO]: [CMI] 47 Enabled and 0 Disabled modules
[02:43:44] [Server thread/INFO]: [CMI] LuckPerms plugin will be used
[02:43:44] [Server thread/INFO]: [CMI] Loaded (46) regular alias into memory. Took 15ms
[02:43:44] [Server thread/INFO]: [CMI] Loaded (1) custom text's into memory. Took 1ms
[02:43:44] [Server thread/INFO]: [CMI] UserTable creating CREATE TABLE `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_uuid` text, `username` text, `nickname` text, `LogOutLocation` text, `DeathLocation` text, `TeleportLocation` text, `teleportToggled` boolean, `Homes` text, `LastLoginTime` bigint, `LastLogoffTime` bigint, `TotalPlayTime` bigint, `tFly` bigint, `tGod` bigint, `Glow` text, `Ips` text, `Cuffed` boolean, `AlertUntil` bigint, `AlertReason` text, `JoinedCounter` boolean, `LockedIps` text, `pTime` bigint, `Kits` text, `Charges` text, `Cooldowns` longtext, `Balance` double, `Notes` text, `Rank` text, `TagSound` boolean, `SignShiftEdit` boolean, `Spy` boolean, `CommandSpy` boolean, `BannedUntil` bigint, `BannedAt` bigint, `BannedBy` text, `BanReason` text, `Ignores` text, `Vanish` text, `Economy` text, `Mail` text, `FlightCharge` double, `UserMeta` text, `Flying` boolean, `Votifier` int, `Jail` text, `JailedUntil` bigint, `FakeAccount` boolean, `PlaytimeOptimized` bigint, `flightChargeEnabled` boolean, `noPayToggled` boolean, `JailReason` text, `Skin` text, `SignSpy` boolean, `Collision` boolean, `NamePrefix` text, `NameSuffix` text, `Warnings` text, `msgToggle` boolean, `NameColor` text);
[02:43:44] [Server thread/INFO]: [CMI] InvTable creating CREATE TABLE `inventories` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `inventories` longtext);
[02:43:44] [Server thread/INFO]: [CMI] PlayTime creating CREATE TABLE `playtime` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `date` int, `h0` bigint, `h1` bigint, `h2` bigint, `h3` bigint, `h4` bigint, `h5` bigint, `h6` bigint, `h7` bigint, `h8` bigint, `h9` bigint, `h10` bigint, `h11` bigint, `h12` bigint, `h13` bigint, `h14` bigint, `h15` bigint, `h16` bigint, `h17` bigint, `h18` bigint, `h19` bigint, `h20` bigint, `h21` bigint, `h22` bigint, `h23` bigint);
[02:43:44] [Server thread/INFO]: [CMI] PlayTimeReward creating CREATE TABLE `playtimereward` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `repeatable` text, `onetime` text);
[02:43:44] [Server thread/INFO]: [CMI] Started (SqLite) data base. Took 191ms
[02:43:44] [Server thread/ERROR]: Error occurred while enabling CMI v8.6.1.2 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Zrips.CMI.Modules.Economy.VaultManager.setupVault(VaultManager.java:47) ~[?:?]
	at com.Zrips.CMI.Modules.Economy.EconomyManager.<init>(EconomyManager.java:69) ~[?:?]
	at com.Zrips.CMI.CMI.getEconomyManager(CMI.java:604) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:678) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:657) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1353) ~[?:?] ##
####################

**Cmi Version (using`/cmi version`):** 
8.6.1.2  is the version i downloaded

**Server Type (Spigot/Paperspigot/etc):** 
spigot 1.12.2
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):** CMI

**Comment by Zrips** [comment]
Should be in working condition now.
