### ISSUE TITLE
Respawn not working

### ISSUE THREAD

**Issue by AloneSpace** [Zrips/CMI#1721]
**Description of issue or feature request:**

15:13:28 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.DedicatedPlayerList.moveToWorld(net.minecraft.server.v1_14_R1.EntityPlayer, org.bukkit.craftbukkit.v1_14_R1.CraftServer$3, boolean)
[15:13:28 WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2109)
[15:13:28 WARN]: 	at com.Zrips.CMI.Reflections.respawn(Reflections.java:1150)
[15:13:28 WARN]: 	at com.Zrips.CMI.Containers.CMIUser.respawn(CMIUser.java:1684)
[15:13:28 WARN]: 	at com.Zrips.CMI.AllListeners.UserEvents$4.run(UserEvents.java:211)
[15:13:28 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[15:13:28 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1111)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1057)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:902)
[15:13:28 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
15:13:28 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.DedicatedPlayerList.moveToWorld(net.minecraft.server.v1_14_R1.EntityPlayer, org.bukkit.craftbukkit.v1_14_R1.CraftServer$3, boolean)
[15:13:28 WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2109)
[15:13:28 WARN]: 	at com.Zrips.CMI.Reflections.respawn(Reflections.java:1150)
[15:13:28 WARN]: 	at com.Zrips.CMI.Containers.CMIUser.respawn(CMIUser.java:1684)
[15:13:28 WARN]: 	at com.Zrips.CMI.AllListeners.UserEvents$4.run(UserEvents.java:211)
[15:13:28 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[15:13:28 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1111)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1057)
[15:13:28 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:902)
[15:13:28 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Cmi Version (using`/cmi version`): 8.6.12** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`): Paper(11) 1.14-R0.1-SNAPSHOT **

**Comment by Zrips** [comment]
Should be in working order now
