### ISSUE TITLE
Make homes gui wool a configurable choice

### ISSUE THREAD

**Issue by runelynx** [Zrips/CMI#1723]
Re: this...
For time being (1.14 servers only) icons in home gui will be random wool instead of material dependent on actual location. This is due to major performance issue in 1.14 while getting block type of unloaded chunk. Awaiting fix and then we can re enable this feature. Maybe 1.14.1 fixes this one...

-=-=-=-=-=

Sourcing the unloaded chunk breaks the homes GUI altogether for those of us who use resource worlds (and reset the world occasionally). Please allow us to choose to use wool in any version if we want so there's no logic to look for chunk data (that doesnt exist).

**Comment by runelynx** [comment]
I raised a separate issue for the bug that exists in the above scenario, as FYI...   if CMI can't find the chunk to get the block (because we regen the world), that user can no longer use the homes GUI at all. An exception is thrown saying the batch is already started.

**Comment by runelynx** [comment]
Still a problem in 8.6.1.3

 16:04:13
16:04:13org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.1.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: y out of range (expected 0-255, got -1)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.craftbukkit.v1_13_R2.CraftChunk.validateChunkCoordinates(CraftChunk.java:293) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at org.bukkit.craftbukkit.v1_13_R2.CraftChunkSnapshot.getBlockType(CraftChunkSnapshot.java:61) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
at com.Zrips.CMI.Containers.CMILocation.getBlockCMIType(CMILocation.java:184) ~[?:?]
at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:375) ~[?:?]
at com.Zrips.CMI.commands.list.homes.perform(homes.java:55) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2-R0.1-SNAPSHOT.jar:git-Spigot-5629554-4c8327f]
... 15 more

**Comment by Zrips** [comment]
Error was fixed, tho another fix will be coming out today. And will add option (config file) to pick random wool color instead of real block

**Comment by runelynx** [comment]
The configurable option works great, thank you!!
