### ISSUE TITLE
Warp bug

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#1733]
I am trying to warp to a world. I used WorldResetPlus to reset my world, and when I go to the world it says that there is no safe place. Then when I /mv tp world type /warp it shows the error below.

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
 [06:23:48 INFO]: TCC issued server command: /cmi warp mine
[06:23:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.1.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.jar:git-Paper-15]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.jar:git-Paper-15]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:118) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:96) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:106) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:972) ~[patched_1.14.jar:git-Paper-15]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.jar:git-Paper-15]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at net.minecraft.server.v1_14_R1.PlayerList.moveToWorld(PlayerList.java:681) ~[patched_1.14.jar:git-Paper-15]
at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:783) ~[patched_1.14.jar:git-Paper-15]
at com.Zrips.CMI.Modules.tp.Teleportations.finalizeTeleport(Teleportations.java:509) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:335) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:300) ~[?:?]
at com.Zrips.CMI.commands.list.warp.perform(warp.java:144) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.jar:git-Paper-15]
... 17 more
```

**Cmi Version (using`/cmi version`):** 8.6.1.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.14

**Relevant plugins (Delete if this isn't needed):** 
WorldResetPlus

**Comment by Zrips** [comment]
Issue seems to originate from something different then CMI, as it point to generic API method where player gets teleported to target location which by itself have been checked to be none null value with existing world. Hard to say where actual cause is, but it could be WorldResetPlus result of world not being properly reset or created in 1.14
