### ISSUE TITLE
 [CMI] Plugin CMI v8.6.1.4 generated an exception while executing task 957

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1739]
[17:21:38] [Craft Scheduler Thread - 24/WARN]: [CMI] Plugin CMI v8.6.1.4 generated an exception while executing task 957
java.lang.NoSuchFieldError: dimension
	at com.Zrips.CMI.NBT.v1_14_R1.updatePlayerViaPackets(v1_14_R1.java:1555) ~[?:?]
	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:100) ~[?:?]
	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:90) ~[?:?]
	at com.Zrips.CMI.Modules.Skin.SkinListener$2$1.run(SkinListener.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-f8e1ae2-a46ef53]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [minecraft_server.jar:git-Spigot-f8e1ae2-a46ef53]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]

**Comment by Zrips** [comment]
Well from your error it seems that Spigot API changed again in mid version... Will have to update it with next version. Should be ok with next build.

**Comment by Zrips** [comment]
Was this latest spigot version?
