### ISSUE TITLE
Error command /cmi tmb

### ISSUE THREAD

**Issue by ludvdber** [Zrips/CMI#174]
Hello,
we get an error in the console when we forget to put a text after %subtitle%
for example: /cmi test %subtitle%
here is the error:

```
[12:03:49] [Server thread/WARN]: Unexpected exception while parsing console command "cmi tmb test %subtitle%"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v7.6.1.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot.jar:git-Spigot-c3093ef-aa25568]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-c3093ef-aa25568]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-c3093ef-aa25568]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.Zrips.CMI.commands.list.tmb.perform(tmb.java:37) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-c3093ef-aa25568]
	... 8 more
```

**Comment by LogGits** [comment]
@Zrips `/cmi tmb test %subtitle%` should catch the exception and send a message to the player saying that they have used to command incorrectly and to actually specify a subtitle. Example: `Invalid usage: Please specify a subtitle after the %subtitle% syntax.`

**Comment by LogGits** [comment]
@Zrips has fixed this. In the next update it will just exclude the subtitle.
