### ISSUE TITLE
at com.Zrips.CMI.Modules.Sheduler.Schedule.perform(Schedule.java:225) [CMI8.6.1.5.jar:?]

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1743]
**I always have the error message since the update. where also cmi occurs in it. what can I do against it. my console writes itself fully**

[01:40:38] [Server thread/ERROR]: Failed to save chunk -11,3
net.minecraft.server.v1_14_R1.ReportedException: Saving entity NBT
	at net.minecraft.server.v1_14_R1.Entity.save(Entity.java:1552) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.Entity.c(Entity.java:1439) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.Entity.d(Entity.java:1447) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.ChunkRegionLoader.saveChunk(ChunkRegionLoader.java:318) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:584) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.saveChunk(PlayerChunkMap.java:551) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.lambda$8(PlayerChunkMap.java:271) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_201]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_201]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_201]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_201]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_201]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.save(PlayerChunkMap.java:266) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.save(ChunkProviderServer.java:189) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:766) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.MinecraftServer.saveChunks(MinecraftServer.java:636) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.CommandSaveAll.a(SourceFile:34) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.CommandSaveAll.b(SourceFile:20) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.CommandDispatcher.a(CommandDispatcher.java:172) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at org.bukkit.craftbukkit.v1_14_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:689) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:648) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:129) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:97) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:93) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.Sheduler.Schedule.perform(Schedule.java:225) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.Sheduler.Schedule.safePerform(Schedule.java:210) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.Sheduler.SchedulerManager.checkSchedulers(SchedulerManager.java:287) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.Sheduler.SchedulerManager.access$0(SchedulerManager.java:280) [CMI8.6.1.5.jar:?]
	at com.Zrips.CMI.Modules.Sheduler.SchedulerManager$1.run(SchedulerManager.java:273) [CMI8.6.1.5.jar:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_14_R1.Entity.save(Entity.java:1473) ~[minecraft_server.jar:git-Spigot-f8e1ae2-58db403]
	... 46 more

**Comment by Zrips** [comment]
It looks more like an issue with server failing to save a chunk. Duno what command was used in scheduler, but in general its not a issue with CMI but with server itself.
