### ISSUE TITLE
[CMI] Task #911 for CMI v8.6.1.5 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1751]
CraftBukkit version git-Spigot-8043ebc-89c52b7 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)

CMI-Ver.8.6.1.5

[07:50:07] [Server thread/WARN]: java.lang.NoSuchFieldException: dimension
[07:50:07] [Server thread/WARN]: 	at java.lang.Class.getField(Unknown Source)
[07:50:07] [Server thread/WARN]: 	at com.Zrips.CMI.Reflections.getDimensionManager(Reflections.java:561)
[07:50:07] [Server thread/WARN]: 	at com.Zrips.CMI.Reflections.respawn(Reflections.java:1148)
[07:50:07] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.respawn(CMIUser.java:1684)
[07:50:07] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.UserEvents$4.run(UserEvents.java:211)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[07:50:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956)
[07:50:07] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801)
[07:50:07] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[07:50:07] [Server thread/WARN]: [CMI] Task #911 for CMI v8.6.1.5 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.Reflections.respawn(Reflections.java:1150) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.respawn(CMIUser.java:1684) ~[?:?]
	at com.Zrips.CMI.AllListeners.UserEvents$4.run(UserEvents.java:211) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [Spigot-latest.jar:git-Spigot-8043ebc-89c52b7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Zrips** [comment]
Will be fixed with todays update
