### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1775]
**Description of issue or feature request:**

This error is spamming console everytime a player logs in

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[09:15:26] [Server thread/INFO]: pvpCARLOS12[/199.127.63.194:54759] logged in with entity id 12621 at ([world]93.73005622517573, 32.7967356006687, -8.374608728845885)
[09:15:26] [Server thread/WARN]: [CMI] Task #7709678 for CMI v8.6.1.3 generated an exception
java.lang.NoSuchMethodError: org.bukkit.ChunkSnapshot.getBlockType(III)Lorg/bukkit/Material;
	at com.Zrips.CMI.Containers.CMILocation.getBlockCMIType(CMILocation.java:187) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.isEmpty(Teleportations.java:550) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:592) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:396) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:311) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:284) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners$6.run(PlayerListeners.java:788) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.1.3
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.8.8
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should no longer happen.
