### ISSUE TITLE
Cmi custom alias ifempty causing exception in 1.14.1

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1784]
```
[02:02:30] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.6.3.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.canPerformCommand(SpecializedCommandManager.java:984) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:614) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:429) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:86) ~[?:?]
	at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:99) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-9bda413]
	... 18 more
>
```
today's cmi and spigot build.
```
>ver
[02:03:11] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-8043ebc-9bda413 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
[02:03:11] [Server thread/INFO]: Checking version, please wait...
[02:03:12] [Thread-5/INFO]: You are running the latest version
>ver cmi
[02:03:13] [Server thread/INFO]: CMI version 8.6.3.0
[02:03:13] [Server thread/INFO]: Powerful server management tool
[02:03:13] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[02:03:13] [Server thread/INFO]: Author: Zrips
>
```
custom alias is:
```
CustomAlias:
  test:
    Cmds:
    - cooldown:5#?! msg! [playerName] debug cooldown test (not in cooldown)
    - ifempty:$1#?! msg! [playerName] debug empty s1 test $1 (not empty)
    - ifonline:$1#?! msg! [playerName] debug target online test $1 (is online)
    - fromConsole! broadcast! &6 welp [playerName] says hi
    - fromConsole! cmi sound item_trident_return -p:0.8 -v:0.8 [playerName]
```

Seems when i use `ifempty` it starts failing.

**Comment by mrfloris** [comment]
OH MY NOTCH

```
New specialized command variable ifempty:[value][?][#]! which will check by hand, offhand, quickbar, subinv, armor, inv variables if players inventory is empty by those criteria.
```

I completely misunderstood ifempty ...
