### ISSUE TITLE
Error when players execute a command

### ISSUE THREAD

**Issue by Daxxas** [Zrips/CMI#1794]
**Description of issue or feature request:** Error when players execute command

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

[18:03:33 INFO]: Kajjou issued server command: /home res
[18:03:36 WARN]: java.lang.NumberFormatException: For input string: "0,51"
[18:03:36 WARN]:        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
[18:03:36 WARN]:        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[18:03:36 WARN]:        at java.lang.Double.parseDouble(Double.java:538)
[18:03:36 WARN]:        at java.lang.Double.valueOf(Double.java:502)
[18:03:36 WARN]:        at com.Zrips.CMI.Containers.CMIHitBox.getHeightAtLocation(CMIHitBox.java:74)
[18:03:36 WARN]:        at com.Zrips.CMI.Modules.tp.Teleportations.getUpLocation(Teleportations.java:756)
[18:03:36 WARN]:        at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:405)
[18:03:36 WARN]:        at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:309)
[18:03:36 WARN]:        at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:298)
[18:03:36 WARN]:        at com.Zrips.CMI.commands.list.home.perform(home.java:146)
[18:03:36 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:262)
[18:03:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[18:03:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:03:36 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[18:03:36 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.performCommand(CraftPlayer.java:323)
[18:03:36 WARN]:        at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.performCmd(WarmUpManager.java:159)
[18:03:36 WARN]:        at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.access$0(WarmUpManager.java:149)
[18:03:36 WARN]:        at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager$1.run(WarmUpManager.java:176)
[18:03:36 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[18:03:36 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[18:03:36 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[18:03:36 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[18:03:36 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[18:03:36 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[18:03:36 WARN]:        at java.lang.Thread.run(Thread.java:745)

```

---

**Cmi Version (using`/cmi version`):** 8.6.3.0

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):** This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should no longer be the issue
