### ISSUE TITLE
[BUG]  ???  Error occurred while enabling

### ISSUE THREAD

**Issue by Someone-NEW** [Zrips/CMI#1797]
What to say i dont know where to locate this, but i will just paste my error here and hope i give help to resolve this big problem.
[21:56:17 ERROR]: Error occurred while enabling CMI v8.6.3.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.ALPINE
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_161]
        at org.bukkit.block.Biome.valueOf(Biome.java:1) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at com.Zrips.CMI.Config.lambda$3(Config.java:554) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.Sink$ChainedReference.end(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_161]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_161]
        at com.Zrips.CMI.Config.LoadLang(Config.java:553) ~[?:?]
        at com.Zrips.CMI.Config.LoadLang(Config.java:427) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1469) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[21:56:17 INFO]: [Vault][Economy] CMI Economy hooked.

EDIT: And i see now all placeholder not work for me too....... :(
EDIT2: And btw some old report not fixed yet:
https://pastebin.com/f5AdeAVn
https://pastebin.com/CVMAYh4g
https://pastebin.com/tZp09Xrb
Perhaps now with these old reports this time is maybe a problem with the placeholders who do not work this time, as the PlaceholdersAPI passes the full time to the new system.

**Comment by Someone-NEW** [comment]
And new report: https://pastebin.com/Sp2bw0De

**Comment by Zrips** [comment]
This got patched
