### ISSUE TITLE
CMI Problem in the 1.14.2 *Could not pass event CMIPlayerUnVanishEvent to CMI v8.6.4.0*

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#1842]
CraftBukkit version git-Spigot-093165d-cb3d14c (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

[00:31:43] [Server thread/ERROR]: Could not pass event CMIPlayerUnVanishEvent to CMI v8.6.4.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:118) [CMI8.6.4.0.jar:?]
	at com.Zrips.CMI.Modules.Vanish.VanishListener.onPlayerJoinHideOthers(VanishListener.java:128) [CMI8.6.4.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:173) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:149) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:230) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1080) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at org.dynmap.bukkit.DynmapPlugin.assertPlayerInvisibility(DynmapPlugin.java:1540) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:41) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:31) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapListener.CMIPlayerUnVanishEvent(DynMapListener.java:20) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot-latest.jar:git-Spigot-093165d-cb3d14c]
	... 23 more

**Comment by Zrips** [comment]
Will be fixed with next build
