### ISSUE TITLE
When a players join the server

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#1898]
Description of issue: When a player joins the server. Spigot 1.12.2
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
08.06 06:41:34 [Server] INFO UUID of player po4ap01 is 6fd63bf8-cc4f-38b0-84dd-99864c962d2a
08.06 06:41:34 [Server] WARN java.io.EOFException
08.06 06:41:34 [Server] WARN at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
08.06 06:41:34 [Server] WARN at java.io.DataInputStream.readUTF(DataInputStream.java:589)
08.06 06:41:34 [Server] WARN at java.io.DataInputStream.readUTF(DataInputStream.java:564)
08.06 06:41:34 [Server] WARN at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:98)
08.06 06:41:34 [Server] WARN at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2579)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
08.06 06:41:34 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
08.06 06:41:34 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
08.06 06:41:34 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
08.06 06:41:34 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

Cmi Version (using`/cmi version`): 8.6.4.4

**Server Type (Spigot/Paperspigot/etc): Spigot 1.12.2

**Server Version (using `/ver`): CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Fixed
