### ISSUE TITLE
Duplicate handler name: CMIPacketInjector4

### ISSUE THREAD

**Issue by TakoidGit** [Zrips/CMI#1901]
**Description of issue:**
When players come in range of holograms the console spams warnings.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:48:43 WARN]: java.lang.IllegalArgumentException: Duplicate handler name: CMIPacketInjector4
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1101)
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:302)
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:259)
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
[17:48:43 WARN]:        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
[17:48:43 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:269)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Packets.PacketInjector.addPlayer(PacketInjector.java:54)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:616)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:596)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.addNearHolo(HologramManager.java:629)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.handleHoloUpdates(HologramManager.java:273)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramListener.onPlayerMoveExtendedRnage(HologramListener.java:59)
[17:48:43 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor703.execute(Unknown Source)
[17:48:43 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:48:43 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:48:43 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:48:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1103)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[17:48:43 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:48:43 WARN]: java.lang.IllegalArgumentException: Duplicate handler name: CMIPacketInjector4
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1101)
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:302)
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:259)
[17:48:43 WARN]:        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
[17:48:43 WARN]:        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
[17:48:43 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:269)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Packets.PacketInjector.addPlayer(PacketInjector.java:54)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:616)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:596)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.addNearHolo(HologramManager.java:629)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.handleHoloUpdates(HologramManager.java:273)
[17:48:43 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramListener.onPlayerMoveExtendedRnage(HologramListener.java:59)
[17:48:43 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor703.execute(Unknown Source)
[17:48:43 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:48:43 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:48:43 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:48:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1103)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974)
[17:48:43 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[17:48:43 WARN]:        at java.lang.Thread.run(Unknown Source)
```
---

It seems to be related to hologram update range as coming within range of a hologram that needs to update causes the warn.

---

**Cmi Version (using`/cmi version`):** 8.6.4.5

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper-70

**Comment by Zrips** [comment]
Should be ok with latest build
