### ISSUE TITLE
[BUG] Offline voters causing exception error in cmi

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1908]
At times it seems that if someone votes before connecting to the server, that the nuVotifier/VotingPlugin and CMI do not play nice, causing a flood of exception errors. 3 builds ago this didn't happen. 

---
```
[18:32:25 INFO]: [Votifier] Got a protocol v1 vote record from /(removed):48158 -> Vote (from:PlanetMinecraft.com username:(removed) address:(removed) timeStamp:1560097945 localTimestamp:1560097945558)
[18:32:25 INFO]: [VotingPlugin] Recieved a vote from 'PlanetMinecraft.com(removed)' by player '(removed)'!
[18:32:25 ERROR]: Could not pass event VotifierEvent to CMI v8.6.4.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:368) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.4.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:655) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:723) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:685) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:129) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:97) ~[?:?]
        at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:145) ~[?:?]
        at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:25) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        ... 11 more
```

```
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.getServer(BungeeCordAPI.java:258) ~[?:?]
        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.getThisServerName(BungeeCordManager.java:610) ~[?:?]
        at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:347) ~[?:?]
        at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:201) ~[?:?]
        at com.Zrips.CMI.Locale.Language.getMessage(Language.java:108) ~[?:?]
        at com.Zrips.CMI.CMI.info(CMI.java:1882) ~[?:?]
        at com.Zrips.CMI.CMI.info(CMI.java:1877) ~[?:?]
        at com.Zrips.CMI.commands.list.give.perform(give.java:323) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:655) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:723) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:685) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:129) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:97) ~[?:?]
        at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:145) ~[?:?]
        at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:25) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-dfa7583]
        ... 11 more
>
```

```
>ver
[18:55:12 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[18:55:12 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
>ver cmi
[18:55:13 INFO]: CMI version 8.6.4.5
[18:55:13 INFO]: Powerful server management tool
[18:55:13 INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[18:55:13 INFO]: Author: Zrips
>
```

**Comment by Zrips** [comment]
Second error i can fix, more or less, but for the first one. Can you give me command example you are performing when player votes?

**Comment by mrfloris** [comment]
When someone votes, it checks if the vote site is known, using VotingPlugin.jar which then runs the VoteReward.yml for that particular site. 

```
# This is a reward file
# Define rewards in here (Items, commands, etc)
# File name is the reward name, without file extention
# This reward is named "ExampleBasic"
# That is what you put as a reward for other plugins, like VotingPlugin
# DO NOT HAVE DUPLICATE NAMES!!

# Wiki Page: 
# https://github.com/Ben12345rocks/AdvancedCore/wiki/Reward-files

# This is basic reward file
# You can have multiple reward files that contain all kinds of rewards
# Below are some basic things you can have, see the advanced example for more

# You can just remove values you don't want (just delete it)
# If you just want money just have a reward file containg only "Money: 100", for example
# You can simply copy and paste from here what you want
# in other reward files, that is the way they are designed


# Amount of money to give, requires vault
# Use 0 to give none
# Money is not per world
# Use negative to take money
# Money: 1000

# Pick random number between min and max amount
MinMoney: 1000
MaxMoney: 2500

# Give player experience
# EXP: 100

# Pick a random number between min and max amount to give
MinEXP: 100
MaxEXP: 500

# Commands to run
# Use %player% for player name
# Set to Console: [] for no commands
Commands:
  # Commands here will be run by console
  Console:
  - 'welcomes add %player% 1'
  - 'cmi broadcast !&3 1MB Vote »&7 Thank you &b❤ &6%player%&7 for voting on &n%SiteName%&r&7!'
  - 'cmi msg %player% !&3 Rewards: »&7 A Diamond, $%money% /money, +%exp% /exp, & /points +1'
  - 'cmi kit VoteSiteOne %player%'
  # Commands here are run by player
  # Player:
  # - 'vote points'

# The messages are sent when rewards above are given to user
# set to '' to give no message
# If no value is set, default in Format.yml is used
# Messages:
#   Player: '&aMessage on reward for vote site 1'
#   Broadcast: '&aThis is a broadcast for vote site 1'

# Sound on reward
Sound:
  # Enable or Disable Sound
  Enabled: true
  # Sound to play
  # 1.9 Sounds: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # 1.8: https://jd.bukkit.org/org/bukkit/Sound.html 
  Sound: 'BLOCK_TRIPWIRE_CLICK_ON'
  # Volume
  # Range: 0.0 to 1.0
  Volume: 1.0
  # Pitch
  # Range: 0.0 to 2.0
  Pitch: 1.0
```

**Comment by mrfloris** [comment]
The latest build has this resolved, I no longer have this issue, closing ticket. Thank you Z.
