### ISSUE TITLE
[Request] Prevent "Main thread call"

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1921]
**Description of feature/improvement request:**

---
### Basic explanation why this feature is needed in CMI and how useful it would be to have it ###
I was experimenting with a program to investigate plugins on the main thread.
CMI appears to call the main thread.
```
[09:38:23 WARN]: [TruAntiLag] Main thread call, Bad!: https://api.spigotmc.org/legacy/premium.php?user_id=566677&resource_id=3742&nonce=-1282196663
[09:38:23 WARN]: [TruAntiLag] Please notify the developer! https://git.io/vA9m2
[09:38:23 ERROR]: Error occurred while enabling CMI v8.6.4.6 (Is it up to date?)
java.lang.RuntimeException: No touchy touchy my main thready
at net.poweredbyhate.truantilag.BadDetector.select(BadDetector.kt:17) ~[?:?]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150) ~[?:1.8.0_212]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_212]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_212]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[?:1.8.0_212]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_212]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_212]
at com.Zrips.CMI.CMI.loadConfig0(CMI.java) ~[?:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-630]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-630]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-630]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-630]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-630]
at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-630]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-630]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-630]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-630]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-630]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[09:38:23 INFO]: [CMI] Disabling CMI v8.6.4.6
[09:38:23 WARN]: java.lang.NullPointerException
[09:38:23 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramManager.load(HologramManager.java:329)
[09:38:23 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramManager.<init>(HologramManager.java:59)
[09:38:23 WARN]: at com.Zrips.CMI.CMI.getHologramManager(CMI.java:591)
[09:38:23 WARN]: at com.Zrips.CMI.CMI.onDisable(CMI.java:1025)
[09:38:23 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[09:38:23 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[09:38:23 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[09:38:23 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[09:38:23 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[09:38:23 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[09:38:23 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[09:38:23 WARN]: at java.lang.Thread.run(Thread.java:748)
[09:38:23 WARN]: java.lang.NullPointerException
[09:38:23 WARN]: at com.Zrips.CMI.Modules.Portals.PortalManager.load(PortalManager.java:324)
[09:38:23 WARN]: at com.Zrips.CMI.Modules.Portals.PortalManager.<init>(PortalManager.java:60)
[09:38:23 WARN]: at com.Zrips.CMI.CMI.getPortalManager(CMI.java:615)
[09:38:23 WARN]: at com.Zrips.CMI.CMI.onDisable(CMI.java:1136)
[09:38:23 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267)
[09:38:23 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:368)
[09:38:23 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:444)
[09:38:23 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[09:38:23 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[09:38:23 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[09:38:23 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316)
[09:38:23 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787)
[09:38:23 WARN]: at java.lang.Thread.run(Thread.java:748)
```
Links in the log:
https://api.spigotmc.org/legacy/premium.php?user_id=566677&resource_id=3742&nonce=-1282196663
https://git.io/vA9m2 ( points to https://github.com/aikar/TaskChain/wiki/Why-TaskChain )

Tested with CMI 8.6.4.6
Paper 1.13.2 build 630

**Comment by Zrips** [comment]
Every plugin is running on main thread and only some features could be run async or should be run in async. So i'm confused here.

**Comment by x1p** [comment]
I wouldn't know if this is a legit check. Thanks anyway.
