### ISSUE TITLE
BungeeCord|Report errors

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#1925]
This error will occur when players cross the clothes.
And money doesn't synchronize across clothes.
-------------------------------------------------------
[Server thread/WARN]: java.io.EOFException
at java.io.DataInputStream.readUnsignedShort(Unknown Source)
at java.io.DataInputStream.readUTF(Unknown Source)
at java.io.DataInputStream.readUTF(Unknown Source)
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.updatePlayerInfoOnNetwork(BungeeCordManager.java:451)
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:252)
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426)
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2579)
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58)
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8)
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
at java.lang.Thread.run(Unknown Source)

spigot 1.12.2
cmi 8.6.4

**Comment by Zrips** [comment]
Clothes? Whats that?
Next, you provided partial plugin version and error log is not a full one, so i cant address this issue properly without accurate information. Make another ticket with correct information. Closing this one as off invalid format.
