### ISSUE TITLE
【BungeeCord 】Sometimes an error is reported.

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#1928]
spigot-1.12.2
cmi-8.6.4
Sorry, my English is not good.
I can only show you the contents of the error report.
This error occurs when the player【/stp Existence2】
MYSQL Storage Method Used
But the two servers do not use the same database
Because money cannot be synchronized with the same database, I use two databases.

------------------------------------
```
[23:49:22] [Server thread/INFO]: feifei issued server command: /stp Existence2
[23:49:22] [Server thread/WARN]: java.io.EOFException
[23:49:22] [Server thread/WARN]: 	at java.io.DataInputStream.readUnsignedShort(Unknown Source)
[23:49:22] [Server thread/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[23:49:22] [Server thread/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[23:49:22] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.updatePlayerInfoOnNetwork(BungeeCordManager.java:451)
[23:49:22] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:252)
[23:49:22] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2579)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[23:49:22] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:49:22] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[23:49:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[23:49:22] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:49:22] [Server thread/INFO]: feifei lost connection: Disconnected
[23:49:23] [Async Chat Thread - #203/INFO]: [0;31;1m?[0;35;1mSkin_YIYI[0;31;1m?[m[m[0;36;1m[[0;33;22m园王[0;36;1m][0;33;22m[m[0;36;1m[[0;37;1mye11ow1ove[0;36;1m][m[0;37;22m: [m[0;33;22m洗澡睡觉了[m
[23:49:24] [Server thread/WARN]: java.io.EOFException
[23:49:24] [Server thread/WARN]: 	at java.io.DataInputStream.readUnsignedShort(Unknown Source)
[23:49:24] [Server thread/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[23:49:24] [Server thread/WARN]: 	at java.io.DataInputStream.readUTF(Unknown Source)
[23:49:24] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.updatePlayerInfoOnNetwork(BungeeCordManager.java:451)
[23:49:24] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:252)
[23:49:24] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2579)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[23:49:24] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:49:24] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[23:49:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[23:49:24] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by momoservertw** [comment]
I have this error too after player login. And it will freeze the server.

**Comment by Zrips** [comment]
This should have disappeared with new bungee handling method by using an additional plugin on bungee server.
