### ISSUE TITLE
/homes error

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1945]
**Description of issue:**
When you do /homes or /homes Nick, there is an error, and the homes are not listed.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[15:39:27] [Server thread/INFO]: OptimusCraft issued server command: /homes
[15:39:28] [Server thread/WARN]: java.lang.NullPointerException
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.Reflections.setNbt(Reflections.java:937)
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GUI.CMIGuiButton.getItem(CMIGuiButton.java:372)
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GUI.GUIManager.generateInventory(GUIManager.java:261)
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GUI.GUIManager.openGui(GUIManager.java:305)
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GUI.CMIGui.open(CMIGui.java:91)
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:439)
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.homes.perform(homes.java:55)
[15:39:28] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264)
[15:39:28] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:39:28] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:39:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:39:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:39:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:39:28] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:39:28] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:39:28] [Server thread/ERROR]: null
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.5.1 (also on older versions, same error)
**Server Type (Spigot/Paperspigot/etc):** 
spigot or paper, both get same error
**Server Version (using `/ver`):** 
1.8.8
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Fixed
