### ISSUE TITLE
Error spamming console

### ISSUE THREAD

**Issue by abhisantos** [Zrips/CMI#1948]
**Description of issue:**
This error is spamming console in the new version
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:17:45] [Server thread/WARN]: java.io.EOFException
[14:17:45] [Server thread/WARN]: 	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
[14:17:45] [Server thread/WARN]: 	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
[14:17:45] [Server thread/WARN]: 	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
[14:17:45] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.updatePlayerInfoOnNetwork(BungeeCordManager.java:451)
[14:17:45] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:252)
[14:17:45] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2114)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:55)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:8)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[14:17:45] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:17:45] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[14:17:45] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[14:17:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.5.1
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.8.8
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should no longer be an issue with new bungee handling
