### ISSUE TITLE
Random teleportation can't find teleport location

### ISSUE THREAD

**Issue by Daxxas** [Zrips/CMI#1970]
**Description of issue:**
I just updated the plugin to the latest version, and now the /rt keeps saying "Could not find correct teleport location, please wait 3 sec and try again". It worked well before.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```

[13:31:02 INFO]: Taodav issued server command: /rt
[13:31:02 WARN]: [CMI] Plugin CMI v8.6.5.2 generated an exception while executing task 2553862
java.lang.IllegalStateException: [AWE] Chunk not found for [472,-277]. Loading from async thread is not supported.
        at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java) ~[?:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.World.getChunkAt(World.java:267) ~[Spigot.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.World.getChunkAtWorldCoords(World.java:263) ~[Spigot.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.World.getType(World.java:658) ~[Spigot.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.World.rayTrace(World.java:703) ~[Spigot.jar:git-Spigot-1a3504a-dfa7583]
        at net.minecraft.server.v1_13_R2.World.rayTrace(World.java:685) ~[Spigot.jar:git-Spigot-1a3504a-dfa7583]
        at com.Zrips.CMI.NBT.v1_13_R2.getBlockLookingAt(v1_13_R2.java:1889) ~[CMI8.6.5.2.jar:?]
        at com.Zrips.CMI.Containers.CMIHitBox.getCollidingdBlock(CMIHitBox.java:369) ~[CMI8.6.5.2.jar:?]
        at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:352) ~[CMI8.6.5.2.jar:?]
        at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:344) ~[CMI8.6.5.2.jar:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:590) ~[CMI8.6.5.2.jar:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:396) ~[CMI8.6.5.2.jar:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.getRandomLocation(Teleportations.java:900) ~[CMI8.6.5.2.jar:?]
        at com.Zrips.CMI.commands.list.rt$1.run(rt.java:108) ~[CMI8.6.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot.jar:git-Spigot-1a3504a-dfa7583]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-1a3504a-dfa7583]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    farm:
      Enabled: true
      MaxRange: 10000
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: true
      IgnoreWater: false
      IgnoreLava: false
      minY: 50
      maxY: 256
```

---

**Cmi Version (using`/cmi version`):** 8.6.5.2

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[13:32:40 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.

**Comment by impmallet** [comment]
+1 same issue since updating to this version.

**Comment by impmallet** [comment]
Posting again, as this is still an issue.

Please prioritize fixing this over adding new features. A good deal of servers, including my own, use this function for new players.

**Comment by Zrips** [comment]
Will do some changes, more or less reverting back to previous state which should solve issue for 1.13.2 and older servers. 1.14+ can still be... picky... Test it out and if issue persists, please let me know.
