### ISSUE TITLE
invisibility issue

### ISSUE THREAD

**Issue by BeeRando** [Zrips/CMI#1978]
**Description of issue:**
Console error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/Wjwk69uK
```
28.06 22:43:05 [Server] Server thread/ERROR Could not pass event CMIPlayerUnVanishEvent to CMI v8.6.5.1
28.06 22:43:05 [Server] INFO org.bukkit.event.EventException: null
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:118) [CMI8.6.5.1.jar:?]
28.06 22:43:05 [Server] INFO at com.Zrips.CMI.Modules.Vanish.VanishListener.onPlayerJoinHideOthers(VanishListener.java:128) [CMI8.6.5.1.jar:?]
28.06 22:43:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:173) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:149) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:53) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:230) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:119) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1076) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:955) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:800) [Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
28.06 22:43:05 [Server] INFO Caused by: java.lang.NullPointerException
28.06 22:43:05 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.assertPlayerInvisibility(DynmapPlugin.java:1543) ~[?:?]
28.06 22:43:05 [Server] INFO at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:42) ~[?:?]
28.06 22:43:05 [Server] INFO at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:30) ~[?:?]
28.06 22:43:05 [Server] INFO at com.Zrips.CMI.Modules.DynMap.DynMapListener.CMIPlayerUnVanishEvent(DynMapListener.java:20) ~[?:?]
28.06 22:43:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
28.06 22:43:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot_Latest_1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
28.06 22:43:05 [Server] INFO ... 23 more
```
**Cmi Version (using`/cmi version`):** 
8.6.5.1
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
latest 1.14.3 build
**Relevant plugins (Delete if this isn't needed):**
dynmap

**Comment by Zrips** [comment]
Should be fixed with next build
