### ISSUE TITLE
When a player use /rt command in console error

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#1980]
Description of issue:
When a player use /rt command and teleports.
---
ERROR:
```
29.06 04:43:51 [Server] INFO vasya issued server command: /rt
29.06 04:43:51 [Server] WARN [CMI] Plugin CMI v8.6.5.4 generated an exception while executing task 258111
29.06 04:43:51 [Server] INFO java.lang.IllegalStateException: Asynchronous entity track!
29.06 04:43:51 [Server] INFO at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.EntityTracker.addEntity(EntityTracker.java:108) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.EntityTracker.track(EntityTracker.java:82) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:21) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.World.b(World.java:1093) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.b(WorldServer.java:1163) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:1128) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.Chunk.addEntities(Chunk.java:753) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:138) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:95) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:568) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.Location.getBlock(Location.java:91) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at com.Zrips.CMI.Modules.tp.Teleportations.getRandomLocation(Teleportations.java:891) ~[?:?]
29.06 04:43:51 [Server] INFO at com.Zrips.CMI.commands.list.rt$1.run(rt.java:108) ~[?:?]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [survival.jar:git-Spigot-e8ded36-acbc348]
29.06 04:43:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
29.06 04:43:51 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
29.06 04:43:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```
---

Cmi Version (using`/cmi version`): 8.6.5.4 BungeeCord

Server Type (Spigot/Paperspigot/etc): Spigot 1.12.2-R0.1-SNAPSHOT

Server Version (using `/ver`): CraftBukkit version git-Spigot-e8ded36-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next update
