### ISSUE TITLE
Small error in server stop (last version)

### ISSUE THREAD

**Issue by JavituRec** [Zrips/CMI#1988]
Hey,

I get a small error in console with last version server (1.14..3) and plugin.

`[16:52:50] [Server thread/INFO]: [CMI] Disabling CMI v8.6.5.4
[16:52:50] [Server thread/INFO]: [CMI]  SEVERE SAVE ERROR WHILE SAVING JavituRec PLAYER DATA (Balance)
[16:52:50] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:518)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:188)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:183)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:147)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.ScheduleDataClear(CMIUser.java:335)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:356)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:87)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:753)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:606)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:307)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1045)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:452)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:438)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:398)
[16:52:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:717)
[16:52:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:737)
[16:52:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:949)
[16:52:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:52:50] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:518)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:188)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:183)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:147)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.ScheduleDataClear(CMIUser.java:335)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:356)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:87)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:753)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:606)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:307)
[16:52:50] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1045)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:452)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:438)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
[16:52:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:398)
[16:52:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:717)
[16:52:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:737)
[16:52:50] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:949)
[16:52:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:52:50] [Server thread/INFO]: [CMI] Closed db connections`

**CMI version**
Last

**Server Type** 
Paperspigot

**Plugins relevants**
I am use modificated vault of CMI page and gringotts for economy.

**Comment by kaiarne** [comment]
Our server restart is hanging at [17:10:50 INFO]: [CMI] Disabling CMI v8.6.5.4

I discovered a flood of 
[17:10:44 ERROR]: Tried to load unrecognized recipe: and
[17:10:44 WARN]: Ignored advancement
directly after using /cmi info before. Maybe it's related.

**Comment by Zrips** [comment]
@JavituRec Will fix your issue with next release.
@kaiarne For your issue, its quite natural output (not a server hanging, that needs more info) if you ahve old player data and you transferred them into new version. In time they should update and convert to new format and you should no longer see those messages.
