### ISSUE TITLE
ERROR /cmi msg

### ISSUE THREAD

**Issue by stashenko** [Zrips/CMI#199]
Last updated CMI7.6.2.0. Before that, everything was fine.
If you enable ClickHoverMessages in config.yml  true, it generates an error:
```
[16:44:22] [Server thread/INFO]: stashenko issued server command: /cmi msg The_stas test msg
[16:44:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v7.6.2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.containsUrl(ChatFormatManager.java:226) ~[?:?]
	at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:181) ~[?:?]
	at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:133) ~[?:?]
	at com.Zrips.CMI.commands.list.msg.perform(msg.java:83) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-c3093ef-29705a0]
	... 15 more
```

**Comment by LogGits** [comment]
Latest version of CMI (was just published now) modifies links. Please retest this and let us know if you still get this error.

**Comment by stashenko** [comment]
CMI 7.6.3.0. 
Everything is working
