### ISSUE TITLE
Error ( Due to plugin I think)

### ISSUE THREAD

**Issue by nathans212** [Zrips/CMI#1993]
####################
####################
[11:52:37 INFO]: [CMI] Enabling CMI v8.6.5.4
[11:52:38 INFO]: [CMI] Citizens found.
[11:52:38 INFO]: [CMI] 47 Enabled and 0 Disabled modules
[11:52:38 ERROR]: [CMI] Plugin CMI v8.6.5.4 has failed to register events for class com.Zrips.CMI.Modules.EventActions.EventActionListener19 because org/bukkit/event/entity/EntityToggleGlideEvent does not exist.
[11:52:38 ERROR]: [CMI] Plugin CMI v8.6.5.4 has failed to register events for class com.Zrips.CMI.Modules.Elytra.ElytraBoostListener because org/bukkit/event/entity/EntityToggleGlideEvent does not exist.
[11:52:38 ERROR]: Error occurred while enabling CMI v8.6.5.4 (Is it up to date?)
java.lang.NoSuchFieldError: UNLOAD_CHUNK
        at com.Zrips.CMI.AllListeners.ProtocolEvent.includeViewRange(ProtocolEvent.java:54) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1331) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot.jar:git-Spigot-7d15d07-c194444]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot.jar:git-Spigot-7d15d07-c194444]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-7d15d07-c194444]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
#####################################
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
Newest  
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
You are 1622 version(s) behind
**Relevant plugins (Delete if this isn't needed):** 
 Plugins (40): BlockCreator, WorldEdit, SimpleTrading, PlaceholderAPI, ChatControl, UltraCustomizer, MessageAnnouncer, Lockette, Votifier, Multiverse-Core, WorldGuard, MobStacker, UltraPunishments, mcMMO, ViaVersion, InvRestore, GAListener, Vault, UltraPermissions, OreGeneratorRevolution, MassiveCore, EnjinMinecraftPlugin, ViaRewind, BlockParticles, TitleManager, ChestShop, CrateReloaded, DailyBonus, ProtocolLib, Citizens, Factions, MythicMobs, CMIEInjector, PlayerVaults, CommandNPC, WorldGuardExtraFlags, ArcadiaEnchants, CompatNoCheatPlus, Jobs, CMI

**Comment by Zrips** [comment]
It is error from CMI, but its informing that it did failed to register particular event. Hard to say which exact version of 1.9 you have, as you are 1622 versions behind. So update to latest version of that 1.9 (which should solve this issue) and if issue persists, give me to know with exact version of current minecraft version you are running.

**Comment by nathans212** [comment]
Hey, I found the error, it was a plugin and ur plugin not liking each other
