### ISSUE TITLE
BungeeCord error (PaperSpigot 1.14.3)

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/CMI#1995]
```
[16:56:57 WARN]: [CMI] Task #578 for CMI v8.6.5.4 generated an exception
java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.getServer(BungeeCordAPI.java:256) ~[?:?]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.getThisServerName(BungeeCordManager.java:600) ~[?:?]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager.initialize(BungeeCordManager.java:119) ~[?:?]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener$1$1.run(BungeeCordListener.java:171) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-120]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-120]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-120]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-120]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-120]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-120]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[16:57:06 INFO]: UUID of player Menled is dc8f4727-e5f7-3e2d-aae4-a1b201fdfed0
[16:57:06 INFO]: Menled[/185.93.62.6:57591] logged in with entity id 380 at ([world]-9999.482965881727, 100.5, -9999.300000011921)
[16:57:06 WARN]: java.lang.IllegalArgumentException: Can not set final it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap field net.minecraft.server.v1_14_R1.DataWatcher.d to java.util.HashMap
[16:57:06 WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[16:57:06 WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[16:57:06 WARN]: at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
[16:57:06 WARN]: at java.lang.reflect.Field.set(Field.java:764)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.DataWatcher.toNMS(DataWatcher.java:170)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.PacketPlayOutSpawnEntityLiving.toNMS(PacketPlayOutSpawnEntityLiving.java:164)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.Packet$1.write(Packet.java:95)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[16:57:06 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[16:57:06 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.lambda$b$4(NetworkManager.java:213)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:307)
[16:57:06 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:57:06 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:57:06 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:57:06 ERROR]: java.lang.NullPointerException
[16:57:06 WARN]: java.lang.NullPointerException
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.PacketPlayOutSpawnEntityLiving.b(SourceFile:96)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.PacketEncoder.encode(PacketEncoder.java:42)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.PacketEncoder.encode(PacketEncoder.java:12)
[16:57:06 WARN]: at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[16:57:06 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:57:06 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[16:57:06 WARN]: at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:455)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:63)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:229)
[16:57:06 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:235)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:06 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.Packet$1.write(Packet.java:101)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[16:57:06 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[16:57:06 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.lambda$b$4(NetworkManager.java:213)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:307)
[16:57:06 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:57:06 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:57:06 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:57:06 WARN]: java.lang.IllegalArgumentException: Can not set final it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap field net.minecraft.server.v1_14_R1.DataWatcher.d to java.util.HashMap
[16:57:06 WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[16:57:06 WARN]: at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[16:57:06 WARN]: at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
[16:57:06 WARN]: at java.lang.reflect.Field.set(Field.java:764)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.DataWatcher.toNMS(DataWatcher.java:170)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.PacketPlayOutSpawnEntityLiving.toNMS(PacketPlayOutSpawnEntityLiving.java:164)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.Packet$1.write(Packet.java:95)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[16:57:06 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[16:57:06 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.lambda$b$4(NetworkManager.java:213)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:307)
[16:57:06 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:57:06 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:57:06 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:57:06 ERROR]: java.lang.NullPointerException
[16:57:06 WARN]: java.lang.NullPointerException
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.PacketPlayOutSpawnEntityLiving.b(SourceFile:96)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.PacketEncoder.encode(PacketEncoder.java:42)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.PacketEncoder.encode(PacketEncoder.java:12)
[16:57:06 WARN]: at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
[16:57:06 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:57:06 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[16:57:06 WARN]: at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:455)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:63)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:229)
[16:57:06 WARN]: at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:235)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[16:57:06 WARN]: at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[16:57:06 WARN]: at me.neznamy.tab.bukkit.packets.Packet$1.write(Packet.java:101)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[16:57:06 WARN]: at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[16:57:06 WARN]: at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[16:57:06 WARN]: at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[16:57:06 WARN]: at net.minecraft.server.v1_14_R1.NetworkManager.lambda$b$4(NetworkManager.java:213)
[16:57:06 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:307)
[16:57:06 WARN]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[16:57:06 WARN]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[16:57:06 WARN]: at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[16:57:06 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:57:07 INFO]: Menled lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
```
---

**Cmi Version (using`/cmi version`):** 
8.6.5.4

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-120 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be fixed with next build
