### ISSUE TITLE
Minor encoder issues

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#1998]
**Description of issue:**
Now if you do /cmi itemnbt with an item with Attachedcommands will show the base64 of the command and not the command. (Idk if it's normal or not).
Trying to use an Attachedcommand encrypted with the wrong key doesn't work (good) but it throws an error in console:

```
[13:54:21 WARN]: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
[13:54:21 WARN]: 	at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
[13:54:21 WARN]: 	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
[13:54:21 WARN]: 	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
[13:54:21 WARN]: 	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
[13:54:21 WARN]: 	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
[13:54:21 WARN]: 	at com.Zrips.CMI.utils.CMIEncoder.decode(CMIEncoder.java:72)
[13:54:21 WARN]: 	at com.Zrips.CMI.Modules.CustomNBT.CustomNBTListener.decode(CustomNBTListener.java:363)
[13:54:21 WARN]: 	at com.Zrips.CMI.Modules.CustomNBT.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:120)
[13:54:21 WARN]: 	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
[13:54:21 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:54:21 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:54:21 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312)
[13:54:21 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[13:54:21 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[13:54:21 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[13:54:21 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304)
[13:54:21 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:271)
[13:54:21 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:267)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1260)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[13:54:21 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:54:21 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[13:54:21 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[13:54:21 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:54:21 INFO]: Fabrimat issued acmd command: /rZEqJCPft6u1CTRXQcVaqgkzaZ7nZ4Mtctf03qsRuJPDI9JlD4LZk1oAB2jGadOj
```

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.5.5
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
 This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Och, 1.13.2 has some different way in reading NBT String list, should be ok with next update and should show real encoded command. And yea, for that error, will add extra message to inform about wrong key when decoding
