### ISSUE TITLE
BUG: /msg playername message = "Internal Error Occurred while attempting to perform command"

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#200]
Seems to be with the latest version released yesterday, as it loaded up this morning around 6:30am and I got reports around 8:30 this morning. It was working fine previously. I noticed you added support for URL's in the /msg command (which is good because I was going to ask for that). But seems to be an error now.

/msg playername (no error just help guide output)
/msg playername anything here (does not work)

```
[09:17:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v7.6.2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paperspigotlatest.jar:git-Paper-1381]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_73]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paperspigotlatest.jar:git-Paper-1381]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.containsUrl(ChatFormatManager.java:226) ~[?:?]
        at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:181) ~[?:?]
        at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:133) ~[?:?]
        at com.Zrips.CMI.commands.list.msg.perform(msg.java:83) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[paperspigotlatest.jar:git-Paper-1381]
        ... 15 more
```

**Comment by LogGits** [comment]
Hey, the latest version of CMI (was just published now) modifies links. Please retest this and let us know if you still get this error.

**Comment by digitalcrowd** [comment]
It fixes it. Thanks. (color codes filter correctly as well, part of the other bug you closed earlier)
