### ISSUE TITLE
help spigot bugs...

### ISSUE THREAD

**Issue by lanessNet** [Zrips/CMI#2000]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[16:35:49 WARN]: java.security.InvalidKeyException: Illegal key size or default parameters
[16:35:49 WARN]:        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
[16:35:49 WARN]:        at javax.crypto.Cipher.implInit(Cipher.java:801)
[16:35:49 WARN]:        at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
[16:35:49 WARN]:        at javax.crypto.Cipher.init(Cipher.java:1249)
[16:35:49 WARN]:        at javax.crypto.Cipher.init(Cipher.java:1186)
[16:35:49 WARN]:        at com.Zrips.CMI.utils.CMIEncoder.initialize(CMIEncoder.java:45)
[16:35:49 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1370)
[16:35:49 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:35:49 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[16:35:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[16:35:49 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[16:35:49 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[16:35:49 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[16:35:49 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[16:35:49 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[16:35:49 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[16:35:49 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[16:35:49 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
v8.6.5.5
**Server Type (Spigot/Paperspigot/etc):** 
spigot
**Server Version (using `/ver`):** 
1.12.2
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
How does your security.key looks like? As this is related to something messed up inside of it.

**Comment by lanessNet** [comment]
key is 4056a5cf8fd5485cbd210a9a013344ac

**Comment by lanessNet** [comment]
```
[15:38:51 INFO]: [CMI] Failed to setup encoder by using key in security.key file.
[15:38:51 INFO]: [CMI] Encryption will be disabled. Report about this to the developer and include error message. This will not effect plugins work
[15:38:51 WARN]: java.security.InvalidKeyException: Illegal key size or default parameters
[15:38:51 WARN]:        at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
[15:38:51 WARN]:        at javax.crypto.Cipher.implInit(Cipher.java:801)
[15:38:51 WARN]:        at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
[15:38:51 WARN]:        at javax.crypto.Cipher.init(Cipher.java:1249)
[15:38:51 WARN]:        at javax.crypto.Cipher.init(Cipher.java:1186)
[15:38:51 WARN]:        at com.Zrips.CMI.utils.CMIEncoder.initialize(CMIEncoder.java:48)
[15:38:51 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1368)
[15:38:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:38:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[15:38:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[15:38:51 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[15:38:51 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[15:38:51 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[15:38:51 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[15:38:51 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[15:38:51 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[15:38:51 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[15:38:51 WARN]:        at java.lang.Thread.run(Unknown Source)
```

error log see...

**Comment by Marlej-dev** [comment]
Try upgrading your java version

**Comment by Zrips** [comment]
This got fixed
