### ISSUE TITLE
Hologram error

### ISSUE THREAD

**Issue by YTRemRem** [Zrips/CMI#2008]
**Description of issue:**
When typing /hologram and click on the <open settings gui> button, it shows the error below.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[00:33:42 WARN]: java.lang.NullPointerException
> [00:33:42 WARN]: at com.Zrips.CMI.Reflections.setNbt(Reflections.java:937)
> [00:33:42 WARN]: at com.Zrips.CMI.Modules.GUI.CMIGuiButton.getItem(CMIGuiButton.java:372)
> [00:33:42 WARN]: at com.Zrips.CMI.Modules.GUI.GUIManager.generateInventory(GUIManager.java:261)
> [00:33:42 WARN]: at com.Zrips.CMI.Modules.GUI.GUIManager.openGui(GUIManager.java:305)
> [00:33:42 WARN]: at com.Zrips.CMI.Modules.GUI.CMIGui.open(CMIGui.java:91)
> [00:33:42 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramManager.openGui(HologramManager.java:1166)
> [00:33:42 WARN]: at com.Zrips.CMI.commands.list.hologram.perform(hologram.java:124)
> [00:33:42 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264)
> [00:33:42 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [00:33:42 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
> [00:33:42 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [00:33:42 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [00:33:42 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
> [00:33:42 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
> [00:33:42 WARN]: at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):8.6.6.1** 

**Server Type (Spigot/Paperspigot/etc):Spigot** 

**Server Version (using `/ver`):1.8.8**

**Comment by Zrips** [comment]
Got fixed
