### ISSUE TITLE
CMI error on server startup

### ISSUE THREAD

**Issue by Arkidos** [Zrips/CMI#2028]
**Description of issue:**
There's this issue on server startup and I don't know how to fix it.
Here's the full server log if needed : https://paste.helpch.at/atitupirem.md
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:08:39] [Server thread/WARN]: java.security.InvalidKeyException: Illegal key size or default parameters
[10:08:39] [Server thread/WARN]:    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
[10:08:39] [Server thread/WARN]:    at javax.crypto.Cipher.implInit(Cipher.java:801)
[10:08:39] [Server thread/WARN]:    at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
[10:08:39] [Server thread/WARN]:    at javax.crypto.Cipher.init(Cipher.java:1249)
[10:08:39] [Server thread/WARN]:    at javax.crypto.Cipher.init(Cipher.java:1186)
[10:08:39] [Server thread/WARN]:    at com.Zrips.CMI.utils.CMIEncoder.initialize(CMIEncoder.java:45)
[10:08:39] [Server thread/WARN]:    at com.Zrips.CMI.CMI.onEnable(CMI.java:1368)
[10:08:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:08:39] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[10:08:39] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[10:08:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[10:08:39] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[10:08:39] [Server thread/WARN]:    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[10:08:39] [Server thread/WARN]:    at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[10:08:39] [Server thread/WARN]:    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[10:08:39] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

---

**Cmi Version (using`/cmi version`):** 
CMI v8.6.6.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-110 (MC: 1.14.3) (Implementing API version 1.14.3-SNAPSHOT)

**Comment by Zrips** [comment]
How does your security.key file looks like?

**Comment by Arkidos** [comment]
```
# DO NOT EDIT THIS!
KEY: c2d971d999d846dcbbb10bcf0eb2c1a3
```

**Comment by Zrips** [comment]
Ok, 2 solutions: one would be for you update your Java version to latest one, i assume you have java 8 pre 161 build, you need atleast 161. Second would be to wait until next update which will have some adjustments which hopefully solve your issue.
