### ISSUE TITLE
SQL SyntaxError

### ISSUE THREAD

**Issue by J0schlZ** [Zrips/CMI#2033]
CMI 8.6.7.0

`[23:08:24 WARN]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM cmi_users WHERE player_uuid = 'afed906' at line 1
[23:08:24 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:08:24 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:08:24 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:08:24 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[23:08:24 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[23:08:24 WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[23:08:24 WARN]: 	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
[23:08:24 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1823)
[23:08:24 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1307)
[23:08:24 WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[23:08:24 WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:793)
[23:08:24 WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:344)
[23:08:24 WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:240)
[23:08:24 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[23:08:24 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[23:08:24 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:08:24 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:08:24 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:08:24 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:08:24 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM cmi_users WHERE player_uuid = 'afed906' at line 1
[23:08:24 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:08:24 WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:08:24 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:08:24 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[23:08:24 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[23:08:24 WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[23:08:24 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[23:08:24 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[23:08:24 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[23:08:24 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[23:08:24 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[23:08:24 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[23:08:24 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[23:08:24 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[23:08:24 WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1801)
[23:08:24 WARN]: 	... 11 more`

**Comment by Rukes** [comment]
Same problem

**Comment by Zrips** [comment]
Damn, this will be pain in ass now. Dint realized that different Mysql databases will use different syntax for this thing. Will make work around for this one with next build. Today most likely.

**Comment by Zrips** [comment]
Should be ok with new build.

**Comment by CypherPhyre** [comment]
I have this same problem. Even after the last update. The db syntax issue remains

**Comment by MrMorganCz** [comment]
it looks like the problem still exists #2050
