### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#2043]
cmi 8.6.7.1
spigot-1.12.2

[11:49:30] [Craft Scheduler Thread - 1930/WARN]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '9a72bc6' at line 1
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at sun.reflect.GeneratedConstructorAccessor410.newInstance(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:822)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:344)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:240)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at java.lang.Thread.run(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '9a72bc6' at line 1
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at sun.reflect.GeneratedConstructorAccessor407.newInstance(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
[11:49:30] [Craft Scheduler Thread - 1930/WARN]: 	... 10 more

**Comment by CypherPhyre** [comment]
#2033

**Comment by Marlej-dev** [comment]
Check if you have the new version of plugin

**Comment by CypherPhyre** [comment]
I am on CMI v8.6.7.1 running spigot 1.14.3 and have this issue.

**Comment by 1425115471** [comment]
The latest CMI

**Comment by Blueeyestar** [comment]
I'm afraid I have the same problem!

**Comment by Blueeyestar** [comment]
Is there no solution?  That spams me the console fully  :(

**Comment by 1425115471** [comment]
The author should be in the repair, has not released a new version

**Comment by Zrips** [comment]
Try out 8.6.7.3, this should be fixed now.

**Comment by 1425115471** [comment]
The author is awesome, the update is really fast.
