### ISSUE TITLE
Failed to setup encoder by using key in security.key file

### ISSUE THREAD

**Issue by Swede37** [Zrips/CMI#2045]
Didn't see this reported earlier, hope it's not a duplicate.

**Encryption will be disabled**

---

**ERROR :**
```
######################
##12.07 10:57:58 [Server] Server thread/INFO Failed to setup encoder by using key in security.key file.
12.07 10:57:58 [Server] Server thread/INFO Encryption will be disabled. Report about this to the developer and include error message. This will not effect plugins work
12.07 10:57:58 [Server] Server thread/WARN java.security.InvalidKeyException: Illegal key size or default parameters
12.07 10:57:58 [Server] Server thread/WARN at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
12.07 10:57:58 [Server] Server thread/WARN at javax.crypto.Cipher.implInit(Cipher.java:801)
12.07 10:57:58 [Server] Server thread/WARN at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
12.07 10:57:58 [Server] Server thread/WARN at javax.crypto.Cipher.init(Cipher.java:1249)
12.07 10:57:58 [Server] Server thread/WARN at javax.crypto.Cipher.init(Cipher.java:1186)
12.07 10:57:58 [Server] Server thread/WARN at com.Zrips.CMI.utils.CMIEncoder.initialize(CMIEncoder.java:48)
12.07 10:57:58 [Server] Server thread/WARN at com.Zrips.CMI.CMI.onEnable(CMI.java:1368)
12.07 10:57:58 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
12.07 10:57:58 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
12.07 10:57:58 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
12.07 10:57:58 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
12.07 10:57:58 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
12.07 10:57:58 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:439)
12.07 10:57:58 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
12.07 10:57:58 [Server] Server thread/WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764)
12.07 10:57:58 [Server] Server thread/WARN at java.lang.Thread.run(Thread.java:748)##
######################
```

---

**Version: CMI8.6.7.1** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): CraftBukkit version git-Spigot-5e4e7f3-5f88938 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)** 

**Relevant plugins: CMIEInjector1.0.2.1; Vault_1.72**

**Comment by Fabrimat** [comment]
Try to make a backup of your security.key file and delete it from the CMI directory.

**Comment by Zrips** [comment]
Should be fixed by now.
