### ISSUE TITLE
Error cmi bungee msg

### ISSUE THREAD

**Issue by Vinyljackers** [Zrips/CMI#2048]
**Description of issue or feature request:**

Everytime when player joins in to the server then this error keeps popping up i also disabled the bungee already in the cmi settings
#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
11:39:00 WARN]: [CMI] Plugin CMI v8.6.7.1 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[patched_1.13.2.jar:git-Paper-638]
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.onPluginMessageReceived(BungeeCordAPI.java:453) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-638]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-638]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.io.EOFException
at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_212]
at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[patched_1.13.2.jar:git-Paper-638]
... 14 more
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
#####################################
```

---

**8.6.7.1:** 

**Paper 1.13.2** 

**1.13.2**

**Comment by Zrips** [comment]
Should no longer be the issue with new bungee handling
