### ISSUE TITLE
BUGS? New player joins this is output in console

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#205]
New player joined and disconnected, this was the result of console...

```
[15:11:30 INFO]: Inotip[/x.x.x.x:59662] logged in with entity id 108296 at ([world3]-548.3867346573292, 69.0, 267.6236608175275)
[15:11:30 WARN]: [CMI] Plugin CMI v7.6.3.1 generated an exception while executing task 19393
java.lang.NullPointerException: null
        at me.glaremasters.statzexpansion.StatzExpansion.onPlaceholderRequest(StatzExpansion.java:133) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:201) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:178) ~[?:?]
        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:247) ~[?:?]
        at com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:162) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [paperspigotlatest.jar:git-Paper-1381]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paperspigotlatest.jar:git-Paper-1381]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
[15:11:31 WARN]: Inotip sent an invalid keepalive! pending keepalive: false got id: 0 expected id: 0
[15:11:31 INFO]: Inotip lost connection: Timed out
```

Player immediately disconnects. Reconnects, same error, gets disconnected. Each time, tried 6 times.

I noticed this error:

[15:13:12 WARN]: Inotip sent an invalid keepalive! pending keepalive: false got id: 0 expected id: 0

Anyhow, been seeing a lot of java noise in console log from CMI lately. I'll keep you posted. ;)

**Comment by Zrips** [comment]
Error originates from StatzExpansion plugin while CMI tries to update some placeholder and its actually not a issue with CMI but with that plugin not handling placeholder properly. Couple options, remove that placeholder from holograms, get in contact with plugin dev to fix this issue, pray for you God for this issue to resolve it self.
Will add some error catchers, but its limited what i can do from my end.
