### ISSUE TITLE
sql syntax error 8.6.7.1 

### ISSUE THREAD

**Issue by MrMorganCz** [Zrips/CMI#2050]
CMI 8.6.7.1 
Server Paper(129) 1.14.3-R0.1-SNAPSHOT

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '2429695' at line 1
[18:49:25 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:49:25 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[18:49:25 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[18:49:25 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[18:49:25 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[18:49:25 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
[18:49:25 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[18:49:25 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[18:49:25 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[18:49:25 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[18:49:25 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[18:49:25 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[18:49:25 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[18:49:25 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[18:49:25 WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1801)
[18:49:25 WARN]: ... 11 more

**Comment by CypherPhyre** [comment]
2043

**Comment by Zrips** [comment]
Got fixed
