### ISSUE TITLE
BUGS? Java Console Errors

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#206]
Kinda spammy in console. Not aware of in-game cause or effect of it.

```
[15:32:24 WARN]: [CMI] Plugin CMI v7.6.3.1 generated an exception while executing task 6787
java.lang.IllegalStateException: Asynchronous Async Player Chunk Add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.a(PlayerChunkMap.java:478) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:180) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.flagDirty(PlayerChunkMap.java:284) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:45) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.World.notify(World.java:488) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:165) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.update(CraftBlockEntityState.java:126) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:147) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:143) ~[paperspigotlatest.jar:git-Paper-1381]
        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [paperspigotlatest.jar:git-Paper-1381]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paperspigotlatest.jar:git-Paper-1381]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
[15:32:28 INFO]: [-MOD-] Cookie_Donut: Hows your day?
[15:32:30 WARN]: [CMI] Plugin CMI v7.6.3.1 generated an exception while executing task 6864
java.lang.IllegalStateException: Asynchronous Async Player Chunk Add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.a(PlayerChunkMap.java:478) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:180) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.flagDirty(PlayerChunkMap.java:284) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.WorldManager.a(WorldManager.java:45) ~[paperspigotlatest.jar:git-Paper-1381]
        at net.minecraft.server.v1_12_R1.World.notify(World.java:488) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:165) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockEntityState.update(CraftBlockEntityState.java:126) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:147) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:143) ~[paperspigotlatest.jar:git-Paper-1381]
        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[paperspigotlatest.jar:git-Paper-1381]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [paperspigotlatest.jar:git-Paper-1381]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [paperspigotlatest.jar:git-Paper-1381]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
```

**Comment by Zrips** [comment]
What is your view range in your server and what is range of dynamic signs update set to? Seems that its further apart than player can actually see what makes it to load chunk out of range to update sign. Will make some adjustments from my end to address this, but i still need that info for better idea what going on in your particular case

**Comment by LogGits** [comment]
This issue has been resolved in a recent build.
