### ISSUE TITLE
weird /back error on 1.14

### ISSUE THREAD

**Issue by xsmeths** [Zrips/CMI#2060]
**Description of issue:**
Error when I do /back after death

---

```[21:08:30] [Server thread/INFO]: smeths issued server command: /back
[21:08:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.7.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:874) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:102) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:142) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:89) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:106) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.Entity.setLocation(Entity.java:1322) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1105) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at net.minecraft.server.v1_14_R1.PlayerConnection.teleport(PlayerConnection.java:1071) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:665) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	at com.Zrips.CMI.Modules.tp.Teleportations.finalizeTeleport(Teleportations.java:508) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:334) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299) ~[?:?]
	at com.Zrips.CMI.commands.list.back.perform(back.java:76) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.3.jar:git-Spigot-9a643a6-2349feb]
	... 17 more

---

**Cmi Version (using`/cmi version`):**  8.6.7.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.14.3

**Comment by Zrips** [comment]
This should not be an issue anymore with latest version
