### ISSUE TITLE
BUGS? More java errors

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#207]
```
[15:39:54 WARN]: java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
[15:39:54 WARN]:        at com.Zrips.CMI.Modules.Sheduler.Schedule.getRandomCommand(Schedule.java:43)
[15:39:54 WARN]:        at com.Zrips.CMI.Modules.Sheduler.Schedule.perform(Schedule.java:198)
[15:39:54 WARN]:        at com.Zrips.CMI.Modules.Sheduler.Schedule.safePerform(Schedule.java:193)
[15:39:54 WARN]:        at com.Zrips.CMI.Modules.Sheduler.SchedulerManager.checkSchedulers(SchedulerManager.java:239)
[15:39:54 WARN]:        at com.Zrips.CMI.Modules.Sheduler.SchedulerManager.access$0(SchedulerManager.java:232)
[15:39:54 WARN]:        at com.Zrips.CMI.Modules.Sheduler.SchedulerManager$1.run(SchedulerManager.java:225)
[15:39:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[15:39:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[15:39:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[15:39:54 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[15:39:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[15:39:54 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[15:39:54 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zrips** [comment]
How does your schedule file looks like?

**Comment by LogGits** [comment]
I am assuming this was resolved. The error suggests you have incorrectly setup your schedule file. If you are still getting this error please create a new issue.
