### ISSUE TITLE
Commands /back and /home not working

### ISSUE THREAD

**Issue by hahaleks** [Zrips/CMI#2077]
**Description of issue:**
The commands /back and /home stoped working after updating to the newest version. A few users has been able to use both commands.

---

**ERROR:**
```
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:89) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:142) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:102) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_211]
19.07 18:57:40 [Server] INFO at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_211]
19.07 18:57:40 [Server] INFO at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_211]
19.07 18:57:40 [Server] INFO Caused by: java.util.ConcurrentModificationException
19.07 18:57:40 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:874) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:57:40 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.7.4
19.07 18:57:40 [Server] Server thread/ERROR null
19.07 18:57:40 [Server] Server thread/INFO (censored username) issued server command: /home e

--

19.07 18:55:44 [Server] INFO ... 17 more
19.07 18:55:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.commands.list.back.perform(back.java:76) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:299) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:310) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:396) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:590) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:344) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:352) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.Containers.CMIHitBox.getCollidingdBlock(CMIHitBox.java:369) ~[?:?]
19.07 18:55:44 [Server] INFO at com.Zrips.CMI.NBT.v1_14_R1.getBlockLookingAt(v1_14_R1.java:2062) ~[?:?]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.IBlockAccess.rayTrace(SourceFile:51) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Multicraft] Skipped 5 lines due to rate limit (30/s)
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:89) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:142) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:202) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:102) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_211]
19.07 18:55:44 [Server] INFO at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_211]
19.07 18:55:44 [Server] INFO at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_211]
19.07 18:55:44 [Server] INFO Caused by: java.util.ConcurrentModificationException
19.07 18:55:44 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:874) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.3.jar:git-Spigot-d05d3c1-087a2cf]
19.07 18:55:44 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.7.4
19.07 18:55:44 [Server] Server thread/ERROR null
19.07 18:55:44 [Server] Server thread/INFO (censored username) issued server command: /back
```

---

**Cmi Version:** 8.6.7.4

**Server Type:** Spigot

**Server Version:** 1.14.3 R0.1

**Comment by Zrips** [comment]
Update to 1.14.4 server version, that should solve this issue.
