### ISSUE TITLE
Constant economic error

### ISSUE THREAD

**Issue by BackWheel** [Zrips/CMI#2098]
[16:49:39] [Craft Scheduler Thread - 74/WARN]: java.lang.StackOverflowError
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at java.util.UUID.toString(Unknown Source)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at java.lang.String.valueOf(Unknown Source)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at java.lang.StringBuilder.append(Unknown Source)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.metadata.PlayerMetadataStore.disambiguate(PlayerMetadataStore.java:21)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.metadata.PlayerMetadataStore.disambiguate(PlayerMetadataStore.java:10)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at org.bukkit.metadata.MetadataStoreBase.hasMetadata(MetadataStoreBase.java:86)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.hasMetadata(CraftPlayer.java:1554)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:369)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:87)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1686)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1680)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:89)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:83)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78)
[16:49:39] [Craft Scheduler Thread - 74/WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:92)

**Comment by Zrips** [comment]
Should get fixed with next build and new recompiled vault version
