### ISSUE TITLE
Error in latest build 7.6.3.1

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#210]
```
WARN 05/04/2018 21:52:54
21:52:54[CMI] Plugin CMI v7.6.3.1 generated an exception while executing task 1990
Console 05/04/2018 21:52:54
21:52:54java.lang.IndexOutOfBoundsException: No group 1
at java.util.regex.Matcher.start(Matcher.java:375) ~[?:1.8.0_161]
at java.util.regex.Matcher.appendReplacement(Matcher.java:880) ~[?:1.8.0_161]
at java.util.regex.Matcher.replaceFirst(Matcher.java:1004) ~[?:1.8.0_161]
at java.lang.String.replaceFirst(String.java:2178) ~[?:1.8.0_161]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:270) ~[CMI7.6.3.1.jar:?]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:243) ~[CMI7.6.3.1.jar:?]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:234) ~[CMI7.6.3.1.jar:?]
at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:283) ~[CMI7.6.3.1.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1381]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1381]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1381]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by stashenko** [comment]
I was helped by the replacement of the placeholder %vault_eco_balance_formatted% at %cmi_user_balance%

**Comment by stashenko** [comment]
Placeholders %vault _ *********% do not work

**Comment by LogGits** [comment]
recieving the same error with %cmi_user_balance_formated%:
```
Console 05/04/2018 22:26:58
22:26:58 at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:234) ~[CMI7.6.3.1.jar:?]
at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:283) ~[CMI7.6.3.1.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1381]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1381]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1381]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
WARN 05/04/2018 22:26:58
22:26:58[CMI] Plugin CMI v7.6.3.1 generated an exception while executing task 1714
Console 05/04/2018 22:26:58
22:26:58java.lang.IndexOutOfBoundsException: No group 1
at java.util.regex.Matcher.start(Matcher.java:375) ~[?:1.8.0_161]
at java.util.regex.Matcher.appendReplacement(Matcher.java:880) ~[?:1.8.0_161]
at java.util.regex.Matcher.replaceFirst(Matcher.java:1004) ~[?:1.8.0_161]
at java.lang.String.replaceFirst(String.java:2178) ~[?:1.8.0_161]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:270) ~[?:?]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:243) ~[?:?]
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:234) ~[?:?]
at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:283) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1381]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1381]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1381]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by stashenko** [comment]
%cmi_user_balance% $

**Comment by stashenko** [comment]
![default](https://user-images.githubusercontent.com/34498917/38366770-831ce262-38e9-11e8-84ce-19d3e1529663.png)

**Comment by Zrips** [comment]
Should be fixed with next build
