### ISSUE TITLE
Hologram Error [Paper 1.8.8]

### ISSUE THREAD

**Issue by NightPrimez** [Zrips/CMI#2120]
**Description of issue:**
im trying to making hologram, i can make hologram's name but i can't open setting or adding line

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[15:54:02 WARN]: java.lang.NullPointerException
[15:54:02 WARN]:        at com.Zrips.CMI.Reflections.setNbt(Reflections.java:937)
[15:54:02 WARN]:        at com.Zrips.CMI.Modules.GUI.CMIGuiButton.getItem(CMIGuiButton.java:380)
[15:54:02 WARN]:        at com.Zrips.CMI.Modules.GUI.GUIManager.generateInventory(GUIManager.java:264)
[15:54:02 WARN]:        at com.Zrips.CMI.Modules.GUI.GUIManager.openGui(GUIManager.java:308)
[15:54:02 WARN]:        at com.Zrips.CMI.Modules.GUI.CMIGui.open(CMIGui.java:96)
[15:54:02 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.openGui(HologramManager.java:1175)
[15:54:02 WARN]:        at com.Zrips.CMI.commands.list.hologram.perform(hologram.java:124)
[15:54:02 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264)
[15:54:02 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:54:02 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[15:54:02 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:54:02 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[15:54:02 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[15:54:02 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[15:54:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:54:02 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.8.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.GUI.CMIGuiButton.getItem(CMIGuiButton.java:382) ~[?:?]
        at com.Zrips.CMI.Modules.GUI.GUIManager.generateInventory(GUIManager.java:264) ~[?:?]
        at com.Zrips.CMI.Modules.GUI.GUIManager.openGui(GUIManager.java:308) ~[?:?]
        at com.Zrips.CMI.Modules.GUI.CMIGui.open(CMIGui.java:96) ~[?:?]
        at com.Zrips.CMI.Modules.Holograms.HologramManager.openGui(HologramManager.java:1175) ~[?:?]
        at com.Zrips.CMI.commands.list.hologram.perform(hologram.java:124) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
```

Cmi Version (using`/cmi version`): 8.6.8.2

Server Type (Spigot/Paperspigot/etc): PaperSpigot

Server Version (using `/ver`): PaperSpigot-1.8.8-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will be fixed with next build
