### ISSUE TITLE
In console error CMI v8.6.8.4

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#2134]
Console error. Spigot 1.13.2

---

```
02.08 06:02:46 [Server] WARN [CMI] Task #87670 for CMI v8.6.8.4 generated an exception
02.08 06:02:46 [Server] INFO java.lang.NullPointerException: null
02.08 06:02:46 [Server] INFO at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.getPlayerList(BungeeCordAPI.java:137) ~[?:?]
02.08 06:02:46 [Server] INFO at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager$3.run(BungeeCordManager.java:354) ~[?:?]
02.08 06:02:46 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
02.08 06:02:46 [Server] WARN [CMI] Task #87672 for CMI v8.6.8.4 generated an exception
02.08 06:02:46 [Server] INFO java.lang.NullPointerException: null
02.08 06:02:46 [Server] INFO at com.Zrips.CMI.Modules.BungeeCord.BungeeCordAPI.getPlayerList(BungeeCordAPI.java:137) ~[?:?]
02.08 06:02:46 [Server] INFO at com.Zrips.CMI.Modules.BungeeCord.BungeeCordManager$3.run(BungeeCordManager.java:354) ~[?:?]
02.08 06:02:46 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [survival.jar:git-Spigot-1a3504a-84f3da3]
02.08 06:02:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

---

02.08 06:26:39 [Server] INFO --------------------------------------------------
02.08 06:26:39 [Server] INFO CMI версия плагина: 8.6.8.4 BungeeCord 
02.08 06:26:39 [Server] INFO Версия сервера: Spigot 1.13.2-R0.1-SNAPSHOT
02.08 06:26:39 [Server] INFO Версия хранилища: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
02.08 06:26:39 [Server] INFO --------------------------------------------------

Spigot

02.08 06:27:43 [Server] INFO This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by x1p** [comment]
Seems to be the same as issue #2129 and #1951 
Hope this gets fixed quickly. It's pretty annoying

**Comment by 4c5458** [comment]
Indeed

**Comment by Zrips** [comment]
Got fixed with new bungee handling
