### ISSUE TITLE
Error spam in console?

### ISSUE THREAD

**Issue by Vehzx** [Zrips/CMI#2144]
**Description of issue:**
On startup I get this error spammed in my console, over and over again, around 1500 lines of this error appear, just pasting itself loads.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor516.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-152]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-152]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-152]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-152]
        at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:89) ~[?:?]
```

---

**Cmi Version** 
8.6.8.4

**Server Type** 
Paperspigot

**Server Version**
git-Paper-146 (MC: 1.14.4)

**Comment by Vehzx** [comment]
Fixed this, was colliding with another plugin I use aliases on, ignore this report.
