### ISSUE TITLE
Error in console from Vault recompile

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#215]
After updating the plugin and adding the new recompiled Vault I get
```
[00:16:08] [Craft Scheduler Thread - 10/WARN]: [CMI] Plugin CMI v7.6.4.0 generated an exception while executing task 889
java.lang.StackOverflowError: null
        at org.bukkit.craftbukkit.v1_12_R1.metadata.PlayerMetadataStore.disambiguate(PlayerMetadataStore.java:1) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
        at org.bukkit.metadata.MetadataStoreBase.hasMetadata(MetadataStoreBase.java:75) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.hasMetadata(CraftPlayer.java:1209) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
        at com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:273) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getWorld(CMIUser.java:1277) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1250) ~[?:?]
        at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[?:?]
        at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[?:?]
        at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[?:?]
```
After removing the recompiled Vault there are no more errors

**Comment by MCTyler** [comment]
Did you remove the Injector? AFAIK it's one or the other.

**Comment by CypherPhyre** [comment]
This was without the Injector.

**Comment by Zrips** [comment]
Its actually issue with NPC players and some small issue with CMI. This should be fixed with next build. Tho Vault version should not effected this one.

**Comment by CypherPhyre** [comment]
There are no issues when using vault version 1.6.6 Only when I swap it out for the recompiled vault version 1.6.8 with no injecter

**Comment by LogGits** [comment]
Still occurring, il reopen 👍

**Comment by LogGits** [comment]
@Zrips has fixed this, it will be in the next update. Make sure to update both CMI and CMI's compiled vault.
