### ISSUE TITLE
Null Pointer when using with UltimateKits

### ISSUE THREAD

**Issue by ColaIan** [Zrips/CMI#2159]
**Description of issue:**
Null Pointer occurs on startup and automatically disables CMI when using with UltimateKits

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:55:22] [Server thread/ERROR]: Error occurred while enabling CMI v8.6.8.4 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Zrips.CMI.Modules.Kits.KitsManager.load(KitsManager.java:274) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1392) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-159]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-159]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-159]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-159]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-159]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-159]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-159]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-159]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

---

**Cmi Version (using`/cmi version`):** 
v.8.6.8.4

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper-160

**Relevant plugins (Delete if this isn't needed):**
UltimateKits

**Comment by Zrips** [comment]
Will make some changes which should solve this issue and will add error catcher, but this issue seems to be caused by UltimateKits if it's only appears when you have it.
