### ISSUE TITLE
/CMI Mobheads Not working (ERRORS)

### ISSUE THREAD

**Issue by mechcalvin** [Zrips/CMI#2163]
**Description of issue:**
Unable to use CMI Mobheads

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
07.08 23:54:28 [Server] INFO ... 17 more
07.08 23:54:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264) ~[?:?]
07.08 23:54:28 [Server] INFO at com.Zrips.CMI.commands.list.mobhead.perform(mobhead.java:72) ~[?:?]
07.08 23:54:28 [Server] INFO Caused by: java.lang.NullPointerException
07.08 23:54:28 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-146]
07.08 23:54:28 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.8.4
07.08 23:54:28 [Server] ERROR null
```

#######################################
#######################################
```

---

**latest** 

**Paper** 

**1.14**

**Comment by Zrips** [comment]
Full error log will be needed. This doesn't even say that issue is with mobhead command. if you still have this issue, please let me know.
