### ISSUE TITLE
npe with /info after /removeuser

### ISSUE THREAD

**Issue by StrangerFive** [Zrips/CMI#217]
So, one of my user's data got corrupted and it was crashing my server every time he logged in.  So, I removed him with /removeuser.  He has not logged in since, so a new account has not been created for him yet.  However, if I run /info on his name, I get the following NPE.  Any thoughts?

``` 06.04 23:58:28 [Server] WARN [CMI] Task #10862 for CMI v7.6.4.0 generated an exception
06.04 23:58:28 [Server] INFO java.lang.NullPointerException: null
06.04 23:58:28 [Server] INFO at com.Zrips.CMI.commands.list.info$1$1.run(info.java:178) ~[CMI7.6.4.0.jar:?]
06.04 23:58:28 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
06.04 23:58:28 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
06.04 23:58:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
06.04 23:58:28 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
06.04 23:58:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
06.04 23:58:28 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-fb423b8]
06.04 23:58:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by Zrips** [comment]
Did you got this error after server restart or straight after removing player data files? And is this still an issue?

**Comment by StrangerFive** [comment]
I get the message (still) every time I run /cmi info on that user.  I've gone through several server restarts since then.  Also, I believe I got the same message when I ran /cmi info a few commands after I ran /cmi removeuser (before the first server restart after removeuser), but I'm not 100% sure.  Yes, it's still an issue.

Also, before I ran removeuser on that user, I noticed he had a nick set.  I tried a couple times to remove his nick, but it kept failing.  Not sure if it gave me an error, and I don't have the logs anymore.

I also saw his location was way out at x=4966528.99, y=7.29, z=4938537.14, which is nonexistent in our world.  tppos wouldn't let me move him to near spawn.  That was failing too.

So, since I assumed user's data was corrupted, I ran removeuser, and now I keep getting this error.

**Comment by StrangerFive** [comment]
Tried a few things and finally got that error to go away for that username, but now it's on a non-existent username, so I guess it just moved.  Seems it has something to do with nicknames.

Recap:

1. Last week we had an issue where our server would immediately crash every time user "dominicm_1474" logged in to the server.
2. We did some experimenting and noticed the user had a nickname set to "DominicCM".  Figuring since there were recent CMI issues with nicknames, we attempted to clear out his nick.  We ran "cmi nick dominicm_1474 off", which we later figured out was wrong.  What this command actually tried to do was set the nick for the non-existent user "off" to "dominicm_1474".  We can't remember if there was an error from this command.
3. User "dominicm_1474" logged in again and the server immediately crashed -- again.
4. Now we decided to delete the user with "cmi removeuser [uuid for dominicm_1474]"
5. The user never logged in again.
6. We did some more digging and discovered that we got a NPE every time we ran "cmi info dominicm_1474", even after several server restarts.
7. We filed this issue and left it alone for a week or so.
8. We upgraded CMI to 7.6.7.0.
9. We then tried out the new command "cmi realname dominicm_1474" and the result was "dominicm_1474 real name off".  Now we realized our mistake in trying to clear out the nick last week.
10. The below log picks up around step 9 above.  We saw some interesting things, and we hope there are enough clues in it for you to figure out one or more problems with CMI and how to fix them.

Regards,
S5

> cmi info dominicm_1474
[13:42:58] [Server thread/WARN]: [CMI] Task #155476 for CMI v7.6.6.2 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.commands.list.info$1$1.run(info.java:178) ~[CMI7.6.7.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

> cmi realname dominicm_1474
[13:46:09] [Server thread/INFO]: dominicm_1474 real name off

> cmi nick clear off
[13:46:30] [Server thread/INFO]: Nickname changed to clear from off

> cmi info clear
[13:47:58] [Server thread/WARN]: [CMI] Task #157528 for CMI v7.6.6.2 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.commands.list.info$1$1.run(info.java:178) ~[CMI7.6.7.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

> cmi info off
[13:48:10] [Server thread/WARN]: [CMI] Task #157616 for CMI v7.6.6.2 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.commands.list.info$1$1.run(info.java:178) ~[CMI7.6.7.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

> cmi info dominicm_1474
[13:49:21] [Server thread/INFO]: Can't find player with this name!

> cmi nick off clear
[13:52:19] [Server thread/INFO]: Nickname reset to default

> cmi info clear
[13:52:26] [Server thread/INFO]: Can't find player with this name!

> cmi info off
[13:52:52] [Server thread/WARN]: [CMI] Task #159562 for CMI v7.6.6.2 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.commands.list.info$1$1.run(info.java:178) ~[CMI7.6.7.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

> cmi nick off off
[13:53:13] [Server thread/INFO]: Nickname reset to default

> cmi info off
[13:53:38] [Server thread/WARN]: [CMI] Task #159881 for CMI v7.6.6.2 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.commands.list.info$1$1.run(info.java:178) ~[CMI7.6.7.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
	
> cmi info clear
[13:53:46] [Server thread/INFO]: Can't find player with this name!

**Comment by LogGits** [comment]
There is a way to resolve this. First access your database. Change the username and uuid sections to the users Username and uuid (you can find the uuid by using https://mcuuid.net/)

**Comment by Zrips** [comment]
@StrangerFive This issue was related to players missing game mode. Error log from crash would give more information what exactly caused it to happen. I can fix this issue as it reapeats over and over again. But server crash could be for multiple different reasons. Most common is corrupted chunk.

**Comment by LogGits** [comment]
I am assuming this issue was resolved due to the lack of response. If you are still experiencing this issue please reopen a ticket.
