### ISSUE TITLE
In BundeeCord server in console error

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#2175]
Description of issue:

When a player kicks from the BundeeCord server in console bungee error.
---

ERROR:
```
10.08 18:55:38 [Server] WARNING Error dispatching event PlayerDisconnectEvent(player=venom568) to listener net.Zrips.Events@6eb82908
10.08 18:55:38 [Server] INFO java.lang.NullPointerException
10.08 18:55:38 [Server] INFO at net.Zrips.Events.onPlayerDisconnectEvent(Events.java:16)
10.08 18:55:38 [Server] INFO at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
10.08 18:55:38 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.08 18:55:38 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
10.08 18:55:38 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
10.08 18:55:38 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
10.08 18:55:38 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
10.08 18:55:38 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:98)
10.08 18:55:38 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:63)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 18:55:38 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 18:55:38 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 18:55:38 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
10.08 18:55:38 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 18:55:38 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 18:55:38 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 18:55:38 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 18:55:38 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
10.08 18:55:38 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
10.08 18:55:38 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
10.08 18:55:38 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
10.08 18:55:38 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
10.08 18:55:38 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
10.08 18:55:38 [Server] INFO at java.lang.Thread.run(Thread.java:748)
10.08 18:55:38 [Server] INFO [venom568] -> UpstreamBridge has disconnected
10.08 19:00:56 [Server] INFO [sokol22584] disconnected with: Вы кикнуты при подключении к Auth: Сервер работает на версиях 1.12 - 1.13.2. Пожалуйста, зайдите с нужной версии.
10.08 19:00:57 [Server] WARNING Error dispatching event PlayerDisconnectEvent(player=sokol22584) to listener net.Zrips.Events@6eb82908
10.08 19:00:57 [Server] INFO java.lang.NullPointerException
10.08 19:00:57 [Server] INFO at net.Zrips.Events.onPlayerDisconnectEvent(Events.java:16)
10.08 19:00:57 [Server] INFO at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
10.08 19:00:57 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.08 19:00:57 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
10.08 19:00:57 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
10.08 19:00:57 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
10.08 19:00:57 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
10.08 19:00:57 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:98)
10.08 19:00:57 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:63)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:00:57 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:00:57 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:00:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
10.08 19:00:57 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:00:57 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 19:00:57 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:00:57 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:00:57 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
10.08 19:00:57 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
10.08 19:00:57 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
10.08 19:00:57 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
10.08 19:00:57 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
10.08 19:00:57 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
10.08 19:00:57 [Server] INFO at java.lang.Thread.run(Thread.java:748)
10.08 19:00:57 [Server] INFO [sokol22584] -> UpstreamBridge has disconnected
10.08 19:00:59 [Server] INFO [DIMON5] -> UpstreamBridge has disconnected
10.08 19:01:00 [Server] INFO [VARY] -> UpstreamBridge has disconnected
10.08 19:01:20 [Server] INFO [maks] disconnected with: Вы кикнуты при подключении к Auth: Auth >> Вы должны зайти на сервер с ником Maks, но не maks.
10.08 19:01:20 [Server] WARNING Error dispatching event PlayerDisconnectEvent(player=maks) to listener net.Zrips.Events@6eb82908
10.08 19:01:20 [Server] INFO java.lang.NullPointerException
10.08 19:01:20 [Server] INFO at net.Zrips.Events.onPlayerDisconnectEvent(Events.java:16)
10.08 19:01:20 [Server] INFO at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
10.08 19:01:20 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.08 19:01:20 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
10.08 19:01:20 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:29)
10.08 19:01:20 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
10.08 19:01:20 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
10.08 19:01:20 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:98)
10.08 19:01:20 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:63)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:01:20 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:01:20 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:01:20 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
10.08 19:01:20 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:01:20 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
10.08 19:01:20 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
10.08 19:01:20 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
10.08 19:01:20 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
10.08 19:01:20 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
10.08 19:01:20 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
10.08 19:01:20 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
10.08 19:01:20 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
10.08 19:01:20 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
10.08 19:01:20 [Server] INFO at java.lang.Thread.run(Thread.java:748)
10.08 19:01:20 [Server] INFO [maks] -> UpstreamBridge has disconnected
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

Cmi Version: CMIB1.0.0.0

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Try new CMIB1.0.0.2.jar issue should be resolved
