### ISSUE TITLE
Spamming this warning in the console

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#2178]
**Description of issue:**
I am getting this warning message all the time in the console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:39:12 WARN]: java.io.UTFDataFormatException: malformed input around byte 294
[21:39:12 WARN]:        at java.io.DataInputStream.readUTF(DataInputStream.java:656)
[21:39:12 WARN]:        at java.io.DataInputStream.readUTF(DataInputStream.java:564)
[21:39:12 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:180)
[21:39:12 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[21:39:12 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:39:12 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[21:39:12 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[21:39:12 WARN]:        at java.lang.Thread.run(Thread.java:748)

```

---

**Cmi Version (using`/cmi version`):** 8.6.9.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper(641) 1.13.2

**Comment by Baktus79** [comment]
I think this was solved by updating the CMI on another server? Not really sure, but I updated the CMI, did a restart and everything seems to work.
