### ISSUE TITLE
Startup causing exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2181]
**Description of issue:**
did /stop, upgraded cmi, started the server, got this:
```
[16:33:06 INFO]: [CMI] Loaded (8) playtime rewards into memory. Took 2ms
[16:33:06 WARN]: java.lang.NullPointerException
[16:33:06 WARN]:        at com.Zrips.CMI.Containers.CMIUser.getLastLogoffClean(CMIUser.java:440)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.checkForExistingSimilarUser(PlayerManager.java:495)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1690)
[16:33:06 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1098)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:462)
[16:33:06 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1378)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[16:33:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[16:33:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[16:33:06 WARN]: java.lang.NullPointerException
[16:33:06 WARN]:        at com.Zrips.CMI.Containers.CMIUser.getLastLogoffClean(CMIUser.java:440)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.checkForExistingSimilarUser(PlayerManager.java:495)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1690)
[16:33:06 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1098)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:462)
[16:33:06 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1378)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[16:33:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[16:33:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[16:33:06 WARN]: java.lang.NullPointerException
[16:33:06 WARN]:        at com.Zrips.CMI.Containers.CMIUser.getLastLogoffClean(CMIUser.java:440)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.checkForExistingSimilarUser(PlayerManager.java:495)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1690)
[16:33:06 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1098)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:462)
[16:33:06 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1378)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[16:33:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[16:33:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[16:33:06 WARN]: java.lang.NullPointerException
[16:33:06 WARN]:        at com.Zrips.CMI.Containers.CMIUser.getLastLogoffClean(CMIUser.java:440)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.checkForExistingSimilarUser(PlayerManager.java:495)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1690)
[16:33:06 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1098)
[16:33:06 WARN]:        at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:462)
[16:33:06 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1378)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[16:33:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[16:33:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[16:33:06 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[16:33:06 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[16:33:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[16:33:06 INFO]: [CMI] Loaded (798) Player data into memory. Took 68ms
```

```
>cmi version
[16:38:22 INFO]: --------------------------------------------------
[16:38:22 INFO]: CMI plugin version: 8.6.9.2
[16:38:22 INFO]: Server version: Spigot 1.13.2-R0.1-SNAPSHOT
[16:38:22 INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[16:38:22 INFO]: --------------------------------------------------
>
```

**Comment by Zrips** [comment]
Was fixed with latest versoin
