### ISSUE TITLE
Hologram API Issue

### ISSUE THREAD

**Issue by Kr3s** [Zrips/CMI#2186]
**Description of issue or feature request:**
Whenever I create a hologram  and set a new text line to
%parkour_toptenxCC_Cave_1% or anything from the parkour api list
It crashes the server entirely. I'm using Papi to get the placeholders for the Parkour plugin.
Ignore the INFO could not find expected ':' that means nothing. I've already tried fixing that.
---

**ERROR:**
```
####################
## 13.08 00:04:19 [Server] Server thread/INFO Kr3s issued server command: /cmi hologram edittext TestPark add
13.08 00:04:30 [Server] Server thread/WARN org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
13.08 00:04:30 [Server] INFO in 'string', line 50, column 3:
13.08 00:04:30 [Server] INFO -'&4%parkour_toptenxCC_Cave_1%'
13.08 00:04:30 [Server] INFO ^
13.08 00:04:30 [Server] INFO could not find expected ':'
13.08 00:04:30 [Server] INFO in 'string', line 51, column 1:
13.08 00:04:30 [Server] INFO ^
13.08 00:04:30 [Server] Server thread/WARN at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
13.08 00:04:30 [Server] Server thread/WARN at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
13.08 00:04:30 [Server] Server thread/WARN at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:222)
13.08 00:04:30 [Server] Server thread/WARN at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:43)
13.08 00:04:30 [Server] Server thread/WARN at com.Zrips.CMI.Modules.Holograms.HologramManager.saveHolograms(HologramManager.java:449)
13.08 00:04:30 [Server] Server thread/WARN at com.Zrips.CMI.Modules.Holograms.HologramManager.access$0(HologramManager.java:436)
13.08 00:04:30 [Server] Server thread/WARN at com.Zrips.CMI.Modules.Holograms.HologramManager$1.run(HologramManager.java:430)
13.08 00:04:30 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
13.08 00:04:30 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)##
####################
```

---

**Cmi Version (using`/cmi version`): 8.6.9.4** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): Spigot 1.14.4-R0.1-SNAPSHOT** 

**Relevant plugins (Delete if this isn't needed): Papi, Parkour**

**Comment by Thrashjoking** [comment]
I have the same problem 😕

**Comment by Zrips** [comment]
Should be in working order with latest builds.
