### ISSUE TITLE
removeuser duplicates

### ISSUE THREAD

**Issue by TheCynicalKitty** [Zrips/CMI#2187]
**When i run cmi removeuser duplicates it starts spamming the error below**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```
[16:17:31 WARN]: [CMI] Task #8324 for CMI v8.6.9.4 generated an exception
java.lang.NullPointerException: null
        at com.Zrips.CMI.commands.list.removeuser$1.run(removeuser.java:83) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Cmi Version (using`/cmi version`):*latest* 

**Server Type (Spigot/Paperspigot/etc):*paper 1.12.2* 

**Server Version (using `/ver`):*git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
*

**Comment by AntoineHrn** [comment]
Got same here

**Comment by Zrips** [comment]
Will be fixed with next build
