### ISSUE TITLE
launch command error

### ISSUE THREAD

**Issue by ArcadeFighter** [Zrips/CMI#2190]
**Description of issue:**
I created on my spawn portals which are pressure plates (for launchpads) and add on that portals command for launch, when i use commands launch, it shows that error but launch command works

---

**ERROR:**
```
> [18:38:58 WARN]: Excessive velocity set detected: tried to set velocity of entity #64 to (6.030208312509488E-16,0.8682408883346516,-4.92403876506104).
> [18:38:58 WARN]: java.lang.Exception: Stack trace
> [18:38:58 WARN]: at java.lang.Thread.dumpStack(Thread.java:1336)
> [18:38:58 WARN]: at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
> [18:38:58 WARN]: at com.Zrips.CMI.commands.list.launch.jumpByAngle(launch.java:169)
> [18:38:58 WARN]: at com.Zrips.CMI.commands.list.launch.perform(launch.java:150)
> [18:38:58 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264)
> [18:38:58 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [18:38:58 WARN]: at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:723)
> [18:38:58 WARN]: at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:683)
> [18:38:58 WARN]: at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:129)
> [18:38:58 WARN]: at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:97)
> [18:38:58 WARN]: at com.Zrips.CMI.Modules.Portals.CMIPortal.teleport(CMIPortal.java:107)
> [18:38:58 WARN]: at com.Zrips.CMI.Modules.Portals.PortalListener.onPlayerMove(PortalListener.java:129)
> [18:38:58 WARN]: at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
> [18:38:58 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [18:38:58 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [18:38:58 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
> [18:38:58 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [18:38:58 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [18:38:58 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
> [18:38:58 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [18:38:58 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [18:38:58 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [18:38:58 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [18:38:58 WARN]: at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 
8.6.9.4

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.8.8-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
It seems that you have too strong launch power set on that launch pad. Its complaining about that. I can add some fail saves to try and prevent certain speeds. Servers in general cant really handle things which moves too fast.
