### ISSUE TITLE
Installing DiscordSRV on the server, causes CMI to crash and fail to load upon startup

### ISSUE THREAD

**Issue by stsguitar23** [Zrips/CMI#2192]
**Description of issue:**

Installing discordSRV on the server, causes CMI to refuse to load during startup

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.Kits.KitsManager.load(KitsManager.java:274) ~[?:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java:1370) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-151]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-151]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-151]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-151]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-151]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-151]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.4.jar:git-Paper-151]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869) ~[patched_1.14.4.jar:git-Paper-151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
######################
```

**Cmi Version (using`/cmi version`):** 
8.6.9.4

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
paper-167 1.14.4

**Relevant plugins (Delete if this isn't needed):**
DiscordSRV + CMI

**Comment by mercurialmusic** [comment]
If you use another chat plugin for Discord, disable the CMI-DiscordSRV hook:
```
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: false
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: false
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: false
```

**Comment by stsguitar23** [comment]
CMI is the only plugin that modifies chat i believe

Plugin list
AdvancedAchievements, AuctionHouse, CMI, CoreProtect, DiscordSRV, FabledSkyBlock, JupiterCore, LuckPerms, Marriage*, QuantumShop, Rankup, UltimateKits, Vault, Votifier, VotingPlugin, WorldEdit, WorldGuard

**Comment by mercurialmusic** [comment]
What are your config setting under that chat section? That might be useful. I've heard of others setting the `ClickHoverMessages: false` solving several plugin interaction issues.
