### ISSUE TITLE
Error in console "ping"

### ISSUE THREAD

**Issue by JavituRec** [Zrips/CMI#2210]
**Description of issue:**
Error in console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## org.bukkit.command.CommandException: Unhandled exception executing 'ping' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(ping)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-167]
	at de.jeppa.DragonSlayer.DragonSlayer$2.run(DragonSlayer.java:1243) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-167]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-167]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:75) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-167]
	... 9 more ##
######################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.9.4
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
fixed
