### ISSUE TITLE
Sit bug (NOTHING RELATED TO PERMISSIONS)

### ISSUE THREAD

**Issue by SebastianTAPM** [Zrips/CMI#2211]
when I'm want to sit on a stair or in place with the command  (/cmi sit and /sit) it doesn`t work, when I'm click nothing happens and when I issue the command /sit it says
"You are no longer sitting"

Error (im dont know if it is from CMI): 
```
[07:53:47 INFO]: TodosebasYT issued server command: /sit
[07:53:50 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
Could not pass event InventoryCloseEvent to EntityOptions v2.5.1
org.bukkit.event.EventException: null
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:38) ~[patched_1.14.4.jar:git-Paper-167]
        at me.incomprehendable.dev.pwp.transparentlisteners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:28) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1332) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityPlayer.closeInventory(EntityPlayer.java:1252) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:623) ~[patched_1.14.4.jar:git-Paper-167]
        at com.Acrobot.ChestShop.Listeners.Player.PlayerTeleport.onPlayerTeleport(PlayerTeleport.java:22) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor353.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:38) ~[patched_1.14.4.jar:git-Paper-167]
        at me.incomprehendable.dev.pwp.transparentlisteners.PWPTimedRegisteredListener.callEvent(PWPTimedRegisteredListener.java:28) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1179) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1158) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1149) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityPlayer.enderTeleportTo(EntityPlayer.java:1465) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityLiving.B(EntityLiving.java:2009) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityLiving.stopRiding(EntityLiving.java:2684) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityHuman.stopRiding(EntityHuman.java:959) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityPlayer.stopRiding(EntityPlayer.java:1057) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityPlayer.stopRiding(EntityPlayer.java:1052) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.EntityHuman.passengerTick(EntityHuman.java:368) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.WorldServer.a(WorldServer.java:614) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:596) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.WorldServer$$Lambda$3540/1366533471.accept(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_14_R1.World.a(World.java:936) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:356) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-167]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-167]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
        at ajneb97.eo.eventos.InventarioEffects.cerrarInventario(InventarioEffects.java:286) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor99.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
        ... 36 more
```

**Cmi Version:  CMI: 8.6.4.0-> 8.6.9.4
**Vault version: 1.7.2-b107**
** 

**Server Type :  PaperSpigot version git-Paper-167 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)** 

**Server Version (Build 167, Minecraft 1.14.4, Bukkit API: `1.14.4-R0.1-SNAPSHOT):** 

**AdvancedFood, AdvancedSlabs, AnimatedMenu, AnimationLib, ArtMap*, ATMs*, AuthMe, Bank, BBDeathChests, BungeePortals*, ChestShop, ChestShop-towny*, Citizens, CitizensCMD, ClearLag, CMI, CombatLog*, CommandNPC*, Computer*, Core, CounterStrike*, CraftBook, CreativeGates*, CS-CoreLib, DiscordMC*, dynmap*, Dynmap-Towny*, EntityOptions*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, Factions*, FeatherBoard*, GangsPlus, GeneralMarket, GroupManager, GUIShop, Holograms*, iConomy, ItemEdit*, Jobs, JupiterCore, LandClaiming, MarriageMaster, MassiveBooks*, MassiveCore*, MassiveHat*, MassiveTickets*, mcMMO, mcMMO-Towny*, MessageAnnouncer, Minepacks, Multiverse-Core, Music, MVdWPlaceholderAPI*, NoCheatPlus*, PermissionsEx*, PerWorldPlugins*, PlaceholderAPI*, PlayerControl, PluginConstructorAPI, PlugMan, ProtocolLib, RealTimePlugin*, Residence, SerialKey, SkinsRestorer, Slimefun*, TAB, Towny*, TownyChat*, TownyNameUpdater*, uCars, UltimateTimber, Vampire*, Vault, VehiclesPlus*, ViaVersion*, WorldEdit, XWeather** (someone gives errors and not start)

**Comment by LogGits** [comment]
this error is coming from  `EntityOptions v2.5.1` please report it to them.

**Comment by SebastianTAPM** [comment]
Nop, the same error,

**Comment by SebastianTAPM** [comment]
> this error is coming from `EntityOptions v2.5.1` please report it to them.

Same error
