### ISSUE TITLE
CMIScoreboardManager fails to initialize player scoreboard.

### ISSUE THREAD

**Issue by anaanook** [Zrips/CMI#2215]
There seems to be an issue with CMIScoreboardManager.  Perhaps it's unfinished or not updated?

code was literally just calling the setscoreboard method and passing it a player, string, and hashmap for the lines.

```
[00:55:10 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_13_R2.Scoreboard.registerObjective(java.lang.String, net.minecraft.server.v1_13_R2.IScoreboardCriteria)
[00:55:10 WARN]:        at java.lang.Class.getMethod(Class.java:1786)
[00:55:10 WARN]:        at com.Zrips.CMI.utils.CMIScoreboardManager.setScoreBoard(CMIScoreboardManager.java:87)

```

Latest CMI version 8.6.9.4

server on paper-6.41

**Comment by Zrips** [comment]
Ignore that part of code, will disable it for time being. Its some test code used to create scoreboards with packets, dint worked out as expected.
