### ISSUE TITLE
Bungeecord NullPointer when player disconnects

### ISSUE THREAD

**Issue by ColaIan** [Zrips/CMI#2218]
**Description of issue:**
Null pointer when player disconnects

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19.08 14:09:53.904] INFO: [Proxy-1] 14:09:53 [警告] Error dispatching event PlayerDisconnectEvent(player=ColaIan) to listener net.Zrips.Events@dd11872
[19.08 14:09:53.909] INFO: [Proxy-1] java.lang.NullPointerException
[19.08 14:09:53.916] INFO: [Proxy-1]     at net.Zrips.Events.onPlayerDisconnectEvent(Events.java:16)
[19.08 14:09:53.923] INFO: [Proxy-1]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19.08 14:09:53.931] INFO: [Proxy-1]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19.08 14:09:53.933] INFO: [Proxy-1]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19.08 14:09:53.934] INFO: [Proxy-1]     at java.lang.reflect.Method.invoke(Unknown Source)
[19.08 14:09:53.938] INFO: [Proxy-1]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
[19.08 14:09:54.256] INFO: [Proxy-1]     at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
[19.08 14:09:54.259] INFO: [Proxy-1]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
[19.08 14:09:54.262] INFO: [Proxy-1]     at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:61)
[19.08 14:09:54.263] INFO: [Proxy-1]     at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:59)
[19.08 14:09:54.264] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.265] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.272] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
[19.08 14:09:54.339] INFO: [Proxy-1]     at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[19.08 14:09:54.340] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.352] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.357] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
[19.08 14:09:54.449] INFO: [Proxy-1]     at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[19.08 14:09:54.453] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.482] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.502] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
[19.08 14:09:54.551] INFO: [Proxy-1]     at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[19.08 14:09:54.555] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.560] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.566] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
[19.08 14:09:54.567] INFO: [Proxy-1]     at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390)
[19.08 14:09:54.568] INFO: [Proxy-1]     at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355)
[19.08 14:09:54.569] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.601] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.645] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
[19.08 14:09:54.648] INFO: [Proxy-1]     at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[19.08 14:09:54.650] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.664] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.742] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
[19.08 14:09:54.747] INFO: [Proxy-1]     at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[19.08 14:09:54.751] INFO: [Proxy-1]     at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[19.08 14:09:54.753] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.754] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.757] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:221)
[19.08 14:09:54.760] INFO: [Proxy-1]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
[19.08 14:09:54.763] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:242)
[19.08 14:09:54.766] INFO: [Proxy-1]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:228)
[19.08 14:09:54.768] INFO: [Proxy-1]     at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
[19.08 14:09:54.771] INFO: [Proxy-1]     at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
[19.08 14:09:54.774] INFO: [Proxy-1]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19.08 14:09:54.775] INFO: [Proxy-1]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19.08 14:09:54.775] INFO: [Proxy-1]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
[19.08 14:09:54.776] INFO: [Proxy-1]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
[19.08 14:09:54.777] INFO: [Proxy-1]     at java.lang.Thread.run(Unknown Source)
[19.08 14:09:54.780] INFO: [Proxy-1] >
```

---

**Cmi Version (using`/cmi version`):** 
8.6.9.4 Bungeecord

**Server Type (Spigot/Paperspigot/etc):** 
Bungeecord

**Server Version (using `/ver`):** 
N/A

**Comment by Zrips** [comment]
Fixed
