### ISSUE TITLE
Error spam on the whole network

### ISSUE THREAD

**Issue by AntoineHrn** [Zrips/CMI#2226]
**Description of issue:**

This error keeps getting spammed while I haven't done a thing to the configuration.
It is spammed on both paper 1.13.2 and paper 1.14.4 with the latest CMI8.6.9.5 (it spammed before this update)
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:36:17 WARN]: [CMI] Plugin CMI v8.6.9.5 generated an exception whilst handling plugin message
java.lang.ArrayIndexOutOfBoundsException: 0
at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:460) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-642]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-642]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-642]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Zrips** [comment]
Will get fixed with next update
