### ISSUE TITLE
null error on checkban

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2231]
**Description of issue:**
Trying to use /cmi checkban username, they've been inactive for a while, but they have been active in the last year. 

Other users worked fine. 

results in unexpected error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[16:37:10 INFO]: mrfloris issued server command: /cmi checkban zxmark
[16:37:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.9.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1621) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_13_R2.GameProfileBanList.a(SourceFile:34) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.GameProfileBanList.a(SourceFile:8) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.JsonList.remove(JsonList.java:92) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at org.bukkit.craftbukkit.v1_13_R2.CraftProfileBanList.pardon(CraftProfileBanList.java:97) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        at com.Zrips.CMI.Containers.CMIUser.unBan(CMIUser.java:1527) ~[?:?]
        at com.Zrips.CMI.commands.list.checkban.perform(checkban.java:151) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:264) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-1a3504a-84f3da3]
        ... 15 more
>
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 8.6.9.4

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** ```>ver
[16:39:13 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-84f3da3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[16:39:13 INFO]: This is a final build for 1.13.2. Please see https://www.spigotmc.org/go/1.13.2 for details about upgrading.
>```

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Could you show me entry in database for this user? Tho will make some changes to prevent this error appearing in future.

**Comment by mrfloris** [comment]
```
Floriss-iMac:CMI floris$ cat finduser.sh
#!/bin/bash
dbresult=$(sqlite3 cmi.sqlite.db "SELECT * FROM \"main\".\"users\" WHERE \"userName\" LIKE '%zxmark%' ESCAPE '\' ORDER BY \"_rowid_\" ASC LIMIT 0, 49999")
echo -e $dbresult

Floriss-iMac:CMI floris$ ./finduser.sh

191|0c733170-0bfb-4292-9e50-90d63e289b26|ZxMark|||||0|endcity%%end:-2810.61:135.58:77.69:69.15:93.86;horse%%general:13862.53:65.0:2908.49:12.84:-85.46;house%%general:12431.51:74.0:1489.58:20.0:-48.54;horsey%%general:13909.53:10.0:2953.62:9.42:4.23|1528562948917|1528563883838|110171|||||0|||0||-1||||10947.85|||1|1|0|0||||||||CMIGlobal%%10947.85|§6[§rmrfloris§6]:1541328523145:§rErhm, I hardly ever use skype these days, just click the bell on youtube to get notified T8C)|||0|0|||0|0|0|0|||0|0||||0|

Floriss-iMac:CMI floris$
```

<img width="1221" alt="Screenshot 2019-08-21 at 19 24 08" src="https://user-images.githubusercontent.com/28841349/63453647-681e8c80-c449-11e9-8665-b0fdabf477f9.png">
<img width="1221" alt="Screenshot 2019-08-21 at 19 24 14" src="https://user-images.githubusercontent.com/28841349/63453649-681e8c80-c449-11e9-8ea6-982208f133d8.png">
