### ISSUE TITLE
Error console (DeathLocation)

### ISSUE THREAD

**Issue by JavituRec** [Zrips/CMI#2244]
**Description of issue:**
Error in console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## [00:00:39] [Craft Scheduler Thread - 353/INFO]: [CMI]  SEVERE SAVE ERROR WHILE SAVING Velasco83 PLAYER DATA (DeathLocation)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: java.lang.IllegalArgumentException: World unloaded
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at org.bukkit.Location.getWorld(Location.java:112)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Containers.CMILocation.getWorld(CMILocation.java:65)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.PlayerManager.convertLocationToString(PlayerManager.java:1778)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1031)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:965)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:647)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:343)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:275)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: java.lang.IllegalArgumentException: World unloaded
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at org.bukkit.Location.getWorld(Location.java:112)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Containers.CMILocation.getWorld(CMILocation.java:65)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.PlayerManager.convertLocationToString(PlayerManager.java:1778)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1031)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:965)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:647)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:343)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:275)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:00:39] [Craft Scheduler Thread - 353/WARN]: 	at java.lang.Thread.run(Thread.java:748) ##
######################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.10.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.14.4

**Comment by Zrips** [comment]
Some issue with world being unloaded at time of recording that death location. Do you have some multiverse plugin?
