### ISSUE TITLE
Error in console 7.6.4.1

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#228]
After updating to 7.6.4.1 I get this error on player join
```
[16:49:05] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v7.6.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_161]
	at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:408) ~[?:?]
	at com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:232) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-b6ecf3b-2e21028]
	... 14 more
```

**Comment by Spikey101** [comment]
I have the same error

**Comment by LogGits** [comment]
Do you both have the cmivault?

**Comment by CypherPhyre** [comment]
The cmi vault recompile version 1.6.8 kept throwing errors so I downgraded back to vault version 1.6.6 and readded the injector.

**Comment by LogGits** [comment]
yeah was it like #230?

**Comment by CypherPhyre** [comment]
See closed 215 for vault error I was getting

**Comment by LogGits** [comment]
@Zrips has fixed this, it will be in the next update. Make sure to update both CMI and CMI's compiled vault.
