### ISSUE TITLE
EntitiyTargetLivingEntityEvent exceptions

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#2286]
**Description of issue:**

Exceptions thrown often after update to new version (8.6.11.0)

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Server thread/ERROR Could not pass event EntityTargetLivingEntityEvent to CMI v8.6.11.0
29.08 12:59:58 [Server] INFO org.bukkit.event.EventException: null
29.08 12:59:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityTargetLivingEvent(CraftEventFactory.java:1054) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.EntityExperienceOrb.tick(EntityExperienceOrb.java:84) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:568) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:745) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:344) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]
29.08 12:59:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
29.08 12:59:58 [Server] INFO Caused by: java.lang.NullPointerException
29.08 12:59:58 [Server] INFO at com.Zrips.CMI.Modules.Afk.AfkListener.EntityTargetLivingEntityEvent(AfkListener.java:491) ~[?:?]
29.08 12:59:58 [Server] INFO at sun.reflect.GeneratedMethodAccessor709.invoke(Unknown Source) ~[?:?]
29.08 12:59:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
29.08 12:59:58 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
29.08 12:59:58 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-065a373-8d4bc54]```


**Cmi Version (using`/cmi version`):** 8.6.11.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** This server is running CraftBukkit version git-Spigot-065a373-8d4bc54 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Fixed
