### ISSUE TITLE
Join error when not using cmi vault

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#229]
Description of issue or feature request: Error on server join when not using cmi vault.

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
ERROR 09/04/2018 13:36:59
13:36:59Could not pass event PlayerJoinEvent to CMI v7.6.4.1
Console 09/04/2018 13:36:59
13:36:59org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1381]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1381]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1381]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1381]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1381]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1381]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
at java.lang.String.replace(String.java:2240) ~[?:1.8.0_161]
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:408) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:232) ~[CMI7.6.4.1.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor836.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1381]
... 15 more
```

Cmi Version (using`/cmi version`): 7.6.4.1
Server Type (Spigot/Paperspigot/etc): Paperspigot
Server Version (using `/ver`): 1.12.2-R0.1-SNAPSHOT git-Paper-1381

**Comment by LogGits** [comment]
Related to #228
