### ISSUE TITLE
CMI vault economy error.

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#230]
Description of issue or feature request: Error when using cmivault.

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
13:31:50 at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
INFO 09/04/2018 13:31:50
13:31:50[AddLight 4.2.0] You are running the latest version.
Console 09/04/2018 13:31:54
13:31:54 at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
13:31:59 at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1276) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Containers.CMIUser.getBalance(CMIUser.java:1270) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getAccountBalance(Economy.java:83) ~[CMI7.6.4.1.jar:?]
at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:77) ~[CMI7.6.4.1.jar:?]
at net.milkbowl.vault.economy.plugins.Economy_CMI.getBalance(Economy_CMI.java:78) ~[Vault1.6.8.jar:?]
at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getBalance(CMIEconomyAcount.java:82) ~[CMI7.6.4.1.jar:?]
```

Cmi Version (using`/cmi version`): 7.6.4.1
Server Type (Spigot/Paperspigot/etc): Paperspigot
Server Version (using `/ver`): git-Paper-1381 1.12.2

**Comment by LogGits** [comment]
@Zrips has fixed this, it will be in the next update. Make sure to update both CMI and CMI's compiled vault.
