### ISSUE TITLE
Player Join Error

### ISSUE THREAD

**Issue by zoma0103** [Zrips/CMI#231]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
[16:09:25] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v7.6.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(Unknown Source) ~[?:1.8.0_161]
	at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:408) ~[?:?]
	at com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:232) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	... 14 more
```

Cmi Version (using`/cmi version`): 7.6.4.1
Server Type (Spigot/Paperspigot/etc): spigot
Server Version (using `/ver`): spigot-1.12.2-R0.1-SNAPSHOT-b1620

**Comment by C4BR3R4** [comment]
I see the same error when a player connects https://pastebin.com/mu7ki9Kv

**Comment by MCTyler** [comment]
The Plugin Page on Spigot is blowing up....

**Comment by LogGits** [comment]
relates to #228
