### ISSUE TITLE
Owners reporting this on Spigot

### ISSUE THREAD

**Issue by MCTyler** [Zrips/CMI#232]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
####################
## [08:46:03] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v7.6.4.1
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
at java.lang.String.replace(String.java:2240) ~[?:1.8.0_111]
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:408) ~[?:?]
at com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:232) ~[?:?] ##
####################
```

Cmi Version (using`/cmi version`): 7.6.4.1
Server Type (Spigot/Paperspigot/etc): [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
Server Version (using `/ver`): ?

**Comment by LogGits** [comment]
duplicate to #228
