### ISSUE TITLE
Crash when user try to connect

### ISSUE THREAD

**Issue by Lethgir** [Zrips/CMI#2370]
**Description of issue:**
When someone wants to connect to my server, the client and the server display an error and the player is disconnected. If i remove CMI, i don't have errors.
I had this error after a config edition so i decided o go back to default config (i deleted CMI/ folder and start my server again) but the issue is still here.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
From client : http://prntscr.com/p7qod4
From server : 
```
03:00:48 [AVERTISSEMENT] Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@2e272ea4, receiver=2xThunder), cancelled=false, tag=BungeeCord) to listener net.Zrips.MessageListener@1e86a5a7
java.lang.NullPointerException
    at net.Zrips.MessageListener.on(MessageListener.java:54)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:397)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:244)
    at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:88)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.lang.Thread.run(Thread.java:748)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Alias.yml : https://pastebin.com/rxA2EzvD
config.yml : https://pastebin.com/YcuredFs
CustomAlias.yml : empty (only comments)
customHeads.yml : https://pastebin.com/CGh583DR
databaseInfo.yml : https://pastebin.com/rJwLi1CD
DisabledEnchants.yml :  List: []
eventCommands.yml : https://hastebin.com/egapecohud.cs
holograms.yml : empty
jails.yml : empty
kits.yml : https://hastebin.com/jijiromoti.bash
Modules.yml : https://hastebin.com/taqebefocu.shell
PlayTimeRewards.yml : https://hastebin.com/nucohoweyi.bash
portals.yml : empty
ranks.yml : https://hastebin.com/henahivema.shell
recipes.yml : empty
SavedItems.yml : empty
schedules.yml : https://hastebin.com/fusekucesi.shell
skinsCache.yml : empty
tabList.yml : https://hastebin.com/zasehohede.bash
warps.yml : empty
worth.yml : https://hastebin.com/sebimoraxi.bash
```

```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.12.1 BungeeCord -> 8.6.13.2

**Server Type (Spigot/Paperspigot/etc):** 
Spigot 

**Server Version (using `/ver`):** 
1.14.4-R0.1-SNAPSHOT

**Relevant plugins (Delete if this isn't needed):**
Plugins (50): AdvancedAchievements, BlockParticles, BlowableObsidians, BungeeBridgeC, BungeeJoinMessages, BungeeTabListPlus, BungeeTeleport, BuycraftX, ChatManager, Citizens, CitizensCMD, CMI, ConsoleSpamFix, CrazyAuctions, CrazyCrates, CrazyEnchantments, EnchantableBlocks, Factions, FactionsTop, Itemizer, JupiterCore, LuckPerms, MarriageMaster, MassiveBooks, MassiveCore, Minepacks, MMOItems, MovingDevApi, Multiverse-Core, MythicArtifacts, MythicMobs, MythicMobsExtension, obsidianraider, OldCombatMechanics, PlaceholderAPI, PlugMan, ProtocolLib, QuantumShop, RandomTeleport, Rankup, RewardPRO, SafeNBT, SuperTrails, VariableTime, Vault, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by Zrips** [comment]
Try new CMIBungee 1.0.0.3 version, should be resolved
