### ISSUE TITLE
This error spams the console when people die. 1.14.4

### ISSUE THREAD

**Issue by MothGirlMusic** [Zrips/CMI#2415]
```
[15:48:25] [Server thread/WARN]: java.lang.IllegalArgumentException: Enchantment cannot be null
[15:48:25] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.inventory.CraftMetaItem.addEnchant(CraftMetaItem.java:822)
[15:48:25] [Server thread/WARN]: 	at com.Zrips.Recount.PlayerListener.onPlayerMakeDamage(PlayerListener.java:371)
[15:48:25] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor948.invoke(Unknown Source)
[15:48:25] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:48:25] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:229)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:901)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:800)
[15:48:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:933)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity0(EntityLiving.java:1620)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1073)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityMonster.damageEntity(SourceFile:72)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityZombie.damageEntity(EntityZombie.java:266)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityArrow.a(EntityArrow.java:365)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityArrow.a(EntityArrow.java:277)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityArrow.tick(EntityArrow.java:188)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityTippedArrow.tick(EntityTippedArrow.java:87)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:568)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.World.a(World.java:745)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:344)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970)
[15:48:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815)
[15:48:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MothGirlMusic** [comment]
i know its Recount and not CMI. same author but no messages are returned or anything. so posting here since i guess this is the most "official" place.
