### ISSUE TITLE
Give command with nbt tags result in CMI Error (Unhandled exception executing command 'cmi')

### ISSUE THREAD

**Issue by quorn23** [Zrips/CMI#2435]
/cmi give quorn23 stone_pickaxe{display:{Name:"[{\"text\":\"6{name} 6- ACTIVE QUEST\"}]",Lore:["{\"text\":\"7{description}\"}","{\"text\":\"6This quest is active.\"}"]},Enchantments:[{id:unbreaking,lvl:3}],HideFlags:37} 1

results in the error below, i can't give myself items with nbt tags defined.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[23:11:48] [Server thread/INFO]: quorn23 issued server command: /cmi give quorn23 stone_pickaxe{display:{Name:"[{\"text\":\"6{name} 6- ACTIVE QUEST\"}]",Lore:["{\"text\":\"7{description}\"}","{\"text\":\"6This quest is active.\"}"]},Enchantments:[{id:unbreaking,lvl:3}],HideFlags:37} 1
[23:11:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.15.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-209]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$3944.00000000D4198C50.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158) ~[patched_1.14.4.jar:git-Paper-209]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-209]
	at java.lang.Thread.run(Thread.java:819) [?:1.8.0_222]
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at com.Zrips.CMI.Modules.CmiItems.ItemManager.getItem(ItemManager.java:190) ~[?:?]
	at com.Zrips.CMI.commands.list.give.perform(give.java:140) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:281) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-209]
	... 18 more

```

**Cmi Version (using`/cmi version`):** 
CMI 8.6.15.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-209 (MC: 1.14.4)

**Comment by quorn23** [comment]
Addition:

/give quorn23 stone_pickaxe{Enchantments:[{id:unbreaking,lvl:3}],HideFlags:1} 1
or
/give quorn23 minecraft:stone_pickaxe{Enchantments:[{id:unbreaking,lvl:3}],HideFlags:1} 1

gives me a stone. Not a stone_pickaxe
