### ISSUE TITLE
player join error

### ISSUE THREAD

**Issue by zoma0103** [Zrips/CMI#245]
ERROR:
```
[19:04:52] [Craft Scheduler Thread - 4/WARN]: [CMI] Plugin CMI v7.6.5.2 generated an exception while executing task 2869
java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:1.8.0_161]
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source) ~[?:1.8.0_161]
	at java.lang.Double.parseDouble(Unknown Source) ~[?:1.8.0_161]
	at java.text.DigitList.getDouble(Unknown Source) ~[?:1.8.0_161]
	at java.text.DecimalFormat.parse(Unknown Source) ~[?:1.8.0_161]
	at java.text.SimpleDateFormat.subParse(Unknown Source) ~[?:1.8.0_161]
	at java.text.SimpleDateFormat.parse(Unknown Source) ~[?:1.8.0_161]
	at java.text.DateFormat.parse(Unknown Source) ~[?:1.8.0_161]
	at com.extendedclip.papi.expansion.player.PlayerUtil.format12(PlayerUtil.java:19) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerExpansion.onPlaceholderRequest(PlayerExpansion.java:257) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:201) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:178) ~[?:?]
	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:264) ~[?:?]
	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:251) ~[?:?]
	at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:279) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

Cmi Version (using`/cmi version`): 7.6.5.3
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): spigot-1.12.2-R0.1-SNAPSHOT-b1620

**Comment by LogGits** [comment]
what placeholders are u using in your tablist?

**Comment by RustyDagger** [comment]
I too am having issues with this I just updated to the latest version and alas the error on join is gone but Im still having issues Mainly noticed it with Dsigns I can't seem to shift right click them to bring up the edit menu for them. Its Like CMI does not consider me a player. Its not even calling for the permission checks to be done when I sneak click the sign. ( it does those checks for other players on my server )

**Comment by zoma0103** [comment]
%cmi_user_name%   %cmi_user_country_code%'
%cmi_user_balance%   %playerpoints_points%'
%cmi_user_prefix%   %cmi_user_rank%'
%griefprevention_accruedclaims%   %griefprevention_bonusclaims%
%griefprevention_remainingclaims%
%player_x%   %player_y%   %player_z%   %player_world_time_12%'
%player_ping%    %server_online%   %server_max_players%'

**Comment by zoma0103** [comment]
New Error v7.6.5.4

[Craft Scheduler Thread - 63/WARN]: [CMI] Plugin CMI v7.6.5.4 generated an exception while executing task 439746
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_161]
	at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_161]
	at java.lang.Long.parseLong(Unknown Source) ~[?:1.8.0_161]
	at java.text.DigitList.getLong(Unknown Source) ~[?:1.8.0_161]
	at java.text.DecimalFormat.parse(Unknown Source) ~[?:1.8.0_161]
	at java.text.SimpleDateFormat.subParse(Unknown Source) ~[?:1.8.0_161]
	at java.text.SimpleDateFormat.parse(Unknown Source) ~[?:1.8.0_161]
	at java.text.DateFormat.parse(Unknown Source) ~[?:1.8.0_161]
	at com.extendedclip.papi.expansion.player.PlayerUtil.format12(PlayerUtil.java:19) ~[?:?]
	at com.extendedclip.papi.expansion.player.PlayerExpansion.onPlaceholderRequest(PlayerExpansion.java:257) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:201) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:178) ~[?:?]
	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:264) ~[?:?]
	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:251) ~[?:?]
	at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:279) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2-R0.1-SNAPSHOT-b1620.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by Zrips** [comment]
Issue originates from com.extendedclip.papi.expansion.player.PlayerUtil.format12 so look for issues with that papi expansion plugin responsible for particular placeholder. CMI is only mentioned as it just requested placeholder update from PAPI plugin it self
