### ISSUE TITLE
Issue: MySQL error message in console

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#247]
Description of issue or feature request:

This is not happening with CMI ver 7.6.5.2 and below.

ERROR:
```
[18:26:41] [Craft Scheduler Thread - 68/WARN]: [CMI] Plugin CMI v7.6.5.4 generated an exception while executing task 33688
java.lang.StackOverflowError: null
	at java.net.AbstractPlainSocketImpl.available(AbstractPlainSocketImpl.java:490) ~[?:1.8.0_131]
	at java.net.SocketInputStream.available(SocketInputStream.java:259) ~[?:1.8.0_131]
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:62) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4811) ~[patched_1.12.2.jar:git-Paper-1390]
	at com.Zrips.CMI.Modules.DataBase.DBConnection.setAutoCommit(DBConnection.java:50) ~[CMI7.6.5.4.jar:?]
	at com.Zrips.CMI.Modules.DataBase.DBDAO.setAutoCommit(DBDAO.java:707) ~[CMI7.6.5.4.jar:?]
	at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:719) ~[CMI7.6.5.4.jar:?]
	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:287) ~[CMI7.6.5.4.jar:?]
```

Cmi Version (using`7.6.5.4`): 
Server Type (Paperspigot): 
Server Version (using `Paper-1390`):

**Comment by MCTyler** [comment]
Show us your Msql Config like this....```storage:
  # storage method, can be MySQL or sqlite
  method: MySQL
mysql:
  # Requires Mysql.
  username: root
  password: secret
  hostname: localhost:3306
  database: cmi
  tablePrefix: CMI_
  # If you have no clue what these values does, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 3```

**Comment by Baktus79** [comment]
'''
  method: MySQL
mysql:

  username: secret
  password: secret
  hostname: localhost:3306
  database: cmi
  tablePrefix: CMI_

  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false

AutoSaveInterval: 15
'''

**Comment by Baktus79** [comment]
Its the same here too, I just skipped out on all the other lines ;) But yeah, the last line there spam the console.

**Comment by Baktus79** [comment]
This issue does not appear on the lastest update
