### ISSUE TITLE
 Error loading plugin

### ISSUE THREAD

**Issue by zabattaro** [Zrips/CMI#248]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
[17:03:55] [Craft Scheduler Thread - 5/WARN]: [CMI] Plugin CMI v7.6.5.2 generated an exception while executing task 17
java.lang.NullPointerException: null
	at com.Zrips.CMI.PlayerManager$1.run(PlayerManager.java:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-b6ecf3b-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-b6ecf3b-9060bfa]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

Cmi Version (using`/cmi 7.6.5.2`): 
Server Type (Spigot
Server Version (using `/1.12.2`):

**Comment by CloudeLecaw** [comment]
this error still exisit in CMI 7.6.6.1?

**Comment by LogGits** [comment]
Was fixed ages ago, updating cmi and cmivault should resolve this :slightly_smiling_face:
