### ISSUE TITLE
security.key  error

### ISSUE THREAD

**Issue by 1425115471** [Zrips/CMI#2480]
[14:56:43] [Server thread/INFO]: [CMI] Enabling CMI v8.6.15.3
[14:56:44] [Server thread/INFO]: [0;37;22m┏━━━┓ [0;37;1m┏━┓┏━┓ [0;37;22m┏━━┓[m
[14:56:44] [Server thread/INFO]: [0;37;22m┃┏━┓┃ [0;37;1m┃ ┗┛ ┃ [0;37;22m┗┫┣┛[m
[14:56:44] [Server thread/INFO]: [0;37;22m┃┃ ┗┛ [0;37;1m┃┏┓┏┓┃ [0;37;22m ┃┃ [m
[14:56:44] [Server thread/INFO]: [0;37;22m┃┃ ┏┓ [0;37;1m┃┃┃┃┃┃ [0;37;22m ┃┃ [m
[14:56:44] [Server thread/INFO]: [0;37;22m┃┗━┛┃ [0;37;1m┃┃┃┃┃┃ [0;37;22m┏┫┣┓[m
[14:56:44] [Server thread/INFO]: [0;37;22m┗━━━┛ [0;37;1m┗┛┗┛┗┛ [0;37;22m┗━━┛[m
[14:56:44] [Server thread/INFO]: [0;37;22m_______________________________________________________[m
[14:56:47] [Server thread/INFO]:   [0;36;22m[0;37;1m45 [0;32;22mEnabled [0;36;22mand [0;37;1m2 [0;33;1mDisabled [0;36;22mmodules[m
[14:56:47] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m8[0;36;22m) [0;37;22mportals [0;36;22minto memory. [0;33;22mTook [0;33;1m27[0;33;22mms[m
[14:56:47] [Server thread/INFO]:   [0;36;22mPermission plugin: [0;35;22mLuckPerms[m
[14:56:47] [Server thread/INFO]:   [0;36;22m[0;33;1mFailed to setup encoder by using key in security.key file.[m
[14:56:47] [Server thread/INFO]:   [0;36;22m[0;33;1mEncryption will be disabled. Report about this to the developer and include error message. This will not effect plugins work[m
[14:56:47] [Server thread/WARN]: java.security.InvalidKeyException: Illegal key size or default parameters
[14:56:47] [Server thread/WARN]: 	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
[14:56:47] [Server thread/WARN]: 	at javax.crypto.Cipher.implInit(Cipher.java:801)
[14:56:47] [Server thread/WARN]: 	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
[14:56:47] [Server thread/WARN]: 	at javax.crypto.Cipher.init(Cipher.java:1249)
[14:56:47] [Server thread/WARN]: 	at javax.crypto.Cipher.init(Cipher.java:1186)
[14:56:47] [Server thread/WARN]: 	at com.Zrips.CMI.utils.CMIEncoder.initialize(CMIEncoder.java:48)
[14:56:47] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1380)
[14:56:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[14:56:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[14:56:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[14:56:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[14:56:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[14:56:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[14:56:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[14:56:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[14:56:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[14:56:47] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[14:56:47] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m48[0;36;22m) [0;37;22mregular alias [0;36;22minto memory. [0;33;22mTook [0;33;1m48[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m1[0;36;22m) [0;37;22mcustom text's [0;36;22minto memory. [0;33;22mTook [0;33;1m2[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m3.25.2 data base type detected[m
[14:56:48] [Server thread/INFO]:   [0;36;22mStarted [0;37;22mSqLite [0;36;22mdata base. Took [0;33;22m390ms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;37;22mVault [0;36;22mwas found - Enabling capabilities. Economy: [0;35;22mCMIEconomy[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;33;1mCan't determine sound name for tag. Trying to defaulting to BLOCK_NOTE_HARP[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m5[0;36;22m) [0;37;22mwarning categories [0;36;22minto memory. [0;33;22mTook [0;33;1m2[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m3[0;36;22m) [0;37;22mwarning commands [0;36;22minto memory. [0;33;22mTook [0;33;1m0[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m131[0;36;22m) [0;37;22mcustom mob heads [0;36;22minto memory. [0;33;22mTook [0;33;1m32[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mcooldowns [0;36;22minto memory. [0;33;22mTook [0;33;1m38[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m5[0;36;22m) [0;37;22mwarmups [0;36;22minto memory. [0;33;22mTook [0;33;1m1[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m1[0;36;22m) [0;37;22mjails [0;36;22minto memory. [0;33;22mTook [0;33;1m3[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;35;22mRandom teleport location is out of minimal world border X coordinate bounds for [0;33;22mfuben [0;35;22mworld. Please update values.[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;35;22mRandom teleport location is out of maximal world border X coordinate bounds for [0;33;22mfuben [0;35;22mworld. Please update values.[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;35;22mRandom teleport location is out of minimal world border Z coordinate bounds for [0;33;22mfuben [0;35;22mworld. Please update values.[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;35;22mRandom teleport location is out of maximal world border Z coordinate bounds for [0;33;22mfuben [0;35;22mworld. Please update values.[m
[14:56:48] [Server thread/INFO]:   [0;36;22mEnabling BungeeCord Support[m
[14:56:48] [Server thread/INFO]:   [0;36;22mInitializing BungeeCord[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m1[0;36;22m) [0;37;22mkits [0;36;22minto memory. [0;33;22mTook [0;33;1m5[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m7[0;36;22m) [0;37;22mranks [0;36;22minto memory. [0;33;22mTook [0;33;1m14[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m4[0;36;22m) [0;37;22mplaytime rewards [0;36;22minto memory. [0;33;22mTook [0;33;1m3[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m9[0;36;22m) [0;37;22mplayer data [0;36;22minto memory. [0;33;22mTook [0;33;1m13[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m2[0;36;22m) [0;37;22mplaytime records [0;36;22minto memory. [0;33;22mTook [0;33;1m3[0;33;22mms[m
[14:56:48] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mplaytime reward records [0;36;22minto memory. [0;33;22mTook [0;33;1m1[0;33;22mms[m
[14:56:49] [Server thread/INFO]:   [0;36;22mRegistered events. Took [0;33;22m803ms[m
[14:56:49] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mevent action commands [0;36;22minto memory. [0;33;22mTook [0;33;1m6[0;33;22mms[m
[14:56:50] [Server thread/INFO]:   [0;36;22mUpdated (EN) language file. Took [0;33;22m313ms[m
[14:56:50] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m245[0;36;22m) [0;37;22mworth values [0;36;22minto memory. [0;33;22mTook [0;33;1m77[0;33;22mms[m
[14:56:50] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m26[0;36;22m) [0;37;22mwarps [0;36;22minto memory. [0;33;22mTook [0;33;1m4[0;33;22mms[m
[14:56:50] [Server thread/INFO]:   [0;36;22mVault permissions was found - Enabling capabilities.[m
[14:56:50] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mPlaceholderAPI hooked.[m
[14:56:50] [Server thread/INFO]:   [0;36;22mPlaceholderAPI was found - Enabling capabilities.[m
[14:56:50] [Server thread/INFO]:   [0;36;22mStarting world timer.[m
[14:56:50] [Server thread/INFO]:   [0;36;22mInitializing world manager.[m
[14:56:50] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m1[0;36;22m) [0;37;22mschedules [0;36;22minto memory. [0;33;22mTook [0;33;1m5[0;33;22mms[m
[14:56:50] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m19[0;36;22m) [0;37;22mholograms [0;36;22minto memory. [0;33;22mTook [0;33;1m24[0;33;22mms[m
[14:56:50] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m0[0;36;22m) [0;37;22mskin cache entries [0;36;22minto memory. [0;33;22mTook [0;33;1m0[0;33;22mms[m
[14:56:50] [Server thread/INFO]:   [0;36;22mVersion [0;37;22m8.6.15.3 [0;36;22mhas been enabled[m
[14:56:50] [Server thread/INFO]: [0;37;22m???????????????????????????????????????????????????????[m
[14:56:50] [Server thread/INFO]: [CMIEInjector][Economy] CMI Economy hooked.

#------------
spigot 1.13.3
CMI v8.6.15.3

**Comment by 1425115471** [comment]
[14:51:15] [Server thread/WARN]: java.lang.IllegalStateException: Cipher not initialized
[14:51:15] [Server thread/WARN]: 	at javax.crypto.Cipher.checkCipherState(Cipher.java:1750)
[14:51:15] [Server thread/WARN]: 	at javax.crypto.Cipher.doFinal(Cipher.java:2157)
[14:51:15] [Server thread/WARN]: 	at com.Zrips.CMI.utils.CMIEncoder.encode(CMIEncoder.java:106)
[14:51:15] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.CustomNBT.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:122)
[14:51:15] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor401.invoke(Unknown Source)
[14:51:15] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:51:15] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:51:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312)
[14:51:15] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[14:51:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[14:51:15] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[14:51:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:304)
[14:51:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:271)
[14:51:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:267)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1260)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[14:51:15] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:51:15] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[14:51:15] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[14:51:15] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Zrips** [comment]
Will post new version. But in general you should be running outdated Java version, you need atleast Java 8 u162 version for it to work properly. But will change some thing to skip this one in case it does fail.

**Comment by 1425115471** [comment]
非常感谢作者
