### ISSUE TITLE
console error report

### ISSUE THREAD

**Issue by NightPrimez** [Zrips/CMI#2486]
**Description of issue:**
it's showing when new player join a first time in my server

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**

[20:01:28] [Server thread/WARN]: [CMI] Task #125794 for CMI v8.6.15.3 generated an exception
java.lang.IllegalArgumentException: location.world
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftPlayer.teleport(CraftPlayer.java:742) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftEntity.teleport(CraftEntity.java:489) ~[patched_1.14.4.jar:git-Paper-221]
	at com.Zrips.CMI.AllListeners.PlayerListeners$6.run(PlayerListeners.java:841) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-221]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-221]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-221]

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.15.3

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
1.14.4 paperspigot

**Comment by Zrips** [comment]
Should get fixed with next version. Tho double check your first spawn location setup as it looks like you have none existing world set as a destination.
