### ISSUE TITLE
Still Issues relating to the Nickname mess ( I Think ) Dsign not doing perm checks.

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#254]
Description of issue or feature request:
So we were on CMI version 7.6.4.1 I had personally changed my own Nickname ( turned it off )
every time I logged in CMI would put the Below error into console, During this time I was unable to shift + right click any Dsign and have the Menu appear in chat it seemed as tho CMI considered me an invalid player and would not even check the permissions for me.

After noticing the error I was on my way to report it here when I seen the update log Mentioning NickNames being fixed and so on. So I held off on reporting and updated. to my current version now (7.6.5.4) After updating the error was gone on login However my inability to click the signs remained ( my other staff on the same rank and perms as me could click it and it worked fine. )
Thinking CMI had maybe saved some bad data About my player on the server I stopped the server and deleted the sqlite File ( backed it up first ) after restarting, No players are now able to click the Dsign and have the edit menu show in chat. There are no errors at all in console and ANY player regardless of permissions is able to type /dsign New and begin setting up a new sign. ( there are no permission checks being done at all from cmi when /dsign is used. ) 

ERROR:
```
####################
[21:30:25] [Server thread/INFO]: [RustyDagger] has joined the game.
[21:30:25] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v7.6.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1384]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1384]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_73]
	at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:408) ~[?:?]
	at com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:232) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor461.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1384]
	... 15 more
[21:30:25] [Server thread/INFO]: RustyDagger[/106.68.32.17:58810] logged in with entity id 316 at ([world]5.5244370279987685, 76.0, -4.925000011920929)
[21:30:51] [User Authenticator #1/INFO]: UUID of player Mr_Grim_ is d9591f7e-a329-457c-a5af-baa5eaf6f980
[21:30:51] [Server thread/INFO]: [Mr_Grim_] has joined the game.
[21:30:51] [Server thread/INFO]: Mr_Grim_[/218.214.28.20:64044] logged in with entity id 551 at ([world]12.755674405581443, 71.1212968405392, 14.897950778284267)
[21:31:48] [Server thread/INFO]: RustyDagger lost connection: Disconnected
[21:31:48] [Server thread/INFO]: [*Console*] RustyDagger Has Logged out.
[21:33:33] [User Authenticator #2/INFO]: UUID of player RustyDagger is d4158f6b-0164-4ced-ae64-d95cf4539132
[21:33:33] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v7.6.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1384]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1384]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240) ~[?:1.8.0_73]
	at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:408) ~[?:?]
	at com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:232) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor461.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1384]
	... 15 more
[21:33:33] [Server thread/INFO]: RustyDagger[/106.68.32.17:58846] logged in with entity id 1748 at ([world]0.5, 71.0, 0.5)
####################
```

Cmi Version: 7.6.5.4 
Server Type:  PaperSpigot
Server Version: Paper version git-paper-1384 MC 1.12.2

**Comment by MCTyler** [comment]
You had me scared so I checked the Perms.....
##################
[05:48:32 INFO]: D8ta doesn't have permission for: cmi.command.dsign
[05:48:32 INFO]: [LP] VB > d8ta - worldguard.region.bypass.world - undefined
[05:48:32 INFO]: [LP] VB > d8ta - worldguard.region.bypass.* - undefined
[05:48:32 INFO]: [LP] VB > d8ta - worldguard.region.* - undefined
[05:48:32 INFO]: [LP] VB > d8ta - worldguard.* - undefined
[05:48:32 INFO]: [LP] VB > d8ta - * - undefined
[05:48:32 INFO]: [LP] VB > d8ta - massivecore.variable.buffer - false
[05:48:32 INFO]: [LP] VB > d8ta - cmi.command - true
[05:48:32 INFO]: [LP] VB > d8ta - cmi.command.* - false
[05:48:32 INFO]: [LP] VB > d8ta - cmi.command.dsign - undefined
#######################

**Comment by RustyDagger** [comment]
was just doing some more testing and IDK what has changed but its now doing every thing it should

**Comment by LogGits** [comment]
Are you sure you are on version `7.6.5.4` your errors are for an outdated version:
`[21:33:33] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v7.6.4.1` Try updating, this problem was likely fixed ages ago ❤️
