### ISSUE TITLE
ShiftSignEdit broken and throwing error

### ISSUE THREAD

**Issue by aenaveen** [Zrips/CMI#2581]
**Description of issue:**
So ShiftSignEdit is throwing an error and is broken for 1.15
Can be accessed by using /cmi toggleshiftedit

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
java.lang.NoSuchFieldException: h
  at java.lang.Class.getDeclaredField(Unknown Source)
 at com.Zrips.CMI.Reflections.openSignUI(Reflections.java:743)
 at com.Zrips.CMI.AllListeners.PlayerListeners.onSignInteractShift(PlayerListeners.java:1054)
```

**Cmi Version (using`/cmi version`):** 
8.6.16.4
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot-23 
**Server Version (using `/ver`):** 
1.15.1

**Comment by Zrips** [comment]
Gets a fix with next version
