### ISSUE TITLE
Get Unexpected exception while parsing console command "list"

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#2588]
**Description of issue:**
And CMI refuse to start on the server. Im now some say in discussion to set a string in database, but where and how shall the string lock like?
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
[Server thread/WARN]: Unexpected exception while parsing console command "list"
org.bukkit.command.CommandException: Unhandled exception executing 'list' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(list)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-236]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-236]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-236]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-236]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_211]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_211]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_211]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[patched_1.14.4.jar:git-Paper-236]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-236]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_211]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:117) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-236]
	... 7 more

######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.16.4
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
 14.4
**Relevant plugins (Delete if this isn't needed):**
CMI
Valut

**Comment by Zrips** [comment]
If Cmi refuses to start on server startup, then i will need that error log. As this one doesn't really point to a issue, its more like a result of previous issue.

**Comment by broken1arrow** [comment]
Was blank-space in config file after we move it to new place.

**Comment by broken1arrow** [comment]
Was a blank space in config file after we move it to new location.
