### ISSUE TITLE
Spammy warning in console

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#2602]
**Description of issue:**

It's not really an issue, I just don't know how to get it away
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
[16:59:43 WARN]: [CMI] Plugin CMI v8.6.16.5 generated an exception while executing task 565719
java.lang.IllegalStateException: Asynchronous command dispatch!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:714) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:660) ~[patched_1.14.4.jar:git-Paper-236]
at com.Zrips.CMI.Modules.Advancements.AdvancementManager.sendToast(AdvancementManager.java:81) ~[?:?]
at com.Zrips.CMI.CMI.multyTypeMsg(CMI.java:2122) ~[?:?]
at com.Zrips.CMI.CMI.sendMessage(CMI.java:2007) ~[?:?]
at com.Zrips.CMI.CMI.sendMessage(CMI.java:1996) ~[?:?]
at com.Zrips.CMI.CMI.info(CMI.java:1950) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager.informPlayer(PlayTimeRewardsManager.java:218) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager$1$1.run(PlayTimeRewardsManager.java:199) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-236]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-236]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-236]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Cmi Version (using`/cmi version`): 8.6.16.5

**Server Type (Spigot/Paperspigot/etc): Paper 1.14.4, Ver.236

**Comment by therealatsuga** [comment]
Same on the testing Server running Paper 1.15.1, Ver. 32 with CMI 8.6.16.5

[11:04:57 WARN]: [CMI] Plugin CMI v8.6.16.5 generated an exception while executing task 6199
java.lang.IllegalStateException: Asynchronous command dispatch!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.1.jar:git-Paper-32]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:715) ~[patched_1.15.1.jar:git-Paper-32]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:660) ~[patched_1.15.1.jar:git-Paper-32]
at com.Zrips.CMI.Modules.Advancements.AdvancementManager.sendToast(AdvancementManager.java:81) ~[?:?]
at com.Zrips.CMI.CMI.multyTypeMsg(CMI.java:2122) ~[?:?]
at com.Zrips.CMI.CMI.sendMessage(CMI.java:2007) ~[?:?]
at com.Zrips.CMI.CMI.sendMessage(CMI.java:1996) ~[?:?]
at com.Zrips.CMI.CMI.info(CMI.java:1950) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager.informPlayer(PlayTimeRewardsManager.java:218) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager$1$1.run(PlayTimeRewardsManager.java:199) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-32]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-32]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-32]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Zrips** [comment]
Will get fixed with next version
