### ISSUE TITLE
"/cmi toggleshiftedit" doesn't work after updating to 8.6.16.5 on Spigot 1.15.1

### ISSUE THREAD

**Issue by derMiepz** [Zrips/CMI#2613]
**Description of issue:**
Title says it all

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[00:23:04] [Server thread/WARN]: java.lang.NoSuchFieldException: h
[00:23:04] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Unknown Source)
[00:23:04] [Server thread/WARN]: 	at com.Zrips.CMI.Reflections.openSignUI(Reflections.java:743)
[00:23:04] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners.onSignInteractShift(PlayerListeners.java:1053)
[00:23:04] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
[00:23:04] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:23:04] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:23:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[00:23:04] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:23:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[00:23:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[00:23:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:441)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:441)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1250)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
[00:23:04] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827)
[00:23:04] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Cmi Version (using`/cmi version`):** 
[00:24:54] [Server thread/INFO]: --------------------------------------------------
[00:24:54] [Server thread/INFO]: CMI Plugin Version: 8.6.16.5 BungeeCord 
[00:24:54] [Server thread/INFO]: Server Version: Spigot 1.15.1-R0.1-SNAPSHOT
[00:24:54] [Server thread/INFO]: Vault Version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[00:24:54] [Server thread/INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
[00:25:09] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-492a779-83af86d (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Next version will be fixed
