### ISSUE TITLE
[TryMe Plugin] java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2632]
**Description of issue:**

Out of the blue in 1.13.2 the plugin tryme is spitting out this error, I've tried upgrading to a newer version and that didn't work. We're on 1.15.1 now and it still doesn't work.

I would let it fresh install and then put the database back, but I still get the error. Besides 100% losing database data, I don't know how to fix this. 

I am sorry for putting this on CMI issue, but under repositories i dont see tryme for issues.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:15:44] [Server thread/ERROR]: Error occurred while enabling TryMe v6.0.3.1 (Is it up to date?)
java.lang.NullPointerException: null
        at me.Zrips.TryMe.ConfigFile.LoadQuestions(ConfigFile.java:451) ~[?:?]
        at me.Zrips.TryMe.ConfigFile.reloading(ConfigFile.java:1186) ~[?:?]
        at me.Zrips.TryMe.TryMe.onEnable(TryMe.java:428) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.1.jar:git-Spigot-492a779-99cf10e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
default
```

---

**Tryme Version (using`/ver tryme`):**  TryMe version 6.0.3.1

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 
```
>ver
[14:22:46] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-492a779-99cf10e (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[14:22:46] [Server thread/INFO]: Checking version, please wait...
[14:22:46] [Thread-82/INFO]: You are running the latest version
>
```

**Relevant plugins (Delete if this isn't needed):**
Vault version 1.7.3-b${env.TRAVIS_BUILD_NUMBER}

**Comment by Zrips** [comment]
Should be fixed with new update
