### ISSUE TITLE
AFK error lastest version CMI

### ISSUE THREAD

**Issue by Taximary** [Zrips/CMI#2634]
**Description of issue:**
When using /afk it throws an error, internal error, worked on the prev version.

---

**ERROR:**
```
10.01 15:41:07 [Server] ERROR null
10.01 15:41:07 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.17.1
10.01 15:41:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
10.01 15:41:07 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
10.01 15:41:07 [Server] INFO Caused by: java.lang.NoSuchFieldError: RAVAGER
10.01 15:41:07 [Server] INFO at com.Zrips.CMI.commands.list.afk.perform(afk.java:33) ~[?:?]
10.01 15:41:07 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:285) ~[?:?]
10.01 15:41:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-652]
10.01 15:41:07 [Server] INFO ... 15 more
```
---

**Cmi Version (using`/cmi version`):** 
8.6.17.1
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
git-paper-652 1.13.2

**Comment by Zrips** [comment]
Will be fixed with todays update
