### ISSUE TITLE
Console spam when using /cmi anvil with certain plugins

### ISSUE THREAD

**Issue by MidnightSugar** [Zrips/CMI#2662]
**Description of issue:**
/cmi anvil throws errors when the anvil is opened and when the anvil inventory is closed, when certain plugins are loaded.
For me these plugins are throwing the errors:
- XrayHeuristics https://www.spigotmc.org/resources/anti-xray-heuristics-1-13-1-14-1-15.72440/
- CrazyAuctions https://www.spigotmc.org/resources/crazy-auctions.25219/
- LagAssist https://www.spigotmc.org/resources/lagassist-%E2%9A%A1-advanced-performance-solution-%E2%9A%A1-1-8-1-15-compatible.56399/
- TownyGUI https://www.spigotmc.org/resources/townygui-4-years-customizable-1-7-10-1-14-4.9493/

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>.... [19:59:39 ERROR]: Could not pass event InventoryCloseEvent to CrazyAuctions v1.2.11-RELEASE
java.lang.IllegalStateException: Title not set
at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.Container.getTitle(Container.java:48) ~[patched_1.15.1.jar:git-Paper-50]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[patched_1.15.1.jar:git-Paper-50]
at me.badbones69.crazyauctions.controllers.GUI.onInvClose(GUI.java:472) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor508.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-50]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-50]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-50]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-50]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1370) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2107) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-50]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
>.... [20:25:57 ERROR]: Could not pass event InventoryClickEvent to TownyGUI v4.8
java.lang.IllegalStateException: Title not set
at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.Container.getTitle(Container.java:48) ~[patched_1.15.1.jar:git-Paper-50]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryView.getTitle(CraftInventoryView.java:69) ~[patched_1.15.1.jar:git-Paper-50]
at com.mystycfalls.townygui.event.TownyInv.onInvClick(TownyInv.java:23) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor728.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-50]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-50]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-50]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2328) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-50]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-50]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 8.6.18.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-50 (MC: 1.15.1)

**Relevant plugins (Delete if this isn't needed):**
CrazyAuctions, AntiXrayHeuristics

**Comment by Zrips** [comment]
Was pain to fix, but it should work without errors with next update.

**Comment by MidnightSugar** [comment]
When I put an item into the anvil GUI I am still spammed with this error:

https://pastebin.com/PJ98nCvk
