### ISSUE TITLE
[1.15.1] Restoring invcheck on owner is broken

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2666]
**Description of issue:**

`/cmi invcheck player` and then go back a couple, and click on [restore for owner] icon does nothing, spits out error in console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[06:52:14] [Server thread/WARN]: [CMI] Task #162381 for CMI v8.6.18.0 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.18.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:332) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at com.Zrips.CMI.utils.Util.performCommand(Util.java:675) ~[?:?]
        at com.Zrips.CMI.Modules.GUI.GUIManager$1.run(GUIManager.java:150) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_15_R1.EntityPlayer.b(EntityPlayer.java:1319) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at net.minecraft.server.v1_15_R1.EntityLiving.removeEffect(EntityLiving.java:877) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.removePotionEffect(CraftLivingEntity.java:356) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.loadInv(SavedInventoryManager.java:637) ~[?:?]
        at com.Zrips.CMI.commands.list.invload.perform(invload.java:62) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:285) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.1.jar:git-Spigot-492a779-d208733]
        ... 12 more
>
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
```
>cmi version
[06:53:51] [Server thread/INFO]: --------------------------------------------------
[06:53:51] [Server thread/INFO]: CMI plugin version: 8.6.18.0-> 8.6.18.1
[06:53:51] [Server thread/INFO]: Server version: Spigot 1.15.1-R0.1-SNAPSHOT
[06:53:51] [Server thread/INFO]: Vault version: 1.7.3-b
[06:53:51] [Server thread/INFO]: --------------------------------------------------
>
```

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 
```
>ver
[06:54:04] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-492a779-d208733 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[06:54:04] [Server thread/INFO]: Checking version, please wait...
[06:54:05] [Thread-172/INFO]: You are 7 version(s) behind
>
```

**Relevant plugins (Delete if this isn't needed):**

**Comment by mrfloris** [comment]
The user is offline that i try to restore btw
when i restore it to my own inventory, it seems to work.

**Comment by Zrips** [comment]
Its something related to potion effect which might no longer exist on your server. Will add extra checks to avoid from this happening in future even if you tried to load broken potion effects.

**Comment by mrfloris** [comment]
Awesome work as always, thank you - can't wait to test it later.
