### ISSUE TITLE
Could not pass event PlayerInteractEvent to CMI v8.6.18.2

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2672]
**since the update i have got big bug reports**

[22:31:46] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
	at com.Zrips.CMI.Containers.CMIEquipmentSlot.get(CMIEquipmentSlot.java:32) ~[?:?]
	at com.Zrips.CMI.Modules.CustomNBT.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor851.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-58]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:425) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.BlockRedstoneOre.stepOn(BlockRedstoneOre.java:36) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:627) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityLiving.e(EntityLiving.java:2255) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityHuman.e(EntityHuman.java:1558) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2620) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityHuman.movementTick(EntityHuman.java:428) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2381) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:426) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:149) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1263) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[22:31:46] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
	at com.Zrips.CMI.Containers.CMIEquipmentSlot.get(CMIEquipmentSlot.java:32) ~[?:?]
	at com.Zrips.CMI.Modules.CustomNBT.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor851.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-58]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:425) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.BlockRedstoneOre.stepOn(BlockRedstoneOre.java:36) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:627) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityLiving.e(EntityLiving.java:2255) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityHuman.e(EntityHuman.java:1558) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityLiving.movementTick(EntityLiving.java:2620) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityHuman.movementTick(EntityHuman.java:428) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2381) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:426) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:149) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1263) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
[22:47:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null

**Comment by Zrips** [comment]
Pushing out hot fix soon for this one
