### ISSUE TITLE
home command creates error

### ISSUE THREAD

**Issue by Qinak** [Zrips/CMI#2675]
**Description of issue:**

When I updated to latest CMI build from Spigot and players do `/home` this error shows.
I use EssentialsX home and have it turned off for CMI.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[03:29:46] [Server thread/INFO]: Player issued server command: /home
[03:30:13] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.18.2
java.lang.NullPointerException: null
	at com.Zrips.CMI.Containers.CMIEquipmentSlot.get(CMIEquipmentSlot.java:32) ~[?:?]
	at com.Zrips.CMI.Modules.CustomNBT.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor675.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.1.jar:git-Paper-58]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.1.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:425) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.BlockPressurePlateBinary.b(BlockPressurePlateBinary.java:78) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:67) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:60) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:214) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.Entity.checkBlockCollisions(Entity.java:949) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.Entity.move(Entity.java:664) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1049) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:1037) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1030) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1014) ~[patched_1.15.1.jar:git-Paper-58]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:937) ~[patched_1.15.1.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

---

**Cmi Version (using`/cmi version`):** 8.6.18.2

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper-58

**Relevant plugins (Delete if this isn't needed):** EssentialsX

**Comment by Zrips** [comment]
Will get fixed with hotfix soon
