### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#2684]
**Description of issue:**

Error when performing `/cmi info SomePlayerName`
Only happens on certain player names.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:34:28] [Server thread/WARN]: [CMI] Task #182152 for CMI v8.6.18.3 generated an exception
java.lang.NullPointerException: null
at com.Zrips.CMI.commands.list.info$1$1.run(info.java:224) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[purpur.jar:git-Purpur-397]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[purpur.jar:git-Purpur-397]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1186) ~[purpur.jar:git-Purpur-397]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:426) ~[purpur.jar:git-Purpur-397]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1113) ~[purpur.jar:git-Purpur-397]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[purpur.jar:git-Purpur-397]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

---

**Cmi Version (using`/cmi version`):** 
CMI 8.6.18.3

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
1.15.1

**Comment by Zrips** [comment]
Will be fixed with next version
