### ISSUE TITLE
Playtimerewards is causing an Error (Nullpointer)

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#2701]
**Description of issue:**
Playtimerewards is causing an Error because it wants to display a Toast (disabled in config)?

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:47:58 WARN]: [CMI] Plugin CMI v8.6.18.4 generated an exception while executing task 167726
java.lang.NullPointerException: null
at com.Zrips.CMI.commands.list.toast.perform(toast.java:106) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.performCMICommand(CommandsHandler.java:76) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.performCMICommand(CommandsHandler.java:69) ~[?:?]
at com.Zrips.CMI.Modules.Advancements.AdvancementManager.sendToast(AdvancementManager.java:82) ~[?:?]
at com.Zrips.CMI.CMI.multyTypeMsg(CMI.java:2127) ~[?:?]
at com.Zrips.CMI.CMI.sendMessage(CMI.java:2012) ~[?:?]
at com.Zrips.CMI.CMI.sendMessage(CMI.java:2001) ~[?:?]
at com.Zrips.CMI.CMI.info(CMI.java:1955) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager.informPlayer(PlayTimeRewardsManager.java:218) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager$1$1.run(PlayTimeRewardsManager.java:199) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-238]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-238]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-238]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Cmi Version (using`/cmi version`): 8.6.18.4

**Server Type (Spigot/Paperspigot/etc): Paper 1.14.4 Ver 238

**Comment by Zrips** [comment]
Will fix it, tho double check what variable are you passing throw while performing playtime rewards commands for Toast feature
