### ISSUE TITLE
[TryMe bug] 1.15.1 exception, precondition

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2716]
**Description of issue:**

Noticed below error in console, after someone joined the game. It probably tried to turn on.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:26:49] [Server thread/WARN]: [TryMe] Task #305473 for TryMe v6.0.4.1 generated an exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:458) ~[?:?]
        at me.Zrips.TryMe.Constructors.GameType.getRandomQuestion(GameType.java:335) ~[?:?]
        at me.Zrips.TryMe.Constructors.GameType.pickNextRandomQuestion(GameType.java:308) ~[?:?]
        at me.Zrips.TryMe.gameModes.AllMode.Run(AllMode.java:56) ~[?:?]
        at me.Zrips.TryMe.gameModes.AllMode$1.run(AllMode.java:71) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at java.lang.Thread.run(Thread.java:834) [?:?]
>
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
default
```

---

**Cmi Version (using`/cmi version`):** 
```
>ver tryme
[17:27:50] [Server thread/INFO]: TryMe version 6.0.4.1
[17:27:50] [Server thread/INFO]: Powerfull Question/Flash/Decode/Math game plugin
[17:27:50] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/tryme.3330/
[17:27:50] [Server thread/INFO]: Author: Zrips
>
```

**Server Type (Spigot/Paperspigot/etc):**  spigot

**Server Version (using `/ver`):** 
```
>ver
[17:28:07] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-037559e-5c6b0dc (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[17:28:07] [Server thread/INFO]: Checking version, please wait...
[17:28:07] [Thread-236/INFO]: You are 15 version(s) behind
>
```
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will fix it with next version
