### ISSUE TITLE
Command /recipe don't work on 1.15.2

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#2723]
**Description of issue:**
Looks like typing /recipe on 1.15.2 server gives an error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[09:06:37] [Server thread/INFO]: artuditu issued server command: /recipe
[09:06:37] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.18.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-80]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.IllegalArgumentException: Recipe must have non-AIR result.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:46) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:19) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:23) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:46) ~[patched_1.15.2.jar:git-Paper-80]
	at net.minecraft.server.v1_15_R1.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:25) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.RecipeIterator.next(RecipeIterator.java:31) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.inventory.RecipeIterator.next(RecipeIterator.java:12) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.getRecipesFor(CraftServer.java:1171) ~[patched_1.15.2.jar:git-Paper-80]
	at org.bukkit.Bukkit.getRecipesFor(Bukkit.java:684) ~[patched_1.15.2.jar:git-Paper-80]
	at com.Zrips.CMI.Modules.CmiItems.CMIItemStack.getRecipesFor(CMIItemStack.java:499) ~[?:?]
	at com.Zrips.CMI.commands.list.recipe.perform(recipe.java:75) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:285) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-80]
	... 17 more
```

---

**Cmi Version (using`/cmi version`):** 
8.6.18.5
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot 1.15.2
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
You seem to have a recipe with incorrect result entry in your database. Duno if it was settup by CMI or another plugin. Will make some fix for it, but check out your plugin which is responsible for custom recipes and make sure you dont have invalid ones.

**Comment by arturek1666** [comment]
Thank you for quick respond I think I did find out the problem, and will try to solve it ;)
