### ISSUE TITLE
bentobox managed world teleportation issue

### ISSUE THREAD

**Issue by DarkObscurity** [Zrips/CMI#2732]
**Description of issue:**
We're using Bentobox for our skyblock server.
Bentobox created and manages the worlds and we're experience issues with teleportation and homes;
- When teleporting from the normal world to a player who is in an island world you will be teleported to the players location in the normal world.
- Sometimes when using /tpo you'll get an message that an error occurred (See below) and after that you can' type or use commands in the chat or move until you rejoin the server.
- Homes are deleted after every server restart.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>.... [21:04:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.18.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-66]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-66]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-66]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:685) ~[patched_1.15.2.jar:git-Paper-66]
at com.Zrips.CMI.NBT.v1_15_R1.forceTeleport(v1_15_R1.java:2005) ~[?:?]
at com.Zrips.CMI.commands.list.tpo.perform(tpo.java:76) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:285) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-66]
... 17 more
>.... [21:04:05 FATAL]: Error executing task on Server
java.lang.NullPointerException: null
at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1303) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:743) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1144) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-66]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-66]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

---

**Cmi Version (using`/cmi version`):** 

§f§eCMI:§e §e§68.6.18.3§e-> 8.6.18.6
Server version: Paper(66) 1.15.2-R0.1-SNAPSHOT
Vault version: 1.7.3-b

**Server Type (Spigot/Paperspigot/etc):** 

Paper Spigot

**Server Version (using `/ver`):** 

This server is running Paper version git-Paper-66 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**

Bentobox 
https://github.com/BentoBoxWorld/BentoBox

**Comment by Zrips** [comment]
Will issue big fix for this one. There was some compatibility issue with newest minecraft versions when trying to force teleport player into target location which is not a standard world.

**Comment by DarkObscurity** [comment]
Thank you!

**Comment by DarkObscurity** [comment]
@Zrips will this aswell fix the homes that dissapear after a server restart?

**Comment by Zrips** [comment]
For homes, i will need more information about it. As homes should not get removed even if those are in none existing world. But in general, wait for next update, after that if issue persists, make a new ticket with as much information as posible. And would be nice to know in which worlds you have those homes, is it custom world or default one, and does it happen with homes in normal world too and do you have any error messages when player data is saved.

**Comment by DarkObscurity** [comment]
@Zrips 
The homes are located in the island worlds, so not in the normal world and I haven't seen any errors. I'll try to use the update.
