### ISSUE TITLE
"IOException: Stream closed" when money log is written just after midnight

### ISSUE THREAD

**Issue by FreeMonoid** [Zrips/CMI#2769]
**Description of issue:**

Every day slightly past midnight the warning below is getting printed to the console.

It does not seem to cause any data loss (there are entries generated at the same time in the money log for the new day).

---

**ERROR:**
```
[00:00:45 WARN]: java.io.IOException: Stream closed
[00:00:45 WARN]:        at java.io.BufferedWriter.ensureOpen(BufferedWriter.java:116)
[00:00:45 WARN]:        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:126)
[00:00:45 WARN]:        at java.io.BufferedWriter.flush(BufferedWriter.java:253)
[00:00:45 WARN]:        at com.Zrips.CMI.Modules.Economy.EconomyManager.moneyLog(EconomyManager.java:787)
[00:00:45 WARN]:        at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount$1.run(CMIEconomyAcount.java:76)
[00:00:45 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[00:00:45 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:00:45 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:00:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:00:45 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:00:45 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 8.6.19.0

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-90 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by FreeMonoid** [comment]
Looks like this was fixed
