### ISSUE TITLE
placeholder %cmi_worth_buy_[itemname]% does not work in moneycost

### ISSUE THREAD

**Issue by StrangerFive** [Zrips/CMI#277]
This works...
moneycost:5?#! asConsole! cmi give [playerName] stone 1

But this doesn't...
moneycost:%cmi_worth_buy_stone%?#! asConsole! cmi give [playerName] stone 1

It throws this error...
```
19.04 08:51:52 [Server] WARN [CMI] Task #391248 for CMI v7.6.10.0 generated an exception
19.04 08:51:52 [Server] INFO java.lang.NumberFormatException: For input string: "%cmi_worth_buy_stone%"
19.04 08:51:52 [Server] INFO at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_152]
19.04 08:51:52 [Server] INFO at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_152]
19.04 08:51:52 [Server] INFO at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_152]
19.04 08:51:52 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.checkIfCanPerformCommand(SpecializedCommandManager.java:610) ~[CMI7.6.10.0.jar:?]
19.04 08:51:52 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:490) ~[CMI7.6.10.0.jar:?]
19.04 08:51:52 [Server] INFO at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:102) ~[CMI7.6.10.0.jar:?]
19.04 08:51:52 [Server] INFO at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandListener$1.run(InteractiveCommandListener.java:60) ~[CMI7.6.10.0.jar:?]
19.04 08:51:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
19.04 08:51:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
19.04 08:51:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
19.04 08:51:52 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
19.04 08:51:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
19.04 08:51:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-bea5a84]
19.04 08:51:52 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

```
```
Cmi Version (using`/cmi version`): 
19.04 08:58:18 [Server] INFO --------------------------------------------------
19.04 08:58:18 [Server] INFO CMI plugin version: 7.6.10.0-> null
19.04 08:58:18 [Server] INFO Server version: Spigot 1.12.2-R0.1-SNAPSHOT
19.04 08:58:18 [Server] INFO Vault version: 1.6.10(+)
19.04 08:58:18 [Server] INFO --------------------------------------------------

Server Type (Spigot/Paperspigot/etc): 
spigot

Server Version (using `/ver`): 
19.04 08:58:23 [Server] INFO This server is running CraftBukkit version git-Spigot-eadd615-bea5a84 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by LogGits** [comment]
Next build will fix this issue.
