### ISSUE TITLE
CMI Severe Save Error

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/CMI#2781]
Severe Save Error
```
[13:35:22 INFO]: [CMI]  SEVERE SAVE ERROR WHILE SAVING RedValkyrja PLAYER DATA (teleportToggled)
[13:35:22 WARN]: java.lang.ArrayIndexOutOfBoundsException: 64
[13:35:22 WARN]:        at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:130)
[13:35:22 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.setInt(JDBC3PreparedStatement.java:329)
[13:35:22 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.setBoolean(JDBC3PreparedStatement.java:294
[13:35:22 WARN]:        at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1168)
[13:35:22 WARN]:        at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1054)
[13:35:22 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:648)
[13:35:22 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:363)
[13:35:22 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:277)
[13:35:22 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[13:35:22 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:5
[13:35:22 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReporti
[13:35:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:35:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:35:22 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:35:22 WARN]: java.lang.ArrayIndexOutOfBoundsException: 64
[13:35:22 WARN]:        at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:130)
[13:35:22 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.setInt(JDBC3PreparedStatement.java:329)
[13:35:22 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.setBoolean(JDBC3PreparedStatement.java:294
[13:35:22 WARN]:        at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1168)
[13:35:22 WARN]:        at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1054)
[13:35:22 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:648)
[13:35:22 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:363)
[13:35:22 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:277)
[13:35:22 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[13:35:22 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:5
[13:35:22 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReporti
[13:35:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[13:35:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[13:35:22 WARN]:        at java.lang.Thread.run(Unknown Source)
```

A second error similar to above
[20:12:57 INFO]: [CMI]  SEVERE SAVE ERROR WHILE SAVING RedValkyrja PLAYER DATA (BannedUntil)
[20:12:57 WARN]: java.lang.ArrayIndexOutOfBoundsException
[20:12:57 WARN]: java.lang.ArrayIndexOutOfBoundsException

CMI Version: CMI8.6.19.1

Server Type Paper

Server Version: 1.15.2

**Comment by Zrips** [comment]
fixed
