### ISSUE TITLE
Unicode Nicknames

### ISSUE THREAD

**Issue by metalshark** [Zrips/CMI#2785]
**Description of issue:**
Users of our server have unicode names, either due to being international or containing emoji's through systems like emojichat. Their nickname isn't set by CMI and we receive an error in the logs.
---

**ERROR:**
```
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: java.sql.BatchUpdateException: Incorrect string value: '\xF0\x9F\x8C\x88' for column 'nickname' at row 1
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1832)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1316)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:814)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:400)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:277)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: Caused by: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x8C\x88' for column 'nickname' at row 1
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1810)
[05:01:06] [Craft Scheduler Thread - 1190/WARN]: 	... 11 more
```

**eventCommands.yml:**
```
firstJoinServer:
  Enabled: true
  Commands:
  - cmi nick %discordsrv_user_name% [playerName]
  - cmi nameplate [playerName] -c:%discordsrv_user_top_role_color_code%
joinServer:
  Enabled: true
  Commands:
  - cmi nick %discordsrv_user_name% [playerName]
  - cmi nameplate [playerName] -c:%discordsrv_user_top_role_color_code%
```

---
**Cmi Version (using`/cmi version`):** 
8.6.19.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper version git-Paper-99 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
**Relevant plugins (Delete if this isn't needed):**
https://www.spigotmc.org/resources/emojichat.50955/
https://www.spigotmc.org/resources/discordsrv.18494/

**Comment by mrfloris** [comment]
I do not understand the technical possibilities for nicknames in Minecraft, but I do believe that Mojang has a limit on valid usernames, like, up to 16 characters, and `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_` only. anything unicode might have to be as a suffix or prefix, correct? 

To be honest, I've never seen a nickname with special characters on a server. But maybe I also simply haven't noticed.

**Comment by metalshark** [comment]
Definitely under 16 characters in length. The nickname appears correctly in game (including autocomplete) but not when saving to the database.

**Comment by metalshark** [comment]
There are also nickname generators now utilising the Unicode it supports:
https://nickfinder.com/Minecraft

**Comment by Zrips** [comment]
@metalshark 
Are you running offline server? Because i cant find any information about Mojang allowing anything besides abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_

**Comment by metalshark** [comment]
No the server is online. It’s the nickname functionality.

**Comment by metalshark** [comment]
For instance you can put an & in your Mojang name, but you can in a nickname for colouring

**Comment by metalshark** [comment]
It’s also why nickname generators such as https://nickfinder.com/Minecraft give you unicode

**Comment by metalshark** [comment]
Here is a quick demo of setting a couple of unicode nicknames using CMI.
![image](https://user-images.githubusercontent.com/146708/74266894-fc80f200-4cfc-11ea-9a8c-e5806e0ea898.png)

**Comment by metalshark** [comment]
The Bank plugin (which supports the names) uses:
`useUnicode=true&characterEncoding=utf-8`
and the character set: UTF8MB4

**Comment by metalshark** [comment]
Changed the character set of the nickname field on the users table of CMI to utf8mb4_unicode_ci and it fixed the issue. You may want to do the same.
