### ISSUE TITLE
DeathMessage error

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#280]
Had a player teleporting while on horseback and then glitch according to what the player said. The player suffocated in a wall. This is the error the console shows.

[23:53:51] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to CMI v7.6.10.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityLiving.Y(EntityLiving.java:210) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.Entity.B_(Entity.java:320) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1873) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:145) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:313) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:139) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_161]
	at com.Zrips.CMI.Modules.DeathMessages.DeathMessages.getRandom(DeathMessages.java:21) ~[?:?]
	at com.Zrips.CMI.Modules.DeathMessages.DeathMessageManager.getDeathMessage(DeathMessageManager.java:109) ~[?:?]
	at com.Zrips.CMI.Modules.DeathMessages.DeathMessageListener.onPlayerMove(DeathMessageListener.java:37) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-eadd615-9060bfa]
	... 21 more
[23:53:51] [Server thread/INFO]: QueenOhChickens suffocated in a wall

Cmi Version (using`/cmi version 7.6.10.0`): 
Server Type (Spigot): 
Server Version (1.12.2`):

**Comment by CloudeLecaw** [comment]
The poor ChickenQueen =(((((

i tried /cmi back -> worked
![image](https://user-images.githubusercontent.com/12080017/39034110-738cad86-4475-11e8-91d5-e97b2fcfa970.png)

i tried /cmi spawn -> worked
![image](https://user-images.githubusercontent.com/12080017/39034079-4f532df0-4475-11e8-81b0-f951cf0f9f02.png)

no Errors in console:

May this is an error that does not affect all Servers aggain

![image](https://user-images.githubusercontent.com/12080017/39034137-9e822a20-4475-11e8-99cc-b06dafdc6ab3.png)

**Comment by CypherPhyre** [comment]
You seem to have missed the point of this post. The issue is not that the player died. Sometimes players suffocate in walls as they randomly teleport to an unsafe area (this setting config is on purpose and is not part of CMI). When players die in this manner, the death message is triggered normally. This is the first time I am aware of a player doing so while on horseback. Teleportation with an entity is part of CMI and is enabled. The issue is how the death message was handled. Your comment "The poor ChickenQueen =(((((" was not needed.

**Comment by CloudeLecaw** [comment]
So it was wanted that QueenOhChicken died? ;(

**Comment by CypherPhyre** [comment]
I never said it was a test. This is an error that showed in the console.

**Comment by ScuroK** [comment]
[21:03:37] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to CMI v7.6.10.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at fr.neatmonster.nocheatplus.compat.cbdev.MCAccessCBDev.dealFallDamage(MCAccessCBDev.java:238) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.dealFallDamage(NoFall.java:179) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.handleOnGround(NoFall.java:94) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.touchDown(NoFall.java:336) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.check(NoFall.java:279) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.moving.MovingListener.checkPlayerMove(MovingListener.java:832) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMove(MovingListener.java:481) [NoCheatPlus.jar:?]
	at sun.reflect.GeneratedMethodAccessor242.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$1.onEvent(MultiListenerRegistry.java:102) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:152) [NoCheatPlus.jar:?]
	at fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124) [NoCheatPlus.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:654) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-eadd615-bea5a84]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_162]
	at com.Zrips.CMI.Modules.DeathMessages.DeathMessages.getRandom(DeathMessages.java:21) ~[?:?]
	at com.Zrips.CMI.Modules.DeathMessages.DeathMessageManager.getDeathMessage(DeathMessageManager.java:109) ~[?:?]
	at com.Zrips.CMI.Modules.DeathMessages.DeathMessageListener.onPlayerMove(DeathMessageListener.java:37) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1284.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-eadd615-bea5a84]
	... 36 more
[21:03:37] [Server thread/INFO]: TDrost fell from a high place

**Comment by ScuroK** [comment]
and from time to time it shows a chat message saying "&e fall down" no idea why.

**Comment by ScuroK** [comment]
im not sure but i think latest update fixes it

**Comment by CypherPhyre** [comment]
It may have. Won't know unless said conditions happen again. I will close this for now.
