### ISSUE TITLE
Error occurred while enabling CMI v8.6.19.5

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#2813]
paper-Version: Paper version git-Paper-112 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

CMI v8.6.19.5

```
[17:22:54] [Server thread/ERROR]: Error occurred while enabling CMI v8.6.19.5 (Is it up to date?)
java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "github/scarsz/discordsrv/api/events/DiscordGuildMessageSentEvent"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_212]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_212]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_212]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_212]
	at github.scarsz.discordsrv.api.ApiManager.subscribe(ApiManager.java:60) ~[?:?]
	at com.Zrips.CMI.Modules.DiscordSRV.DiscordSRVManager.<init>(DiscordSRVManager.java:21) ~[?:?]
	at com.Zrips.CMI.CMI.getDiscordSRVManager(CMI.java:444) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1620) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

[17:25:24] [Server thread/ERROR]: Could not pass event PlayerAdvancedAchievementEvent to AdvancedAchievements v5.14.1
java.lang.NoClassDefFoundError: com/Zrips/CMI/Modules/Economy/Economy
	at com.Zrips.Economy_CMI.depositPlayer(Economy_CMI.java:98) ~[?:?]
	at com.hm.achievement.listener.PlayerAdvancedAchievementListener.rewardMoney(PlayerAdvancedAchievementListener.java:284) ~[?:?]
	at com.hm.achievement.listener.PlayerAdvancedAchievementListener.giveRewardsAndPrepareTexts(PlayerAdvancedAchievementListener.java:215) ~[?:?]
	at com.hm.achievement.listener.PlayerAdvancedAchievementListener.onPlayerAdvancedAchievementReception(PlayerAdvancedAchievementListener.java:182) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor708.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-112]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-112]
	at com.hm.achievement.utils.StatisticIncreaseHandler.checkThresholdsAndAchievements(StatisticIncreaseHandler.java:95) ~[?:?]
	at com.hm.achievement.listener.statistics.AbstractListener.updateStatisticAndAwardAchievementsIfAvailable(AbstractListener.java:56) ~[?:?]
	at com.hm.achievement.listener.statistics.PickupsListener.onPlayerPickupItem(PickupsListener.java:38) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor672.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-112]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.EntityItem.pickup(EntityItem.java:356) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.EntityHuman.c(EntityHuman.java:492) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.EntityHuman.movementTick(EntityHuman.java:465) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2383) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:430) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:149) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.Modules.Economy.Economy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	... 31 more
[17:25:41] [Server thread/INFO]: Opa_Gerd issued server command: /fly
[17:25:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'fly' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(fly)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1821) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1629) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Paper-112]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-112]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_212]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_212]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_212]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:133) ~[patched_1.15.2.jar:git-Paper-112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
	at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:594) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.getDisplayName(CMIUser.java:657) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.getDisplayName(CMIUser.java:650) ~[?:?]
	at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:313) ~[?:?]
	at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:189) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:155) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-112]
	... 16 more
```

**Comment by LogGits** [comment]
@Blueeyestar is this still happening or was it resolved?

**Comment by Zrips** [comment]
Issue like this comes from invalid plugin file which can be corrupted during download from spigot site, or incorrect plugin load like plugman and similar. This can be resolved by simply redownloading plugin and performing full server restart
