### ISSUE TITLE
Migrate Database throwing errors

### ISSUE THREAD

**Issue by banit** [Zrips/CMI#2832]
```
10:08:28
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
AsyncLogger error handling event seq=1634, value='':
java.lang.NullPointerException
at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

`0:14:10
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:277)
at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)
at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)
at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)
at com.Zrips.CMI.Containers.CMIUser.getNameColor(CMIUser.java:700)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:613)
at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:579)
at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CMIUser.java:575)
AsyncLogger error handling event seq=9137, value=' at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:513)':
java.lang.NullPointerException
AsyncLogger error handling event seq=9138, value=' at com.Zrips.CMI.Modules.Permissions.LuckPermsHandler5.getNameColor(LuckPermsHandler5.java:74)':
java.lang.NullPointerException
AsyncLogger error handling event seq=9139, value=' at com.Zrips.CMI.Modules.Permissions.PermissionsManager.getNameColor(PermissionsManager.java:637)':
java.lang.NullPointerException`

Paper 105, CMI 8.6.19.5

**Comment by Zrips** [comment]
Should get fixed with next build
