### ISSUE TITLE
Player Death Messages just say "&efall down"

### ISSUE THREAD

**Issue by tmellen** [Zrips/CMI#287]
Description of issue or feature request:

When players die on the server, it used to say "Player was killed by..." and pass the message. Now it just says "&efall down". It's been going on a couple of days.

I had no idea what was causing this until I saw this in the console. Can you take a look?

Thanks!

ERROR:
```
22.04 09:54:01 [Server] ERROR Could not pass event PlayerDeathEvent to CMI v7.6.10.0
22.04 09:54:01 [Server] INFO org.bukkit.event.EventException: null
22.04 09:54:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:413) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.die(EntityPlayer.java:432) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:956) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.EntityHuman.damageEntity(EntityHuman.java:759) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.damageEntity(EntityPlayer.java:586) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.EntityArrow.a(EntityArrow.java:286) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.EntityArrow.B_(EntityArrow.java:194) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.EntityTippedArrow.B_(EntityTippedArrow.java:86) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.World.h(World.java:1601) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:668) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
22.04 09:54:01 [Server] INFO Caused by: java.lang.IllegalArgumentException: bound must be positive
22.04 09:54:01 [Server] INFO at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_152]
22.04 09:54:01 [Server] INFO at com.Zrips.CMI.Modules.DeathMessages.DeathMessages.getRandom(DeathMessages.java:21) ~[?:?]
22.04 09:54:01 [Server] INFO at com.Zrips.CMI.Modules.DeathMessages.DeathMessageManager.getDeathMessage(DeathMessageManager.java:109) ~[?:?]
22.04 09:54:01 [Server] INFO at com.Zrips.CMI.Modules.DeathMessages.DeathMessageListener.onPlayerMove(DeathMessageListener.java:37) ~[?:?]
22.04 09:54:01 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
22.04 09:54:01 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
22.04 09:54:01 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
22.04 09:54:01 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
22.04 09:54:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-21d5f75]
22.04 09:54:01 [Server] INFO ... 20 more```

Cmi Version (using`/cmi version`): CMI plugin version: 7.6.10.0-> null
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.12.2-R0.1-SNAPSHOT (Latest)

**Comment by LogGits** [comment]
Are you still getting this in 7.6.10.1?

**Comment by tmellen** [comment]
I haven't upgraded yet due to the patch notes and not seeing console errors:
Just small fix for some code i forgot to disable and now its throwing out error messages. No harm in having them, just unneeded spam in console.

I'll load it up and see.

**Comment by MCTyler** [comment]
Good Job! ...and it no longer kills you when cliff diving into water!

**Comment by MCTyler** [comment]
@tmellen YOU Close the thread!
