### ISSUE TITLE
[Bug] Certain items show invisible on holograms as icon

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2884]
**Description of issue:**

Vincent on Discord mentioned that he couldn't use tripwire, i looked. into this and can reproduce this. See screenshots

i can add stone or stick, but i can't enchant a stick (shows invisible) and i can't show a tripwire hook  that is enchanted 
<img width="1392" alt="Screenshot 2020-03-03 at 19 43 32" src="https://user-images.githubusercontent.com/28841349/75808893-1c4d8800-5d88-11ea-9f76-802474ce8206.png">
<img width="1392" alt="Screenshot 2020-03-03 at 19 43 17" src="https://user-images.githubusercontent.com/28841349/75808904-2079a580-5d88-11ea-9ce1-fccd82211cf0.png">

I think something's wrong.

```
[19:43:53] [Server thread/WARN]: [CMI] Task #74806 for CMI v8.6.20.0 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.Zrips.CMI.Modules.CmiItems.ItemManager.getItem(ItemManager.java:255) ~[?:?]
        at com.Zrips.CMI.Modules.Holograms.CMIHologram$1$1.run(CMIHologram.java:728) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-8faa8b4-13ed05d]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-8faa8b4-13ed05d]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-8faa8b4-13ed05d]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Console also has this message. 

```
>ver
[19:48:29] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-8faa8b4-13ed05d (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[19:48:29] [Server thread/INFO]: Checking version, please wait...
[19:48:29] [Thread-90/INFO]: You are running the latest version
>cmi version
[19:48:31] [Server thread/INFO]: --------------------------------------------------
[19:48:31] [Server thread/INFO]: CMI plugin version: 8.6.20.0-> 8.6.19.10
[19:48:31] [Server thread/INFO]: Server version: Spigot 1.15.2-R0.1-SNAPSHOT
[19:48:31] [Server thread/INFO]: Vault version: 1.7.3-b
[19:48:31] [Server thread/INFO]: --------------------------------------------------
>
```

**Comment by Zrips** [comment]
**ICON:Stick%enchanted%**
You added : which caused this error. Will fix error and you can fix format and it will work
