### ISSUE TITLE
Warning loading playerdata

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#2898]
**Description of issue:**
I'm getting this warning every time starting the Server. Don't know it if has an effect on player join, but sometimes we're expieriencing massive lag on join
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:35:41] [Server thread/WARN]: java.lang.IllegalArgumentException: UUID cannot be null
[17:35:41] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[17:35:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.getOfflinePlayer(CraftServer.java:1438)
[17:35:41] [Server thread/WARN]: 	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:834)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getOfflinePlayer(CMIUser.java:431)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getName(CMIUser.java:442)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIUser.getName(CMIUser.java:424)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.checkForExistingSimilarUser(PlayerManager.java:598)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1837)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1099)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:570)
[17:35:41] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1420)
[17:35:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[17:35:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[17:35:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[17:35:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[17:35:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[17:35:41] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
[17:35:41] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[17:35:41] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[17:35:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[17:35:42] [Server thread/INFO]:   Loaded (1124) player data into memory. Took 434ms
```

**Cmi Version (using`/cmi version`):** 
v8.6.20.2
**Server Type (Spigot/Paperspigot/etc):** 
Paper ver 126
**Server Version (using `/ver`):** 
1.15.2

**Comment by Zrips** [comment]
Should be improved with next update
