### ISSUE TITLE
cmi vault can't load

### ISSUE THREAD

**Issue by Rirbe** [Zrips/CMI#2929]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[06:55:36] [Server thread/ERROR]: Could not load 'plugins\Vault-1.7.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:352) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-131]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-131]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:203) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.2.jar:git-Paper-131]
	at net.milkbowl.vault.Vault.<init>(Vault.java:106) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.15.2.jar:git-Paper-131]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:206) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[patched_1.15.2.jar:git-Paper-131]
	at sk.jakubvanko.ultrachest.UltraChest.<init>(UltraChest.java:12) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.15.2.jar:git-Paper-131]
	... 6 more
[06:55:36] [Server thread/ERROR]: Could not load 'plugins\advancedregionmarket.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:239) ~[patched_1.15.2.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) ~[patched_1.15.2.jar:git-Paper-131]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-131]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```
https://zerobin.net/?d790589b9b55b10e#urGE+iGCoKHaDYFzxddwfaKim7N/E3tfvh7Dzhzs0Aw=

---

**Cmi Version (using`/cmi version`):** 
CMI8.6.20.4
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
131
**Relevant plugins (Delete if this isn't needed):**

**Comment by LogGits** [comment]
This looks like you have 2 vault jar files in your plugin folder. If this is not the case please reply (with a full startup log) and i'll reopen this.
