### ISSUE TITLE
CMI petblocks worldguard error?

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#294]
Description of issue or feature request:

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR:
```
[PetBlocks] Failed to connect to worldguard
java.lang.NoSuchMethodException: com.sk89q.worldguard.protection.managers.RegionManager.getApplicableRegions(com.Zrips.CMI.Containers.CMILocation)
	at java.lang.Class.getDeclaredMethod(Class.java:2130) ~[?:1.8.0_161]
	at com.github.shynixn.petblocks.core.logic.business.helper.ReflectionUtils.invokeMethodByObject(ReflectionUtils.java:167) ~[PetBlocks-Bukkit.jar:?]
	at com.github.shynixn.petblocks.core.logic.business.helper.ReflectionUtils.invokeMethodByObject(ReflectionUtils.java:139) ~[PetBlocks-Bukkit.jar:?]
	at com.github.shynixn.petblocks.bukkit.dependencies.worldguard.WorldGuardConnection6.getRegionsFromLocation(WorldGuardConnection6.java:124) ~[PetBlocks-Bukkit.jar:?]
	at com.github.shynixn.petblocks.bukkit.nms.NMSRegistry.getWorldGuardRegionsFromLocation(NMSRegistry.java:215) [PetBlocks-Bukkit.jar:?]
	at com.github.shynixn.petblocks.bukkit.logic.persistence.configuration.Config.handleRegionSpawn(Config.kt:126) [PetBlocks-Bukkit.jar:?]
	at com.github.shynixn.petblocks.bukkit.logic.persistence.configuration.Config.allowPetSpawning(Config.kt:113) [PetBlocks-Bukkit.jar:?]
	at com.github.shynixn.petblocks.bukkit.logic.business.listener.PetBlockListener.onPlayerTeleportEvent(PetBlockListener.java:197) [PetBlocks-Bukkit.jar:?]
	at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.teleport(CraftPlayer.java:510) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.teleport(CraftEntity.java:271) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:330) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:309) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:187) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:149) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:144) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.commands.list.warp.perform(warp.java:120) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209) [CMI7.6.7.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:541) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:446) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:65) [CMI7.6.7.0.jar:?]
	at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) [CMI7.6.7.0.jar:?]
	at sun.reflect.GeneratedMethodAccessor296.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [paperclip.jar:git-Spigot-b6ecf3b-fb423b8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

Cmi Version (using`/cmi version`): 7.6.6.2
Server Type (Spigot/Paperspigot/etc): Paper
Server Version (using `/ver`): 1.12.2

**Comment by CloudeLecaw** [comment]
Failed to connect to worldgaurd?
is this really an error causesd from CMI?

**Comment by LogGits** [comment]
As @CloudeLecaw stated this is not related to cmi.
