### ISSUE TITLE
Bossbar Bug

### ISSUE THREAD

**Issue by YTRemRem** [Zrips/CMI#2957]
It looks like is bossbar problem but I don't really know what to do

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
> [20:28:57 WARN]: [CMI] Task #1521796 for CMI v8.6.20.3 generated an exception
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (NaN)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[server.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.craftbukkit.v1_13_R2.boss.CraftBossBar.setProgress(CraftBossBar.java:159) ~[server.jar:git-Spigot-1a3504a-84f3da3]
at com.Zrips.CMI.Modules.BossBar.BossBarManager$1.run(BossBarManager.java:179) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-1a3504a-84f3da3]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [server.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [server.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [server.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [server.jar:git-Spigot-1a3504a-84f3da3]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [server.jar:git-Spigot-1a3504a-84f3da3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

---

**Cmi Version (using`/cmi version`):** 8.6.20.3

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 1.13.2

**Comment by Steev93** [comment]
What command did you try and do?
