### ISSUE TITLE
Cmi money error

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#2964]
**Description of issue:**
typi
`/cmi money give all 10` (yes 10) yields this error:

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
java.lang.NumberFormatException: For input string: "l"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at com.Zrips.CMI.Modules.Economy.EconomyManager.translateMoney(EconomyManager.java:331)
at com.Zrips.CMI.commands.list.money.perform(money.java:172)
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:299)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825)
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633)
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
at java.lang.Thread.run(Thread.java:748)
```
---

**Cmi Version (using`/cmi version`):** 8.6.20.5

**Server Type (Spigot/Paperspigot/etc):** paper

**Server Version (using `/ver`):** Paper 1.15.2 build 132

**Comment by Steev93** [comment]
Running the same thing and didn't give off an error, do you have full logs please?

/cmi money give all 1 -s

http://prntscr.com/rocgfx
