### ISSUE TITLE
Cmi plugin don't work with MmoItems

### ISSUE THREAD

**Issue by LeBelgeDuTurfu** [Zrips/CMI#2999]
**CMI plugin does not work with Mmoitem. 
I removed and returned the plugins 1 to 1 and only CMI is the problem
I have Mmocore,lib,items and mythicmob**

---

**null initializing MMOItems v5.3.2 (Is it up to date?)**
```
java.lang.NullPointerException: null
at net.Indyuce.mmoitems.comp.mmocore.MMOCoreMMOLoader.<init>(MMOCoreMMOLoader.java:31) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.onLoad(MMOItems.java:113) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Error occurred while enabling MMOItems v5.3.2 (Is it up to date?)**
```
java.lang.NullPointerException: null
at net.Indyuce.mmoitems.manager.ConfigManager.<init>(ConfigManager.java:101) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:130) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a03b1fd-fc318cc]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Basic plugin configuration**
---

**Cmi Version 8.6.20.9** 

**Server Type: Spigot** 

**Server Version CraftBukkit version git-Spigot-a03b1fd-fc318cc (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT):**

**Comment by Zrips** [comment]
Those errors doesnt really point to CMI plugin. Its pointing towards mmoitems config file failing to load their files for one or another reasson. 
Just tested clean install of latest CMI 8.6.20.9 MMOLib-1.0.9 MMOItems-5.3.2 no issues, everything loads as it should and no errors.
