### ISSUE TITLE
I can't unban people!

### ISSUE THREAD

**Issue by pvvvo** [Zrips/CMI#3030]
**Description of issue:**
Can't unban, the only way it's deleting them from the files. When i do /tempipban name 1s -s and then check with /checkban i get an error

---

**ERROR (DELETE IF YOU HAVE NO ERROR): **
```
######################
## [23:41:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.21.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_15_R1.CraftIpBanEntry.<init>(CraftIpBanEntry.java:21) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftIpBanList.getBanEntries(CraftIpBanList.java:57) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	at com.Zrips.CMI.commands.list.checkban.perform(checkban.java:84) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:297) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Tuinity-"c2ad42c"]
	... 17 more
 ##
######################


**Cmi Version (using`/cmi version`): 8.6.21.1** 

**Server Type (Spigot/Paperspigot/etc): Tuinity** 

**Server Version (using `/ver`): Tuinity build 31**

**Comment by Zrips** [comment]
Tuinity? This type of server is not in a supported list. So some issues will be seen. Will make some changes related to this error message, but this is only to check ban state and not to unban player. If you are getting any errors when trying to unban player, let me know. But this error should be fixed with next build.
