### ISSUE TITLE
error on console

### ISSUE THREAD

**Issue by griot007** [Zrips/CMI#3034]
[15:11:29 WARN]: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 1540, column 13:
        MaxLevel:
                ^

[15:11:29 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[15:11:29 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
[15:11:29 WARN]:        at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:225)
[15:11:29 WARN]:        at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:43)
[15:11:29 WARN]:        at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:35)
[15:11:29 WARN]:        at com.Zrips.CMI.Config.load(Config.java:692)
[15:11:29 WARN]:        at com.Zrips.CMI.Config.load(Config.java:687)
[15:11:29 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1363)
[15:11:29 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:11:29 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:11:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:11:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[15:11:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[15:11:29 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:11:29 WARN]: Caused by: mapping values are not allowed here
 in 'string', line 1540, column 13:
        MaxLevel:
                ^

[15:11:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
[15:11:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
[15:11:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[15:11:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
[15:11:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[15:11:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[15:11:29 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
[15:11:29 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
[15:11:29 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
[15:11:29 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[15:11:29 WARN]:        ... 18 more
[15:11:29 INFO]:   Failed to load config.yml! Backup have been saved into plugins\CMI\FileBackups\2020-04-03 15-11-29 config.yml
[15:11:29 WARN]: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 1540, column 13:
        MaxLevel:
                ^

[15:11:29 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[15:11:29 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
[15:11:29 WARN]:        at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:225)
[15:11:29 WARN]:        at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:43)
[15:11:29 WARN]:        at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:35)
[15:11:29 WARN]:        at com.Zrips.CMI.Config.load(Config.java:692)
[15:11:29 WARN]:        at com.Zrips.CMI.Config.load(Config.java:687)
[15:11:29 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1363)
[15:11:29 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[15:11:29 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:11:29 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:11:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[15:11:29 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[15:11:29 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[15:11:29 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:11:29 WARN]: Caused by: mapping values are not allowed here
 in 'string', line 1540, column 13:
        MaxLevel:
                ^

[15:11:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
[15:11:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
[15:11:29 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[15:11:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
[15:11:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
[15:11:29 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:229)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[15:11:29 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[15:11:29 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
[15:11:29 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
[15:11:29 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369)
[15:11:29 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[15:11:29 WARN]:        ... 18 more
[15:11:29 ERROR]: Error occurred while enabling CMI v8.6.21.1 (Is it up to date?)
java.lang.NullPointerException
        at com.Zrips.CMI.Config.load(Config.java:701) ~[?:?]
        at com.Zrips.CMI.Config.load(Config.java:687) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1363) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

help pls

**Comment by griot007** [comment]
i fixed sorry
