### ISSUE TITLE
SQL error / money error

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3071]
**Description of issue:**

See below.

And just a little up for [#3028](https://github.com/Zrips/CMI/issues/3028)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>.... [22:42:11 WARN]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '6bc83ab' at line 1
>.... [22:42:11 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>.... [22:42:11 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>.... [22:42:11 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>.... [22:42:11 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>.... [22:42:11 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
>.... [22:42:11 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
>.... [22:42:11 WARN]: at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154)
>.... [22:42:11 WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1832)
>.... [22:42:11 WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1316)
>.... [22:42:11 WARN]: at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954)
>.... [22:42:11 WARN]: at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:830)
>.... [22:42:11 WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:419)
>.... [22:42:11 WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:281)
>.... [22:42:11 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
>.... [22:42:11 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
>.... [22:42:11 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
>.... [22:42:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [22:42:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [22:42:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [22:42:11 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '6bc83ab' at line 1
>.... [22:42:11 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>.... [22:42:11 WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>.... [22:42:11 WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>.... [22:42:11 WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>.... [22:42:11 WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
>.... [22:42:11 WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408)
>.... [22:42:11 WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
>.... [22:42:11 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
>.... [22:42:11 WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
>.... [22:42:11 WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
>.... [22:42:11 WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
>.... [22:42:11 WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
>.... [22:42:11 WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
>.... [22:42:11 WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
>.... [22:42:11 WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1810)
>.... [22:42:11 WARN]: ... 11 more
```

---

**Cmi Version (using`/cmi version`):** 
8.6.21.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
155

**Comment by maxlehot1234** [comment]
Same issue for me #3069 
@Zrips ?

**Comment by CloudeLecaw** [comment]
`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '6bc83ab' at line `

**Comment by maxlehot1234** [comment]
Seems to occured only with offline players, but not 100% sure.

Why not make CMI create this table?

**Comment by CloudeLecaw** [comment]
If the table is created for online players this means offline players have it too, because the table is counting for all. the offline players just have a NULL value or 0 there at the moment. I renember when we where changing to MYSQL we also needed to set the balance from the old stores value into the MYSQL tables. but after that it worked fine, also for offline players if CMI allready manges the Balance.

We are usiing CMI + CMIInjector (for full Valut compatibility) + Vault

**Comment by Zrips** [comment]
Should be resolved
