### ISSUE TITLE
internal error while issuing "/i water"

### ISSUE THREAD

**Issue by Ahmadh26** [Zrips/CMI#3109]
**Description of issue:**
i tried running the command `/i water` but it said an internal error has occurred, the console log is below. 
pretty sure that it shouldn't error even if the item is not correct .. so thought i'd mention it here.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
>.... [10:03:48 INFO]: _Jayy26 issued server command: /i water
>.... [10:03:48 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.22.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-162]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-162]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: Item cannot be null
at org.apache.commons.lang.Validate.noNullElements(Validate.java:364) ~[patched_1.15.2.jar:git-Paper-162]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.addItem(CraftInventory.java:287) ~[patched_1.15.2.jar:git-Paper-162]
at com.Zrips.CMI.Containers.CMIPlayerInventory.addItem(CMIPlayerInventory.java:79) ~[?:?]
at com.Zrips.CMI.Containers.CMIPlayerInventory.addItem(CMIPlayerInventory.java:73) ~[?:?]
at com.Zrips.CMI.commands.list.give.perform(give.java:313) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.performCMICommand(CommandsHandler.java:89) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.performCMICommand(CommandsHandler.java:82) ~[?:?]
at com.Zrips.CMI.commands.list.item.perform(item.java:29) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:297) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-162]
... 17 more
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.22.1 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
Paper(162) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should be fixed with next build and will have appropriate message to inform that its incorrect item type
