### ISSUE TITLE
/cmi vanish I get an error but I still go into vanish.

### ISSUE THREAD

**Issue by AppleMacOS** [Zrips/CMI#3126]
**Description of issue:**
When using /cmi vanish I get an error but I still go into vanish.

---

**ERROR**
```
17.04 13:45:41 [Server] ERROR null
17.04 13:45:41 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.22.2
17.04 13:45:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [?:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [?:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
17.04 13:45:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
17.04 13:45:41 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/boss/BarColor
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:95) ~[?:?]
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.Containers.CMIUser.setVanished(CMIUser.java:1773) ~[?:?]
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.commands.list.vanish.perform(vanish.java:73) ~[?:?]
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:297) ~[?:?]
17.04 13:45:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO ... 15 more
17.04 13:45:41 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.boss.BarColor
17.04 13:45:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
17.04 13:45:41 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:95) ~[?:?]
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.Containers.CMIUser.setVanished(CMIUser.java:1773) ~[?:?]
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.commands.list.vanish.perform(vanish.java:73) ~[?:?]
17.04 13:45:41 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:297) ~[?:?]
17.04 13:45:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
17.04 13:45:41 [Server] INFO ... 15 more
```
---

**Cmi Version (using`/cmi version`):**  8.6.22.2

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):**  This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
could it be u have setup a wrong not allowed colorcode for you Bossbar?
Not all corlor allowed - specialy for the backgrounds and strip

Why i think so?
your error log tells us:
`17.04 13:45:41 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.boss.BarColor`

**Comment by AppleMacOS** [comment]
I haven't changed anything for the vanish bossbar.

**Comment by CloudeLecaw** [comment]
Also not in your language file?

**Comment by AppleMacOS** [comment]
All the vanish related things are set to the default in the language file.

**Comment by AppleMacOS** [comment]
Looks like it doesn't throw an error anymore, so I'll close this.
