### ISSUE TITLE
player join skin error

### ISSUE THREAD

**Issue by jbbpt** [Zrips/CMI#3152]
**player join skin error :**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
##[Craft Scheduler Thread - 142/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at com.Zrips.CMI.Modules.Skin.SkinManager.setSkin(SkinManager.java:157)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:119)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:100)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at com.Zrips.CMI.Modules.Skin.SkinListener$2$1.run(SkinListener.java:52)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:15:08] [Craft Scheduler Thread - 142/WARN]: at java.lang.Thread.run(Thread.java:748)  ##
######################
```

---

**Cmi Version (8.6.22.2`):** 

**Server Type (Spigot):** 

**Server Version (1.15.2`):**

**Comment by RedAlphard** [comment]
``22.04 18:58:42 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
22.04 18:58:42 [Server] WARN at com.Zrips.CMI.Modules.Skin.SkinManager.setSkin(SkinManager.java:157)
22.04 18:58:42 [Server] WARN at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:119)
22.04 18:58:42 [Server] WARN at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:100)
22.04 18:58:42 [Server] WARN at com.Zrips.CMI.Modules.Skin.SkinListener$2$1.run(SkinListener.java:52)
22.04 18:58:42 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
22.04 18:58:42 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
22.04 18:58:42 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
22.04 18:58:42 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
22.04 18:58:42 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
22.04 18:58:42 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:834)

for a couple of days I have had this error at the entry of recently opped player (not opped in join).

**Cmi Version (8.6.22.2)**
**Version Paper 1.15.2 -199**

**Comment by Zrips** [comment]
Should be fixed with latest build
