### ISSUE TITLE
[Bug] /cmi editwarp NAME of removed world causes exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3159]
**Description of issue:**

/mvdelete worldname
/stop the server
start it up
/cmi editwarp worldname
-internal server error-

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[09:57:22] [Server thread/INFO]: mrfloris issued server command: /cmi editwarp test
[09:57:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.23.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.Warps.WarpManager.openWarpEditor(WarpManager.java:235) ~[?:?]
        at com.Zrips.CMI.commands.list.editwarp.perform(editwarp.java:60) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:297) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-94cb030]
        ... 17 more
```

---

```
>cmi version
 --------------------------------------------------
 CMI plugin version: 8.6.23.0
 Server version: Spigot 1.15.2-R0.1-SNAPSHOT
 Vault version: 1.7.3-b
 --------------------------------------------------
>
```

**Relevant plugins (Delete if this isn't needed):**
Multiverse-Core version 4.1.1-SNAPSHOT-b777 is used to remove the world.

**Comment by Zrips** [comment]
Will be fixed with next update
