### ISSUE TITLE
MySQL error: Failed to utilize complex MySQL insert

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#3166]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[01:52:03] [Craft Scheduler Thread - 189/WARN]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '2100fd3' at line 1
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1832)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1316)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:830)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:419)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:281)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = '2100fd3' at line 1
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at jdk.internal.reflect.GeneratedConstructorAccessor106.newInstance(Unknown Source)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1810)
[01:52:03] [Craft Scheduler Thread - 189/WARN]: 	... 11 more
[01:52:03] [Craft Scheduler Thread - 189/INFO]: [CMI] Failed to utilize complex MySQL insert syntax query, switching to simple one
```

---

**Cmi Version (using`/cmi version`): 8.6.23.1** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot fork named "SSSpigot"** 

**Server Version (using `/ver`):1.15.2**

**Comment by NineTown** [comment]
There another player_uuid every time i restart server

[02:00:40 WARN]: java.sql.BatchUpdateException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = 'cda82a5' at line 1
[02:00:40 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[02:00:40 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[02:00:40 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[02:00:40 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[02:00:40 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[02:00:40 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[02:00:40 WARN]:        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154)
[02:00:40 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1832)
[02:00:40 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1316)
[02:00:40 WARN]:        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954)
[02:00:40 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:830)
[02:00:40 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:419)
[02:00:40 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:281)
[02:00:40 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[02:00:40 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[02:00:40 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[02:00:40 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[02:00:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[02:00:40 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE NOT EXISTS (SELECT player_uuid FROM CMI_users WHERE player_uuid = 'cda82a5' at line 1
[02:00:40 WARN]:        at jdk.internal.reflect.GeneratedConstructorAccessor96.newInstance(Unknown Source)
[02:00:40 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[02:00:40 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[02:00:40 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[02:00:40 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[02:00:40 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[02:00:40 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[02:00:40 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[02:00:40 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[02:00:40 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[02:00:40 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[02:00:40 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
[02:00:40 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2133)
[02:00:40 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1810)
[02:00:40 WARN]:        ... 11 more
[02:00:40 INFO]: [CMI] Failed to utilize complex MySQL insert syntax query, switching to simple one

**Comment by Zrips** [comment]
As scary this error looks its not really a big deal. This most likely is caused by your outdated mysql database or some strange type of it. As some commonly used query fails I'm switching back to old regular one. Will add some extra checks and avoid displaying this message, so it should startup with a clean log with next version.
