### ISSUE TITLE
Opening GUI error with AIR emptyfields

### ISSUE THREAD

**Issue by BukkitProfi** [Zrips/CMI#3176]
When AIR is specified in the GlobalGui settings in the "Empty Field", then when you open the GUI (/cmi vanishedit), a NullPointerException occurs

---

**ERROR:**
```
[01:42:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.23.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-205]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-205]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[?:git-Paper-205]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[?:git-Paper-205]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1203) ~[patched_1.15.2.jar:git-Paper-205]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-205]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.GUI.CMIGui.addEmptyButton(CMIGui.java:269) ~[?:?]
        at com.Zrips.CMI.Modules.GUI.CMIGui.fillEmptyButtons(CMIGui.java:251) ~[?:?]
        at com.Zrips.CMI.Modules.GUI.CMIGui.fillEmptyButtons(CMIGui.java:243) ~[?:?]
        at com.Zrips.CMI.commands.list.vanishedit.perform(vanishedit.java:125) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:297) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-205]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
GlobalGui:
  # Defines item type in empty fields in GUI when its needed to be filled up
  EmptyField: AIR
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/64229180/80149253-c8189480-85cf-11ea-8dd5-f24212e216f7.png)

**Server Type (Spigot/Paperspigot/etc):** 
Paper/Tuinity
**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/64229180/80149295-d8c90a80-85cf-11ea-846d-47fa513793dd.png)

**Comment by Zrips** [comment]
Will be fixed with next build
