### ISSUE TITLE
NullPointerException BossBar

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3195]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[09:57:25] [Craft Scheduler Thread - 173/WARN]: [CMI] Plugin CMI v8.6.23.4 generated an exception while executing task 221363
java.lang.NullPointerException: null
	at com.Zrips.CMI.Modules.BossBar.BossBarInfo.cancelAutoScheduler(BossBarInfo.java:77) ~[?:?]
	at com.Zrips.CMI.Containers.CMIUser.addBossBar(CMIUser.java:1931) ~[?:?]
	at com.Zrips.CMI.utils.TimeManager$3$1.run(TimeManager.java:627) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Purpur-569]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Purpur-569]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Purpur-569]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.6.23.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Purpur version git-Purpur-569 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should get fixed with next version.
