### ISSUE TITLE
CMIPaperLib Error 

### ISSUE THREAD

**Issue by WolverStones** [Zrips/CMI#3209]
**Description of issue:**

---
[CMI] Enabling CMI v8.6.23.6
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:35:47 WARN]: org.bukkit.plugin.InvalidPluginException: java.io.FileNotFoundException: plugins\CMI\Libs\CMIPaperLib.jar does not exist
[19:35:47 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:76)
[19:35:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397)
[19:35:47 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1302)
[19:35:47 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:35:47 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
[19:35:47 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[19:35:47 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471)
[19:35:47 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385)
[19:35:47 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[19:35:47 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[19:35:47 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895)
[19:35:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:35:47 WARN]: Caused by: java.io.FileNotFoundException: plugins\CMI\Libs\CMIPaperLib.jar does not exist
[19:35:47 WARN]:        ... 12 more
```

---

**Cmi Version (using`/cmi version`):** 
[19:39:27 INFO]: --------------------------------------------------
[19:39:27 INFO]: CMI: 8.6.23.6 BungeeCord -> 8.6.23.5
[19:39:27 INFO]: Server version: Paper(226) 1.15.2-R0.1-SNAPSHOT
[19:39:27 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-226 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[19:39:00 INFO]: Checking version, please wait...
[19:39:00 INFO]: Previous version: git-Paper-162 (MC: 1.15.2)
[19:39:00 INFO]: You are running the latest version

**Relevant plugins (Delete if this isn't needed):**

 CMI, CMIEInjector*, LibsDisguises, ProtocolLib, Vault

**Comment by vicllow** [comment]
I had the same problem, but if you restart your server, CMI will download CMIPaperLib.jar in folder, where it must be ;)

**Comment by WolverStones** [comment]
> I had the same problem, but if you restart your server, CMI will download CMIPaperLib.jar in folder, where it must be ;)

yeah i didn't see it there anymore so it probably wasn't that hot: D
