### ISSUE TITLE
Big error spam in console

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3289]
**Description of issue:**
Hello, I have this big spam in console... there is much more of this.  It happens, when server starts.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[01:36:14] [Server thread/INFO]:   Failed to load workbench command!
[01:36:14] [Server thread/WARN]: java.lang.ClassNotFoundException: com.Zrips.CMI.commands.list.workbench
[01:36:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:141)
[01:36:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[01:36:14] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[01:36:14] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[01:36:14] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[01:36:14] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[01:36:14] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:561)
[01:36:14] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:523)
[01:36:14] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1438)
[01:36:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:36:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
[01:36:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[01:36:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471)
[01:36:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385)
[01:36:14] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[01:36:14] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[01:36:14] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896)
[01:36:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:36:14] [Server thread/WARN]: Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
[01:36:14] [Server thread/WARN]: 	at java.util.zip.ZipFile.read(Native Method)
[01:36:14] [Server thread/WARN]: 	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
[01:36:14] [Server thread/WARN]: 	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
[01:36:14] [Server thread/WARN]: 	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
[01:36:14] [Server thread/WARN]: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[01:36:14] [Server thread/WARN]: 	at java.io.FilterInputStream.read(FilterInputStream.java:107)
[01:36:14] [Server thread/WARN]: 	at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
[01:36:14] [Server thread/WARN]: 	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:166)
[01:36:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
[01:36:14] [Server thread/WARN]: 	... 17 more
[01:36:14] [Server thread/INFO]:   Failed to load nameplate command!
```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 8.6.24.3 BungeeCord

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-260 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Redownload plugin file, as it seems to be damaged.
