### ISSUE TITLE
8.6.24.4 Fully breaks on 1.12.2 Paper

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3312]
**Description of issue:**
I updated from 8.6.24.2 to 8.6.24.4 and CMI will not enable at boot.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:31:41] [Server thread/ERROR]: Error occurred while enabling CMI v8.6.24.4 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bukkit.enchantments.Enchantment.<init>(org.bukkit.NamespacedKey)'
	at com.Zrips.CMI.Modules.Enchants.CMIItemGlow.<init>(CMIItemGlow.java:12) ~[?:?]
	at com.Zrips.CMI.Modules.Enchants.CMIEnchantment.saveEnchants(CMIEnchantment.java:23) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1369) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[10:31:41] [Server thread/INFO]: [CMI] Disabling CMI v8.6.24.4
[10:31:41] [Server thread/INFO]:   Loaded (13) holograms into memory. Took 7ms
[10:31:41] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: Essentials Economy
[10:31:41] [Server thread/WARN]: java.lang.NullPointerException
[10:31:41] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1075)
[10:31:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[10:31:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350)
[10:31:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[10:31:41] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
[10:31:41] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:31:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:31:41] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:31:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:31:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:31:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:31:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:31:41] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:31:41] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

```

---

**Cmi Version (using`/cmi version`):** 8.6.24.4

**Server Type (Spigot/Paperspigot/etc):**  Paper 1.12.2

**Comment by CloudeLecaw** [comment]
hm i cant agree with this, may there is an error in your files...
with a clean folder of CMI you would see it will load fine.

Im also using the 8.6.24.4 but with latest paper 1.15.2

**Comment by AppleMacOS** [comment]
This is happening to me on 1.8.8 and 1.12.2

**Comment by CloudeLecaw** [comment]
so it just happens to the old outdated paperversions 1.8.8 and 1.12.2 i see:3
cant test this

**Comment by Zrips** [comment]
Sorry for inconvenience, this will be fixed with todays update.
