### ISSUE TITLE
Hologram console spam

### ISSUE THREAD

**Issue by Fabrimat** [Zrips/CMI#3338]
CMI spams this error in console

---
```
[CMI] Task #411391 for CMI v8.6.25.1 generated an exception
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-300]
	at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433) ~[patched_1.15.2.jar:git-Paper-300]
	at com.Zrips.CMI.NBT.v1_15_R1.makeFloatingIcon(v1_15_R1.java:1530) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:840) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-300]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-300]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-300]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-300]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-300]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-300]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
---

**Cmi Version (using`/cmi version`):** 8.6.25.1 BungeeCord 

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** git-Paper-282 (MC: 1.15.2)

**Comment by Zrips** [comment]
Should get fixed with next build
