### ISSUE TITLE
[Bug report] Portals not working

### ISSUE THREAD

**Issue by Andoz** [Zrips/CMI#3345]
**Description of issue or feature request:**
When I type and send command /portals it show me that error in console..

---

**ERROR:**
```

_org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.26.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1158) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance to a null world
at org.bukkit.Location.distanceSquared(Location.java:508) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.Location.distance(Location.java:493) ~[patched_1.14.4.jar:git-Paper-243]
at com.Zrips.CMI.Modules.Portals.PortalManager.getPortalsByDistance(PortalManager.java:619) ~[?:?]
at com.Zrips.CMI.commands.list.portals.perform(portals.java:109) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:316) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-243]
... 17 more_

```

---

**Cmi Version (using`/cmi version`):** 8.6.26.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-243 (MC: 1.14.4)

**Comment by Andoz** [comment]
### My portals.yml here:

```

# Command section can utilize same custom variables as scheduler. Check schedules.yml file for all possible variables.

Lobby:
  LobbyPriroda:
    Loc: -153.0:61.0:-2.0:-151.0:64.0:-2.0
    enabled: true
    effect: TOTEM
    showParticles: true
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 5
    particleHide: 0
    activationRange: 25
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - warp priroda [playerName]
  LobbyPvP:
    Loc: -167.0:61.0:-2.0:-165.0:64.0:-2.0
    enabled: true
    effect: crit
    showParticles: true
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 10
    particleHide: 0
    activationRange: 25
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - warp PvPArena [playerName]
  LobbyTutorial:
    Loc: -239.0:79.0:-54.0:-238.0:82.0:-54.0
    enabled: true
    effect: TOTEM
    showParticles: true
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 7
    particleHide: 0
    activationRange: 10
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - spawn [playerName]
    - mycmd tellto [playerName] &a&lTutoriĂˇl dokonÄŤen.. &8(&bodmÄ›na 100 Coins&8)
    - money give [playerName] 100
Build:
  PvPKit:
    Loc: -1.0:64.0:-1.0:1.0:64.0:1.0
    enabled: true
    effect: witchMagic
    showParticles: true
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 10
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: true
    commands:
    - deluxemenus open pvpvybaveni [playerName]
lobbyna:
  Spawn-Aukce:
    Loc: -1.0:45.0:-8.0:-1.0:48.0:-7.0
    enabled: true
    effect: enchantmenttable
    showParticles: true
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 10
    particleHide: 0
    activationRange: 20
    commandsWithoutTp: true
    commands:
    - ah [playerName]
  Spawn-Priroda:
    Loc: 11.0:45.0:-31.0:17.0:50.0:-31.0
    enabled: true
    effect: TOTEM
    showParticles: true
    safeLoc: world;-2053.41;73.0;87.31;18.12;6.6
    Tp: world;-2053.41;73.0;87.31;18.12;6.6
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 10
    particleHide: 0
    activationRange: 16
    commandsWithoutTp: false
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - warp priroda [playerName]
  SpawnPortal:
    Loc: -2.0:45.0:2.0:-2.0:48.0:5.0
    enabled: true
    effect: TOTEM
    showParticles: true
    requiresPerm: false
    informOnMissingPerm: false
    particleAmount: 5
    particleHide: 0
    activationRange: 20
    commandsWithoutTp: true
    commands:
    - cmi effect [playerName] blindness 2 1 -s
    - warp SkyIslands [playerName]

```

**Comment by CloudeLecaw** [comment]
i can reproduce this error:

i started in world "world"  there it works fine and the GUI opens
![Snag_15704e39](https://user-images.githubusercontent.com/12080017/82726795-c503e780-9ce6-11ea-9208-e229303d6081.png)

![Snag_1570abf9](https://user-images.githubusercontent.com/12080017/82726807-d220d680-9ce6-11ea-83c0-b2bf8a56ca5f.png)


Then i warped to world created with Multiverse called "newnether" a netherworld
![Snag_157166cd](https://user-images.githubusercontent.com/12080017/82726825-eebd0e80-9ce6-11ea-9d51-a812162bbe02.png)

```
[11:13:57 INFO]: Cloude_Lecaw issued server command: /portals
[11:13:57 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.26.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-304]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-304]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1097) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1090) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1164) ~[patched_1.15.2.jar:git-Paper-304]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-304]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance to a null world
	at org.bukkit.Location.distanceSquared(Location.java:508) ~[patched_1.15.2.jar:git-Paper-304]
	at org.bukkit.Location.distance(Location.java:493) ~[patched_1.15.2.jar:git-Paper-304]
	at com.Zrips.CMI.Modules.Portals.PortalManager.getPortalsByDistance(PortalManager.java:619) ~[?:?]
	at com.Zrips.CMI.commands.list.portals.perform(portals.java:109) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:316) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-304]
	... 17 more
```

i warped back to world "world" it works aggain

**Comment by CloudeLecaw** [comment]
EDIT after edting my portals in the portals.yml file they all work nowin all worlds

**Comment by Andoz** [comment]
Same for me, when I removed file portals.yml and than reloaded CMI and copy/paste content of old portals.yml in new created file it worked..

So **I'm closing thread** and I will be happy when some member of CMI help team will write back sometimes because we are paying for plugin and help not for seraching the bug on server and console..
