### ISSUE TITLE
GeoIP error

### ISSUE THREAD

**Issue by WolverStones** [Zrips/CMI#3393]
```
[CMI] Plugin CMI v8.6.26.5 generated an exception while executing task 3012
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:1.8.0_241]
at com.Zrips.CMI.Modules.GeoIP.LookupService.getLocation(LookupService.java:375) ~[?:?]
at com.Zrips.CMI.commands.list.info$1.run(info.java:202) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-318]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-318]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-318]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```
when I want to display information about a player who has ipv6, I don't see anything
and I get this error

**Comment by Zrips** [comment]
Will fix error, tho ipv6 isint supported at this time.
