### ISSUE TITLE
CMI info and GeoLiteCity

### ISSUE THREAD

**Issue by masterhacka** [Zrips/CMI#3398]
**Description of issue:**
Command /cmi info gives a NullPointerException
Also only the Country of the IP is providet and not the City. I am using GeoLiteCity.dat
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[11:17:06] [Server thread/WARN]: java.lang.NullPointerException
[11:17:06] [Server thread/WARN]:     at com.Zrips.CMI.commands.list.info$1.lambda$0(info.java:520)
[11:17:06] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[11:17:06] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[11:17:06] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[11:17:06] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:17:06] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[11:17:06] [Server thread/WARN]:     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[11:17:06] [Server thread/WARN]:     at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 8.6.26.5

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.12.2

**Comment by CloudeLecaw** [comment]
Is this the whole error? It looks like there is missing the half...

**Comment by masterhacka** [comment]
Yes it is

**Comment by Zrips** [comment]
Error should be fixed, for geolocation, i'm aware of missing town information, working on that one. For some reason it stopped returning correct town locations and more up to date database has even more restrictions due to privacy concerns.
