### ISSUE TITLE
 Error when performing /chat create <chatName> when a chat with the same name already exists

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#3413]
Error when performing /chat create <chatName> when a chat with the same name already exists

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.26.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1860) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1668) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1094) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1087) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1221) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:959) ~[patched_1.15.2.jar:git-Paper-284]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.commands.list.chat.perform(chat.java:120) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:319) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-284]
	... 17 more
######################
```

---

**Cmi Version (using`/cmi version`):** v8.6.26.7

**Server Type (Spigot/Paperspigot/etc):** paper(284)

**Server Version (using `/ver`):** 1.15.2

**Comment by Zrips** [comment]
Fixed
