### ISSUE TITLE
Incompatable with latest DiscordSRV Update

### ISSUE THREAD

**Issue by FrozenBeard** [Zrips/CMI#3425]
Using Paper 1.12.2, I updated to DiscordSRV 1.19.0 which needs its hook updated with CMI.
DiscordSRV 1.19.0 is actually broken on 1.12.2, so I will be backdating, but just a heads up that DiscordSRV updated.

```
[10:32:22] [Server thread/INFO]:   Found DiscordSRV, but it looks to be incompatible with current version
[10:32:22] [Server thread/WARN]: java.lang.NoClassDefFoundError: github/scarsz/discordsrv/DiscordSRV
[10:32:22] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DiscordSRV.DiscordSRVManager.<init>(DiscordSRVManager.java:20)
[10:32:22] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.getDiscordSRVManager(CMI.java:497)
[10:32:22] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1645)
[10:32:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:32:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:32:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:32:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:32:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:32:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:32:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:32:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:32:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:32:22] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:32:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:32:22] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: github.scarsz.discordsrv.DiscordSRV
[10:32:22] [Server thread/WARN]: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[10:32:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[10:32:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[10:32:22] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[10:32:22] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[10:32:22] [Server thread/WARN]: 	... 14 more
[10:32:22] [Server thread/INFO]: [CMI] Preloading playtimetop statistics
[10:32:22] [Server thread/INFO]:   Loaded (1) custom recipes into memory. Took 2ms
[10:32:22] [Server thread/INFO]:   Version 8.6.26.6 has been enabled
```

**Comment by Blueeyestar** [comment]
I also had problems but was fixed with the DiscordSRV-Build-1.19.1-SNAPSHOT. Please test it with it and then it should work again

[DiscordSRV-Build-1.19.1-SNAPSHOT-1591040482.zip](https://github.com/Zrips/CMI/files/4713120/DiscordSRV-Build-1.19.1-SNAPSHOT-1591040482.zip)
