### ISSUE TITLE
NullPointerException  EconomyManager

### ISSUE THREAD

**Issue by archroot** [Zrips/CMI#3429]
`https://paste.laravel.io/80c9caea-a698-4850-81c9-43b59d9ed841`

[09:38:50 INFO]: Версия плагина CMI: 8.6.26.7 SqLite
[09:38:50 INFO]: Server: Paper(333) 1.15.2-R0.1-SNAPSHOT
[09:38:50 INFO]: CMI economy: Да Vault: 1.7.3-b(CMIEInjector) CMI Chat: Да 
[09:38:50 INFO]: Modules -> 49 enabled 2 disabled: tablist, votifier

**Comment by CloudeLecaw** [comment]
please post a little error liek that as code next time :)
i postet it for you

[02:04:27 INFO]: none lost connection: Disconnected
[02:04:27 INFO]: none left the game
```
[02:04:27 WARN]: java.lang.NullPointerException
[02:04:27 WARN]: 	at com.Zrips.CMI.Modules.Economy.EconomyManager.moneyLog(EconomyManager.java:804)
[02:04:27 WARN]: 	at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount$1.run(CMIEconomyAcount.java:76)
[02:04:27 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[02:04:27 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[02:04:27 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:04:27 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[02:04:27 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[02:04:27 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[07:14:32 INFO]: [Vault] Checking for Updates ... 
[07:14:33 INFO]: [LibsDisguises] Now looking for update on Github..
[07:14:33 INFO]: [Vault] Stable Version: 1.7.2 | Current Version: 1.7.3
```

**Comment by CloudeLecaw** [comment]
Your runging Vault 1.7.2 + CMI Injector    or the Modified 1.7.3 from CMI Wiki?
https://www.zrips.net/cmi/

**Comment by archroot** [comment]
> Your runging Vault 1.7.2 + CMI Injector or the Modified 1.7.3 from CMI Wiki?
> https://www.zrips.net/cmi/

Yes

**Comment by Zrips** [comment]
Will be fixed, but ion general you can ignore this error, will not interfere with plugins works.
