### ISSUE TITLE
Portal particle edits are broken

### ISSUE THREAD

**Issue by AppleMacOS** [Zrips/CMI#3436]
**Description of issue:**
Whenever you try to change the particle settings for portals the entire portal just breaks and you have to go into the portals.yml file to remove it.

---

**ERROR:**
```
02.06 17:29:06 [Server] WARN [CMI] Task #14074 for CMI v8.6.26.7 generated an exception
02.06 17:29:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.6.26.7
02.06 17:29:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:357) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at com.Zrips.CMI.utils.Util.performCommand(Util.java:700) ~[?:?]
02.06 17:29:06 [Server] INFO at com.Zrips.CMI.Modules.GUI.GUIManager$1.run(GUIManager.java:153) ~[?:?]
02.06 17:29:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
02.06 17:29:06 [Server] INFO Caused by: java.lang.NullPointerException
02.06 17:29:06 [Server] INFO at com.Zrips.CMI.Modules.GUI.CMIGuiButton.<init>(CMIGuiButton.java:95) ~[?:?]
02.06 17:29:06 [Server] INFO at com.Zrips.CMI.Modules.GUI.CMIGuiButton.<init>(CMIGuiButton.java:87) ~[?:?]
02.06 17:29:06 [Server] INFO at com.Zrips.CMI.commands.list.portals.perform(portals.java:229) ~[?:?]
02.06 17:29:06 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:319) ~[?:?]
02.06 17:29:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
02.06 17:29:06 [Server] INFO ... 12 more
```
---

**Cmi Version: 8.6.26.8** 

**Server Type: Paper** 

**Server Version: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

**Comment by Zrips** [comment]
Should be fixed with next update.
