### ISSUE TITLE
Concurrent modification exception

### ISSUE THREAD

**Issue by FaMa91** [Zrips/CMI#3462]
**Description of issue:**
This error appear in console sometime

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
`[22:12:16] [Craft Scheduler Thread - 15014/WARN]: [CMI] Plugin CMI v8.6.26.7 generated an exception while executing task 39076763
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
    at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
    at com.Zrips.CMI.Modules.Holograms.CMIHologram$4.run(CMIHologram.java:1270) ~[?:?]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-284]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-284]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-284]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:112￼ [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:62￼ [?:?]
    at java.lang.Thread.run(Thread.java:834) [?:?]
    
    [22:13￼1] [Craft Scheduler Thread - 15018/WARN]: [CMI] Plugin CMI v8.6.26.7 generated an exception while executing task 39079051
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
    at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
    at com.Zrips.CMI.Modules.Holograms.CMIHologram$4.run(CMIHologram.java:1270) ~[?:?]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-284]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-284]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-284]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:112￼ [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:62￼ [?:?]
    at java.lang.Thread.run(Thread.java:834) [?:?]
[22:13￼1] [Craft Scheduler Thread - 15019/WARN]: [CMI] Plugin CMI v8.6.26.7 generated an exception while executing task 39079254
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
    at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
    at com.Zrips.CMI.Modules.Holograms.CMIHologram$4.run(CMIHologram.java:1270) ~[?:?]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-284]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-284]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-284]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:112￼ [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:62￼ [?:?]
    at java.lang.Thread.run(Thread.java:834) [?:?]`
######################
```
**Cmi Version (using`/cmi version`):** 2.6.26.7

**Server Type (Spigot/Paperspigot/etc):** paper(284)

**Server Version (using `/ver`):** 1.15.2

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be fixed with next build
