### ISSUE TITLE
Could not pass event PlayerInteractEvent to CMI v8.6.27.0

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#3503]
**Description of issue:**
Spam in Console
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:35:18 ERROR]: Could not pass event PlayerInteractEvent to CMI v8.6.27.0
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:8d2a711]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:8d2a711]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:8d2a711]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:263) [CraftEventFactory.class:8d2a711]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:479) [or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1139) [pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:864) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:736) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.Selection.SelectionListener.onSelection(SelectionListener.java:38) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor641.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:8d2a711]
        ... 16 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 8.6.27.0

**Server Type (Spigot/Paperspigot/etc):**  Catserver

**Server Version (using `/ver`):** 1.12.2

**Comment by blakedj012** [comment]
and CMI dont work anymore after this error

**Comment by CloudeLecaw** [comment]
what the hell is a CatServer, does not sound like a supported fork...

**Comment by blakedj012** [comment]
https://github.com/Luohuayu/CatServer/blob/1.12.2/README_EN.md

**Comment by blakedj012** [comment]
With Version rotocolLib 4.5.1 is the same.

**Comment by CloudeLecaw** [comment]
I see, but i dont know if zrips wanne start now looking into all kind of forks, but maybe its a cmi internal one. Well we will see

**Comment by Zrips** [comment]
@blakedj012 
From your error log it looks like you have set selection tool to some moded one which was not recognized properly by CMI and created this error. Change it to vanilla item, like a stick or something. This should resolve your issue.
