### ISSUE TITLE
Teleporting while riding a boat causes ClassCastException

### ISSUE THREAD

**Issue by xRebellion** [Zrips/CMI#3507]
**Description of issue:**
The issue is as stated above. Both adding and removing the permission cmi.teleportwith.* does not make any difference. Also, /ride and then teleporting while having the permission cmi.teleportwith.* does not teleport the ridden entity. (for example, cat)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[16:04:52] [Server thread/WARN]: java.lang.ClassCastException: Cannot cast net.minecraft.server.v1_15_R1.EntityBoat to net.minecraft.server.v1_15_R1.EntityLiving
[16:04:52] [Server thread/WARN]: 	at java.base/java.lang.Class.cast(Class.java:3605)
[16:04:52] [Server thread/WARN]: 	at com.Zrips.CMI.Reflections.spawnInEntityData(Reflections.java:1616)
[16:04:52] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners$4$1.run(PlayerListeners.java:839)
[16:04:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[16:04:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:04:52] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[16:04:52] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[16:04:52] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[16:04:52] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[16:04:52] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

![image](https://user-images.githubusercontent.com/32483348/84639620-d2e20c80-af22-11ea-808c-de46a32b44de.png)

**Comment by Zrips** [comment]
Will be fixed with next version
