### ISSUE TITLE
[CMI] Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#3513]
**Description of issue:**

[19:55:50] [Server thread/ERROR]: [CMI] Unhandled exception occured in onPacketSending(PacketEvent) for CMI
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.Zrips.CMI.AllListeners.ProtocolEvent$1.onPacketSending(ProtocolEvent.java:71) ~[CMI8.6.27.0.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198) [gw.class:?]
at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149) [gw.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336) [pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214) [NetworkDispatcher$1.class:git-CatServer-1.12.2-8cf55c8]
at net.minecraft.server.management.PlayerList.func_148537_a(PlayerList.java:1348) [pl.class:?]
at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:1496) [oo.class:?]
at net.minecraft.world.World.func_72835_b(World.java:2869) [amu.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:289) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[19:55:50] [Server thread/ERROR]: Parameters:
net.minecraft.network.play.server.SPacketChangeGameState@6e07705c[
field_149140_b=8
field_149141_c=0.19000003
]

[19:55:51] [Server thread/ERROR]: [CMI] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for CMI
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.Zrips.CMI.AllListeners.ProtocolEvent$1.onPacketSending(ProtocolEvent.java:71) ~[CMI8.6.27.0.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198) [gw.class:?]
at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149) [gw.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336) [pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214) [NetworkDispatcher$1.class:git-CatServer-1.12.2-8cf55c8]
at net.minecraft.server.management.PlayerList.func_148537_a(PlayerList.java:1348) [pl.class:?]
at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:1496) [oo.class:?]
at net.minecraft.world.World.func_72835_b(World.java:2869) [amu.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:289) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[19:55:53] [Server thread/ERROR]: [CMI] Unhandled exception number 64 occured in onPacketSending(PacketEvent) for CMI
com.comphenix.protocol.reflect.FieldAccessException: Field index out of bounds. (Index: 1, Size: 1)
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:220) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.Zrips.CMI.AllListeners.ProtocolEvent$1.onPacketSending(ProtocolEvent.java:71) ~[CMI8.6.27.0.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:334) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:296) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.6.0-SNAPSHOT-b460]
at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:198) [gw.class:?]
at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:149) [gw.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1336) [pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(NetworkDispatcher.java:214) [NetworkDispatcher$1.class:git-CatServer-1.12.2-8cf55c8]
at net.minecraft.server.management.PlayerList.func_148537_a(PlayerList.java:1348) [pl.class:?]
at net.minecraft.world.WorldServer.func_72979_l(WorldServer.java:1496) [oo.class:?]
at net.minecraft.world.World.func_72835_b(World.java:2869) [amu.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:289) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:892) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:775) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:629) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Cmi Version (using`/cmi version`):**  8.6.27.0

**Server Version (using `/ver`):** catserver 1.12.2
ProtocolLib.jar:4.6.0-SNAPSHOT-b460

**Comment by Zrips** [comment]
Should be fixed with next update
