### ISSUE TITLE
Upgrade to [8.6.27.1] gives Static getHandlerList method required exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3514]
**Description of issue:**

Upgrading from 27.0 to 27.1 gives the following error during start of the server.
It seems to be related to the flightcharge module.

```
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event com.Zrips.CMI.events.CMIBossBarHideEvent. Static getHandlerList method required!

java.lang.NoSuchMethodException: com.Zrips.CMI.Modules.FlightCharge.FlightListener.<init>()
```

https://pastebin.com/h7jRUFjY
<img width="588" alt="Screenshot 2020-06-16 at 15 41 01" src="https://user-images.githubusercontent.com/28841349/84781972-c8d61180-afe7-11ea-9b60-06653f528e05.png">

**Comment by Blueeyestar** [comment]
I can confirm. I have that problem too


[16:54:31] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event com.Zrips.CMI.events.CMIBossBarHideEvent. Static getHandlerList method required!
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:703)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:640)
[16:54:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.ModuleHandling.CMIModule.registerListener(CMIModule.java:179)
[16:54:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.ModuleHandling.CMIModuleManager.registerListeners(CMIModuleManager.java:62)
[16:54:31] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1347)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[16:54:31] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[16:54:31] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[16:54:31] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:54:31] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:54:31] [Server thread/WARN]: java.lang.NoSuchMethodException: com.Zrips.CMI.Modules.FlightCharge.FlightListener.<init>()
[16:54:31] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[16:54:31] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Class.java:1825)
[16:54:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.ModuleHandling.CMIModule.registerListener(CMIModule.java:184)
[16:54:31] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.ModuleHandling.CMIModuleManager.registerListeners(CMIModuleManager.java:62)
[16:54:31] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1347)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
[16:54:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
[16:54:31] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488)
[16:54:31] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
[16:54:31] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:54:31] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by blakedj012** [comment]
yes me too

**Comment by Zrips** [comment]
Fixed
