### ISSUE TITLE
[1.16.1] Cannot run CMI on 1.16.1, requires initial dev build

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3548]
I hope this helps you get started on the first step to take cmi to 1.16.x :)

[CMI] Loading CMI v8.6.27.4 .. reporting : 
```
Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16_R1
```

Full error
```
[03:15:17] [Server thread/INFO]: Time elapsed: 1237 ms
[03:15:17] [Server thread/INFO]: [CMI] Enabling CMI v8.6.27.4
[03:15:18] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[03:15:18] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[03:15:18] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃
[03:15:18] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃
[03:15:18] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[03:15:18] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[03:15:18] [Server thread/INFO]: _______________________________________________________
[03:15:18] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16_R1
[03:15:18] [Server thread/INFO]: [CMI] Vault was found but economy engine is missing. Use one from list provided in https://dev.bukkit.org/bukkit-plugins/vault/
[03:15:18] [Server thread/INFO]:   Vault was found but not economy plugin, you will have limited economy support
[03:15:18] [Server thread/WARN]: java.lang.NullPointerException
[03:15:18] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1064)
[03:15:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[03:15:18] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1326)
[03:15:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[03:15:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[03:15:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[03:15:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488)
[03:15:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402)
[03:15:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436)
[03:15:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[03:15:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808)
[03:15:18] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[03:15:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[03:15:18] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[03:15:18] [Server thread/INFO]: Done (20.309s)! For help, type "help"
```

```
>ver
[03:17:19] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[03:17:19] [Server thread/INFO]: Checking version, please wait...
[03:17:20] [Thread-10/INFO]: You are running the latest version
>
```

**Comment by CloudeLecaw** [comment]
i can agree this

```
[07:56:26] [Server thread/INFO]: [CMI] Enabling CMI v8.6.27.4
[07:56:27] [Server thread/INFO]: ????? ?????? ????[m

[07:56:27] [Server thread/INFO]: ????? ? ?? ? ????[m

[07:56:27] [Server thread/INFO]: ?? ?? ??????  ?? [m

[07:56:27] [Server thread/INFO]: ?? ?? ??????  ?? [m

[07:56:27] [Server thread/INFO]: ????? ?????? ????[m

[07:56:27] [Server thread/INFO]: ????? ?????? ????[m

[07:56:27] [Server thread/INFO]: _______________________________________________________[m

[07:56:27] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16_R1

[07:56:28] [Server thread/INFO]:   [0;36;22m[0;37;22mVault [0;36;22mwas found - Enabling capabilities. Economy: [0;35;22mCMIEconomy[m

[07:56:28] [Server thread/WARN]: java.lang.NullPointerException

[07:56:28] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1064)

[07:56:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)

[07:56:28] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1326)

[07:56:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)

[07:56:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)

[07:56:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)

[07:56:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488)

[07:56:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402)

[07:56:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436)

[07:56:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)

[07:56:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808)

[07:56:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)

[07:56:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by mrfloris** [comment]
initial dev/test release of CMI for  1.16.1 fixed this, closing thread 

Get version 8.7.0.0 of CMI or newer
