### ISSUE TITLE
Mobfarm-Manager 1.16.1 Error

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3551]
Now the time has come. 1.16.1 has been released and gives all server owners happy sleepless nights. I hereby submit my modest contribution to it :)

Mfm-Version: 1.5.5.3
Spigot-Version: CraftBukkit version git-Spigot-758abbe-38de0b8 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

[05:35:59] [Server thread/ERROR]: Error occurred while enabling MobFarmManager v1.5.5.3 (Is it up to date?)
java.lang.NullPointerException: null
at com.MobFarmManager.Zrips.MFM.onDisable(MFM.java:66) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at com.MobFarmManager.Zrips.MFM.onEnable(MFM.java:90) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-758abbe-b136f84]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by mrfloris** [comment]
reported it here in the other repository for mfm https://github.com/Zrips/MobFarmManager/issues/1

**Comment by Zrips** [comment]
fixed
