### ISSUE TITLE
[Server thread/WARN]: java.lang.NullPointerException  1.16.1

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3552]
Now the time has come. 1.16.1 has been released and gives all server owners happy sleepless nights. I hereby submit my modest contribution to it :)

Spigot-Version: CraftBukkit version git-Spigot-758abbe-38de0b8 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

[05:44:59] [Server thread/INFO]: [CMI] Enabling CMI v8.6.27.4
[05:44:59] [Server thread/INFO]: ????? ?????? ????[m
[05:44:59] [Server thread/INFO]: ????? ? ?? ? ????[m
[05:44:59] [Server thread/INFO]: ?? ?? ??????  ?? [m
[05:44:59] [Server thread/INFO]: ?? ?? ??????  ?? [m
[05:44:59] [Server thread/INFO]: ????? ?????? ????[m
[05:44:59] [Server thread/INFO]: ????? ?????? ????[m
[05:44:59] [Server thread/INFO]: _______________________________________________________[m
[05:44:59] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16_R1
[05:44:59] [Server thread/INFO]:   [0;36;22m[0;37;22mVault [0;36;22mwas found - Enabling capabilities. Economy: [0;35;22mCMIEconomy[m
[05:44:59] [Server thread/WARN]: java.lang.NullPointerException
[05:44:59] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1064)
[05:44:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[05:44:59] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1326)
[05:44:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:44:59] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[05:44:59] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[05:44:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488)
[05:44:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402)
[05:44:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436)
[05:44:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[05:44:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808)
[05:44:59] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[05:44:59] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:44:59] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m15[0;36;22m) [0;37;22mportals [0;36;22minto memory. [0;33;22mTook [0;33;1m12[0;33;22mms[m
[05:44:59] [Server thread/INFO]:   [0;36;22mLoaded GeoLiteCity[m

**Comment by mrfloris** [comment]
Duplicate https://github.com/Zrips/CMI/issues/3548

**Comment by mrfloris** [comment]
Try CMI 8.7.0.0 for 1.16.1, initial dev/test release.
