### ISSUE TITLE
Cannot execute command 'cmi' in plugin CMI v8.6.27.4 - plugin is disabled.   1.16.1

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3554]
[06:27:27] [Server thread/INFO]: Blueeyestar issued server command: /spawn
[06:27:30] [Server thread/INFO]: Blueeyestar issued server command: /cmi
[06:27:30] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v8.6.27.4 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:747) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1702) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1545) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-758abbe-38de0b8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

**Comment by mrfloris** [comment]
Duplicate https://github.com/Zrips/CMI/issues/3553

**Comment by mrfloris** [comment]
Duplicate https://github.com/Zrips/CMI/issues/3548

**Comment by mrfloris** [comment]
Try CMI 8.7.0.0 for 1.16.1 (initial dev/test release)
