### ISSUE TITLE
tab-complete error msg every i use cmi enchant

### ISSUE THREAD

**Issue by notbike** [Zrips/CMI#3555]
Every time i use the command "/cmi enchant" two error messages pops up,  right after "/cmi enchant" every letter i type will result in the same 2 errors. I'm not sure what's going on.

---
Console Error:

[00:55:27] [Server thread/ERROR]: Exception when bennypryde attempted to tab complete cmi enchant
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/cmi enchant ' in plugin CMI v8.6.27.4
    at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.15.2.jar:git-Paper-264]
    at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.15.2.jar:git-Paper-264]
    at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.15.2.jar:git-Paper-264]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabCompleteCommand(CraftServer.java:1770) ~[patched_1.15.2.jar:git-Paper-264]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.tabComplete(CraftServer.java:1742) ~[patched_1.15.2.jar:git-Paper-264]
    at org.bukkit.craftbukkit.v1_15_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.15.2.jar:git-Paper-264]
    at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.15.2.jar:git-Paper-264]
    at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.15.2.jar:git-Paper-264]
    at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.PlayerConnection.lambda$a$3(PlayerConnection.java:577) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1047) ~[patched_1.15.2.jar:git-Paper-264]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-264]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    at java.lang.String.substring(Unknown Source) ~[?:1.8.0_251]
    at com.Zrips.CMI.utils.Util.firstToUpperCase(Util.java:448) ~[?:?]
    at com.Zrips.CMI.Modules.Enchants.CMIEnchantment.getName(CMIEnchantment.java:76) ~[?:?]
    at com.Zrips.CMI.TabComplete.get(TabComplete.java:539) ~[?:?]
    at com.Zrips.CMI.TabComplete.onTabComplete(TabComplete.java:72) ~[?:?]
    at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[patched_1.15.2.jar:git-Paper-264]
    ... 19 more

In-Game chat window error:

An internal error occurred while attempting to tab-complete this command

(I did not press tab to complete the command)

---

**Cmi Version (using`/cmi version`):** 
8.6.27.4

**Server Type (Spigot/Paperspigot/etc):** 
Papermc

**Server Version (using `/ver`):** 
ver 1.15.2

**Comment by Zrips** [comment]
Should be fixed with latest version.
