### ISSUE TITLE
condense fails in spigot 1.16.1

### ISSUE THREAD

**Issue by paul-palmer** [Zrips/CMI#3564]
/cmi condense always reports "An internal error occurred while attempting to perform this command" instead of performing the expected action.

I looked through my config files, but could find nothing that might need to be updated to 1.16 for this command.

---

An internal error occurred while attempting to perform this command
```
[12:03:48] [Server thread/INFO]: BornToCode issued server command: /cmi condense
[12:03:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:747) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1702) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1545) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.server.v1_16_R1.RecipeSmithing does not define or inherit an implementation of the resolved method abstract toBukkitRecipe()Lorg/bukkit/inventory/Recipe; of interface net.minecraft.server.v1_16_R1.IRecipe.
	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:31) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.inventory.RecipeIterator.next(RecipeIterator.java:1) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	at com.Zrips.CMI.commands.list.condense.getPossibleCondense(condense.java:116) ~[?:?]
	at com.Zrips.CMI.commands.list.condense.condenseStack(condense.java:75) ~[?:?]
	at com.Zrips.CMI.commands.list.condense.perform(condense.java:55) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-758abbe-2b00831]
	... 18 more
```

---
CMI version 8.7.0.0
Spigot 1.16.1

**Comment by mercurialmusic** [comment]
This is working normally for me in CMI 8.7.0.3 on the latest builds of Spigot 1.16.1. I realize this is also an old report, but your server is 56 CraftBukkit and 11 Spigot Version(s) behind. Updating (if you haven't already) will likely fix the issue. If so, please close the ticket.

**Comment by paul-palmer** [comment]
closing. It seems to be a Spigot issue (https://hub.spigotmc.org/jira/browse/SPIGOT-5802). I have switched to Paper for now and it seems to be working normally now.
