### ISSUE TITLE
TPS command error java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#3572]
**Description of issue:**
TPS command gives error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[22:21:49 INFO]: PlayerName123abc issued server command: /cmi tps
[22:21:49 WARN]: java.lang.reflect.InvocationTargetException
[22:21:49 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:21:49 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:21:49 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:21:49 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[22:21:49 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
[22:21:49 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:640)
[22:21:49 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:624)
[22:21:49 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:670)
[22:21:49 WARN]: at com.Zrips.CMI.commands.list.tps.perform(tps.java:87)
[22:21:49 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[22:21:49 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:21:49 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[22:21:49 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1905)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1713)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1186)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1179)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1155)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:998)
[22:21:49 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[22:21:49 WARN]: Caused by: com.google.gson.JsonParseException: Unexpected empty array of components
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:316)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:232)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:185)
[22:21:49 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[22:21:49 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:447)
[22:21:49 WARN]: ... 28 more
[22:21:49 INFO]: [CMI] Failed to show json message with packets, using command approach
[22:21:49 INFO]: Invalid chat component: Unexpected empty array of components
[22:21:49 INFO]: ...PlayerName123abc" ["",{"text":"","extra":[{"text":"TPS: "}]},{"text":"","extra":[{"text":""}]},{"text":"","extra":[{"text":"20.0"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"3 sec Max: 20.0 Min: 20.0"}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"20.0"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"10 sec Max: 20.0 Min: 20.0"}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"20.0"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"30 sec Max: 20.0 Min: 18.6"}]}}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"20.0"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"60 sec Max: 20.0 Min: 18.6"}]}}},{"text":"","extra":[ ]}]<--[HERE]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
Default config
Plain test server

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.0.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper 1.15.2 build 372

**Comment by x1p** [comment]
Same sort of error appears when performing `cmi info`
All relevant information is gone!
![Screenshot_20200628_142233](https://user-images.githubusercontent.com/28690790/85947484-47697200-b94b-11ea-82f2-9195d57f3cae.png)

This issue likely breaks much more cmi commands too

**Comment by Zrips** [comment]
Fixed with latest build
