### ISSUE TITLE
TPS doesn't show up, warning in console

### ISSUE THREAD

**Issue by thomaslft** [Zrips/CMI#3578]
When doing /tps it doesnt the values dont show up, it gives warning into the console instead. This only happened right after updating. So im assuming its a fault in the plugin.

The warning :

```
[WARNING] .... java.lang.reflect.InvocationTargetException

[WARNING] .... at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[WARNING] .... at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[WARNING] .... at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[WARNING] .... at java.lang.reflect.Method.invoke(Method.java:498)

[WARNING] .... at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)

[WARNING] .... at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:640)

[WARNING] .... at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:624)

[WARNING] .... at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:670)

[WARNING] .... at com.Zrips.CMI.commands.list.tps.perform(tps.java:87)

[WARNING] .... at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)

[WARNING] .... at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)

[WARNING] .... at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)

[WARNING] .... at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1905)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1713)

[WARNING] .... at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)

[WARNING] .... at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43)

[WARNING] .... at net.minecraft.server.v1_15_R1.PlayerConnectionUtils$$Lambda$5170.00000000CD081C10.run(Unknown Source)

[WARNING] .... at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1186)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1179)

[WARNING] .... at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1155)

[WARNING] .... at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:998)

[WARNING] .... at java.lang.Thread.run(Thread.java:813)

[WARNING] .... Caused by: com.google.gson.JsonParseException: Unexpected empty array of components

[WARNING] .... at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:316)

[WARNING] .... at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:232)

[WARNING] .... at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:185)

[WARNING] .... at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)

[WARNING] .... at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)

[WARNING] .... at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)

[WARNING] .... at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:447)

[WARNING] .... ... 29 more
```

Using version 8.7.0.1

We run on HumHum, a fork from PurPur

1.15.2

**Comment by Blueeyestar** [comment]
I also have the problem

**Comment by Miner28** [comment]
Very similar problem on 1.16.1 both spigot and paper

**Comment by Zrips** [comment]
Fixed
