### ISSUE TITLE
Validate Enchantments Error

### ISSUE THREAD

**Issue by Xuwznln** [Zrips/CMI#3582]
Console sometimes continuously output this error log.
I can also confirm that I saw this error on 1.15.2 before.
---

`[18:59:49] [Server thread/WARN]: java.lang.IllegalArgumentException: Enchantment cannot be null
[18:59:49] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaItem.addEnchant(CraftMetaItem.java:821)
[18:59:49] [Server thread/WARN]: 	at com.Zrips.Recount.PlayerListener.onPlayerMakeDamage(PlayerListener.java:371)
[18:59:49] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor675.invoke(Unknown Source)
[18:59:49] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:59:49] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:241)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:943)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:830)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:786)
[18:59:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:975)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity0(EntityLiving.java:1755)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityLiving.damageEntity(EntityLiving.java:1138)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityGhast.damageEntity(EntityGhast.java:48)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityArrow.a(EntityArrow.java:320)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IProjectile.a(IProjectile.java:113)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityArrow.tick(EntityArrow.java:164)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:659)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.World.a(World.java:753)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:394)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1106)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848)
[18:59:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[18:59:49] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

CMI 8.7.0.1

Spigot 1.16.1   git-Spigot-6f4ff1b-d424351

**Comment by Zrips** [comment]
This one originates from Recount plugin. Will make some adjustment to avoid this error from appearing in future updates
