### ISSUE TITLE
CustomAlias error in consol: [20:26:05 ERROR]: [WorldEdit]

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#359]
CustomAlias
```
   info:
   - cmi info $1

```

write in console: info _ 
and tap TAB
have error in consol:

write in console: cmi info _
have no error
```
[20:26:05 ERROR]: [WorldEdit] Could not dispatch event: com.sk89q.worldedit.event.platform.CommandSuggestionEvent@38e94e5d to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-bukkit-6.1.7.3.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:187) [worldedit-bukkit-6.1.7.3.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:173) [worldedit-bukkit-6.1.7.3.jar:?]
        at com.sk89q.worldedit.bukkit.WorldEditPlugin.onTabComplete(WorldEditPlugin.java:261) [worldedit-bukkit-6.1.7.3.jar:?]
        at com.sk89q.bukkit.util.DynamicPluginCommand.tabComplete(DynamicPluginCommand.java:84) [worldedit-bukkit-6.1.7.3.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:90) [patched_1.12.2.jar:git-Paper-1413]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:229) [patched_1.12.2.jar:git-Paper-1413]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:181) [patched_1.12.2.jar:git-Paper-1413]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:68) [patched_1.12.2.jar:git-Paper-1413]
        at org.bukkit.craftbukkit.v1_12_R1.command.ConsoleCommandCompleter$2.evaluate(ConsoleCommandCompleter.java:65) [patched_1.12.2.jar:git-Paper-1413]
        at org.bukkit.craftbukkit.v1_12_R1.util.Waitable.run(Waitable.java:24) [patched_1.12.2.jar:git-Paper-1413]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:854) [patched_1.12.2.jar:git-Paper-1413]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1413]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1413]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1413]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.7.3.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.7.3.jar:?]
        ... 15 more
Caused by: java.lang.RuntimeException: Invalid suggestion context
        at com.sk89q.worldedit.util.command.parametric.ParametricCallable.getSuggestions(ParametricCallable.java:367) ~[FastAsyncWorldEdit-bukkit-18.05.02-89bd2c0-1105-19.7.10.jar:?]
        at com.sk89q.worldedit.util.command.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:166) ~[FastAsyncWorldEdit-bukkit-18.05.02-89bd2c0-1105-19.7.10.jar:?]
        at com.sk89q.worldedit.extension.platform.CommandManager.handleCommandSuggestion(CommandManager.java:483) ~[FastAsyncWorldEdit-bukkit-18.05.02-89bd2c0-1105-19.7.10.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-bukkit-6.1.7.3.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-bukkit-6.1.7.3.jar:?]
        ... 15 more
```

**Comment by valenvaio** [comment]
after disabling fawe, the error is gone.
