### ISSUE TITLE
editctext completely broken

### ISSUE THREAD

**Issue by kristouffe** [Zrips/CMI#3594]
**Description of issue:**
/editctext seems to be broken, unable to  edit custom texts in game.
Auto pagination seems to be broken aswell. Even if it's enabled, it wont auto paginate.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:35:02 INFO]: Kristouffe issued server command: /cmi editctext test
[14:35:02 WARN]: java.lang.reflect.InvocationTargetException
[14:35:02 WARN]:        at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[14:35:02 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:35:02 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:35:02 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
[14:35:02 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:689)
[14:35:02 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:673)
[14:35:02 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:719)
[14:35:02 WARN]:        at com.Zrips.CMI.Modules.CustomText.CTextManager.showCTextEditor(CTextManager.java:308)
[14:35:02 WARN]:        at com.Zrips.CMI.commands.list.editctext.perform(editctext.java:209)
[14:35:02 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[14:35:02 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:35:02 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:35:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[14:35:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:35:02 WARN]: Caused by: com.google.gson.JsonParseException: Unexpected empty array of components
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:229)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:148)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101)
[14:35:02 WARN]:        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:517)
[14:35:02 WARN]:        at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:358)
[14:35:02 WARN]:        ... 29 more
[14:35:02 INFO]: [CMI] Failed to show json message with packets, using command approach
[14:35:02 INFO]: Invalid chat component: Unexpected empty array of components
[14:35:02 INFO]: ...istouffe" ["",{"text":"","extra":[{"text":"[+]"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Page automatique: Vrai"}]}},"clickEvent":{"action":"run_command","value":"/cmi editctext test autopage false"}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"[+]"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Alias automatique: Vrai"}]}},"clickEvent":{"action":"run_command","value":"/cmi editctext test autoalias false"}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"[-]"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Permission requise: Faux\ncmi.command.ctext.test"}]}},"clickEvent":{"action":"run_command","value":"/cmi editctext test permreg true"}},{"text":"","extra":[ ]},{"text":"","extra":[{"text":"<NouvelleLigne>"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Ajouter une nouvelle ligne"}]}},"clickEvent":{"action":"run_command","value":"/cmi editctext test 1 add 0"}},{"text":"","extra":[{"text":" "}]},{"text":"","extra":[{"text":"<NouvellePage>"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Créer une nouvelle page"}]}},"clickEvent":{"action":"run_command","value":"/cmi editctext test 1 newpage"}},{"text":"","extra":[{"text":" "}]},{"text":"","extra":[{"text":"<RetirerUnePage>"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Retirer une page"}]}},"clickEvent":{"action":"run_command","value":"/cmi editctext test 1 removepage"}}]<--[HERE]
```

**Cmi Version (using`/cmi version`):** 
[14:37:55 INFO]: --------------------------------------------------
[14:37:55 INFO]: CMI: 8.7.0.2 SqLite
[14:37:55 INFO]: Server: Paper(3) 1.16.1-R0.1-SNAPSHOT
[14:37:55 INFO]: CMI economy: Vrai Vault: 1.7.3-b CMI Chat: Vrai
[14:37:55 INFO]: Modules -> 47 enabled 4 disabled: coloredArmor, votifier, holograms, dynamicSigns
[14:37:55 INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
paper 1.16.1
**Server Version (using `/ver`):** 
[08:39:47 INFO]: This server is running Paper version git-Paper-19 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[08:39:47 INFO]: Checking version, please wait...
[08:39:47 INFO]: Previous version: git-Paper-10 (MC: 1.16.1)
[08:39:47 INFO]: You are running the latest version
**Relevant plugins (Delete if this isn't needed):**
only cmi atm

**Comment by Zrips** [comment]
Will be fixed with next update
