### ISSUE TITLE
Error with TileEntityBeehive 

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3605]
Version: CMI8.7.0.2
Server:  Paper 1.16.1 Build24

```
[18:22:57] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R1.TileEntityBeehive.j()
[18:22:57] [Server thread/WARN]: 	at java.lang.Class.getMethod(Class.java:1786)
[18:22:57] [Server thread/WARN]: 	at com.Zrips.CMI.Reflections.getBeesInside(Reflections.java:786)
[18:22:57] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners.onInteractBeeHive(PlayerListeners.java:460)
[18:22:57] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1079.execute(Unknown Source)
[18:22:57] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:22:57] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:22:57] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:22:57] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[18:22:57] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:482)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1449)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[18:22:57] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[18:22:57] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

We see no reason for this. but its returning randomly.
Could it be that htis happens when CMI is looking for Bees inside a stock?
......Reflections.getBeesInside

This Error happpen if your checking a beestock or beenest for the bees it contains

**Comment by Zrips** [comment]
Will be fixed with next version
