### ISSUE TITLE
Unsent messages when using links

### ISSUE THREAD

**Issue by KieranGateley** [Zrips/CMI#3607]
Messages are not being sent if there is a link, followed by text. The specific message attempted to be sent was: `https://ucdn.fluxinc.xyz/sh-pack.zip mistyped the link`

---

**ERROR:**
```
java.lang.reflect.InvocationTargetException
 	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:498)
 	at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:689)
 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:673)
 	at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:135)
 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
 	at java.lang.Thread.run(Thread.java:748)
 Caused by: com.google.gson.JsonParseException: Unexpected empty array of components
 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:229)
 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:148)
 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.deserialize(IChatBaseComponent.java:101)
 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
 	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493)
 	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:517)
 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:358)
 	... 15 more
```
---
CMI: 8.7.0.2 SqLite
Server: Paper(21) 1.16.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Should work with latest build
