### ISSUE TITLE
ArrayIndexOutOfBounds when RGB color code is at the end of a nickname when private messaging

### ISSUE THREAD

**Issue by KieranGateley** [Zrips/CMI#3609]
Players are unable to send private messages if the final part of a nickname is using an RGB color. Nickname was set using `/nick {#55cdfc}C{#f7a8b8}el{#ffffff}e{#f7a8b8}st{#55cdfc}e{#ffffff}`, as a way to get around another bug I reported. 

---

**ERROR:**
```
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.0.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-21]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-21]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-21]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.Zrips.CMI.Modules.RawMessages.RawMessage.intoJsonColored(RawMessage.java:159) ~[?:?]
	at com.Zrips.CMI.Modules.RawMessages.RawMessage.add(RawMessage.java:431) ~[?:?]
	at com.Zrips.CMI.Modules.RawMessages.RawMessage.add(RawMessage.java:414) ~[?:?]
	at com.Zrips.CMI.Modules.RawMessages.RawMessage.add(RawMessage.java:70) ~[?:?]
	at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:310) ~[?:?]
	at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:233) ~[?:?]
	at com.Zrips.CMI.commands.list.msg.perform(msg.java:127) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-21]
	... 18 more
```
---

CMI: 8.7.0.2 SqLite
Server: Paper(21) 1.16.1-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will be fixed with next build
