### ISSUE TITLE
Teleportation fails & throws error when specific items are in your inventory

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#3612]
**Description of issue:**
When attempting to teleport with certain items in inventory, the teleportation will fail (warmup finishes and nothing happens) and throw an error in console. This issue does not happen while OP.

One item that I know causes this issue is this shield:
![image](https://user-images.githubusercontent.com/56176412/86075407-4d03ac80-ba5e-11ea-9bfb-668b948d8c46.png)

I also have Item blacklist enabled for the Dragon Egg if it matters.
```
    BlackListedItems:
      # Option to prevent player teleportation when he has blacklisted items in his inventory. Can be bypassed with cmi.teleport.bypassblacklist
      Enabled: true
      EnabledFor:
        tp: true
        tpa: true
        tpahere: true
        warp: true
        home: true
        spawn: true
      # Item and amount (if not defined, defaults to 0) we want to protect
      # Separate amount with : in example IronOre:5 what will limit ironOre block in players inventory up to 5, more than that and player cant teleport
      List:
      - DragonEgg
```
---

**ERROR:**
```
[02:03:03] [Server thread/INFO]: DragonEye issued server command: /home
[02:03:06] [Server thread/WARN]: [CMI] Task #268895 for CMI v8.7.0.3 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.0.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-26]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792) ~[patched_1.16.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:464) ~[patched_1.16.1.jar:git-Paper-26]
	at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.performCmd(WarmUpManager.java:268) ~[?:?]
	at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager.access$0(WarmUpManager.java:263) ~[?:?]
	at com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager$1.run(WarmUpManager.java:300) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-26]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-26]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-26]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-26]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-26]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-26]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_16_R1.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:301) ~[patched_1.16.1.jar:git-Paper-26]
	at com.Zrips.CMI.NBT.v1_16_R1.getShulkerInv(v1_16_R1.java:804) ~[?:?]
	at com.Zrips.CMI.utils.Util.getAllItemsFromInv(Util.java:1282) ~[?:?]
	at com.Zrips.CMI.utils.Util.getBlackListedItems(Util.java:1268) ~[?:?]
	at com.Zrips.CMI.utils.Util.haveBlackListedItems(Util.java:1229) ~[?:?]
	at com.Zrips.CMI.commands.list.home.perform(home.java:92) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-26]
	... 14 more
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/56176412/86075522-8fc58480-ba5e-11ea-988d-d49a7201cd31.png)

**Comment by Zrips** [comment]
Can't reproduce issue, but i can prevent error message from appearing again. It looks more like a minecraft issue itself where you have incorrectly created item stack in your inventory. Anyways, should be working with next build.
