### ISSUE TITLE
Playtime rewards not working, throwing error that spams console and occasionally crashes server

### ISSUE THREAD

**Issue by asterism-s** [Zrips/CMI#3614]
We updated to 1.16.1 today - our playtime rewards have been throwing this error every time a player received one - it crashed the server multiple times. We've disabled them temporarily but it would be nice if we could put them back in :) I've put an example of one of our playtime rewards in the config section, but they worked perfectly in 1.15.2 so i don't think they're the issue?

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>.... [05:11:55 WARN]: [CMI] Task #739593 for CMI v8.7.0.3 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.0.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-24]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:792) ~[patched_1.16.1.jar:git-Paper-24]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:738) ~[patched_1.16.1.jar:git-Paper-24]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:759) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:721) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:144) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:108) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeReward.performCommands(PlayTimeReward.java:60) ~[?:?]
at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager$1$1$1.run(PlayTimeRewardsManager.java:162) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-24]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-24]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-24]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-24]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-24]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-24]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.StackOverflowError
at com.google.gson.internal.$Gson$Types.resolve($Gson$Types.java:378) ~[patched_1.16.1.jar:git-Paper-24]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
R1:
  DisplayName: "&230 Minute &aPlaytime"
  AutoClaim: true
  Description:
  - "&aGet a reward every &230 minutes &ayou play!"
  PayEvery: 1800
  Commands:
  - asConsole! cmi toast [playerName] -icon:EMERALD Thanks for playing on Wildrift Valley!
  - asConsole! cmi money give [playerName] 600
```

---

**Cmi Version (using`/cmi version`):**  8.7.0.3

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):**  Paper(24) 1.16.1-R0.1-SNAPSHOT

**Comment by mercurialmusic** [comment]
I'm not having this issue on regular Spigot at least, using CMI 8.7.0.3 and git-Spigot-0287a20-2fe6b4a (MC: 1.16.1). All of our schedulers working normally with similar setup.

That said, Zrips did already say that toast commands were not working, so that might be what's catching you out rather than the rewards. I suggest changing that reward command to something else (a PM?) and see if it still has issues.

**Comment by Zrips** [comment]
This was issue related to spigot not handling properly toast messages. Update spigot to latest version and update CMI to .6 version and this will work as usual.
