### ISSUE TITLE
Spawnmob error

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#362]
Description of issue or feature request:
Error using `/spawnmob zombie:villager`

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
ERROR 11/05/2018 17:29:34
17:29:34null
Console 11/05/2018 17:29:34
17:29:34org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v7.7.4.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1415]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1415]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472) ~[patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1415]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1415]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1415]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.UnsupportedOperationException: Not supported.
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftZombie.setVillagerProfession(CraftZombie.java:50) ~[patched_1.12.2.jar:git-Paper-1415]
at com.Zrips.CMI.commands.list.spawnmob.proccessMob(spawnmob.java:605) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.commands.list.spawnmob.perform(spawnmob.java:272) ~[CMI7.7.4.0.jar:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209) ~[CMI7.7.4.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1415]
... 15 more
```
Cmi Version (using`/cmi version`): 7.7.4.0
Server Type (Spigot/Paperspigot/etc): paperspigot
Server Version (using `/ver`): 1.12.2 paperspigot 1415

**Comment by Zrips** [comment]
Should be fixed with next  build
