### ISSUE TITLE
Bug with holograms

### ISSUE THREAD

**Issue by QuiquePineyro** [Zrips/CMI#3623]
**Description of issue:**
Im using the plugin ModelEngine, and for some reason when I get nearby a hologram ofCMI the console throws an error message 

---

**ERROR :**
```
[18:44:39 WARN]: java.lang.NullPointerException
[18:44:39 WARN]: at com.Zrips.CMI.Modules.Packets.PacketInjector.removePlayer(PacketInjector.java:73)
[18:44:39 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:733)
[18:44:39 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:715)
[18:44:39 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramManager.addNearHolo(HologramManager.java:748)
[18:44:39 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramManager.handleHoloUpdates(HologramManager.java:315)
[18:44:39 WARN]: at com.Zrips.CMI.Modules.Holograms.HologramListener.onPlayerMoveExtendedRnage(HologramListener.java:161)
[18:44:39 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor792.execute(Unknown Source)
[18:44:39 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:44:39 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:44:39 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:44:39 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1153)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1232)
[18:44:39 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[18:44:39 WARN]: at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 
8.7.0.5
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper(374) 1.15.2-R0.1-SNAPSHOT
**Relevant plugins (Delete if this isn't needed):**
ModelEngine (https://www.spigotmc.org/resources/conxeptworks-model-engine%E2%80%94ultimate-entity-model-manager-1-14-1-15-2.79477/)

**Comment by Zrips** [comment]
Should be fixed with next version
