### ISSUE TITLE
First Login - Parse Equation Error

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#3625]
My server restarts every night, but at the first player login (only the first one to join the server), there is an error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>.... [08:53:11 WARN]: com.Zrips.CMI.Equations.ParseError: Semantic Error, expected function or variable or constant or '('
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.U(Parser.java:377)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.F(Parser.java:329)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.T(Parser.java:319)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.H(Parser.java:301)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.G(Parser.java:287)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.E(Parser.java:273)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.S(Parser.java:258)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getTree(Parser.java:109)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getValue(Parser.java:437)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1111)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:630)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:534)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:58)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:303)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$8.get(PlaceholderManager.java:241)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:17)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager.onJoin(PlaceholderManager.java:276)
>.... [08:53:11 WARN]: at me.neznamy.tab.platforms.bukkit.Main$3.lambda$0(Main.java:159)
>.... [08:53:11 WARN]: at java.util.ArrayList.forEach(ArrayList.java:1257)
>.... [08:53:11 WARN]: at me.neznamy.tab.platforms.bukkit.Main$3.run(Main.java:159)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.cpu.CPUManager$2.run(CPUManager.java:56)
>.... [08:53:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>.... [08:53:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [08:53:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [08:53:11 WARN]: com.Zrips.CMI.Equations.ParseError: Semantic Error, expected function or variable or constant or '('
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.U(Parser.java:377)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.F(Parser.java:329)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.T(Parser.java:319)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.H(Parser.java:301)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.G(Parser.java:287)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.E(Parser.java:273)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.S(Parser.java:258)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getTree(Parser.java:109)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getValue(Parser.java:437)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1111)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:630)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:534)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:58)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:303)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$8.get(PlaceholderManager.java:241)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:17)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:141)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:91)
>.... [08:53:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>.... [08:53:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [08:53:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [08:53:11 WARN]: [FogusCore] Loaded class net.citizensnpcs.api.CitizensAPI from Citizens v2.0.27-SNAPSHOT (build 2024) which is not a depend, softdepend or loadbefore of this plugin.
>.... [08:53:11 INFO]: [+] WAXIIE
>.... [08:53:11 WARN]: com.Zrips.CMI.Equations.ParseError: Semantic Error, expected function or variable or constant or '('
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.U(Parser.java:377)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.F(Parser.java:329)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.T(Parser.java:319)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.H(Parser.java:301)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.G(Parser.java:287)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.E(Parser.java:273)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.S(Parser.java:258)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getTree(Parser.java:109)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getValue(Parser.java:437)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1111)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:630)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:534)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:58)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:303)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$8.get(PlaceholderManager.java:241)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:17)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:141)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:91)
>.... [08:53:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>.... [08:53:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [08:53:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [08:53:11 INFO]: WAXIIE[/149.202.205.11:56297] logged in with entity id 859 at ([world]-3468.3070635487047, 65.0, 2140.088848227605)
>.... [08:53:11 WARN]: com.Zrips.CMI.Equations.ParseError: Semantic Error, expected function or variable or constant or '('
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.U(Parser.java:377)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.F(Parser.java:329)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.T(Parser.java:319)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.H(Parser.java:301)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.G(Parser.java:287)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.E(Parser.java:273)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.S(Parser.java:258)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getTree(Parser.java:109)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getValue(Parser.java:437)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1111)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:630)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:534)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:58)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:303)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$8.get(PlaceholderManager.java:241)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:17)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:141)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:91)
>.... [08:53:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>.... [08:53:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [08:53:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [08:53:11 WARN]: com.Zrips.CMI.Equations.ParseError: Semantic Error, expected function or variable or constant or '('
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.U(Parser.java:377)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.F(Parser.java:329)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.T(Parser.java:319)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.H(Parser.java:301)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.G(Parser.java:287)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.E(Parser.java:273)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.S(Parser.java:258)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getTree(Parser.java:109)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getValue(Parser.java:437)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1111)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:630)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:534)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:58)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:303)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$8.get(PlaceholderManager.java:241)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:17)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:141)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:91)
>.... [08:53:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>.... [08:53:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [08:53:11 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [08:53:11 WARN]: com.Zrips.CMI.Equations.ParseError: Semantic Error, expected function or variable or constant or '('
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.U(Parser.java:377)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.F(Parser.java:329)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.T(Parser.java:319)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.H(Parser.java:301)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.G(Parser.java:287)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.E(Parser.java:273)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.S(Parser.java:258)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getTree(Parser.java:109)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Equations.Parser.getValue(Parser.java:437)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1111)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:630)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:534)
>.... [08:53:11 WARN]: at com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:58)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326)
>.... [08:53:11 WARN]: at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.PluginHooks.PlaceholderAPI_setPlaceholders(PluginHooks.java:303)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$8.get(PlaceholderManager.java:241)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.placeholders.PlayerPlaceholder.update(PlayerPlaceholder.java:17)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:141)
>.... [08:53:11 WARN]: at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:91)
>.... [08:53:11 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>.... [08:53:11 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>.... [08:53:11 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>.... [08:53:11 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
**The only place where I have an equation is the TAB menu (plugin TAB Premium, not the CMI module)**
```
header:
- '&a&lHERIDIA'
- '&7&oOuvrir le menu:'
- '&7/menu &8&l| &7/h &8&l| &7/heridia'
- ' '
- '&7En ligne: &a%cmi_equationint_{cmi_bungee_current_creatif}+{server_online}%'
- '&8Créatif: &2%cmi_bungee_current_creatif%'
- ''
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/50526337/86212730-e2935f00-bb78-11ea-9ed7-f794ee748973.png)

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC version 374 (latest)
**Server Version (using `/ver`):** 
1.15.2
**Relevant plugins (Delete if this isn't needed):**
TAB Premium https://www.mc-market.org/resources/14009/

**Comment by Zrips** [comment]
Its general issue when {cmi_bungee_current_creatif} failed to check only status at that moment and returned invalid (empty) field as amount which failed to be processed when calculating with it. Will fix it with next update to return 0 in case it cant really check how many online we have on target server
