### ISSUE TITLE
Failed save while saving DeathLocation field

### ISSUE THREAD

**Issue by Phoetrix** [Zrips/CMI#3638]
**Description of issue:**
Hi!
Since my last issue at https://github.com/Zrips/CMI/issues/3601 I don't get the severe error anymore but data are already not saved.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
03.07 08:35:30 [Server] INFO [CMI] Failed save while saving DeathLocation field (Location{world=null,x=-0.81,y=64.36,z=6.02,pitch=-48.77,yaw=186.98})
03.07 08:35:30 [Server] WARN java.lang.IllegalArgumentException: World unloaded
03.07 08:35:30 [Server] WARN at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
03.07 08:35:30 [Server] WARN at org.bukkit.Location.getWorld(Location.java:112)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.Containers.CMILocation.getWorld(CMILocation.java:86)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.PlayerManager.convertLocationToString(PlayerManager.java:1970)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1179)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1112)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:686)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:395)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:286)
03.07 08:35:30 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
03.07 08:35:30 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
03.07 08:35:30 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
03.07 08:35:30 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
03.07 08:35:30 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
03.07 08:35:30 [Server] WARN at java.lang.Thread.run(Thread.java:748)
03.07 08:35:30 [Server] WARN java.sql.SQLException: No value specified for parameter 4
03.07 08:35:30 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
03.07 08:35:30 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
03.07 08:35:30 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
03.07 08:35:30 [Server] WARN at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
03.07 08:35:30 [Server] WARN at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2265)
03.07 08:35:30 [Server] WARN at com.mysql.jdbc.PreparedStatement.addBatch(PreparedStatement.java:943)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:699)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:395)
03.07 08:35:30 [Server] WARN at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:286)
03.07 08:35:30 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
03.07 08:35:30 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
03.07 08:35:30 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
03.07 08:35:30 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
03.07 08:35:30 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
03.07 08:35:30 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.0.6 MySQL
Server: Paper(374) 1.15.2-R0.1-SNAPSHOT
CMI economy: True Vault: 1.7.3-b(CMIEInjector) CMI Chat: False
Modules -> 46 enabled 5 disabled: customMessages, firstJoinMessages, votifier, vanish, playerChatTag

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-374 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-350 (MC: 1.15.2)
You are 1 version(s) behind

**Comment by Zrips** [comment]
Will update this and it should be fixed with next update. Tho now i wonder whats going on in your situation in particular. Why do you have unloaded worlds with saved locations in them?

**Comment by Phoetrix** [comment]
Maybe you have a better solution for me but actually I use your schedule system to reset a world two times in one day:
`dragon_box_reset:
  Enabled: true
  PerformOn:
    '1':
      Hour: 6
      Minute: 59
    '2':
      Hour: 18
      Minute: 59
  Commands:
  - mv delete dragon_box
  - mvconfirm
  - delay! 60
  - mv clone dragon_box_reference dragon_box
  - playsoundall entity.ender_dragon.ambient
  - cmi broadcast Le dragon s'est éveillé dans la &c&lBoîte à dragon&e!
  - mv modify set difficulty HARD dragon_box
  - mv modify set alias dragon_box dragon_box`

When the reset happens, maybe your plugin believe that the world is unloaded but he is unloaded only for 60 seconds and the bug happens all the day.

**Comment by Phoetrix** [comment]
And thank you for solving the bug :)
