### ISSUE TITLE
Bug with not-showing groups in /list still here

### ISSUE THREAD

**Issue by MaxWainer** [Zrips/CMI#3653]
**Description of issue:**
When I use /list (Not only from console) plugin give error and now showing group-name which I need and which I named and added.
Proof:
```
> lp group default permission check cmi.command.list.group.default
[05:40:53 INFO]: [LP] default has permission cmi.command.list.group.default set to true in context global.
```
---

**ERROR:**
```
https://pastebin.com/ijc5yA17
```

**CONFIG SECTION (Locale_RU.yml):**
```
    info:
      # [groupLine] can be replaced with specific grouped names like [group1] and [group2] and so on, you can have as many of those as you want and order them by your own liking
      List:
      - '&f'
      - '&8>->->->-> &7Онлайн &c[amount] [hidden] &7из &c[maxamount] &8<-<-<-<-<'
      - '[staffLine]'
      - '[groupLine]'
      - '[adminLine]'
      - '[moder]'
      - '[yt]'
      - '[test]'
      - '[helper]'
      - '[phantom]'
      - '[avenger]'
      - '[phoenix]'
      - '[wither]'
      - '[legend]'
      - '[supreme]'
      - '[god]'
      - '[hero]'
      - '[default]'
      - '&f'
      staffL: '&8• &7Персонал: &f[list]'
      adminL: '&8• &7Администрация: &f[list]'
      hiddenPref: '&7&7[Скрыт] '
      hiddenCount: '&7&7([amount])'
      groupL: '&7[groupName]: &f[list]'
      player: '%cmi_user_afk_symbol%&f[playerDisplayName]'
      # Add as many groups as you wish, by default there is only 10, to create new one, just copy paste one line and add increment into lines name, like group11 or group12 and so on.
      # Player need to have appropriate permission node to be placed in group cmi.command.list.group.[groupnumber], bigger number have bigger priority
      groups:
        moder: '&8• &7Модераторы: &f[list]'
        yt: '&8• &7Ютуберы: &f[list]'
        test: '&8• &7Тестеры: &f[list]'
        helper: '&8• &7Хелпер: &f[list]'
        phantom: '&8• &4&lPHANTOM&7: &f[list]'
        avenger: '&8• &a&lAVANGER&7: &f[list]'
        phoenix: '&8• &6&lPHOENIX&7: &f[list]'
        wither: '&8• &e&lWITHER&7: &f[list]'
        legend: '&8• &b&lLEGEND&7: &f[list]'
        supreme: '&8• &5&lSUPREME&7: &f[list]'
        god: '&8• &c&lGOD&7: &f[list]'
        hero: '&8• &9&lHERO&7: &f[list]'
        default: '&8• &7Игроки: &f[list]'
      noGroupLine: '&7Список'
```

---

**Cmi Version (using`/cmi version`):** 
```
> cmi version
[05:38:24 INFO]: --------------------------------------------------
[05:38:24 INFO]: Версия плагина CMI: 8.7.0.9 BungeeCord  MySQL
[05:38:24 INFO]: Server: Paper(1618) 1.12.2-R0.1-SNAPSHOT
[05:38:24 INFO]: CMI economy: Нет Vault: 1.7.2-b107 CMI Chat: Нет
[05:38:24 INFO]: Modules -> 50 enabled 1 disabled: tablist
[05:38:24 INFO]: --------------------------------------------------
```
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
```
> ver
[05:32:48 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[05:32:48 INFO]: Checking version, please wait...
[05:32:48 INFO]: You are running the latest version
```

**Comment by MaxWainer** [comment]
```
> list
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: ""
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:592)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -3
[05:30:28 WARN]:        at java.lang.String.substring(String.java:1931)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[05:30:28 WARN]:        at java.lang.String.substring(String.java:1931)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "r"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "om"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "er"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "ix"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "r"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "d"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "me"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
[05:30:28 WARN]:        at java.lang.String.substring(String.java:1931)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[05:30:28 WARN]:        at java.lang.String.substring(String.java:1931)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[05:30:28 WARN]:        at java.lang.String.substring(String.java:1931)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 WARN]: java.lang.NumberFormatException: For input string: "lt"
[05:30:28 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[05:30:28 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[05:30:28 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[05:30:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:30:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[05:30:28 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[05:30:28 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[05:30:28 WARN]:        at java.lang.Thread.run(Thread.java:748)
[05:30:28 INFO]:
[05:30:28 INFO]: >->->->-> Онлайн 1  из 20 <-<-<-<-<
[05:30:28 INFO]: default: van2011
[05:30:28 INFO]:
```

**Comment by Zrips** [comment]
Like comment section just about group list says you need to use names as group1 group2 ... group10... group50 and so on. Using completely custom names will cause this error.
