### ISSUE TITLE
After the correct response, an error occurred in the console. TryMe v6.0.5.0

### ISSUE THREAD

**Issue by iLiDanMoon** [Zrips/CMI#3656]
[13:00:19] [Server thread/WARN]: [TryMe] Task #4447 for TryMe v6.0.4.4 generated an exception
java.lang.NoClassDefFoundError: com/Zrips/CMI/utils/VersionChecker$Version
	at me.Zrips.TryMe.Util$3.run(Util.java:238) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-68]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-68]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-68]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Zrips** [comment]
Will be fixed with next version, most likely with todays release
