### ISSUE TITLE
%cmi_random_<from>_<to>% not parsing correctly

### ISSUE THREAD

**Issue by xRebellion** [Zrips/CMI#3672]
**Description of issue:**
Hello, there seems to be a problem with the latest update - as it seems that the %cmi_random% placeholder is not parsing properyas it should be. It used to be fine on 8.7.0.6, but somewhere along the way after I updated to 8.7.0.10 this error below occurred.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Expected integer
[00:30:31 INFO]: ... @a speed %cmi_random_180_300% %cmi_random_0_3% true<--[HERE]
[00:30:31 WARN]: java.lang.NumberFormatException: For input string: "-%cmi_random_180_300%"
[00:30:31 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[00:30:31 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[00:30:31 WARN]:        at java.base/java.lang.Double.parseDouble(Double.java:543)
[00:30:31 WARN]:        at com.Zrips.CMI.commands.list.bossbarmsg.perform(bossbarmsg.java:215)
[00:30:31 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:323)
[00:30:31 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:30:31 WARN]:        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758)
[00:30:31 WARN]:        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:709)
[00:30:31 WARN]:        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:144)
[00:30:31 WARN]:        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:100)
[00:30:31 WARN]:        at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:62)
[00:30:31 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1063.execute(Unknown Source)
[00:30:31 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[00:30:31 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:30:31 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:30:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
```
Config:
(schedules.yml)
```
RandomGlobalEvent:
  Enabled: false
  MinPlayers: 1
  FeedBack: false
  Repeat: false
  Randomize: true
  Commands:
  - potionglobalevent haste %cmi_random_180_300% %cmi_random_0_2%
<truncated>
```
(customalias.yml)
```
potionglobalevent:
    Cmds:
    - perm:globalevent.admin! asConsole! effect give @a $1 $2 $3 true
    - perm:globalevent.admin! asConsole! cmi bossbarmsg all -sec:-$2 -t:0 -n:potioneventrunning
      -c:green &7-- Potion Effect &7([autoTimeLeft]&7) &7--
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

![image](https://user-images.githubusercontent.com/32483348/86822470-e01f9080-c0b5-11ea-90ab-e6180d537951.png)

**Comment by CloudeLecaw** [comment]
Placeholders from cmi schwdulers broke in last Version where they tried to optimize the scheduler.

**Comment by Zrips** [comment]
Yea, while previous bugfix fixed issue on one end, it did broke things like this. Will revert back to previous behavior to make it work as it was before and will try to find more universal solution after that.
This placeholder translation is quite complex thing to handle when we need to translate only some of them at one of the stages and then others, while code itself currently translates everything at once which removes some of the placeholders which are related to the player directly. Well, anyways, will be fixed with next version.
