### ISSUE TITLE
error and bug

### ISSUE THREAD

**Issue by arts7493** [Zrips/CMI#3692]
**Description of issue:**
1. if muted OP try send chat, console error
2. there are TEST and 1004 player in server and command /cmi exp give TEST 100
but 1004 player will get exp

sorry bad english
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:03:22] [Netty Server IO #2/ERROR]: java.lang.StackOverflowError
[12:03:22] [Netty Server IO #2/WARN]: java.lang.StackOverflowError
[12:03:22] [Netty Server IO #2/WARN]:     at java.io.StringWriter.write(StringWriter.java:101)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.stream.JsonWriter.string(JsonWriter.java:566)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.stream.JsonWriter.beginArray(JsonWriter.java:287)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:95)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.Gson$FutureTypeAdapter.write(Gson.java:976)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
[12:03:22] [Netty Server IO #2/WARN]:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
[04:35:50] [Server thread/INFO]: --------------------------------------------------
[04:35:50] [Server thread/INFO]: CMI: 8.7.0.11 SqLite
[04:35:50] [Server thread/INFO]: Server: Paper(378) 1.15.2-R0.1-SNAPSHOT
[04:35:50] [Server thread/INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False 
[04:35:50] [Server thread/INFO]: Modules -> 19 enabled 32 disabled: spawnerProximity, customMessages, mirror, tablist, versionCheck, skin, noTarget, elytraBoost, cmiPlaytime, eventCommands, elytraLaunch, bossBarCompass, coloredArmor, spawnerCharge, namePlates, timedCommands, hpBossBar, armorstand, afk, jail, spawners, paintingEditor, dynamicSigns, playerChatTag, kits, flightCharge, schedule, disabledEnchants, worldLimits, ranks, firstJoinMessages, sitAnimation
[04:35:50] [Server thread/INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
Paper version git-Paper-378 (MC: 1.15.2)

**Comment by Zrips** [comment]
Will fix exp issue. For error itself, there is not enough information in whats going on exactly. I need full report and if this is it what you have in your console, you will need to remove any plugin which could modify console chat messages and disable it to get full error message. Will close this ticket, you can open new one with that specific issue and full error log
