### ISSUE TITLE
Citizens Compatibility - World Teleportation

### ISSUE THREAD

**Issue by remusjones** [Zrips/CMI#3699]
**Description of issue:**

When using the latest citizens2 version, and having that NPC /follow someone who is traversing worlds there is an error thrown.
---
Latest change citizens made that may effect CMI: [Commit](https://github.com/CitizensDev/CitizensAPI/commit/6436dd5fb30d7d52df2bc819ea8b068783f56c4b)
---

**Link to Latest.log:** [Server Latest.log](https://pastebin.com/iHQNUhL8)

---

**ERROR:**
```
Isolated Error: 

[19:01:42 ERROR]: Could not pass event PlayerChangedWorldEvent to CMI v8.7.0.11
java.lang.NullPointerException: null
    at com.Zrips.CMI.AllListeners.WorldLimits.onWorldChangeFlyCached(WorldLimits.java:76) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor281.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-86]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-86]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-86]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-86]
    at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:869) ~[patched_1.16.1.jar:git-Paper-86]
    at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:813) ~[patched_1.16.1.jar:git-Paper-86]
    at org.bukkit.craftbukkit.v1_16_R1.entity.CraftEntity.teleport(CraftEntity.java:522) ~[patched_1.16.1.jar:git-Paper-86]
    at net.citizensnpcs.api.npc.AbstractNPC$3.run(AbstractNPC.java:417) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-86]
    at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-86]
    at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-86]
    at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-86]
    at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-86]
    at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-86]
    at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-86]
    at java.lang.Thread.run(Thread.java:832) [?:?]

```
---

**Cmi Version (using`/cmi version`): CMI: 8.7.0.7 MySQL -> 8.7.0.11** 

**Server Type (Spigot/Paperspigot/etc): Paper(86) 1.16.1-R0.1-SNAPSHOT** 

**Server Version (using `/ver`): minecraft server version 1.16.1** 

**Relevant plugins (Delete if this isn't needed): Citizens v2.0.27-SNAPSHOT (build 2053)**

**Comment by Zrips** [comment]
Will be fixed with next update
