### ISSUE TITLE
Sitting on slaps and steps doesnt work

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3705]
```
>.... [11:28:36 ERROR]: Could not pass event PlayerInteractEvent to CMI v8.7.1.1
java.lang.NoClassDefFoundError: com/Zrips/CMI/Containers/CMIBlock$StairShape
at com.Zrips.CMI.Containers.CMIBlock.getStairShape(CMIBlock.java:181) ~[?:?]
at com.Zrips.CMI.Modules.Animations.AnimationManager.getStairLedgeDirection(AnimationManager.java:530) ~[?:?]
at com.Zrips.CMI.Modules.Animations.AnimationManager.sit(AnimationManager.java:654) ~[?:?]
at com.Zrips.CMI.Modules.Animations.AnimationSitListener.PlayerTeleportEvent(AnimationSitListener.java:198) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor967.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-88]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-88]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-88]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-88]
at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-88]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-88]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by CloudeLecaw** [comment]
solved after restart
