### ISSUE TITLE
Error on /cmi info OFFLINEPLAYER

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#3717]
```
>.... [02:02:42 INFO]: Blueeyestar issued server command: /cmi info Mardelzur
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: java.lang.NullPointerException
>.... [02:02:42 WARN]: [CMI] Task #3673345 for CMI v8.7.1.1 generated an exception
java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:506) ~[?:?]
at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:484) ~[?:?]
at com.Zrips.CMI.Modules.Homes.HomeManager.getReSpawnLocation(HomeManager.java:297) ~[?:?]
at com.Zrips.CMI.commands.list.info$1.lambda$0(info.java:213) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-90]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-90]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
Happens to all players that are offline
![Snag_2bf6dc2](https://user-images.githubusercontent.com/12080017/87365371-54ef4080-c576-11ea-9d63-c49654286a2d.png)

**Comment by Zrips** [comment]
Should get fixed with next release
