### ISSUE TITLE
Server Crash When Player Go Through End Gateway While Riding a Pig

### ISSUE THREAD

**Issue by TheBlueKingLP** [Zrips/CMI#3721]
**Description of issue:**
When I go through an End Gateway while riding a pig, the server will just crash, this issue does NOT exist in vanilla or spigot without CMI

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at net.minecraft.server.v1_16_R1.Entity.lambda$9(Entity.java:2620)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
	at net.minecraft.server.v1_16_R1.Entity.enderTeleportTo(Entity.java:2614)
	at net.minecraft.server.v1_16_R1.Entity.enderTeleportAndLoad(Entity.java:2605)
	at net.minecraft.server.v1_16_R1.TileEntityEndGateway.a(TileEntityEndGateway.java:167)
	at net.minecraft.server.v1_16_R1.TileEntityEndGateway.tick(TileEntityEndGateway.java:67)
	at net.minecraft.server.v1_16_R1.World.tickBlockEntities(World.java:678)
	at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:418)
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1106)
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354)
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009)
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848)
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
	at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 
--------------------------------------------------
CMI: 8.7.1.1 SqLite
Server: Spigot 1.16.1-R0.1-SNAPSHOT
CMI economy: False CMI Chat: False
Modules -> 50 enabled 1 disabled: votifier
--------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
CraftBukkit version git-Spigot-05da6fa-b0c6dfe (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be investigating this issue as it looks to be more spigot issue as its glitching out quite badly even if you would disable CMI entirely and then teleport throw endgate while riding pig. You could update to paperspigot as that one prevents server crashes in situations like that and only throws out error.

**Comment by TheBlueKingLP** [comment]
This issue still haven't been fixed. PaperSpigot isn't an option for me, I have players with a Redstone machine that doesn't work on PaperSpigot.

**Comment by Zrips** [comment]
This is not CMI bug, you can reproduce same issue on Vanilla minecraft. We can only hope that Mojang fixed this on 1.16.2 version as it was reported to them about this one.

**Comment by TheBlueKingLP** [comment]
It didn't crash in spigot without CMI or in vanilla

**Comment by Zrips** [comment]
Well this could be related to player ride teleportation with him. For time being will try to exclude teleportations with rides when teleportation cause is UNKNOWN which seams to be the case with endgateways while other teleportations usually are defined, so it should have big impact.
