### ISSUE TITLE
HologramManager

### ISSUE THREAD

**Issue by Cuki1998** [Zrips/CMI#3736]
[00:18:19 INFO]: Cuki lost connection: Disconnected
[00:18:19 WARN]: java.util.NoSuchElementException: packet_handler
[00:18:19 WARN]:        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
[00:18:19 WARN]:        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
[00:18:19 WARN]:        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
[00:18:19 WARN]:        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66)
[00:18:19 WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:283)
[00:18:19 WARN]:        at com.Zrips.CMI.Modules.Packets.PacketInjector.addPlayer(PacketInjector.java:45)
[00:18:19 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.recheckInteractableHolograms(HologramManager.java:754)
[00:18:19 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:734)
[00:18:19 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.addNearHolo(HologramManager.java:767)
[00:18:19 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramManager.handleHoloUpdates(HologramManager.java:334)
[00:18:19 WARN]:        at com.Zrips.CMI.Modules.Holograms.HologramListener.onPlayerMoveExtendedRnage(HologramListener.java:188)
[00:18:19 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor133.execute(Unknown Source)
[00:18:19 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[00:18:19 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[00:18:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:18:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[00:18:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.teleport(CraftPlayer.java:781)
[00:18:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.entity.CraftEntity.teleport(CraftEntity.java:522)
[00:18:19 WARN]:        at plugin.cuki.borderserver.Listener.BorderModuleListener.onQuit(BorderModuleListener.java:63)
[00:18:19 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source)
[00:18:19 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[00:18:19 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[00:18:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:18:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.PlayerList.disconnect(PlayerList.java:509)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1590)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.NetworkManager.handleDisconnection(NetworkManager.java:481)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:162)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[00:18:19 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[00:18:19 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Zrips** [comment]
Should be fixed with next update
