### ISSUE TITLE
type "\" and server lag 1.16

### ISSUE THREAD

**Issue by ogoo2997** [Zrips/CMI#3757]
Just type "\" in chat and server get error message 

---

```
[19:07:28] [Server thread/INFO]: [CMI] Failed to show json message with packets, using command approach
[19:07:28] [Server thread/INFO]: Invalid chat component: Unterminated string at line 1 column 577 path $[2].extra[0].text
[19:07:28] [Server thread/INFO]: ...w "Oma_X" ["",{"text":"","extra":[{"color":"light_purple","text":"{洨妹} "},{"bold":true,"color":"red","text":"❤ "},{"color":"dark_gray","text":"▸"},{"color":"gray","text":"塔利波"},{"color":"dark_gray","text":"▸"},{"color":"green","text":"主世界"},{"color":"dark_gray","text":"▸ "},{"color":"white","text":"RRMC "},{"color":"gray","text":">"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"color":"yellow","text":"發送時間: "},{"color":"gold","text":"07:07:28"}]}},"clickEvent":{"action":"suggest_command","value":"\/msg Virgatum_OuO "}},{"text":"","extra":[{"text":"]34et\"}]}]<--[HERE]
[19:07:28] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:481)
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:463)
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:140)
[19:07:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:07:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[19:07:28] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 577 path $[2].extra[0].text
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:60)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:493)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.ChatDeserializer.a(SourceFile:517)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:359)
[19:07:28] [Server thread/WARN]: 	... 15 more
[19:07:28] [Server thread/WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 577 path $[2].extra[0].text
[19:07:28] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1017)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[19:07:28] [Server thread/WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:48)
[19:07:28] [Server thread/WARN]: 	... 19 more
[19:07:28] [Server thread/INFO]: [CMI] Failed to show json message with packets, using command approach
[19:07:28] [Server thread/INFO]: Invalid chat component: Unterminated string at line 1 column 577 path $[2].extra[0].text
[19:07:28] [Server thread/INFO]: ... "Cleffl" ["",{"text":"","extra":[{"color":"light_purple","text":"{洨妹} "},{"bold":true,"color":"red","text":"❤ "},{"color":"dark_gray","text":"▸"},{"color":"gray","text":"塔利波"},{"color":"dark_gray","text":"▸"},{"color":"green","text":"主世界"},{"color":"dark_gray","text":"▸ "},{"color":"white","text":"RRMC "},{"color":"gray","text":">"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"color":"yellow","text":"發送時間: "},{"color":"gold","text":"07:07:28"}]}},"clickEvent":{"action":"suggest_command","value":"\/msg Virgatum_OuO "}},{"text":"","extra":[{"text":"]34et\"}]}]<--[HERE]
[19:07:28] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:481)
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:463)
[19:07:28] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:140)
[19:07:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:07:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[19:07:28] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[19:07:28] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.Malformed
```

---

CMI8.7.2.5

paper 93

1.16.1

**Comment by variananora** [comment]
I think this problem also correlate with #3756

**Comment by Zrips** [comment]
Will get resolved with next update
