### ISSUE TITLE
[item] throws errors in console

### ISSUE THREAD

**Issue by Aevox01** [Zrips/CMI#3765]
**Description of issue:**

We're trying to do the [item] thing in chat and it throws the error shown below everytime.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[16:05:56 INFO]: <3 [Lvl. 0] [Head-Admin] Aevox » [item]
[16:05:56 WARN]: java.lang.reflect.InvocationTargetException
[16:05:56 WARN]: at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
[16:05:56 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:05:56 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:463)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:445)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:140)
[16:05:56 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[16:05:56 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[16:05:56 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:05:56 WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 15 column 262 path $[3].hoverEvent.value
[16:05:56 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:60)
[16:05:56 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:445)
[16:05:56 WARN]: ... 14 more
[16:05:56 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 15 column 262 path $[3].hoverEvent.value
[16:05:56 WARN]: at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[16:05:56 WARN]: at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[16:05:56 WARN]: at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[16:05:56 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:48)
[16:05:56 WARN]: ... 18 more
[16:05:56 INFO]: [CMI] Failed to show json message with packets, using command approach
[16:05:56 INFO]: Invalid chat component: Unterminated object at line 15 column 262 path $[3].hoverEvent.value
[16:05:56 INFO]: ...eem_2000" ["",{"text":"","extra":[{"bold":true,"color":"dark_red","text":"<3 "},{"color":"dark_gray","text":"["},{"color":"green","text":"Lvl. 0"},{"color":"dark_gray","text":"] "},{"color":"dark_gray","text":"["},{"color":"dark_red","text":"Head-Admin"},{"color":"dark_gray","text":"] "},{"color":"dark_red","text":"Aevox"},{"text":" "},{"color":"green","text":"» "}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"color":"dark_gray","text":"["},{"color":"dark_red","text":"Head-Admin"},{"color":"dark_gray","text":"] "},{"color":"gray","text":"Aevox
"},{"color":"gray","text":"Kills: "},{"color":"gold","text":"6
"},{"color":"gray","text":"Deaths: "},{"color":"gold","text":"5
"},{"color":"gray","text":"KDR: "},{"color":"gold","text":"1.2
"},{"color":"gray","text":"Total EXP: "},{"color":"gold","text":"13215
"},{"color":"gray","text":"Mobs Killed: "},{"color":"gold","text":"70
"},{"color":"gray","text":"Balance: "},{"color":"gold","text":"1,932,850.00$
"},{"color":"gray","text":"Blocks mined: "},{"color":"yellow","text":"325
"},{"color":"gray","text":"Blocks placed: "},{"color":"yellow","text":"287
"},{"color":"gray","text":"Island Level: "},{"color":"yellow","text":"0
"},{"color":"gray","text":"Playtime: "},{"color":"yellow","text":"5h 32m 32s
"},{"color":"gray","text":"Party: "},{"color":"yellow","text":"Oblivion
"},{"color":"gray","text":"Click to message"}]}},"clickEvent":{"action":"run_command","value":"/msg Aevox "}},{"text":""},{"text":"","extra":[{"color":"gray","text":"[Oak Wood x64"},{"color":"gray","text":"]"}],"hoverEvent":{"action":"show_item","value":"{id:"minecraft:oak_wood",Count:64b}"}}]<--[HERE]
[16:05:56 WARN]: java.lang.reflect.InvocationTargetException
[16:05:56 WARN]: at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
[16:05:56 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:05:56 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:463)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:445)
[16:05:56 WARN]: at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:140)
[16:05:56 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[16:05:56 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[16:05:56 WARN]: at java.lang.Thread.run(Thread.java:748)
[16:05:56 WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 15 column 262 path $[3].hoverEvent.value
[16:05:56 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:60)
[16:05:56 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[16:05:56 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:445)
[16:05:56 WARN]: ... 14 more
[16:05:56 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 15 column 262 path $[3].hoverEvent.value
[16:05:56 WARN]: at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[16:05:56 WARN]: at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[16:05:56 WARN]: at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[16:05:56 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[16:05:56 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:48)
[16:05:56 WARN]: ... 18 more
[16:05:56 INFO]: [CMI] Failed to show json message with packets, using command approach
[16:05:56 INFO]: Invalid chat component: Unterminated object at line 15 column 262 path $[3].hoverEvent.value
[16:05:56 INFO]: ...w "Aevox" ["",{"text":"","extra":[{"bold":true,"color":"dark_red","text":"<3 "},{"color":"dark_gray","text":"["},{"color":"green","text":"Lvl. 0"},{"color":"dark_gray","text":"] "},{"color":"dark_gray","text":"["},{"color":"dark_red","text":"Head-Admin"},{"color":"dark_gray","text":"] "},{"color":"dark_red","text":"Aevox"},{"text":" "},{"color":"green","text":"» "}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"color":"dark_gray","text":"["},{"color":"dark_red","text":"Head-Admin"},{"color":"dark_gray","text":"] "},{"color":"gray","text":"Aevox
"},{"color":"gray","text":"Kills: "},{"color":"gold","text":"6
"},{"color":"gray","text":"Deaths: "},{"color":"gold","text":"5
"},{"color":"gray","text":"KDR: "},{"color":"gold","text":"1.2
"},{"color":"gray","text":"Total EXP: "},{"color":"gold","text":"13215
"},{"color":"gray","text":"Mobs Killed: "},{"color":"gold","text":"70
"},{"color":"gray","text":"Balance: "},{"color":"gold","text":"1,932,850.00$
"},{"color":"gray","text":"Blocks mined: "},{"color":"yellow","text":"325
"},{"color":"gray","text":"Blocks placed: "},{"color":"yellow","text":"287
"},{"color":"gray","text":"Island Level: "},{"color":"yellow","text":"0
"},{"color":"gray","text":"Playtime: "},{"color":"yellow","text":"5h 32m 32s
"},{"color":"gray","text":"Party: "},{"color":"yellow","text":"Oblivion
"},{"color":"gray","text":"Click to message"}]}},"clickEvent":{"action":"run_command","value":"/msg Aevox "}},{"text":""},{"text":"","extra":[{"color":"gray","text":"[Oak Wood x64"},{"color":"gray","text":"]"}],"hoverEvent":{"action":"show_item","value":"{id:"minecraft:oak_wood",Count:64b}"}}]<--[HERE]
```

**Cmi Version (using`/cmi version`):** 
[16:09:57 INFO]: --------------------------------------------------
[16:09:57 INFO]: CMI: 8.7.2.4 BungeeCord MySQL-> 8.7.2.6
[16:09:57 INFO]: Server: Paper(378) 1.15.2-R0.1-SNAPSHOT
[16:09:57 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[16:09:57 INFO]: Modules -> 50 enabled 1 disabled: tablist
[16:09:57 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):**  Paperspigot

**Server Version (using `/ver`):** 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Update plugin, you have outdated version
