### ISSUE TITLE
/cmi scan error

### ISSUE THREAD

**Issue by dwdddfly** [Zrips/CMI#3773]
[04:14:19 INFO]: cyera_heihei issued server command: /scan continue
[04:14:19 WARN]: [CMI] Task #118164 for CMI v8.7.2.5 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/material/Hopper
at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:218) ~[?:?]
at com.Zrips.CMI.Modules.Scan.Scan.CheckContent(Scan.java:402) ~[?:?]
at com.Zrips.CMI.Modules.Scan.Scan$1.run(Scan.java:182) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[jyf.jar:git-PaperSpigot-f6fba00-9935adc]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by Zrips** [comment]
Will be fixed with next version
