### ISSUE TITLE
Could not pass event PlayerMoveEvent

### ISSUE THREAD

**Issue by Srborjaa** [Zrips/CMI#3780]
**Description of issue:**
When a user moves after being in afk state, this error appears:

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:26:59 ERROR]: Could not pass event PlayerMoveEvent to CMI v8.7.2.8
java.lang.NullPointerException: null
        at com.Zrips.CMI.Modules.Portals.CuboidArea.<init>(CuboidArea.java:27) ~[?:?]
        at com.Zrips.CMI.Containers.CMIHitBox.collides(CMIHitBox.java:439) ~[?:?]
        at com.Zrips.CMI.Modules.Afk.AfkListener.onPlayerMove(AfkListener.java:274) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor581.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-379]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-379]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-379]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1153) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-379]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-379]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 8.7.2.8

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper(379) 1.15.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Will get fixed with today's update
