### ISSUE TITLE
 Could not pass event ServerCommandEvent to CMI v8.7.3.2

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3798]
Paper: Paper version git-Paper-108 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

CMI: CMI v8.7.3.2

Since the latest update, CustomAlias.yml has stopped working. We get a big error message instead

`>.... [18:24:08 ERROR]: Could not pass event ServerCommandEvent to CMI v8.7.3.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.3.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:738) ~[patched_1.16.1.jar:git-Paper-108]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:720) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:100) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:62) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor873.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-108]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-108]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:705) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:470) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:466) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:93) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:112) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor869.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-108]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1904) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-108]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:327) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-108]
... 39 more`

**Comment by CloudeLecaw** [comment]
also some custom commands stoped working
This custom alias i tried to execute
```
  speedstop:
    Cmds:
    - asPlayer! rideadm fly disable
    - asPlayer! rideadm KarusellFlug disable
    - asPlayer! rideadm ketten disable
    - asPlayer! rideadm Riesenrad disable
    - asPlayer! rideadm Lamania disable
    - asPlayer! rideadm Speedy disable
    - asPlayer! rideadm tower disable
    - perm:cmi.command.customalias.serverstop! asConsole! speedstop2
  speedstop2:
    Cmds:
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Neustart
      in 5 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Neustart
      in 4 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Neustart
      in 3 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Neustart
      in 2 %subtitle% &4&lBitte loggt euch jetzt aus.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! cmi titlemsg all Serverneustart!
      %subtitle% &4&lDer Server startet nun neu.
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! rp save-all
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! minecraft:save-all
    - delay! 5
    - perm:cmi.command.customalias.serverstop! kickall! &eDer Server ist gleich wieder
      online!
    - delay! 1
    - perm:cmi.command.customalias.serverstop! fromConsole! minecraft:stop

```

This is the errorcode in console - looks simlias to the one Blueeyestar posted
```
>.... [18:24:08 ERROR]: Could not pass event ServerCommandEvent to CMI v8.7.3.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.3.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:738) ~[patched_1.16.1.jar:git-Paper-108]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:720) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:100) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:62) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor873.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-108]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-108]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:705) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:470) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:466) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:93) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:112) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor869.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-108]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-108]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1904) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1259) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-108]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-108]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:327) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-108]
... 39 more
```

**Comment by CloudeLecaw** [comment]
An other apearet to our joincommand
This is the code that normaly should be executed on login

```
[19:04:41] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v8.7.3.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:738) ~[patched_1.16.1.jar:git-Paper-101]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:720) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:108) ~[?:?]
	at com.Zrips.CMI.Modules.EventActions.EventActionManager.performCommands(EventActionManager.java:81) ~[?:?]
	at com.Zrips.CMI.Modules.EventActions.EventActionManager.performCommands(EventActionManager.java:52) ~[?:?]
	at com.Zrips.CMI.Modules.EventActions.EventActionListener.PlayerJoinEvent(EventActionListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor829.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-101]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:327) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-101]
	... 26 more
```

**Comment by Zrips** [comment]
issued fix for this issue, try out .3 version
