### ISSUE TITLE
[CMI] Join error

### ISSUE THREAD

**Issue by ArcadeFighter** [Zrips/CMI#3800]
**Description of issue:**
When player join, this error happend.

---

**ERROR:**
```
[19:35:46 WARN]: [CMI] Task #145371 for CMI v8.7.3.2 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.3.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607) ~[skyblock.jar:git-Paper-33d42c8e]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:720) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$2.run(SpecializedCommandManager.java:137) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:852) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[skyblock.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.ClassCastException: com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to org.bukkit.entity.Player
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:327) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[skyblock.jar:git-Paper-33d42c8e]
        ... 14 more

```

---

**Cmi Version (using`/cmi version`):** 8.7.3.2

**Server Type (Spigot/Paperspigot/etc):** Paper 1.12.2

**Server Version (using `/ver`):** Paper version git-Paper-33d42c8e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
[19:04:41] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to CMI v8.7.3.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:738) ~[patched_1.16.1.jar:git-Paper-101]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:720) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:108) ~[?:?]
	at com.Zrips.CMI.Modules.EventActions.EventActionManager.performCommands(EventActionManager.java:81) ~[?:?]
	at com.Zrips.CMI.Modules.EventActions.EventActionManager.performCommands(EventActionManager.java:52) ~[?:?]
	at com.Zrips.CMI.Modules.EventActions.EventActionListener.PlayerJoinEvent(EventActionListener.java:72) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor829.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-101]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:373) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:142) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:327) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-101]
	... 26 more

**Comment by Zrips** [comment]
Issued fix
