### ISSUE TITLE
[CMI] Chat tag error

### ISSUE THREAD

**Issue by ArcadeFighter** [Zrips/CMI#3801]
**Description of issue:**
When you somebody tag in chat, it throw error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:41:23 ERROR]: Command Dispatched Async: cmi sound BLOCK_NOTE_BLOCK_PLING:3:1 MrLarkyy_ -s
[19:41:23 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:667) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607) ~[skyblock.jar:git-Paper-33d42c8e]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:707) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:108) ~[?:?]
        at com.Zrips.CMI.Modules.ChatTag.TagManager.tag(TagManager.java:139) ~[?:?]
        at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:127) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor947.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[skyblock.jar:git-Paper-33d42c8e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1407) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1322) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[skyblock.jar:git-Paper-33d42c8e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[19:41:23 ERROR]: Command Dispatched Async: cmi sound BLOCK_NOTE_BLOCK_PLING:3:1 MrLarkyy_ -s
[19:41:23 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:667) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:607) ~[skyblock.jar:git-Paper-33d42c8e]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:720) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:108) ~[?:?]
        at com.Zrips.CMI.Modules.ChatTag.TagManager.tag(TagManager.java:139) ~[?:?]
        at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:127) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor947.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[skyblock.jar:git-Paper-33d42c8e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1407) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1322) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[skyblock.jar:git-Paper-33d42c8e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**CONFIG SECTION:**
```
  Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: true
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: false
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&c'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound BLOCK_NOTE_BLOCK_PLING:3:1 [playerName] -s
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: false
```

---

**Cmi Version (using`/cmi version`):** 8.7.3.2

**Server Type (Spigot/Paperspigot/etc):** Paper 1.12.2

**Server Version (using `/ver`):** Paper version git-Paper-33d42c8e (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next version. For time being you could remove command and leave it at 
CommandsOnTag: []
