### ISSUE TITLE
Gradient in chat formatting broken.

### ISSUE THREAD

**Issue by HumanTarget** [Zrips/CMI#3802]
**Description of issue:**
When adding a gradient to the chat formatting section, it breaks all formatting.
Additionally as a feature request within here: Could/is it possible to have a multi-gradient chat format?

---
```
22.07 14:42:22 [Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v8.7.3.3
22.07 14:42:22 [Server] INFO java.util.UnknownFormatConversionException: Conversion = '?'
22.07 14:42:22 [Server] INFO at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:101) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:156) ~[?:?]
22.07 14:42:22 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor700.execute(Unknown Source) ~[?:?]
22.07 14:42:22 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1825) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1740) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-108]
22.07 14:42:22 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_242]
22.07 14:42:22 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
22.07 14:42:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
22.07 14:42:22 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
22.07 14:42:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```
```
GroupFormat:
    '1': '%luckperms_prefix% &f|&f {displayName} &f|&r &8&lLVL &e&l%LevelPoints_player_level%&f
      &7&l>>&r {#0f1eaf>}{message}{#fd641f<}'
```

---

**Cmi Version (using`/cmi version`):** 8.7.3.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper-108

**Relevant plugins (Delete if this isn't needed):** LuckPerms

![image](https://user-images.githubusercontent.com/39173534/88215618-8ecce080-cc21-11ea-81c6-36bfdd8109cd.png)
Top chat message is with the formatting above. Bottom chat message is without the two gradient hex codes.

**Comment by Zrips** [comment]
In general this is not really a bug as you should not be using gradient for message. This simply causes issues and more specific support should be added to be able to handle gradient messages, especially if you want multicolored ones. Closing this ticket, you could create new one with feature request to have gradient messages.
