### ISSUE TITLE
/scan  error

### ISSUE THREAD

**Issue by dwdddfly** [Zrips/CMI#3816]
issued server command: /sCAN speed 100
[06:42:08 WARN]: [CMI] Task #69604 for CMI v8.7.3.4 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.ArmorStand.getFacing()Lorg/bukkit/block/BlockFace;
        at com.Zrips.CMI.Modules.Scan.Scan.CheckContent(Scan.java:413) ~[?:?]
        at com.Zrips.CMI.Modules.Scan.Scan$1.run(Scan.java:259) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[jyf.jar:git-PaperSpigot-f6fba00-9935adc]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [jyf.jar:git-PaperSpigot-f6fba00-9935adc]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by Zrips** [comment]
Issue fix with next version
