### ISSUE TITLE
Sign bug with SignShop

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#3826]
**Description of issue:**

Hello, on my server players can create their own shops with SignShop plugin. But when anyone shift + right-clicking on SignShop sign - sign will be restored.

1. Sign before shift + right-clicking:
![image](https://user-images.githubusercontent.com/7281619/88475313-58e86e80-cf37-11ea-8176-7038fbe25763.png)

2. Sign after shift + right-clicking: 
![image](https://user-images.githubusercontent.com/7281619/88475308-4ff79d00-cf37-11ea-955e-11b06abf0daf.png)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[11:52:37 WARN]: java.lang.NoSuchFieldException: c
[11:52:37 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2411)
[11:52:37 WARN]:        at com.Zrips.CMI.Reflections.openSignUI(Reflections.java:875)
[11:52:37 WARN]:        at com.Zrips.CMI.AllListeners.PlayerListeners.onSignInteractShift(PlayerListeners.java:1183)
[11:52:37 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor360.execute(Unknown Source)
[11:52:37 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[11:52:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[11:52:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:52:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:614)
[11:52:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:487)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1472)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:41)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1182)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1175)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1151)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:995)
[11:52:37 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:163)
[11:52:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

---

**Cmi Version (using`/cmi version`): 8.7.3.5** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot (SSSpigot fork)** 

**Server Version (using `/ver`): 1.16.1** 

**Relevant plugins (Delete if this isn't needed): Plugins (34): AAC, AACAdditionPro, AACPlus, ArmorStandTools, CMI, CMIPaperLib, ConditionalCommands*, DeluxeCombat, DeluxeMenus, EasyBackup, FarmLimiter, GangsPlus, HeadDatabase*, IllegalStack, LagAssist, LeaderHeadsRevamped, LuckPerms, MoonDonateGiver*, PlaceholderAPI, ProtocolLib, ShopGUIPlus, SignShop, SkinsRestorer, SpecializedCrates, SpigotGuard, StreakRewards, TAB, TigerReports*, TradePlus, Vault, WGExtender, WorldBorder, WorldEdit, WorldGuard
**

**Comment by Zrips** [comment]
Well, solution for time being will be to disable sign edit for 1.16.1 version due to bug in a client. This will continue working properly after Mojang releases 1.16.2 version.

**Comment by NineTown** [comment]
So how can I disable sign edit? Miss it in every config file

**Comment by Zrips** [comment]
Its permission based. You can ether wait for next CMI release which will be today, or negate cmi.signs.shiftedit
FYI You can always check for permissions with something like **/cmi checkperm sign**
