### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by NineTown** [Zrips/CMI#3829]
Few days ago I started to use ArmorStandTools instead CitizensNPC (cause Citizens are so laggy with commands npc). So after this I have this error which smap my console (latest.log is 1GB for 10 hours uptime server).

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[16:45:55] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.util.RayTraceResult org.bukkit.craftbukkit.v1_16_R1.util.CraftRayTraceResult.fromNMS(org.bukkit.World, net.minecraft.server.v1_16_R1.MovingObjectPosition)'
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_16_R1.getBlockLookingAt(v1_16_R1.java:2010)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getCollidingdBlock(CMIHitBox.java:426)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:363)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:355)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:1207)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:691)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:653)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:411)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:364)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1392)
[16:45:55] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor374.execute(Unknown Source)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:45:55] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:614)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:487)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1472)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:41)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1182)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1175)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1151)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:995)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:163)
[16:45:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:45:55] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.util.RayTraceResult org.bukkit.craftbukkit.v1_16_R1.util.CraftRayTraceResult.fromNMS(org.bukkit.World, net.minecraft.server.v1_16_R1.MovingObjectPosition)'
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_16_R1.getBlockLookingAt(v1_16_R1.java:2010)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getCollidingdBlock(CMIHitBox.java:426)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:363)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:355)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:1207)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:691)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1392)
[16:45:55] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor374.execute(Unknown Source)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:45:55] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:614)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:487)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1472)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:41)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1182)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1175)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1151)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:995)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:163)
[16:45:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:45:55] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.util.RayTraceResult org.bukkit.craftbukkit.v1_16_R1.util.CraftRayTraceResult.fromNMS(org.bukkit.World, net.minecraft.server.v1_16_R1.MovingObjectPosition)'
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_16_R1.getBlockLookingAt(v1_16_R1.java:2010)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getCollidingdBlock(CMIHitBox.java:426)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:363)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:355)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:1207)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:691)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:653)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:411)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:364)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1392)
[16:45:55] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor374.execute(Unknown Source)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:45:55] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:614)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:487)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1472)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:41)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1182)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1175)
[16:45:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:45:55] [Server thread/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.util.RayTraceResult org.bukkit.craftbukkit.v1_16_R1.util.CraftRayTraceResult.fromNMS(org.bukkit.World, net.minecraft.server.v1_16_R1.MovingObjectPosition)'
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_16_R1.getBlockLookingAt(v1_16_R1.java:2010)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.getCollidingdBlock(CMIHitBox.java:426)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:363)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMIHitBox.isEmptySpace(CMIHitBox.java:355)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getDownLocation(Teleportations.java:1207)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:691)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:653)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:411)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:364)
[16:45:55] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1392)
[16:45:55] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor374.execute(Unknown Source)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:45:55] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:614)
[16:45:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:487)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1472)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:41)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1182)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1175)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1151)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:995)
[16:45:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:163)
[16:45:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`): 8.7.3.5** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot (SSSpigot fork)** 

**Server Version (using `/ver`): 1.16.1** 

**Relevant plugins (Delete if this isn't needed): Plugins (34): AAC, AACAdditionPro, AACPlus, ArmorStandTools, CMI, CMIPaperLib, ConditionalCommands*, DeluxeCombat, DeluxeMenus, EasyBackup, FarmLimiter, GangsPlus, HeadDatabase*, IllegalStack, LagAssist, LeaderHeadsRevamped, LuckPerms, MoonDonateGiver*, PlaceholderAPI, ProtocolLib, ShopGUIPlus, SignShop, SkinsRestorer, SpecializedCrates, SpigotGuard, StreakRewards, TAB, TigerReports*, TradePlus, Vault, WGExtender, WorldBorder, WorldEdit, WorldGuard
**

**Comment by NineTown** [comment]
So I think error spam is triggered for right click on armor stand maybe? Cause it execute command (I use it for NPC-shop and tp to pvp arena for example)

**Comment by Zrips** [comment]
Give me link to your actual spigot fork you are using here. Its issue with your server build being incompatible

**Comment by arturek1666** [comment]
NineTown are you using sspigot in anychance as I do and have same issue xD

**Comment by arturek1666** [comment]
He is using this just like me:
https://www.mc-market.org/resources/14122/

**Comment by arturek1666** [comment]
I had contact author of ssspigot to see if he can fix it on his side.

**Comment by Zrips** [comment]
Well if you have some completely different platform then it was said to be supported, then ether i need to add direct support for that build, which doesn't seam to happen any time soon as i cant keep track of all 50+ different forks anyone decides to create. Or developer of that fork could simply keep spigot/paper spigot methods without actually modifying or removing them... 
At this point i can only issue some crude patch to fail silently, where we will print out one error message and continue failing on that method silently after that.

**Comment by arturek1666** [comment]
It was fine like one day ago but after the author updated the Ssspigot well something bad happen. So had contact him and waiting for respond.

**Comment by arturek1666** [comment]
I got replay that the issue was fixed by Ssspigot and on new update it should be fine. So check it and close the issue :)

**Comment by Zrips** [comment]
Nice to hear this one. if you will encounter errors again, let me know.
