### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by emanondev** [Zrips/CMI#3837]
**Description of issue:**

Just some errors on console, no big issue, triggered by text message "later \o"

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:35:18 INFO]: Christiansant » later \o
[12:35:18 WARN]: java.lang.reflect.InvocationTargetException
[12:35:18 WARN]: at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
[12:35:18 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:35:18 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[12:35:18 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:109)
[12:35:18 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:481)
[12:35:18 WARN]: at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:463)
[12:35:18 WARN]: at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:140)
[12:35:18 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[12:35:18 WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[12:35:18 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1324)
[12:35:18 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432)
[12:35:18 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1239)
[12:35:18 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[12:35:18 WARN]: at java.lang.Thread.run(Thread.java:748)
[12:35:18 WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 330 path $[2].extra[0].text
[12:35:18 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:60)
[12:35:18 WARN]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[12:35:18 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:494)
[12:35:18 WARN]: at net.minecraft.server.v1_15_R1.ChatDeserializer.a(SourceFile:519)
[12:35:18 WARN]: at net.minecraft.server.v1_15_R1.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:445)
[12:35:18 WARN]: ... 14 more
[12:35:18 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 1 column 330 path $[2].extra[0].text
[12:35:18 WARN]: at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[12:35:18 WARN]: at com.google.gson.stream.JsonReader.readEscapeCharacter(JsonReader.java:1550)
[12:35:18 WARN]: at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1004)
[12:35:18 WARN]: at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
[12:35:18 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
[12:35:18 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[12:35:18 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[12:35:18 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[12:35:18 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[12:35:18 WARN]: at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[12:35:18 WARN]: at com.google.gson.internal.Streams.parse(Streams.java:48)
[12:35:18 WARN]: ... 18 more
[12:35:18 INFO]: [CMI] Failed to show json message with packets, using command approach
[12:35:18 INFO]: Invalid chat component: Invalid escape sequence at line 1 column 330 path $[2].extra[0].text
[12:35:18 INFO]: ...ranco_xX" ["",{"text":"","extra":[{"color":"aqua","text":"Christiansant "},{"color":"dark_green","text":"» "}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"color":"gray","text":"12:35:18"}]}},"clickEvent":{"action":"suggest_command","value":"\/msg Christiansant "}},{"text":"","extra":[{"color":"white","text":"later \o"}]}]<--[HERE]
```

---
**Version**
CMI plugin version: 8.7.2.5 BungeeCord SqLite-> 8.7.4.0
Server: Tuinity 1.15.2-R0.1-SNAPSHOT
CMI economy: True Vault: 1.6.11(+) CMI Chat: True
Modules -> 50 enabled 1 disabled: votifier

**Comment by variananora** [comment]
Try to update your CMI version first.

**Comment by Zrips** [comment]
Yea, having outdated CMI version will not help out us here much. Update CMI to the latest version and if issue persists, let me know.
