### ISSUE TITLE
gamerule causes an error in console

### ISSUE THREAD

**Issue by dragontekgaming** [Zrips/CMI#3843]
**Description of issue:**
/cmi gamerule should bring up a gui of things to change, but instead causes an error in console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
27.07 20:16:32 [Server] Server thread/INFO DragonTheTek issued server command: /cmi gamerule
27.07 20:16:32 [Server] Server thread/ERROR null
27.07 20:16:32 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.4.0
27.07 20:16:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot_1.16.1.jar:git-Spigot-9639cf7-7c03d25]
27.07 20:16:32 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
27.07 20:16:32 [Server] INFO Caused by: java.lang.StackOverflowError
27.07 20:16:32 [Server] INFO at java.lang.Class.getEnclosingMethodInfo(Class.java:1072) ~[?:1.8.0_252]
27.07 20:16:32 [Server] INFO at java.lang.Class.getEnclosingClass(Class.java:1272) ~[?:1.8.0_252]
27.07 20:16:32 [Server] INFO at java.lang.Class.getSimpleBinaryName(Class.java:1443) ~[?:1.8.0_252]
27.07 20:16:32 [Server] INFO at java.lang.Class.getSimpleName(Class.java:1309) ~[?:1.8.0_252]
27.07 20:16:32 [Server] INFO at com.Zrips.CMI.Modules.GUI.CMIGui.addPagination(CMIGui.java:349) ~[?:?]
27.07 20:16:32 [Server] INFO at com.Zrips.CMI.Modules.GUI.CMIGui.addPagination(CMIGui.java:349) ~[?:?]
27.07 20:16:32 [Server] INFO at com.Zrips.CMI.Modules.GUI.CMIGui.addPagination(CMIGui.java:349) ~[?:?]

```

---

**Cmi Version (using`/cmi version`):** 
8.7.4.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-9639cf7-7c06d25 (MC: 1.16.1)

**Comment by variananora** [comment]
Can confirm.
With CMI 8.7.4.0 and Paper 1.16.1-113

**Comment by Zrips** [comment]
Confirmed, will be fixed with next version
