### ISSUE TITLE
[CMI] Votifier module issue

### ISSUE THREAD

**Issue by ArcadeFighter** [Zrips/CMI#3848]
**Description of issue:**
When you have disabled votifier module and somebody vote, it throw error in console.

---

**ERROR:**
```
[19:54:26 ERROR]: Could not pass event VotifierEvent to CMI v8.7.4.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[skyblock.jar:git-Paper-33d42c8e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[skyblock.jar:git-Paper-33d42c8e]
        at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
        at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onForward$2(NuVotifierBukkit.java:363) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[skyblock.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:852) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[skyblock.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[skyblock.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:118) ~[?:?]
        at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor823.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[skyblock.jar:git-Paper-33d42c8e]
        ... 12 more

```

**CONFIG SECTION:**
```
# Handles votifier system
# Applies for servers from 1.7.x and up
votifier: false
```

---

**Cmi Version (using`/cmi version`):** 8.7.4.1

**Server Type (Spigot/Paperspigot/etc):** Paper 1.12.2

**Server Version (using `/ver`):** Paper(33d42c8e) 1.12.2-R0.1-SNAPSHOT

**Relevant plugins:** SuperbVote

**Comment by x1p** [comment]
Same. Following.
I have the module also disabled so CMI should not listen to vote events!
```
votifier: false
```

**Comment by Zrips** [comment]
Will be fixed with next version
