### ISSUE TITLE
Error cmi list

### ISSUE THREAD

**Issue by Italoplcl** [Zrips/CMI#3851]
when using /cmi list or alias /list it shows this error in console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
> list
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "lt"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "ult"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "ur"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "eur"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: ""
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "e"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: ""
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "m"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "iana"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 WARN]: java.lang.NumberFormatException: For input string: "diana"
[06:25:12 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.list.list.perform(list.java:243)
[06:25:12 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:350)
[06:25:12 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[06:25:12 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[06:25:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
[06:25:12 WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:25:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:25:12 INFO]: ----------------------------------------------------------------
[06:25:12 INFO]: ----------------------------------------------------------------
[06:25:12 INFO]: defaults:  zZZz ahp_esteban,  _hues0s,  benja_enm,  Sanzco,  shoro_galaxia
[06:25:12 INFO]:
[06:25:12 INFO]: Total 5 jugadores conectados (de 40).
[06:25:12 INFO]: ----------------------------------------------------------------
>

---

**Cmi Version (using`/cmi version`): 8.7.4.0** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 1.16.1 - 121**

**Comment by Zrips** [comment]
You have incorrect group settup in your locale file. As stated at that section in with a comment, you cant have custom names for it, you need to use format as 
```
        group1: '&eGroup1: &f[list]'
        group2: '&eGroup2: &f[list]'
        group3: '&eGroup3: &f[list]'
        group4: '&eGroup4: &f[list]'
        group5: '&eGroup5: &f[list]'
        group6: '&eGroup6: &f[list]'
        group7: '&eGroup7: &f[list]'
        group8: '&eGroup8: &f[list]'
        group9: '&eGroup9: &f[list]'
        group10: '&eGroup10: &f[list]'
```
