### ISSUE TITLE
GET SavedItems - When Offline

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#3855]
**Description of issue:**
When a player is **offline** and vote on a website, **it return an error**.
When the same player is **online** and vote on a website, **it works**.
(VotingPlugin and CMI /cmi saveditems)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[VotingPlugin] Task #111132 for VotingPlugin v5.22 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.4.1
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-380]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-380]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-380]
at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Misc.MiscUtils$3.run(MiscUtils.java:142) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-380]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-380]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-380]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: bound must be positive
at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_242]
at com.Zrips.CMI.Modules.SavedItems.SavedItemManager.processText(SavedItemManager.java:206) ~[?:?]
at com.Zrips.CMI.Modules.SavedItems.SavedItemManager.getUpatedItemClone(SavedItemManager.java:176) ~[?:?]
at com.Zrips.CMI.commands.list.saveditems.perform(saveditems.java:119) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-380]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
- cmi saveditems get clevote -t:%player% -a:1
```

---

**Cmi Version (using`/cmi version`):** 
8.7.4.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper380
**Server Version (using `/ver`):** 
1.15.2
**Relevant plugins (Delete if this isn't needed):**
VotingPlugin (does the command)

**Comment by Zrips** [comment]
Will be fixed with next update
