### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by SinsOfSolitude** [Zrips/CMI#3861]
Completely random error, don't know what it influences, just spotted it in the console whenever I switch servers on my Bungeecord. Error gets sent on the server I join.

---

```
[01:14:22] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mCMIB proxy plugin detected[m
[01:14:22] [Server thread/WARN]: java.lang.NullPointerException
[01:14:22] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:396)
[01:14:22] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:352)
[01:14:22] [Server thread/WARN]: 	at com.Zrips.CMI.AllListeners.PlayerListeners$7.run(PlayerListeners.java:1023)
[01:14:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81)
[01:14:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[01:14:22] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061)
[01:14:22] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354)
[01:14:22] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009)
[01:14:22] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848)
[01:14:22] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[01:14:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

```

---

**Cmi Version (using`/cmi version`): 8.7.5.0** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`): 1.16.1** 

**Relevant plugins (Delete if this isn't needed): CMIB1.0.0.4(on proxy), no other relevant plugins**

**Comment by Zrips** [comment]
Should be fixed with next build
