### ISSUE TITLE
Warning in log

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3872]
**Description of issue:**
---
Hi, I got this warning in my log when someone got tokens and kit. 
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[00:48:17] [Server thread/INFO]: Tokeny » Added 1 tokens to michaltheguy.
[00:48:17] [Craft Scheduler Thread - 407/WARN]: java.io.IOException: Stream closed
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at java.base/java.io.BufferedWriter.ensureOpen(BufferedWriter.java:107)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:224)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at java.base/java.io.Writer.write(Writer.java:249)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at java.base/java.io.Writer.append(Writer.java:322)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at com.Zrips.CMI.Modules.Economy.EconomyManager.moneyLog(EconomyManager.java:871)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at com.Zrips.CMI.Modules.Economy.Economy$1.run(Economy.java:308)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[00:48:17] [Server thread/INFO]: Dal jsi kit HlasovaniCzechCraft hráči michaltheguy
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[00:48:17] [Craft Scheduler Thread - 407/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

---

**Cmi Version (using`/cmi version`):** 
```
[17:07:23 INFO]: --------------------------------------------------
[17:07:23 INFO]: CMI: 8.7.5.1 BungeeCord MySQL
[17:07:23 INFO]: Server: Paper(130) 1.16.1-R0.1-SNAPSHOT
[17:07:23 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False
[17:07:23 INFO]: Modules -> 38 enabled 13 disabled: customMessages, mirror, tablist, skin, cmiPlaytime, eventCommands, playerChatTag, ranks, firstJoinMessages, selection, attachedCommands, warmup, namePlates
[17:07:23 INFO]: --------------------------------------------------
```

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** git-Paper-130 (MC: 1.16.1)

**Comment by Zrips** [comment]
Nothing serious, its just failed, once, to record data into log for money transaction, doesn't have any effect on plugins work. At worst you lost one record of one transaction. Will fix this issue with next update tho.
