### ISSUE TITLE
Could not pass event VotifierEvent to CMI v8.7.5.3

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3891]
**With the offline voting no / cmi-Kit commands are executed anymore! Instead there is a big error message.
When one of us votes when he's not in the game, it actually happens:**

CommandsOnVote:
  - mysterydust add [playerName] 1
  - cmi give [playerName] diamond
  - cmi kit vote [playername]
  - aach add 1 Custom.votes [playerName]

**you get everything except the cmi kit vote [playername] is executed**

`[16:11:39] [Server thread/INFO]: Giving 1 of Diamond () to Blueeyestar
[16:11:39] [Server thread/ERROR]: 
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.5.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:738) ~[patched_1.16.1.jar:git-Paper-131]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:758) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:720) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:108) ~[?:?]
	at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:135) ~[?:?]
	at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor744.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-131]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-131]
	at com.vexsoftware.votifier.net.VoteReceiver$1.run(VoteReceiver.java:182) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_242]
	at com.Zrips.CMI.Modules.Kits.KitsManager.processText(KitsManager.java:766) ~[?:?]
	at com.Zrips.CMI.Modules.Kits.Kit.getItems(Kit.java:111) ~[?:?]
	at com.Zrips.CMI.Modules.Kits.KitsManager.giveKit(KitsManager.java:1299) ~[?:?]
	at com.Zrips.CMI.commands.list.kit.perform(kit.java:176) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-131]
	... 23 more
[16:11:39] [Craft Scheduler Thread - 11/INFO]: LuLu-Gadgets » Du hast erfolgreich 1 LuLuManten an Blueeyestar überwiesen.
[16:12:14] [Server thread/INFO]: Giving 1 of Diamond () to Blueeyestar`

**But this only happens when you are not in the game, but offline from outside. if you are in the game and vote, the instigation**
```

[16:18:57] [Server thread/INFO]: LuLu-Gadgets » Du hast erfolgreich 1 LuLuManten an Blueeyestar überwiesen.
[16:18:57] [Server thread/INFO]: Giving 1 of Diamond () to Blueeyestar
[16:18:57] [Server thread/INFO]: Du hast Blueeyestar das Kit vote gegeben.
[16:18:57] [Server thread/INFO]: [☘] Statistic Custom.votes increased by 1 for Blueeyestar!
[16:19:51] [Server thread/INFO]: Saving the game (this may take a moment!)
```

**Comment by Zrips** [comment]
Will be fixed with next version
