### ISSUE TITLE
[Exception error] Task for CMI generated null exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3902]
**Description of issue:**

upgraded cmi, /stop and started the server, player logged in, and no idea what they were doing (no commands entered from what i can see) and the console spit this out.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[09:26:28] [Server thread/WARN]: [CMI] Task #9916 for CMI v8.7.5.4 generated an exception
java.lang.NullPointerException: null
        at com.Zrips.CMI.Modules.Ranks.RankManager$2.run(RankManager.java:181) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-8fb6585]
        at java.lang.Thread.run(Thread.java:834) [?:?]
>
```

---

**Cmi Version (using`/cmi version`):** CMI plugin version: 8.7.5.4

**Server Type (Spigot/Paperspigot/etc):** Spigot 

**Server Version (using `/ver`):** 1.16.1
```
>ver
[09:28:11] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9639cf7-8fb6585 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[09:28:11] [Server thread/INFO]: Checking version, please wait...
[09:28:12] [Thread-98/INFO]: You are running the latest version
>
```
```
>cmi version
[09:28:03] [Server thread/INFO]: --------------------------------------------------
[09:28:03] [Server thread/INFO]: CMI plugin version: 8.7.5.4 SqLite
[09:28:03] [Server thread/INFO]: Server: Spigot 1.16.1-R0.1-SNAPSHOT
[09:28:03] [Server thread/INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[09:28:03] [Server thread/INFO]: Modules -> 50 enabled 1 disabled: flightCharge
[09:28:03] [Server thread/INFO]: --------------------------------------------------
```
**Relevant plugins (Delete if this isn't needed):**

**Comment by mrfloris** [comment]
<img width="1712" alt="Screenshot 2020-08-07 at 09 35 47" src="https://user-images.githubusercontent.com/28841349/89621310-6be13400-d891-11ea-97b0-0687254b1b45.png">

**Comment by Zrips** [comment]
Will be fixed with next update.
