### ISSUE TITLE
Team CMICol already exists in this scoreboard

### ISSUE THREAD

**Issue by aarons13** [Zrips/CMI#3909]
**Description of issue or feature request:**
Two servers linked via Bungeecord. When joining servers back and forth with /server, no issue first try. Upon second try, error below in proxy console and kicked from server with a 'CMICol already exists in scoreboard' error.
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
08.08 07:18:02 [Server] INFO java.lang.IllegalArgumentException: Team CMICol already exists in this scoreboard
08.08 07:18:02 [Server] INFO at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
08.08 07:18:02 [Server] INFO at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
08.08 07:18:02 [Server] INFO at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:210)
08.08 07:18:02 [Server] INFO at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124)
08.08 07:18:02 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
08.08 07:18:02 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
08.08 07:18:02 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
08.08 07:18:02 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
08.08 07:18:02 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
08.08 07:18:02 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
08.08 07:18:02 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
08.08 07:18:02 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
08.08 07:18:02 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
08.08 07:18:02 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
08.08 07:18:02 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
08.08 07:18:02 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
08.08 07:18:02 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
08.08 07:18:02 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
08.08 07:18:02 [Server] INFO at java.lang.Thread.run(Thread.java:748)
```

No changes to default config file.

---

**Cmi Version (using`/cmi version`):** 
CMI 8.7.5.5

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot with Bungeecord

**Server Version (using `/ver`):** 
git-Paper-116 version 1.16.1-R0.1 SNAPSHOT

**Relevant plugins (Delete if this isn't needed):** 
No other plugins aside from CMI.

**Comment by aarons13** [comment]
Issue can be resolved by setting `DisableTeamManagement` to true, disabling CMI player collision connections with teams.

**Comment by Zrips** [comment]
This might have been bungeecord issue as currently i cant reproduce this and it was mentioning of scoreboard change in #1509 buungee update. Try retesting with latest build if this issue still repeats let me know.
