### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to CMI - Spam everytime player send message

### ISSUE THREAD

**Issue by Baterka** [Zrips/CMI#3913]
**Description of issue:**
Console keep spamming this on every player message into chat (not on commands)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[18:17:50 ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.7.5.6
java.lang.NoClassDefFoundError: com/gamingmesh/jobs/CmiItems/ItemManager$CMIChatColor
        at com.Zrips.CMI.Modules.ChatTag.TagListener.AsyncPlayerChatEvent(TagListener.java:61) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor476.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-134]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-134]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-134]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1823) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1738) ~[patched_1.16.1.jar:git-Paper-134]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-134]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Cmi Version (using`/cmi version`):** 8.7.5.6

**Server Type (Spigot/Paperspigot/etc):** PaperMC

**Server Version (using `/ver`):** Build-134 1.16.1

**Comment by Zrips** [comment]
This was fixed with latest builds
