### ISSUE TITLE
new cmi update   8.7.5.7        [console] cmi rt %player% world          this command not working

### ISSUE THREAD

**Issue by ourworkzone** [Zrips/CMI#3925]
Paper-134
*******************

CMI - 270+ Commands/Insane Kits/Portals/Essentials/Economy/MySQL & SqLite/Much More! 8.7.5.7
*********************************************************************

[console] cmi rt %player% world          this command not working
**********************************************************************

[09:20:26] [Server thread/WARN]: [CitizensCMD] Task #3502351 for CitizensCMD v2.5 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'rt Rebel112 world' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(rt)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-134]
	at me.mattstudios.citizenscmd.listeners.NPCClickListener.lambda$doCommands$0(NPCClickListener.java:249) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:475) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:142) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:103) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:236) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-134]
	... 10 more
[09:20:27] [Server thread/WARN]: [CitizensCMD] Task #3502469 for CitizensCMD v2.5 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'rt Rebel112 world' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(rt)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-134]
	at me.mattstudios.citizenscmd.listeners.NPCClickListener.lambda$doCommands$0(NPCClickListener.java:249) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-134]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-134]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:475) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:142) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:103) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:236) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-134]
	... 10 more

**Comment by Zrips** [comment]
Getting fix with next version
