### ISSUE TITLE
Error on the newest ver 

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#3927]
**Description of issue:**

---

Hi, I'm getting this error on the newest ver... but got just one time, I uploaded again and restarted again and didn't happen, so maybe it was uploaded on my server wrongly, idk... try look please, and if it's due to wrong file, close.
**ERROR (DELETE IF YOU HAVE NO ERROR):**
https://pastebin.com/eL2M8DMX

---

**Cmi Version (using`/cmi version`):** 
```
[18:22:06 INFO]: --------------------------------------------------
[18:22:06 INFO]: CMI: 8.7.5.8 BungeeCord MySQL-> 8.7.5.7
[18:22:06 INFO]: Server: Paper(134) 1.16.1-R0.1-SNAPSHOT
[18:22:06 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False
[18:22:06 INFO]: Modules -> 36 enabled 16 disabled: customMessages, mirror, tablist, moneyCheque, portals, skin, cmiPlaytime, eventCommands, playerChatTag, flightCharge, ranks, firstJoinMessages, selection, attachedCommands, warmup, namePlates
[18:22:06 INFO]: --------------------------------------------------
```

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 
```
:23:11 INFO]: This server is running Paper version git-Paper-134 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[18:23:11 INFO]: Checking version, please wait...
[18:23:11 INFO]: Previous version: git-Paper-133 (MC: 1.16.1)
[18:23:11 INFO]: You are running the latest version

```

**Comment by Volgeop** [comment]
Also getting this one on the working server, where is any error on startup:
```
[15:30:00] [Server thread/WARN]: java.lang.NullPointerException
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:475)
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:142)
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:107)
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Sheduler.Schedule.perform(Schedule.java:286)
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Sheduler.Schedule.safePerform(Schedule.java:266)
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Sheduler.SchedulerManager.checkSchedulers(SchedulerManager.java:359)
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Sheduler.SchedulerManager.access$0(SchedulerManager.java:352)
[15:30:00] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Sheduler.SchedulerManager$1.run(SchedulerManager.java:304)
[15:30:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[15:30:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:30:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292)
[15:30:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
[15:30:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213)
[15:30:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001)
[15:30:00] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:30:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Zrips** [comment]
Second error was fixed with latest versions. First error will get fix with next version
