### ISSUE TITLE
My scheduler stopped working after upgrade

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3930]
**Description of issue:**

I get empty white lines in the chat and in console, so i can't even figure out what is causing that, but I suspected it might be the scheduler. I went ingame and typed /cmi scheduler announcer, and it errored. so here reporting that.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[23:11:44] [Server thread/INFO]: mrfloris issued server command: /cmi schedule announcer
[23:11:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.5.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:475) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:142) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:99) ~[?:?]
        at com.Zrips.CMI.Modules.Sheduler.Schedule.perform(Schedule.java:280) ~[?:?]
        at com.Zrips.CMI.commands.list.schedule.perform(schedule.java:38) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-f622793]
        ... 18 more
>cmi version
[23:11:59] [Server thread/INFO]: --------------------------------------------------
[23:11:59] [Server thread/INFO]: CMI plugin version: 8.7.5.7 SqLite
[23:11:59] [Server thread/INFO]: Server: Spigot 1.16.1-R0.1-SNAPSHOT
[23:11:59] [Server thread/INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[23:11:59] [Server thread/INFO]: Modules -> 50 enabled 1 disabled: flightCharge
[23:11:59] [Server thread/INFO]: --------------------------------------------------
>
```

**SCHEDULER SECTION (DELETE IF NOT RELEVANT):**
```
Announcer:
  Enabled: true
  MinPlayers: 3
  Delay: 1500
  Repeat: true
  Randomize: true
  Feedback: false
  Commands:
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} You can sit on stairs! (right click
    empty handed)
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} You can claim a horse once you tame
    it!
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Type /menu to find out what else is
    on our server.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Learn more about horses with the /horse
    command.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Level up for perks from /mcMMO.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Level up for rewards with /achievements,
    and /mh achievements
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} RPG mcMMO commands: /mcstats, /mcrank,
    /mctop :)'
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} RPG features: /horse, /fish, /pvp,
    /party'
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Protection cmds: /lock, /unlock, /cmodify'
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} You can have 6 homes with the player
    group.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} You can have 12 homes with the builder
    group.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} The blue club members can have 14 homes!
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Please join our website: omgboards.com/forums/minecraft/
    It has fun offtopic discussion, events, inside information, help, and much more.'
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Need resources? You can mine in the
    temporary /mine world
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Need resources? You can mine in the
    temporary /nether world
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Need resources? You can mine in the
    temporary /end world
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Players have access to the /back command
    to quickly teleport back to their previous location. Super handy if you accidentally
    died and lost your stuff.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Someone just /msg-ed you? Type /r to
    quick-reply
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Players cannot create portals, please
    use /end, /nether, /mine
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Ranks: Yellow, Green, Blue, and Red,
    to learn more about our ranks, type: /ranks'
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Welcome someone when they join to earn
    /points
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Grind mcMMO levels to unlock perks and
    level up your skill abilities.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Eat Pointy Fish to earn up to 5 /points
    per fish.
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Sell all the types of fish on the:
    /fish market'
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Server: 1MB version 2.8.1 for Minecraft
    1.16.1'
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Yellow Players can create up to 6 chest
    /shops
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Green Players can create up to 12 chest
    /shops
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} The command /j is a little perk for
    the Green rank. It allows the player to quickly teleport to where they point.
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Help grow the server, ask your friends
    to join!
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} First line on a sign [trash] to build
    a trash-bin!
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} To find out more of where you are, type
    /here
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Bottle your experience orbs with dragon
    breath, ask staff how! Location: /warp shops (the bedrock at the enchantment table)'
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Collect all the vote-tokens for unique
    OP stuff
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} You can sell and buy items on the /market
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Instead of regular operators, we have
    community helpers, ask away!
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} Player and Admin Shops: /warp shops'
  - broadcast! {#Cerulean} 1MB Tip »{#Feijoa} You cannot take from chests or break
    things made by others unless a sign says so. Please type /rules, and play fair.
    Thank you!
  - 'broadcast! {#Cerulean} 1MB Tip »{#Feijoa} A great way to make money is with Jobs,
    players can join up to three. To get started type: "/jobs browse"'

```

---

**Cmi Version (using`/cmi version`):** 8.7.5.7

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):**  This server is running CraftBukkit version git-Spigot-9639cf7-f622793 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**

I do not know if these white empty lines in console are related to this issue or not, i have no clue how to debug that.

<img width="877" alt="Screenshot 2020-08-10 at 23 14 25" src="https://user-images.githubusercontent.com/28841349/89832137-4b4dfe00-db5f-11ea-92bc-1042b4abacb1.png"> 
<img width="449" alt="Screenshot 2020-08-10 at 23 14 38" src="https://user-images.githubusercontent.com/28841349/89832129-48eba400-db5f-11ea-9d38-5583991fc6a6.png">

**Comment by mrfloris** [comment]
Actually.. /cmi version did not show there's a .8 out, i've upgraded and dont get the exception error. 
So leaving this open for now, but it seems it might have been fixed with the update.

**Comment by Zrips** [comment]
Was fixed with latest build
