### ISSUE TITLE
CMI Give

### ISSUE THREAD

**Issue by levarar** [Zrips/CMI#3934]
On the new version CMI, plugins that give out items through CMI (fabledskyblock, cases with prizes
) stopped doing it, the problem was observed on the latest version. After I rolled back to 8.7.5.3 the problem went away.

ERROR:
```
[12:17:47 INFO]: Root_User issued server command: /is c
[12:17:50 ERROR]: Could not pass event InventoryClickEvent to FabledSkyBlock v2.3.7
org.bukkit.command.CommandException: Unhandled exception executing 'money give Root_User 20' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(money)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:738) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at com.songoda.skyblock.challenge.challenge.Challenge$Type$2.executeReward(Challenge.java:240) ~[?:?]
at com.songoda.skyblock.challenge.player.PlayerManager.doChallenge(PlayerManager.java:193) ~[?:?]
at com.songoda.skyblock.challenge.inventory.inv.ChallengeInventory.lambda$init$1(ChallengeInventory.java:93) ~[?:?]
at com.songoda.skyblock.challenge.inventory.ClickableItem.run(ClickableItem.java:21) ~[?:?]
at com.songoda.skyblock.challenge.inventory.Inventory.handler(Inventory.java:189) ~[?:?]
at com.songoda.skyblock.challenge.inventory.InventoryManager.onPlayerInventoryClick(InventoryManager.java:103) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor876.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2438) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1192) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:475) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:142) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:103) ~[?:?]
at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:236) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Tuinity-"650532a"]
... 28 more


8.7.5.7:

**Tuinity **

Tuinity 1.16.1-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
Check out 8.7.5.8 pls ^^

**Comment by Zrips** [comment]
This was fixed already with latest build
