### ISSUE TITLE
Spigot 1.16.2  incompatible

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#3940]
A new MC version is out now, 1.16.2, and so the fun starts all over again for all server owners. I hereby post the first mistake. Welcome to the sleepless nights :)

`[00:05:47] [Server thread/INFO]: [CMI] Enabling CMI v8.7.5.8
[00:05:49] [Server thread/INFO]: ????? ?????? ????[m
[00:05:49] [Server thread/INFO]: ????? ? ?? ? ????[m
[00:05:49] [Server thread/INFO]: ?? ?? ??????  ?? [m
[00:05:49] [Server thread/INFO]: ?? ?? ??????  ?? [m
[00:05:49] [Server thread/INFO]: ????? ?????? ????[m
[00:05:49] [Server thread/INFO]: ????? ?????? ????[m
[00:05:49] [Server thread/INFO]: _______________________________________________________[m
[00:05:49] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16_R2
[00:05:49] [Server thread/WARN]: java.lang.ClassNotFoundException: com.Zrips.CMI.NBT.v1_16_R2
[00:05:49] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[00:05:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[00:05:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[00:05:49] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:05:49] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:05:49] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[00:05:49] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[00:05:49] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1327)
[00:05:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:05:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[00:05:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[00:05:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492)
[00:05:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[00:05:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435)
[00:05:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219)
[00:05:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808)
[00:05:49] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[00:05:49] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[00:05:49] [Server thread/INFO]:   [0;36;22m[0;33;22mVault was not found, you will have limited economy support[m
[00:05:49] [Server thread/INFO]:   [0;36;22m[0;36;22mLoaded ([0;37;1m26[0;36;22m) [0;37;22mportals [0;36;22minto memory. [0;33;22mTook [0;33;1m14[0;33;22mms[m
[00:05:49] [Server thread/INFO]:   [0;36;22mLoaded GeoLiteCity[m`

https://pastebin.com/RBXFCa32

**Comment by the456gamer** [comment]
there hasnt been a compatability update for cmi yet
can you be patient, its been a couple of hours

**Comment by Blueeyestar** [comment]
> 
> 
> there hasnt been a compatability update for cmi yet
> can you be patient, its been a couple of hours

Can you stop pissing me off ??? This was information so that you can see what the problem is. Should I wait 1 day before I report something that strikes me or wait for your permission ^^

**Comment by the456gamer** [comment]
Ok, sorry. I didn't mean come across like that.
The error is basically just saying hey! I haven't been given the right files to deal with 1.16.2 yet!

Sorry!

**Comment by Zrips** [comment]
Support for 1.16.2 comes out with today's update
