### ISSUE TITLE
[1.16.2] /cmi version gives null exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#3948]
**Description of issue:**

Typing in console `/cmi version` spits out null exception error.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>cmi version
[22:15:15] [Server thread/INFO]: --------------------------------------------------
[22:15:15] [Server thread/WARN]: [CMI] Task #23 for CMI v8.7.6.0 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.commands.list.version$1$1.run(version.java:78) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-43c7ff9]
	at java.lang.Thread.run(Thread.java:834) [?:?]
>
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
fresh default install
```

---

**Cmi Version (using`/cmi version`):** v8.7.6.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** 
```
>ver
[22:16:43] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[22:16:43] [Server thread/INFO]: Checking version, please wait...
[22:16:43] [Thread-8/INFO]: You are running the latest version
>
```

**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
This also happens in Version 1.16.1

```
[01:00:12 WARN]: [CMI] Task #146437 for CMI v8.7.6.0 generated an exception
java.lang.NullPointerException: null
        at com.Zrips.CMI.commands.list.version$1$1.run(version.java:78) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Zrips** [comment]
Fixing with next version
