### ISSUE TITLE
Portals edit error

### ISSUE THREAD

**Issue by Flashyboi** [Zrips/CMI#3955]
**Description of issue:**
when trying to open up gui edit for portals it sends an internal error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:11:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-135]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[?:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[?:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Containers.CMILocation.<init>(CMILocation.java:32) ~[?:?]
	at com.Zrips.CMI.commands.list.portals.perform(portals.java:375) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-135]
	... 18 more

```

---

**Cmi Version (using`/cmi version`):** 
8.7.6.0
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.16.1

**Comment by mrfloris** [comment]
Can reproduce on Spigot 1.16.1 latest build, and same CMI version, no other plugins installed. Fresh setup.
```
[12:31:05] [Server thread/INFO]: mrfloris issued server command: /cmi portals new testportal
[12:31:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1703) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1546) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.6.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:337) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at com.Zrips.CMI.utils.Util.performCommand(Util.java:544) ~[?:?]
	at com.Zrips.CMI.utils.Util.performCommand(Util.java:520) ~[?:?]
	at com.Zrips.CMI.CMI.performCommand(CMI.java:2301) ~[?:?]
	at com.Zrips.CMI.commands.list.portals.perform(portals.java:190) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	... 18 more
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Containers.CMILocation.<init>(CMILocation.java:32) ~[?:?]
	at com.Zrips.CMI.commands.list.portals.perform(portals.java:375) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:757) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:337) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at com.Zrips.CMI.utils.Util.performCommand(Util.java:544) ~[?:?]
	at com.Zrips.CMI.utils.Util.performCommand(Util.java:520) ~[?:?]
	at com.Zrips.CMI.CMI.performCommand(CMI.java:2301) ~[?:?]
	at com.Zrips.CMI.commands.list.portals.perform(portals.java:190) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:331) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	... 18 more
>
```

**Comment by Zrips** [comment]
Getting fix with next build
