### ISSUE TITLE
An error in console 1.16.2

### ISSUE THREAD

**Issue by JavituRec** [Zrips/CMI#3973]
**Description of issue:**
An error that appears from time to time on the console.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[Server thread/WARN]: [CMI] Task #6377231 for CMI v8.7.6.0 generated an exception
--
3072 | java.lang.NullPointerException: null
3073 | at com.Zrips.CMI.commands.list.version$1$1.run(version.java:78) ~[?:?]
3074 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
3075 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-135]
3076 | at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-135]
3077 | at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-135]
3078 | at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
3079 | at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
3080 | at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
3081 | at java.lang.Thread.run(Thread.java:834) [?:?]
3082 | [09:17:52] [Server thread/INFO]: §x--------------------------------------------------------
3083 | [09:17:52] [Server thread/WARN]: [CMI] Task #6377355 for CMI v8.7.6.0 generated an exception
3084 | java.lang.NullPointerException: null
3085 | at com.Zrips.CMI.commands.list.version$1$1.run(version.java:78) ~[?:?]
3086 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
3087 | at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-135]
3088 | at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-135]
3089 | at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-135]
3090 | at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-135]
3091 | at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-135]
3092 | at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
3093 | at java.lang.Thread.run(Thread.java:834) [?:?]

```

---

**Cmi Version (using`/cmi version`):** 
CMI v8.7.6.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.16.2

**Comment by Zrips** [comment]
Getting fix with next version
