### ISSUE TITLE
User bug and Remove user bug

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#4]
Startup error that spams console:
```
 Warning! There is two users with same name and diffrent UUID. This can cause issues! Please remove one of them from database with /cmi removeuser [uuid] 
 *usernamehere* *uuidhere* last seen: 41 days 8 hours 56 min 23 sec ago 
 *SameUsernameWithCapitalsHere* *otheruuidhere* last seen: 48 years 57 days 5 hours 51 min 32 sec ago
[00:51:32] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[00:51:32] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getLocationFromString(PlayerManager.java:1645)
[00:51:32] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getLocationMapFromString(PlayerManager.java:1629)
[00:51:32] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1511)
[00:51:32] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1189)
[00:51:32] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:773)
[00:51:32] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:544)
[00:51:32] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1165)
[00:51:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:51:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[00:51:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:51:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
[00:51:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
[00:51:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[00:51:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[00:51:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[00:51:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[00:51:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[00:51:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
Then when i type /cmi removeuser with the uuid of the 48year one it says:
```
[01:02:18] [Server thread/INFO]: Could not remove player data file. Most likely data file dont exist
[01:02:18] [Server thread/INFO]: Could not remove player stats file. Most likely data file dont exist
[01:02:18] [Server thread/INFO]: Could not remove player advancements file. Most likely data file dont exist
[01:02:18] [Server thread/INFO]: Could not remove player from database. Most likely data entrie dont exist
```
**Also feature request:** allow /cmi removeuser to be used ingame

**Comment by Zrips** [comment]
Plugin version?

**Comment by LogGits** [comment]
latest version (7.3.8.5)

**Comment by Zrips** [comment]
Will fix this error, tho this should not happen on normal conditions.
