### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4000]
[19:49:41 WARN]: java.util.ConcurrentModificationException
[19:49:41 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[19:49:41 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:49:41 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:49:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1310)
[19:49:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:694)
[19:49:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:598)
[19:49:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[19:49:41 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[19:49:41 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:49:41 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:49:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:49:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:49:41 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:49:41 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:50:28 INFO]: zwergolaf24 is now AFK
[19:50:35 INFO]: blakedj issued server command: /cmi balance
[19:50:39 INFO]: blakedj issued server command: /cmi balance Phalton
[19:50:46 WARN]: java.util.ConcurrentModificationException
[19:50:46 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[19:50:46 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:46 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1454)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:694)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:598)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[19:50:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:50:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:50:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:50:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:50:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:50:46 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:50:46 WARN]: java.util.ConcurrentModificationException
[19:50:46 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[19:50:46 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:46 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1310)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:694)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:598)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[19:50:46 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[19:50:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:50:46 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:50:46 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:50:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:50:46 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:50:46 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:50:51 WARN]: java.util.ConcurrentModificationException
[19:50:51 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[19:50:51 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:51 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:51 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1310)
[19:50:51 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:694)
[19:50:51 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:598)
[19:50:51 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[19:50:51 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[19:50:51 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:50:51 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:50:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:50:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:50:51 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:50:51 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:50:56 WARN]: java.util.ConcurrentModificationException
[19:50:56 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[19:50:56 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:56 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1454)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:694)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:598)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[19:50:56 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:50:56 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:50:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:50:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:50:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:50:56 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:50:56 WARN]: java.util.ConcurrentModificationException
[19:50:56 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[19:50:56 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:56 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1454)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:694)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:598)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[19:50:56 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[19:50:56 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
[19:50:56 WARN]:        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:50:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:50:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:50:56 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:50:56 WARN]:        at java.lang.Thread.run(Unknown Source)

Latest CMI Version in 1.16.1

PS: Thanks for the Warping changes!

**Comment by Zrips** [comment]
Small issue with baltop placeholder, should be resolved with next update
