### ISSUE TITLE
[CMI] Task #7280 for CMI v8.7.6.3 generated an exception

### ISSUE THREAD

**Issue by MikeWHK** [Zrips/CMI#4016]
**Description of issue:**
No noticeable problem in game, found error while scanning logs.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[16:27:08] [Server thread/WARN]: [CMI] Task #7280 for CMI v8.7.6.3 generated an exception
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (NaN)
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at org.bukkit.craftbukkit.v1_12_R1.boss.CraftBossBar.setProgress(CraftBossBar.java:123) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at com.Zrips.CMI.Modules.BossBar.BossBarManager$1.run(BossBarManager.java:209) ~[?:?]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

---

**Cmi Version (using`/cmi version`):**  8.7.6.3

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):**  
This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by MikeWHK** [comment]
Fixed, after restart the server
