### ISSUE TITLE
Multiple bungeecord offline issues

### ISSUE THREAD

**Issue by Roselle-cloud** [Zrips/CMI#4020]
**Description of issue:**

My server structure is

bungeecord-> server1
   |
Waterfall -> Server 2 -> Server 3

bungeecord only fills the ports of server1 and Waterfall
Fill the port of server2 and server3 in the waterfall chart

If you use 1.16+ client to transfer between server2 and server3, the connection will be dropped
Clients below 1.15 will not

If you remove CMI and use other cross-server plugins, this problem will not occur with 1.16+.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```
00:09:18 [严重] [Yin] <-> DownstreamBridge <-> [server2] - encountered exception
java.lang.IllegalArgumentException: Team CMICol already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
    at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:216)
    at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```
No change, default configuration
---

**Cmi Version (using`/cmi version`):** 
CMI-8.7.6.3
**Server Type (Spigot/Paperspigot/etc):** 
git-Paper-79 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
**Server Version (using `/ver`):** 
bungeecord and waterfall are both up to date
**Relevant plugins (Delete if this isn't needed):**

If you don’t have any time to implement this environment, please add my discord ID 小尹#2166
I will provide the server IP

**Comment by Zrips** [comment]
@Roselle-cloud 
Having remote server which has this issue will not really help out allot. I need to setup it on my test rig so i could test it out properly with as many changes to the plugin i would need and in shortest time possible, as this will involve some extensive testing to figure out why its failing on this particular minecraft client version and not on others. 
I need exact walk throw on how to setup basic environment you have this issue on, from start till end.

**Comment by Roselle-cloud** [comment]
> @Roselle-cloud
> Having remote server which has this issue will not really help out allot. I need to setup it on my test rig so i could test it out properly with as many changes to the plugin i would need and in shortest time possible, as this will involve some extensive testing to figure out why its failing on this particular minecraft client version and not on others.
> I need exact walk throw on how to setup basic environment you have this issue on, from start till end.

ok

**Comment by Roselle-cloud** [comment]
> @Roselle-cloud
> Having remote server which has this issue will not really help out allot. I need to setup it on my test rig so i could test it out properly with as many changes to the plugin i would need and in shortest time possible, as this will involve some extensive testing to figure out why its failing on this particular minecraft client version and not on others.
> I need exact walk throw on how to setup basic environment you have this issue on, from start till end.

Problem has been solved
Reason: CMI is not installed on server1
server1 is the login server, so I did not install it. . .

The player enters server1 from Bungeecord
Usage/Server Waterfall
Enter Waterfall, because the default server of Waterfall is server2
He will enter server2 and use /cmi server server3 on server2
Then the player will fall out of the bungee jump, or return to server1

This problem will not occur when cmi is installed on server1
