### ISSUE TITLE
help question

### ISSUE THREAD

**Issue by lanessNet** [Zrips/CMI#403]
Thank you for developing a good plugin

I have a question

1. How can I define a prefix in the rank? Do I have to use permissonEX?
Is there a requirement in the rank when using permisson?

2. Outputs an error log when using the spawn command on horse

```
[20:02:48 INFO]: NewWorld_ issued server command: /spawn
[20:02:48 WARN]: [CMI] Task #1067 for CMI v7.7.7.0 generated an exception
java.lang.NullPointerException: null
        at com.Zrips.CMI.AllListeners.PlayerListeners$3.run(PlayerListeners.java:592) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by lanessNet** [comment]
Can I see Rank and permisson as totally different? I'd like to use it together, but if not, we can use the chat format to show the rank and the permisson prefix.

**Comment by lanessNet** [comment]
I looked at the plugin you introduced and it looks like a really good plugin. How do I get this plugin to work with CMI's rank feature?

**Comment by MCTyler** [comment]
Just add a bunch of groups and label the CMI ranks the same as those groups. I will try to find my example. Give me a sec.

**Comment by lanessNet** [comment]
I took the guide and tried it, but it was not what I wanted.

When ranking up, the prefix has to be changed but it has not changed. Why?

`user:
  Enabled: true
  DisplayName: "&euser"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Branch1
  - Branch2
Branch1:
  Enabled: true
  DisplayName: "&2Branch1"
  AutoRankup: true
  RankupConfirmation: true
  Votes: 5
  ItemRequirement:
  - "Dirt:10"
  NextRanks:
  - Branch1Rank1
  MoneyCost: 100
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Branch1 rank!"`

**Comment by lanessNet** [comment]
`test`

**Comment by lanessNet** [comment]
I took the guide and tried it, but it was not what I wanted.

When ranking up, the prefix has to be changed but it has not changed. Why?

`
user:
Enabled: true
DisplayName: "&euser"
DefaultRank: true
AutoRankup: true
NextRanks:

Branch1
Branch2
Branch1:
Enabled: true
DisplayName: "&2Branch1"
AutoRankup: true
RankupConfirmation: true
Votes: 5
ItemRequirement:
"Dirt:10"
NextRanks:
Branch1Rank1
MoneyCost: 100
Commands:
"broadcast! &6[playerDisplayName] &eleveled up to Branch1 rank!"
`

**Comment by lanessNet** [comment]
I took the guide and tried it, but it was not what I wanted.

When ranking up, the prefix has to be changed but it has not changed. Why?

```
user:
  Enabled: true
  DisplayName: "&euser"
  DefaultRank: true
  AutoRankup: true
  NextRanks:
  - Branch1
  - Branch2
Branch1:
  Enabled: true
  DisplayName: "&2Branch1"
  AutoRankup: true
  RankupConfirmation: true
  Votes: 5
  ItemRequirement:
  - "Dirt:10"
  NextRanks:
  - Branch1Rank1
  MoneyCost: 100
  Commands:
  - "broadcast! &6[playerDisplayName] &eleveled up to Branch1 rank!"
```
```

**Comment by Zrips** [comment]
Error should be fixed with next build

**Comment by MCTyler** [comment]
Confused...what was broke again?
