### ISSUE TITLE
 java.util.NoSuchElementException

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4055]
[22:09:00 WARN]: java.util.NoSuchElementException
[22:09:00 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.putAll(Unknown Source)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Statistics.StatsManager.getTop(StatsManager.java:324)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1350)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:699)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:603)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:566)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:172)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:897)
[22:09:00 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[22:09:00 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[22:09:00 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:09:00 WARN]: java.util.NoSuchElementException
[22:09:00 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.buildFromSorted(Unknown Source)
[22:09:00 WARN]:        at java.util.TreeMap.putAll(Unknown Source)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Statistics.StatsManager.getTop(StatsManager.java:324)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1383)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:699)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:603)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:566)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:172)
[22:09:00 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:897)
[22:09:00 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[22:09:00 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[22:09:00 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[22:09:00 WARN]:        at java.lang.Thread.run(Unknown Source)

Playtimetop not show latest CMI 8.7.6.6

**Comment by Zrips** [comment]
Should get resolved with next update
