### ISSUE TITLE
[CMI] Plugin CMI v8.7.6.6 generated an exception while executing task

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4057]
[09:52:45 WARN]: [CMI] Plugin CMI v8.7.6.6 generated an exception while executing task 10994
java.lang.NullPointerException: null
        at java.util.TreeMap.fixAfterInsertion(Unknown Source) ~[?:1.8.0_231]
        at java.util.TreeMap.put(Unknown Source) ~[?:1.8.0_231]
        at com.Zrips.CMI.Modules.Statistics.StatsManager$2.run(StatsManager.java:382) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-"dccaf59a0"]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-"dccaf59a0"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-"dccaf59a0"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

Latest CMI 8.7.6.6 and latest paper

**Comment by Zrips** [comment]
Should be resolved with next build
