### ISSUE TITLE
Removeuser error and duplicate issue

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#410]
**Description of issue or feature request:**

Running the `/cmi removeuser` command with a username creates errors.

#### IGNORE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

ERROR (IGNORE IF YOU HAVE NO ERROR):
```
WARN 23/05/2018 02:08:00
02:08:00java.lang.IllegalArgumentException: Invalid UUID string: usernamehere
at java.util.UUID.fromString(UUID.java:194)
at com.Zrips.CMI.commands.list.removeuser.perform(removeuser.java:30)
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648)
at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:465)
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:428)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
at java.lang.Thread.run(Thread.java:748)
```

Sidenote: running command with a uuid of a "duplicate player" causes this to output:
```
Could not remove player data file. Most likely data file dont exist
Could not remove player stats file. Most likely data file dont exist
Could not remove player from database. Most likely data entrie dont exist
```

Cmi Version (using`/cmi version`): 7.7.8.1
Server Type (Spigot/Paperspigot/etc): Paperspigot
Server Version (using `/ver`): paper 1.12.2 1416

**Comment by valenvaio** [comment]
Sidenote: running command with a uuid of a "duplicate player" causes this to output:

```
Could not remove player data file. Most likely data file dont exist
Could not remove player stats file. Most likely data file dont exist
Could not remove player from database. Most likely data entrie dont exist
```
while it deletes the player. And next time says that this player is no longer there.

**Comment by LogGits** [comment]
Still getting this issue, by posting the username error message I was suggesting it should be handled by code to print out something like "Please use a valid UUID."

Mine doesn't remove the user at all.
