### ISSUE TITLE
 java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4115]
[12:15:31 WARN]: java.util.ConcurrentModificationException
[12:15:31 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[12:15:31 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[12:15:31 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1525)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:700)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:604)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[12:15:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[12:15:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:15:31 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:15:31 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:15:31 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:15:31 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:15:31 WARN]: java.util.ConcurrentModificationException
[12:15:31 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[12:15:31 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[12:15:31 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1525)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:700)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:604)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[12:15:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[12:15:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:15:31 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:15:31 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:15:31 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:15:31 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:15:31 WARN]: java.util.ConcurrentModificationException
[12:15:31 WARN]:        at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
[12:15:31 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[12:15:31 WARN]:        at java.util.TreeMap$EntryIterator.next(Unknown Source)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1314)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:700)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:604)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[12:15:31 WARN]:        at com.Zrips.CMI.Modules.DynamicSigns.CMISign$1.run(CMISign.java:182)
[12:15:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[12:15:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:15:31 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:15:31 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[12:15:31 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[12:15:31 WARN]:        at java.lang.Thread.run(Unknown Source)

latest CMI and Paper

sometimes it spam in the console

**Comment by Zrips** [comment]
Should be resolved with next update
