### ISSUE TITLE
NPE on join

### ISSUE THREAD

**Issue by KasearMC** [Zrips/CMI#4124]
this occurred every time i joined my server while doing some testing. the error only occurred during some unrelated testing when i had most of my plugins uninstalled. after the testing when i installed everything again, the error stopped occurring.

i'm pretty sure that the plugins i had installed during testing were: CMI, luckperms, multiverse core, world edit, world guard.

---
```
31.08 08:49:01 [Server] WARN java.lang.NullPointerException
31.08 08:49:01 [Server] WARN at com.Zrips.CMI.CMI.sendMessage(CMI.java:2055)
31.08 08:49:01 [Server] WARN at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:400)
31.08 08:49:01 [Server] WARN at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:352)
31.08 08:49:01 [Server] WARN at com.Zrips.CMI.AllListeners.PlayerListeners$7.run(PlayerListeners.java:1028)
31.08 08:49:01 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99)
31.08 08:49:01 [Server] WARN at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
31.08 08:49:01 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298)
31.08 08:49:01 [Server] WARN at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377)
31.08 08:49:01 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213)
31.08 08:49:01 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001)
31.08 08:49:01 [Server] WARN at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
31.08 08:49:01 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```
```
```

---

CMI: 8.7.6.9

Minecraft: 1.16.1

Paper: 138

**Comment by Zrips** [comment]
Will be fixed with next update
