### ISSUE TITLE
/homes near:100 generates exception in console (doesn't work)

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#4133]
**Description of issue:**

/homes near:100 generates exception in console (doesn't work)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
`[09:51:37 WARN]: [CMI] Plugin CMI v8.7.6.10 generated an exception while executing task 15828
java.lang.NullPointerException: null
        at com.Zrips.CMI.commands.list.homes$1.run(homes.java:109) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-174]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.2.jar:git-Paper-174]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.2.jar:git-Paper-174]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
`

---

`[09:53:31 INFO]: --------------------------------------------------
[09:53:31 INFO]: CMI plugin version: 8.7.6.10 MySQL
[09:53:31 INFO]: Server: Paper(174) 1.16.2-R0.1-SNAPSHOT
[09:53:31 INFO]: CMI economy: True Vault: 1.7.3-b(CMIEInjector) CMI Chat: True
[09:53:31 INFO]: Modules -> 49 enabled 3 disabled: flightCharge, disabledEnchants, namePlates
[09:53:31 INFO]: --------------------------------------------------`

**Comment by Fabrimat** [comment]
It happens with any value

**Comment by Zrips** [comment]
Will be fixed with next update
