### ISSUE TITLE
[CMI] Plugin CMI v7.7.8.2 generated an exception while executing task 651558

### ISSUE THREAD

**Issue by valenvaio** [Zrips/CMI#415]
```
[20:04:57 WARN]: [CMI] Plugin CMI v7.7.8.2 generated an exception while executing task 651558
java.lang.NullPointerException: null
        at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:950) ~[patched_1.12.2.jar:git-Paper-1413]
        at net.minecraft.server.v1_12_R1.EntityPlayer.updateInventory(EntityPlayer.java:946) ~[patched_1.12.2.jar:git-Paper-1413]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.updateInventory(CraftPlayer.java:700) ~[patched_1.12.2.jar:git-Paper-1413]
        at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:85) ~[CMI7.7.8.2.jar:?]
        at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:74) ~[CMI7.7.8.2.jar:?]
        at com.Zrips.CMI.Modules.Skin.SkinListener$1$1.run(SkinListener.java:36) ~[CMI7.7.8.2.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1413]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1413]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1413]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Thre
```

**Comment by CloudeLecaw** [comment]
as u can see there the Tastnumber can switch ;)
https://github.com/Zrips/CMI/issues/418

like the other guy it would be nice to know what u did to create this Problem?
the tastnumber itself is just a number the Server gave this, Action/Event/what ever.
but it did not explain what how it was created

**Comment by MCTyler** [comment]
I really don't think #418 and this are related at all. Could you explain your reason for linking these?

**Comment by Zrips** [comment]
@valenvaio 
Should be fixed with next build
