### ISSUE TITLE
/playtime <server economy account> throws an unhandled error

### ISSUE THREAD

**Issue by jarim5891** [Zrips/CMI#4157]
When checking the server economy account playtime, an unhandled exception is thrown.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
[17:13:30 INFO]: * Total play time: 0 sec 
[17:13:30 WARN]: Unexpected exception while parsing console command "cmi playtime Government"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.6.12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.2.jar:git-Paper-183]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.2.jar:git-Paper-183]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.2.jar:git-Paper-183]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:762) ~[patched_1.16.2.jar:git-Paper-183]
        at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:409) ~[patched_1.16.2.jar:git-Paper-183]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:376) ~[patched_1.16.2.jar:git-Paper-183]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-183]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-183]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-183]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.commands.list.playtime.perform(playtime.java:39) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:332) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.2.jar:git-Paper-183]
        ... 9 more

######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
Jobs/generalConfig.yml, ln 224:

  # Server economy account
  # With this enabled, players will get money from defined user (server account)
  # If this account don't have enough money to pay for players for, player will get message
  UseServerAccount: true
  # Username should be with Correct capitalization
  AccountName: Government
#######################################
```

---

Cmi Version (using/cmi version):
[17:10:59 INFO]: --------------------------------------------------
[17:10:59 INFO]: CMI: 8.7.6.12 SqLite-> 8.7.6.13
[17:10:59 INFO]: Server: Paper(183) 1.16.2-R0.1-SNAPSHOT
[17:10:59 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: False
[17:10:59 INFO]: Modules -> 51 enabled 1 disabled: votifier
[17:10:59 INFO]: --------------------------------------------------

Server Type (Spigot/Paperspigot/etc):

Server Version (using /ver):
[17:11:35 INFO]: This server is running Paper version git-Paper-183 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
[17:11:35 INFO]: Checking version, please wait...
[17:11:36 INFO]: You are 1 version(s) behind

**Relevant plugins (Delete if this isn't needed):**
Jobs4.16.1.jar

**Comment by Zrips** [comment]
Should be resolved with next version
