### ISSUE TITLE
Failed save while saving DeathLocation field

### ISSUE THREAD

**Issue by sherwood2142** [Zrips/CMI#4165]
These warns only occur on BedWars server. It seems that something is enabled in config.yml. What should I disable to avoid annoying warns? It really spams a lot. The server is running on PaperSpigot 1.15.2, Java 8.

Pastebin logs --> https://pastebin.com/DY9kEkhP

```
[15:57:28] [Craft Scheduler Thread - 1941/INFO]: [CMI] Failed save while saving DeathLocation field (Location{world=null,x=-145.29101401814216,y=-97.19316873445669,z=932.4390402090578,pitch=-0.5999576,yaw=-197.39948})
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: java.lang.IllegalArgumentException: World unloaded
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at org.bukkit.Location.getWorld(Location.java:112)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.PlayerManager.convertLocationToString(PlayerManager.java:1995)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1193)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1120)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:699)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:447)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:337)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: java.sql.SQLException: Values not bound to statement
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at org.sqlite.core.CorePreparedStatement.checkParameters(CorePreparedStatement.java:71)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at org.sqlite.jdbc3.JDBC3PreparedStatement.addBatch(JDBC3PreparedStatement.java:110)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:712)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:447)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:337)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:57:28] [Craft Scheduler Thread - 1941/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Zrips** [comment]
Should be resolved with next version
