### ISSUE TITLE
CMI 8.7.6.15 won't load

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4170]
**Description of issue:**
CMI won't load on a empty test server.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:59:49 INFO]: [CMI] Enabling CMI v8.7.6.15
[20:59:49 INFO]: [CMIPaperLib] Enabling CMIPaperLib v1.0.0
[20:59:52 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[20:59:52 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[20:59:52 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃ ┃┃
[20:59:52 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃ ┃┃
[20:59:52 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[20:59:52 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[20:59:52 INFO]: _______________________________________________________
[20:59:52 INFO]: Integrating PaperSpigot async methods
[20:59:53 INFO]: 52 Enabled and 0 Disabled modules
[20:59:53 INFO]: [P2] (UUID) PlotSquared will fetch UUIDs in groups of 200
[20:59:53 INFO]: [P2] (UUID) PlotSquared has cached 100.0% of UUIDs
[20:59:53 INFO]: [P2] (UUID) PlotSquared has cached all UUIDs
[20:59:54 INFO]: Permission plugin: LuckPerms5.1.93
[20:59:54 INFO]: Initialized Cipher256 AES
[20:59:54 INFO]: Loaded (51) regular alias into memory. Took 90ms
[20:59:54 INFO]: Loaded (1) custom text's into memory. Took 1ms
[20:59:54 INFO]: 3.32.3 data base type detected
[20:59:54 INFO]: UserTable creating CREATE TABLE `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_uuid` text, `username` text, `nickname` text, `LogOutLocation` text, `DeathLocation` text, `TeleportLocation` text, `teleportToggled` boolean, `Homes` text, `LastLoginTime` bigint, `LastLogoffTime` bigint, `TotalPlayTime` bigint, `tFly` bigint, `tGod` bigint, `Glow` text, `Ips` text, `Cuffed` boolean, `AlertUntil` bigint, `AlertReason` text, `JoinedCounter` boolean, `LockedIps` text, `pTime` bigint, `Kits` text, `Charges` text, `Cooldowns` longtext, `Balance` double, `Notes` text, `Rank` text, `TagSound` boolean, `SignShiftEdit` boolean, `Spy` boolean, `CommandSpy` boolean, `BannedUntil` bigint, `BannedAt` bigint, `BannedBy` text, `BanReason` text, `Ignores` text, `Vanish` text, `Economy` text, `Mail` text, `FlightCharge` double, `UserMeta` text, `Flying` boolean, `Votifier` int, `Jail` text, `JailedUntil` bigint, `FakeAccount` boolean, `PlaytimeOptimized` bigint, `flightChargeEnabled` boolean, `noPayToggled` boolean, `JailReason` text, `Skin` text, `SignSpy` boolean, `Collision` boolean, `NamePrefix` text, `NameSuffix` text, `Warnings` text, `msgToggle` boolean, `NameColor` text, `Muted` text);
[20:59:55 INFO]: InvTable creating CREATE TABLE `inventories` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `inventories` longtext);
[20:59:55 INFO]: PlayTime creating CREATE TABLE `playtime` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `date` int, `h0` bigint, `h1` bigint, `h2` bigint, `h3` bigint, `h4` bigint, `h5` bigint, `h6` bigint, `h7` bigint, `h8` bigint, `h9` bigint, `h10` bigint, `h11` bigint, `h12` bigint, `h13` bigint, `h14` bigint, `h15` bigint, `h16` bigint, `h17` bigint, `h18` bigint, `h19` bigint, `h20` bigint, `h21` bigint, `h22` bigint, `h23` bigint);
[20:59:55 INFO]: PlayTimeReward creating CREATE TABLE `playtimereward` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `repeatable` text, `onetime` text);
[20:59:55 INFO]: Started SqLite data base. Took 414ms
[20:59:55 INFO]: Vault was not found, you will have limited economy support
[20:59:55 ERROR]: Error occurred while enabling CMI v8.7.6.15 (Is it up to date?)
java.lang.NoClassDefFoundError: com/gamingmesh/jobs/CmiItems/ItemManager$CMIChatColor
at com.Zrips.CMI.FileHandler.ConfigReader.get(ConfigReader.java:402) ~[?:?]
at com.Zrips.CMI.Modules.Economy.EconomyManager.loadConfig(EconomyManager.java:406) ~[?:?]
at com.Zrips.CMI.Config.load(Config.java:726) ~[?:?]
at com.Zrips.CMI.Config.load(Config.java:705) ~[?:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java:1450) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Purpur-710]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Purpur-710]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Purpur-710]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Purpur-710]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:472) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:251) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:943) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.1.jar:git-Purpur-710]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.gamingmesh.jobs.CmiItems.ItemManager$CMIChatColor
at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Purpur-710]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Purpur-710]
at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
... 15 more
[20:59:55 INFO]: [CMI] Disabling CMI v8.7.6.15
[20:59:55 INFO]: Closed db connections
```
Some files are not created, even after another reboot
Some files have a different formatting.
Ranks file example:
```yaml
Branch1:
  Enabled: true
  DisplayName: '&2Branch1'
  AutoRankup: true
  RankupConfirmation: true
  Votes: 5
  PermissionRequirement:
  - cmi.command.fly:Fly
```
is now:
```yaml
Branch1:
  Enabled: true
  DisplayName: "&2Branch1"
  AutoRankup: true
  RankupConfirmation: true
  Votes: 5
  PermissionRequirement:
  - "cmi.command.fly:Fly"
```
Maybe logical after a failed attempt to load, maybe it has nothing to do with the above, idk.

Edit: it won't load even if I all files (the default files from .13) are in place.

---

**Cmi Version (using`/cmi version`):** 
8.7.6.15
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.16.1

**Comment by x1p** [comment]
Speaking of the devil, a new version is there. :-)
.16 fixes it.
