### ISSUE TITLE
Only plugin running is vault-CMI-luckyperms

### ISSUE THREAD

**Issue by spiderpig1o** [Zrips/CMI#4177]
[latest (3).log](https://github.com/Zrips/CMI/files/5184086/latest.3.log)

**Comment by spiderpig1o** [comment]
nothing works on the server no commands and nothing will download on the console for the plugin to work it looks like

**Comment by CloudeLecaw** [comment]
```
[12:47:12] [Server thread/ERROR]: Error occurred while enabling CMI v8.7.6.16 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_251]
	at com.Zrips.CMI.commands.CommandsHandler.getClass(ätzii4inIAmM=öoFTSeöönbNMVöaBo5HzA=öFvPlDöFSwQCwE4Hjs=öYxOHsötuL6rTFDrKI=öAgoKqöL9hSHsZXsqQ=ötBwtsöezkYJUzWeNPpHr8BKoeKT5fwHrS+QDR3RWzvfLZc0GsFFJzcPIC6/g==ömgHgTöJx8CWjE9Bg4dJ2YOChk+KQMBWhEkAgYfECcACBU9LD4AGjctHw==öHmetSöCiE=öJQsgnöGRw=öYnsmNöTdj1rr/32xo=öUzdBzöMAYiHxkCBTQEGwUrökvGmtökBy7jaMZqT4=öfynDröFmJQSuLVGwc=öXeGJhöJEZq/cajuG4=öXfiBwöRQ==öeLycLöE0xYDg==öHiiSböPl1BOQ==öexsdjö6ckl7fE35y8=ölFyqUöVw==öwSjxaödw==öWPpjGöTg==önsmbRöd4BkK+k0f1A=ölcNCeöfJZ1+lgXwz/tKTE6AXY3rg==öINtUiöü:595) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(ätzii4inIAmM=öoFTSeöönbNMVöaBo5HzA=öFvPlDöFSwQCwE4Hjs=öYxOHsötuL6rTFDrKI=öAgoKqöL9hSHsZXsqQ=ötBwtsöezkYJUzWeNPpHr8BKoeKT5fwHrS+QDR3RWzvfLZc0GsFFJzcPIC6/g==ömgHgTöJx8CWjE9Bg4dJ2YOChk+KQMBWhEkAgYfECcACBU9LD4AGjctHw==öHmetSöCiE=öJQsgnöGRw=öYnsmNöTdj1rr/32xo=öUzdBzöMAYiHxkCBTQEGwUrökvGmtökBy7jaMZqT4=öfynDröFmJQSuLVGwc=öXeGJhöJEZq/cajuG4=öXfiBwöRQ==öeLycLöE0xYDg==öHiiSböPl1BOQ==öexsdjö6ckl7fE35y8=ölFyqUöVw==öwSjxaödw==öWPpjGöTg==önsmbRöd4BkK+k0f1A=ölcNCeöfJZ1+lgXwz/tKTE6AXY3rg==öINtUiöü:557) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(äby7Dd1jAUWDO4XQ6FSliCMzh41VO4cRTIzDCyfmx4HBhY/vffVYk1Bsq9KS/EJ6ZF6BnZLEAblAm3diOUPyUSx2HjXx+vVKrdqifBjE6sUpPtXzZ0yo4QjaKXXdUlaTJfDM2AaITEMQ=ötQObCöNQN9BeSKbprioWPjZyspcylU5JzywIqmNQN9BeSKbpoaxN+DxB8uoQ==öqFRAhöV2x+öaZLBGöYV1göSoXwNöPkWtirDLRF4=öGWAgWö7/nx71UtvAo=öangKFöUb5WY68bP1A4WjxRNjzOog==öDCQjZöK82+//s5OVQ=öMGuzhöJ7DtKgNrCeGRNnpqjdhITwxfln+qs4UxxiCT5KXms1r3FqFH0jn/g3ibsxjUTpAqyT4jhDiPjWY=öUApWmöCsExHy9gURgdeQ+kyxLvSge9GxIu62IcgcLFjymtEg4rFZaguEA9CMxwASJ7BU6iE9ZSsYFKLFg=öpDRcMöü:1446) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-b5a13e6-a939fbd]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 20
	at com.Zrips.CMI.commands.list.tempipban.TY_4WGOHevU(äGRQYNgwTFA==ötqkEmöTwUMPCBJJDk6ZSEHNTkgG0YwNTZJFSg7LgwIeQ==öifXTEöAQEMIA0dösdmSböTkjBRRzDe/hecCjM6VNORIYOt6Q0OvCaöLqTvmöJYN8y+uIoUaxV+Bs0LJrTw==öQtIxKöZDQzGDsuMBEUMGIiAAMiJyNFAyEuNBY=öBQeqTöH2pwdg1yzmEDSRCPeZNp3g==öTdNeyöK8MSq9DQZHXLejCRPpQlRpeHN0xHe6yqA0wdkRc58Ye6KOW2CeBDvJcUkzSLDBHiOLcc5eYOTfsWnbCFtdZ5A7v+grHMwYt+LCxJUUScrUQKEzvIreiOIk8Usc95fEFDöuYsIGöGzkgKhQqMSIqHg0=öyXNOpöR3YsaGAyKBsrNhVnQBN+VxoHIjkYJAUKMRIxGy8hLyAaKwVBZ0ApNxVhAys1EWEePngDIBkgPQVhESEqQWdAFSwILBITflZ7V2huOjMSLysOLyo=öaAwNXööü:10) ~[?:?]
	at com.Zrips.CMI.commands.list.tempipban.<clinit>(äGRQYNgwTFA==ötqkEmöTwUMPCBJJDk6ZSEHNTkgG0YwNTZJFSg7LgwIeQ==öifXTEöAQEMIA0dösdmSböTkjBRRzDe/hecCjM6VNORIYOt6Q0OvCaöLqTvmöJYN8y+uIoUaxV+Bs0LJrTw==öQtIxKöZDQzGDsuMBEUMGIiAAMiJyNFAyEuNBY=öBQeqTöH2pwdg1yzmEDSRCPeZNp3g==öTdNeyöK8MSq9DQZHXLejCRPpQlRpeHN0xHe6yqA0wdkRc58Ye6KOW2CeBDvJcUkzSLDBHiOLcc5eYOTfsWnbCFtdZ5A7v+grHMwYt+LCxJUUScrUQKEzvIreiOIk8Usc95fEFDöuYsIGöGzkgKhQqMSIqHg0=öyXNOpöR3YsaGAyKBsrNhVnQBN+VxoHIjkYJAUKMRIxGy8hLyAaKwVBZ0ApNxVhAys1EWEePngDIBkgPQVhESEqQWdAFSwILBITflZ7V2huOjMSLysOLyo=öaAwNXööü) ~[?:?]
	... 15 more
```
The problem is your ban list. try it aggain with a clear server /-no banlist or anything else) + vault + LuckPerms

**Comment by spiderpig1o** [comment]
ill give it a shot soon, its a brand new server so idk why its acting weird, if i have to add them manually thats fine but it just needs to work

**Comment by spiderpig1o** [comment]
what does the file look like? i have a file named Translations but i feel like im missing something

**Comment by CloudeLecaw** [comment]
When you downloade the file they have to be named like Locale_EN.yml when you have Set EN for language in config. The file has to be placed into the Translations subfolder.

**Comment by spiderpig1o** [comment]
ok so downloading the language files worked but it wont download config.yml  im pretty sure im only missing config now

**Comment by CloudeLecaw** [comment]
oh your mssing the default config yml?

ih wait i generate a full fresh CMI folder for you (i just delet the key file that get generated to proove you bought it on spigot)

**Comment by spiderpig1o** [comment]
[latest.log](https://github.com/Zrips/CMI/files/5192263/latest.log)
i have everything in the files correct now and every file in the cmi folder but plugin still doesnt want to work and throws a console error list

**Comment by CloudeLecaw** [comment]
It still has a problem with your banlist. Be sure you have cleared your ban and IP banlist?

**Comment by Zrips** [comment]
@spiderpig1o 
Try redownloading file, this was issue with webpage messing up some of the classes, adjusted options and now it should work properly.
