### ISSUE TITLE
[Bug Report] CMI Task exception

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#418]
:cat2: 

```
[08:08:27 WARN]: [CMI] Task #235962 for CMI v7.7.8.2 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.Zrips.CMI.AllListeners.PlayerListeners$4.run(PlayerListeners.java:964) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by CloudeLecaw** [comment]
could u explain what caused this Problem?

**Comment by Zrips** [comment]
Should be fixed with next build
