### ISSUE TITLE
TPS warnings command

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4185]
**Description of issue:**

---
TPS warnings

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:06:04] [Craft Scheduler Thread - 30/WARN]: java.lang.IndexOutOfBoundsException: Index 600 out of bounds for length 335
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/java.util.Objects.checkIndex(Objects.java:373)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/java.util.ArrayList.get(ArrayList.java:426)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:06:04] [Craft Scheduler Thread - 30/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

---

**Cmi Version (using`/cmi version`):**  8.7.7.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.16.2, 186 Paper

**Comment by Zrips** [comment]
Will be fixed with next update
