### ISSUE TITLE
Interactive command crash? or /cmi tps ?

### ISSUE THREAD

**Issue by PhracKko** [Zrips/CMI#4194]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
[17:58:02 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 466
[17:58:02 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:02 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:02 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:02 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:02 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:02 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:02 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:03 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 466
[17:58:03 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:03 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:03 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:03 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:03 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:03 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 467
[17:58:03 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:03 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:03 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:03 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:03 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:10 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 473
[17:58:10 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:10 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:10 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:10 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:10 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:10 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:10 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:12 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 476
[17:58:12 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:12 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:12 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:12 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:12 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:12 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:13 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 476
[17:58:13 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:13 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:13 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:13 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:13 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:13 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:13 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 477
[17:58:13 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:13 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:13 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:13 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:13 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:13 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:13 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:13 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:14 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 478
[17:58:14 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:14 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:14 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:58:14 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:58:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[17:58:14 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[17:58:14 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:15 WARN]: java.lang.IndexOutOfBoundsException: Index: 600, Size: 479
[17:58:15 WARN]:        at java.util.ArrayList.rangeCheck(Unknown Source)
[17:58:15 WARN]:        at java.util.ArrayList.get(Unknown Source)
[17:58:15 WARN]:        at com.Zrips.CMI.commands.list.tps.lambda$0(tps.java:110)
[17:58:15 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[17:58:15 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
[18:05:50 INFO]: CMI plugin version: 8.7.7.0 BungeeCord  SqLite
[18:05:50 INFO]: Server: Paper(387) 1.15.2-R0.1-SNAPSHOT
[18:05:50 INFO]: CMI economy: True Vault: 1.7.3-b131(CMIEInjector) CMI Chat: False
[18:05:50 INFO]: Modules -> 51 enabled 0 disabled:

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
[18:06:23 INFO]: This server is running Paper version git-Paper-387 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[18:06:23 INFO]: Checking version, please wait...
[18:06:25 INFO]: Previous version: git-Paper-378 (MC: 1.15.2)
[18:06:25 INFO]: You are running the latest version

**Relevant plugins (Delete if this isn't needed):**

**Comment by PhracKko** [comment]
Youtube Link
[https://www.youtube.com/watch?v=dphe-qIUUuo&feature=youtu.be](url)

**Comment by Zrips** [comment]
Known issue, this will get resolved with next version.
