### ISSUE TITLE
Error instead of design? /cmi se 5

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4279]
The new feature for /cmi se with the autocomplet is wonderfull
but if your typingan invalid nummer behind like 5 then you get an unnice looking error in console even if u have not really pressed enter or anything now.

```
>.... [00:56:38 ERROR]: Exception when Cloude_Lecaw attempted to tab complete se 5
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'se 5 ' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(se)
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:250) ~[patched_1.16.3.jar:git-Paper-206]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabCompleteCommand(CraftServer.java:1883) ~[patched_1.16.3.jar:git-Paper-206]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.tabComplete(CraftServer.java:1855) ~[patched_1.16.3.jar:git-Paper-206]
at org.bukkit.craftbukkit.v1_16_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.3.jar:git-Paper-206]
at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.3.jar:git-Paper-206]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.3.jar:git-Paper-206]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.PlayerConnection.lambda$a$4(PlayerConnection.java:584) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-206]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
at org.bukkit.craftbukkit.v1_16_R2.block.CraftSign.getLine(CraftSign.java:44) ~[patched_1.16.3.jar:git-Paper-206]
at com.Zrips.CMI.TabComplete.get(TabComplete.java:413) ~[?:?]
at com.Zrips.CMI.TabComplete.onTabComplete(TabComplete.java:75) ~[?:?]
at com.Zrips.CMI.TabComplete.get(TabComplete.java:201) ~[?:?]
at com.Zrips.CMI.Containers.CommandReg.onTabComplete(CommandReg.java:115) ~[?:?]
at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.tabComplete(CommandReg.java:270) ~[?:?]
at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.16.3.jar:git-Paper-206]
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.3.jar:git-Paper-206]
... 18 more
```

Would be nice if this could been fixed to have a small meassge in chat like "there is no line 5 on signs" instead of this error in the console. It can happen so fast that you pressed 5 instead of 4 :D

**Comment by Zrips** [comment]
Fixed
