### ISSUE TITLE
Sign error

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#429]
**Description of issue or feature request:**
Error with signs.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
07:26:04java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
at com.Zrips.CMI.AllListeners.PlayerListeners$4.run(PlayerListeners.java:964) ~[CMI7.7.9.0.jar:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1416]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1416]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Cmi Version (using`/cmi version`):** CMI7.7.9.0

**Server Type (Spigot/Paperspigot/etc):** patched_1.12.2.jar:git-Paper-1416

**Comment by Zrips** [comment]
Should be fixed in next update
