### ISSUE TITLE
Input command /cmi anvil The background will report an error

### ISSUE THREAD

**Issue by AauuOVO** [Zrips/CMI#4319]
[02:19:22] [Server thread/WARN]: java.lang.NullPointerException
[02:19:22] [Server thread/WARN]:        at com.Zrips.CMI.Modules.Anvil.CMIAnvilGUI.open(CMIAnvilGUI.java:345)
[02:19:22] [Server thread/WARN]:        at com.Zrips.CMI.Modules.Anvil.CMIAnvilGUI.open(CMIAnvilGUI.java:271)
[02:19:22] [Server thread/WARN]:        at com.Zrips.CMI.commands.list.anvil.perform(anvil.java:55)
[02:19:22] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:330)
[02:19:22] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:19:22] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:144)
[02:19:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:709)
[02:19:22] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1594)
[02:19:22] [Server thread/WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439)
[02:19:22] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[02:19:22] [Server thread/WARN]:        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[02:19:22] [Server thread/WARN]:        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[02:19:22] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:19:22] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:19:22] [Server thread/WARN]:        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[02:19:22] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839)
[02:19:22] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[02:19:22] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776)
[02:19:22] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
[02:19:22] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Cmi Version (using`/cmi version`):** 
8.7.8.1
**Server Type (Spigot/Paperspigot/etc):** 
CatServer
**Server Version (using `/ver`):** 
1.12.2

**Comment by CloudeLecaw** [comment]
Does this happen with paperMC or spigot?

i dont think it will be supported if this comes only from CatServer Fork,

Well maybe its easy to fix.. but just maybe..But dont aspect it.. normaly Zrips does not support any other servers then the regular Paper and Spigot...

**Comment by Zrips** [comment]
In general this is CatServer issue, but will make small error catcher to avoid showing this error, doesn't seam to have impact on UI work even if it fails.
