### ISSUE TITLE
cannot use nickname

### ISSUE THREAD

**Issue by filmmaro12** [Zrips/CMI#4326]
[02:41:23] [Server thread/INFO]: _TheepakornX_ issued server command: /nick xd
[02:41:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.8.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_261]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.util.regex.PatternSyntaxException: Unclosed character class near index 1
[]
 ^
	at java.util.regex.Pattern.error(Unknown Source) ~[?:1.8.0_261]
	at java.util.regex.Pattern.clazz(Unknown Source) ~[?:1.8.0_261]
	at java.util.regex.Pattern.sequence(Unknown Source) ~[?:1.8.0_261]
	at java.util.regex.Pattern.expr(Unknown Source) ~[?:1.8.0_261]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_261]
	at java.util.regex.Pattern.<init>(Unknown Source) ~[?:1.8.0_261]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:1.8.0_261]
	at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_261]
	at com.Zrips.CMI.utils.Util.validName(Util.java:1138) ~[?:?]
	at com.Zrips.CMI.commands.list.nick.perform(nick.java:99) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:330) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
	... 15 more

**Comment by Zrips** [comment]
What do you have set in config file for ValidNicknameRegex ? As this is the part which fails new nick name check
