### ISSUE TITLE
walk into Hologram Location console error.

### ISSUE THREAD

**Issue by Ricozaur** [Zrips/CMI#4350]
**Description of issue:**

I thought it was because i kept walking into an area where i recently deleted a hologram. But it seems that it's very time i walk into a hologram location.
---

**ERROR:**
```
[15:26:02 WARN]: java.lang.NumberFormatException: For input string: "[1-10]"
[15:26:02 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[15:26:02 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[15:26:02 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1401)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:698)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:602)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:565)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:172)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:853)
[15:26:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[15:26:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1354)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:26:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:26:02 WARN]: java.lang.NumberFormatException: For input string: "[1-10]"
[15:26:02 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[15:26:02 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[15:26:02 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1401)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:698)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:602)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:565)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:172)
[15:26:02 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:897)
[15:26:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[15:26:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1354)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:26:02 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:26:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:26:04 WARN]: java.lang.NumberFormatException: For input string: "[1-10]"
[15:26:04 WARN]:        at java.lang.NumberFormatException.forInputString(Unknown Source)
[15:26:04 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[15:26:04 WARN]:        at java.lang.Integer.parseInt(Unknown Source)
[15:26:04 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1401)
[15:26:04 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:698)
[15:26:04 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:602)
[15:26:04 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:565)
[15:26:04 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:172)
[15:26:04 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:897)
[15:26:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[15:26:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:26:04 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1354)
[15:26:04 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372)
[15:26:04 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267)
[15:26:04 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:26:04 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:26:04 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**CONFIG SECTION:** (idk if it's needed for this)
```
crates:
  Loc: spawn;15.56;67.62;-0.55
  Interval: -1.0
  LOSInterval: 0.0
  Range: 7
  RangeExtra: 35
  Spacing: 0.25
  SpacingIcon: 0.7
  DownOrner: true
  Interactable: false
  Lines:
  - '&dCrates'
  - Have any keys?
  - ICON:chest
parkourreward:
  Loc: spawn;0.46;75.76;36.92
  Interval: -1.0
  LOSInterval: 0.0
  Range: 7
  RangeExtra: 16
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&bA reward awaits you...'
topvotes:
  Loc: spawn;4.5;66.62;3.47
  Interval: 0.0
  LOSInterval: 0.0
  Range: 8
  RangeExtra: 16
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '%cmi_votetop_[1-10]%'
parkour:
  Loc: spawn;0.52;67.62;16.57
  Interval: -1.0
  LOSInterval: 0.0
  Range: 8
  RangeExtra: 35
  Spacing: 0.25
  SpacingIcon: 1.1
  DownOrner: true
  Interactable: false
  Lines:
  - '&b&lParkour'
  - Jumpy-jump
  - ICON:rails
clouds:
  Loc: spawn;-14.51;67.62;-0.49
  Interval: -1.0
  LOSInterval: 0.0
  Range: 8
  RangeExtra: 35
  Spacing: 0.25
  SpacingIcon: 1.0
  DownOrner: true
  Interactable: false
  Lines:
  - '&kf&b&l???&kf'
  - Still needs purpose.
  - ICON:barrier

```

---

**Cmi Version: 8.7.8.2** 

**Server Type: BungeeCord/FlameCord** 

**Server Version: 1.16.3**

**Comment by Zrips** [comment]
You have miss formatted placeholder.
Change
`  - '%cmi_votetop_[1-10]%'`
into
`  - '%cmi_votetop_1%'` and similar
