### ISSUE TITLE
Big errors while update CMI8.7.7.0 to CMI8.7.9.0

### ISSUE THREAD

**Issue by Hypocisy** [Zrips/CMI#4425]
**Description of issue:**
While update CMI to new version, the console cause so many database error, cmi can not load....
Other plugins relation with CMI can not load too.
Bro, please fix that, my server may not works good now.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[06:46:41] [Server thread/INFO]: [CMI] Enabling CMI v8.7.9.0
[06:46:41] [Server thread/INFO]: [CMIPaperLib] Enabling CMIPaperLib v1.0.0
[06:46:42] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[06:46:42] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[06:46:42] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[06:46:42] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[06:46:42] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[06:46:42] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[06:46:42] [Server thread/INFO]: _______________________________________________________
[06:46:42] [Server thread/INFO]:   Integrating PaperSpigot async methods
[06:46:43] [Server thread/INFO]:   41 Enabled and 10 Disabled modules
[06:46:43] [Server thread/INFO]:   Loaded (2) portals into memory. Took 14ms
[06:46:43] [Server thread/INFO]:   Loaded (3) dynamic signs into memory. Took 721ms
[06:46:43] [Server thread/INFO]:   Permission plugin: LuckPerms5.1.15
[06:46:43] [Server thread/INFO]:   Initialized Cipher256 AES
[06:46:44] [Server thread/INFO]:   Loaded (52) regular alias into memory. Took 17ms
[06:46:44] [Server thread/INFO]:   Loaded (1) custom text's into memory. Took 1ms
[06:46:44] [Server thread/INFO]:   5.5.5-10.4.14-MariaDB data base type detected
[06:46:44] [Server thread/INFO]:   Started MySQL data base. Took 91ms
[06:46:44] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: CMIEconomy
[06:46:44] [Server thread/INFO]:   Loaded (1) holograms into memory. Took 8ms
[06:46:44] [Server thread/INFO]:   Loaded (5) warning categories into memory. Took 0ms
[06:46:44] [Server thread/INFO]:   Loaded (3) warning commands into memory. Took 0ms
[06:46:44] [Server thread/INFO]:   Loaded (131) custom mob heads into memory. Took 8ms
[06:46:44] [Server thread/INFO]:   Loaded (0) cooldowns into memory. Took 14ms
[06:46:44] [Server thread/INFO]:   Loaded (4) warmups into memory. Took 0ms
[06:46:44] [Server thread/INFO]:   Loaded (2) jails into memory. Took 2ms
[06:46:44] [Server thread/INFO]:   (RandomTeleportation) Can't find world with (worldeditregentempworld) name
[06:46:44] [Server thread/INFO]:   Enabling BungeeCord Support
[06:46:44] [Server thread/INFO]:   Initializing BungeeCord
[06:46:44] [Server thread/INFO]:   Loaded (2) kits into memory. Took 7ms
[06:46:44] [Server thread/INFO]:   Loaded (0) ranks into memory. Took 3ms
[06:46:44] [Server thread/INFO]:   Loaded (8) playtime rewards into memory. Took 1ms
[06:46:44] [Server thread/WARN]: java.sql.SQLException: Column 'ToggleBBCompassOff' not found.
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1069)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getBoolean(ResultSetImpl.java:1623)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1942)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1377)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1194)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:583)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1438)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:46:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[06:46:44] [Server thread/WARN]: java.sql.SQLException: Column 'AFRecharge' not found.
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1069)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5166)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1954)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1377)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1194)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:583)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1438)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:46:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[06:46:44] [Server thread/WARN]: java.sql.SQLException: Column 'DisplayName' not found.
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1069)
[06:46:44] [Server thread/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5166)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1954)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1377)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1194)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:583)
[06:46:44] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1438)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[06:46:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[06:46:44] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:46:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

etc...

[06:46:49 WARN]: java.sql.SQLException: Column 'DisplayName' not found.
[06:46:49 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[06:46:49 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[06:46:49 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[06:46:49 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[06:46:49 WARN]:        at com.mysql.jdbc.ResultSetImpl.findColumn(ResultSetImpl.java:1069)
[06:46:49 WARN]:        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5166)
[06:46:49 WARN]:        at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1954)
[06:46:49 WARN]:        at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1377)
[06:46:49 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1194)
[06:46:49 WARN]:        at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:583)
[06:46:49 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1438)
[06:46:49 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[06:46:49 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[06:46:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[06:46:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[06:46:49 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[06:46:49 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[06:46:49 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[06:46:49 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[06:46:49 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[06:46:49 WARN]:        at java.lang.Thread.run(Thread.java:748)
[06:46:49 INFO]:   Loaded (834) player data into memory. Took 5409ms
[06:46:49 INFO]:   Loaded (0) playtime records into memory. Took 0ms
[06:46:49 INFO]:   Loaded (4) playtime reward records into memory. Took 5ms
[06:46:50 INFO]:   Loaded (2) interactive commands into memory. Took 2ms
[06:46:50 INFO]:   Found dynmap
[06:46:50 INFO]:   Registered events. Took 252ms
[06:46:50 INFO]:   Loaded (0) event action commands into memory. Took 3ms
[06:46:50 INFO]:   Updated (EN) language file. Took 99ms
[06:46:50 INFO]:   Updated (CN) language file. Took 58ms
[06:46:50 INFO]:   Can't load worth value for SIGN
[06:46:50 INFO]:   Loaded (244) worth values into memory. Took 7ms
[06:46:50 INFO]:   Loaded (4) warps into memory. Took 2ms
[06:46:50 INFO]:   Vault permissions was found - Enabling capabilities.
[06:46:50 INFO]: [PlaceholderAPI] Successfully registered expansion: cmi
[06:46:50 INFO]:   PlaceholderAPI hooked.
[06:46:50 INFO]:   PlaceholderAPI was found - Enabling capabilities.
[06:46:50 INFO]:   LWC was found - Enabling capabilities.
[06:46:50 INFO]:   Starting world timer.
[06:46:50 INFO]:   Initializing world manager.
[06:46:50 INFO]:   Loaded (5) schedules into memory. Took 3ms
[06:46:50 INFO]:   Loaded GeoIP
[06:46:50 INFO]:   Loaded (0) skin cache entries into memory. Took 0ms
[06:46:50 INFO]:   Loaded (2) custom recipes into memory. Took 6ms
[06:46:50 INFO]:   Version 8.7.9.0 has been enabled
[06:46:50 INFO]: ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
[06:46:50 INFO]: [CMIEInjector][Economy] CMI Economy hooked.
```

---

**Cmi Version (using`/cmi version`):** 
[06:52:14 INFO]: --------------------------------------------------
[06:52:14 INFO]: CMI 插件版本: 8.7.9.0 BungeeCord  MySQL
[06:52:14 INFO]: Server: Paper(229) 1.16.3-R0.1-SNAPSHOT
[06:52:14 INFO]: CMI economy: 是 Vault: 1.7.3-b131(CMIEInjector) CMI Chat: 是 
[06:52:14 INFO]: Modules -> 40 enabled 11 disabled: spawnerProximity, disabledEnchants, tablist, ranks, versionCheck, votifier, skin, noTarget, spawners, spawnerCharge, silentChest
[06:52:14 INFO]: --------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
[06:52:43 INFO]: This server is running Paper version git-Paper-229 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[06:52:43 INFO]: Checking version, please wait...
[06:52:45 INFO]: Previous version: git-Paper-216 (MC: 1.16.3)
[06:52:45 INFO]: You are 15 version(s) behind
**Relevant plugins (Delete if this isn't needed):**
[06:52:59 INFO]: Plugins (39): AlwaysKeepInventory*, AsyncWorldEdit, BigDoors, BungeeTabListPlus, ChunksExplorerLimiter*, ClearLag, CMI, CMIEInjector*, CMIPaperLib, ContainerControls, CoreProtect, CustomDragonDrop, dynmap*, EntityTrackerFixer, Harbor, IllegalStack, LangUtils, LiteSignIn, LuckPerms, LWC, MobSpawnLimit, PlaceholderAPI, PlayRewarder, PlugMan, ProtocolLib, QQBinder, QuickShop, RedPacket*, Residence, SAML, spark, Spartan, TimeIsMoney*, TitleManager, Vault, WoodCutter, WorldBorder, WorldEdit, WorldEditSUI

**Comment by Hypocisy** [comment]
By the way, my Mysql server version is: `10.4.14-MariaDB MariaDB Server`

**Comment by CloudeLecaw** [comment]
simply looks like CMI was not able to find your databse on your mysqlserver and was not able to create them too

**Comment by Hypocisy** [comment]
> simply looks like CMI was not able to find your databse on your mysqlserver and was not able to create them too. have you checked your mysql databse if the colums exists and if the server has access to create them?

Yes, My login is superuser, has all Linux perms, and database user is too.And CMI8.7.7.0 can run and has no error. Version > CMI8.7.7.0 Cause those errors. The dataBaseInfo.yml has no  change. So Please tell me how can I fix the error?

**Comment by Zrips** [comment]
Issue with new column creation for some reason. You can try creating those manually
```
	ToggleBBCompassOff	tinyint(1)
	AFRecharge	text
	DisplayName	text
```
Tho i wonder why it failed to make them in the first place, as no one else reported issue like this when i added those new collumns.

**Comment by Hypocisy** [comment]
> Issue with new column creation for some reason. You can try creating those manually
> 
> ```
> 	ToggleBBCompassOff	tinyint(1)
> 	AFRecharge	text
> 	DisplayName	text
> ```
> 
> Tho i wonder why it failed to make them in the first place, as no one else reported issue like this when i added those new collumns.

ok.

**Comment by Hypocisy** [comment]
> Issue with new column creation for some reason. You can try creating those manually
> 
> ```
> 	ToggleBBCompassOff	tinyint(1)
> 	AFRecharge	text
> 	DisplayName	text
> ```
> 
> Tho i wonder why it failed to make them in the first place, as no one else reported issue like this when i added those new collumns.
![image](https://user-images.githubusercontent.com/43266516/96889110-daa95300-14b8-11eb-9491-f3609a9d8e1d.png)
But database is all ready has those tables. how can i do?

**Comment by Hypocisy** [comment]
I mean, which table do these new columns belong to?

**Comment by Hypocisy** [comment]
Can someone please reply to me?

**Comment by Hypocisy** [comment]
> Issue with new column creation for some reason. You can try creating those manually
> 
> ```
> 	ToggleBBCompassOff	tinyint(1)
> 	AFRecharge	text
> 	DisplayName	text
> ```
> 
> Tho i wonder why it failed to make them in the first place, as no one else reported issue like this when i added those new collumns.

I did what you said and recreated these tables, and then no more errors were reported.

**Comment by CloudeLecaw** [comment]
so it looks like your mysql had programs with creating these new tables. may they where not used before so it may was not seens because u had all needed tabled before.

**Comment by Hypocisy** [comment]
> so it looks like your mysql had programs with creating these new tables. may they where not used before so it may was not seens because u had all needed tabled before.

This should just be a mysql issue. The server is running fine now, thank you very much!
