### ISSUE TITLE
null - CMI Itemname

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#4444]
**Description of issue:**
Renaming a Dragon egg causes a null error

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[00:58:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.9.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Purpur-802]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.3.jar:git-Purpur-802]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1974) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1777) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1172) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1016) ~[patched_1.16.3.jar:git-Purpur-802]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-802]
```

No big deal, just an error if you want to rename a dragon egg.
An anvil works as intented.

---

**Cmi Version (using`/cmi version`):** 
8.7.9.0
**Server Type (Spigot/Paperspigot/etc):** 
Purpur (Paper fork)
**Server Version (using `/ver`):** 
1.16.3

**Comment by Zrips** [comment]
Will get a fix with next build
