### ISSUE TITLE
Critical errors : a lost of lost cmi datas

### ISSUE THREAD

**Issue by RSLuke** [Zrips/CMI#4461]
**Description of issue:**

Now with latest I have even more players losing data (money/homes resetting), it looks like data is not saving.
It started happening in CMI8.7.9.0 and it now continues in CMI8.7.9.1.
In 8.7.9.0, I added manually the colums missing so the server could start but I don't know know if the unsaved datas come from the exception with the colum AFRecharge or just the update.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[07:36:16 WARN]: java.sql.BatchUpdateException: Column 'AFRecharge' cannot be null
[07:36:16 WARN]:        at sun.reflect.GeneratedConstructorAccessor170.newInstance(Unknown Source)
[07:36:16 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:36:16 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[07:36:16 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[07:36:16 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[07:36:16 WARN]:        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
[07:36:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1823)
[07:36:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1307)
[07:36:16 WARN]:        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[07:36:16 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:884)
[07:36:16 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:484)
[07:36:16 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:336)
[07:36:16 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[07:36:16 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[07:36:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:36:16 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[07:36:16 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[07:36:16 WARN]:        at java.lang.Thread.run(Thread.java:748)
[07:36:16 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'AFRecharge' cannot be null
[07:36:16 WARN]:        at sun.reflect.GeneratedConstructorAccessor156.newInstance(Unknown Source)
[07:36:16 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[07:36:16 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[07:36:16 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[07:36:16 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[07:36:16 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[07:36:16 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[07:36:16 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[07:36:16 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[07:36:16 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[07:36:16 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[07:36:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[07:36:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[07:36:16 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1801)
[07:36:16 WARN]:        ... 11 more
```

---

**Cmi Version (using`/cmi version`):**  CMI8.7.9.1

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.13.2

**Comment by RSLuke** [comment]
I had to go back to 8.7.5.5 while there is a stable release for this huge problem.

**Comment by Zrips** [comment]
By any chance you have created those columns manually and they are set to not being able to be a null value? In general you should be able to remove those columns and let them to be regenerated by plugin which should make them in a correct format. It would be nice to see how exactly your column settings look like.
Sorry for troubles you are having.

**Comment by RSLuke** [comment]
Yes I have created them without a null value, so I should delete the column AFRecharge right ?
Here are some screenshots :
https://puu.sh/GGA61/0357d50e9a.png
https://puu.sh/GGA6o/13299d2a67.png
I tried then to replace values within AFRecharge by 0 or 1 but it didn't fix anything.

**Comment by Zrips** [comment]
Yea, you have last 3 lines which cant contain NULL value as indicated with "Non" and "Aucun(e)" Those both need to match lines from above or simply remove them and allow them to be regenerated with CMI which hopefully with latest build should detect properly missing columns and create them

**Comment by RSLuke** [comment]
I have used the latest build on one of my servers when I haven't added or removed any column. The AFRecharge didn't regenerate.
I get spammed by these errors :
`[00:21:58 WARN]: java.sql.BatchUpdateException: Unknown column 'AFRecharge' in 'field list'
[00:21:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:21:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[00:21:58 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:21:58 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:21:58 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[00:21:58 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:386)
[00:21:58 WARN]:        at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1154)
[00:21:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1835)
[00:21:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1319)
[00:21:58 WARN]:        at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:954)
[00:21:58 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:884)
[00:21:58 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:484)
[00:21:58 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:336)
[00:21:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[00:21:58 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[00:21:58 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:21:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[00:21:58 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[00:21:58 WARN]:        at java.lang.Thread.run(Thread.java:748)
[00:21:58 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'AFRecharge' in 'field list'
[00:21:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:21:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[00:21:58 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:21:58 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:21:58 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
[00:21:58 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:386)
[00:21:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[00:21:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
[00:21:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[00:21:58 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[00:21:58 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[00:21:58 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[00:21:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[00:21:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2136)
[00:21:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1813)
[00:21:58 WARN]:        ... 11 more`

**Comment by RSLuke** [comment]
I can't add manually the column @Zrips looks like your table are too big now
# 1118 - Line too big. The maximum size of a row, except BLOBs, is 8126. Change the type of some columns to BLOBs

**Comment by RSLuke** [comment]
So I'm stucked with CMI8.7.5.5, it was the latest stable build for this.

**Comment by RSLuke** [comment]
ah nevermind I can't use CMI8.7.5.5 on 1.16.3 I have 0 solutions to have a viable server...

**Comment by Zrips** [comment]
Table ant be too big as its running just fine on everyone's else servers. Some core settings for your database prevents from new columns being created. Are you no longer able to create them manually? As you had them before, just column settings needed to be changed to accept null values. Other than this its hard to suggest anything specific.
What i find out after some googling that you might have some outdated row format, which needs to be "Dynamic" which is used in new versions of MariaDB, if you have had some old database being updated it might still have old format like 'Redundant' or 'Compact'. Will add some special code which maybe helps you out to update your table to "Dynamic" format which should resolve issue with new columns not being able to be created

**Comment by Zrips** [comment]
If you still having this issue let me know, for now closing this ticket. You can open new one and we can try to investigate this one further.
