### ISSUE TITLE
Spam in console 

### ISSUE THREAD

**Issue by fidzhikovsky** [Zrips/CMI#4467]
**Description of issue:** Spam in console

---

**ERROR:**
```
[14:01:41 WARN]: java.lang.NumberFormatException: For input string: "[1]"
[14:01:41 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[14:01:41 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:652)
[14:01:41 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:770)
[14:01:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1407)
[14:01:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:700)
[14:01:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:604)
[14:01:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[14:01:41 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:484)
[14:01:41 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$6.run(TabListManager.java:768)
[14:01:41 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[14:01:41 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:01:41 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:01:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[14:01:41 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[14:01:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```
Placeholder updated at .

---

**Cmi Version (using`/cmi version`):** last 8.7.9.2

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 1.16.3

**Relevant plugins :** AuthMe, AutoMessage*, ChestCommands, ClearLag, CMI, CMIEInjector*, CMIPaperLib, CoreProtect, DiscordSRV, LuckPerms, PlaceholderAPI, ProtocolLib, SAML, UltimateTimber, WGExtender, WorldBorder*, WorldEdit, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags.
>

**Comment by Zrips** [comment]
You have invalid placeholder for votetop, it should be cmi.votetop.1 and not cmi.votetop.[1] tho will add more informative message in case something like that happens again.

**Comment by fidzhikovsky** [comment]
Excuse me? I updated again Placeholder. and the error is the same.

**Comment by fidzhikovsky** [comment]
votetop off. why to spam in console
