### ISSUE TITLE
Versions starting from "8.7.9.0" to "8.7.9.3" break the plugins Mmoitems and Mmocore.

### ISSUE THREAD

**Issue by Lorenzostuy** [Zrips/CMI#4494]
**Description of issue:**

Like the title says the versions 
Version 8.7.9.3 has no problems with MMOCORE and MMOItems
Version 8.7.9.0 to version 8.7.9.3 break MMOCORE and MMOITEMS
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
>.... [19:15:19 ERROR]: Error occurred while enabling MMOItems v6.2.4 (Is it up to date?)
java.lang.NullPointerException: null
at net.Indyuce.mmoitems.comp.mythicmobs.MythicMobsLoader.getFactions(MythicMobsLoader.java:26) ~[?:?]
at net.Indyuce.mmoitems.comp.mythicmobs.MythicMobsLoader.<init>(MythicMobsLoader.java:19) ~[?:?]
at net.Indyuce.mmoitems.MMOItems.onEnable(MMOItems.java:169) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at java.lang.Thread.run(Thread.java:834) [?:?]
>.... [19:15:19 INFO]: [MMOItems] Disabling MMOItems v6.2.4
>.... [19:15:19 ERROR]: Error occurred while disabling MMOItems v6.2.4 (Is it up to date?)
java.lang.NullPointerException: null
at net.Indyuce.mmoitems.MMOItems.onDisable(MMOItems.java:332) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at java.lang.Thread.run(Thread.java:834) [?:?]

And the mmocore Error

>.... [19:23:44 INFO]: SlothSetups issued server command: /mmoitems
>.... [19:23:44 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'mmoitems' in plugin MMOItems v6.2.4 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1921) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1732) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1190) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1183) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1159) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Tuinity-"ef4e59a"]
at java.lang.Thread.run(Thread.java:834) [?:?]

```

---

**Cmi Version (using`/cmi version`):** 
Version 8.7.9.0 to version 8.7.9.3 break MMOCORE and MMOITEMS

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity

**Server Version (using `/ver`):** 
git-Tuinity-"5df4a4f" (MC: 1.16.3)
Basically latest version

**Comment by Zrips** [comment]
Your error log doesn't mention CMI and as of some testing with latest versions of MMOCORE and MMOITEMS it does seam to work. I will need some error logs mentioning CMI or atleast some explanation when exactly it breaks
And exact versions of mmocore and mmolib plugins

**Comment by Lorenzostuy** [comment]
Using latest dev versions of both MMOCORE & MMOITEMS

**Comment by Zrips** [comment]
That doesn't say allot. And i would recommend to run none dev versions. And any extra information when those errors appear?

**Comment by Lorenzostuy** [comment]
I have to use both plugins dev versions for certain features in both plugins besides that, once I load up the latest version of CMI, the other two plugins (MMOCORE & MMOITEMS) Just stop working,

https://pastebin.com/i5zVuU4C
There's the log

**Comment by Zrips** [comment]
You have error of mmoitems long before CMI even starts loading, i have no idea what they changed in those dev builds as i don't have access to them, but it doesn't look to even load properly from starting point. And if official mmoitems version works as it should, then i cant really help here until they release actual version. There is a reason why its called "dev build".
None of the errors you have in your logs directly mentions CMI, you will need to check out with mmoitems devs so they could fix this issue at their end as they have access to actual code which failed, which is located in their plugin and they will know why it did that even if it was caused by CMI, somehow, this is mmoitems bug.
