### ISSUE TITLE
Error after enabling maintenance mode, and then disabling it.

### ISSUE THREAD

**Issue by RuKira** [Zrips/CMI#4496]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## 28.10 19:49:50 [Server] INFO []<RuKira> Hello cmi?
28.10 19:50:00 [Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v8.7.9.3
28.10 19:50:00 [Server] INFO java.lang.NoSuchMethodError: nl.chimpgamer.networkmanager.api.models.player.Player.getTag()Ljava/lang/String;
28.10 19:50:00 [Server] INFO at nl.chimpgamer.networkmanager.NetworkManagerPlaceholderAPIExpension.parseOthersPlaceholders(NetworkManagerPlaceholderAPIExpension.java:182) ~[?:?]
28.10 19:50:00 [Server] INFO at nl.chimpgamer.networkmanager.NetworkManagerPlaceholderAPIExpension.onRequest(NetworkManagerPlaceholderAPIExpension.java:159) ~[?:?]
28.10 19:50:00 [Server] INFO at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
28.10 19:50:00 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
28.10 19:50:00 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
28.10 19:50:00 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:575) ~[?:?]
28.10 19:50:00 [Server] INFO at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:83) ~[?:?]
28.10 19:50:00 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor913.execute(Unknown Source) ~[?:?]
28.10 19:50:00 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:00 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:00 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1831) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:00 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1746) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:00 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:00 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_262]
28.10 19:50:00 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_262]
28.10 19:50:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
28.10 19:50:00 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
28.10 19:50:00 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
28.10 19:50:02 [Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v8.7.9.3
28.10 19:50:02 [Server] INFO java.lang.NoSuchMethodError: nl.chimpgamer.networkmanager.api.models.player.Player.getTag()Ljava/lang/String;
28.10 19:50:02 [Server] INFO at nl.chimpgamer.networkmanager.NetworkManagerPlaceholderAPIExpension.parseOthersPlaceholders(NetworkManagerPlaceholderAPIExpension.java:182) ~[?:?]
28.10 19:50:02 [Server] INFO at nl.chimpgamer.networkmanager.NetworkManagerPlaceholderAPIExpension.onRequest(NetworkManagerPlaceholderAPIExpension.java:159) ~[?:?]
28.10 19:50:02 [Server] INFO at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
28.10 19:50:02 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
28.10 19:50:02 [Server] INFO at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
28.10 19:50:02 [Server] INFO at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:575) ~[?:?]
28.10 19:50:02 [Server] INFO at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:83) ~[?:?]
28.10 19:50:02 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor913.execute(Unknown Source) ~[?:?]
28.10 19:50:02 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:02 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:02 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:02 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.chat(PlayerConnection.java:1831) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:02 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1746) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:02 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.3.jar:git-Paper-246]
28.10 19:50:02 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_262]
28.10 19:50:02 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_262]
28.10 19:50:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
28.10 19:50:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
28.10 19:50:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
##  GeneralFormat: '&7[{prefix}&7] &r{displayName} %networkmanager_tag%&7> &r{message}' ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.9.3
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper Version git-Paper-246 (MC: 1,16.3)

**Comment by RuKira** [comment]
This is my first time doing this, if you need any more info please let me know.

**Comment by CloudeLecaw** [comment]
Looks like the placeholder api dont want to work with the command or a used placeholder. May a wrong used placeholder? Could you post your langfile string for maintence from language file?

**Comment by RuKira** [comment]
maintenance: '&7Maintenance mode'

  maintenance:
    help:
      info: '&eSet server into maintenance mode'
      args: (true/false) (message)
      explanation:
      - cmi.command.maintenance.bypass - to bypass maintenance mode

basically, CMI chat formatting worked, enabled this mode, it stopped working, stopping it did not fix it.

**Comment by RuKira** [comment]
I'm not sure but this issue fixed itself.

**Comment by Zrips** [comment]
Issue originated from nl.chimpgamer.networkmanager.api.models.player.Player.getTag() plugin and not CMI itself, CMI only requested placeholder update and this plugin failed to produce one.
