### ISSUE TITLE
Module issue?

### ISSUE THREAD

**Issue by Trippyn** [Zrips/CMI#4498]
Throwing error (Hologram+Modules)

---

Module + Placeholder Error
```
[14:07:55] [Server thread/WARN]: java.util.NoSuchElementException
[14:07:55] [Server thread/WARN]: 	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1209)
[14:07:55] [Server thread/WARN]: 	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247)
[14:07:55] [Server thread/WARN]: 	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242)
[14:07:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1531)
[14:07:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:700)
[14:07:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:604)
[14:07:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[14:07:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:172)
[14:07:55] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:853)
[14:07:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81)
[14:07:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[14:07:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059)
[14:07:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349)
[14:07:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007)
[14:07:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846)
[14:07:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164)
[14:07:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Palo:
  Loc: Spawn2;9083.54;80.45;-10491.5
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&2&lPalo'
  - '&fZnova som zabludil'
MoneyTop:
  Loc: Spawn2;9121.45;100.01;-10488.51
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&8(&6TOP10&8) &e&lNajbohatsi Hraci &8(&6TOP10&8)'
  - '&8&m--------------------'
  - '&e1. &f%cmi_baltop_name_1% &8➠ &e%cmi_baltop_money_1%'
  - '&e2. &f%cmi_baltop_name_2% &8➠ &e%cmi_baltop_money_2%'
  - '&e3. &f%cmi_baltop_name_3% &8➠ &e%cmi_baltop_money_3%'
  - '&e4. &f%cmi_baltop_name_4% &8➠ &e%cmi_baltop_money_4%'
  - '&e5. &f%cmi_baltop_name_5% &8➠ &e%cmi_baltop_money_5%'
  - '&e6. &f%cmi_baltop_name_6% &8➠ &e%cmi_baltop_money_6%'
  - '&e7. &f%cmi_baltop_name_7% &8➠ &e%cmi_baltop_money_7%'
  - '&e8. &f%cmi_baltop_name_8% &8➠ &e%cmi_baltop_money_8%'
  - '&e9. &f%cmi_baltop_name_9% &8➠ &e%cmi_baltop_money_9%'
  - '&e10. &f%cmi_baltop_name_10% &8➠ &e%cmi_baltop_money_10%'
Jobs:
  Loc: Spawn2;9105.52;85.02;-10501.51
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&9&lPracovnik'
  - '&fHladas si pracu? Tak'
  - '&fsa zamestnaj u mna'
  - '&8(&fKlikni na mna&8)'
Obchodnik:
  Loc: Spawn2;9070.48;80.72;-10471.52
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&6&lObchodnik'
  - '&fPredavam cokolvek'
  - '&8(&fKlikni na mna&8)'
Kredity:
  Loc: Spawn2;9088.48;80.62;-10513.53
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&3&lKredity'
  - '&fKredity za super cenu'
  - '&8(&fKlikni na mna&8)'
aukcia:
  Loc: Spawn2;9076.46;86.65;-10627.5
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&1&lAukcia'
  - '&fHladas veci v aukcii?'
  - '&8(&fKlikni na mna&8)'
anabella:
  Loc: Spawn2;8892.42;67.65;-10553.52
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&5&lAnabella'
  - '&fPomozem ti ak chces'
  - '&8(&fKlikni na mna&8)'
Rybar:
  Loc: Spawn2;9098.45;77.81;-10534.52
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&a&lRybar'
  - '&fChytam ryby, ktore sa'
  - '&fpotom predavaju v obchode'
Pavucina:
  Loc: Spawn2;9100.51;82.52;-10508.5
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&b&lOtec'
  - '&fZberac pavucin'
knihovnik:
  Loc: Spawn2;9041.53;78.45;-10671.5
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&e&lKnihovnik'
  - '&fAkurat citam'
Straznik1:
  Loc: Spawn2;9106.53;88.72;-10482.45
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&3&lStraznik'
  - '&fStrazim tuto dedinu, pred'
  - '&fzlymi vojakmi a hracmi'
Kovar:
  Loc: Spawn2;9023.53;72.42;-10685.49
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&0&lKovar'
  - '&fOpravujem itemy'
Mama:
  Loc: Spawn2;9131.51;99.52;-10503.48
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&d&lMama'
  - '&fAkurat tu varim obed'
VIP:
  Loc: Spawn2;9082.51;80.72;-10476.52
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&9&lVIP'
  - '&fChces byt tiez bohaty?'
  - '&8(&fKlikni na mna&8)'
Welcome:
  Loc: Spawn2;9123.49;98.68;-10473.4
  Interval: 1.0
  LOSInterval: 0.0
  Range: 25
  RangeExtra: 45
  Spacing: 0.25
  SpacingIcon: 0.5
  DownOrner: true
  Interactable: false
  Lines:
  - '&e&lVitaj!'
  - '&fInformacie o servery'
  - '&8(&fKlikni na mna&8)'

```

---

**Cmi Version 8.7.9.2** 

**Server Type: Spigot** 

**Server Version: 1.16.3-R0.1-SNAPSHOT 3 versions behind**

**Comment by nitewing76** [comment]
Try removing the decimals from the Y-level.  I've had some problems if they are not integers. The problem has not been consistent...but when there is a problem, setting the Y-level to a whole number fixed it.

**Comment by Zrips** [comment]
Will be fixed with next update
