### ISSUE TITLE
Shutdown error

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#451]
**Description of issue or feature request:**

Error caused at shutdown.
```
WARN 03/06/2018 10:39:27
10:39:27 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:425)
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:418)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363)
at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:90)
at org.spigotmc.RestartCommand.restart(RestartCommand.java:60)
at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:854)
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1043)
at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:658)
at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:286)
at com.Zrips.CMI.CMI.onDisable(CMI.java:1053)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:425)
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:418)
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:363)
at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:90)
at org.spigotmc.RestartCommand.restart(RestartCommand.java:60)
at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31)
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:854)
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
at java.lang.Thread.run(Thread.java:748)
```

**Cmi Version (using`/cmi version`):** 7.8.0.0

**Server Type (Spigot/Paperspigot/etc):** paperspigot

**Server Version (using `/ver`):** paperspigot 1.12.2 1416

**Comment by LogGits** [comment]
Another error with saving to database:
```
12:54:07[CMI] SEVERE SAVE ERROR WHILE SAVING Poumatua PLAYER DATA (Collision)
WARN 03/06/2018 12:54:07
12:54:07java.lang.NullPointerException
at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1043)
at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:641)
at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:286)
at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:230)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1043)
at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:641)
at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:286)
at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:230)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by stashenko** [comment]
I also received an error on all servers after the update 7.8.0.0

**Comment by Zrips** [comment]
Will be fixed with next update
