### ISSUE TITLE
Completely Breaks server.

### ISSUE THREAD

**Issue by ablac** [Zrips/CMI#4521]
During boot CMI Disables itself, after crashing, and not being able to run.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://ptero.co/bulexogaxe.md
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Was caused by Update to new CMI Version
```

---

**Cmi Version (using`/cmi version`):** 

[05:02:08 WARN]: Unexpected exception while parsing console command "cmi version"
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v8.7.9.4 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.4.jar:git-Paper-256]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-256]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-256]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:764) ~[patched_1.16.4.jar:git-Paper-256]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.4.jar:git-Paper-256]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Paper-256]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-256]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-256]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-256]

**Server Type (Spigot/Paperspigot/etc):** 

Paper

**Server Version (using `/ver`):** 

[05:02:32 INFO]: This server is running Paper version git-Paper-256 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[05:02:32 INFO]: Checking version, please wait...
[05:02:32 INFO]: Previous version: git-Paper-231 (MC: 1.16.3)
[05:02:32 INFO]: You are running the latest version

**Comment by mrfloris** [comment]
I noticed this last night yep, but was about to jump into bed, anyway, here are my errors to confirm this isn't working on Spigot and Paper (both build few minutes ago)
```
[07:52:15] [Server thread/INFO]: [CMI] Enabling CMI v8.7.9.4
[07:52:16] [Server thread/ERROR]: Error occurred while enabling CMI v8.7.9.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1288) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.utils.VersionChecker$Version.isCurrentLower(VersionChecker.java:167) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<init>(CMIChatColor.java:209) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<init>(CMIChatColor.java:169) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<clinit>(CMIChatColor.java:134) ~[?:?]
	... 11 more
[07:52:16] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[07:52:16] [Server thread/INFO]: Done (16.083s)! For help, type "help"
[07:52:16] [Craft Scheduler Thread - 11/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 13
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 8/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 10
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 3/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 5
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 7/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 9
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 6/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 8
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 1/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 3
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 4/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 6
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 0/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 2
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 9/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 11
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 5/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 7
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 2/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 4
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[07:52:16] [Craft Scheduler Thread - 10/WARN]: [CMI] Plugin CMI v8.7.9.4 generated an exception while executing task 12
java.lang.NoClassDefFoundError: Could not initialize class com.Zrips.CMI.Containers.CMIChatColor
	at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1800) ~[?:?]
	at com.Zrips.CMI.utils.FileDownloader$1.run(FileDownloader.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.4.jar:git-Spigot-f011ca2-3af81c7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
>ver
[07:53:08] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f011ca2-3af81c7 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[07:53:08] [Server thread/INFO]: Checking version, please wait...
[07:53:08] [Thread-7/INFO]: You are running the latest version
>ver cmi
[07:53:11] [Server thread/INFO]: CMI version 8.7.9.4
[07:53:11] [Server thread/INFO]: Powerful server management tool
[07:53:11] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/content-management-interface.3742/
[07:53:11] [Server thread/INFO]: Author: Zrips
>
```

**Comment by mrfloris** [comment]
The above report is on spigot, on Paper 1.16.4 the error looks like this to me:
```
[07:58:49 INFO]: Time elapsed: 465 ms
[07:58:49 INFO]: [CMI] Enabling CMI v8.7.9.4
[07:58:49 INFO]: [CMIPaperLib] Enabling CMIPaperLib v1.0.0
[07:58:50 ERROR]: Error occurred while enabling CMI v8.7.9.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1288) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-256]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-256]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-256]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-256]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-256]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-256]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.utils.VersionChecker$Version.isCurrentLower(VersionChecker.java:167) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<init>(CMIChatColor.java:209) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<init>(CMIChatColor.java:169) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<clinit>(CMIChatColor.java:134) ~[?:?]
	... 11 more
[07:58:50 INFO]: [CMI] Disabling CMI v8.7.9.4
[07:58:51 INFO]: Running delayed init tasks
[07:58:51 INFO]: Done (6.952s)! For help, type "help"
[07:58:51 INFO]: Timings Reset
>
```
A few files are created, compared to spigot, but clearly it's not working hehe. 

<img width="647" alt="Screenshot 2020-11-03 at 08 00 03" src="https://user-images.githubusercontent.com/28841349/97957097-95373080-1daa-11eb-8455-9c04abf3ed76.png">

**Comment by CloudeLecaw** [comment]
hey guy ..just wait a bit the 1.16.4 was pushed this morning and issues from everywhere are aspected ;)

**Comment by mrfloris** [comment]
> hey guy ..just wait a bit the 1.16.4 was pushed this morning and issues from everywhere are aspected ;)
> im pretty sure a patch fix will follow the next days

It should be fairly easy to fix, it's probably nms related. I think we can expect an update on spigot later today.

**Comment by Zrips** [comment]
Will be fixed soon enough

**Comment by mrfloris** [comment]
Thumbsup, thank you for the swift follow up. Have fun testing everybody.
