### ISSUE TITLE
1.16.4 Error message on Paper

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#4524]
Hello, I hope you are doing well so far. Now the 1.16.4 is out. I'll send you the error message from paper. Then you know where you are .. hope that mojang haven't changed too much

I know the version was only out yesterday and everything takes time. I just wanted to send you in advance what error paper produced.

Paper version git-Paper-258 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

```
[09:57:18] [Server thread/INFO]: [CMI] Enabling CMI v8.7.9.4
[09:57:19] [Server thread/INFO]: [CMIPaperLib] Enabling CMIPaperLib v1.0.0
[09:57:20] [Server thread/ERROR]: Error occurred while enabling CMI v8.7.9.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1288) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.utils.VersionChecker$Version.isCurrentLower(VersionChecker.java:167) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<init>(CMIChatColor.java:209) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<init>(CMIChatColor.java:169) ~[?:?]
	at com.Zrips.CMI.Containers.CMIChatColor.<clinit>(CMIChatColor.java:134) ~[?:?]
	... 11 more
[09:57:20] [Server thread/INFO]: [CMI] Disabling CMI v8.7.9.4
[09:57:20] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[09:57:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.validate(CraftScheduler.java:537)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:197)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:192)
[09:57:20] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.tasker(SignManager.java:373)
[09:57:20] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addPlayersNearSign(SignManager.java:401)
[09:57:20] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addSign(SignManager.java:77)
[09:57:20] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.load(SignManager.java:274)
[09:57:20] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.<init>(SignManager.java:56)
[09:57:20] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.getSignManager(CMI.java:658)
[09:57:20] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1113)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[09:57:20] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[09:57:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[09:57:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[09:57:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939)
[09:57:20] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:57:20] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[09:57:20] [Server thread/INFO]:  Failed to load portal (blüte1)! Reason:null Error Log:
[09:57:20] [Server thread/ERROR]: [com.Zrips.CMI.Modules.Portals.PortalManager] null
java.lang.NullPointerException: null
	at com.Zrips.CMI.utils.VersionChecker$Version.isCurrentEqualOrHigher(VersionChecker.java:159) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIEffectManager$CMIParticle.getCMIParticle(CMIEffectManager.java:248) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.loadMap(PortalManager.java:399) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.load(PortalManager.java:365) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.<init>(PortalManager.java:62) ~[?:?]
	at com.Zrips.CMI.CMI.getPortalManager(CMI.java:652) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[09:57:20] [Server thread/INFO]:  Failed to load portal (blüte2)! Reason:null Error Log:
[09:57:20] [Server thread/ERROR]: [com.Zrips.CMI.Modules.Portals.PortalManager] null
java.lang.NullPointerException: null
	at com.Zrips.CMI.utils.VersionChecker$Version.isCurrentEqualOrHigher(VersionChecker.java:159) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIEffectManager$CMIParticle.getCMIParticle(CMIEffectManager.java:248) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.loadMap(PortalManager.java:399) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.load(PortalManager.java:365) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.<init>(PortalManager.java:62) ~[?:?]
	at com.Zrips.CMI.CMI.getPortalManager(CMI.java:652) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[09:57:20] [Server thread/INFO]:  Failed to load portal (blüte3)! Reason:null Error Log:
[09:57:20] [Server thread/ERROR]: [com.Zrips.CMI.Modules.Portals.PortalManager] null
java.lang.NullPointerException: null
	at com.Zrips.CMI.utils.VersionChecker$Version.isCurrentEqualOrHigher(VersionChecker.java:159) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIEffectManager$CMIParticle.getCMIParticle(CMIEffectManager.java:248) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.loadMap(PortalManager.java:399) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.load(PortalManager.java:365) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.<init>(PortalManager.java:62) ~[?:?]
	at com.Zrips.CMI.CMI.getPortalManager(CMI.java:652) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[09:57:20] [Server thread/INFO]:  Failed to load portal (blüte4)! Reason:null Error Log:
[09:57:20] [Server thread/ERROR]: [com.Zrips.CMI.Modules.Portals.PortalManager] null
java.lang.NullPointerException: null
	at com.Zrips.CMI.utils.VersionChecker$Version.isCurrentEqualOrHigher(VersionChecker.java:159) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIEffectManager$CMIParticle.getCMIParticle(CMIEffectManager.java:248) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.loadMap(PortalManager.java:399) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.load(PortalManager.java:365) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.<init>(PortalManager.java:62) ~[?:?]
	at com.Zrips.CMI.CMI.getPortalManager(CMI.java:652) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-258]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

```
[09:57:24] [Craft Scheduler Thread - 7/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.6 generated an exception while executing task 2325
java.lang.NoClassDefFoundError: com/Zrips/CMI/Modules/Economy/Economy
	at com.Zrips.Economy_CMI.getBalance(Economy_CMI.java:78) ~[?:?]
	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:220) ~[?:?]
	at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-258]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-258]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.Modules.Economy.Economy
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.4.jar:git-Paper-258]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Paper-258]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	... 9 more
```

**Comment by Zrips** [comment]
Will be fixed soon enough
