### ISSUE TITLE
[Solved] Economy is broken

### ISSUE THREAD

**Issue by MrPranklez** [Zrips/CMI#4528]
**Description of issue:**
Anything economy related seems to be broken with cmi, it started with a simple placeholder not being parsed but when executing command relating to cmi economy it throws an internal error

---

**ERROR:**
```
https://pastebin.com/SihFc9rs
```
---

**Cmi Version (using`/cmi version`):*latest 8.7.10.0* 

**Server Type (Spigot/Paperspigot/etc):*Paper* 

**Server Version (using `/ver`):*1.16.4*

**Comment by CloudeLecaw** [comment]
we tested cmi economy too on our server latest paper 1.16.4 And cmi8. 7.10 our economy works fine. 


what hook u choose? we took vault + cmiinjector

**Comment by MrPranklez** [comment]
I use the recompiled vault version

**Comment by CloudeLecaw** [comment]
we went back to vault + cmi injector becaus we has Problems too with zrips rexompiled Version. could you check if it works for you with vault (the normal one) + cmiinjector.
this would be just a proove that there is an issue with the rexompiled vaultversion of zrips in some casea

**Comment by MrPranklez** [comment]
switched and default vault is running and cmienjector as well but still get the following error

*versions:*
CMIEInjector:
`[11:25:48 INFO]: - Version: 1.0.2.3
[11:25:48 INFO]: - Author(s): Zrips
[11:25:48 INFO]: - Status: Enabled
[11:25:48 INFO]: - Depends: Vault, CMI`

*Vault:*
`[11:25:08 INFO]: - Version: 1.7.3-b131
[11:25:08 INFO]: - Author(s): cereal, Sleaker, mung3r
[11:25:08 INFO]: - Status: Enabled`

*Error:*
`[11:27:33 INFO]: MrPranklez issued server command: /bal
[11:27:33 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.10.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-259]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-259]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2005) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1816) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1769) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1135) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.4.jar:git-Paper-259]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-259]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Malformed pattern "###.###,00"
        at java.text.DecimalFormat.applyPattern(Unknown Source) ~[?:?]
        at java.text.DecimalFormat.<init>(Unknown Source) ~[?:?]
        at com.Zrips.CMI.Modules.Economy.EconomyManager.getMoneyFormat(EconomyManager.java:369) ~[?:?]
        at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.format(CMIEconomyAcount.java:191) ~[?:?]
        at com.Zrips.CMI.Modules.Economy.CMIEconomyAcount.getFormatedBalance(CMIEconomyAcount.java:172) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getFormatedBalance(CMIUser.java:1998) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getFormatedBalance(CMIUser.java:1990) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getFormatedBalance(CMIUser.java:1982) ~[?:?]
        at com.Zrips.CMI.commands.list.balance.perform(balance.java:41) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-259]
        ... 19 more`

**Comment by MrPranklez** [comment]
I think it's an issue with the money format what format do you use? @CloudeLecaw

**Comment by MrPranklez** [comment]
Yup that's what it was, regenerated the files on a test server and the format below is what i had to use but in the error you can tell it's something different for some reason. Probably changed at some point but i forgot to update.

`MoneyFormat: '###,##0.00'`

Recompiled version of vault works just fine.

**Comment by CloudeLecaw** [comment]
we are using


`MoneyFormat: '###,###.00'`
