### ISSUE TITLE
Some Error

### ISSUE THREAD

**Issue by EPGMooky** [Zrips/CMI#4531]
**Description of issue:**
Hi, i have another error. Now its just little thing.
Thanks for respond.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:38:50 WARN]: [CMI] Task #1014854 for CMI v8.7.10.0 generated an exception
java.lang.ClassCastException: net.minecraft.server.v1_16_R3.DataWatcher cannot be cast to net.minecraft.server.v1_16_R3.EntityArmorStand
        at com.Zrips.CMI.NBT.v1_16_R3.updateHologram(v1_16_R3.java:1511) ~[?:?]
        at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:897) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```
---

**Cmi Version (using`/cmi version`):** 
CMI v8.7.10.0
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
git-Paper-261 (MC: 1.16.4)

**Comment by titidelaff** [comment]
same for me

**Comment by Zrips** [comment]
Could one of you provide hologram and its settings which causes this issue? Trying to reproduce it, but everything seams to be working in my setup, so you might have something special which creates this issue in particular

**Comment by Zrips** [comment]
Will issue fix which will stop this error from appearing, tho it would still be interesting to reproduce it just to know why exactly it failed in your situations.
