### ISSUE TITLE
[ERROR] Could not pass event CMIPvEStartEventAsync to CMI v8.7.9.3

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#4533]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[ERROR] Could not pass event CMIPvEStartEventAsync to CMI v8.7.9.3
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[server.jar:git-Paper-1594]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-Paper-1594]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1594]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[server.jar:git-Paper-1594]
at com.Zrips.CMI.Modules.PlayerCombat.PlayerCombatManager$4.run(PlayerCombatManager.java:408) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[server.jar:git-Paper-1594]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[server.jar:git-Paper-1594]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-1594]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.IllegalStateException: Asynchronous player tracker update!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:352) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:219) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.EntityPlayer.G(EntityPlayer.java:1361) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.EntityPlayer.updateAbilities(EntityPlayer.java:1206) ~[server.jar:git-Paper-1594]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setAllowFlight(CraftPlayer.java:1476) ~[server.jar:git-Paper-1594]
at com.Zrips.CMI.Modules.PlayerCombat.PlayerCombatListener.CMIPvPStartEventAsync(PlayerCombatListener.java:113) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor534.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[server.jar:git-Paper-1594]
... 10 more
```

**Cmi Version (using`/cmi version`):** CMI: 8.7.9.3 BungeeCord SqLite-> 8.7.10.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-1594 (MC: 1.12.2)

**Comment by CloudeLecaw** [comment]
can u retty with 8.7.10.0¿

**Comment by Zrips** [comment]
Will be fixed with next build
