### ISSUE TITLE
Missing chatRooms.yml

### ISSUE THREAD

**Issue by Androkai** [Zrips/CMI#4538]
**Description of issue:**
Updated my server to 1.16.4 and CMI to 8.7.10.1 a moment ago and got an error at server startup about chatRooms.yml not available.

---

**ERROR:**
```
[Server thread/WARN]: java.io.FileNotFoundException: plugins/CMI/chatRooms.yml (No such file or directory)
[Server thread/WARN]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[Server thread/WARN]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
[Server thread/WARN]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:126)
[Server thread/WARN]: 	at com.Zrips.CMI.FileHandler.ConfigReader.load(ConfigReader.java:48)
[Server thread/WARN]: 	at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.load(ChatFormatManager.java:692)
[Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1415)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
---

**Cmi Version (using`/cmi version`):** 8.7.10.1

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-261 (MC: 1.16.4)

**Comment by EkonC** [comment]
It is not an error but a warning. Same for me though - the plugin probably doesn't create the missing yml file on its start.

**Comment by mrfloris** [comment]
https://www.spigotmc.org/resources/cmi-270-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much-more.3742/

`.2` fixes this warning message.
