### ISSUE TITLE
[WARN] java.lang.NullPointerException

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#4546]
**ERROR**
```
19:23:52[WARN] java.lang.NullPointerException
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthItem.<init>(WorthItem.java:29)
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:212)
19:23:52[WARN] at com.Zrips.CMI.Config.reload(Config.java:2515)
19:23:52[WARN]
at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
19:23:52[WARN] at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340)
19:23:52[WARN]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19:23:52[WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
19:23:52[WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
19:23:52[WARN] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19:23:52[WARN] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
19:23:52[WARN] at java.lang.Thread.run(Thread.java:748)
19:23:52[INFO] [CMI] Failed to load worth for: BREWING_STAND>0
19:23:52[WARN] java.lang.NullPointerException
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthItem.<init>(WorthItem.java:29)
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:212)
19:23:52[WARN] at com.Zrips.CMI.Config.reload(Config.java:2515)
19:23:52[WARN] at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
19:23:52[WARN] at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340)
19:23:52[WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19:23:52[WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
19:23:52[WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
19:23:52[WARN] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19:23:52[WARN]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
19:23:52[WARN]
at java.lang.Thread.run(Thread.java:748)
19:23:52[INFO] [CMI] Failed to load worth for: CARROT>0
19:23:52[INFO] [CMI] Can't load worth value for FIREWORK>0
19:23:52[WARN] java.lang.NullPointerException
19:23:52[WARN] at com.Zrips.CMI.Modules.CmiItems.ItemManager.getItem(ItemManager.java:472)
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:129)
19:23:52[WARN] at com.Zrips.CMI.Config.reload(Config.java:2515)
19:23:52[WARN] at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
19:23:52[WARN] at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340)
19:23:52[WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19:23:52[WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
19:23:52[WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
19:23:52[WARN] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19:23:52[WARN] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
19:23:52[WARN] at java.lang.Thread.run(Thread.java:748)
19:23:52[INFO] [CMI] Failed to load worth for: LAVA>0
19:23:52[WARN] java.lang.NullPointerException
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthItem.<init>(WorthItem.java:29)
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:212)
19:23:52[WARN] at com.Zrips.CMI.Config.reload(Config.java:2515)
19:23:52[WARN] at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
19:23:52[WARN] at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340)
19:23:52[WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19:23:52[WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
19:23:52[WARN]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
19:23:52[WARN] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19:23:52[WARN]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
19:23:52[WARN]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
19:23:52[WARN] at java.lang.Thread.run(Thread.java:748)
19:23:52[INFO] [CMI] Failed to load worth for: WOODEN_DOOR>0
19:23:52[INFO] [CMI] Can't load worth value for WOOD_BUTTON>0
19:23:52[INFO] [CMI] Can't load worth value for WOOD>0
19:23:52[INFO] [CMI] Can't load worth value for WOOD_PLATE>0
19:23:52[INFO] [CMI] Can't load worth value for SAPLING>0
19:23:52[WARN] java.lang.NullPointerException
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthItem.<init>(WorthItem.java:29)
19:23:52[WARN] at com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:212)
19:23:52[WARN] at com.Zrips.CMI.Config.reload(Config.java:2515)
19:23:52[WARN] at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
19:23:52[WARN] at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340)
19:23:52[WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19:23:52[WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
19:23:52[WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
19:23:52[WARN] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
19:23:52[WARN] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
19:23:52[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
19:23:52[WARN] at java.lang.Thread.run(Thread.java:748)
19:23:52[INFO] [CMI] Failed to load worth for: POTATO>0
```

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.10.2 BungeeCord SqLite

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-1594 (MC: 1.12.2)

**Comment by Zrips** [comment]
Will fix some of them but you will need to rename "POTATO" into "POTATO_ITEM" and "CARROT" into "CARROT_ITEM" due to old material names not wanting to be friends.
