### ISSUE TITLE
error on worth manager?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4560]
```
>.... [22:31:43 INFO]: [CMI] Loaded (72) interactive commands into memory. Took 5ms
>.... [22:31:43 WARN]: java.lang.NullPointerException
>.... [22:31:43 WARN]: at com.Zrips.CMI.Modules.Worth.WorthItem.<init>(WorthItem.java:29)
>.... [22:31:43 WARN]: at com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:212)
>.... [22:31:43 WARN]: at com.Zrips.CMI.Config.reload(Config.java:2515)
>.... [22:31:43 WARN]: at com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
>.... [22:31:43 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340)
>.... [22:31:43 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
>.... [22:31:43 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [22:31:43 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1265)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
>.... [22:31:43 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [22:31:43 WARN]: at java.lang.Thread.run(Thread.java:748)
>.... [22:31:43 INFO]: [CMI] Failed to load worth for: carrotitem
>.... [22:31:43 INFO]: [CMI] Loaded (240) worth values into memory. Took 4ms
```

![Snag_be05977](https://user-images.githubusercontent.com/12080017/98484854-93d68f80-2212-11eb-9bc2-fa16e6440878.png)

**Comment by CloudeLecaw** [comment]
I deleted the carrotitem from worth.yml and reloaded.
This seem to fix the issue
