### ISSUE TITLE
[ERROR] Could not pass event BlockBreakEvent to CMI v8.7.10.2

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#4566]
**ERROR**
```
[ERROR] Could not pass event BlockBreakEvent to CMI v8.7.10.2
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[server.jar:git-Paper-1594]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[server.jar:git-Paper-1594]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Paper-1594]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:322) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:221) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:934) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[server.jar:git-Paper-1594]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_265]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_265]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[server.jar:git-Paper-1594]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[server.jar:git-Paper-1594]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.Modules.Animations.AnimationSitListener.BlockBreakEvent(AnimationSitListener.java:104) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor711.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[server.jar:git-Paper-1594]
... 17 more
```

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.10.2 BungeeCord SqLite-> 8.7.10.3

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-1594 (MC: 1.12.2)

**Comment by Zrips** [comment]
Will get fixed.
