### ISSUE TITLE
CMIPlayerNickNameChangeEvent is missing the static handlers getter

### ISSUE THREAD

**Issue by sgdc3** [Zrips/CMI#4622]
The CMIPlayerNickNameChangeEvent is missing the static getHandlersList method.

```
[19:57:03 ERROR]: Error occurred while enabling FearNickname v1.0-SNAPSHOT (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event com.Zrips.CMI.events.CMIPlayerNickNameChangeEvent. Static getHandlerList method required!
        at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:703) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:640) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at it.feargames.fearnickname.FearNickname.onEnable(FearNickname.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:764) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:425) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:392) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1278) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Yatopia-"94afff9"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by CloudeLecaw** [comment]
This more looks like annissue if your Plugin FearNickName.
Have you tried tobreload it with Plugman?

**Comment by sgdc3** [comment]
Not at all, the issue is still present even if I perform a server restart.

**Comment by CloudeLecaw** [comment]
But this issue can also be fixed from the dev of FearNickname....

**Comment by sgdc3** [comment]
It's me...

**Comment by sgdc3** [comment]
No this is an issue in the CMI's source files

**Comment by sgdc3** [comment]
@Zrips bump

**Comment by LogGits** [comment]
Should be fixed in the next update, stay tuned :)
