### ISSUE TITLE
Error executing task on Client

### ISSUE THREAD

**Issue by J0schlZ** [Zrips/CMI#4644]
**Description of issue:**

I found this in my error log and it seems like it was caused by CMI.
https://craft-together.de/~irgendsoeintyp/MinecraftLauncher_2020-11-21_18-23-45.png

---

**ERROR:**
```

Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'CMINP170'.
	at net.minecraft.class_269.method_1157(class_269.java:236)
	at net.minecraft.class_634.method_11099(class_634.java:2151)
	at net.minecraft.class_2755.method_11860(class_2755.java:122)
	at net.minecraft.class_2755.method_11054(class_2755.java:16)
	at net.minecraft.class_2600.lambda$checkThreadAndEnqueue$0(class_2600.java:34)
	at net.minecraft.class_2600$$Lambda$3642/625219543.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:172)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:134)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1015)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
https://paste.craft-together.de/ditocizize
```

---

**Cmi Version (using`/cmi version`):** 
https://craft-together.de/~irgendsoeintyp/2020-11-21_18-20-30.png

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
https://craft-together.de/~irgendsoeintyp/javaw_2020-11-21_18-20-58.png

**Comment by Zrips** [comment]
What plugins do you have which could be related to player teams? Some nametag plugins? Scoreboard plugin? It is some what from CMI, but it looks to be more like a 3rd party plugin issue
