### ISSUE TITLE
Ride warn

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#4653]
**ERROR**
```
18:26:39[INFO] Ijar0 issued server command: /ride
18:26:43[INFO] Ijar0 issued server command: /ride
18:26:43[WARN] java.lang.NoSuchMethodError: org.bukkit.entity.Slime.setInvisible(Z)V
18:26:43[WARN] at com.Zrips.CMI.commands.list.ride.perform(ride.java:79)
18:26:43[WARN] at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340)
18:26:43[WARN] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
18:26:43[WARN] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
18:26:43[WARN] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
18:26:43[WARN] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18:26:43[WARN] at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
18:26:43[WARN] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
18:26:43[WARN] at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** CMI: 8.7.10.8 BungeeCord SqLite

**Server Type (Spigot/Paperspigot/etc):** PaperSpigot

**Server Version (using `/ver`):** git-Paper-1594 (MC: 1.12.2)

**Comment by Zrips** [comment]
Should be fixed with next version
