### ISSUE TITLE
Error PlaceHolder like "{#12FF77>}{#12FF77<>}{#0FD8B6<}" withe FeatherBoard

### ISSUE THREAD

**Issue by Teyir** [Zrips/CMI#4661]
**Description of issue:**

When I set this type of color for my tablist.yml settings `{#12FF77>}{#12FF77<>}{#0FD8B6<}` I have an error withe the plugin Featherboard when a player join the server.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[FeatherBoard] Error in placeholder: {#12ff77>}
[FeatherBoard] java.lang.IllegalArgumentException: Could not parse ChatColor #12FF77>
at net.md_5.bungee.api.ChatColor.of(ChatColor.java:273)
at be.maximvdw.placeholdercore.placeholders.ColorPlaceholderPack$1.getResult(ColorPlaceholderPack.java:30)
at be.maximvdw.placeholdercore.placeholders.ColorPlaceholderPack$1.getResult(ColorPlaceholderPack.java:26)
at be.maximvdw.placeholderapi.internal.PlaceholderReplacer.getResult(PlaceholderReplacer.java:67)
at be.maximvdw.featherboard.dk.a(dk.java:45)
at be.maximvdw.featherboard.dk.a(dk.java:174)
at be.maximvdw.featherboard.dk.a(dk.java:41)
at be.maximvdw.featherboard.dk.getPlaceholderResult(dk.java:213)
at be.maximvdw.placeholderapi.PlaceholderAPI.replacePlaceholders(PlaceholderAPI.java:103)
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:577)
at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:491)
at com.Zrips.CMI.Modules.TabList.TabListManager$6.run(TabListManager.java:768)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

**tablist.yml**
```
    PlayerName: '%luckperms_prefix_element_highest_on_track_grades% [playerDisplayName]'
    Header:
      '1':
      - '  {#5ACDAA}&m  ] {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m
        [ &r  '
      - '&r'
      - ' &r   {#12FF77>}{#12FF77<>}Sky-Dream{#0FD8B6<}   '
      - ''
      - '{#12FF77>}{#12AEDC<>}Joueurs en ligne{#29F0D2<} {#C74968}%server_online%'
      - '&r'
      - '{#12FF77>}{#5A64CD<>}&m══════════{#AA5ACD<}'
    Footer:
      '1':
      - '{#12FF77>}{#AA5ACD<>}&m══════════{#5A64CD<}'
      - '&r'
      - '{#12DC70}Nombre d''îles {#12AEDC}%bskyblock_world_islands%&r  &7|  {#12DC70}Joueurs
        {#12AEDC}%server_unique_joins%&r  &7|  {#12DC70}Grade {#12AEDC}%luckperms_prefix_element_highest_on_track_grades%'
      - '&r'
      - '  {#5ACDAA}&m  ] {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m   {#77CD5A}&m   {#5ACDAA}&m
        [ &r  '
```

---

**Cmi Version (using`/cmi version`):** 8.7.11.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-252 (MC: 1.16.3)

**Relevant plugins (Delete if this isn't needed):**
Featherboard 4.29.0
PlaceHolderAPI 2.10.9
MVdWPlaceholderAPI

Thank you very much

**Comment by Zrips** [comment]
Not a CMI bug in particular. FeatherBoard passes over hex color code over spigot color parser which fails to process it. FeatherBoard needs to take correct hex color code, no idea why its including last special symbol as > while it needs to only take 6 symbols after #. So ether avoid using gradient color codes or inform FeatherBoard about this issue and its developer can fix it in no time on his end.
