### ISSUE TITLE
cmi se 5 creates error in console

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4676]
```
>.... [02:16:37 ERROR]: Exception when Cloude_Lecaw attempted to tab complete cmi se 5
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/cmi se 5 ' in plugin CMI v8.7.11.1
at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[patched_1.16.4.jar:git-Paper-300]
at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.16.4.jar:git-Paper-300]
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.16.4.jar:git-Paper-300]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabCompleteCommand(CraftServer.java:1905) ~[patched_1.16.4.jar:git-Paper-300]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.tabComplete(CraftServer.java:1877) ~[patched_1.16.4.jar:git-Paper-300]
at org.bukkit.craftbukkit.v1_16_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.16.4.jar:git-Paper-300]
at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.16.4.jar:git-Paper-300]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:596) ~[patched_1.16.4.jar:git-Paper-300]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:633) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1131) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1124) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1085) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-300]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-300]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
at org.bukkit.craftbukkit.v1_16_R3.block.CraftSign.getLine(CraftSign.java:44) ~[patched_1.16.4.jar:git-Paper-300]
at com.Zrips.CMI.TabComplete.getByAction(TabComplete.java:567) ~[?:?]
at com.Zrips.CMI.TabComplete.get(TabComplete.java:454) ~[?:?]
at com.Zrips.CMI.TabComplete.onTabComplete(TabComplete.java:85) ~[?:?]
at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[patched_1.16.4.jar:git-Paper-300]
... 20 more
```
i know i sign cant have 5 lines but it happens fast u push 5 instead of 4.....
there should be no big error in console line that.
![Snag_8c92fde](https://user-images.githubusercontent.com/12080017/100951647-41397c00-350f-11eb-9723-cf33b7409407.png)

**Comment by Zrips** [comment]
Will be fixed with next build
