### ISSUE TITLE
Lag command exception

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4693]
**Description of issue:**

---
Hi, when using /lag command I got this exception.
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:20:03] [Server thread/INFO]: Renzotom issued server command: /lag
[20:20:03] [Craft Scheduler Thread - 2259/WARN]: [CMI] Plugin CMI v8.7.11.2 generated an exception while executing task 26752355
java.lang.SecurityException: read permission error: /
	at com.hicoria.javaSandBox.Main$CustomSecurityManager.checkRead(Main.java:384) ~[sdb:?]
	at java.io.File.getTotalSpace(File.java:1801) ~[?:1.8.0_171]
	at com.Zrips.CMI.commands.list.status$1$2$1.run(status.java:177) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-298]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-298]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-298]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

---

**Cmi Version (using`/cmi version`):** 8.7.11.

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 298

**Comment by Zrips** [comment]
Interesting issue. Seams that plugin failed to check general storage capacity due to blocked action. Will make some changes to avoid this error, tho due to this limitation we cant get storage capacity. but everything else will be shown properly.
