### ISSUE TITLE
Player can't join, he is stucked in boat, and can't be kicked

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4694]
**Description of issue:**

---
Hi, when was player in boat, and the server was lagging due to pregenerating map, he got kicked, but he still stayed in boat and was "online" even when he wasn't. And then when he tried to connect, this error appeared.
![image](https://user-images.githubusercontent.com/18662086/101227534-7ae9be80-3698-11eb-8a25-db2763fba2a9.png)

![image](https://user-images.githubusercontent.com/18662086/101227537-7b825500-3698-11eb-9f76-195321281f68.png)

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[01:11:26] [Server thread/WARN]: [CMI] Task #3002826 for CMI v8.7.11.2 generated an exception
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_16_R3.changeGameModePlayerSide(v1_16_R3.java:1318) ~[?:?]
	at com.Zrips.CMI.AllListeners.WorldLimits$1.run(WorldLimits.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[01:11:30] [Server thread/INFO]: Anticheat »  Ciiba failed VehicleMorePackets: sent too many moves (Packets/VL 36)
```

---

**Cmi Version (using`/cmi version`):** 8.7.11.

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 298

**Comment by Zrips** [comment]
Will be fixed with next build
