### ISSUE TITLE
Give error?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4716]
**Description of issue:**

---

HI, I'm getting this error when using /give cmd, it didn't happen before, maye it's caused by multiple reloads.
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:32:31] [Server thread/INFO]: Renzotom issued server command: /give renzotom pickaxe
[20:32:31] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.11.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-312]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2008) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1819) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1772) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-312]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-312]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.CmiItems.ItemManager.getItem(ItemManager.java:243) ~[?:?]
	at com.Zrips.CMI.commands.list.give.perform(give.java:322) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-312]
	... 19 more
```

---

**Cmi Version (using`/cmi version`):** 8.7.11.2

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 298

**Comment by mercurialmusic** [comment]
I'm not sure if this used to work differently, but typically you need to provide the type of pickaxe, e.g. stone_pickaxe or diamond_pickaxe. The ambiguity might be what is causing the error.

**Comment by bobhenl** [comment]
Yeah but this error probably shouldn't happen

**Comment by Zrips** [comment]
Both are right, this error should not happen. If any command outputs any errors, we need to resolve that. But yea, it needs to specify pickaxe type to get correct one. 
In any case, will be fixed with next build.
