### ISSUE TITLE
Error when using custom alias + give cmd

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4740]
**Description of issue:**

EDIT: This has broken in the latest update, before it worked I think.
---
Hi, I'm getting these two errors when I'm using whole custom alias or just mentioned give cmd.
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:21:36] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.7.11.3
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.11.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:749) ~[patched_1.16.4.jar:git-Paper-320]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:877) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:839) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:577) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:573) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:155) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor687.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-320]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1998) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1817) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1770) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.commands.list.give.perform(give.java:135) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-320]
	... 32 more
```
When using just give from custom alias
```
cmi give <player_name> diamond_sword{display:{Name:'[{"text":"Nezničitelný meč","italic":false,"color":"dark_aqua"}]',Lore ['[{"text":"Eventová odměna","italic":false,"underlined":true,"color":"dark_red"}]']},Unbreakable:1} 1
```
I get this error:
```
[19:25:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.11.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-320]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2006) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1817) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1770) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.4.jar:git-Paper-320]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.commands.list.give.perform(give.java:135) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-320]
	... 19 more
```
And it worked few days ago...

Custom alias to give random reward from event
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  eventodmenalehci:
    Cmds:
    - 'check:$1==null! asConsole! cmi ctellraw [playerName] <T>&eVyužití: &6/eventodmenalehci
      &f<jméno_hráče></T><SC>/eventodmenalehci </SC>'
    - check:$1!=null#! cooldown:5?#! asConsole! cmi ctellraw [playerName] <T>&c&lEventy &f» &fDal jsi
      odměnu za event hráči $1.</T>
    - 'asConsole! cmi ctellraw $1 <T>&c&lEventy &f» &fZa výhru v eventu jsi získal
      &e&l%cmi_random_1_5%. &fz &e&l5 &fodměn.</T>'
    - asConsole! cmi give $1 diamond_sword{display:{Name:'[{"text":"Nezničitelný #tried to remove check to test if it works without check, cause previous parts worked
      meč","italic":false,"color":"dark_aqua"}]',Lore:['[{"text":"Eventová odměna","italic":false,"underlined":true,"color":"dark_red"}]']},Unbreakable:1}
      1
    - check:%cmi_lastrandom_[playerName]%==2! asConsole! cmi give $1 golden_sword{Damage:33,RepairCost:10,display:{Name:'[{"text":"Meč
      s kořistí na jeden zásah","italic":false,"color":"dark_aqua"}]',Lore:['[{"text":"Eventová
      odměna","italic":false,"underlined":true,"color":"dark_red"}]']},Enchantments:[{id:looting,lvl:6},{id:sharpness,lvl:20}]}
      1
    - check:%cmi_lastrandom_[playerName]%==3! asConsole! cmi give $1 enchanted_golden_apple{Damage:32,display:{Lore:['[{"text":"Eventová
      odměna","italic":false,"color":"dark_red","underlined":true}]']}} 5
    - check:%cmi_lastrandom_[playerName]%==4! asConsole! cmi give $1 minecraft:potion{CustomPotionEffects:[{Id:3,Amplifier:1,Duration:1200}],CustomPotionColor:16170240,display:{Name:"\"Lektvar
      spěchu\"",Lore:["Eventová odměna"]}}
    - check:%cmi_lastrandom_[playerName]%==5! asConsole! cmi give $1 wooden_sword{RepairCost:10,display:{Name:'[{"text":"Ostrý
      meč","italic":false}]',Lore:['[{"text":"Eventová odměna","italic":false,"color":"dark_red","underlined":true}]']},Enchantments:[{id:sharpness,lvl:10}]}
      1
    Perm: true
```

---

**Cmi Version (using`/cmi version`):** 8.7.11.3

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.4, 320

**Comment by bobhenl** [comment]
Same for /cmi give Renzotom enchanted_book {StoredEnchantments:[{id:Mending,lvl:1}]} 1

**Comment by WolverStones** [comment]
Same if use command: 

`/cmi give %player_name% bow{CustomModelData:10} n &b&lARCHER_KING_BOW l &f l &f&lEXKLUZIVNÍ l &bK_dispozici_pouze_prostřednictvím l &bArcher_King_Loot_crate._/bosses l &f l &eZískej_vajíčka_bossů_@_&nstore.northville.cz e ARROW_FIRE:2 e ARROW_INFINITE:1 e ARROW_DAMAGE:6 e ARROW_KNOCKBACK:2 e unbreaking:7`

**Comment by Zrips** [comment]
Gets a fix with next update
