### ISSUE TITLE
NullPointerException at startup

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#4744]
**Description of issue:**
At boot I get a NullPointerException when CMI is loading.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:32:40] [Server thread/INFO]:   Loaded (183914) player data into memory. Took 4094ms
[10:32:42] [Server thread/INFO]:   Loaded (353105) playtime records into memory. Took 1960ms
[10:32:42] [Server thread/INFO]:   Loaded (0) playtime reward records into memory. Took 1ms
[10:32:42] [Server thread/INFO]:   Loaded (15) custom alias into memory. Took 10ms
[10:32:42] [Server thread/INFO]:   Found dynmap
[10:32:42] [Server thread/INFO]:   Registered events. Took 83ms
[10:32:42] [Server thread/INFO]:   Loaded (0) event action commands into memory. Took 2ms
[10:32:42] [Server thread/INFO]:   Updated (EN) language file. Took 87ms
[10:32:42] [Server thread/WARN]: java.lang.NullPointerException
[10:32:42] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Worth.WorthItem.<init>(WorthItem.java:29)
[10:32:42] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:212)
[10:32:42] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1598)
[10:32:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:32:42] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:32:42] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:32:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:32:42] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:32:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:32:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:32:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:32:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:32:42] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:32:42] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[10:32:42] [Server thread/INFO]:   Failed to load worth for: CARROT>0
[10:32:42] [Server thread/INFO]:   Can't load worth value for WOOD_BUTTON>0
[10:32:42] [Server thread/INFO]:   Can't load worth value for WOOD_PLATE>0
[10:32:42] [Server thread/INFO]:   Loaded (247) worth values into memory. Took 7ms
```

---

**Cmi Version (using`/cmi version`):** 8.7.11.3 MySQL

**Server Type (Spigot/Paperspigot/etc):** paper 1.12.2

**Comment by Zrips** [comment]
You will need to update your worth file value set for CARROT>0 into CARROT
Will make some changes to avoid this scary error
