### ISSUE TITLE
certain chat message just does not work.

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#4751]
**Description of issue:**
sending the message ```have you been kicked for "Internal Exception: io.netty.handler.timeout.ReadTimeoutException" in the past week/week and a half?``` dosent work. it does not work when you try to /msg it to someone else either.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[04:30:12] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[04:30:12] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
[04:30:12] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:30:12] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[04:30:12] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:111)
[04:30:12] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:586)
[04:30:12] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:568)
[04:30:12] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.NickName.NickNameListener$1.run(NickNameListener.java:183)
[04:30:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[04:30:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1358)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1271)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1003)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[04:30:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[04:30:12] [Server thread/WARN]: Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1020 path $[3].clickEvent.value
[04:30:12] [Server thread/WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:60)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChatDeserializer.a(SourceFile:493)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.ChatDeserializer.a(SourceFile:517)
[04:30:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IChatBaseComponent$ChatSerializer.a(IChatBaseComponent.java:359)
[04:30:12] [Server thread/WARN]: 	... 15 more
[04:30:12] [Server thread/WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 1020 path $[3].clickEvent.value
[04:30:12] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:738)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
[04:30:12] [Server thread/WARN]: 	at com.google.gson.internal.Streams.parse(Streams.java:48)
[04:30:12] [Server thread/WARN]: 	... 19 more
[04:30:12] [Server thread/INFO]: [CMI] Failed to show json message with packets, using command approach
[04:30:12] [Server thread/INFO]: Invalid chat component: Unterminated object at line 1 column 1020 path $[3].clickEvent.value
[04:30:12] [Server thread/INFO]: ...ahCookie" ["",{"text":"","extra":[{"color":"dark_gray","text":"["},{"color":"dark_purple","text":"Staff"},{"color":"dark_gray","text":"] "},{"color":"aqua","text":"Sarah"},{"color":"gold","text":"C"},{"color":"dark_gray","text":"o"},{"color":"gold","text":"o"},{"color":"dark_gray","text":"k"},{"color":"gold","text":"i"},{"color":"dark_gray","text":"e"},{"color":"gray","text":": "},{"text":""}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"color":"yellow","text":"Sent time: "},{"color":"gold","text":"04:30:12"}]}},"clickEvent":{"action":"suggest_command","value":"\/msg SarahCookie "}},{"text":"","extra":[{"text":"have you been kicked for \"Internal Exception: "}]},{"text":"","extra":[{"color":"dark_red","text":"["},{"color":"gray","text":"LINK"},{"color":"dark_red","text":"]"}],"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"io.netty.handler.timeout.ReadTimeoutException\""}]}},"clickEvent":{"action":"open_url","value":"http://io.netty.handler.timeout.ReadTimeoutException""}},{"text":"","extra":[{"text":"\" in the past week\/week and a half?"}]}]<--[HERE]
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.7.11.1

**Server Type (Spigot/Paperspigot/etc):** 
Tuinity, a paper fork --> https://github.com/Spottedleaf/Tuinity

**Server Version (using `/ver`):** 
 Tuinity version git-Tuinity-"8056d13" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will fix issue in general, but you might want to update your LinkRegex in config file to new format like 
`(?i)((http|https|ftp|ftps)\:\/\/|www\.)(\w*\.)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\S*)` which is some what more accurate in detecting url's
