### ISSUE TITLE
Give command for enchanted book not working

### ISSUE THREAD

**Issue by Threshian** [Zrips/CMI#4753]
**Description of issue:**

Since the last update, no more give commands with enchanted books are working. The books are not given and there is an error in the console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.12.0
[09:57:38] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
[09:57:38] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[09:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[09:57:38] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:749)
[09:57:38] [Server thread/WARN]: 	at io.izzel.taboolib.util.Features.dispatchCommand(Features.java:179)
[09:57:38] [Server thread/WARN]: 	at me.arasple.mc.trmenu.api.action.impl.ActionCommandConsole$onExecute$1$1.run(ActionCommandConsole.kt:17)
[09:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[09:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[09:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[09:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[09:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[09:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[09:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[09:57:38] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[09:57:38] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[09:57:38] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.give.perform(give.java:135)
[09:57:38] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:339)
[09:57:38] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:57:38] [Server thread/WARN]: 	... 13 more

[09:59:41] [Server thread/INFO]: Threshian_ issued server command: /give threshian_ enchanted_book{StoredEnchantments:[{id:mending,lvl:1}]} 1
[09:59:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.12.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-251]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-251]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.commands.list.give.perform(give.java:135) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:339) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-251]
	... 18 more
```

---

**Cmi Version (using`/cmi version`):** 
CMI v8.7.12.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
[1.16.3]

**Comment by Zrips** [comment]
Will be fixed with todays update

**Comment by Threshian** [comment]
Thanks, you are great !
