### ISSUE TITLE
HELP ME

### ISSUE THREAD

**Issue by DreamMiu** [Zrips/CMI#4757]
**Description of issue:**
8.7.12.0 is very bad, a lot of bugs, ordinary paper also turned into a check, give also appeared a lot of bugs, unable to give enchanted items
######################
######################
```
[11:18:43 INFO]: [Yum] [Yum command monitoring] Player China_Miu executes the CMI plug-in cmi give @p minecraft:diamond_sword 1 0 {ench:[{id:16,lvl:5},{id:22, lvl:3}]) An exception occurred during the command!
[11:18:43 INFO]: [Yum] Exception name: java.lang.NullPointerException
[11:18:43 INFO]: [Yum] Exception description: null
[11:18:43 INFO]: [Yum] The simple error message is as follows:
[11:18:43 INFO]: [Yum] is located at com.Zrips.CMI.commands.list.give.perform(give.java:135)
[11:18:43 INFO]: [Yum] is located at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:339)
[11:18:43 INFO]: [Yum] is located at pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)
[11:18:43 INFO]: [Yum] is located at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:18:43 INFO]: [Yum] is located at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
```
**Cmi Version (using`/cmi version`):** 
8.7.12.0
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
1.16.4-R0.1-SNAPSHOT

**Comment by DreamMiu** [comment]
I tried to return to version 8.7.11.3 and the same problem occurred, only 8.7.11.2 was normal and error-free

**Comment by Zrips** [comment]
Sorry for inconvenience, will post new version today with a fix for it
