### ISSUE TITLE
Hologram does't works

### ISSUE THREAD

**Issue by gethertv** [Zrips/CMI#4818]
Cant create hologram

`[19:08:19] [Server thread/INFO]: GetherTV issued server command: /hologram new gethertv
[19:08:19] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.12.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:758) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1788) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1631) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1584) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:941) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[server.jar:git-Spigot-37d799b-3eb7236]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-37d799b-3eb7236]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.IllegalStateException: zip file closed
at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686) ~[?:1.8.0_202]
at java.util.zip.ZipFile.getEntry(ZipFile.java:315) ~[?:1.8.0_202]
at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_202]
at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_202]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:202) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[server.jar:git-Spigot-37d799b-3eb7236]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server.jar:git-Spigot-37d799b-3eb7236]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
at com.Zrips.CMI.commands.list.hologram.perform(hologram.java:110) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:339) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-37d799b-3eb7236]
... 19 more`

**Comment by Zrips** [comment]
Seams to be issue with plugin load, you might have replaced original plugin jar file and dint performed server restart which caused this issue. Avoid updating plugin jar files during server run.
