### ISSUE TITLE
Error in console (unknown), probably with schedules

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4832]
**Description of issue:**

---

Hi, this error appeared don't know why, but happened multiple times few seconds after previous.
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:06:56] [Server thread/WARN]: [CMI] Task #29583275 for CMI v8.7.12.4 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.7.12.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-351]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-351]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-351]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:492) ~[patched_1.16.4.jar:git-Paper-351]
	at com.Zrips.CMI.utils.Util.performCommand(Util.java:475) ~[?:?]
	at com.Zrips.CMI.Modules.GUI.GUIManager$1.run(GUIManager.java:184) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-351]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-351]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.4.jar:git-Paper-351]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-351]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-351]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-351]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-351]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.fillFields(SavedInventoryManager.java:511) ~[?:?]
	at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.openSavedInv(SavedInventoryManager.java:601) ~[?:?]
	at com.Zrips.CMI.commands.list.invcheck.perform(invcheck.java:69) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:339) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-351]
	... 13 more
```

**Cmi Version (using`/cmi version`):** 8.7.12.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 352

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Relating to saved inventory in a world which no longer exists. Should be fixed with next build
