### ISSUE TITLE
cmi anvil causes server crash and cmi ver produce errors

### ISSUE THREAD

**Issue by blacksythe** [Zrips/CMI#4838]
**Description of issue:**
run command "CMI anvil" server crash's

run cmi version and this error appears
[CMI]: Plugin CMI v8.7.12.4 generated an exception while executing task 241
Console 21:15:16
java.lang.ArrayIndexOutOfBoundsException: 1
at com.Zrips.CMI.commands.list.version$1.run(version.java:45) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[CraftTask.class:5bff736]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:5bff736]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:5bff736]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

[crash-2020-12-31_15.07.47-server.txt](https://github.com/Zrips/CMI/files/5758282/crash-2020-12-31_15.07.47-server.txt)
---

**Cmi Version (using`/cmi version`):** 
v8.7.12.4
(updating to new version as of this post)

**Server Type (Spigot/Paperspigot/etc):** 
Magma Hybrid
running tekkit reloaded modpack

**Server Version (using `/ver`):** 

This server is running Magma version 5bff736 (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge Version 14.23.5.2854)

**Comment by Zrips** [comment]
I can fix /version command, but without actual error log what happen when running /anvil i cant resolve that one. And just side note, CMI isint built for modded servers as it was mentioned on plugin page, so you can encounter issues as it never been made to work on servers like that.

**Comment by blacksythe** [comment]
[error log.txt](https://github.com/Zrips/CMI/files/5762717/error.log.txt)
1 error log

Just in case ;)
