### ISSUE TITLE
救命！

### ISSUE THREAD

**Issue by wkurumi** [Zrips/CMI#4840]
**Description of issue:**
抱歉，我的英语不好，破坏任何mod方块CMI都会报错。

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```[23:13:58] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerInteractEvent to CMI v8.7.12.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.4-1.0.10-d46a39d] {re:mixin,re:classloading}
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.4-1.0.10-d46a39d] {re:mixin,re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.4-1.0.10-d46a39d] {re:mixin,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactoryMixin.java:483) ~[arclight:arclight-1.16.4-1.0.10-d46a39d] {re:mixin,re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactoryMixin.java:450) ~[arclight:arclight-1.16.4-1.0.10-d46a39d] {re:mixin,re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManagerMixin.java:603) ~[?:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:mixins.arclight.core.json:server.management.PlayerInteractionManagerMixin,pl:mixin:A,re:mixin}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandlerMixin.java:2169) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.play.ServerPlayNetHandlerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.network.PacketThreadUtil.mda7eb43$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.PacketThreadUtilMixin,pl:mixin:A}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading,re:mixin}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:733) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:716) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:710) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1898) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.SpawnerCharge.SpawnerActionsListener.onPlayerInteractEvent(SpawnerActionsListener.java:62) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        ... 23 more

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
#######################################
```

---

**Cmi Version (using`/cmi version`):*8.7.12.5* 

**Server Type (Spigot/Paperspigot/etc):*Arclight* 

**Server Version (using `/ver`):*1.16.4* 
![QQ图片20210102000729](https://user-images.githubusercontent.com/63358787/103442142-8677d780-4c8e-11eb-9a7c-bf1ba9a4c653.png)

**Comment by Zrips** [comment]
CMI was never mentioned to support modded servers.
I can fix this particular issue, but in general i cant guarantee any stability with your modded server.
