### ISSUE TITLE
MySQL Connection impossible

### ISSUE THREAD

**Issue by DoctaEnkoda** [Zrips/CMI#4844]
**Description of issue:**
Hello, I currently have a bug with the MySQL connection, indeed the / mdp / host identifiers are good but impossible to make it work!

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:14:56 WARN]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[14:15:08 WARN]: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[14:15:08 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[14:15:08 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
[14:15:08 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[14:15:08 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBConnectionPool.getConnection(DBConnectionPool.java:34)
[14:15:08 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.<init>(DBDAO.java:514)
[14:15:08 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBMySQL.<init>(DBMySQL.java:21)
[14:15:08 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.startMysql(DBManager.java:227)
[14:15:08 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.load(DBManager.java:141)
[14:15:08 WARN]:        at com.Zrips.CMI.Config.load(Config.java:775)
[14:15:08 WARN]:        at com.Zrips.CMI.Config.load(Config.java:757)
[14:15:08 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1454)
[14:15:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:15:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[14:15:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[14:15:08 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:503)
[14:15:08 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:417)
[14:15:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:422)
[14:15:08 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:178)
[14:15:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:872)
[14:15:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:160)
[14:15:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[14:15:08 WARN]: Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'cmi_gestion2;'
[14:15:08 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:15:08 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
[14:15:08 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:15:08 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[14:15:08 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[14:15:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[14:15:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[14:15:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[14:15:08 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129)
[14:15:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:792)
[14:15:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:717)
[14:15:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:685)
[14:15:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:134)
[14:15:08 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:469)
[14:15:08 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:174)
[14:15:08 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1348)
[14:15:08 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
[14:15:08 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850)
[14:15:08 WARN]:        ... 24 more
```

---

**Cmi Version (using`/cmi version`):** 8.7.12.5

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.4

**Comment by DoctaEnkoda** [comment]
After research, your class is deprecated and is no longer valid for the latest versions of Java (in this case, I am using Java 15.0.1)

**Comment by DoctaEnkoda** [comment]
![image](https://user-images.githubusercontent.com/26461373/103458661-90d7b700-4d0a-11eb-821d-dae1d6eb3035.png)

**Comment by Zrips** [comment]
Noted, testing and it should be resolved with next release.
