### ISSUE TITLE
Error when breaking blocks in 1.8.8

### ISSUE THREAD

**Issue by AppleMacOS** [Zrips/CMI#4849]
**Description of issue:**

Whenever I break a block I get the error that's listed below.

I haven't tested if this happens in other versions other then 1.8.8

---

**ERROR:**
```
[16:26:39 WARN]: java.lang.NullPointerException
[16:26:39 WARN]: 	at com.Zrips.CMI.Reflections.getNbt(Reflections.java:1150)
[16:26:39 WARN]: 	at com.Zrips.CMI.Containers.CMINBT.<init>(CMINBT.java:31)
[16:26:39 WARN]: 	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.processInteract(CustomNBTListener.java:72)
[16:26:39 WARN]: 	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:50)
[16:26:39 WARN]: 	at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
[16:26:39 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:26:39 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:26:39 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[16:26:39 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[16:26:39 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:26:39 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[16:26:39 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[16:26:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
[16:26:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:626)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:26:39 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:26:39 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[16:26:39 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:26:39 WARN]: java.lang.NullPointerException
[16:26:39 WARN]: 	at com.Zrips.CMI.Reflections.getNbt(Reflections.java:1150)
[16:26:39 WARN]: 	at com.Zrips.CMI.Containers.CMINBT.<init>(CMINBT.java:31)
[16:26:39 WARN]: 	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.processInteract(CustomNBTListener.java:104)
[16:26:39 WARN]: 	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:50)
[16:26:39 WARN]: 	at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
[16:26:39 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:26:39 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:26:39 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[16:26:39 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[16:26:39 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:26:39 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[16:26:39 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[16:26:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
[16:26:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:626)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:26:39 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:26:39 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[16:26:39 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:26:39 WARN]: java.lang.NullPointerException
[16:26:39 WARN]: 	at com.Zrips.CMI.Reflections.getNbt(Reflections.java:1150)
[16:26:39 WARN]: 	at com.Zrips.CMI.Containers.CMINBT.<init>(CMINBT.java:31)
[16:26:39 WARN]: 	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.processInteract(CustomNBTListener.java:163)
[16:26:39 WARN]: 	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:50)
[16:26:39 WARN]: 	at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
[16:26:39 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:26:39 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:26:39 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[16:26:39 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[16:26:39 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[16:26:39 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[16:26:39 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[16:26:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228)
[16:26:39 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:626)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[16:26:39 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:26:39 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[16:26:39 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[16:26:39 WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version :** 8.7.12.6

**Server Type:** Paper

**Server Version:** This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Confirmed, will be fixed with next build.
