### ISSUE TITLE
Problem with the performing commands with /warn

### ISSUE THREAD

**Issue by MdoubleM** [Zrips/CMI#4855]
**Cmi Version (using`/cmi version`):8.7.12.6** 

**Server Type (Spigot/Paperspigot/etc):Paper(366)** 

**Server Version (using `/ver`):This server is running Paper version git-Paper-366 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)** 

When I use the command /warn and the user get the points to be for example muted, the server gives this error:
https://ufile.io/spg1dpwi

I have the warn config like this:
https://ufile.io/bbxhkfcz

**Comment by CloudeLecaw** [comment]
Could you Upload your log content on pastebin ? The fileupload is a bit complicated

**Comment by MdoubleM** [comment]
Here is the error: https://pastebin.com/mbVVvyMN
Warnings: https://pastebin.com/nD3TBfq0

The ! is at the end of the phrase, I don't know if that matters. I only know that something with the command is giving me errors

**Comment by CloudeLecaw** [comment]
i tried this one
```
  Perform:
    '3':
    - cmi mute [playerName] 15m
    - cmi msg [playerName] &cSilenciado durante &715 &cminutos por obtener &73 &cpuntos de advertencia!
    '6':
    - cmi kick [playerName] &cKickeado por obtener 6 puntos de advertencia!
    '9':
    - cmi tempban [playerName] 10m &cBaneado temporalmente por obtener 9 puntos deadvertencia!
    '12':
    - cmi tempban [playerName] 1d &cBaneado temporalmente por obtener 12 puntos de advertencia!
```

worked fine so long

**Comment by MdoubleM** [comment]
I'm still having the same error, even with the default warning config that have the cmi
https://pastebin.com/Kd7NwUjC

**Comment by CloudeLecaw** [comment]
On our server we now cqn confirm this problem

**Comment by BratLive** [comment]
org.bukkit.command.CommandException: Unhandled exception executing command 'bw' in plugin MBedwars v5.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776) ~[patched_1.16.5.jar:git-Paper-794]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1116) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1066) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:401) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:305) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:261) ~[?:?]
        at com.Zrips.CMI.Modules.Portals.CMIPortal.teleport(CMIPortal.java:133) ~[?:?]
        at com.Zrips.CMI.Modules.Portals.PortalListener.processMove(PortalListener.java:200) ~[?:?]
        at com.Zrips.CMI.Modules.Portals.PortalListener.onPlayerMove(PortalListener.java:111) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor489.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1424) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.serv
er.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.OfflinePlayer.getUniqueId()" because "<parameter1>" is null
        at de.marcely.bedwars.api.remote.RemoteAPI.getOnlinePlayer(RemoteAPI.java:208) ~[?:?]
        at de.marcely.bedwars.ko.a(Util.java:1005) ~[?:?]
        at de.marcely.bedwars.y.onFire(JoinCommand.java:113) ~[?:?]
        at de.marcely.bedwars.api.command.CollectionCommandHandler.onFire(CollectionCommandHandler.java:78) ~[?:?]
        at de.marcely.bedwars.api.command.CommandHandlerWrappedSender.onFire(CommandHandlerWrappedSender.java:30) ~[?:?]
        at de.marcely.bedwars.q.onCommand(BaseCommandExecutor.java:38) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-794]
        ... 31 more
