### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4861]
**Description of issue:**

---
Hi, I've got this error in console when server was starting.
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[23:14:04] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "REX2005"
[23:14:04] [Server thread/WARN]: 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
[23:14:04] [Server thread/WARN]: 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[23:14:04] [Server thread/WARN]: 	at java.lang.Double.parseDouble(Double.java:538)
[23:14:04] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getLocationFromString(PlayerManager.java:2094)
[23:14:04] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.getValueFromDb(PlayerManager.java:1931)
[23:14:04] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1374)
[23:14:04] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1209)
[23:14:04] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:580)
[23:14:04] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1483)
[23:14:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:14:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:14:04] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:14:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[23:14:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[23:14:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469)
[23:14:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
[23:14:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936)
[23:14:04] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[23:14:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
---

**Cmi Version (using`/cmi version`):**  v8.7.12.5

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 367

**Comment by Zrips** [comment]
Will fix this error, tho was your database modified manually? In general this error should not effect plugins work. But it would be interesting to know why it showed this one as this could only happened if recorded location in database was modified unproperly or maybe saved incorrectly.
