### ISSUE TITLE
PlaceHolder from VotingPlugin don't load 

### ISSUE THREAD

**Issue by Threshian** [Zrips/CMI#4872]
**Description of issue:**
Since the last 2 updates, placeholdes from votingplugin are not loaded with cmi.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[18:54:39] [Server thread/WARN]: [CMI] Task #38271 for CMI v8.7.12.7 generated an exception
java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/Util/PlaceHolders/PlaceHolders
	at com.Ben12345rocks.VotingPlugin.PlaceHolderAPI.expansion.VotingPliuginExpansion.onRequest(VotingPliuginExpansion.java:55) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:517) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:177) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:925) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1289) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-390]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[18:54:39] [Server thread/WARN]: [CMI] Task #38274 for CMI v8.7.12.7 generated an exception
java.lang.NoClassDefFoundError: com/Ben12345rocks/VotingPlugin/Util/PlaceHolders/PlaceHolders
	at com.Ben12345rocks.VotingPlugin.PlaceHolderAPI.expansion.VotingPliuginExpansion.onRequest(VotingPliuginExpansion.java:55) ~[?:?]
	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
	at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:517) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:177) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:925) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-390]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1289) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-390]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-390]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

---

**Cmi Version (using`/cmi version`):** 
CMI 8.7.12.7
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.16.4

**Comment by Zrips** [comment]
Not a CMI plugin issue, CMI only requested placeholder update and **Ben12345rocks.VotingPlugin** failed to provide one for some reason.
