### ISSUE TITLE
Hello. I encountered a new error.

### ISSUE THREAD

**Issue by wkurumi** [Zrips/CMI#4875]
**Description of issue:**
In the module server, the console reports an error, which may be the same last time.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```[19:24:45] [Server thread/ERROR] [Minecraft/]: Could not pass event EntityDamageByEntityEvent to CMI v8.7.12.7
org.bukkit.event.EventException: null
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading,re:mixin}
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading}
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactoryMixin.java:249) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactoryMixin.java:964) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactoryMixin.java:851) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactoryMixin.java:807) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactoryMixin.java:996) ~[arclight:arclight-1.16.4-1.0.11-SNAPSHOT-093932b] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftEventFactoryMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.entity.LivingEntity.damageEntity0(LivingEntityMixin.java:3970) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70097_a(LivingEntityMixin.java:3807) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.passive.AnimalEntity.func_70097_a(AnimalEntityMixin.java:552) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.passive.AnimalEntityMixin,pl:mixin:APP:randompatches.mixins.json:AnimalEntityMixin,pl:mixin:APP:byg.mixins.json:common.entity.MixinAnimalEntity,pl:mixin:A,pl:runtimedistcleaner:A}
        at com.minecolonies.coremod.entity.ai.citizen.herders.AbstractEntityAIHerder.butcherAnimal(AbstractEntityAIHerder.java:597) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.ai.citizen.herders.AbstractEntityAIHerder.butcherAnimals(AbstractEntityAIHerder.java:298) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.ai.citizen.herders.EntityAIWorkCowboy.butcherAnimals(EntityAIWorkCowboy.java:172) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
        at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at net.minecraft.entity.MobEntity.func_70626_be(MobEntityMixin.java:682) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntityMixin.java:2411) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70636_d(MobEntityMixin.java:488) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.entity.AgeableEntity.func_70636_d(AgeableEntityMixin.java:127) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:entity.AgeableEntityMixin,pl:mixin:A}
        at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:389) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:457) ~[minecolonies:0.13.557-ALPHA] {re:classloading}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntityMixin.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.LivingEntityMixin,pl:mixin:A,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntityMixin.java:300) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorldMixin.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(WorldMixin.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.WorldMixin,pl:mixin:APP:mixins.performance.paper.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:world.server.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A,pl:arclight_implementer:async,pl:arclight_implementer:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1894) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272] {}
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.PlayerCombat.PlayerCombatListener.entityCombatEvent(PlayerCombatListener.java:178) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        ... 39 more

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
#######################################
```

---

**Cmi Version (using`/cmi version`):*8.7.12.7* 

**Server Type (Spigot/Paperspigot/etc):*Arclight* 

**Server Version (using `/ver`):*1.16.4*

**Comment by wkurumi** [comment]
https://paste.ubuntu.com/p/vcTxyXYN2S/

**Comment by Zrips** [comment]
Should be resolved with next build
