### ISSUE TITLE
[Exception Error] cmi aliaseditor command using %rand placeholder

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#4883]
```
[14:29:10 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.8.0.0
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-397]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-397]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-397]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:758) ~[patched_1.16.4.jar:git-Paper-397]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:877) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:839) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:576) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:572) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:144) ~[?:?]
        at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:97) ~[?:?]
        at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:156) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1160.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-397]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2013) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1082) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-397]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-397]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at com.Zrips.CMI.commands.list.warp.perform(warp.java:101) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:340) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-397]
        ... 32 more
>
```

```
> cmi version
[14:30:12 INFO]: --------------------------------------------------
[14:30:12 INFO]: CMI plugin version: 8.8.0.0 SqLite
[14:30:12 INFO]: Server: Paper(397) 1.16.4-R0.1-SNAPSHOT
[14:30:12 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[14:30:12 INFO]: Modules -> 52 enabled 1 disabled: flightCharge
[14:30:12 INFO]: --------------------------------------------------
>
```

`asConsole! cmi warp dropparty%rand/1-4% [playerName] -s`

I've tried to make a random warp spot, i've set 4 of them, and i wanted to force the player to go there and randomly go to 1 2 3 or 4. 

Upon trying for the first time it spit out an exception error in console.

**Comment by mrfloris** [comment]
`%cmi_random_1_5%`
Was using the wrong random thingy..
