### ISSUE TITLE
Error starting plugin

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#4889]
**Description of issue:**
Error in console starting plugin.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
########################
[Server thread/WARN]: java.lang.NullPointerException
at com.Zrips.CMI.Modules.Jail.JailManager.getJailsByDistance(JailManager.java:411)
at com.Zrips.CMI.Modules.Jail.JailManager.getValidCell(JailManager.java:483)
at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1843)
at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1209)
at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:580)
at com.Zrips.CMI.CMI.onEnable(CMI.java:1546)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464)
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:931)
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
at java.base/java.lang.Thread.run(Thread.java:834) ##
######################
```

---

**Cmi Version (using`/cmi version`):** 
8.8.0.1

**Server Type (Spigot/Paperspigot/etc):** 
Paper(400) 1.16.4-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
Paper version git-Paper-400 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be fixed with next build
