### ISSUE TITLE
Error when /Armorstand last

### ISSUE THREAD

**Issue by strahil211** [Zrips/CMI#4903]
An error seems to appear when someone does /armorstand last

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[18:40:07 INFO]: Valon issued server command: /armorstand last
[18:40:07 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Purpur-952]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.4.jar:git-Purpur-952]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2074) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1877) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1830) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1202) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1195) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1332) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.4.jar:git-Purpur-952]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.4.jar:git-Purpur-952]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.AStand.ArmorStandManager.getLast(ArmorStandManager.java:111) ~[?:?]
        at com.Zrips.CMI.commands.list.armorstand.perform(armorstand.java:83) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:354) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Purpur-952]
        ... 19 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.8.0.2
**Server Type (Spigot/Paperspigot/etc):** 
PurPur
**Server Version (using `/ver`):** 
1.16.4 #952
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Will be fixed with next build
