### ISSUE TITLE
PlayerDeathEvent Null 8.8.0.5

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/CMI#4962]
**Description of issue:**
Player dies and throws a console error

**ERROR (DELETE IF YOU HAVE NO ERROR):**
[Server thread/ERROR]: Could not pass event PlayerDeathEvent to CMI v8.8.0.5
java.lang.NullPointerException: null
	at com.Zrips.CMI.Modules.PlayerCombat.PlayerCombatListener.onPlayerDeath(PlayerCombatListener.java:290) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1160.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-434]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:834) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:675) ~[patched_1.16.5.jar:git-Paper-434]
	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.die(EntityHumanNPC.java:179) ~[?:?]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1267) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:844) ~[patched_1.16.5.jar:git-Paper-434]
	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:153) ~[?:?]
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:271) ~[patched_1.16.5.jar:git-Paper-434]
	at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.playerTick(EntityHumanNPC.java:371) ~[?:?]
	at net.citizensnpcs.nms.v1_16_R3.util.NMSImpl.playerTick(NMSImpl.java:974) ~[?:?]
	at net.citizensnpcs.util.NMS.playerTick(NMS.java:340) ~[?:?]
	at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-434]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-434]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-434]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Cmi Version (using`/cmi version`):** v8.8.0.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper 

**Server Version (using `/ver`):** 
Paper git-Paper-434 (MC: 1.16.5)

**Relevant plugins (Delete if this isn't needed):**
Including full list incase it helps. 
Plugins (79): 
AdminGUI-Premium, AdvancedChests, AdvancedEnchantments, AdvancedFood, ArmoredElytra, AureliumSkills, Bank, BigDoors, BKCommonLib, BuycraftX, ChatControl, ChestLockGui, Citizens, CMI, CMIEInjector*, CMILib, CMIPaperLib, CombatPlus, ConsoleSpamFix, Core, CoreProtect, CustomCrafting, CustomEnderChest, DangerousCaves, Denizen, DiscordSRV, DisplayShopAddon*, DisplayShops, dtlTraders, EpicFurnaces, EpicSpawners, ExoticGarden, ExtraGear, HeadDatabase, HolographicDisplays, HorseOverhaul, HungerGames, ImageOnMap, InfoBook, Item-Chest-Sorter, Jobs, Lands, LightCleaner, LimitPillagers, LuckPerms, LWC, MobArena, MurderMystery, My_Worlds, NBTAPI, NexEngine, NoPlugins, Oh_the_dungeons_youll_go, Parkour, ParkourTopTen, PlaceholderAPI, PotionCreation, ProtocolLib, PublicCrafters, racing, Sentinel, Slimefun, spark, SuperLuckyBlock, TangledMaze, TNTRun_reloaded, UltimateCatcher, UltimateKits, UltimateRepairing, VanillaTweaks, Vault, VillageDefense, Votifier, VotingPlugin, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldResourcepacks

**Comment by Zrips** [comment]
Should be resolved with next update. Its mainly originates from Citizens plugin, no idea why it would throw error when player dies as this is relating to NPC dying, but maybe there is some feature linking those things together. In any case, will be fixed.
