### ISSUE TITLE
Error in console starting plugin ► Cannot measure distance

### ISSUE THREAD

**Issue by C4BR3R4** [Zrips/CMI#4981]
**Description of issue:**
Error in console starting plugin ► Cannot measure distance...

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
########################
java.lang.IllegalArgumentException: Cannot measure distance to a null world
at org.bukkit.Location.distanceSquared(Location.java:508)
at org.bukkit.Location.distance(Location.java:493)
at com.Zrips.CMI.Modules.Jail.JailManager.getJailsByDistance(JailManager.java:415)
at com.Zrips.CMI.Modules.Jail.JailManager.getValidCell(JailManager.java:483)
at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1849)
at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1209)
at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:582)
at com.Zrips.CMI.CMI.onEnable(CMI.java:1538)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464)
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239)
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935)
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173)
at java.base/java.lang.Thread.run(Thread.java:834) ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
Versión de CMI: 8.8.0.6
Versión de CMILib: 1.0.0.2

**Server Type (Spigot/Paperspigot/etc):** 
PaperMC v1.16.5 #444

**Server Version (using `/ver`):** 
Paper version git-Paper-444 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be fixed with next build
