### ISSUE TITLE
error

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#501]
`[17:35:25 WARN]: [CMI] Plugin CMI v7.8.3.0 generated an exception while executing task 15437564
java.lang.NullPointerException: null
        at com.Zrips.CMI.Modules.PlayTimeRewards.PlayTimeRewardsManager$1$1.run(PlayTimeRewardsManager.java:118) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1448]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.12.2.jar:git-Paper-1448]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.12.2.jar:git-Paper-1448]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`

**Cmi Version The latest version:** 

**Server Type paper:** 

**Server Version 1.12.2:**

**Comment by TheWranger** [comment]
Could you give some context to this? When do you get this error? On server startup or when something specific happens?

**Comment by CloudeLecaw** [comment]
NullPointer in Paper...voila...

the only Thing that helps here when not using offical spigot is a bit more detailed contect how to produce this error like TheWranger allready suggested.
