### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Antonecek** [Zrips/CMI#5097]
**Description of issue:**
11:36:35[WARN] [CMI] Plugin CMI v8.8.1.1 generated an exception while executing task 1007288
java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:768) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[server.jar:git-Paper-437]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[server.jar:git-Paper-437]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[server.jar:git-Paper-437]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be fixed with next release.

**Comment by Antonecek** [comment]
Thank you very much. :)
