### ISSUE TITLE
[Issue] SQL warning message in console

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#513]
**Description of issue or feature request:**

```
[12:01:13][WARN]: java.sql.BatchUpdateException: Data truncation: Data too long for column 'inventories' at row 1 
[12:01:13][WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
[12:01:13][WARN]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
[12:01:13][WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
[12:01:13][WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
[12:01:13][WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) 
[12:01:13][WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:408) 
[12:01:13][WARN]: at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163) 
[12:01:13][WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1778) 
[12:01:13][WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1262) 
[12:01:13][WARN]: at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970) 
[12:01:13][WARN]: at com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:864) 
[12:01:13][WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:322) 
[12:01:13][WARN]: at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:230) 
[12:01:13][WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) 
[12:01:13][WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) 
[12:01:13][WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) 
[12:01:13][WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
[12:01:13][WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
[12:01:13][WARN]: at java.lang.Thread.run(Thread.java:748) 
[12:01:13][WARN]: Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'inventories' at row 1 
[12:01:13][WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971) 
[12:01:13][WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) 
[12:01:13][WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) 
[12:01:13][WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) 
[12:01:13][WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) 
[12:01:13][WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) 
[12:01:13][WARN]: at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) 
[12:01:13][WARN]: at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756) 
[12:01:13][WARN]: ... 11 more 
```

I have changed the value of the column manually from TEXT to MEDIUMTEXT. I think this might solve the issue.

**Cmi Version (using`7.8.3.0`):** 

**Server Type (Paper):** 

**Server Version (using `Paper(1452) 1.12.2-R0.1-SNAPSHOT`):**

**Comment by Zrips** [comment]
@Baktus79 I think you have terribly old database as currently that field is been set to LONGTEXT which can contain up to 2GB of data. But this was fixed like a year ago or so. But yea, manually changing type will solve issue.

**Comment by Baktus79** [comment]
You are right :D My database is very old. I wasnt sure it was fixed so I just posted it here :) The issue was solved easly by changing the field
