### ISSUE TITLE
Paper spigot having issue with § symbol.

### ISSUE THREAD

**Issue by horsecraft** [Zrips/CMI#5144]
I'm noticing the symbol § is in the default settings of the config folders of CMI. For some reason, the latest versions of paper spigot are having an issue with the § symbol.
---

[22-Feb-2021 12:13:11] Could not pass event AsyncPlayerChatEvent to CMI v8.8.1.3

[22-Feb-2021 12:13:11] java.util.UnknownFormatConversionException: Conversion = '§'

[22-Feb-2021 12:13:11] at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:101) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:170) ~[?:?]

[22-Feb-2021 12:13:11] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor707.execute(Unknown Source) ~[?:?]

[22-Feb-2021 12:13:11] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1936) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1851) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1789) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.5.jar:git-Paper-483]

[22-Feb-2021 12:13:11] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]

[22-Feb-2021 12:13:11] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]

[22-Feb-2021 12:13:11] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]

[22-Feb-2021 12:13:11] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]

[22-Feb-2021 12:13:11] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```




**Cmi Version : Latest
Paper Spigot: Latest

1.16.4

**Comment by AZFire1** [comment]
When did you update? Paper has been making MASSIVE changes to the way they handle colors all day long.. I recommend downgrading for now.. This is likely an issue caused by all of Paper's color changes to their new "Adventure" system. I have yet to figure out what that is, though.

**Comment by horsecraft** [comment]
I ended up deleting CMI from the server and re-installing. Fixed the issue.

**Comment by horsecraft** [comment]
closing
