### ISSUE TITLE
Alias for "/cmi" command

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#5149]
**DESCRIPTION OF ISSUE:**
I have created custom help files for my players groups and I would like to add custom alias to re-map command `/cmi`. Here comes the problem... I can easilyre-map commands `/help` and `/?` but when I want to re-map `/cmi` ... really bad things starts to happenning.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[23:18:45] [Server thread/INFO]: Player issued server command: /help
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: AsyncLogger error handling event seq=472, value='':
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: java.lang.NullPointerException
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at org.apache.logging.log4j.core.async.RingBufferLogEvent.execute(RingBufferLogEvent.java:161)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:45)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at org.apache.logging.log4j.core.async.RingBufferLogEventHandler.onEvent(RingBufferLogEventHandler.java:29)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[23:18:47] [Log4j2-TF-1-AsyncLogger[AsyncContext@70dea4e]-1/WARN]: AsyncLogger error handling event seq=483, value='':




[23:18:47] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to WorldGuard v7.0.4-beta1;bc551da
java.lang.StackOverflowError: null
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:675) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.util.concurrent.SettableFuture.setException(SettableFuture.java:54) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache$LoadingValueReference.setException(LocalCache.java:3690) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3735) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[patched_1.16.5.jar:git-Paper-470]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[patched_1.16.5.jar:git-Paper-470]
	at com.sk89q.worldguard.session.AbstractSessionManager.hasBypass(AbstractSessionManager.java:138) ~[?:?]
	at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.hasBypass(BukkitSessionManager.java:81) ~[?:?]
	at com.sk89q.worldguard.bukkit.listener.WorldGuardPlayerListener.onPlayerCommandPreprocess(WorldGuardPlayerListener.java:434) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor190.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-470]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-470]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:738) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:897) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:763) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:897) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:763) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:897) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:763) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-470]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:758) ~[patched_1.16.5.jar:git-Paper-470]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:899) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:763) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:897) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:763) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:897) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:763) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:145) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:98) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
[customAlias]:
  cmi:
    Cmds:
    - perm:custom.help.player! cmi ctext help_player [playerName]
    - perm:custom.help.patron! cmi ctext help_patron [playerName]
    - perm:custom.help.community! cmi ctext help_community [playerName]
    - perm:custom.help.sponsor! cmi ctext help_sponsor [playerName]
    - perm:custom.help.platinum! cmi ctext help_platinum [playerName]
    - perm:custom.help.mod! cmi ctext help_mod [playerName]
    - perm:custom.help.admin! cmi ctext help_admin [playerName]
    - perm:custom.help.ceo! cmi ctext help_ceo [playerName]
```
---

**Cmi Version (using`/cmi version`):** 8.8.1.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 1.16.5-b470

**Relevant plugins (Delete if this isn't needed):**

**Comment by CloudeLecaw** [comment]
well first you may give a look to Worldgaurd 7.0.5...
https://builds.enginehub.org/job/worldguard/17264

my this problem is fixed allready..

could you post your customalias? this might would help to see where to problem is

**Comment by Zrips** [comment]
@mare-on 
You are trying to remap command which by itself points to itself which creates infinite loop as you can see from your error logs. You cant simply say to perform /cmi ctext when performing /cmi as when you will perform /cmi ctext it will trigger /cmi alias which will perform itself once more and so on. You will need to use different approach here.

**Comment by mare-on** [comment]
I understand the issue with loop for `/cmi` command, but hey... does exists permission note to disable help list from `/cmi` at least? When I disable permissions `cmi.command` then all CMI command are blocked, sooo... does even exists a permission for this?

**Comment by CloudeLecaw** [comment]
you mean a permission for seeing the comand listed when using /cmi help or /cmi command ? or /cmi ?

**Comment by mare-on** [comment]
I mean exactly the permission for command `/cmi` which shows help page with every CMI command for which player has permission. I just want to disable access tothe `/cmi` - `/cmi help` command.

**Comment by CloudeLecaw** [comment]
what you can do is set this to false

```
  Commands:
    # When set to true player will see full list of posible commands when performing /cmi command without defining specific command
    # When set to false we will return 'No command found' feedback message
    ShowMainHelpPage: false
```

this will prevent showing the list when just using /cmi
but it does not prevent using the help arugment..
may you can try negating   cmi.command.help  dont know if this permision exists... if not you can suggest it in a request :-)

**Comment by CloudeLecaw** [comment]
on the Langfile you find this:

```
command:
  help:
    output:
      usage: '&eVerwendung: &6%usage%'
      cmdInfoFormat: '[command] &f- &e[description]'
      cmdFormat: '&6/[command]&f[arguments]'
      helpPageDescription: '&e* [description]'
      explanation: '&e * [explanation]'
      title: '&e------ ======= &6CMI&e &e======= ------'
```

so the command seems to be /cmi help  right?
then negate cmi.command.help for your players
and do the setting i wrote before from config.yml

```
  Commands:
    # When set to true player will see full list of posible commands when performing /cmi command without defining specific command
    # When set to false we will return 'No command found' feedback message
    ShowMainHelpPage: false
```

**Comment by mare-on** [comment]
Hi, sorry for the delay between reply, I was too busy.

`ShowMainHelpPage: false`

This is exactly what I wanted ;)
Many thanks for the help.
