### ISSUE TITLE
cmi portals setlocation Event Eventy;-29;77;-81;0;-10 -> ERROR

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5169]
**Description of issue:**

---

Hi, there's error with the new command. Could you please fix it? From game it works, but from console/cmd block I'm getting this.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:28:13 WARN]: Unexpected exception while parsing console command "cmi portals setlocation Event Eventy;-29;77;-81;0;-10"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:768) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:432) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:399) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1295) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassCastException: class com.destroystokyo.paper.console.TerminalConsoleCommandSender cannot be cast to class org.bukkit.entity.Player (com.destroystokyo.paper.console.TerminalConsoleCommandSender and org.bukkit.entity.Player are in unnamed module of loader 'app')
        at com.Zrips.CMI.commands.list.portals.perform(portals.java:95) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:357) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-33]
        ... 9 more
```

---

**Cmi Version (using`/cmi version`):** 8.8.1.5

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 25

Same for /cmi portals enabled [portalname] [true/false]...

**Comment by Zrips** [comment]
Should be fixed with next update
