### ISSUE TITLE
Task #3267615

### ISSUE THREAD

**Issue by POBO0314** [Zrips/CMI#5198]
[WARNING] .... [CMI] Task #3267615 for CMI v8.8.1.5 generated an exception

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]

at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]

at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]

at java.util.Objects.checkIndex(Unknown Source) ~[?:?]

at java.util.ArrayList.set(Unknown Source) ~[?:?]

at com.Zrips.CMI.Modules.ChatEditor.ChatMessageListEdit$3$1.run(ChatMessageListEdit.java:96) ~[?:?]

at com.Zrips.CMI.Modules.ChatEditor.ChatEditorManager.perform(ChatEditorManager.java:47) ~[?:?]

at com.Zrips.CMI.Modules.ChatEditor.ChatEditorListener$1.run(ChatEditorListener.java:36) ~[?:?]

at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-503]

at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-503]

at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1299) ~[patched_1.16.5.jar:git-Paper-503]

at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-503]

at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-503]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-503]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-503]

at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3149.000000007124C3C0.run(Unknown Source) ~[?:?]

at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by we67iop** [comment]
How much help do you expect when you provide no other information but the stack trace.

**Comment by Zrips** [comment]
Will fix error, hard to determine exact cause, but it seams that multiple users tried to modify same thing at same time which caused this error message
