### ISSUE TITLE
[TryMe] exception error 

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#5252]
**Description of issue:**
```
[10:58:48 WARN]: [TryMe] Task #4139797 for TryMe v6.2.2.1 generated an exception
java.lang.NullPointerException: null
        at me.Zrips.TryMe.gameModes.HangManMode.differentLetterCount(HangManMode.java:140) ~[?:?]
        at me.Zrips.TryMe.gameModes.HangManMode.internalRun(HangManMode.java:52) ~[?:?]
        at me.Zrips.TryMe.gameModes.HangManMode.runMode(HangManMode.java:88) ~[?:?]
        at me.Zrips.TryMe.gameModes.GameModesUtil.processGameInitialization(GameModesUtil.java:334) ~[?:?]
        at me.Zrips.TryMe.gameModes.HangManMode.initializeMode(HangManMode.java:102) ~[?:?]
        at me.Zrips.TryMe.gameModes.AllMode.internalRun(AllMode.java:36) ~[?:?]
        at me.Zrips.TryMe.gameModes.AllMode.access$0(AllMode.java:25) ~[?:?]
        at me.Zrips.TryMe.gameModes.AllMode$1.run(AllMode.java:45) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-529]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-529]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1299) ~[patched_1.16.5.jar:git-Paper-529]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:379) ~[patched_1.16.5.jar:git-Paper-529]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-529]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-529]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-529]
        at java.lang.Thread.run(Thread.java:834) [?:?]
>
```

I woke up to this a few times in the console, haven't seen these in a while from tryme, thought i'd report it.
<img width="1680" alt="Screenshot 2021-03-09 at 11 12 48" src="https://user-images.githubusercontent.com/28841349/110455514-d167fe00-80c8-11eb-8739-f79bd841a6f8.png">

```
> ver
[11:20:49 INFO]: This server is running Paper version git-Paper-534 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[11:20:49 INFO]: Checking version, please wait...
[11:20:49 INFO]: Previous version: git-Paper-529 (MC: 1.16.5)
[11:20:49 INFO]: You are running the latest version
> ver TradeMe
[11:20:51 INFO]: TradeMe version 6.0.5.3
[11:20:51 INFO]: Powerfull trade plugin
[11:20:51 INFO]: Website: https://www.spigotmc.org/resources/trademe.7544/
[11:20:51 INFO]: Author: Zrips
>
```

tryme was running in amode, automatically on with 4+ players.

**Comment by Zrips** [comment]
Will fix it and post new version.

**Comment by mrfloris** [comment]
Awesome, thank you.
