### ISSUE TITLE
Get ArrayIndexOutOfBoundsException: 1 in version 8.8.2.2

### ISSUE THREAD

**Issue by broken1arrow** [Zrips/CMI#5274]
**Description of issue:**
Last working version are 8.8.2.0

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[08:07:29] [Server thread/ERROR]: Error occurred while enabling CMI v8.8.2.2 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.Zrips.CMI.Modules.Alias.AliasManager.register(AliasManager.java:216) ~[?:?]
	at com.Zrips.CMI.Modules.Alias.AliasManager.addCustom(AliasManager.java:276) ~[?:?]
	at com.Zrips.CMI.Modules.Alias.AliasManager.load(AliasManager.java:529) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1545) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-498]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-498]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-498]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-498]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466) ~[patched_1.16.5.jar:git-Paper-498]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-498]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941) ~[patched_1.16.5.jar:git-Paper-498]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-498]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
[08:07:29] [Server thread/INFO]: [CMI] Disabling CMI v8.8.2.2
```

more errors, I miss to add.
https://pastebin.com/TyT42YRB

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
https://pastebin.com/SUkztZzz
https://pastebin.com/NVmDTyMy

---

**Cmi Version (using`/cmi version`):** 
8.8.2.2
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
498 and 400
**Relevant plugins (Delete if this isn't needed):**
has try on testserver with vault ,luck perms.

**Comment by Kbryst** [comment]
I have this too but I can't get any custom alias to work on 8.8.2.0 when I rolled back to it.

**Comment by broken1arrow** [comment]
> I have this too but I can't get any custom alias to work on 8.8.2.0 when I rolled back to it.

Custom alias work for me on 8.8.2.0. 

Hope he look in to this soon. We has not update main severer before a fix is released.

**Comment by broken1arrow** [comment]
Still a issue and update it with more issue reports.

I think you has made soo big changes after 8.8.2.0. So it cant use old settings yml files.

**Comment by broken1arrow** [comment]
Sill a issue in  8.8.2.8.

https://pastebin.com/rkjjknLb

**Comment by Zrips** [comment]
Confirmed, should be resolved with next build.

**Comment by broken1arrow** [comment]
> Confirmed, should be resolved with next build.
> 
> To be more accurate here, you had ` 'randomteleport ':` which is invalid format and broke some things in the code. Will prevent from this happening in the future

Is not only I some edit the files, but thanks will fix that (the error not say what thing some was the problem only the file some make the error).

**Comment by broken1arrow** [comment]
> I have this too but I can't get any custom alias to work on 8.8.2.0 when I rolled back to it.

Check your files for errors, like my yml has. Like not use 'randomteleport ': , use it with out ''.
