### ISSUE TITLE
World unloaded error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5284]
**Description of issue:**

---

Hi, this error occurred in my log multiple times.

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: java.lang.IllegalArgumentException: World unloaded
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at org.bukkit.Location.getWorld(Location.java:112)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.Containers.CMILocation.updateWorld(CMILocation.java:61)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.Containers.CMILocation.getWorld(CMILocation.java:89)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.PlayerManager.convertLocationToString(PlayerManager.java:2034)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.PlayerManager.proccessForSaveField(PlayerManager.java:1213)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1146)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:717)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:451)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:341)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:05:43] [Craft Scheduler Thread - 7125 - CMI/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 8.8.2.2

**Server Type (Spigot/Paperspigot/etc):** Yatopia

**Server Version (using `/ver`):** 33

**Comment by Zrips** [comment]
Should be resolved with latest builds
