### ISSUE TITLE
[Bug] [SignShop Conflict] CMI Will Conflict With & Disable SignShop Plugin

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Zrips/CMI#5308]
**Description of issue or feature request:**

Until recently I was able to use CMI & SignShop alongside each other without issues. 

Then I updated some plugins & added MythicMobs and a SignShop error started occurring- that would disable SignShops every server startup. At first I thought this was a conflict between CMI & SignShop and was caused by SignShop starting **before** CMI- thus causing the error. I thought this because I found someone had the same error in April 2020: https://github.com/wargamer/SignShop/issues/72

After about 4 hours of testing I determined it was when MythicMobs, CMI, and SignShop were added then the SignShop error would occur. If MythicMobs is not added then there were no issues. 

However, I find this very odd because MythicMobs isn't an economy plugin- it is a custom mobs plugin. Furthermore, I tried disabling the vault hook in the MythicMobs config and that did not solve the issue. I suspect it has something to do with CMI as CMI is the economy plugin for my server. 

Perhaps MythicMobs is somehow causing SignShops to start before CMI (CMI should be starting before SignShops I believe).

Help would be greatly appreciated. Both plugins are **extremely** powerful and I'd really like to use both of them on my server.

**Latest.log:** https://pastebin.com/njHRXpqv

---

**ERROR:**
```
[20:06:13] [Server thread/INFO]: [SignShop] Enabling SignShop v3.5.0
[20:06:13] [Server thread/INFO]: [SignShop] Checking data version.
[20:06:13] [Server thread/INFO]: [SignShop] Your data is current.
[20:06:17] [Server thread/ERROR]: Error occurred while enabling SignShop v3.5.0 (Is it up to date?)
java.lang.NullPointerException: null
	at org.wargamer2010.signshop.worth.CMIWorthHandler.<init>(CMIWorthHandler.java:16) ~[?:?]
	at org.wargamer2010.signshop.SignShop.onEnable(SignShop.java:189) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-562]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-562]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-562]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-562]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-562]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-562]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-562]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-562]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-562]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[20:06:17] [Server thread/INFO]: [SignShop] Disabling SignShop v3.5.0
[20:06:18] [Server thread/INFO]: [SignShop] Successfully cancelled async sellers.yml save task with ID: 1562
[20:06:18] [Server thread/INFO]: [SignShop] Successfully cancelled async timing.yml save task with ID: 2039
[20:06:18] [Server thread/INFO]: [SignShop] Disabled
[20:06:18] [Server thread/INFO]: [CMI] Enabling CMI v8.8.2.3
[20:06:18] [Server thread/INFO]: [CMIPaperLib] Enabling CMIPaperLib v1.0.0
```

---

**Cmi Version (using`/cmi version`):** 
[20:07:46 INFO]: --------------------------------------------------
[20:07:46 INFO]: CMI: 8.8.2.3 MySQL
[20:07:46 INFO]: CMILib: 1.0.0.2 
[20:07:46 INFO]: Server: Paper(562) 1.16.5-R0.1-SNAPSHOT
[20:07:46 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True 
[20:07:46 INFO]: Modules -> 46 enabled 9 disabled: spawnerProximity, cuffed, disabledEnchants, worldLimitsElytra, votifier, skin, warmup, vanish, dynamicSigns
[20:07:46 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
[20:07:56 INFO]: This server is running Paper version git-Paper-562 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

**Relevant plugins:** Vault, CMI, SignShop, MythicMobs 4.11.0 (Free Version)

**Additional Notes:** (**NOTE:** These notes were from before I updated my message, however, they may still be useful)
- In April 2020 it appears someone else had a similar or identical issue to this: https://github.com/wargamer/SignShop/issues/72. What they determined was SignShop was starting before CMI for some reason- even though it shouldn't have been. And the user's temporary solution was to edit the SignShop source code to change CMI to a hard dependency of SignShop and remove CMIPaperLib as a softdependency. IF we have the same problem, sadly I cannot implement this change by myself as I don't know enough Java to compile the plugin successfully after changing the plugin.yml harddepend & softdepend sections. 
- If you'd be willing to do the above for me, that could potentially be a much faster solution to this issue. Although I'm not 100% sure if it'd fix this issue seeing how it only started happening after a CMI update.

**Comment by PiggiesGoSqueal** [comment]
After running into this issue I tried backtracking to see which CMI version it worked on. Now I'm very confused because I updated CMI on 3/6/2021 (AKA to version: 8.8.2.0) and there were no conflicts. But all CMI versions from last 1-2 months now have this issue occur...?! 

I am guessing updating CMI caused it to change the way data was saved or something, that way the issue persists regardless of which CMI version I'm using?

Issue occurs on (Tested) CMI versions:
- 8.8.2.3
- 8.8.2.2
- 8.8.2.0
- 8.8.1.6
- 8.8.1.4
- 8.8.1.2
- 8.8.1.0
- 8.8.0.8

Happens on (Tested) CMI Lib Versions:
- 1.0.0.2
- 1.0.0.1


These are all the plugins I updated today when this issue started occurring:
- Chunkmaster &:
-  https://gyazo.com/36eab15fd57c13180b694f574e0f6339

**Comment by PiggiesGoSqueal** [comment]
To update it was ShopGUIPlus causing the conflict. Very peculiar that updating ShopGUIPlus caused SignShop to be disabled and the reason in the error mentioned CMI...?!

**Comment by PiggiesGoSqueal** [comment]
Okay. I've done thorough testing now. 

If I have ShopGUIPlus 1.50.0 added, there is no issue.
If I have ShopGUIPlus 1.54.0 added, there is no issue.
If I add MythicMobs, there is an issue.

End Result:
The issue occurs when MythicMobs is added. Which is a plugin I added for the first time today (on this map). 

I also tried disabling the Vault hook in MythicMobs config and SignShops still disables itself on server startup.

However, as it is highly unlikely MythicMobs would directly cause issues with an economy plugin, I'm still guessing CMI is somehow related? The issue only occurs when CMI, SignShop, and MythicMobs is present I believe.

**Comment by PiggiesGoSqueal** [comment]
Peculiar. Now it is happening without MythicMobs added. The only difference is I switched from a VPS to a Minecraft host and added EasyBackup (a plugin I've used alongside MythicMobs & CMI in past without issues).
