### ISSUE TITLE
Can't load CMI.

### ISSUE THREAD

**Issue by MC-SHD1** [Zrips/CMI#531]
**Description of issue or feature request:**
Error occurred while enabling

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[11:29:25] [Server thread/ERROR]: Error occurred while enabling CMI v7.8.5.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/JsonListEntry
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_172]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_172]
	at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:421) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:389) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1313) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.JsonListEntry
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.11.2.jar:git-Paper-1104]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
	... 16 more
[11:29:25] [Server thread/INFO]: [CMI] Disabling CMI v7.8.5.0
[11:29:25] [Server thread/ERROR]: Error occurred while disabling CMI v7.8.5.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:130) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:126) ~[patched_1.11.2.jar:git-Paper-1104]
	at com.Zrips.CMI.Modules.Afk.AfkManager.tasker(AfkManager.java:134) ~[?:?]
	at com.Zrips.CMI.Modules.Afk.AfkManager.<init>(AfkManager.java:25) ~[?:?]
	at com.Zrips.CMI.CMI.getAfkManager(CMI.java:758) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1138) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [patched_1.11.2.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [patched_1.11.2.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [patched_1.11.2.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
None
```

**Cmi Version (using`/cmi version`):** 7.8.5.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):**  Paper version git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
"patched_1.11.2.jar"
What is this? Download official normal version of 1.11.2, this doesn't look like one or give link where you got it so i could test out whats going on with it

**Comment by MC-SHD1** [comment]
But the CMI 7.8.3.0 can run on paperclip-1104(https://destroystokyo.com/ci/job/Paper/1104/)
The patched_1.11.2.jar is paperclip-1104 is paper auto cache

**Comment by Zrips** [comment]
Something went wrong with file exporting, will post new version today which should work correctly.

**Comment by Zrips** [comment]
Test new 7.8.5.1 version, should work correctly from now on.

**Comment by MC-SHD1** [comment]
Thank you for fixing this issue.

**Comment by MC-SHD1** [comment]
Thank you for fixing this issue.
