### ISSUE TITLE
/entitynbt & armor stands error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5323]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
        ... 19 more
[00:56:05 INFO]: Renzotom issued server command: /entitynbt
[00:56:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.2.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2093) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1908) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1861) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1199) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1168) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1012) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/Zrips/CMILib/Container/CMIList
        at com.Zrips.CMI.Reflections.printNBT(Reflections.java:2058) ~[?:?]
        at com.Zrips.CMI.Reflections.printEntityNBT(Reflections.java:1921) ~[?:?]
        at com.Zrips.CMI.commands.list.entitynbt.perform(entitynbt.java:43) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:354) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"44e8e5d"]
        ... 19 more
```

Hi, I've tried to see entitynbt of armor stands but I've got this error. Also, I wanted to copy this armor stand but I cannot search the way.

And just question, is there a way to copy these armor stands into another place somehow easily?

---

**Cmi Version (using`/cmi version`):** 8.8.2.3

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Should be fixed with next build
