### ISSUE TITLE
Plugin does not work on version 1.16.1 

### ISSUE THREAD

**Issue by serguna99** [Zrips/CMI#5341]
Visit https://github.com/Zrips/CMI/discussions/new to post question
Posting questions in ticket section could result in their removal.
Please correct this situation 
PaperSpigot 1.16.1
[02:51:51] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[02:51:51] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[02:51:51] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[02:51:51] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[02:51:51] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[02:51:51] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[02:51:51] [Server thread/INFO]: _______________________________________________________
[02:51:51] [Server thread/INFO]:   Integrating PaperSpigot async methods
[02:51:51] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16_R1
[02:51:51] [Server thread/WARN]: java.lang.ClassNotFoundException: com.Zrips.CMI.NBT.v1_16_R1
[02:51:51] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[02:51:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171)
[02:51:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[02:51:51] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:51:51] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[02:51:51] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[02:51:51] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[02:51:51] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1398)
[02:51:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:51:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[02:51:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[02:51:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500)
[02:51:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414)
[02:51:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471)
[02:51:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241)
[02:51:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941)
[02:51:51] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[02:51:51] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[02:51:51] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: Essentials Economy

**Comment by mrfloris** [comment]
This isn't a bug, this is announced a while ago in the changelog when 1.16.4 / 1.16.5 were released.

There's no reason to be on such old versions, please upgrade to stay current. Support for 1.16.0 and 1.16.1 has been dropped

**Comment by CloudeLecaw** [comment]
i agree This is not a bug
The support for 1.16.0 and 1.16.1 was dropped long ago when 1.16.5 was released and CMI was updated.
So Its recomment to update to 1.16.5 if you want to continue using CMI.

**Comment by Zrips** [comment]
@serguna99 
Please update your server to 1.16.5 as this is best version for you to have in any case as it has least bugs in general as is allot more optimized in general. Support for minor minecraft versions got dropped as it should not be used in any case anyways.

**Comment by serguna99** [comment]
> 
> 
> @serguna99
> Please update your server to 1.16.5 as this is best version for you to have in any case as it has least bugs in general as is allot more optimized in general. Support for minor minecraft versions got dropped as it should not be used in any case anyways.

you have indicated what works with different versions 1.16, including, and where you have indicated that I stopped supporting 1.16.1 in order to use it on 1.16.1. the server itself on this version
