### ISSUE TITLE
Error occurred while enabling CMI v8.8.2.6 (Is it up to date?)

### ISSUE THREAD

**Issue by TehZombiJesus** [Zrips/CMI#5344]
**I simply tried updating to the new Paper and  CMI version available and when I restarted the server, theses errors showed up. Even tried going back to my previous Paper-567 and CMI verison 8.8.2.5 and still got the same error.**

---

**ERROR FROM CMI**
```
[Server thread/ERROR]: Error occurred while enabling CMI v8.8.2.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/Zrips/CMI/Containers/CMICustomColors
	at com.Zrips.CMI.Containers.CMIChatColor.<clinit>(CMIChatColor.java:32) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1322) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-570]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.Containers.CMICustomColors
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-570]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 12 more
[Server thread/INFO]: [CMI] Disabling CMI v8.8.2.6
```
**WARNING FROM CHATCONTROL**
```	
[Craft Scheduler Thread - 9/INFO]: ChatControl 8.9.10 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[Craft Scheduler Thread - 9/INFO]: org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: ChatControl could not hook into CMI as the plugin is disabled! (DO NOT REPORT THIS TO ChatControl, look for errors above and contact support of 'CMI')
[Craft Scheduler Thread - 9/INFO]: at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
[Craft Scheduler Thread - 9/INFO]: at org.mineacademy.chatcontrol.lib.fo.Common.lambda$doesPluginExist$2(Common.java:1075)
[Craft Scheduler Thread - 9/INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
[Craft Scheduler Thread - 9/INFO]: !-----------------------------------------------------!
[Craft Scheduler Thread - 9/INFO]: Failed to execute scheduled task: org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: ChatControl could not hook into CMI as the plugin is disabled! (DO NOT REPORT THIS TO ChatControl, look for errors above and contact support of 'CMI')
[Craft Scheduler Thread - 9/INFO]: !-----------------------------------------------------!
```

**ERROR.LOG FILE**
```
------------------------------------[ 26.03.2021 13:53:13 ]-----------------------------------
ChatControl 8.9.10 encountered a FoException
Running Paper 1.16.5-R0.1-SNAPSHOT and Java 11.0.10
Plugins: CoreProtect v19.5, Chunky v1.2.54, UltraRegions v1.3.5, PlaceholderAPI v2.10.10-DEV-122, ProtocolLib v4.6.1-SNAPSHOT-b498, spark v1.5.2, UltraPermissions v4.9.9.2, Vault v1.7.3-b131, AntiVPN v6.4.13, DiscordSRV v1.21.3, CMI v8.8.2.6, ChatControl v8.9.10
----------------------------------------------------------------------------------------------

More Information: 
ChatControl could not hook into CMI as the plugin is disabled! (DO NOT REPORT THIS TO ChatControl, look for errors above and contact support of 'CMI')
FoException Report: ChatControl could not hook into CMI as the plugin is disabled! (DO NOT REPORT THIS TO ChatControl, look for errors above and contact support of 'CMI')
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.fo.Common.lambda$doesPluginExist$2(Common.java:1075)
	 at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:68)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	 at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	 at java.base/java.lang.Thread.run(Thread.java:834)
----------------------------------------------------------------------------------------------

```

---

**CMI v8.8.2.6** 

**Paper** 

**git-Paper-570 (MC: 1.16.5)** 

**ChatControl Pro - v8.9.10**

**Comment by Zrips** [comment]
Try redownloading plugin as this error usually (99.9% of times) originates from corrupted plugin file after downloading it. If issue persists, let me know, for now closing this ticket.

**Comment by TehZombiJesus** [comment]
I've already tried that multiple times..

Stopping the server;
Deleting the current plugins/paper jar;
Adding the new jar files;
Restarting the server ..

I tried it again after your message but this time I deleted all plugins configs and I still get the same error.

**Comment by TehZombiJesus** [comment]
Problem solved, it was my antivirus :(
