### ISSUE TITLE
Could not pass event PlayerJoinEvent to ChatControl v8.9.10

### ISSUE THREAD

**Issue by TehZombiJesus** [Zrips/CMI#5346]
**Happens everytime a player joins the server.**

**I also want to point out that my issue #5344 was never fixed.**

**Everything was working fine before I updating CMI and Paper to latest version and even tried going back to the previous versions I was using but still didn't work. Tried downloading from multiples browsers, tested on multiples servers and everything I get the same errors**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to ChatControl v8.9.10
java.lang.NoClassDefFoundError: com/Zrips/CMI/CMI
	at org.mineacademy.chatcontrol.lib.fo.model.CMIHook.getUser(HookManager.java:2861) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.model.CMIHook.isMuted(HookManager.java:2799) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.model.HookManager.isMuted(HookManager.java:699) ~[?:?]
	at org.mineacademy.chatcontrol.util.Utils.isMuteApplied(Utils.java:366) ~[?:?]
	at org.mineacademy.chatcontrol.listener.ListenerPlayer.onJoin(ListenerPlayer.java:213) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-570]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:314) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:158) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1501) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-570]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-570]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.CMI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-570]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-570]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 21 more
```
---

**Cmi Version (using`/version cmi` "/cmi version" doesn't work): 8.8.2.6** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): Paper-570** 

**Relevant plugins (Delete if this isn't needed): ChatControl v8.9.10**

**Comment by TehZombiJesus** [comment]
Problem solved, it was my antivirus :(
