### ISSUE TITLE
Failing to load on startup

### ISSUE THREAD

**Issue by AppleStrafe** [Zrips/CMI#5390]
**Description of issue:**
When I start the server it fails to load properly.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
02.04 01:30:59 [Server] INFO [CMI] Enabling CMI v8.8.2.9
02.04 01:30:59 [Server] INFO [TAB] Version Deleted is out! Your version: 2.8.10
02.04 01:30:59 [Server] INFO [TAB] Get the update at https://www.spigotmc.org/resources/57806/
02.04 01:31:02 [Server] INFO ????? ?????? ????
02.04 01:31:02 [Server] INFO ????? ? ?? ? ????
02.04 01:31:02 [Server] INFO ?? ?? ??????  ?? 
02.04 01:31:02 [Server] INFO ?? ?? ??????  ?? 
02.04 01:31:02 [Server] INFO ????? ?????? ????
02.04 01:31:02 [Server] INFO ????? ?????? ????
02.04 01:31:02 [Server] INFO _______________________________________________________
02.04 01:31:02 [Server] INFO Integrating PaperSpigot async methods
02.04 01:31:02 [Server] INFO Downloading CMILib file.
02.04 01:31:03 [Server] Startup 55 Enabled and 0 Disabled modules
02.04 01:31:03 [Server] ERROR Error occurred while enabling CMI v8.8.2.9 (Is it up to date?)
02.04 01:31:03 [Server] INFO java.lang.NoClassDefFoundError: net/Zrips/CMILib/Colors/CMIChatColor
02.04 01:31:03 [Server] INFO at com.Zrips.CMI.Modules.Enchants.CMIEnchantment.saveEnchants(CMIEnchantment.java:22) ~[?:?]
02.04 01:31:03 [Server] INFO at com.Zrips.CMI.CMI.onEnable(CMI.java:1374) ~[?:?]
02.04 01:31:03 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
02.04 01:31:03 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.Zrips.CMILib.Colors.CMIChatColor
02.04 01:31:03 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
02.04 01:31:03 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Paper-"8b47131da"]
02.04 01:31:03 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
02.04 01:31:03 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
02.04 01:31:03 [Server] INFO ... 12 more
02.04 01:31:03 [Server] INFO [CMI] Disabling CMI v8.8.2.9
```
**Cmi Version (using`/cmi version`):** 
8.8.2.9
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot 1.16.5
**Server Version (using `/ver`):** 
1.16.5-R0.1-SNAPSHOT

**Comment by mrfloris** [comment]
Hi there,

Thank you for writing this out here.

If you check your plugins/ folder, is both the cmi jar and cmi lib jar there? 
If the cmi lib jar cannot automatically download you can get it for free from here:

https://www.spigotmc.org/resources/cmilib.87610/

Hopefully this will resolve it.

**Comment by AppleStrafe** [comment]
> Hi there,
> 
> Thank you for writing this out here.
> 
> If you check your plugins/ folder, is both the cmi jar and cmi lib jar there?
> If the cmi lib jar cannot automatically download you can get it for free from here:
> 
> https://www.spigotmc.org/resources/cmilib.87610/
> 
> Hopefully this will resolve it.

Seemed to been having trouble downloading the lib file. Installing it manually worked! Thanks!
