### ISSUE TITLE
Cant download CMILib

### ISSUE THREAD

**Issue by MADS0LADEN** [Zrips/CMI#5391]
**Description of issue:**
It cannot find a class from CMILib because it is not in the plugins folder

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:48:19 INFO]: [CMI] Enabling CMI v8.8.2.9
[10:48:20 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[10:48:20 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[10:48:20 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[10:48:20 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[10:48:20 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[10:48:20 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[10:48:20 INFO]: _______________________________________________________
[10:48:20 INFO]:   Integrating PaperSpigot async methods
[10:48:20 INFO]:   Downloading CMILib file.
[10:48:20 INFO]:   Citizens found.
[10:48:20 INFO]:   55 Enabled and 0 Disabled modules
[10:48:20 INFO]:   Votifier found. Enabling vote listeners
[10:48:20 ERROR]: Error occurred while enabling CMI v8.8.2.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/Zrips/CMILib/Colors/CMIChatColor
        at com.Zrips.CMI.Modules.Enchants.CMIEnchantment.saveEnchants(CMIEnchantment.java:22) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1374) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1061) ~[patched_1.16.5.jar:git-Purpur-1051]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1051]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.Zrips.CMILib.Colors.CMIChatColor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Purpur-1051]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Purpur-1051]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 12 more
[10:48:20 INFO]: [CMI] Disabling CMI v8.8.2.9
```

---

**Cmi Version (using`/cmi version`):** 
v8.8.2.9

**Server Type (Spigot/Paperspigot/etc):** 
Purpur ([link](https://purpur.pl3x.net/))

**Server Version (using `/ver`):** 
This server is running Purpur version git-Purpur-1051 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Zrips** [comment]
Posted new version. Sorry for inconvenience.
