### ISSUE TITLE
CMI EXP Error

### ISSUE THREAD

**Issue by WolverStones** [Zrips/CMI#5392]
"cmi exp WolverStone add 200"
```
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.2.9
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1051]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1051]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Purpur-1051]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Purpur-1051]
at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:464) ~[patched_1.16.5.jar:git-Purpur-1051]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.16.5.jar:git-Purpur-1051]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1403) ~[patched_1.16.5.jar:git-Purpur-1051]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Purpur-1051]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1051]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/Zrips/CMILib/Container/CMIArray
at com.Zrips.CMI.commands.list.exp.perform(exp.java:105) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:354) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1051]
... 9 more
```
---

**Cmi Version (using`/cmi version`):** 
[14:43:20 INFO]: Version CMI: 8.8.2.9 BungeeCord CMIB MySQL-> 8.8.2.10
[14:43:20 INFO]: CMILib: 1.0.0.2
[14:43:20 INFO]: Server: Purpur 1.16.5-R0.1-SNAPSHOT
[14:43:20 INFO]: CMI economy: enable Vault: 1.7.3-b131(CMIEInjector) CMI Chat: disable
[14:43:20 INFO]: Modules -> 53 enabled 2 disabled: tablist, skin

**Server Type (Spigot/Paperspigot/etc):** 
Purpur 

**Server Version (using `/ver`):** 
This server is running Purpur version git-Purpur-1051 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

**Comment by CloudeLecaw** [comment]
Pls use lates cmi Version

**Comment by WolverStones** [comment]
In version 8.8.3.0 work fine.

**Comment by CloudeLecaw** [comment]
Normal u may have not read last Patch logs ;)
