### ISSUE TITLE
Errors in console - holograms - spigot 1.9

### ISSUE THREAD

**Issue by andramil** [Zrips/CMI#5418]
**Description of issue:**
Hi, I have spam in console with warnings caused by holograms.
14 x times warns bellow (I have 14 holo so every single hologram cause one block of warnings)

```
[09:57:31 WARN]: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.server.v1_9_R2.EntityArmorStand.bB to java.lang.Integer
[09:57:31 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[09:57:31 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[09:57:31 WARN]:        at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:86)
[09:57:31 WARN]:        at java.lang.reflect.Field.set(Field.java:764)
[09:57:31 WARN]:        at com.Zrips.CMI.NBT.v1_9_R2.createStand(v1_9_R2.java:651)
[09:57:31 WARN]:        at com.Zrips.CMI.NBT.v1_9_R2.spawnHologram(v1_9_R2.java:660)
[09:57:31 WARN]:        at com.Zrips.CMI.Modules.Holograms.CMIHologram$2$1.run(CMIHologram.java:942)
[09:57:31 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
[09:57:31 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[09:57:31 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)
[09:57:31 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)
[09:57:31 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)
[09:57:31 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)
[09:57:31 WARN]:        at java.lang.Thread.run(Thread.java:748)

```
---

**Cmi Version (using`/cmi version`):** 
http://prntscr.com/117995l
8.8.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-c6871e2-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
PAPI

**Comment by andramil** [comment]
Holograms shows in client normally, they seems to working. Just spam in console.

**Comment by Zrips** [comment]
Should be fixed with next update.
