### ISSUE TITLE
Console Spam: Error handling plugin message

### ISSUE THREAD

**Issue by GioDM** [Zrips/CMI#5422]
My console is getting spammed with an error about CMI v8.8.3.0 generating an exception whilst handling plugin message.
I have installed CMI Bungeecord plugin on my bungeecord server.
I don't use CMI for chat handeling since I use Deluxechat.
---

**ERROR:**
```
[15:52:59] [Server thread/WARN]: [CMI] Plugin CMI v8.8.3.0 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[patched_1.16.5.jar:git-Paper-582]
	at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.onPluginMessageReceived(CMIBungeeCord.java:439) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3056) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-582]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-582]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readShort(DataInputStream.java:320) ~[?:?]
	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[patched_1.16.5.jar:git-Paper-582]
	... 17 more
```
---

**Cmi Version (using`/cmi version`):** 8.8.3.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** git-Paper-582

**Relevant plugins:** Deluxechat (Chat handeling), NetworkManager (Network handeling)

**Comment by Zrips** [comment]
Will be resolved with next update

**Comment by AerWyn81** [comment]
Hi, the issue still here with latest version.

![image](https://user-images.githubusercontent.com/22222045/114315648-2354d700-9b00-11eb-8a00-127f591347e9.png)

```[19:56:50 WARN]: [CMI] Plugin CMI v8.8.3.1 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.onPluginMessageReceived(CMIBungeeCord.java:398) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2760) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:345) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 14 more
```

Extra notes : All related bungee config in CMI is set to false.

**Comment by AerWyn81** [comment]
Hello @Zrips, do you have any possibilities to solve this issue ? This incredibly spams the console... I know this is not a blocking issue but it is not comfortable, especially since this problem was supposed to be solved... Thanks by advance ! :)
