### ISSUE TITLE
[20:18:20 WARN]: java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#5434]
**Description of issue:**

[20:18:20 WARN]: java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getFirstPlayer(CMIBungeeCord.java:521)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getPlayerList(CMIBungeeCord.java:133)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordServer.update(BungeeCordServer.java:133)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1661)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:755)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:605)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:441)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:771)
[20:18:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:18:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:18:20 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:18:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[20:18:20 WARN]: java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getFirstPlayer(CMIBungeeCord.java:521)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getPlayerList(CMIBungeeCord.java:133)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordServer.update(BungeeCordServer.java:133)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1661)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:755)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:605)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:441)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:771)
[20:18:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:18:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:18:20 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:18:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[20:18:20 WARN]: java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getFirstPlayer(CMIBungeeCord.java:521)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getPlayerList(CMIBungeeCord.java:133)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordServer.update(BungeeCordServer.java:133)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1661)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:755)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:605)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:561)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:441)
[20:18:20 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:771)
[20:18:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[20:18:20 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:18:20 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:18:20 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:18:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
---

**Cmi Version (using`/cmi version`):** 
CMI Plugin Version: 8.8.3.1 BungeeCord CMIB  MySQL
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
git-Paper-576 (MC: 1.16.5)

**Comment by dkalaxdk** [comment]
Might be a good idea to describe when this happens?

**Comment by blakedj012** [comment]
I dont know when it happens. I saw this in my console.

**Comment by Zrips** [comment]
Nothing to special about this error, can be ignored, but will prevent it from appearing with next update anyways.
