### ISSUE TITLE
CMI Wont create MySQL tables

### ISSUE THREAD

**Issue by Korinocho** [Zrips/CMI#5462]
I deleted all my tables on some server to clean the users info (its a lobby server so the info doesnt matter), but after this, i detected that my CMI (was on 8.8.3.1 and even updating to 8.8.3.4) wont create new tables.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[02:29:52] [Server thread/INFO]: [CMI] Enabling CMI v8.8.3.3
[02:29:53] [Server thread/INFO]: ????? ?????? ????
[02:29:53] [Server thread/INFO]: ????? ? ?? ? ????
[02:29:53] [Server thread/INFO]: ?? ?? ??????  ?? 
[02:29:53] [Server thread/INFO]: ?? ?? ??????  ?? 
[02:29:53] [Server thread/INFO]: ????? ?????? ????
[02:29:53] [Server thread/INFO]: ????? ?????? ????
[02:29:53] [Server thread/INFO]: _______________________________________________________
[02:29:53] [Server thread/INFO]:   Integrating PaperSpigot async methods
[02:29:53] [Server thread/INFO]:   Citizens found.
[02:29:53] [Server thread/INFO]:   23 Enabled and 32 Disabled modules
[02:29:53] [Server thread/INFO]:   Votifier found. Enabling vote listeners
[02:29:53] [Server thread/INFO]:   Loaded (7) portals into memory. Took 8ms
[02:29:53] [Server thread/INFO]:   Permission plugin: LuckPerms5.3.15
[02:29:53] [Server thread/INFO]:   Initialized Cipher256 AES
[02:29:53] [Server thread/INFO]:   Loaded (54) regular alias into memory. Took 35ms
[02:29:53] [Server thread/INFO]:   Loaded (1) custom text's into memory. Took 1ms
[02:29:53] [Server thread/INFO]:   Detected Java11
[02:29:53] [Server thread/INFO]:   8.0.23 data base type detected
[02:29:54] [Server thread/INFO]:   Started MySQL data base. Took 283ms
[02:29:54] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: CMIEconomy
[02:29:54] [Server thread/INFO]:   Loaded (5) warning categories into memory. Took 0ms
[02:29:54] [Server thread/INFO]:   Loaded (3) warning commands into memory. Took 0ms
[02:29:54] [Server thread/INFO]:   Loaded (131) custom mob heads into memory. Took 15ms
[02:29:54] [Server thread/INFO]:   Loaded (0) cooldowns into memory. Took 22ms
[02:29:54] [Server thread/INFO]:   Enabling BungeeCord Support
[02:29:54] [Server thread/INFO]:   Initializing BungeeCord
[02:29:54] [Server thread/INFO]:   Loaded (7) ranks into memory. Took 16ms
[02:29:54] [Server thread/INFO]:   Loaded (8) playtime rewards into memory. Took 2ms
[02:29:54] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table 'cmi_hub.cmi_users' doesn't exist
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1207)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:582)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1478)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[02:29:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:29:54] [Server thread/INFO]:   Loaded (0) player data into memory. Took 2ms
[02:29:54] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table 'cmi_hub.cmi_playtime' doesn't exist
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayTimes(DBDAO.java:1231)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:605)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1478)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[02:29:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:29:54] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table 'cmi_hub.cmi_playtimereward' doesn't exist
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[02:29:54] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayerPlayTimeRewards(DBDAO.java:1365)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:606)
[02:29:54] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1478)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[02:29:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[02:29:54] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[02:29:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:29:54] [Server thread/INFO]:   Loaded (1) custom alias into memory. Took 2ms
[02:29:54] [Server thread/INFO]:   Registered events. Took 97ms
[02:29:54] [Server thread/INFO]:   Loaded (0) event action commands into memory. Took 3ms
[02:29:54] [Server thread/INFO]:   Updated (EN) language file. Took 102ms
[02:29:54] [Server thread/INFO]:   Updated (ES) language file. Took 91ms
[02:29:54] [Server thread/INFO]:   Can't load worth value for LEGACY_RAW_FISH
[02:29:54] [Server thread/INFO]:   Loaded (244) worth values into memory. Took 9ms
[02:29:54] [Server thread/INFO]:   Vault permissions was found - Enabling capabilities.
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
I didnt changed ANY database config, but there it is
```
storage:
  # storage method, can be MySQL or sqlite
  # ATTENTION! DON'T USE SAME DATABASE TABLES FOR MORE THEN ONE SERVER, YOU WILL HAVE UNEXPECTED ISSUES. EACH SERVER SHOULD HAVE ITS OWN DATABASE TABLE SETUP
  method: MySQL
mysql:
  # Requires Mysql.
  username: root
  password: ************
  hostname: localhost:3306
  database: cmi_hub
  # Valid characters are a-z 0-9 and _
  tablePrefix: CMI_
  # If you have no clue what these values do, then keep it at default values
  autoReconnect: true
  useSSL: false
  verifyServerCertificate: false
# Auto save interval in seconds
# This will define how often to write down data into data base
# Save operation will not be performed if there is no changes to save
# !ATTENTION! Keep it in low numbers, around 60 seconds
# Minimal interval is 10 seconds
AutoSaveInterval: 15
# Player data will be recorded straight after he logs out, without any delay
ForceSaveOnLogOut: false
# EXPERIMENTAL. This is not fully tested yet and some minor issues can happen when ussing on bungee network
# Player data will be loaded from database each time player joins server
# When its set to false then precached data will be uses which is more efficient
ForceLoadOnLogIn: false
```

---

**Cmi Version (using`/cmi version`):** 
8.8.3.4

**Server Type (Spigot/Paperspigot/etc):** 
Paper 594

**Server Version (using `/ver`):** 
Paper 594

**Comment by Korinocho** [comment]
I have to add that i tried with clean config files, but it wont help

**Comment by Korinocho** [comment]
I managed to create the tables by myself (using the table creation query that appear if you use sqlite, but changing it a little bit) but i dont know if its working right

**Comment by TomLewis** [comment]
You should have just emptied the tables instead of deleting them. 
You will most likely have to remove all the tables for CMI to populate all tables again, its classed as a one time setup thing and doesn't expect people to just remove random tables.

You can empty a table without deleting it, this is what you should have done.

I suggest you restore the table from a backup and empty it.

**Comment by Korinocho** [comment]
It doesnt matter if i deleted, because i restored the configs to default (deleted the CMI folder completly). If it stores a "check" to dont create the tables again anywhere else, please tell me where.

**Comment by Korinocho** [comment]
I mean, i understood that i SHOULD just empty the tables, but i dont believe that CMI wont recreate them in any way

**Comment by TomLewis** [comment]
If you just emptied the ones you wanted, you wouldn't have this problem *shrugs*. I've told you a solution.

**Comment by Korinocho** [comment]
I just dropped all the tables from this server. But its already done hahahaha. And i dont have backup of that :/

**Comment by TomLewis** [comment]
Dude, Keep backups!

**Comment by Korinocho** [comment]
Its a lobby server. It doesnt store anything important.

**Comment by Korinocho** [comment]
Its all Ok @Zrips? Im not trying to ask you to solve this but to know if you are good, its been a while after your last appear here.
Cheers!

**Comment by Korinocho** [comment]
Ok. Kinda solved it! CMI MySQL break after Paper-587 release. They made some change to the MySQL connector and CMI wont create new tables after this.
This is the change they made:
![image](https://user-images.githubusercontent.com/21372197/116645818-fbad9d80-a94c-11eb-91bd-7bb8dc0bae41.png)
Anyone can test this. Just use last CMI+Paper 587 (there cmi will create new tables on MySQL), and then drop all the tables and use any Paper release after 587 (588, for example) and then CMI wont create any tables. This is a huge bug!

**Comment by Zrips** [comment]
This seams to be resolved with latest paper builds. Tables get created properly without dropping them.
