### ISSUE TITLE
NullPointerException CmiWarp.getIcon when /warp

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5477]
**Description of issue:**
When player use /warp, we have a error in console

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[09:38:53] [Server thread/INFO]: iBuseWinner issued server command: /warps
[09:38:53] [Server thread/INFO]: [CMI] false false false
[09:38:53] [Server thread/WARN]: java.lang.NullPointerException
[09:38:53] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Warps.CmiWarp.getIcon(CmiWarp.java:147)
[09:38:53] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Warps.WarpManager.openGUI(WarpManager.java:602)
[09:38:53] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.warp.perform(warp.java:163)
[09:38:53] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:354)
[09:38:53] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:225)
[09:38:53] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[09:38:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2286)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2101)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2054)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[09:38:53] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[09:38:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[09:38:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1053]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1053]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Purpur-1053]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776) ~[patched_1.16.5.jar:git-Purpur-1053]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:897) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:761) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:144) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:97) ~[?:?]
	at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:238) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1053]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2286) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2101) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2054) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1326) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1295) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Purpur-1053]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1053]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.Modules.Warps.CmiWarp.getIcon(CmiWarp.java:147) ~[?:?]
	at com.Zrips.CMI.Modules.Warps.WarpManager.openGUI(WarpManager.java:602) ~[?:?]
	at com.Zrips.CMI.commands.list.warp.perform(warp.java:163) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:354) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1053]
	... 27 more
```

**WARPS.YML**
```
ad1\:
  Location: vanilla_nether;-314.7;67.0;-954.71;175.12;-5.64
  Creator: 6c15232d-44bb-38d0-82d5-d012acc69a2c
Farm_endermen:
  Location: vanilla_the_end;-1493.41;57.0;1250.69;-176.14;8.09
  Creator: 0855aa08-5168-317e-a3ed-7dfa701e1715
messa:
  Location: vanilla;3256.8;87.0;9375.86;68.86;16.19
  Creator: 603cecc2-4dc6-326f-ab10-0c961d61053d
flower_forest:
  Location: vanilla;4461.55;76.0;5809.02;-76.01;-4.48
  Creator: c95b2c27-222b-3219-888b-e385578abd00
  Item:
    v: 2586
    type: AIR
    amount: 0
casino:
  Location: spawn;-10.09;30.44;1.26;38.56;14.1
  Creator: 4018c480-4b2d-3fa8-8c2b-317543e92c6b
Дом_Ленина:
  Location: vanilla;-438.28;64.0;714.39;-272.2;-23.85
  Creator: 0855aa08-5168-317e-a3ed-7dfa701e1715
Лед:
  Location: vanilla;6375.69;96.0;-3126.49;94.76;17.41
  Creator: 16223879-4fbf-346c-ad76-8a4d9966343a
led:
  Location: vanilla;-5367.52;63.0;-3844.26;295.88;9.75
  Creator: f0c14347-15fe-3622-832b-e06fe285b1c8
Багровый_Лес:
  Location: vanilla_nether;704.43;61.0;353.71;-115.66;9.3
  Creator: 16223879-4fbf-346c-ad76-8a4d9966343a
DarkOak:
  Location: vanilla;237.74;63.0;7178.45;-175.82;0.75
  Creator: 4dd63236-ffba-3055-a9e5-d9fbda34ef53
Цветочный_биом:
  Location: vanilla;5629.11;91.0;-5062.17;-90.73;26.26
  Creator: 0855aa08-5168-317e-a3ed-7dfa701e1715
djungli:
  Location: vanilla;-5030.85;71.0;-1792.61;75.19;10.36
  Creator: f41d5fb9-09df-3cfc-8849-f8b7f6d045ec
Темный_Лес:
  Location: vanilla;4068.64;112.0;-2670.9;248.2;41.26
  Creator: 16223879-4fbf-346c-ad76-8a4d9966343a
ice_spikes:
  Location: vanilla;5564.47;67.0;3718.21;86.21;7.96
  Creator: ce31a552-d89b-314b-b1f3-d26cda3ccb41
dark_forest:
  Location: vanilla;-6849.36;72.0;-6056.74;89.39;26.92
  Creator: c95b2c27-222b-3219-888b-e385578abd00
  Item:
    v: 2586
    type: AIR
    amount: 0
coral:
  Location: vanilla;-1287.76;63.0;-11894.93;277.0;19.04
  Creator: f0c14347-15fe-3622-832b-e06fe285b1c8
пиглин:
  Location: vanilla_nether;-748.69;73.0;626.29;-98.92;-0.54
  Creator: 6c15232d-44bb-38d0-82d5-d012acc69a2c
jungle_edge:
  Location: vanilla;-6525.94;75.0;5644.51;97.38;7.31
  Creator: c95b2c27-222b-3219-888b-e385578abd00
END:
  Location: vanilla_the_end;-3.38;61.0;0.6;269.85;52.64
  Creator: 0f79f8f2-73aa-3932-93c0-eb6096aeda5e
pustina:
  Location: vanilla;-1326.23;71.0;1701.22;145.47;15.61
  Creator: 967794a7-7311-3392-8ce0-c8914b24b4c0
farm_skeletov:
  Location: vanilla;1998.01;20.0;2331.63;3.12;19.87
  Creator: de374abe-a98b-36af-8071-f9d981d46164
koral:
  Location: vanilla;3373.72;62.07;8750.18;211.93;13.2
  Creator: 603cecc2-4dc6-326f-ab10-0c961d61053d
синий:
  Location: vanilla_nether;-706.69;37.0;-989.48;303.09;19.19
  Creator: 0f79f8f2-73aa-3932-93c0-eb6096aeda5e
pvp:
  Location: pvp;286.49;87.0;-10.54;-180.12;-0.6
  Page: 3
  Creator: 4018c480-4b2d-3fa8-8c2b-317543e92c6b
exitcasino:
  Location: spawn;-4.79;45.44;7.91;224.95;15.47
  Creator: 4018c480-4b2d-3fa8-8c2b-317543e92c6b
город_энд:
  Location: vanilla_the_end;3948.36;62.0;454.27;-179.43;17.84
  Creator: 0855aa08-5168-317e-a3ed-7dfa701e1715
big_taiga:
  Location: vanilla;5900.69;69.0;4389.59;157.86;-10.72
  Creator: c95b2c27-222b-3219-888b-e385578abd00
jungle1:
  Location: vanilla;1582.54;72.0;4694.58;89.32;12.72
  Creator: 8aa90b5e-fb8b-3257-a810-6c24140ae852
джунгли:
  Location: vanilla;-5169.02;65.0;-1432.13;314.5;57.38
  Creator: fbd55b55-573e-34af-9477-1da90e4d93c8
pauk:
  Location: vanilla;747.88;9.0;1890.75;182.18;5.14
  Creator: 02500116-e4c3-3b5c-b7ff-89db9d5bdbc5
((((фарм)))):
  Location: vanilla;-5936.44;57.0;3205.78;273.52;1.49
  Creator: 87b2a407-93e1-3390-8e46-bf2f95729391
grib:
  Location: vanilla;1742.23;71.0;-6272.47;-170.16;61.94
  Creator: f550dec4-3608-3099-ab6f-8c5ba65b837e
Ель:
  Location: vanilla;2134.82;74.0;1248.05;37.12;-0.58
  Creator: 16223879-4fbf-346c-ad76-8a4d9966343a
КакойТоСинийЛес:
  Location: vanilla_nether;718.02;40.0;199.95;159.88;6.45
  Creator: 16223879-4fbf-346c-ad76-8a4d9966343a
neend:
  Location: vanilla_the_end;-858.34;61.0;1561.0;272.32;23.39
  Creator: 0f79f8f2-73aa-3932-93c0-eb6096aeda5e
Jungle:
  Location: vanilla;2241.52;68.0;4798.29;-184.33;16.33
  Creator: 96d6b71e-29f5-36f9-b3b9-b77c80fd2dee
```

---

**Cmi Version (using`/cmi version`):** 
8.8.3.2

**Server Type (Spigot/Paperspigot/etc):** 
Purpur

**Server Version (using `/ver`):** 
This server is running Purpur version git-Purpur-1053 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be fixed with next update
