### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by TehZombiJesus** [Zrips/CMI#5485]
**I am not sure if this is an issue exactly but I prefer to report it just in case.**
**I was doing a test while having the Debug mode enabled and the error above showed up during the loading of CMI.**

**If this isn't an issue, you can just go ahead and close this bug report and I apologize for wasting your time.**

**Edit: The "Initializing Legacy Material Support" message still appears when the Debug mode is disabled. Only CMI was running on the server when it happened.**

---

```
[Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[Server thread/WARN]: java.lang.Exception
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:259)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.fromLegacy(CraftMagicNumbers.java:234)
[Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:497)
[Server thread/WARN]: 	at com.Zrips.CMI.Modules.Kits.KitsManager.load(KitsManager.java:434)
[Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1466)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

---

**CMI Version: 8.8.3.5** 

**Server Type: Paper** 

**Server Version: 1.16.5 (Latest)**

**Comment by Zrips** [comment]
Looks like you have some old Kits in your kits.yml file. You might want to update them to fit new standards which could be done by simply opening kit with kit editor ingame and closing, which should force it to resave entire file and make it more friendly.
