### ISSUE TITLE
[bug] /cmi inv giving java.lang.ArrayIndexOutOfBoundsException error 

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#5506]
**Description of issue:**

Did /cmi inv player today to catch someone stealing items from other players, and noticed the console wasn't happy with me. Thought i'd report it.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:52:02 INFO]: mrfloris issued server command: /cmi inv LexiGHG
[20:52:13 INFO]: mrfloris issued server command: /cmi inv LexiGHG
[20:52:14 WARN]: [CMI] Task #22900 for CMI v8.8.3.6 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 45 out of bounds for length 5
        at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager$3.run(RegChestManager.java:204) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:52:14 WARN]: [CMI] Task #22902 for CMI v8.8.3.6 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 5
        at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager$7.run(RegChestManager.java:319) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-629]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:831) [?:?]

> ver
[21:05:10 INFO]: Checking version, please wait...
[21:05:10 INFO]: This server is running Paper version git-Paper-629 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-626 (MC: 1.16.5)
> cmi version
[21:05:13 INFO]: --------------------------------------------------
[21:05:13 INFO]: CMI plugin version: 8.8.3.6 SqLite
[21:05:13 INFO]: CMILib: 1.0.0.2
[21:05:13 INFO]: Server: Paper(629) 1.16.5-R0.1-SNAPSHOT
[21:05:13 INFO]: CMI economy: True Vault: 1.7.3-b CMI Chat: True
[21:05:13 INFO]: Modules -> 54 enabled 1 disabled: flightCharge
[21:05:13 INFO]: --------------------------------------------------
>
```

**Comment by Zrips** [comment]
Should be fixed with next build

**Comment by mrfloris** [comment]
Thank you for always adding things and bug fixing the plugins. It's highly appreciated.
