### ISSUE TITLE
After using attachcommand, the server is rebooted

### ISSUE THREAD

**Issue by GlobusOk** [Zrips/CMI#5521]
![2021-05-01_19 03 37](https://user-images.githubusercontent.com/81820782/116787983-e7ce7c80-aaaf-11eb-9760-e84efced868b.png)

[crash-2021-05-01_18.14.24-server.txt](https://github.com/Zrips/CMI/files/6409896/crash-2021-05-01_18.14.24-server.txt)

**Comment by GlobusOk** [comment]
/attachcommand !limiteduse:1!;;!cc!lp user [playerName] permission set epidemic.craft.bandage

**Comment by Zrips** [comment]
Interesting error, will debug properly later, but it looks to be internal minecraft issue and not directly caused by CMI. Try testing same command with CMI only, without any other plugin to make sure that its not caused by another plugin.

**Comment by GlobusOk** [comment]
The error does not apply to other plugins. using / attachcommand! limiteduse: 1! ;;! cc! give [playerName] debugstick 1 the result is repeated.

**Comment by GlobusOk** [comment]
[20:26:47] [Server thread/INFO]: GlobusOk issued server command: /attachcommand !limiteduse:1!;;!cc!give [playerName] debugstick 1
[20:26:50] [Server thread/INFO]: [0;33;22mВыдача [0;33;1m1 [0;33;1mDebug Stick [0;33;22m([0;33;1m[0;33;22m) игроку [0;33;1mGlobusOk[m
[20:26:50] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_16_R3.ItemStack.checkEmpty(ItemStack.java:153) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.ItemStack.setCount(ItemStack.java:944) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:438) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1570) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1051) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1044) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1028) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:960) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3037-Spigot-a25e8ed-c85efa8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[20:26:50] [Server thread/ERROR]: This crash report has been saved to: /home/home/prison/./crash-reports/crash-2021-05-01_20.26.50-server.txt,

**Comment by GlobusOk** [comment]
[crash-2021-05-01_20.26.50-server.txt](https://github.com/Zrips/CMI/files/6410036/crash-2021-05-01_20.26.50-server.txt)

**Comment by Zrips** [comment]
On what type of item you are using this command? And is this error appear after using that item? It looks to be more like minecraft issue itself. Currently cant reproduce on latest Spigot builds

**Comment by CloudeLecaw** [comment]
Could you try redownload cmi and also your server
Jar?
We tried this on our server and our attacheds works fine, nonmatter with it usses cmi commands or commands of other plugins..
