### ISSUE TITLE
 java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#5523]
[08:45:09 WARN]: java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getFirstPlayer(CMIBungeeCord.java:521)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getPlayerList(CMIBungeeCord.java:133)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordServer.update(BungeeCordServer.java:133)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1692)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:761)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:611)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:447)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:771)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[08:45:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:45:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[08:45:09 WARN]: java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getFirstPlayer(CMIBungeeCord.java:521)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getPlayerList(CMIBungeeCord.java:133)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordServer.update(BungeeCordServer.java:133)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1692)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:761)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:611)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:447)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:771)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[08:45:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:45:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[08:45:09 WARN]: java.lang.IllegalArgumentException: Bungee Messaging Api requires at least one player to be online.
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getFirstPlayer(CMIBungeeCord.java:521)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.getPlayerList(CMIBungeeCord.java:133)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordServer.update(BungeeCordServer.java:133)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1692)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:761)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:611)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:567)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:447)
[08:45:09 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:771)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[08:45:09 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[08:45:09 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[08:45:09 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[08:45:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

Latest CMI and Paper.

Some times i didnt get msgs from different servers in Bungee

**Comment by Zrips** [comment]
This will be fixed with next version.
