### ISSUE TITLE
CMI ride

### ISSUE THREAD

**Issue by VojtechAdam29** [Zrips/CMI#5524]
**Description of issue:**
When player issues command /ride it shows warns

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[15:27:27 WARN]: java.lang.NoSuchMethodError: org.bukkit.entity.Slime.setInvisible(Z)V
[15:27:27 WARN]: at com.Zrips.CMI.commands.list.ride.perform(ride.java:84)
[15:27:27 WARN]: at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:367)
[15:27:27 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:27:27 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:27:27 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060)
[15:27:27 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975)
[15:27:27 WARN]: at java.lang.Thread.run(Thread.java:748)
```
---

**Cmi Version (using`/cmi version`):8.8.3.5** 

**Server Type (Spigot/Paperspigot/etc):PaperSpigot** 

**Server Version (using `/ver`):git-Paper-390**

**Comment by Zrips** [comment]
Should be fixed with next build
