### ISSUE TITLE
java.lang.NoSuchMethodException:

### ISSUE THREAD

**Issue by Fiks75** [Zrips/CMI#5530]
**Description of issue:**

This error spam in console
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:34:36] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R3.DedicatedPlayerList.moveToWorld(net.minecraft.server.v1_16_R3.EntityPlayer, net.minecraft.server.v1_16_R3.WorldServer, boolean, org.bukkit.Location, boolean)
[10:34:36] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2108)
[10:34:36] [Server thread/WARN]: 	at com.Zrips.CMI.Reflections.lambda$1(Reflections.java:1498)
[10:34:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[10:34:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[10:34:36] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423)
[10:34:36] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
[10:34:36] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338)
[10:34:36] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
[10:34:36] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[10:34:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
```

---

**Cmi Version (using`/cmi version`):** CMI: 8.8.3.8 BungeeCord CMIB  MySQL

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 1.16.5

**Server Version (using `/ver`):** This server is running Paper version git-Paper-641 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) Java 11

**Comment by Zrips** [comment]
Will be fixed with next build
