### ISSUE TITLE
BungeeCordListener Error

### ISSUE THREAD

**Issue by NightFuryStrike** [Zrips/CMI#5570]
**Description of issue:**
Whenever a player joins the server, this error is printed in console. 
Affects CMI versions v8.8.3.9 and beyond.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[02:41:07] [Server thread/INFO]: [CMI] CMIB proxy plugin detected
[02:41:08] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[02:41:08] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[02:41:08] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[02:41:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:41:08] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[02:41:08] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[02:41:08] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[02:41:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:41:08] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[02:41:08] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[02:41:08] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[02:41:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:41:08] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[02:41:08] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[02:41:08] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[02:41:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:41:08] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[02:41:08] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[02:41:08] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[02:41:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:41:08] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[02:41:08] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[02:41:08] [Server thread/WARN]: 	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2910)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
[02:41:08] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[02:41:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

---

**Cmi Version (using`/cmi version`): 8.8.4.1** 

**Server Type (Spigot/Paperspigot/etc): Paper 631** 

**Server Version (using `/ver`): 1.16.5** 

**Relevant plugins: On proxy: CMIB1.0.0.4.jar**

**Comment by Zrips** [comment]
Should be fixed with next version
