### ISSUE TITLE
Error on Join Plugin Messages

### ISSUE THREAD

**Issue by simon44556** [Zrips/CMI#5572]
**Description of issue:**

Whenever any player joins i get spammed with errors from plugin messages that cmi tries to proccess.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[17:53:54 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:54 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordListener.onPluginMessageReceived(BungeeCordListener.java:512)
[17:53:54 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2911)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1092)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006)
[17:53:54 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[17:53:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)

```

---

**Cmi Version (using`/cmi version`): 8.8.4.1** 

**Server Type (Spigot/Paperspigot/etc): PaperSpigot** 

**Server Version (using `/ver`): git-Paper-668** 

**Relevant plugins (Delete if this isn't needed): https://i.imgur.com/i7RDuSg.png**

**Comment by Zrips** [comment]
Should be fixed with next update
