### ISSUE TITLE
Gui cannot config on hybrid server

### ISSUE THREAD

**Issue by DearTanakorn** [Zrips/CMI#5577]
**Description of issue:**
when i open a gui setting it not show detail about setting 

**Paper 1.12.2 :** 
![2021-05-15_07 32 32](https://user-images.githubusercontent.com/43856376/118342906-c493da80-b54f-11eb-923c-c26506d87171.png)

![2021-05-15_07 37 11](https://user-images.githubusercontent.com/43856376/118342997-63b8d200-b550-11eb-9a8b-56ef7734847c.png)

**Magma 1.12.2 :** 
![2021-05-15_07 29 19](https://user-images.githubusercontent.com/43856376/118342884-a928cf80-b54f-11eb-9842-c4a88a104800.png)

![2021-05-15_07 36 57](https://user-images.githubusercontent.com/43856376/118343003-6adfe000-b550-11eb-9edf-d1c2ae8aede0.png)

---
**ERROR :**
```
[Server thread/WARN]  java.lang.NoSuchFieldException: activeContainer
[Server thread/WARN]      at java.lang.Class.getField(Class.java:1703)
[Server thread/WARN]      at org.magmafoundation.magma.remapper.proxy.ProxyClass.getField(ProxyClass.java:70)
[Server thread/WARN]      at com.Zrips.CMI.Reflections.getActiveContainerId(Reflections.java:1747)
[Server thread/WARN]      at com.Zrips.CMI.Reflections.updateInventoryTitle(Reflections.java:1826)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager.updateContent(GUIManager.java:356)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager.openGui(GUIManager.java:346)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.CMIGui.open(CMIGui.java:96)
[Server thread/WARN]      at com.Zrips.CMI.commands.list.gamerule.openGui(gamerule.java:244)
[Server thread/WARN]      at com.Zrips.CMI.commands.list.gamerule.perform(gamerule.java:108)
[Server thread/WARN]      at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:385)
[Server thread/WARN]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[Server thread/WARN]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:428)
[Server thread/WARN]      at com.Zrips.CMI.utils.Util.performCommand(Util.java:479)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager$1.run(GUIManager.java:184)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
[Server thread/WARN]      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[Server thread/WARN]      at java.lang.Thread.run(Thread.java:748)
[Server thread/WARN]  java.lang.IllegalArgumentException
[Server thread/WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Server thread/WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Server thread/WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Server thread/WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[Server thread/WARN]      at com.Zrips.CMI.Reflections.updateInventoryTitle(Reflections.java:1826)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager.updateContent(GUIManager.java:356)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager.openGui(GUIManager.java:346)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.CMIGui.open(CMIGui.java:96)
[Server thread/WARN]      at com.Zrips.CMI.commands.list.gamerule.openGui(gamerule.java:244)
[Server thread/WARN]      at com.Zrips.CMI.commands.list.gamerule.perform(gamerule.java:108)
[Server thread/WARN]      at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:385)
[Server thread/WARN]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[Server thread/WARN]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:428)
[Server thread/WARN]      at com.Zrips.CMI.utils.Util.performCommand(Util.java:479)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager$1.run(GUIManager.java:184)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
[Server thread/WARN]      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[Server thread/WARN]      at java.lang.Thread.run(Thread.java:748)
[Server thread/WARN]  java.lang.IllegalArgumentException
[Server thread/WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[Server thread/WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[Server thread/WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[Server thread/WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[Server thread/WARN]      at com.Zrips.CMI.Reflections.updateInventoryTitle(Reflections.java:1826)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager.updateContent(GUIManager.java:356)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager.openGui(GUIManager.java:346)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.CMIGui.open(CMIGui.java:96)
[Server thread/WARN]      at com.Zrips.CMI.commands.list.gamerule.openGui(gamerule.java:244)
[Server thread/WARN]      at com.Zrips.CMI.commands.list.gamerule.perform(gamerule.java:108)
[Server thread/WARN]      at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:385)
[Server thread/WARN]      at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[Server thread/WARN]      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:428)
[Server thread/WARN]      at com.Zrips.CMI.utils.Util.performCommand(Util.java:479)
[Server thread/WARN]      at com.Zrips.CMI.Modules.GUI.GUIManager$1.run(GUIManager.java:184)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65)
[Server thread/WARN]      at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917)
[Server thread/WARN]      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
[Server thread/WARN]      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[Server thread/WARN]      at java.lang.Thread.run(Thread.java:748)
```
---

**Cmi Version :** 8.8.4.2

**Server Type :** Magma 1.12

**Server Version :** 48ec0a1

**Comment by Zrips** [comment]
CMI isint supporting moded servers. Will make some small changes to mitigate some errors relating to GUI, but I cant guarantee that you will not experience issues down the road with other features as CMI was not tested on Magma. Basic things should work, more complex ones could break.

**Comment by DearTanakorn** [comment]
ok i just found way to solve this problem just change from magma to catserver

cmi is work perfectly no more bug
