### ISSUE TITLE
the Jail is eroor 

### ISSUE THREAD

**Issue by nicklly** [Zrips/CMI#5579]
CMI version: 8.8.3.6
CMILib version: 1.0.0.2
Server: paper 1.12.2

the error log: 
`TonyKun issued server command: /cmi jailedit redefineJail 监狱
[12:51:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.3.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Skyblock.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Skyblock.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Skyblock.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Skyblock.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Skyblock.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.Portals.CuboidArea.checkCollision(CuboidArea.java:206) ~[?:?]
        at com.Zrips.CMI.Modules.Jail.CMIJail.checkCollision(CMIJail.java:46) ~[?:?]
        at com.Zrips.CMI.Modules.Jail.JailManager.collidesWithJail(JailManager.java:208) ~[?:?]
        at com.Zrips.CMI.commands.list.jailedit.perform(jailedit.java:238) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:385) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Skyblock.jar:git-Paper-1618]
        ... 15 more
`

**Comment by Zrips** [comment]
Should be fixed with next build
