### ISSUE TITLE
Error dropping player head

### ISSUE THREAD

**Issue by NoChanceSD** [Zrips/CMI#5581]
**Description of issue:**
Error happens sometimes after a player kills another player, I'm guessing when it tries to drop a player head which I enabled but doesn't seem to work. Mob heads do drop though.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[00:11:47 ERROR]: Could not pass event EntityDamageByEntityEvent to CMI v8.8.4.2
java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.PlayerCombat.HeadDropListener.PlayerCombatEvent(HeadDropListener.java:95) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor674.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:253) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1084) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:971) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:927) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1116) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1932) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:959) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1260) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:876) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:1151) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1202) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2180) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2486) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1321) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1314) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1290) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"1382473"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

---

**Cmi Version (using`/cmi version`):** 8.8.4.2 SqLite

**Server Type (Spigot/Paperspigot/etc):** Tuinity 1.16.5-R0.1-SNAPSHOT

**Server Version (using `/ver`):** Tuinity version git-Tuinity-"1382473" (MC: 1.16.5)

**Comment by Zrips** [comment]
Should be resolved with next update
