### ISSUE TITLE
[Bug] Not showing anything, also CMI econemy

### ISSUE THREAD

**Issue by 1ZQ** [Zrips/CMI#560]
Read Desc Of Video
https://youtu.be/CL0qBqICs8A

CMI Version: Freshly downloaded new version
ST: Spigot
SV: Latest Version

**Comment by 1ZQ** [comment]
The "latest" is talking about my server version (1.12.2)(Newest Build) also I litterly cant do cmi version, if you watch the video nothing in the cmi plugin works

**Comment by Zrips** [comment]
Startup log would help too, as this could happen if CMI failed to load in general for one or another reason.

**Comment by 1ZQ** [comment]
Sorry Been Moving lately here is CMI in consle

[22:36:21 INFO]: [CMI] Enabling CMI v7.8.8.0
[22:36:21 INFO]: [CMI] Loaded (4) portals into memory. Took 10ms
[22:36:21 INFO]: [CMI] UltraPermissions plugin will be used
[22:36:22 INFO]: [CMI] Loaded (38) regular alias into memory. Took 60ms
[22:36:22 INFO]: [CMI] Loaded (1) custom text's into memory. Took 11ms
[22:36:22 WARN]: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 1208, column 13:
        MaxLevel:
                ^

[22:36:22 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[22:36:22 WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162)
[22:36:22 WARN]: 	at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:210)
[22:36:22 WARN]: 	at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
[22:36:22 WARN]: 	at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:33)
[22:36:22 WARN]: 	at com.Zrips.CMI.Config.load(Config.java:575)
[22:36:22 WARN]: 	at com.Zrips.CMI.Config.load(Config.java:570)
[22:36:22 WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1325)
[22:36:22 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:36:22 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:36:22 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[22:36:22 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[22:36:22 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[22:36:22 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:36:22 WARN]: Caused by: mapping values are not allowed here
 in 'string', line 1208, column 13:
        MaxLevel:
                ^

[22:36:22 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:872)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
[22:36:22 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
[22:36:22 WARN]: 	... 18 more
[22:36:22 INFO]: [CMI] Failed to load config.yml! Backup have been saved into plugins/CMI/FileBackups/2018-07-03 22-36-22 config.yml
[22:36:22 WARN]: org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 1208, column 13:
        MaxLevel:
                ^

[22:36:22 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
[22:36:22 WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162)
[22:36:22 WARN]: 	at com.Zrips.CMI.FileHandler.ConfigReader.getyml(ConfigReader.java:210)
[22:36:22 WARN]: 	at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
[22:36:22 WARN]: 	at com.Zrips.CMI.FileHandler.ConfigReader.<init>(ConfigReader.java:33)
[22:36:22 WARN]: 	at com.Zrips.CMI.Config.load(Config.java:575)
[22:36:22 WARN]: 	at com.Zrips.CMI.Config.load(Config.java:570)
[22:36:22 WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1325)
[22:36:22 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:36:22 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:36:22 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[22:36:22 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382)
[22:36:22 WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[22:36:22 WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[22:36:22 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:36:22 WARN]: Caused by: mapping values are not allowed here
 in 'string', line 1208, column 13:
        MaxLevel:
                ^

[22:36:22 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:872)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:227)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
[22:36:22 WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
[22:36:22 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
[22:36:22 WARN]: 	... 18 more
[22:36:22 ERROR]: Error occurred while enabling CMI v7.8.8.0 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Zrips.CMI.Config.load(Config.java:584) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:570) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1325) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:382) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:331) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by MCTyler** [comment]
CMI Config file is invalid. Either let it recreate or use a YML Parser to fix it.
