### ISSUE TITLE
Custom Inventories

### ISSUE THREAD

**Issue by arceusxs2** [Zrips/CMI#5612]
Hello, im getting these errors, im using backpack plugin and have some of them with inventories with less slots than 9, is there anything i can do about these errors ?

[17:21:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.8.4.2
java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 5)
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.16.5.jar:git-Purpur-1093]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createInventory(CraftServer.java:1855) ~[patched_1.16.5.jar:git-Purpur-1093]
	at com.Zrips.CMI.Modules.SilentChest.silentChestListener.onPlayerInteract(silentChestListener.java:195) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor547.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1093]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1093]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1093]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1093]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:534) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1834) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1336) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1329) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1305) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1149) ~[patched_1.16.5.jar:git-Purpur-1093]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1093]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by levtey** [comment]
It seems like the player trying to open the backpack is vanished and has silent chests on in /cmi vanishedit (a new inventory is created to mirror the actual chest inventory so that the original is not opened, which in this case is not a normal chest inventory).

A possible fix would be to create the inventory based on the InventoryType first, since this is probably an InventoryType.HOPPER, then using the size in Bukkit.createInventory as a last resort.

**Comment by Zrips** [comment]
Will fix that with next update
