### ISSUE TITLE
BungeeCord plugin messaging error

### ISSUE THREAD

**Issue by Beelzebu** [Zrips/CMI#5622]
**Description of issue:**
I started getting a bungeecord error after updating to CMI 8.8.4.6, from 8.8.2.6, bungeecord is disabled in config. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:26:51 WARN]: [CMI] Plugin CMI v8.8.4.6 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:408) ~[patched_1.16.5.jar:git-Purpur-1127]
        at com.Zrips.CMI.Modules.BungeeCord.CMIBungeeCord.onPluginMessageReceived(CMIBungeeCord.java:436) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:3227) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1331) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1307) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1151) ~[patched_1.16.5.jar:git-Purpur-1127]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1127]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:345) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:406) ~[patched_1.16.5.jar:git-Purpur-1127]
        ... 17 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
BungeeCord:
  # You can disable bungeecord support entirely if you are exrperiencing issues with it
  # When setting this to false some features like public messages over bungee cord, private messages over bungeecord, portals over bungecoord and other features will stop working
  # Keep in mind that regular behavior of those features will remain intacted
  Enabled: false
  # When set to true player names from entire bungee network will be included into tab complete
  NamesInTabComplete: false
```

---

**Cmi Version (using`/cmi version`):** 8.8.4.6

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** git-Purpur-1127 (MC: 1.16.5)

**Comment by Beelzebu** [comment]
Seems to be fixed in 8.8.4.7
