### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by recycie** [Zrips/CMI#5628]
---
[22:20:35 ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.8.4.6
java.lang.IllegalStateException: No format found
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$DecodedFormat.<init>(LegacyComponentSerializerImpl.java:549) ~[patched_1.16.5.jar:git-Purpur-1138]
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$DecodedFormat.<init>(LegacyComponentSerializerImpl.java:543) ~[patched_1.16.5.jar:git-Purpur-1138]
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.decodeTextFormat(LegacyComponentSerializerImpl.java:167) ~[patched_1.16.5.jar:git-Purpur-1138]
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:223) ~[patched_1.16.5.jar:git-Purpur-1138]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.setDisplayName(CraftPlayer.java:392) ~[patched_1.16.5.jar:git-Purpur-1138]
        at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:644) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.updateDisplayName(CMIUser.java:600) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getDisplayNameClean(CMIUser.java:696) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getDisplayName(CMIUser.java:689) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getDisplayName(CMIUser.java:685) ~[?:?]
        at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventExtra(NickNameListener.java:242) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor872.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1138]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1138]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1138]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1138]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:223) ~[patched_1.16.5.jar:git-Purpur-1138]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:105) ~[patched_1.16.5.jar:git-Purpur-1138]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63) ~[patched_1.16.5.jar:git-Purpur-1138]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2232) ~[?:git-Purpur-1138]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2147) ~[?:git-Purpur-1138]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2085) ~[?:git-Purpur-1138]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44) ~[patched_1.16.5.jar:git-Purpur-1138]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

```


**Cmi Version:** 
8.8.4.6

**Server Type:** 
Purpur

**Server Version:** 
1.16.5

**Java Version:**
graalvm-ce-java11-21.1.0

**Comment by recycie** [comment]
Error is solved, Reset config.
