### ISSUE TITLE
/inv dupe #2

### ISSUE THREAD

**Issue by ComPieter-1** [Zrips/CMI#5635]
**Description of issue:**
When opening a players inventory and fast clicking an item (picking it up and placing it in there inventory) It will duplicate.
https://imgur.com/WpBbCcA

**Cmi Version (using`/cmi version`): 8.8.4.6** 

**Server Type (Spigot/Paperspigot/etc): Tuinity** 

**Server Version (using `/ver`): This server is running Tuinity version git-Tuinity-"f0e91a4" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**

**Comment by iLoopBreak** [comment]
@Zrips Related to your fix, at least at 1.8.8 the item is disappearing.

We were testing the inv dupe fix, and we figured out if you keep switching an item between inventories with shift, "fast click actions", there is a chance when you do /inv to make the item disappear, when moving from player inv to chest (maybe with the rest of inventories in general). We have tested it spamming /inv while moving the item between inventories. After that, the console shows up an error message.

The error posted on console:
20:36:52 WARN]: [CMI] Task #5077 for CMI v8.8.4.8 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 10
        at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager$7.run(RegChestManager.java:354) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Min
