### ISSUE TITLE
Error on loading in new 7.8.7.3

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#565]
```
[12:49:36] [Server thread/INFO]: [CMI] Enabling CMI v7.8.7.3
[12:49:37] [Server thread/WARN]: java.lang.NullPointerException
[12:49:37] [Server thread/WARN]: 	at org.bukkit.Location.getBlock(Location.java:91)
[12:49:37] [Server thread/WARN]: 	at com.Zrips.CMI.Containers.CMILocation.getBlock(CMILocation.java:70)
[12:49:37] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.load(SignManager.java:267)
[12:49:37] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.<init>(SignManager.java:59)
[12:49:37] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.getSignManager(CMI.java:650)
[12:49:37] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1192)
[12:49:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[12:49:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[12:49:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[12:49:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[12:49:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[12:49:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[12:49:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[12:49:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[12:49:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[12:49:37] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[12:49:37] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[12:49:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (41) regular alias into memory. Took [0;33;22m33ms[m
[12:49:37] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (1) custom text's into memory. Took [0;33;22m2ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mStarted (SqLite) data base. Took [0;33;22m437ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22m[0;33;22mVault was not found, you will have limited economy support[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (4) kits into memory. Took [0;33;22m126ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (8) cooldowns into memory. Took [0;33;22m2ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (8) warmups into memory. Took [0;33;22m0ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (4) kits into memory. Took [0;33;22m13ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (0) ranks into memory. Took [0;33;22m7ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (9) playtime rewards into memory. Took [0;33;22m4ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (0) Player data into memory. Took [0;33;22m6ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (0) playtime records into memory. Took [0;33;22m0ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (0) playtime reward records into memory. Took [0;33;22m0ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (5) custom alias into memory. Took [0;33;22m4ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mRegistered events. Took [0;33;22m219ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (352) worth values into memory. Took [0;33;22m28ms[m
[12:49:38] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (8) event action commands into memory. Took [0;33;22m11ms[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mUpdated (EN) language file. Took [0;33;22m299ms[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mUpdated (DE_7.7.3.0) language file. Took [0;33;22m237ms[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mCleaning.[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mStarting world timer.[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mInitializing world manager.[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (6) schedules into memory. Took [0;33;22m9ms[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mLoaded (9) skin cache entries into memory. Took [0;33;22m37ms[m
[12:49:39] [Server thread/INFO]: [0;33;22m[CMI] [0;36;22mVersion 7.8.7.3 has been enabled[m
```

![image](https://user-images.githubusercontent.com/12080017/42160385-3f07b284-7df7-11e8-9d52-b0d516da474c.png)

**Comment by MCTyler** [comment]
Thanks, Haven't made it to that Version Yet!

**Comment by CloudeLecaw** [comment]
Edit this error was an outdated Sign in the Signdatabase that was Standing in a not anymore existing world.
removing it worng the dynmaicsing database now solved the Problem, so i closed it.

**Comment by Zrips** [comment]
Well that was fast. Tho will add fail safe to avoid issues like this one in future with console message informing about none existing world.
