### ISSUE TITLE
Server Crash when using /cmi anvil

### ISSUE THREAD

**Issue by FrontierPixelmon** [Zrips/CMI#5659]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[23:44:42] [Server thread/WARN] []: java.lang.reflect.InvocationTargetException                                      
[23:44:42] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)               
[23:44:42] [Server thread/WARN] []:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java$
62)                                                                                                                  
[23:44:42] [Server thread/WARN] []:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorI$
pl.java:43)                                                                                                          
[23:44:42] [Server thread/WARN] []:     at java.lang.reflect.Method.invoke(Method.java:498)                          
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.Reflections.invokeMethod(Reflections.java:1720)             
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.Modules.Anvil.CMIAnvilGUI.open(CMIAnvilGUI.java:330)        
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.Modules.Anvil.CMIAnvilGUI.open(CMIAnvilGUI.java:276)        
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.commands.list.anvil.perform(anvil.java:73)                  
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:393$
[23:44:42] [Server thread/WARN] []:     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)           
[23:44:42] [Server thread/WARN] []:     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153)   
[23:44:42] [Server thread/WARN] []:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.j$
va:689)                                                                                                              
[23:44:42] [Server thread/WARN] []:     at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlaySe$
ver.java:1604)                                                                                                       
[23:44:42] [Server thread/WARN] []:     at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlaySe$
ver.java:1452)                                                                                                       
[23:44:42] [Server thread/WARN] []:     at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacke$
ChatMessage.java:50)                                                                                                 
[23:44:42] [Server thread/WARN] []:     at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacke$
ChatMessage.java:11)                                                                                                 
[23:44:42] [Server thread/WARN] []:     at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(Pac$
etThreadUtil.java:14)                                                                                                
[23:44:42] [Server thread/WARN] []:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)   
[23:44:42] [Server thread/WARN] []:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)                  
[23:44:42] [Server thread/WARN] []:     at net.minecraft.util.Util.func_181617_a(SourceFile:46)                      
[23:44:42] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:92$
)                                                                                                                    
[23:44:42] [Server thread/WARN] []:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServe
r.java:461)
[23:44:42] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865
)
[23:44:42] [Server thread/WARN] []:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[23:44:42] [Server thread/WARN] []:     at java.lang.Thread.run(Thread.java:748)
[23:44:42] [Server thread/WARN] []: Caused by: java.lang.NullPointerException
[23:44:42] [Server thread/WARN] []:     at net.minecraft.inventory.ContainerRepair.getBukkitView(ContainerRepair.java
:509)
[23:44:42] [Server thread/WARN] []:     ... 25 more
[23:44:42] [Server thread/WARN] []: java.lang.NullPointerException
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.Reflections.invokeMethod(Reflections.java:1720)
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.Modules.Anvil.CMIAnvilGUI.open(CMIAnvilGUI.java:330)
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.Modules.Anvil.CMIAnvilGUI.open(CMIAnvilGUI.java:276)
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.commands.list.anvil.perform(anvil.java:73)
[23:44:42] [Server thread/WARN] []:     at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:393$
```

**Cmi Version (using`/cmi version`):** CMI8.8.4.8

**Server Type (Spigot/Paperspigot/etc):** Magma

**Server Version (using `/ver`):** 1.12.2

**Comment by Zrips** [comment]
Magma type server is not officially supported. This command will not work on modded servers due to its complex handling and requiring specific methods to be present. And it should not have crashed your server in particular, it should only show few errors when trying to use this command.
