### ISSUE TITLE
Internal error on /enchant without item

### ISSUE THREAD

**Issue by S4IVin** [Zrips/CMI#5667]
**Description of issue or feature request:**
When i make /enchant [enchanting] [level] without an item in my hand it gives me an internal error, and not a simple error of the plugin.
---

**ERROR:**
```
null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.8.4.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_291]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_8_R3.EnchantmentWeaponDamage.canEnchant(SourceFile:82) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.enchantments.CraftEnchantment.canEnchantItem(CraftEnchantment.java:57) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at com.Zrips.CMI.Modules.CmiItems.CMIItemStack.getValidEnchants(CMIItemStack.java:696) ~[?:?]
        at com.Zrips.CMI.commands.list.enchant.perform(enchant.java:211) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:393) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 15 more
```

---

**Cmi Version (using`/cmi version`):** 8.8.4.8

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** 1.8.8

**Comment by Zrips** [comment]
Should be fixed with next version
