### ISSUE TITLE
Console error when clicking on command line in kit that doesnt exist

### ISSUE THREAD

**Issue by Tobi-Jakka** [Zrips/CMI#5669]
**Description of issue:**
When trying to click on a command for a kit in chat that you have already removed it throws an error in console.

---

**ERROR:**
```
>.... [08:54:20 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.8.4.2
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
at com.Zrips.CMI.Modules.ChatEditor.ChatMessageListEdit$4.run(ChatMessageListEdit.java:180) ~[?:?]
at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.perform(RawMessageManager.java:59) ~[?:?]
at com.Zrips.CMI.Modules.RawMessages.RawMessageListener.onShadowCommand(RawMessageListener.java:47) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1006.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-651]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-651]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-651]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2168) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1991) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1944) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-651]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-651]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

---

**Cmi Version (using`/cmi version`):** 
CMI: 8.8.4.2 SQLite: 8.8.4.8 CMILib: 1.0.0.2
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
paper version git-Paper-651 (1.16.5)

**Comment by Zrips** [comment]
Should be fixed with next build
