### ISSUE TITLE
This might dont need to be reported because we allready aspect an update for 1.17 but well..here it is

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5690]
```
[10:33:17] [Server thread/INFO]: ????? ?????? ????
[10:33:17] [Server thread/INFO]: ????? ? ?? ? ????
[10:33:17] [Server thread/INFO]: ?? ?? ??????  ?? 
[10:33:17] [Server thread/INFO]: ?? ?? ??????  ?? 
[10:33:17] [Server thread/INFO]: ????? ?????? ????
[10:33:17] [Server thread/INFO]: ????? ?????? ????
[10:33:17] [Server thread/INFO]: _______________________________________________________
[10:33:17] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_17_R1
[10:33:17] [Server thread/WARN]: java.lang.ClassNotFoundException: com.Zrips.CMI.NBT.v1_17_R1
[10:33:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[10:33:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[10:33:17] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[10:33:17] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[10:33:17] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[10:33:17] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1342)
[10:33:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:33:17] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[10:33:17] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[10:33:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[10:33:17] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[10:33:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[10:33:17] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[10:33:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[10:33:17] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[10:33:17] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[10:33:17] [Server thread/INFO]:   Loaded (1) holograms into memory. Took 13ms
[10:33:17] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: CMIEconomy
[10:33:17] [Server thread/INFO]:   Loaded (1) dynamic signs into memory. Took 114ms
[10:33:17] [Server thread/INFO]:   Loaded (48) portals into memory. Took 20ms
[10:33:17] [Server thread/INFO]:   Loaded GeoLiteCity
```

in result of this PlaceholderAPI might shows this issue

```
[10:33:26] [Craft Scheduler Thread - 2/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.10-DEV-123 generated an exception while executing task 412
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.DataBase.DBManager.addForSave(com.Zrips.CMI.Containers.CMIUser)" because the return value of "com.Zrips.CMI.CMI.getDbManager()" is null
	at com.Zrips.CMI.Containers.CMIUser.addForDelayedSave(CMIUser.java:316) ~[?:?]
	at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:521) ~[?:?]
	at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.java:494) ~[?:?]
	at com.Zrips.CMI.Modules.Economy.Economy.getBalance(Economy.java:80) ~[?:?]
	at com.Zrips.Economy_CMI.getBalance(Economy_CMI.java:78) ~[?:?]
	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:223) ~[?:?]
	at com.extendedclip.papi.expansion.vault.BalTopTask.run(BalTopTask.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:3101-Spigot-c9cea60-5182f92]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [server.jar:3101-Spigot-c9cea60-5182f92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by mrfloris** [comment]
CMI version 9.0.0.0 will fix this. Which is an early beta build for Spigot 1.17.0
