### ISSUE TITLE
IllegalArgumentException AliasManager

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#5693]
**Description of issue:**
Private message is corrupted if it contains a certain character. Error on console.

This error only happens when the alias for msg is used
Alias.yml
```yaml
  /msg:
    Enabled: true
    Tab: true
```
The problem in the example (see error below) is the `\ ` character.
It also happens if the message contains  `$` (wherever placed in the sentence).

If used in the middle of a sentence the  `\ ` character will be replaced without error

Edit: it also happens in other commands like e.g. `/home blabla'\`

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:21:06] [Server thread/INFO]: Player123abc issued server command: /msg Staffmember123 can you help me with a claim\
[20:21:06] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.8.5.0
java.lang.IllegalArgumentException: character to be escaped is missing
at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1020) ~[?:?]
at java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[?:?]
at java.util.regex.Matcher.replaceFirst(Matcher.java:1408) ~[?:?]
at java.lang.String.replaceFirst(String.java:2096) ~[?:?]
at com.Zrips.CMI.Modules.Alias.AliasManager.updateCommands(AliasManager.java:446) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:100) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor779.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1163]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1163]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1163]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2307) ~[?:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130) ~[?:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083) ~[?:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1469) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1163]
at java.lang.Thread.run(Thread.java:832) [?:?]
[20:21:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'msg Staffmember123 can you help me with a claim\' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(msg)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[patched_1.16.5.jar:git-Purpur-1163]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2315) ~[?:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130) ~[?:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083) ~[?:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1469) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1163]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1163]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1020) ~[?:?]
at java.util.regex.Matcher.appendReplacement(Matcher.java:998) ~[?:?]
at java.util.regex.Matcher.replaceFirst(Matcher.java:1408) ~[?:?]
at java.lang.String.replaceFirst(String.java:2096) ~[?:?]
at com.Zrips.CMI.Modules.Alias.AliasManager.updateCommands(AliasManager.java:446) ~[?:?]
at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:184) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1163]
... 18 more
```

---

**Cmi Version (using`/cmi version`):** 
8.8.5.0
**Server Type (Spigot/Paperspigot/etc):** 
Purpur (fork of paper)
**Server Version (using `/ver`):** 
1.16.5

**Comment by Zrips** [comment]
Fixed with latest builds
