### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by strahil211** [Zrips/CMI#5698]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
[02:13:41 INFO]: LadyGirlPerson issued server command: /msg RiddleDirtGoddes BEEEEEEEEEEEEEE\
[02:13:41 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.8.5.0
java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1019) ~[?:?]
        at java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[?:?]
        at java.util.regex.Matcher.replaceFirst(Matcher.java:1407) ~[?:?]
        at java.lang.String.replaceFirst(String.java:2098) ~[?:?]
        at com.Zrips.CMI.Modules.Alias.AliasManager.updateCommands(AliasManager.java:446) ~[?:?]
        at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:100) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor640.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2259) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2082) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2035) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-"125aff7"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[02:13:41 ERROR]: null
######################
```
---

**Cmi Version (using`/cmi version`):** 
8.8.5.0
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
1.16.5

**Comment by CloudeLecaw** [comment]
Looks like there  a  regex issues from the Chat filter. Your triying to replace one of these longer onces?

**Comment by strahil211** [comment]
> Looks like there a regex issues from the Chat filter. Your triying to replace one of these longer onces?

I have no idea, I didn't really mess with the config and never seen it show this before so it confused me that it just now showed. Happened 4 times when that players was messaging her friend

**Comment by Zrips** [comment]
Gets a fix with next build.
