### ISSUE TITLE
/cmi inv

### ISSUE THREAD

**Issue by arts7493** [Zrips/CMI#5699]
[13:12:38] [Server thread/WARN]: [CMI] Task #1004961 for CMI v8.8.5.0 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 5
	at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager$7.run(RegChestManager.java:354) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-777]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-777]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-777]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Zrips** [comment]
Should be fixed in latest 9.x builds
