### ISSUE TITLE
Updating from 8.5.5.0 to 9.0.0.0 has an issue with CMiLib?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5701]
I got this test on updating in my log.
dont know why? 

```
[19:44:40] [Server thread/INFO]: [CMILib] Enabling CMILib v1.0.1.0
[19:44:43] [Server thread/INFO]: CMI hooked.[m
[19:44:43] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: cmil
[19:44:43] [Server thread/INFO]: PlaceholderAPI hooked.[m
[19:44:43] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning a double-quoted scalar
[19:44:43] [Server thread/WARN]:  in 'string', line 523, column 31:
[19:44:43] [Server thread/WARN]:       commandAddInformationHover: "&e[???]??????????\n&e??\
[19:44:43] [Server thread/WARN]:                                   ^
[19:44:43] [Server thread/WARN]: found unknown escape character ?(35201)
[19:44:43] [Server thread/WARN]:  in 'string', line 524, column 6:
[19:44:43] [Server thread/WARN]:         \?????????,???: \n&edelay 5! \n&e ... 
[19:44:43] [Server thread/WARN]:          ^
[19:44:43] [Server thread/WARN]: 
[19:44:43] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:247)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:48)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILibConfig.importFromCMI(CMILibConfig.java:149)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILibConfig.LoadLang(CMILibConfig.java:281)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILibConfig.LoadLang(CMILibConfig.java:114)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:179)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[19:44:43] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[19:44:43] [Server thread/WARN]: Caused by: while scanning a double-quoted scalar
[19:44:43] [Server thread/WARN]:  in 'string', line 523, column 31:
[19:44:43] [Server thread/WARN]:       commandAddInformationHover: "&e[???]??????????\n&e??\
[19:44:43] [Server thread/WARN]:                                   ^
[19:44:43] [Server thread/WARN]: found unknown escape character ?(35201)
[19:44:43] [Server thread/WARN]:  in 'string', line 524, column 6:
[19:44:43] [Server thread/WARN]:         \?????????,???: \n&edelay 5! \n&e ... 
[19:44:43] [Server thread/WARN]:          ^
[19:44:43] [Server thread/WARN]: 
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1965)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1901)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1048)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1030)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:415)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:633)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:309)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:300)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[19:44:43] [Server thread/WARN]: 	... 17 more
[19:44:43] [Server thread/INFO]: [0;31;1mFailed to load Locale_CN.yml! Backup have been saved into plugins\CMILib\FileBackups\2021-06-14 19-44-43 Locale_CN.yml[m
[19:44:43] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while scanning a double-quoted scalar
[19:44:43] [Server thread/WARN]:  in 'string', line 523, column 31:
[19:44:43] [Server thread/WARN]:       commandAddInformationHover: "&e[???]??????????\n&e??\
[19:44:43] [Server thread/WARN]:                                   ^
[19:44:43] [Server thread/WARN]: found unknown escape character ?(35201)
[19:44:43] [Server thread/WARN]:  in 'string', line 524, column 6:
[19:44:43] [Server thread/WARN]:         \?????????,???: \n&edelay 5! \n&e ... 
[19:44:43] [Server thread/WARN]:          ^
[19:44:43] [Server thread/WARN]: 
[19:44:43] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:247)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:48)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILibConfig.importFromCMI(CMILibConfig.java:149)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILibConfig.LoadLang(CMILibConfig.java:281)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILibConfig.LoadLang(CMILibConfig.java:114)
[19:44:43] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:179)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[19:44:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[19:44:43] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[19:44:43] [Server thread/WARN]: Caused by: while scanning a double-quoted scalar
[19:44:43] [Server thread/WARN]:  in 'string', line 523, column 31:
[19:44:43] [Server thread/WARN]:       commandAddInformationHover: "&e[???]??????????\n&e??\
[19:44:43] [Server thread/WARN]:                                   ^
[19:44:43] [Server thread/WARN]: found unknown escape character ?(35201)
[19:44:43] [Server thread/WARN]:  in 'string', line 524, column 6:
[19:44:43] [Server thread/WARN]:         \?????????,???: \n&edelay 5! \n&e ... 
[19:44:43] [Server thread/WARN]:          ^
[19:44:43] [Server thread/WARN]: 
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1965)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1901)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1048)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1030)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:415)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:633)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:309)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:300)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[19:44:43] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[19:44:43] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[19:44:43] [Server thread/WARN]: 	... 17 more
```

**Comment by mrfloris** [comment]
It helps if you include a bit of info.

paper 1.16.5 to spigot 1.17, with cmi 8.what? to cmi 9 ? ..

**Comment by mrfloris** [comment]
he said:

M] Cloude_Lecaw: from last 8.5.5.5.0 cmi to 9.0.0.0 cmi and from the CMILib 1.0.02  to 1.0.1.0 on my local testserver with J16.01 and  Spigot 1.17

**Comment by CloudeLecaw** [comment]
it also looks like its coming from the Chiniese CN file
This file allways gets copied to backup folder.
The lines are:
```
  commandAddInformationHover: "&e[玩家名]可用于获取玩家昵称。\n&e要在\
    \要在命令中包含延迟,请键入: \n&edelay 5! \n&e同时也支持特定指令。\
    \更多信息请参见\n&ewww.spigotmc.org/wiki/cmi-specialized-commands/"
  commandEditInfo: '&e点击粘贴旧文本。键入&6cancel&e取消操作。请键入&6remove&e移除行'
```

**Comment by mrfloris** [comment]
I think it tried to convert it because it has to move things out of the cmi8 into cmilib for cmi9

**Comment by CloudeLecaw** [comment]
Well  on other Offlien server where i was updating to 9.0.0.0 from older CMI the issue seems not accour.
So here is the file if you also have this problem...
can be placed inside CMILibs\translation folder then this issue is fixed (well this still means the CMI CN langfile might be corrupet on some update..)
[Locale_CN.yml.txt](https://github.com/Zrips/CMI/files/6653303/Locale_CN.yml.txt)
