### ISSUE TITLE
Cannot jail offline player

### ISSUE THREAD

**Issue by Ultrasonic1209** [Zrips/CMI#5706]
**Description of issue:**
I jailed someone who went offline. They rejoined and I unjailed them. They then left again, and jailing them led to an internal error.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:26:37] [Server thread/INFO]: FlyFoxKurama lost connection: Disconnected
[13:26:37] [Server thread/INFO]: FlyFoxKurama left the game
[13:26:43] [Server thread/INFO]: Ultrasonic54321 issued server command: /jail flyfoxkurama 30d
[13:26:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1944) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1783) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1764) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1125) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1118) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1102) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1031) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null
        at net.Zrips.CMILib.BossBar.BossBarManager.getBossBarInfo(BossBarManager.java:355) ~[?:?]
        at net.Zrips.CMILib.BossBar.BossBarManager.getBossBar(BossBarManager.java:348) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getBossBar(CMIUser.java:2128) ~[?:?]
        at com.Zrips.CMI.Modules.Jail.JailManager.placePlayerIntoJail(JailManager.java:614) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.jail(CMIUser.java:2418) ~[?:?]
        at com.Zrips.CMI.commands.list.jail.perform(jail.java:126) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:395) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:3141-Spigot-66f9d3c-72a2901]
        ... 19 more
```

---

**Cmi Version (using`/cmi version`):** 

![image](https://user-images.githubusercontent.com/44583181/122053120-5d7f7500-cdde-11eb-809f-6c127e86b623.png)

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 

![image](https://user-images.githubusercontent.com/44583181/122053183-6cfebe00-cdde-11eb-821f-42b880ec2028.png)

**Comment by mrfloris** [comment]
Nice error, do you also get it when you follow the syntax of the command btw? Or only when the input is technically wrong?

`Usage: /cmi jail [playerName] (time) (jailName) (cellId) (-s) (r:jail_reason)`

`/cmi jail Notch 30d JailNameThing 1 r:making_minecraft`

**Comment by Ultrasonic1209** [comment]
I still do.

![image](https://user-images.githubusercontent.com/44583181/122054468-9c61fa80-cddf-11eb-9e2e-27d73cde7691.png)

**Comment by mrfloris** [comment]
Thank you for the update, helpful!

**Comment by Zrips** [comment]
Will be fixed with next update
