### ISSUE TITLE
TryMe Error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5727]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[01:46:30] [Server thread/INFO]: [Tryme] Loaded 100 Questions in 1 categories
[01:46:30] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:me.Zrips.TryMe.Constructors.GameMode
[01:46:30] [Server thread/WARN]:  in 'string', line 5, column 11:
[01:46:30] [Server thread/WARN]:         Mode: &id001 !!me.Zrips.TryMe.Construc ... 
[01:46:30] [Server thread/WARN]:               ^
[01:46:30] [Server thread/WARN]: 
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[01:46:30] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:247)
[01:46:30] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:48)
[01:46:30] [Server thread/WARN]: 	at me.Zrips.TryMe.ConfigFile.LoadPendingRewards(ConfigFile.java:122)
[01:46:30] [Server thread/WARN]: 	at me.Zrips.TryMe.ConfigFile.reloading(ConfigFile.java:1465)
[01:46:30] [Server thread/WARN]: 	at me.Zrips.TryMe.TryMe.onEnable(TryMe.java:451)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:504)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:418)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:294)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1071)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[01:46:30] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[01:46:30] [Server thread/WARN]: Caused by: could not determine a constructor for the tag tag:yaml.org,2002:me.Zrips.TryMe.Constructors.GameMode
[01:46:30] [Server thread/WARN]:  in 'string', line 5, column 11:
[01:46:30] [Server thread/WARN]:         Mode: &id001 !!me.Zrips.TryMe.Construc ... 
[01:46:30] [Server thread/WARN]:               ^
[01:46:30] [Server thread/WARN]: 
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:574)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[01:46:30] [Server thread/WARN]: 	... 16 more
[01:46:30] [Server thread/INFO]: Failed to load PendingRewards.yml! Backup have been saved into plugins/CMILib/FileBackups/2021-06-21 01-46-30 PendingRewards.yml
[01:46:30] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:me.Zrips.TryMe.Constructors.GameMode
[01:46:30] [Server thread/WARN]:  in 'string', line 5, column 11:
[01:46:30] [Server thread/WARN]:         Mode: &id001 !!me.Zrips.TryMe.Construc ... 
[01:46:30] [Server thread/WARN]:               ^
[01:46:30] [Server thread/WARN]: 
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[01:46:30] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:247)
[01:46:30] [Server thread/WARN]: 	at net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:48)
[01:46:30] [Server thread/WARN]: 	at me.Zrips.TryMe.ConfigFile.LoadPendingRewards(ConfigFile.java:122)
[01:46:30] [Server thread/WARN]: 	at me.Zrips.TryMe.ConfigFile.reloading(ConfigFile.java:1465)
[01:46:30] [Server thread/WARN]: 	at me.Zrips.TryMe.TryMe.onEnable(TryMe.java:451)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:504)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:418)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:294)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1071)
[01:46:30] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[01:46:30] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[01:46:30] [Server thread/WARN]: Caused by: could not determine a constructor for the tag tag:yaml.org,2002:me.Zrips.TryMe.Constructors.GameMode
[01:46:30] [Server thread/WARN]:  in 'string', line 5, column 11:
[01:46:30] [Server thread/WARN]:         Mode: &id001 !!me.Zrips.TryMe.Construc ... 
[01:46:30] [Server thread/WARN]:               ^
[01:46:30] [Server thread/WARN]: 
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:574)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
[01:46:30] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[01:46:30] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[01:46:30] [Server thread/WARN]: 	... 16 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# DO NOT EDIT THIS FILE BY HAND!
PendingRewards:
  '1':
    Uuid: cff82788-7a44-3c9a-8bcd-c1c3df32af88
    Mode: &id001 !!me.Zrips.TryMe.Constructors.GameMode {}
    Place: 1
    SchedulerName: ThisIsMonthly
  '2':
    Uuid: 5553031b-9bb0-32e3-b851-c2c0461d2765
    Mode: *id001
    Place: 4
    SchedulerName: ThisIsMonthly
  '3':
    Uuid: 7988b360-d5d5-34ed-8a27-9604a8e93d50
    Mode: *id001
    Place: 5
    SchedulerName: ThisIsMonthly
  '4':
    Uuid: 17778345-86ea-3f78-8c1e-4abc91691f90
    Mode: *id001
    Place: 7
    SchedulerName: ThisIsMonthly
  '5':
    Uuid: f455539c-0ad2-3fcd-952c-637cbcd1933e
    Mode: *id001
    Place: 8
    SchedulerName: ThisIsMonthly
  '6':
    Uuid: 995fae87-a6e5-344e-bfc0-3c4b6d950c59
    Mode: *id001
    Place: 10
    SchedulerName: ThisIsMonthly

```

---

**TryMe Version (using`/cmi version`):** 7.0.0.0

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
Will fix with next build. For time being you will need to clear out this file due to corrupted data in it causing issues.
