### ISSUE TITLE
java.lang.NoSuchMethodError: com.Zrips.CMI.Modules.Warps.CmiWarp.getLoc()Lcom/Zrips/CMI/Containers/CMILocation;

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#5732]
**Description of issue:**
Exception when try to use `CmiWarp#getLoc()...`

My code:
```
List<CmiWarp> warps = CMI.getInstance().getWarpManager().getWarps((Player)sender);
if(warps.size() == 0) {
    sender.sendMessage("§cYou don't have any warps!");
    return true;
} else {
    for(CmiWarp warp : warps) {
        if(warp.getCreator().equals(((Player)sender).getUniqueId())) {
            String loc = "%x%x %y%y %z%z %world% world";
            loc = loc
                    .replace("%x%", "" + warp.getLoc().getBlockX())
                    .replace("%y%", "" + warp.getLoc().getBlockY())
                    .replace("%z%", "" + warp.getLoc().getBlockZ())
                    .replace("%world%", warp.getLoc().getWorldName());
            TextComponent tc = new TextComponent("§e" + warp.getName() + " §2- §a" + loc);
                    tc.setClickEvent(new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND,
                            "/warp " + warp.getName()));
            sender.sendMessage(tc);
        }
    }
}
```

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
org.bukkit.command.CommandException: Unhandled exception executing command 'mywarps' in plugin CMIWarpsChecker v1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-1135]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1135]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:827) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2315) ~[?:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2130) ~[?:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2083) ~[?:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1338) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1331) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1307) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1151) ~[patched_1.16.5.jar:git-Purpur-1135]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1135]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: com.Zrips.CMI.Modules.Warps.CmiWarp.getLoc()Lcom/Zrips/CMI/Containers/CMILocation;
        at ru.ibusewinner.fundaily.cmiwarpschecker.CMIWarpsChecker.onCommand(CMIWarpsChecker.java:145) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-1135]
        ... 19 more
```

---

**Cmi Version (using`/cmi version`):** 9.0.0.1

**Server Type (Spigot/Paperspigot/etc):** Purpur

**Server Version (using `/ver`):** This server is running Purpur version git-Purpur-1135 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** Custom

**Comment by Zrips** [comment]
As of 9.x version core things from plugins like CMI got moved into CMILib, this would include CMILocation object. You will need to update plugin to properly import net.Zrips.CMILib.Container.CMILocation class instead of old one.
