### ISSUE TITLE
ConcurrentModificationException bungee placeholders in async tablist

### ISSUE THREAD

**Issue by radiant-ai** [Zrips/CMI#5742]
**Description of issue:**

Parsing of some placeholders async causes `ConcurrentModificationException`.  In `tabList.yml`: `Async: true`.
(Used placeholders: `%cmi_bungee_onlinestatus_lobby%` / `%cmi_bungee_current_lobby%` / `%cmi_bungee_total_lobby%`
This might be an expected behaviour though (placeholders cannot run async), in such a case please close the issue.

---

**ERROR:**
```
[07:16:30 WARN]: java.util.ConcurrentModificationException
[07:16:30 WARN]:        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1584)
[07:16:30 WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1617)
[07:16:30 WARN]:        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1615)
[07:16:30 WARN]:        at java.base/java.util.HashMap.putMapEntries(HashMap.java:513)
[07:16:30 WARN]:        at java.base/java.util.HashMap.<init>(HashMap.java:486)
[07:16:30 WARN]:        at com.Zrips.CMI.Modules.BungeeCord.BungeeCordServer.update(BungeeCordServer.java:104)
[07:16:30 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1720)
[07:16:30 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:785)
[07:16:30 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:635)
[07:16:30 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:560)
[07:16:30 WARN]:        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:451)
[07:16:30 WARN]:        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:777)
[07:16:30 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[07:16:30 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
[07:16:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:16:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[07:16:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[07:16:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

---

**Cmi Version (using`/cmi version`):** 
8.9.5.0, 9.0.2 
**Server Type (Spigot/Paperspigot/etc):** 
Purpur
**Server Version (using `/ver`):** 
This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Should be resolved with next update
