### ISSUE TITLE
VotifierEvent sometimes stuck..in 9.0.0.3

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5751]
The issues happen sometimes after a player voted.

```
>.... [21:27:12 ERROR]: Could not pass event VotifierEvent to CMI v9.0.0.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:795) ~[patched_1.17.jar:git-Paper-49]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:902) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:864) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:254) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:222) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:175) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:137) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor850.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-49]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-49]
at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-49]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because "this.entity.t" is null
at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.getWorld(CraftEntity.java:502) ~[patched_1.17.jar:git-Paper-49]
at com.Zrips.CMI.Modules.Kits.KitsManager.processText(KitsManager.java:780) ~[?:?]
at com.Zrips.CMI.Modules.Kits.Kit.getItems(Kit.java:111) ~[?:?]
at com.Zrips.CMI.Modules.Kits.KitsManager.giveKit(KitsManager.java:1340) ~[?:?]
at com.Zrips.CMI.commands.list.kit.perform(kit.java:184) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Paper-49]
... 25 more
>.... [21:27:16 INFO]: [Votifier] Got a protocol v1 vote record from /5.83.162.202:33502 -> Vote (from:minecraft-serverlist.net username:ItzMaxGamesToday address:93.223.210.32 timeStamp:1624822036 additionalData:null)
>.... [21:27:16 ERROR]: Could not pass event VotifierEvent to CMI v9.0.0.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:795) ~[patched_1.17.jar:git-Paper-49]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:902) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:864) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:254) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:222) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:175) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:137) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor850.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-49]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-49]
at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-49]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
>.... [21:27:17 INFO]: [Votifier] Got a protocol v1 vote record from /45.33.29.47:40742 -> Vote (from:MCSL username:ItzMaxGamesToday address:93.223.210.32 timeStamp:1624822037 additionalData:null)
>.... [21:27:17 ERROR]: Could not pass event VotifierEvent to CMI v9.0.0.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:795) ~[patched_1.17.jar:git-Paper-49]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:902) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:864) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:254) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:222) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:175) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:137) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor850.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-49]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-49]
at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-49]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
>.... [21:27:58 INFO]: [Votifier] Got a protocol v1 vote record from /192.99.101.31:51242 -> Vote (from:TopG.org username:ItzMaxGamesToday address:93.223.210.32 timeStamp:1624822078 additionalData:null)
>.... [21:27:58 ERROR]: Could not pass event VotifierEvent to CMI v9.0.0.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:795) ~[patched_1.17.jar:git-Paper-49]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:902) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:864) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:254) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:222) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:175) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:137) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor850.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-49]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-49]
at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-49]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
>.... [21:28:03 INFO]: [Votifier] Got a protocol v1 vote record from /149.202.74.183:48320 -> Vote (from:Minecraft-MP.com username:ItzMaxGamesToday address:93.223.210.32 timeStamp:1624822084 additionalData:null)
>.... [21:28:03 ERROR]: Could not pass event VotifierEvent to CMI v9.0.0.2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:795) ~[patched_1.17.jar:git-Paper-49]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:902) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:864) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:254) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:222) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:175) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:137) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor850.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-49]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-49]
at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-49]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-49]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-49]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
>.... [21:28:07 INFO]: [Votifier] Got a protocol v1 vote record from /188.68.47.181:34306 -> Vote (from:serverliste.net username:ItzMaxGamesToday address:93.223.210.32 timeStamp:1624822087 additionalData:null)
```
---

**Cmi Version (using`/cmi version`):** 
Cmi 9.0.0.2, NuVotifer 3.0.0 Build 36
**Server Type (Spigot/Paperspigot/etc):** 
Papermc
**Server Version (using `/ver`): Paper 1.17 Build 46

**Comment by CloudeLecaw** [comment]
still apears sometimes in 9.0.0.3

```
>.... [20:58:04 ERROR]: Could not pass event VotifierEvent to CMI v9.0.0.3
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Paper-55]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.jar:git-Paper-55]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Paper-55]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:795) ~[patched_1.17.jar:git-Paper-55]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:902) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:864) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:254) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:222) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:175) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierManager.processVote(VotifierManager.java:137) ~[?:?]
at com.Zrips.CMI.Modules.Votifier.VotifierListener.VotifierEvent(VotifierListener.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor856.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Paper-55]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Paper-55]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Paper-55]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Paper-55]
at com.vexsoftware.votifier.NuVotifierBukkit.fireVotifierEvent(NuVotifierBukkit.java:372) ~[?:?]
at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:341) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-55]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.17.jar:git-Paper-55]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1488) ~[patched_1.17.jar:git-Paper-55]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[patched_1.17.jar:git-Paper-55]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1404) ~[patched_1.17.jar:git-Paper-55]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[patched_1.17.jar:git-Paper-55]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-55]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException
>.... [20:58:12 INFO]: [Votifier] Got a protocol v1 vote record from /149.202.74.183:57036 -> Vote (from:Minecraft-MP.com username:ItzMaxGamesToday address:93.223.210.32 timeStamp:1624906694 additionalData:null)
```

**Comment by CloudeLecaw** [comment]
Ok this seems to be Happen when updating to 1.17 and may having a new world and the voted player never loged into the server.
I forced all players from not existing worlds to tp to spawn. Well seems to solve this issue. So i can close it.
