### ISSUE TITLE
CMI 9.0.0.3 Error with /cmi command

### ISSUE THREAD

**Issue by Speedspencer** [Zrips/CMI#5761]
**Description of issue or feature request:**
I believe that this only happens with cmi toast message option (not the command but the option to transform any message into a toast message in config)
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################

[23:17:45 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.jar:git-Purpur-1204]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.jar:git-Purpur-1204]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2315) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2126) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2107) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1360) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1271) ~[patched_1.17.jar:git-Purpur-1204]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-Purpur-1204]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: advancement
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.17.jar:git-Purpur-1204]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:2148) ~[patched_1.17.jar:git-Purpur-1204]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.grant(CMIAdvancement.java:197) ~[?:?]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:173) ~[?:?]
        at net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:127) ~[?:?]
        at net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:85) ~[?:?]
        at net.Zrips.CMILib.Messages.CMIMultiMessage.show(CMIMultiMessage.java:195) ~[?:?]
        at com.Zrips.CMI.CMI.sendMessage(CMI.java:2100) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:176) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.jar:git-Purpur-1204]
        ... 21 more

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
#####################################
```
I can't find a config that I used in 1.16.5 before I moved to 1.17
---

**Cmi Version (using`/cmi version`):** 

--------------------------------------------------
CMI: 9.0.0.3 SQLite
CMILib: 1.0.2.4
Server: Purpur 1.17-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 54 enabled 2 disabled: tablist, votifier
--------------------------------------------------
**Server Type (Spigot/Paperspigot/etc):** 

Purpur 1.17

**Server Version (using `/ver`):** 

This server is running Purpur version git-Purpur-1204 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: b4e0fc7 on HEAD)

**Comment by Zrips** [comment]
Will be fixed with next CMILib build
