### ISSUE TITLE
[bug] yaw on armorstand gives exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#5781]
```
[21:37:10 WARN]: java.lang.NoSuchFieldException: yaw
[21:37:10 WARN]:        at java.base/java.lang.Class.getField(Class.java:2086)
[21:37:10 WARN]:        at com.Zrips.CMI.Modules.AStand.ArmorStandManager.duplicate(ArmorStandManager.java:1021)
[21:37:10 WARN]:        at com.Zrips.CMI.Modules.AStand.ArmorStandCopy.duplicateOn(ArmorStandCopy.java:48)
[21:37:10 WARN]:        at com.Zrips.CMI.Modules.AStand.ArmorStandListener.onPlayerInteractAtEntityEvent(ArmorStandListener.java:101)
[21:37:10 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1084.execute(Unknown Source)
[21:37:10 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:37:10 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:37:10 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:37:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[21:37:10 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2350)
[21:37:10 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2405)
[21:37:10 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$e.a(PacketPlayInUseEntity.java:161)
[21:37:10 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[21:37:10 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2342)
[21:37:10 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[21:37:10 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[21:37:10 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[21:37:10 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:37:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[21:37:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[21:37:10 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[21:37:10 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[21:37:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[21:37:10 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[21:37:10 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[21:37:10 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[21:37:10 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273)
[21:37:10 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184)
[21:37:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:37:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:37:17 WARN]: java.lang.NoSuchFieldException: yaw
[21:37:17 WARN]:        at java.base/java.lang.Class.getField(Class.java:2086)
[21:37:17 WARN]:        at com.Zrips.CMI.Modules.AStand.ArmorStandManager.duplicate(ArmorStandManager.java:1021)
[21:37:17 WARN]:        at com.Zrips.CMI.Modules.AStand.ArmorStandCopy.duplicateOn(ArmorStandCopy.java:48)
[21:37:17 WARN]:        at com.Zrips.CMI.Modules.AStand.ArmorStandListener.onPlayerInteractAtEntityEvent(ArmorStandListener.java:101)
[21:37:17 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1084.execute(Unknown Source)
[21:37:17 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:37:17 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:37:17 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:37:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[21:37:17 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2350)
[21:37:17 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2405)
[21:37:17 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$e.a(PacketPlayInUseEntity.java:161)
[21:37:17 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[21:37:17 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2342)
[21:37:17 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[21:37:17 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[21:37:17 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[21:37:17 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:37:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[21:37:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[21:37:17 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1340)
[21:37:17 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[21:37:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[21:37:17 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1319)
[21:37:17 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1312)
[21:37:17 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[21:37:17 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1273)
[21:37:17 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1184)
[21:37:17 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:37:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
>
```
I've noticed this in console when someone's now what I assume is an armorstand. 

```
> cmi version
[21:39:58 INFO]: --------------------------------------------------
[21:39:58 INFO]: CMI plugin version: 9.0.0.4 SqLite-> 9.0.0.3
[21:39:58 INFO]: CMILib: 1.0.2.5
[21:39:58 INFO]: Server: Paper(66) 1.17-R0.1-SNAPSHOT
[21:39:58 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[21:39:58 INFO]: Modules -> 55 enabled 1 disabled: flightCharge
[21:39:58 INFO]: --------------------------------------------------
> ver
[21:39:59 INFO]: Checking version, please wait...
[21:40:00 INFO]: This server is running Paper version git-Paper-66 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 31d8fd5)
You are running the latest version
Previous version: git-Paper-65 (MC: 1.17)
>
```
java16

**Comment by Zrips** [comment]
Gets a fix with next version
