### ISSUE TITLE
CMI swears at placeholders

### ISSUE THREAD

**Issue by catfishua** [Zrips/CMI#5788]
Description of issue: Good afternoon, placeholders stopped working on my 1.17 version of minecraft, due to an error that the plugin
CMI spams into the server console with incredible speed, for placeholders I use the PlaceholderAPI plugin, while in the tab, half of the placeholders work and half of the placeholders do not work

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:30:27 FATAL]: Thread Craft Scheduler Thread - 31 - CMI failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Paper-"d28f4bf"]
        at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2335) ~[patched_1.17.jar:git-Paper-"d28f4bf"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getEntities(CraftWorld.java:1172) ~[patched_1.17.jar:git-Paper-"d28f4bf"]
        at com.extendedclip.papi.expansion.server.ServerExpansion.onRequest(ServerExpansion.java:190) ~[?:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97) ~[?:?]
        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:586) ~[?:?]
        at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:451) ~[?:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:771) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"d28f4bf"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.jar:git-Paper-"d28f4bf"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"d28f4bf"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

---

CMI Version: 9.0.0.4

Server Type: Patina fork https://github.com/PatinaMC/Patina

Server Version: Patina version git-Paper-"d28f4bf" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

Relevant plugins: AsyncWorldEdit, BookAuthorStatus, Brewery, ChatControl, CMI, CMILib, CoreProtect, CoreProtectTNT, F3Name, HideTags, LightChatBubbles, MineAlerts, NashornPlus, NickNameShow, PermissionsEx, PL-Hide-Pro, PlaceholderAPI, PlugMan, ProtocolLib, PunishControl, ReloadBlocker, Restarter, RPChat, ShiftSit, SimpleLay, SimplixCore, Spartan, Spitty, Vault, WorldEdit

**Comment by Zrips** [comment]
You might want to switch Async mode in tablist config file to false. Async updates causes issues with some of the placeholders you are trying to use. From error log looks to be related to entity count check. You might want to remove that one or go with sync mode.
