### ISSUE TITLE
Actionbar error? with CMILIB? - 1.0.2.7

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5815]
Since last version of CMILIB we have this issue

```
>.... [22:26:33 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "player" is null
>.... [22:26:33 WARN]: at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:146)
>.... [22:26:33 WARN]: at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:101)
>.... [22:26:33 WARN]: at net.Zrips.CMILib.ActionBar.CMIActionBar.send(CMIActionBar.java:97)
>.... [22:26:33 WARN]: at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:176)
>.... [22:26:33 WARN]: at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:48)
```

![image](https://user-images.githubusercontent.com/12080017/124550206-9f756700-de30-11eb-908b-1f474edb1a7f.png)

looks like it has to do with jobs or might be causes by jobs?

**Comment by CloudeLecaw** [comment]
Should be fixed with next version of cmilib :)
