### ISSUE TITLE
PatternSyntaxException when using special character (*) in nickname (Bedrock players trough GeyserMC)

### ISSUE THREAD

**Issue by Baterka** [Zrips/CMI#5816]
**Description of issue:**
CMI spits `PatternSyntaxException` when using special character (*) in nickname because Bedrock players trough GeyserMC have `*` prefix in nickname.

---

**ERROR:**
```
[01:22:27 ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.8.5.0
[01:22:27 ERROR]: Suspected Plugins:
[01:22:27 ERROR]:       CMI{enabled,ver=8.8.5.0,path=plugins/CMI8.8.5.0.jar}
[01:22:27 ERROR]: Exception details below:
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*SquashyCurve0
^
        at java.util.regex.Pattern.error(Pattern.java:2027) ~[?:?]
        at java.util.regex.Pattern.sequence(Pattern.java:2202) ~[?:?]
        at java.util.regex.Pattern.expr(Pattern.java:2068) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1782) ~[?:?]
        at java.util.regex.Pattern.<init>(Pattern.java:1428) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1068) ~[?:?]
        at java.lang.String.split(String.java:2317) ~[?:?]
        at com.Zrips.CMI.Modules.ChatTag.TagManager.tag(TagManager.java:116) ~[?:?]
        at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventExtra(NickNameListener.java:227) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor918.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:223) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:105) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:63) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:2229) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2144) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2082) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44) ~[patched_1.16.5.jar:git-Yatopia-staging/1.16.5-"22be9f2"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

```
---

**Cmi Version (using`/cmi version`): 8.8.5.0** 

**Server Type (Spigot/Paperspigot/etc): Yatopia** 

**Server Version (using `/ver`): Yatopia version git-Yatopia-staging/1.16.5-"22be9f2" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)**

**Comment by Zrips** [comment]
Should be fixed with next build
