### ISSUE TITLE
/rt (random teleport) can't find correct location on 1.17 (FATAL ERROR)

### ISSUE THREAD

**Issue by strahil211** [Zrips/CMI#5819]
/rt (random teleport) can't find suitable location on 1.17
rt used to work well everywhere except the Nether it could never find a safe spot, now it won't work in any world. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[18:20:57 FATAL]: Thread Craft Scheduler Thread - 315 - CMI failed thread check for reason: Asynchronous chunk load
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.jar:git-Airplane-40]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.loadChunk(CraftWorld.java:600) ~[patched_1.17.jar:git-Airplane-40]
        at org.bukkit.craftbukkit.v1_17_R1.CraftChunk.load(CraftChunk.java:179) ~[patched_1.17.jar:git-Airplane-40]
        at net.Zrips.CMILib.Items.CMIMaterial.get(CMIMaterial.java:1696) ~[?:?]
        at com.Zrips.CMI.Containers.CMIBlock.isWaterlogged(CMIBlock.java:108) ~[?:?]
        at com.Zrips.CMI.Modules.tp.Teleportations.getRandomLocation(Teleportations.java:1714) ~[?:?]
        at com.Zrips.CMI.commands.list.rt$1.run(rt.java:104) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Airplane-40]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.jar:git-Airplane-40]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Airplane-40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
RandomTeleportation:
  # If this set to true we will generate random teleport default settings for all detected worlds
  # Setting to false will not longer generate world setups, but you can add them manually if needed
  AutoGenerateWorlds: false
  Worlds:
    # World name to use this feature. Add annother one with appropriate name to enable random teleportation
    world_nether:
      Enabled: true
      # Max coordinate to teleport, setting to 1000, player can be teleported between -1000 and 1000 coordinates
      MaxRange: 9990
      # If maxcord set to 1000 and mincord to 500, then player can be teleported between -1000 to -500 and 1000 to 500 coordinates
      MinRange: 100
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: false
      minY: 20
      maxY: 120
    world:
      Enabled: true
      MaxRange: 29990
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
    world_the_end:
      Enabled: true
      MaxRange: 14990
      MinRange: 500
      CenterX: 0
      CenterZ: 0
      Circle: false
      IgnoreWater: true
      IgnoreLava: true
      minY: 0
      maxY: 256
  # How long force player to wait before using command again.
  Cooldown: 10
  # How many times to try find correct location for teleportation.
  # Keep it at low number, as player always can try again after delay
  MaxTries: 20
  # List of biomes to exclude from random teleportation
  ExcludedBiomes:
  - Ocean
  - Deep ocean
```

---

Cmi Version (using`/cmi version`): 9.0.0.7

Server Type (Spigot/Paperspigot/etc): Airplane (Fork of Tuinity, fork of Paper)

Server Version (using `/ver`): 1.17

**Comment by mrfloris** [comment]
https://pastebin.com/6gnurg7r

both ppl said latest cmilib.

**Comment by strahil211** [comment]
Yes
CMILIB 1.0.2.8

**Comment by mrfloris** [comment]
You can try to set cmilib/config.yml to false so it doesn't auto update, and try /stop and get 1.0.2.7 and start again, see if that works.

**Comment by Zrips** [comment]
Fixed with .9 CMILib and next version will receive update relating to this to improve entire mechanic
