### ISSUE TITLE
Spam of an Issue in 1.17.1 after login

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5824]
CMILIb 1.0.2.10
CMI 9.0.0.8
Paper 1.17.1 Build 88

After login this error got spammed

```
[19:17:23] [Craft Scheduler Thread - 39/WARN]: [CMI] Plugin CMI v9.0.0.8 generated an exception while executing task 26114
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:506) ~[patched_1.17.1.jar:git-Paper-88]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeyIterator.next(Object2ObjectOpenHashMap.java:728) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:434) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftMetaLeatherArmor.<init>(CraftMetaLeatherArmor.java:32) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:303) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:273) ~[patched_1.17.1.jar:git-Paper-88]
	at com.Zrips.CMI.Modules.Animations.AnimationManager.setColor(AnimationManager.java:256) ~[?:?]
	at com.Zrips.CMI.Modules.Animations.AnimationManager.access$2(AnimationManager.java:220) ~[?:?]
	at com.Zrips.CMI.Modules.Animations.AnimationManager$2.run(AnimationManager.java:212) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-88]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-88]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-88]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

The error was repeating until my server crashed

**Comment by mrfloris** [comment]
Hasn't happened on my servers yet, I will keep an eye out.

**Comment by Zrips** [comment]
This looks more like a paper bug as its failing on basic `item.getItemMeta()` for leather armor which are set to biome type colors

**Comment by CloudeLecaw** [comment]
ahh could be i was wearing the leather armor... i think the biom one

**Comment by Zrips** [comment]
It should still not produce this error, will introduce extra check which would resolve this specific issue, but you might have some what broken item in your hands due to which this error happen

**Comment by CloudeLecaw** [comment]
well i removed the whole set after u told it has to do with getting the color on leather from catching biom..
i was wearing a full biom dyed lether set

**Comment by Zrips** [comment]
Will fix with next version, even tho this should not have happen in normal situations will add basic check to avoid from this error reappearing in future.
