### ISSUE TITLE
Issue with holograms.

### ISSUE THREAD

**Issue by MarcussGTX** [Zrips/CMI#5832]
**Description of issue :**

Creating a hologram or just having a hologram creates error on reload, or when getting close to hologram. Holograms also appears to accumulate over time if player stands near (creating copy's of it self).

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
ERROR15:25:20
Could not pass event PlayerMoveEvent to CMI v9.0.0.9
Console15:25:20
java.lang.NoSuchMethodError: 'boolean net.Zrips.CMILib.Version.Version.isCurrentSubEqual(int)'
at com.Zrips.CMI.NBT.v1_17_R1.removeHologram(v1_17_R1.java:853) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.CMIHologram.removeFromCache(CMIHologram.java:1047) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.CMIHologram.hide(CMIHologram.java:537) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.CMIHologram.removeLastHoloInRangeExtra(CMIHologram.java:1529) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.HologramManager.handleHoloRangeUpdates(HologramManager.java:367) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.HologramManager.handleHoloUpdates(HologramManager.java:312) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.HologramListener.onPlayerMoveExtendedRnage(HologramListener.java:161) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor629.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-90]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-90]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-90]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1420) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:42) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-90]
at java.lang.Thread.run(Thread.java:831) [?:?]

AND THIS ON RELOAD:

15:26:05
null
Console15:26:05
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.0.9
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-90]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-90]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2165) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1976) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1957) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-90]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-90]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean net.Zrips.CMILib.Version.Version.isCurrentSubEqual(int)'
at com.Zrips.CMI.NBT.v1_17_R1.removeHologram(v1_17_R1.java:853) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.CMIHologram.removeFromCache(CMIHologram.java:1047) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.CMIHologram.hide(CMIHologram.java:530) ~[?:?]
at com.Zrips.CMI.Modules.Holograms.HologramManager.load(HologramManager.java:418) ~[?:?]
at com.Zrips.CMI.Config.reload(Config.java:2685) ~[?:?]
at com.Zrips.CMI.commands.list.reload.perform(reload.java:21) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-90]
... 21 more
```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin versjon: 9.0.0.9 SqLite
CMILib: 1.0.2.9 -> 1.0.2.10
Server: Paper(90) 1.17.1-R0.1-SNAPSHOT
CMI �konomi: Aktivert Vault: 1.7.3-b CMI Chat: Aktivert
Moduler -> 56 aktivert 0 deaktivert:

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
Paper version git-Paper-90 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bb44da8)

**Comment by MarcussGTX** [comment]
Was fixed with CMILib 1.0.2.10 or new paper update.
