### ISSUE TITLE
Error getMaxWorldHeight

### ISSUE THREAD

**Issue by bigenergy** [Zrips/CMI#5922]
**Description of issue:**

```
[06:31:50][ERROR/]: Error occurred while enabling CMI v9.0.1.3 (Is it up to date?)
 java.lang.NullPointerException: null
        at com.Zrips.CMI.utils.Util.getMaxWorldHeight(Util.java:176) ~[?:?]
        at com.Zrips.CMI.Config.load(Config.java:2024) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1457) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:414) ~[forge:1.16.5-Unknown-f5b8574]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:325) ~[forge:1.16.5-Unknown-f5b8574]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:432) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
```

Once I have installed the mod on my server https://www.curseforge.com/minecraft/mc-mods/skyblock-builder/
plugin stopped working (

**Cmi Version (using`/cmi version`):** v9.0.1.3

**Server Type (Spigot/Paperspigot/etc):** Spigot+Forge (LoliServer)

**Server Version (using `/ver`):** 1.16.5

**Relevant plugins (Delete if this isn't needed):** no

**Comment by CloudeLecaw** [comment]
U modded a not allowed workd high for your 1.16.5 server like -y or over 256+?

**Comment by bigenergy** [comment]
> U modded a not allowed workd high for your 1.16.5 server like -y or over 256+?
> These y values just work with 1.17, 1.17.1 + modpack

no, I did not touch the standard height
the plugin for some reason cannot get the height of the world from this mod

**Comment by Zrips** [comment]
Will fix this with next update

**Comment by bigenergy** [comment]
> Will fix this with next update

```
[18:36:14][ERROR/]: Error occurred while enabling CMI v9.0.2.0 (Is it up to date?)
 java.lang.NullPointerException: null
        at com.Zrips.CMI.utils.Util.getMaxWorldHeight(Util.java:176) ~[?:?]
        at com.Zrips.CMI.Config.load(Config.java:2031) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1461) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:414) ~[forge:1.16.5-Unknown-f5b8574]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:325) ~[forge:1.16.5-Unknown-f5b8574]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:432) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:351) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:721) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by CloudeLecaw** [comment]
Maybe its just because forge is not a supported fork?

**Comment by bigenergy** [comment]
@Zrips
