### ISSUE TITLE
1.17.1 Major server crash, irreparable

### ISSUE THREAD

**Issue by FZDNSZYT** [Zrips/CMI#5937]
1.17.1 When CMI is enabled on the server, a major error occurs. Constantly refreshing red warning. Then the world collapsed, and reports appeared to save the world. More serious will directly freeze the process. I can't even terminate the process forcibly. Finally, I could only delete all the data and reinstall the server. I tried many times.

**Comment by FZDNSZYT** [comment]
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'bekvon' of 'Residence' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/ERROR]: Nag author: 'Zrips' of 'CMI' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
[00:48:42] [Server thread/INFO]: Saving players
[00:48:42] [Server thread/INFO]: Saving worlds
[00:48:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[00:48:43] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[00:48:44] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[00:48:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[00:48:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[00:48:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[00:48:45] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[00:48:45] [Server thread/INFO]: Flushing Chunk IO
[00:48:45] [Server thread/INFO]: Closing Thread Pool
[00:48:45] [Server thread/INFO]: Closing Server

**Comment by FZDNSZYT** [comment]
以上就是错误日志，

**Comment by strahil211** [comment]
Something else is wrong here and I don't think it's CMI.
I run this plugin on multiple different servers, jars, and hosts and never encountered any of this.
Please look further or give a consistent way to replicate this. 
Also can we get more info on the system and type of server you are running?

**Comment by FZDNSZYT** [comment]
My server side is paper1.17.1, if possible. Can you tell me what more data you need to accurately judge this situation? thanks.

**Comment by Zrips** [comment]
@FZDNSZYT 
Its nothing serious, will investigate those errors but in general those will not cause any issues for you.

**Comment by FZDNSZYT** [comment]
Big problem. I didn't care about this last time. As a result, I deleted the archive and started over to repair it.

**Comment by levtey** [comment]
You sent the wrong part of the log, you should send the big red text as what you sent is just errors on shutdown, which are expected to show when the server crashes.

**Comment by Zrips** [comment]
@FZDNSZYT 
Errors you provided isint anything special or dangerous. If you are getting different errors while server is running i need to see those.

**Comment by FZDNSZYT** [comment]
Thank you, I will make good use of your work. Support you, come on.

**Comment by FZDNSZYT** [comment]
Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[13:44:42 WARN]: Legacy plugin WhiteList v0.1 does not specify an api-version.
[13:44:42 WARN]: Legacy plugin CMIB v1.0.0.4 does not specify an api-version.
[13:44:42 ERROR]: Could not load 'plugins/CMIB1.0.0.4.jar' in folder 'plugins'

**Comment by FZDNSZYT** [comment]
Could not load 'plugins/CMIB1.0.0.4.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.17.1.jar:git-Paper-112]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-112]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-112]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-112]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:192) ~[patched_1.17.1.jar:git-Paper-112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Paper-112]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Plugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:192) ~[patched_1.17.1.jar:git-Paper-112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-112]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71) ~[patched_1.17.1.jar:git-Paper-112]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Paper-112]
        ... 7 more
[13:44:42 WARN]: Legacy plugin CMIEInjector v1.0.2.3 does not specify an api-version

**Comment by levtey** [comment]
Ok.. you're just showing the proper shutdown of a Bungee plugin failing to start on a Spigot server. This is not the actual issue.

**Comment by Zrips** [comment]
@FZDNSZYT 
CMIB needs to be on bungeeserver and not on spigot/paper one. This is why you are getting this error. Simply move it to correct server and it will be fine.
