### ISSUE TITLE
/cmi sell error

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/CMI#5973]
Error when using `/cmi sell`
`/cmi sell hand` still all works
```
[ERROR]: null
```
---

**Cmi Version (9.0.2.1)

**Server Type (purpur-1296)

**Server Version (1.17.1)

**Comment by Stabrinai** [comment]
[latest.log](https://github.com/Zrips/CMI/files/6899898/latest.log)
Yes, this happened to Paperclip too.

**Comment by mrfloris** [comment]
Confirmed. I've just fresh installed it to test.


<img width="838" alt="Screenshot 2021-07-30 at 12 04 23" src="https://user-images.githubusercontent.com/28841349/127637514-54c13e48-882a-48e3-9baf-19d97e887154.png">


```
[12:04:14 INFO]: UUID of player mrfloris is 631e3896-da2a-4077-974b-d047859d76bc
[12:04:14 INFO]: mrfloris joined the game
[12:04:14 INFO]: mrfloris[/127.0.0.1:56749] logged in with entity id 164 at ([spawn]266.3892473616186, 86.78260132881829, -104.50101868875433)
[12:04:17 INFO]: mrfloris issued server command: /sell
[12:04:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.2.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-138]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:830) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-138]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.Zrips.CMI.commands.list.sell.perform(sell.java:71) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-138]
	... 21 more
>
```

```
> cmi version
[12:05:29 INFO]: --------------------------------------------------
[12:05:29 INFO]: CMI: 9.0.2.2 SqLite
[12:05:29 INFO]: CMILib: 1.0.3.2
[12:05:29 INFO]: Server: Paper(138) 1.17.1-R0.1-SNAPSHOT
[12:05:29 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[12:05:29 INFO]: Modules -> 55 enabled 1 disabled: votifier
[12:05:29 INFO]: --------------------------------------------------
>
```

**Comment by UBeagle** [comment]
also having this issue.. commenting to follow easier.

**Comment by SkeletonAce** [comment]
My hotfix for this was to remove the `/cmi sell` alias and make `/sell` perform `/cmi sell hand` in commands.yml
