### ISSUE TITLE
Holograms spam 

### ISSUE THREAD

**Issue by BlackkkMaster** [Zrips/CMI#6001]
**Description of issue:**
When reloading plugins (/reload), spam occurs in the console after that, the server shuts down. If you restart the server, there is no such error.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
(endlessly spamming in console and server crash)
```
> [11:31:38 INFO]: Loaded (2) holograms into memory. Took 1ms
> [11:31:38 INFO]: Loaded (2) holograms into memory. Took 1ms
> [11:31:38 INFO]: Loaded (2) holograms into memory. Took 1ms
> [11:31:39 INFO]: Loaded (2) holograms into memory. Took 2ms
```
(sometimes it occurs):
```
at com.Zrips.CMI.CMI.consoleMessage(CMI.java:1870) ~[?:?]
	at com.Zrips.CMI.CMI.loadMessage(CMI.java:1874) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.load(HologramManager.java:549) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.<init>(HologramManager.java:74) ~[?:?]
	at com.Zrips.CMI.CMI.getHologramManager(CMI.java:645) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.load(HologramManager.java:552) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.<init>(HologramManager.java:74) ~[?:?]
	at com.Zrips.CMI.CMI.getHologramManager(CMI.java:645) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.load(HologramManager.java:552) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.<init>(HologramManager.java:74) ~[?:?]
	at com.Zrips.CMI.CMI.getHologramManager(CMI.java:645) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.load(HologramManager.java:552) ~[?:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.<init>(HologramManager.java:74) ~[?:?]
```

---

**Cmi Version (using`/cmi version`):** 
9.0.2.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
1.12.2

**Comment by Zrips** [comment]
/reload command is strongly not recommended to be used due to similar issues. Will have a look to prevent this from happening in the future, but try to perform full server restarts which will minimize issues in general across all plugins.

**Comment by BlackkkMaster** [comment]
ok, thanks
