### ISSUE TITLE
Ranks throwing error on start

### ISSUE THREAD

**Issue by iTemmy** [Zrips/CMI#6016]
When CMI is loaded it doesn't load all of the ranks in, it only loads the first rank 'Vagabond' the other ranks have previously worked.  It was noticed to have stopped working on CMI version 9.0.2.3 then updated to latest being 9.0.2.4 and still not working, also updated paper to latest version and also had no effect.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
`[14:13:09] [Server thread/WARN]: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Ranks.RankManager.load(RankManager.java:1381)
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:13:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:13:09] [Server thread/INFO]:   Cant load rank (Capitalist)
[14:13:09] [Server thread/WARN]: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Ranks.RankManager.load(RankManager.java:1381)
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:13:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:13:09] [Server thread/INFO]:   Cant load rank (Affluent)
[14:13:09] [Server thread/WARN]: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Ranks.RankManager.load(RankManager.java:1381)
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:13:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:13:09] [Server thread/INFO]:   Cant load rank (Elite)
[14:13:09] [Server thread/WARN]: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Ranks.RankManager.load(RankManager.java:1381)
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:13:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[14:13:09] [Server thread/INFO]:   Cant load rank (Idol)
[14:13:09] [Server thread/WARN]: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Ranks.RankManager.load(RankManager.java:1381)
[14:13:09] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onEnable(CMI.java:1486)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:527)
[14:13:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:441)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[14:13:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:13:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)`
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
`Vagabond:
  Enabled: true
  DisplayName: '&2Vagabond'
  DefaultRank: true
  AutoRankup: false
  NextRanks:
  - Resident
Resident:
  Enabled: true
  DisplayName: Resident
  DefaultRank: false
  AutoRankup: false
  MoneyCost: 10000
  NextRanks:
  - Capitalist
  Commands:
  - lp user [playerName] promote player
  - broadcast! &r[playerDisplayName] &eelevated their social standing!
  - crate give to [playerName] CitizenAward 1
  StatsRequirements:
  - PlayTime: 10800
Capitalist:
  Enabled: true
  DisplayName: Capitalist
  DefaultRank: false
  AutoRankup: false
  MoneyCost: 45000
  NextRanks:
  - Affluent
  Commands:
  - lp user [playerName] promote player
  - broadcast! &r[playerDisplayName] &eelevated their social standing!
  - crate give to [playerName] CitizenAward 1
  StatsRequirements:
  - PlayTime: 32400
Affluent:
  Enabled: true
  DisplayName: Affluent
  DefaultRank: false
  AutoRankup: false
  MoneyCost: 100000
  NextRanks:
  - Elite
  Commands:
  - lp user [playerName] promote player
  - broadcast! &r[playerDisplayName] &eelevated their social standing!
  - crate give to [playerName] CitizenAward 1
  StatsRequirements:
  - PlayTime: 64800
Elite:
  Enabled: true
  DisplayName: Elite
  DefaultRank: false
  AutoRankup: false
  MoneyCost: 200000
  Commands:
  - lp user [playerName] promote player
  - broadcast! &r[playerDisplayName] &eelevated their social standing!
  - crate give to [playerName] CitizenAward 1
  StatsRequirements:
  - PlayTime: 129600
Idol:
  Enabled: true
  DisplayName: Idol
  DefaultRank: false
  AutoRankup: false
  MoneyCost: 500000
  Commands:
  - lp user [playerName] promote player
  - broadcast! &r[playerDisplayName] &eelevated their social standing!
  - crate give to [playerName] CitizenAward 1
  StatsRequirements:
  - PlayTime: 259200`
```

---

**Cmi Version (using`/cmi version`):** 
9.0.2.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-165 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f261419)
You are running the latest version
Previous version: git-Paper-137 (MC: 1.17.1)

**Comment by Zrips** [comment]
Issue is with you having `PlayTime: 259200` while it should have been `PlayTime:259200` basically without extra space, will make some adjustment to avoid this issue in the future, for now you can fix it by simply removing that extra space
