### ISSUE TITLE
Registering CustomAlias error?

### ISSUE THREAD

**Issue by HiddenThesis** [Zrips/CMI#6026]
**Description of issue:**

On startup the server, you can randomly get error for players who execute custom alias commands. As here we have a /infinity command that opens a MmoItems station.
---

**ERROR:**
```
>.... [21:31:17 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v9.0.2.4
org.bukkit.command.CommandException: Unhandled exception executing command 'mi' in plugin MMOItems v6.6.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-1327]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1327]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Purpur-1327]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:819) ~[patched_1.17.1.jar:git-Purpur-1327]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:905) ~[CMI9.0.2.4.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:867) ~[CMI9.0.2.4.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:151) ~[CMI9.0.2.4.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:104) ~[CMI9.0.2.4.jar:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:170) ~[CMI9.0.2.4.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1383.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1327]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1327]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1327]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1327]
at com.Zrips.CMI.commands.list.sudo.perform(sudo.java:59) ~[CMI9.0.2.4.jar:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396) ~[CMI9.0.2.4.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1327]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1327]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2309) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2120) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2101) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1422) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1532) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1327]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1327]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 4
at java.lang.String.checkBoundsBeginEnd(String.java:3751) ~[?:?]
at java.lang.String.substring(String.java:1907) ~[?:?]
at net.Indyuce.mmoitems.api.crafting.IngredientInventory.getIngredient(IngredientInventory.java:89) ~[MMOItems-6.6.0.jar:?]
at net.Indyuce.mmoitems.api.crafting.ingredient.Ingredient.evaluateIngredient(Ingredient.java:69) ~[MMOItems-6.6.0.jar:?]
at net.Indyuce.mmoitems.api.crafting.recipe.CheckedRecipe.<init>(CheckedRecipe.java:39) ~[MMOItems-6.6.0.jar:?]
at net.Indyuce.mmoitems.api.crafting.recipe.Recipe.evaluateRecipe(Recipe.java:135) ~[MMOItems-6.6.0.jar:?]
at net.Indyuce.mmoitems.api.crafting.CraftingStation.getAvailableRecipes(CraftingStation.java:117) ~[MMOItems-6.6.0.jar:?]
at net.Indyuce.mmoitems.gui.CraftingStationView.updateData(CraftingStationView.java:58) ~[MMOItems-6.6.0.jar:?]
at net.Indyuce.mmoitems.gui.CraftingStationView.<init>(CraftingStationView.java:49) ~[MMOItems-6.6.0.jar:?]
at net.Indyuce.mmoitems.command.mmoitems.stations.OpenCommandTreeNode.execute(OpenCommandTreeNode.java:37) ~[MMOItems-6.6.0.jar:?]
at io.lumine.mythic.lib.mmolibcommands.api.CommandTreeRoot.onCommand(CommandTreeRoot.java:42) ~[MythicLib-1.1.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1327]
... 37 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
CustomAlias:
  infinity:
    Cmds:
    - asconsole! mmoitems stations open nidavellir [playername]
```
---

**Cmi Version (using`/cmi version`):** CMI 9.0.2.4

**Server Type (Spigot/Paperspigot/etc):**  Purpur

**Server Version (using `/ver`):**  1.17.1

**Relevant plugins (Delete if this isn't needed):** CMI & MmoItems

**Comment by Zrips** [comment]
Its error from MMOItems and not CMI as indicated from these lines. It might have looked misleading due to CMI mentioning, but its only because CMI initialized command while MMOItems failed to process it. You will need to contact MMOitems plugin developer to fix this at their end.
```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 4
at java.lang.String.checkBoundsBeginEnd(String.java:3751) ~[?:?]
at java.lang.String.substring(String.java:1907) ~[?:?]
at net.Indyuce.mmoitems.api.crafting.IngredientInventory.getIngredient(IngredientInventory.java:89) ~[MMOItems-6.6.0.jar:?]
```
