### ISSUE TITLE
 java.lang.NullPointerException console error

### ISSUE THREAD

**Issue by benfiratkaya** [Zrips/CMI#6033]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:40:42 ERROR]: Could not pass event BlockBreakEvent to CMI v9.0.2.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:121) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:602) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:781) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:410) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:720) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:623) [SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.Modules.PlayerCombat.HeadDropListener.BlockBreakEvent(HeadDropListener.java:139) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor350.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307) ~[SpaceDeltaSpigot.jar:git-TacoSpigot-bf023c7d]
        ... 18 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 

**Server Type (Spigot/Paperspigot/etc):** 

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be resolved with next update
