### ISSUE TITLE
Issues with CMI Bungee plugin

### ISSUE THREAD

**Issue by compieter-gh** [Zrips/CMI#6053]
**Description of issue:**

The plugin is constantly giving NPE's in console of Bungeecord.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[02:31:58 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@7c3fb788, receiver=Daniel_playz23), cancelled=false, tag=BungeeCord) to listener net.Zrips.MessageListener@62058742
java.lang.NullPointerException: null
```

---

**CMIB 1.0.0,4** 

**git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448** 

**Waterfall 1.17.1**

**Comment by ComPieter-1** [comment]
bump

**Comment by raphaellaplante1** [comment]
Hi! Got the exact same message here. I'm using CMILib version 1.0.1.0 (from the file name since using the command /cmi version ingame gives me version 1.1.1.0) and Waterfall version waterfall-1.18-477. A bit of context that might help: I'm running all my servers and my proxy inside docker containers (itzg/bungeecord and itzg/minecraft-server).

```
[03:28:17 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@6ad84228, receiver=Hizoky), cancelled=false, tag=BungeeCord) to listener net.Zrips.MessageListener@1be4f05c
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at net.Zrips.MessageListener.on(MessageListener.java:30) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:283) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.18-477.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:de46489:477]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by RispyCZ** [comment]
I also have same error


[16:03:14] [Netty Worker IO Thread #0/WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@426bd439, receiver=YakuzaCZ), cancelled=false, tag=BungeeCord) to listener net.Zrips.MessageListener@513fab1e
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
        at net.Zrips.MessageListener.on(MessageListener.java:30) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:288) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:5661172:488]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by compieter-gh** [comment]
bump

**Comment by KhalidPlus** [comment]
bump

**Comment by Edrow-6** [comment]
same for me, bump

**Comment by Jqstln** [comment]
Bump, getting the same error. Using CMIBungee version 1.0.2.2. I'm using [itzg/docker-minecraft-server](https://github.com/itzg/docker-minecraft-server) with java version 17 [(jdk-17.0.8.0.2)](https://www.oracle.com/java/technologies/javase/17-0-8-relnotes.html). With latest FlameCord Version, (Waterfall Fork)

```
[09:43:43 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@20453c60, receiver=XX_Venum_XX), cancelled=false, tag=BungeeCord) to listener net.Zrips.MessageListener@72364a40
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
	at net.Zrips.MessageListener.on(MessageListener.java:56) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:511) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:301) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:111) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:130) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:e4c1c98:unknown]
```

This errors keeps spamming/repeating in my console for several days. Until now haven't been able to find any stuff to fix this.
