### ISSUE TITLE
asFakeOp! bug

### ISSUE THREAD

**Issue by arceusxs2** [Zrips/CMI#6071]
**Description of issue:**
Hello, i had problem with the asFakeOp! thing in eventcommands. When i changed it to asConsole or asPlayer! it worked fine.
When i tried to use this, it didnt work and got warn in console
playerWorldChange:
  Enabled: true
  Commands:
  - delay! 0.1
  - ifinworld:MinihryLobby! asFakeOp! spawn

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
 [Server thread/WARN]: [CMI] Task #1306 for CMI v9.0.2.6 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.2.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Tuinity-"b12d0cc"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[server.jar:git-Tuinity-"b12d0cc"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[server.jar:git-Tuinity-"b12d0cc"]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:776) ~[server.jar:git-Tuinity-"b12d0cc"]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:905) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:792) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:257) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$1(SpecializedCommandManager.java:226) ~[?:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$2.run(SpecializedCommandManager.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[server.jar:git-Tuinity-"b12d0cc"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[server.jar:git-Tuinity-"b12d0cc"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1475) ~[server.jar:git-Tuinity-"b12d0cc"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[server.jar:git-Tuinity-"b12d0cc"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[server.jar:git-Tuinity-"b12d0cc"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[server.jar:git-Tuinity-"b12d0cc"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[server.jar:git-Tuinity-"b12d0cc"]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.GameMode.name()" because the return value of "org.bukkit.entity.Player.getGameMode()" is null
	at com.Zrips.CMI.Modules.tp.Teleportations.isImortal(Teleportations.java:338) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.isSafeToDrop(Teleportations.java:1097) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.getSafeLocation(Teleportations.java:711) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:424) ~[?:?]
	at com.Zrips.CMI.Modules.tp.Teleportations.teleport(Teleportations.java:382) ~[?:?]
	at com.Zrips.CMI.commands.list.spawn.perform(spawn.java:55) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Tuinity-"b12d0cc"]
	... 16 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
playerWorldChange:
  Enabled: true
  Commands:
  - delay! 0.1
  - ifinworld:MinihryLobby! asFakeOp! spawn
```

---

**Cmi Version (using`/cmi version`):** 
CMI plugin version: 9.0.2.6
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
Tuinity version git-Tuinity-"b12d0cc" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
asFakeOP! should not be used in such way. We are performing command as a player with OP status, while this player isint actual real one and can create issues like that. Dont know exactly what you tried to achieve with your command, but if you want to teleport player then use asConsole! variable and add player name which needs to be teleported, for example 
`- ifinworld:MinihryLobby! asConsole! cmi spawn [playerName]`
