### ISSUE TITLE
Chat not passing messages on 1.7.10

### ISSUE THREAD

**Issue by trickman325** [Zrips/CMI#6129]
**Description of issue:**
Im running CMI on modded FTB infinity
Im running it through thermos to allow for spigot plugins.
mc version 1.7.10
i get this error everytime i try to type in chat, and it will not let me send anything in chat
its saying something about a nickname, but i do not have one on. (the console log even says the message goes through but nothing happens in game)

I dont need any other support i just want to be able to type in chat thats it and i dont see why CMI is blocking it

---

**ERROR:** 
```
EDIT: turns out this is all commands that send chat messages (APART from /me)
https://pastebin.com/DEwkJDbh


https://pastebin.com/YwZzrrWr

[13:17:09 WARN]: java.lang.NullPointerException
[13:17:09 WARN]: 	at net.Zrips.CMILib.RawMessages.RawMessageManager.send(RawMessageManager.java:162)
[13:17:09 WARN]: 	at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:618)
[13:17:09 WARN]: 	at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:650)
[13:17:09 WARN]: 	at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:644)
[13:17:09 WARN]: 	at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:185)
[13:17:09 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:17:09 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[13:17:09 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[13:17:09 WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[13:17:09 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[13:17:09 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:17:09 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[13:17:09 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:489)
[13:17:09 WARN]: 	at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1234)
[13:17:09 WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1158)
[13:17:09 WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[13:17:09 WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[13:17:09 WARN]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:137)
[13:17:09 WARN]: 	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:353)
[13:17:09 WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:220)
[13:17:09 WARN]: 	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:47)
[13:17:09 WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:261)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[13:17:09 WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[13:17:09 WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
[13:17:09 WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
[13:17:09 WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
[13:17:09 WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
[13:17:09 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
[13:17:09 WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:17:09 INFO]: [world] <Trickman325> est
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Here is my config im using
[config.zip](https://github.com/Zrips/CMI/files/7110843/config.zip)
```

---

**Cmi Version (using`/cmi version`):** 9.0.2.10

**Server Type (Spigot/Paperspigot/etc):** FTB infinity evolved 1.7 (Running Thermos-1.7.10-1614-server)

**Server Version (using `/ver`):** 1614.58 (MC: 1.7.10) 1.7.10-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Your server version is not supported, at all. Will make some small changes to minimize this issue, but in general its simply isint supported. 1.7.10 is 7 year old version, let alone using modded servers doesn't remove complexity and chance in having bugs.
