### ISSUE TITLE
9.0.3.0 Fresh install error

### ISSUE THREAD

**Issue by levtey** [Zrips/CMI#6150]
**Description of issue:**

With a fresh install of CMI, an error is thrown on startup or `/cmi reload` if there is no `CustomAlias.yml`
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[18:58:37 WARN]: java.io.FileNotFoundException: plugins/CMI/CustomAlias.yml (No such file or directory)
[18:58:37 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[18:58:37 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
[18:58:37 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
[18:58:37 WARN]:        at com.google.common.io.Files$FileByteSource.openStream(Files.java:129)
[18:58:37 WARN]:        at com.google.common.io.Files$FileByteSource.openStream(Files.java:119)
[18:58:37 WARN]:        at com.google.common.io.ByteSource.copyTo(ByteSource.java:267)
[18:58:37 WARN]:        at com.google.common.io.Files.copy(Files.java:319)
[18:58:37 WARN]:        at CMILib1.0.3.8.jar//net.Zrips.CMILib.FileHandler.ConfigReader.saveToBackup(ConfigReader.java:286)
[18:58:37 WARN]:        at CMI9.0.3.0.jar//com.Zrips.CMI.Modules.Alias.AliasManager.load(AliasManager.java:491)
[18:58:37 WARN]:        at CMI9.0.3.0.jar//com.Zrips.CMI.Config.reload(Config.java:2694)
[18:58:37 WARN]:        at CMI9.0.3.0.jar//com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
[18:58:37 WARN]:        at CMI9.0.3.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[18:58:37 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:58:37 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[18:58:37 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838)
[18:58:37 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2316)
[18:58:37 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2127)
[18:58:37 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[18:58:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[18:58:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[18:58:37 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[18:58:37 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:58:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:58:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:58:37 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433)
[18:58:37 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[18:58:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:58:37 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411)
[18:58:37 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404)
[18:58:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:58:37 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382)
[18:58:37 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293)
[18:58:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[18:58:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by CloudeLecaw** [comment]
i agree this is new because reload still look for the old place of custom alias.yml
same happens on cmi reload

```
[23:09:56 INFO]: [CMI] Loaded (61) warps into memory. Took 1ms
[23:09:56 WARN]: java.io.FileNotFoundException: plugins/CMI/CustomAlias.yml (No such file or directory)
[23:09:56 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[23:09:56 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
[23:09:56 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
[23:09:56 WARN]:        at com.google.common.io.Files$FileByteSource.openStream(Files.java:129)
[23:09:56 WARN]:        at com.google.common.io.Files$FileByteSource.openStream(Files.java:119)
[23:09:56 WARN]:        at com.google.common.io.ByteSource.copyTo(ByteSource.java:267)
[23:09:56 WARN]:        at com.google.common.io.Files.copy(Files.java:319)
[23:09:56 WARN]:        at CMILib_1.0.3.8.jar//net.Zrips.CMILib.FileHandler.ConfigReader.saveToBackup(ConfigReader.java:286)
[23:09:56 WARN]:        at CMI_9.0.3.0.jar//com.Zrips.CMI.Modules.Alias.AliasManager.load(AliasManager.java:491)
[23:09:56 WARN]:        at CMI_9.0.3.0.jar//com.Zrips.CMI.Config.reload(Config.java:2694)
[23:09:56 WARN]:        at CMI_9.0.3.0.jar//com.Zrips.CMI.commands.list.reload.perform(reload.java:21)
[23:09:56 WARN]:        at CMI_9.0.3.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[23:09:56 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:09:56 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:09:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838)
[23:09:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:801)
[23:09:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518)
[23:09:56 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[23:09:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[23:09:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[23:09:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:09:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[23:09:56 INFO]: [CMI] Loaded (164) custom alias into memory. Took 15ms
[23:09:56 INFO]: [CMI] Loaded (57) regular alias into memory. Took 16ms
```

**Comment by CloudeLecaw** [comment]
I think Zrips allready noticed this one :)
So i think it will be fixed with next update :)

**Comment by Zrips** [comment]
Yea, i noticed it, its generic error and you should simply ignore as it has no impact on plugins performance. Will fix with next update.
