### ISSUE TITLE
[Bug] CMI 9.3 Looking for CustomAlias.yml in old location.

### ISSUE THREAD

**Issue by Terminal-Access** [Zrips/CMI#6152]
**CustomAlias.yml Location error:**
Post upgrading to CMI v9.0.3.0 and CMILib v1.0.3.8
CMI is still looking for CustomAlias.yml in the old location and throws an error/stack trace when it cant be found.

---

**ERROR:**
```
[12:54:12 WARN]: java.io.FileNotFoundException: plugins\CMI\CustomAlias.yml (The system cannot find the file specified)
[12:54:12 WARN]:        at java.base/java.io.FileInputStream.open0(Native Method)
[12:54:12 WARN]:        at java.base/java.io.FileInputStream.open(FileInputStream.java:211)
[12:54:12 WARN]:        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:153)
[12:54:12 WARN]:        at com.google.common.io.Files$FileByteSource.openStream(Files.java:129)
[12:54:12 WARN]:        at com.google.common.io.Files$FileByteSource.openStream(Files.java:119)
[12:54:12 WARN]:        at com.google.common.io.ByteSource.copyTo(ByteSource.java:267)
[12:54:12 WARN]:        at com.google.common.io.Files.copy(Files.java:319)
[12:54:12 WARN]:        at CMILib-1.0.3.8.jar//net.Zrips.CMILib.FileHandler.ConfigReader.saveToBackup(ConfigReader.java:286)
[12:54:12 WARN]:        at CMI-9.0.3.0.jar//com.Zrips.CMI.Modules.Alias.AliasManager.load(AliasManager.java:491)
[12:54:12 WARN]:        at CMI-9.0.3.0.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1498)
[12:54:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[12:54:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[12:54:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:54:12 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535)
[12:54:12 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449)
[12:54:12 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725)
[12:54:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[12:54:12 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212)
[12:54:12 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:54:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

---

**Version Informations:** 
```
[13:03:59 INFO]: --------------------------------------------------
[13:03:59 INFO]: CMI: 9.0.3.0 SqLite
[13:03:59 INFO]: CMILib: 1.0.3.8
[13:03:59 INFO]: Server: Paper(257) 1.17.1-R0.1-SNAPSHOT
[13:03:59 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[13:03:59 INFO]: Modules -> 38 enabled 18 disabled: spawnerProximity, versionCheck, skin, anvilRenameColor, elytraBoost, spawners, elytraLaunch, durabilityLoss, coloredArmor, flightCharge, disabledEnchants, worldLimitsElytra, ranks, votifier, headDrop, spawnerCharge, silentChest, vanish
[13:03:59 INFO]: --------------------------------------------------
```

**Server Version:** 
```
This server is running Paper version git-Paper-257 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8a2b23a)
```

**Comment by Zrips** [comment]
Will be resolved with next update. This is just informational error message and will not have any impact on plugins work
