### ISSUE TITLE
Error on Event FoodLevelChangeEvent

### ISSUE THREAD

**Issue by MaxRubbel** [Zrips/CMI#6153]
Hello it's me again,

When eating on the server comes the following 2 error messages.

Also thank you again in advance

---

Error 1:
```
18:34:43
Could not pass event FoodLevelChangeEvent to CMI v9.0.3.0
Console18:34:43
java.lang.NoSuchMethodError: org.bukkit.entity.HumanEntity.getFoodLevel()I
at com.Zrips.CMI.AllListeners.PlayerListeners.FoodLevelChangeEvent(PlayerListeners.java:1505) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor559.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:dd991e7-DEV]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:dd991e7-DEV]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:dd991e7-DEV]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) [SimplePluginManager.class:dd991e7-DEV]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:785) [CraftEventFactory.class:dd991e7-DEV]
at net.minecraft.util.FoodStats.func_151686_a(FoodStats.java:60) [afp.class:?]
at net.minecraft.item.ItemFood.func_77654_b(SourceFile:43) [aij.class:?]
at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:245) [aip.class:?]
at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:3137) [vp.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1422) [oq.class:?]
at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:3019) [vp.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2427) [vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:253) [aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:482) [oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:253) [pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:dd991e7-DEV]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:296) [gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:193) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```
Error 2:
```
Could not pass event FoodLevelChangeEvent to CMI v9.0.3.0
Console18:34:44
java.lang.NoSuchMethodError: org.bukkit.entity.HumanEntity.getFoodLevel()I
at com.Zrips.CMI.AllListeners.PlayerListeners.FoodLevelChangeEvent(PlayerListeners.java:1505) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor559.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:dd991e7-DEV]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:dd991e7-DEV]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:dd991e7-DEV]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) [SimplePluginManager.class:dd991e7-DEV]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:785) [CraftEventFactory.class:dd991e7-DEV]
at net.minecraft.util.FoodStats.func_75118_a(FoodStats.java:91) [afp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:270) [aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:482) [oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:253) [pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:dd991e7-DEV]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:296) [gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:193) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

---

Server Type:
Magma Hybrid Server 1.12.2 (Bukkit/Forge)

Server Version:
Magma Version dd9991e7-dev
API Version Spigot 1.12.2-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Fixed
