### ISSUE TITLE
CMI Chunk issue with CMI.Modules.Holograms.CMIHologram

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#6164]
**Description of issue:**
Error in console from `java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns `

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:42:47] [Craft Scheduler Thread - 104/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:170)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:153)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at net.minecraft.server.v1_12_R1.World.getChunkAt(World.java:357)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at net.minecraft.server.v1_12_R1.Entity.setLocation(Entity.java:1312)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at com.Zrips.CMI.NBT.v1_12_R1.spawnClickable(v1_12_R1.java:802)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at com.Zrips.CMI.Modules.Holograms.CMIHologram$2.run(CMIHologram.java:1128)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[10:42:47] [Craft Scheduler Thread - 104/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

---

**Cmi Version (using`/cmi version`):** 
```
[10:53:10] [Server thread/INFO]: --------------------------------------------------
[10:53:10] [Server thread/INFO]: CMI: 9.0.4.1 BungeeCord CMIB  MySQL
[10:53:10] [Server thread/INFO]: CMILib: 1.0.3.9
[10:53:10] [Server thread/INFO]: Server: Paper(1618) 1.12.2-R0.1-SNAPSHOT
[10:53:10] [Server thread/INFO]: CMI economy: Disabled Vault: 1.6.6-b CMI Chat: Disabled
[10:53:10] [Server thread/INFO]: Modules -> 29 enabled 27 disabled: spawnerProximity, customMessages, mirror, tablist, moneyCheque, skin, noTarget, elytraBoost, elytraLaunch, coloredArmor, votifier, shulkerBackpack, attachedCommands, spawnerCharge, namePlates, homeInteractions, hpBossBar, afk, anvilRenameColor, spawners, dynamicSigns, playerChatTag, durabilityLoss, flightCharge, disabledEnchants, worldLimits, ranks
[10:53:10] [Server thread/INFO]: --------------------------------------------------
```
**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 1.12.2

**Comment by Zrips** [comment]
Should get a fix with next update
