### ISSUE TITLE
CMI issue with latest version of mysql

### ISSUE THREAD

**Issue by Abhinavbajpai30** [Zrips/CMI#6185]
**Description of issue:**
CMI is not able to connect to latest version of mysql which is 8.0.26.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[05:18:50 WARN]: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
[05:18:50 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[05:18:50 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
[05:18:50 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
[05:18:50 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBConnectionPool.getConnection(DBConnectionPool.java:34)
[05:18:50 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.<init>(DBDAO.java:506)
[05:18:50 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBMySQL.<init>(DBMySQL.java:44)
[05:18:50 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.startMysql(DBManager.java:228)
[05:18:50 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.load(DBManager.java:142)
[05:18:50 WARN]:        at com.Zrips.CMI.Config.load(Config.java:794)
[05:18:50 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1465)
[05:18:50 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:18:50 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:18:50 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[05:18:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[05:18:50 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[05:18:50 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596)
[05:18:50 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309)
[05:18:50 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[05:18:50 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[05:18:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[05:18:50 WARN]: Caused by: com.mysql.cj.exceptions.CJException: Public Key Retrieval is not allowed
[05:18:50 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:18:50 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:18:50 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:18:50 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[05:18:50 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[05:18:50 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[05:18:50 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[05:18:50 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:124)
[05:18:50 WARN]:        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:151)
[05:18:50 WARN]:        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
[05:18:50 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:441)
[05:18:50 WARN]:        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:174)
[05:18:50 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1350)
[05:18:50 WARN]:        at com.mysql.cj.NativeSession.connect(NativeSession.java:157)
[05:18:50 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847)
[05:18:50 WARN]:        ... 23 more
[05:18:50 WARN]: Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
[05:18:50 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:18:50 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:18:50 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:18:50 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[05:18:50 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[05:18:50 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[05:18:50 WARN]:        at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:128)
[05:18:50 WARN]:        ... 29 more
```

---

**Cmi Version (using`/cmi version`):** 
```
4.0.9.2
```

**Server Type (Spigot/Paperspigot/etc):** 
```
Purpur
```

**Server Version (using `/ver`):** 
```
1.16.5
```

**Comment by Zrips** [comment]
You will need to double-check your database setup including login name, password and make sure that database by provided name actually exists. This doesn't look to be issue with plugin itself, it simply wasn't able to connect to MySQL database due to incorrect information provided in dataBaseInfo.yml
