### ISSUE TITLE
Problem with arclight 

### ISSUE THREAD

**Issue by Tealwen** [Zrips/CMI#6194]
**Description of issue:**

cmi don't work with arclight 1.16.5 (see error)

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[24Sep2021 17:19:06.310] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling CMI v9.0.4.3 (Is it up to date?)
java.lang.NullPointerException: null
	at com.Zrips.CMI.utils.Util.getMaxWorldHeight(Util.java:187) ~[?:?]
	at com.Zrips.CMI.Config.load(Config.java:1973) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1465) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:492) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:406) ~[arclight:arclight-1.16.5-1.0.21-SNAPSHOT-f7852ed]
	at net.minecraft.server.MinecraftServer.handler$bpb000$arclight$enablePlugins(MinecraftServerMixin.java:1977) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1861) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`): CMI v9.0.4.3** 

**Server Type (Spigot/Paperspigot/etc): Arclight** 

**Server Version (using `/ver`): 1.16.5**

**Comment by Tealwen** [comment]
After more test the problem occured with KubeJS ^^ i don't know why !

**Comment by Zrips** [comment]
Issue with world not having set environment, you have some custom world which is not properly initialized. Will make some basic fix from my end, but this should be fixed from plugins side which creates those custom worlds to be more robust across all plugins as this will be an issue
