### ISSUE TITLE
cmi search god true results in basically infinite loopyloop

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6223]
**Description of issue:**

```
/cmi search god true
```

Causes basically a loop it can't get out of because the result is null. 

You can still /save-all and then /stop, so it doesn't freeze up - but it will go beyond the 100% found users, and never finishes. This used to work in the past, but haven't had to use this in a few months. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[09:36:26] [Server thread/WARN]: [CMI] Task #108246 for CMI v9.0.4.5 generated an exception
java.lang.NullPointerException: Cannot read field "paperConfig" because "this.t" is null
	at net.minecraft.server.level.ServerPlayer.isInvulnerableTo(ServerPlayer.java:1422) ~[app:?]
	at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.isInvulnerable(CraftEntity.java:1057) ~[patched_1.17.1.jar:git-Paper-295]
	at com.Zrips.CMI.Modules.Search.Search.checkPlayer(Search.java:422) ~[CMI9.0.4.5.jar:?]
	at com.Zrips.CMI.Modules.Search.Search.access$1(Search.java:260) ~[CMI9.0.4.5.jar:?]
	at com.Zrips.CMI.Modules.Search.Search$4.run(Search.java:474) ~[CMI9.0.4.5.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-295]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-295]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-295]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-295]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-295]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-295]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-295]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

```
> cmi version
[09:39:49 INFO]: --------------------------------------------------
[09:39:49 INFO]: CMI plugin version: 9.0.4.5 SqLite
[09:39:49 INFO]: CMILib: 1.0.3.11
[09:39:49 INFO]: Server: Paper(295) 1.17.1-R0.1-SNAPSHOT
[09:39:49 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[09:39:49 INFO]: Modules -> 55 enabled 1 disabled: flightCharge
[09:39:49 INFO]: --------------------------------------------------
> ver
[09:39:50 INFO]: Checking version, please wait...
[09:39:50 INFO]: This server is running Paper version git-Paper-295 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f905057)
You are running the latest version
Previous version: git-Paper-293 (MC: 1.17.1)
>
```

**Comment by Zrips** [comment]
Will fix with next update, tho this looks more like miencraft issue by itself due to this line
```
java.lang.NullPointerException: Cannot read field "paperConfig" because "this.t" is null
	at net.minecraft.server.level.ServerPlayer.isInvulnerableTo(ServerPlayer.java:1422) ~[app:?]
```
Or there was some player data file with incorrect information in it. In any case, this needs to be pointed out to Paper/Spigot devs to be fixed at their end too as i can only ignore this error and process remaining data when this happens.
