### ISSUE TITLE
Can't load plugin.

### ISSUE THREAD

**Issue by NeotenySS** [Zrips/CMI#6264]
Initially, I assumed that the error could be caused by other plugins, but I created and started a clean server and then installed cmi and cmilib and got this error.
(checked on hosting and on local server):

---

**ERROR:**
```
######################## 
[19:35:54] [Craft Scheduler Thread - 0/INFO]: [CMILib] Cannot look for updates: Server returned HTTP response code: 403 for URL: https://api.spigotmc.org/legacy/update.php?resource=87610
[19:35:54] [Craft Scheduler Thread - 1/WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.spigotmc.org/legacy/update.php?resource=87610
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at com.Zrips.CMI.utils.VersionChecker.getOfficialVersion(VersionChecker.java:106)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at com.Zrips.CMI.CMI.lambda$0(CMI.java:1268)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at com.Zrips.CMI.CMI$$Lambda$3814/1034813742.run(Unknown Source)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:35:54] [Craft Scheduler Thread - 1/WARN]:   at java.lang.Thread.run(Unknown Source)
[19:35:54] [Craft Scheduler Thread - 1/INFO]: [CMI] Failed to check for CMI update on spigot web page.
########################
```

---

Cmi Version: 9.0.6.0
CmiLib: 1.0.4.1
Server Type: Spigot
Server Version: 1.16.5

**Comment by Zrips** [comment]
Its just error that plugin failed to check for newest version number, in general you can ignore it. If you have internet connection then its simply derping out at spigot side. It wont have any effect on plugins work.
