### ISSUE TITLE
ptime command bug

### ISSUE THREAD

**Issue by plebalol1231** [Zrips/CMI#6310]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.0.6.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-349]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-349]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1401) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1394) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-349]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-349]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getDayTime()" because "this.t" is null
        at net.minecraft.server.level.ServerPlayer.getPlayerTime(ServerPlayer.java:2287) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.getPlayerTime(CraftPlayer.java:1264) ~[patched_1.17.1.jar:git-Paper-349]
        at com.Zrips.CMI.commands.list.ptime.perform(ptime.java:91) ~[CMI9.0.6.0.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396) ~[CMI9.0.6.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-349]
        ... 21 more ##
######################
```

---

**Cmi Version (using`/cmi version`): 9.0.6.0** 

**Server Type (Spigot/Paperspigot/etc): Paperspigot** 

**Server Version (using `/ver`):This server is running Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)
You are 4 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-46 (MC: 1.17)**

**Comment by Zrips** [comment]
Will issue fix, tho this is issue by trying to modify ptime for player whose data isint correctly loaded in.
