### ISSUE TITLE
Dynmap Core Error

### ISSUE THREAD

**Issue by alecfarmer** [Zrips/CMI#6374]
**Description of issue:**

I receive this error on startup. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
16.11 22:56:50 [Server]  [CMI] Task #55443 for CMI v9.0.6.2 generated an exception
16.11 22:56:50 [Server] INFO java.lang.NullPointerException: Cannot invoke "org.dynmap.DynmapCore.assertPlayerInvisibility(String, boolean, String)" because "this.core" is null
16.11 22:56:50 [Server] INFO at org.dynmap.bukkit.DynmapPlugin.assertPlayerInvisibility(DynmapPlugin.java:1608) ~[Dynmap-3.1-spigot.jar:?]
16.11 22:56:50 [Server] INFO at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:50) ~[CMI9.0.6.2.jar:?]
16.11 22:56:50 [Server] INFO at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:34) ~[CMI9.0.6.2.jar:?]
16.11 22:56:50 [Server] INFO at com.Zrips.CMI.Modules.DynMap.DynMapListener.lambda$0(DynMapListener.java:34) ~[CMI9.0.6.2.jar:?]
16.11 22:56:50 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-"51b7b60"]
16.11 22:56:50 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-"51b7b60"]
16.11 22:56:50 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-"51b7b60"]
16.11 22:56:50 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-"51b7b60"]
16.11 22:56:50 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-"51b7b60"]
16.11 22:56:50 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-"51b7b60"]
16.11 22:56:50 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-"51b7b60"]
16.11 22:56:50 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

---

**Cmi Version (using`/cmi version`):** 
Latest: 9.0.6.3
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper - "51b7b60" - 1.17.1

**Comment by Zrips** [comment]
This looks more of DynMap plugin issue due to the error originating from DynMap class and not CMI. Try contacting DynMap developer with this error message.
