### ISSUE TITLE
1.13, build 8.0.0.1, /cmi info error

### ISSUE THREAD

**Issue by gerardvanschip** [Zrips/CMI#639]
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:27:04] [Server thread/INFO]: KaizenWorlds issued server command: /cmi info Lethal_Host
[12:27:05] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: -16776960
[12:27:05] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GeoIP.LookupService.readCityRecord(LookupService.java:415)
[12:27:05] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GeoIP.LookupService.getLocation(LookupService.java:390)
[12:27:05] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GeoIP.LookupService.getLocation(LookupService.java:365)
[12:27:05] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.GeoIP.LookupService.getLocation(LookupService.java:378)
[12:27:05] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.info$1$1.run(info.java:448)
[12:27:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76)
[12:27:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[12:27:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877)
[12:27:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[12:27:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[12:27:05] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[12:27:05] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by Zrips** [comment]
Which geop ip files are you using to determine players location?
