### ISSUE TITLE
1.13 Error(s) 

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#640]
Command:
/cmi toast
```
####################
## /cmi toast TheTopCz -t:challenge -icon:stone test
[00:00:31 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:692) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_74]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_74]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: net.minecraft.server.v1_13_R1.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:STONE
at net.minecraft.server.v1_13_R1.MinecraftKey.<init>(SourceFile:38) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftKey.<init>(SourceFile:43) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.ChatDeserializer.b(SourceFile:123) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.ChatDeserializer.i(SourceFile:136) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.AdvancementDisplay.a(SourceFile:109) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.AdvancementDisplay.a(SourceFile:96) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.Advancement$SerializedAdvancement.a(Advancement.java:323) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.AdvancementDataWorld.lambda$0(AdvancementDataWorld.java:30) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:493) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:518) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at net.minecraft.server.v1_13_R1.ChatDeserializer.a(SourceFile:538) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
at com.Zrips.CMI.NBT.v1_13_R1.loadAdvancement(v1_13_R1.java:1674) ~[?:?]
at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.add(CMIAdvancement.java:135) ~[?:?]
at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.show(CMIAdvancement.java:120) ~[?:?]
at com.Zrips.CMI.commands.list.toast.perform(toast.java:98) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-ed1cec9-1c7adf7]
... 15 more ##
####################
```

Commad UI:
If I enable an alias, UI commands are not displayed..

**CMI plugin version: 8.0.0.2
Server version: Spigot 1.13-R0.1-SNAPSHOT** 

This server is running CraftBukkit version git-Spigot-ed1cec9-1c7adf7 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

**Comment by CloudeLecaw** [comment]
minefarm: true

**Comment by Zrips** [comment]
Will be fixed with next build
