### ISSUE TITLE
[1.18] CMI 9.1 /setmotd exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6410]
```
[17:12:33 INFO]: TSLint issued server command: /setmotd {#gold}&lU{#fed201}&ln{#ffce02}&lo{#ffc903}&lf{#ffc504}&lf{#ffc006}&li{#ffbc07}&lc{#ffb708}&li{#ffb309}&la{#ffaf0b}&ll{#ffaa0c}&l {#ffa60d}&lC{#ffa10e}&lM{#ff9d10}&lI{#ff9811}&l {#ff9412}&lT{#ff8f13}&le{#ff8b15}&ls{#ff8716}&lt{#ff8217}&l {#ff7e18}
[17:12:33 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.rcon.RemoteControlCommandListener.getProperties()
[17:12:33 WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[17:12:33 WARN]: 	at CMILib1.1.0.0.jar//net.Zrips.CMILib.Reflections.setServerProperties(Reflections.java:501)
[17:12:33 WARN]: 	at CMI9.1.0.0.jar//com.Zrips.CMI.commands.list.setmotd.perform(setmotd.java:47)
[17:12:33 WARN]: 	at CMI9.1.0.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[17:12:33 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:12:33 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:12:33 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:878)
[17:12:33 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[17:12:33 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[17:12:33 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[17:12:33 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[17:12:33 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[17:12:33 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[17:12:33 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:12:33 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[17:12:33 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[17:12:33 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1412)
[17:12:33 WARN]: 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[17:12:33 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[17:12:33 WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1390)
[17:12:33 WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1383)
[17:12:33 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[17:12:33 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1361)
[17:12:33 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1267)
[17:12:33 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[17:12:33 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:12:44 INFO]: TSLint issued server command: /setmotd a
[17:12:44 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.rcon.RemoteControlCommandListener.getProperties()
[17:12:44 WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[17:12:44 WARN]: 	at CMILib1.1.0.0.jar//net.Zrips.CMILib.Reflections.setServerProperties(Reflections.java:501)
[17:12:44 WARN]: 	at CMI9.1.0.0.jar//com.Zrips.CMI.commands.list.setmotd.perform(setmotd.java:47)
[17:12:44 WARN]: 	at CMI9.1.0.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[17:12:44 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:12:44 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[17:12:44 WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:878)
[17:12:44 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[17:12:44 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2012)
[17:12:44 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1993)
[17:12:44 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[17:12:44 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[17:12:44 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[17:12:44 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:12:44 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[17:12:44 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[17:12:44 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1412)
[17:12:44 WARN]: 	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[17:12:44 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[17:12:44 WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1390)
[17:12:44 WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1383)
[17:12:44 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[17:12:44 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1361)
[17:12:44 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1267)
[17:12:44 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[17:12:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:12:46 INFO]: TSLint lost connection: Disconnected
```
```
> cmi version
[17:20:06 INFO]: --------------------------------------------------
[17:20:06 INFO]: CMI plugin version: 9.1.0.0 SqLite-> 9.0.7.0
[17:20:06 INFO]: CMILib: 1.1.0.0
[17:20:06 INFO]: Server: Paper(22) 1.18-R0.1-SNAPSHOT
[17:20:06 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[17:20:06 INFO]: Modules -> 55 enabled 1 disabled: votifier
[17:20:06 INFO]: --------------------------------------------------
>
```

Can confirm on two servers. During early testing I tried it and it worked. CMI/CMILib jars are from SpigotMC (not the internal builds)

**Comment by Zrips** [comment]
Gets a fix with next version
