### ISSUE TITLE
toast msg all

### ISSUE THREAD

**Issue by Freddereck** [Zrips/CMI#6413]
I'am use toast all for schedules, not work.

---

[13:09:18] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Fredderick issued server command: /toast Fredderick -t:challenge -icon:stone asd
[13:09:19] [Server thread/WARN] [com.Zrips.CMI.CMI]: [CMI] Task #18695 for CMI v9.0.7.0 generated an exception
 java.lang.IllegalAccessError: tried to access field net.minecraft.advancements.AdvancementList.field_192092_b from class com.Zrips.CMI.NBT.v1_12_R1
        at com.Zrips.CMI.NBT.v1_12_R1.removeAdvancement(v1_12_R1.java:1036) ~[?:?]
        at com.Zrips.CMI.Modules.Advancements.CMIAdvancement$1.run(CMIAdvancement.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:bb50f45]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:bb50f45]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[13:09:19] [Server thread/ERROR] [global]: TIMING_STACK_CORRUPTION - Report this to the plugin CMI(Look for errors above this in the logs) (TimingIdentifier{id=CMI:Task: null (Single)} did not stopTiming)
 java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:bb50f45]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:918) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
#######################################
```

---

>cmi version
[13:22:39] [Server thread/INFO] []: --------------------------------------------------
[13:22:39] [Server thread/INFO] []: CMI: 9.0.7.0 SqLite-> 9.1.0.0
[13:22:39] [Server thread/INFO] []: CMILib: 1.1.0.0 
[13:22:39] [Server thread/INFO] []: Server: bb50f45 (MC: 1.12.2) 1.12.2-R0.1-SNAPSHOT
[13:22:39] [Server thread/INFO] []: CMI economy: Disabled CMI Chat: Disabled 
[13:22:39] [Server thread/INFO] []: Modules -> 32 enabled 24 disabled: spawnerProximity, hpBossBar, customMessages, mirror, armorstand, versionCheck, moneyCheque, skin, jail, spawners, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, coloredArmor, deathMessages, disabledEnchants, worldLimits, firstJoinMessages, votifier, spawnerCharge, silentChest, interactiveCommands, namePlates
[13:22:39] [Server thread/INFO] []: --------------------------------------------------

magma))

[13:22:52] [Server thread/INFO] []: This server is running Magma version bb50f45 (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge Version 14.23.5.2855)

**Comment by Zrips** [comment]
You have unsupported minecraft version. Plugin isint made to work with moded servers and might cause some errors from time to time, you will need to avoid using particular commands as i cant keep up will all different versions for ancient moded Minecraft versions.
