### ISSUE TITLE
console error with venturechat and cmilib

### ISSUE THREAD

**Issue by kelso6969** [Zrips/CMI#6414]
**Description of issue:**

With VentureChat, Getting an console error related to CMILIB. Opening ticket with both plugins.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]: java.lang.IllegalArgumentException: Index parameter is not within [0 - 0)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.reflect.StructureModifier.getField(StructureModifier.java:664)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at mineverse.Aust1n46.chat.listeners.PacketListener.onPacketSending(PacketListener.java:56)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.minecraft.network.NetworkManager.b(NetworkManager.java:203)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.minecraft.network.NetworkManager.a(NetworkManager.java:183)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1701)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1687)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessageManager.send(RawMessageManager.java:197)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:618)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:650)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:644)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at com.Zrips.CMI.Modules.CustomText.CTextManager.lambda$0(CTextManager.java:379)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[13:36:18] [ForkJoinPool.commonPool-worker-4/WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

---

**Cmi Version (using`/cmi version`):** 
[13:40:10] [Server thread/INFO]: --------------------------------------------------
[13:40:10] [Server thread/INFO]: CMI plugin version: 9.1.0.0 MySQL
[13:40:10] [Server thread/INFO]: CMILib: 1.1.0.0
[13:40:10] [Server thread/INFO]: Server: Spigot 1.18-R0.1-SNAPSHOT
[13:40:10] [Server thread/INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[13:40:10] [Server thread/INFO]: Modules -> 51 enabled 5 disabled: spawnerProximity, flightCharge, tablist, playerCombat, moneyCheque
[13:40:10] [Server thread/INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
"name": "3344",
        "description": "Jenkins build 3344",

**Relevant plugins (Delete if this isn't needed):**
venturechat

**Comment by kelso6969** [comment]
I thought this went away but didnt. 

***
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]: java.lang.IllegalArgumentException: Index parameter is not within [0 - 0)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.reflect.StructureModifier.getField(StructureModifier.java:664)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at mineverse.Aust1n46.chat.listeners.PacketListener.onPacketSending(PacketListener.java:56)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.minecraft.network.NetworkManager.b(NetworkManager.java:203)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.minecraft.network.NetworkManager.a(NetworkManager.java:183)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1701)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1687)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessageManager.send(RawMessageManager.java:197)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:618)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:650)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:644)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at com.Zrips.CMI.Modules.CustomText.CTextManager.lambda$0(CTextManager.java:379)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[18:03:10] [ForkJoinPool.commonPool-worker-3/WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

***
