### ISSUE TITLE
Attach Command with multiple command

### ISSUE THREAD

**Issue by Sempoinus1** [Zrips/CMI#6424]
**Description of issue:**
Hello, 
I tried to use /cmi attachcommand cmi heal [playerName];;cmi feed [playerName] which is showed as example in wiki, but I can't make it work, it shows errors in console. It's not even when trying to use the item, but right after trying to perform attachcommand

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[02:12:27] [Server thread/INFO]: Sempoinus1 issued server command: /cmi attachcommand cmi heal [playerName];;cmi feed [playerName]
[02:12:27] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[02:12:27] [Server thread/WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor316.invoke(Unknown Source)
[02:12:27] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:12:27] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[02:12:27] [Server thread/WARN]:        at net.Zrips.CMILib.NBT.CMINBT.getList(CMINBT.java:361)
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.Reflections.printNBT(Reflections.java:868)
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.Reflections.printItemNBT(Reflections.java:797)
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.commands.list.attachcommand.perform(attachcommand.java:270)
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[02:12:27] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:12:27] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[02:12:27] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:800)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1937)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1776)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1757)
[02:12:27] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[02:12:27] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:12:27] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[02:12:27] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:12:27] [Server thread/WARN]: Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
[02:12:27] [Server thread/WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[02:12:27] [Server thread/WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[02:12:27] [Server thread/WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[02:12:27] [Server thread/WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[02:12:27] [Server thread/WARN]:        at java.base/java.util.ArrayList.remove(ArrayList.java:504)
[02:12:27] [Server thread/WARN]:        at net.minecraft.nbt.NBTTagList.c(SourceFile:155)
[02:12:27] [Server thread/WARN]:        ... 30 more
[02:12:27] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "<local16>" is null
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.Reflections.printNBT(Reflections.java:870)
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.Reflections.printItemNBT(Reflections.java:797)
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.commands.list.attachcommand.perform(attachcommand.java:270)
[02:12:27] [Server thread/WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[02:12:27] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:12:27] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[02:12:27] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:800)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1937)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1776)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1757)
[02:12:27] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[02:12:27] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:12:27] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
[02:12:27] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
[02:12:27] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[02:12:27] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```
---

**Cmi Version (using`/cmi version`):** 9.1.0.1

**Server Type (Spigot/Paperspigot/etc):** spigot

**Server Version (using `/ver`):** 3350-Spigot-dbf4938-1825cc0, 1.18-R0.1-SNAPSHOT

**Comment by Zrips** [comment]
Get fix with next CMILib update
