### ISSUE TITLE
chat not functionnal

### ISSUE THREAD

**Issue by jAvEE-fr** [Zrips/CMI#6427]
**Description of issue:**
chat is non functionnal (no color or something. we can talk minecraft style and that sall

---
[14:09:21 WARN]: [CMI] Task #91 for CMI v9.1.0.1 generated an exception
java.lang.NullPointerException: Cannot invoke "org.dynmap.DynmapCore.assertPlayerInvisibility(String, boolean, String)" because "this.core" is null
        at org.dynmap.bukkit.DynmapPlugin.assertPlayerInvisibility(DynmapPlugin.java:1641) ~[Dynmap-3.2.1-spigot.jar:?]
        at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:50) ~[CMI9.1.0.1.jar:?]
        at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:34) ~[CMI9.1.0.1.jar:?]
        at com.Zrips.CMI.Modules.DynMap.DynMapListener.lambda$0(DynMapListener.java:34) ~[CMI9.1.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-39]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-39]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

[14:01:40 INFO]: Cant load chat filter section from config file! Error: 
[14:01:40 WARN]: java.util.NoSuchElementException
[14:01:40 WARN]:        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758)
[14:01:40 WARN]:        at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
[14:01:40 WARN]:        at CMI9.1.0.1.jar//com.Zrips.CMI.Modules.ChatFilter.ChatFilterManager.load(ChatFilterManager.java:407)
[14:01:40 WARN]:        at CMI9.1.0.1.jar//com.Zrips.CMI.Config.load(Config.java:1457)
[14:01:40 WARN]:        at CMI9.1.0.1.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1487)
[14:01:40 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:01:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:01:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:01:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
[14:01:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
[14:01:40 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[14:01:40 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[14:01:40 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[14:01:40 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[14:01:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[14:01:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

---

**Cmi Version (using`/cmi version`):** 
CMI9.1.0.1.jar
**Server Type (Spigot/Paperspigot/etc):** 
paper-1.18-39.jar
**Server Version (using `/ver`):** 
1.18 - Java 17
**Relevant plugins (Delete if this isn't needed):**
tested without

**Comment by CloudeLecaw** [comment]
You got the 1.18 version if dynmap?

https://www.reddit.com/r/Dynmap/comments/r71mzh/first_experimental_builds_for_spigotpaper_forge/

**Comment by Zrips** [comment]
@jAvEE-fr 
Check config file as of error there is issue with chat filter section
`Cant load chat filter section from config file!`
