### ISSUE TITLE
After banning someone on Spigot, getting error on first login attempt. 

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6437]
I haven't tested 1.18 yet, but on SPIGOT 1.17.1 I can reproduce this.

```
[14:55:37] [User Authenticator #1/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:55:38] [Server thread/INFO]: Paprikaatje[/127.0.0.1:57078] logged in with entity id 163 at ([spawn]246.5, 64.0, -102.5)
[14:55:49] [Async Chat Thread - #0/INFO]: <Paprikaatje> i am a bad person, ban me

>cmi ban Paprikaatje bad ppl arent welcome
[14:55:58] [Server thread/INFO]: Paprikaatje lost connection: You are banned from this server!
Reason: bad ppl arent welcome
[14:55:59] [Server thread/INFO]: Paprikaatje left the game
[14:55:59] [Server thread/INFO]: Paprikaatje got banned by Server for: bad ppl arent welcome
[14:56:11] [User Authenticator #2/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:56:11] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@38d0dfbc[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@7746a1c8]},legacy=false] (/127.0.0.1:57088): You are banned from this server.
Reason: bad ppl arent welcome
[14:56:11] [Server thread/INFO]: com.mojang.authlib.GameProfile@38d0dfbc[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@7746a1c8]},legacy=false] (/127.0.0.1:57088) lost connection: You are banned from this server.
Reason: bad ppl arent welcome
>cmi unban paprikaatje
[14:56:18] [Server thread/INFO]: Paprikaatje unbanned
[14:56:22] [User Authenticator #3/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:56:22] [Server thread/INFO]: Paprikaatje[/127.0.0.1:57095] logged in with entity id 277 at ([spawn]246.364938051416, 64.0, -99.09307832559216)

>cmi tempban
[14:56:28] [Server thread/INFO]: Usage: /cmi tempban [playerName] [timeValue] (reason) (-s)
[14:56:28] [Server thread/INFO]: * TempBan player

>cmi tempban Paprikaatje 60s bad person
[14:56:47] [Server thread/INFO]: Paprikaatje lost connection: Temporarily Banned!
Reason: bad person
You will be unbanned after 1 min
[14:56:47] [Server thread/INFO]: Paprikaatje left the game
[14:56:47] [Server thread/INFO]: Paprikaatje got tempbanned by Server for: 1 min  reason: bad person
[14:56:53] [User Authenticator #4/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:56:53] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@633e3d33[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@123a4e15]},legacy=false] (/127.0.0.1:57104): You are banned from this server.
Reason: bad person
Your ban will be removed on 2021-12-08 at 14:57:47 CET
[14:56:53] [Server thread/INFO]: com.mojang.authlib.GameProfile@633e3d33[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@123a4e15]},legacy=false] (/127.0.0.1:57104) lost connection: You are banned from this server.
Reason: bad person
Your ban will be removed on 2021-12-08 at 14:57:47 CET

>cmi info paprikaatje
[14:57:15] [Server thread/INFO]:
[14:57:15] [Server thread/INFO]: --------------------------------------------------
[14:57:15] [Server thread/INFO]: Paprikaatje Group: default Offline for: 28 sec  PlayTime: 45 sec  (0.0)
[14:57:15] [Server thread/INFO]: UUID: e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:57:15] [Server thread/INFO]: Ip: 127.0.0.1 N/A (--)  First login: 08/12/21 14:55:37
[14:57:15] [Server thread/INFO]: CanFly(Flying)  Fly speed: 1
[14:57:15] [Server thread/INFO]: Mode: Survival  Walk speed: 1 HP: 20.0/20.0 Air: 300/300 Hunger: 20/20 Saturation +5.0 Exp: 0exp -> 0/7 (0lvl)
[14:57:15] [Server thread/INFO]: Banned  Banned by: Server Left: 31 sec  For: bad person
[14:57:15] [Server thread/INFO]: Pos  spawn (246.35:64.0:-98.1)
[14:57:15] [Server thread/INFO]: Respawn  spawn (256:64:-112)
[14:57:15] [Server thread/INFO]: --------------------------------------------------
>cmi info paprikaatje
[14:57:30] [Server thread/INFO]:
[14:57:30] [Server thread/INFO]: --------------------------------------------------
[14:57:30] [Server thread/INFO]: Paprikaatje Group: default Offline for: 43 sec  PlayTime: 45 sec  (0.0)
[14:57:30] [Server thread/INFO]: UUID: e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:57:30] [Server thread/INFO]: Ip: 127.0.0.1 N/A (--)  First login: 08/12/21 14:55:37
[14:57:30] [Server thread/INFO]: CanFly(Flying)  Fly speed: 1
[14:57:30] [Server thread/INFO]: Mode: Survival  Walk speed: 1 HP: 20.0/20.0 Air: 300/300 Hunger: 20/20 Saturation +5.0 Exp: 0exp -> 0/7 (0lvl)
[14:57:30] [Server thread/INFO]: Banned  Banned by: Server Left: 16 sec  For: bad person
[14:57:30] [Server thread/INFO]: Pos  spawn (246.35:64.0:-98.1)
[14:57:30] [Server thread/INFO]: Respawn  spawn (256:64:-112)
[14:57:30] [Server thread/INFO]: --------------------------------------------------
>cmi info paprikaatje
[14:57:46] [Server thread/INFO]:
[14:57:46] [Server thread/INFO]: --------------------------------------------------
[14:57:46] [Server thread/INFO]: Paprikaatje Group: default Offline for: 58 sec  PlayTime: 45 sec  (0.0)
[14:57:46] [Server thread/INFO]: UUID: e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:57:46] [Server thread/INFO]: Ip: 127.0.0.1 N/A (--)  First login: 08/12/21 14:55:37
[14:57:46] [Server thread/INFO]: CanFly(Flying)  Fly speed: 1
[14:57:46] [Server thread/INFO]: Mode: Survival  Walk speed: 1 HP: 20.0/20.0 Air: 300/300 Hunger: 20/20 Saturation +5.0 Exp: 0exp -> 0/7 (0lvl)
[14:57:46] [Server thread/INFO]: Banned  Banned by: Server Left: 1 sec  For: bad person
[14:57:46] [Server thread/INFO]: Pos  spawn (246.35:64.0:-98.1)
[14:57:46] [Server thread/INFO]: Respawn  spawn (256:64:-112)
[14:57:46] [Server thread/INFO]: --------------------------------------------------

[14:57:54] [User Authenticator #5/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:57:54] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:57148
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.players.GameProfileBanEntry.hasExpired()" because the return value of "net.minecraft.server.players.GameProfileBanList.get(Object)" is null
	at net.minecraft.server.players.PlayerList.attemptLogin(PlayerList.java:585) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.LoginListener.c(LoginListener.java:156) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1336) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:57:54] [Server thread/INFO]: com.mojang.authlib.GameProfile@430f9b4[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@5fb626e0]},legacy=false] (/127.0.0.1:57148) lost connection: Internal server error

[14:58:29] [User Authenticator #6/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[14:58:29] [Server thread/INFO]: Paprikaatje[/127.0.0.1:57155] logged in with entity id 327 at ([spawn]246.35180105783104, 64.0, -98.10440227996644)
[14:58:34] [Async Chat Thread - #1/INFO]: <Paprikaatje> ha! im back
[14:58:35] [Server thread/INFO]: Paprikaatje lost connection: Disconnected
[14:58:35] [Server thread/INFO]: Paprikaatje left the game

>cmi version
[14:58:44] [Server thread/INFO]: --------------------------------------------------
[14:58:44] [Server thread/INFO]: CMI: 9.1.0.1 SqLite
[14:58:44] [Server thread/INFO]: CMILib: 1.1.0.1
[14:58:44] [Server thread/INFO]: Server: Spigot 1.17.1-R0.1-SNAPSHOT
[14:58:44] [Server thread/INFO]: CMI economy: Disabled CMI Chat: Disabled
[14:58:44] [Server thread/INFO]: Modules -> 55 enabled 1 disabled: votifier
[14:58:44] [Server thread/INFO]: --------------------------------------------------

>ver
[14:58:45] [Server thread/INFO]: This server is running CraftBukkit version 3284-Spigot-3892929-0ebef35 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[14:58:45] [Server thread/INFO]: Checking version, please wait...
[14:58:45] [Thread-16/INFO]: You are 40 version(s) behind
>
```

Regular ban, no issue, player gets banned, they disconnect with the ban msg in the client, they can try to reconnect and they get the ban msg. No console error.

Temporary ban, here's the issue, they get banned, they get properly disconnected with a ban msg, and when they try to reconnect while they are still temp banned they get the msg they can't get in. And they have to wait it out. 

Now, when the temp ban has expired and they try to connect, the First time they try it will give a client-side disconnect error msg, and in the console it will show an exception.

**Comment by mrfloris** [comment]
Same on SPIGOT 1.18
```
[15:11:28] [Async Chat Thread - #0/INFO]: <Paprikaatje> first time joiner, and im spamming my server, dont ban me: google.com
>cmi tempban Paprikaatje 30s naughty spammer
[15:11:58] [Server thread/INFO]: Paprikaatje lost connection: Temporarily Banned!
Reason: naughty spammer
You will be unbanned after 30 sec
[15:11:58] [Server thread/INFO]: Paprikaatje left the game
[15:11:58] [Server thread/INFO]: Paprikaatje got tempbanned by Server for: 30 sec  reason: naughty spammer
>cmi info paprikaatje
[15:12:05] [Server thread/INFO]:
[15:12:05] [Server thread/INFO]: --------------------------------------------------
[15:12:05] [Server thread/INFO]: Paprikaatje Group: default Offline for: 6 sec  PlayTime: 46 sec  (0.0)
[15:12:05] [Server thread/INFO]: UUID: e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[15:12:05] [Server thread/INFO]: Ip: 127.0.0.1 N/A (--)  First login: 08/12/21 15:11:12
[15:12:05] [Server thread/INFO]: CanFly(Flying)  Fly speed: 1
[15:12:05] [Server thread/INFO]: Mode: Survival  Walk speed: 1 HP: 20.0/20.0 Air: 300/300 Hunger: 20/20 Saturation +5.0 Exp: 0exp -> 0/7 (0lvl)
[15:12:05] [Server thread/INFO]: Banned  Banned by: Server Left: 23 sec  For: naughty spammer
[15:12:05] [Server thread/INFO]: Pos  spawn (-149.5:74.0:-222.5)
[15:12:05] [Server thread/INFO]: Respawn  spawn (-160:71:-224)
[15:12:05] [Server thread/INFO]: --------------------------------------------------
[15:12:10] [User Authenticator #2/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[15:12:10] [Server thread/INFO]: Disconnecting com.mojang.authlib.GameProfile@6518c0b[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@68059a79]},legacy=false] (/127.0.0.1:57432): You are banned from this server.
Reason: naughty spammer
Your ban will be removed on 2021-12-08 at 15:12:28 CET
[15:12:10] [Server thread/INFO]: com.mojang.authlib.GameProfile@6518c0b[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@68059a79]},legacy=false] (/127.0.0.1:57432) lost connection: You are banned from this server.
Reason: naughty spammer
Your ban will be removed on 2021-12-08 at 15:12:28 CET
[15:13:44] [User Authenticator #3/INFO]: UUID of player Paprikaatje is e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c
[15:13:44] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:57498
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.players.GameProfileBanEntry.f()" because the return value of "net.minecraft.server.players.GameProfileBanList.b(Object)" is null
	at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:586) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.network.LoginListener.c(LoginListener.java:156) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.network.LoginListener.b(LoginListener.java:74) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1322) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3355-Spigot-dbf4938-3c2af1b]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:13:44] [Server thread/INFO]: com.mojang.authlib.GameProfile@6921d372[id=e0d07db8-f7e8-43c7-9ded-864dfc6f3b7c,name=Paprikaatje,properties={textures=[com.mojang.authlib.properties.Property@28c62cc1]},legacy=false] (/127.0.0.1:57498) lost connection: Internal server error
>
```

**Comment by mrfloris** [comment]
Cannot reproduce on Paper 1.18

**Comment by NeotenySS** [comment]
Also, when a player gets banned, the required columns are not filled in the database.
MySQL is used
![image](https://user-images.githubusercontent.com/11386982/145230636-3be2c5be-6356-4fb2-b5a3-32c2dca8d769.png)

**Comment by CloudeLecaw** [comment]
Because servers banfile is used. Bans are notnstored innthe msql

**Comment by NeotenySS** [comment]
> 
The cmi temp ban command is used.
Once the information was saved to the database, but then it stopped updating.
Needless to say, this doesn't work in the database because of the "banfile server".
This function used to work well.

**Comment by NeotenySS** [comment]
> Because servers banfile is used. Bans are notnstored innthe msql

The cmi temp ban command is used.
Once the information was saved to the database, but then it stopped updating.
Needless to say, this doesn't work in the database because of the "banfile server".
This function used to work well.

**Comment by mrfloris** [comment]
> Because servers banfile is used. Bans are notnstored innthe msql

<img width="601" alt="Screenshot 2021-12-08 at 13 22 42" src="https://user-images.githubusercontent.com/28841349/145397915-d4aaa465-53a9-4019-8eb0-f614d2cb796f.png">

They're in the sqlite file. I can't confirm they aren't in MySQL.

**Comment by NeotenySS** [comment]
Me Database info:
![image](https://user-images.githubusercontent.com/11386982/145426906-d83adfdb-9660-4a33-ae54-0aaf19bcdcdd.png)

**Comment by NeotenySS** [comment]
My database received data about the banned player several times, but after a while, this data stopped coming again.

**Comment by NeotenySS** [comment]
It seems that the problem with the database is that if there are no players on the server or there was 1 player who was later banned, then the information is not saved in the database.
But if a second player is present, then the information is successfully saved in the database.

**Comment by NeotenySS** [comment]
But the error posted by mrfloris still remains.

**Comment by arminfuerst** [comment]
I noticed the same behaviour on spigot 1.18.2 - is there any hint how to prevent this?
I set the ban using following code:
```
BanList userBanList = Bukkit.getBanList(BanList.Type.NAME);
userBanList.addBan(userToBan, reason.toString(), banExpiration, null);
```

**Comment by NeotenySS** [comment]
Не знаю, разработчик молчил... И активно работает с голограммами

**Comment by mrfloris** [comment]
For the people that can reproduce this in 1.18.2, which version of Spigot or Paper are you using, please share your `/ver` output, thank you. I can no longer reproduce this issue on my own test servers, using Paper 1.18.2 build 317.

**Comment by arminfuerst** [comment]
> For the people that can reproduce this in 1.18.2, which version of Spigot or Paper are you using, please share your `/ver` output, thank you. I can no longer reproduce this issue on my own test servers, using Paper 1.18.2 build 317.

This server is running CraftBukkit version 3453-Spigot-ffceeae-64db512 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

**Comment by mrfloris** [comment]
This is still an issue in 1.20 and cmi 9.6 - temp banned, get exception error and client side error, have to wait a bit and try again then we can login. probably a spigot issue, doesn't seem to be an issue on paper 1.19.4, so probably neither on paper 1.20

https://paste.md-5.net/kaqazisebu.cs

**Comment by NeotenySS** [comment]
> Это все еще проблема в 1.20 и cmi 9.6 - временный бан, ошибка исключения и ошибка на стороне клиента, нужно немного подождать и повторить попытку, после чего мы сможем войти. вероятно, проблема с патрубком, кажется, не проблема на бумаге 1.19.4, поэтому, вероятно, ни на бумаге 1.20
> 
> https://paste.md-5.net/kaqazisebu.cs

Thanks u for this information 🙏

**Comment by NeotenySS** [comment]
> This is still an issue in 1.20 and cmi 9.6 - temp banned, get exception error and client side error, have to wait a bit and try again then we can login. probably a spigot issue, doesn't seem to be an issue on paper 1.19.4, so probably neither on paper 1.20
> 
> https://paste.md-5.net/kaqazisebu.cs

Thanks u for this information 🙏

**Comment by Zrips** [comment]
Looks to be issue with servers itself not updating information quickly enough. CMI uses official ban API and database only stores information for reference purposes and not to actually use that data to keep player banned.
