### ISSUE TITLE
Cant load chat filter section from config file! Error

### ISSUE THREAD

**Issue by StealthDeci** [Zrips/CMI#6440]
#######################################
[21:19:45 INFO]: Cant load chat filter section from config file! Error:
[21:19:45 WARN]: java.util.NoSuchElementException
[21:19:45 WARN]:        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:758)
[21:19:45 WARN]:        at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
[21:19:45 WARN]:        at CMI 9.1.0.1.jar//com.Zrips.CMI.Modules.ChatFilter.ChatFilterManager.load(ChatFilterManager.java:407)
[21:19:45 WARN]:        at CMI 9.1.0.1.jar//com.Zrips.CMI.Config.load(Config.java:1457)
[21:19:45 WARN]:        at CMI 9.1.0.1.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1487)
[21:19:45 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:19:45 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[21:19:45 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[21:19:45 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
[21:19:45 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
[21:19:45 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:730)
[21:19:45 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:506)
[21:19:45 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:347)
[21:19:45 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1215)
[21:19:45 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:19:45 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
#######################################
```

---

**Cmi Version (using`/cmi version`):   9.1.0.1

**Server Type (Spigot/Paperspigot/etc):   Purpur

**Server Version (using `/ver`):    1.18

**Comment by Zrips** [comment]
Gets a fix with next release
