### ISSUE TITLE
The money system does not work, Vault latest version

### ISSUE THREAD

**Issue by h0up** [Zrips/CMI#6443]
**Description of issue:**
The money system does not work
Vault latest version. Plugins: CMI, CMILib, DeluxeMenus, FastAsyncWorldEdit, LuckPerms, PlaceholderAPI, Vault, WGExtender, WorldBorder, WorldEdit, WorldGuard

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[01:30:37 INFO]: [CMI] Vault was found but economy engine is missing. Use one from list provided in https://dev.bukkit.org/bukkit-plugins/vault/
[01:30:37 INFO]: [CMI] Alternatively you can enable CMI economy in config.yml file
[01:30:37 INFO]:   Vault was found but not economy plugin, you will have limited economy support

> money give
[01:37:58 WARN]: Unexpected exception while parsing console command "cmi money give"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.1.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:648) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_311]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.commands.list.money.perform(money.java:80) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
        ... 8 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Economy:
  # Enable or disable CMI economy in general
  # In case CMIInjector is present, then this will be set to true automatically.
  # Attention! For economy to work properly with other plugins you will need ether an injector or recompiled Vault version. 
  # You can find both option at top of plugins page
  # ATTENTION! If you disabled CMI economy while server was running, you will need to perform full server restart for this to take correct effect and avoid any issues while getting players balances
  Enabled: true
  # Determines if player needs to confirm money payment by clicking on chat message
  Confirmation: false
  # Set to true if you want to log money transfers between players
  LogEnabled: false
  log:
    Unknown: true
    Transfer: true
  Cheque:
    # Determines max amount of cheque player can create
    # Set it to 0 to remove limit
    MaxValue: 1.0E8
    # If set to true player will be required to hold peace of paper to create cheque
    Paper: true
    # When set to true player will be required to have cmi.command.cheque.withdraw permission node to withdraw cheque
    Permission: false
  PaymentWithShorts:
    # When set to true players will be able to make payments by using short amount formats like 10k which results into 10000 and similar
    # In addition 10.2k will result into 10200
    Allow: true
    # List of suffixes we should accept and into what amount it results into
    # Only one letter is acceptable when defining suffix
    values:
    - k-1000
    - m-1000000
    - b-1000000000
    - t-1000000000000
    - q-1000000000000000
  BalTop:
    # List of players to exclude from baltop list
    Exclude:
    - Notch
    # When enabled baltop list will show short money values, like 12.5M instead of 12501234
    DisplayWithShorts: false
    # List of names to exclude from baltop
    # Can be used to filter out towny towns
    ExcludeStartingWith:
    - town_
    - town-
    - towny_
    - towny-
    # When set to true some fake accounts will be included into baltop list
    # This should include some previously marked accounts as fake which have been created for town usage or similar things
    IncludeFakes: false
    # Set to 0 or lower to disable this feature
    # Time in days of player being offline to exclude from being included in balance top list
    ExcludeInactive: 0
  Global:
    # Starting amount of money players will have
    StartingAmount: 0.0
    # Minimal amount, can go into negative if needed
    MinimalAmount: 0.0
    # Maximal amount of money player can have. Set to -1 to disable this limit
    MaximumAmount: 1.0E8
    # Defines amount until player can send to another player
    # This can prevent annoying spam some players would want to create by sending tiny amounts of money
    MinimalPay: 0.5
    # Defines if you want to allow payments with fractions
    # if this is disabled then payments will be limited to whole numbers and in case player provides number with fraction we will round number down
    Fractions: true
    # Currency symbol to be used when showing balance or similar
    CurrencySymbol: €
    # Format used for displaying money
    MoneyFormat: '###,##0.00'
    # Converts long numbers to short ones, like 12305122 to 12.3m
    UseShortNumbers: false
    # Suffixes for short numbers
    ShortNumbersSuffixes:
    - ''
    - k
    - m
    - b
    - t
    - q
    # Replaces to western format where decimals are separated by , and thousands by . In example 1,000,000.00 changes to 1.000.000,00
    SwitchPlaces: false
    # Placing of currency symbol
    Placing: '[money][symbol]'
```

---

**Cmi Version (using`/cmi version`): CMI9.1.0.2

**Server Type (Spigot/Paperspigot/etc): Paperspigot

**Server Version (using `/ver`): Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Everything works fine on the CMI8.6.26.5 version

**Comment by Zrips** [comment]
Will be fixed with next update
