### ISSUE TITLE
CMi air error

### ISSUE THREAD

**Issue by splops** [Zrips/CMI#648]
**Description of issue or feature request: /cmi air <player> <any positive number> send "an internal error has ocurred. . ."**

**ERROR (DELETE IF YOU HAVE NO ERROR):an internal error has ocurred**
```
[00:20:38 INFO]: plop40 issued server command: /cmi air plop40 200
[00:20:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.0.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:692) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_12_R1/BlockPosition
	at com.Zrips.CMI.Modules.Animations.DeadBodies.playFakeBed(DeadBodies.java:193) ~[?:?]
	at com.Zrips.CMI.commands.list.air.perform(air.java:52) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13-R0.1-SNAPSHOT-b1723.jar:git-Spigot-ed1cec9-1a6b4f5]
	... 15 more

```

**Cmi Version (using`/cmi version`): 8.0.0.2** 

**Server Type (Spigot/Paperspigot/etc): Spigot** 

**Server Version (using `/ver`):MC 1.13R0.1**

**Comment by Zrips** [comment]
Will be fixed with next build
