### ISSUE TITLE
Maxplayers error on 1.18.1

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#6509]
**Description of issue:**

Input: cmi maxplayers {integer]
Output: error
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
cmi maxplayers 5
[11:10:55 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.getPlayerList()
[11:10:55 WARN]: at java.base/java.lang.Class.getMethod(Class.java:2227)
[11:10:55 WARN]: at CMI9.1.0.4.jar//com.Zrips.CMI.Reflections.changePlayerLimit(Reflections.java:258)
[11:10:55 WARN]: at CMI9.1.0.4.jar//com.Zrips.CMI.commands.list.maxplayers.perform(maxplayers.java:34)
[11:10:55 WARN]: at CMI9.1.0.4.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[11:10:55 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:10:55 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:10:55 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[11:10:55 WARN]: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860)
[11:10:55 WARN]: at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:507)
[11:10:55 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:481)
[11:10:55 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[11:10:55 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[11:10:55 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[11:10:55 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[11:10:55 INFO]: Changed max allowed players from 10 to 10. Online: 0
```

---

**Cmi Version (using`/cmi version`):** 
 CMI: 9.1.0.4
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.18.1 build 105

**Comment by Zrips** [comment]
Should be fixed with latest builds
