### ISSUE TITLE
Holograms , Placeholders

### ISSUE THREAD

**Issue by PlesCZ** [Zrips/CMI#6552]
**Description of issue:**
After restarting the server when I connect to the server I get this error only once. 

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[10:41:52 WARN]: java.util.ConcurrentModificationException
[10:41:52 WARN]:        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1522)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1517)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Statistics.StatsManager.getTop(StatsManager.java:382)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1791)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:861)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:706)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:625)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:199)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$2.run(CMIHologram.java:1159)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:41:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:41:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:52 WARN]: java.util.ConcurrentModificationException
[10:41:52 WARN]:        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1522)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1517)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Statistics.StatsManager.getTop(StatsManager.java:382)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1791)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:861)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:706)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:625)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:199)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$2.run(CMIHologram.java:1159)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:41:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:41:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:52 INFO]: [CMI] Inccorrect placeholder format for %cmi_playtimetop_time_5%
[10:41:52 WARN]: java.util.ConcurrentModificationException
[10:41:52 WARN]:        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1522)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1517)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Statistics.StatsManager.getTop(StatsManager.java:382)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1791)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:861)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:706)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:625)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:199)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$2.run(CMIHologram.java:1159)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:41:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:41:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:41:52 INFO]: [CMI] Inccorrect placeholder format for %cmi_playtimetop_time_6%
[10:41:52 WARN]: java.util.ConcurrentModificationException
[10:41:52 WARN]:        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1522)
[10:41:52 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1517)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Statistics.StatsManager.getTop(StatsManager.java:382)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1791)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:861)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:706)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:625)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:199)
[10:41:52 WARN]:        at CMI9.1.0.5.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$2.run(CMIHologram.java:1159)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:41:52 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:41:52 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:41:52 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:41:52 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

---

**Cmi Version (using`/cmi version`): 9.1.0.5** 

**Server Type (Spigot/Paperspigot/etc): Purpur - 1497** 

**Server Version (using `/ver`): 1.18.1**

**Comment by Zrips** [comment]
Should be resolved with net update
