### ISSUE TITLE
Could not pass event FoodLevelChangeEvent to CMI v8.7.10.8

### ISSUE THREAD

**Issue by danyadanya2005** [Zrips/CMI#6561]
[10:09:37] [Server thread/ERROR]: Could not pass event FoodLevelChangeEvent to CMI v8.7.10.8
java.lang.NullPointerException: null
	at com.Zrips.CMI.AllListeners.PlayerListeners.FoodLevelChangeEvent(PlayerListeners.java:1317) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1030.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-792]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:1213) ~[patched_1.16.5.jar:git-Paper-792]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:1208) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MobEffectList.tick(MobEffectList.java:70) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MobEffect.a(SourceFile:169) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MobEffect.tick(SourceFile:148) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.EntityLiving.tickPotionEffects(EntityLiving.java:813) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:457) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:530) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:258) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:658) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:600) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1856) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:520) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:188) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1520) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-792]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-792]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[10:09:38] [pool-58-thread-1/WARN]: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/gists
[10:09:38] [pool-58-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
[10:09:38] [pool-58-thread-1/WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[10:09:38] [pool-58-thread-1/WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[10:09:38] [pool-58-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport.gistText(ErrorReport.java:120)
[10:09:38] [pool-58-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport$Builder.build(ErrorReport.java:374)
[10:09:38] [pool-58-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport.withException(ErrorReport.java:330)
[10:09:38] [pool-58-thread-1/WARN]: 	at ru.tehkode.permissions.bukkit.ErrorReport$2.run(ErrorReport.java:193)
[10:09:38] [pool-58-thread-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:09:38] [pool-58-thread-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:09:38] [pool-58-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10:09:38] [pool-58-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10:09:38] [pool-58-thread-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[10:09:38] [pool-58-thread-1/ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.permissionValue(PermissiblePEX.java:240)
	at ru.tehkode.permissions.bukkit.regexperms.PermissiblePEX.hasPermission(PermissiblePEX.java:127)
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:214)
	at net.minecraft.server.v1_16_R3.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:189)
	at net.minecraft.server.v1_16_R3.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:178)
	at net.minecraft.server.v1_16_R3.CommandBossBar.b(SourceFile:54)
	at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:79)
	at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:401)
	at net.minecraft.server.v1_16_R3.CommandDispatcher.sendAsync(CommandDispatcher.java:359)
	at net.minecraft.server.v1_16_R3.CommandDispatcher.lambda$a$5(CommandDispatcher.java:348)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by Zrips** [comment]
@danyadanya2005 
Please update to latest CMI version for best experience and full support for it. This should be fixed with newer versions.
