### ISSUE TITLE
 [CMI] Task #1026 for CMI v9.1.0.6 generated an exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Deviken** [Zrips/CMI#6565]
**Description of issue:**
having this after joining the server

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
##[11:28:41] [Server thread/WARN] [com.Zrips.CMI.CMI/]: [CMI] Task #1026 for CMI v9.1.0.6 generated an exception
java.lang.NullPointerException: null
	at org.dynmap.bukkit.DynmapPlugin.assertPlayerInvisibility(DynmapPlugin.java:1641) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:50) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapManager.processPlayer(DynMapManager.java:34) ~[?:?]
	at com.Zrips.CMI.Modules.DynMap.DynMapListener.lambda$0(DynMapListener.java:34) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:983) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:929) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:762) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?] ##
######################
```

```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
9.1.0.6
**Server Type (Spigot/Paperspigot/etc):** 
loliserver
**Server Version (using `/ver`):** 
This server is running LoliServer version 1.16.5-ccb19cf (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.22)[m

**Comment by CloudeLecaw** [comment]
Loli server... Fork of fork of fork of fork...

Ticket can be closed ;)

Give a test with Spigot or papermc and report back if issue still exist there.

**Comment by Zrips** [comment]
End issue originates at DynMap plugin, this needs to be fixed by that plugin.
