### ISSUE TITLE
Maxplayer command error

### ISSUE THREAD

**Issue by norhu1130** [Zrips/CMI#6575]
**Description of issue:**
Error Edit Maxplayer

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:53:07 INFO]: norhu1130 issued server command: /maxplayers 50
[20:53:07 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.getPlayerList()
[20:53:07 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[20:53:07 WARN]:        at CMI9.1.0.6.jar//com.Zrips.CMI.Reflections.changePlayerLimit(Reflections.java:258)
[20:53:07 WARN]:        at CMI9.1.0.6.jar//com.Zrips.CMI.commands.list.maxplayers.perform(maxplayers.java:34)
[20:53:07 WARN]:        at CMI9.1.0.6.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[20:53:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:53:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[20:53:07 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[20:53:07 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2368)
[20:53:07 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2179)
[20:53:07 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2160)
[20:53:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[20:53:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[20:53:07 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[20:53:07 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:53:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[20:53:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[20:53:07 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1440)
[20:53:07 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[20:53:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[20:53:07 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1418)
[20:53:07 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1411)
[20:53:07 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[20:53:07 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1389)
[20:53:07 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1295)
[20:53:07 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[20:53:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/46096192/149620847-3656bee6-6e6c-41f7-a702-d7a5d0e95d2f.png)

**Server Type (Spigot/Paperspigot/etc):** 
etc(Purpur)
**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/46096192/149620857-0c995cd4-2cc6-475e-9997-da6a6a913919.png)
(Purpur Forked)

**Comment by Zrips** [comment]
Fixed with 9.1.1.2 version
