### ISSUE TITLE
org.bukkit.command.CommandException: Unhandled exception executing 'is admin reload' in com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand(island)

### ISSUE THREAD

**Issue by Eth4nSP** [Zrips/CMI#6588]
**Description of issue:**
Doesn't work /is admin reload
(In game) An internal error occurred while attermpting to perform this command 
(console):
---

Unexpected exception while parsing console command "is admin reload"
org.bukkit.command.CommandException: Unhandled exception executing 'is admin reload' in com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand(island)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Airplane-112]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:531) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Airplane-112]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-112]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.IllegalArgumentException: The embedded resource 'modules/missions/BlocksMissions' cannot be found in plugins/SuperiorSkyblock2-1.8.3.jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:193) ~[patched_1.17.1.jar:git-Airplane-112]
        at com.bgsoftware.superiorskyblock.utils.FileUtils.copyResource(FileUtils.java:210) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.generateDefaultFiles(MissionsModule.java:43) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.module.missions.MissionsModule.onPluginInit(MissionsModule.java:90) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onPluginInit(BuiltinModule.java:54) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.module.BuiltinModule.onReload(BuiltinModule.java:29) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.lambda$reloadPlugin$3(SuperiorSkyblockPlugin.java:497) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087) ~[?:?]
        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:497) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.commands.admin.CmdAdminReload.execute(CmdAdminReload.java:56) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.commands.player.CmdAdmin.execute(CmdAdmin.java:75) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.commands.ISuperiorCommand.execute(ISuperiorCommand.java:18) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at com.bgsoftware.superiorskyblock.commands.CommandsHandler$PluginCommand.execute(CommandsHandler.java:262) ~[SuperiorSkyblock2-1.8.3.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Airplane-112]
        ... 8 more

---

**Server Type (Spigot):** 

**Server Version (1.17.1):** 

**Relevant plugins (Superior Skyblock2):**

**Comment by Zrips** [comment]
Caused by SuperiorSkyblockPlugin and not CMI
