### ISSUE TITLE
/MaxPlayers Error

### ISSUE THREAD

**Issue by Strahilchu** [Zrips/CMI#6614]
Executing /MaxPlayers return an error and does not work.
Server is on a Velocity Network

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[14:09:34 INFO]: Strahill issued server command: /cmi maxplayers 99
[14:09:34 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.dedicated.DedicatedServer.getPlayerList()
[14:09:34 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[14:09:34 WARN]:        at CMI9.1.1.1.jar//com.Zrips.CMI.Reflections.changePlayerLimit(Reflections.java:258)
[14:09:34 WARN]:        at CMI9.1.1.1.jar//com.Zrips.CMI.commands.list.maxplayers.perform(maxplayers.java:34)
[14:09:34 WARN]:        at CMI9.1.1.1.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[14:09:34 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:09:34 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:09:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897)
[14:09:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2288)
[14:09:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2099)
[14:09:34 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2080)
[14:09:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[14:09:34 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[14:09:34 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[14:09:34 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1415)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1393)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1386)
[14:09:34 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1270)
[14:09:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[14:09:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

---

**Cmi Version (using`/cmi version`):** 
9.1.1.1
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
1.18

**Comment by Zrips** [comment]
Gets a fix with next version
