### ISSUE TITLE
Unable to fully run on 1.16.5, some functions will not be available.

### ISSUE THREAD

**Issue by NEIKI19914** [Zrips/CMI#6632]
**Description of issue:**

For some reasons, I need to open an old version of 1.16.5 server. I hope I can repair it or tell me what version of the plug-in supports 1.16.5.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.IllegalArgumentException: Newer version! Server downgrades are not supported!
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.getMaterial(CraftMagicNumbers.java:194) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:501) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
**Cmi Version (using`/cmi version`):**
 
CMI9.1.1.2   CMILib1.1.1.0

**Server Type (Spigot/Paperspigot/etc):** 

Spigot

**Server Version (using `/ver`):** 

This server is running CraftBukkit version 3096a-Spigot-9fb885e-af1a232 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Checking version, please wait...
You are 52 version(s) behind

**Relevant plugins (Delete if this isn't needed):**
LuckPerms-Bukkit-5.3.86

**Comment by Zrips** [comment]
It looks to be just simple issue when trying to load in kits file which with new server versions gets slightly different format, so trying to convert it back might result in issues like that. You might need to redo your kits or try to spot differences and fix that. its not really a CMI issue in general as its only uses official spigot API to serialize items for simpler save. If you dont care about kits then you can simply ignore this message in general.

**Comment by NEIKI19914** [comment]
> It looks to be just simple issue when trying to load in kits file which with new server versions gets slightly different format, so trying to convert it back might result in issues like that. You might need to redo your kits or try to spot differences and fix that. its not really a CMI issue in general as its only uses official spigot API to serialize items for simpler save. If you dont care about kits then you can simply ignore this message in general.

Thank you very much. It's found that it's a problem with the configuration file. It's OK after regeneration.
