### ISSUE TITLE
CMI Mirror with angelchest plugin throws error.

### ISSUE THREAD

**Issue by janiiik** [Zrips/CMI#6638]
Hi, I have reported this issue to angelchest developer and was kindly redirected to report it here, so will try my best to describe it. When using CMI mirror, Angelchest plugins how errors in console. It was explained to me that the ItemStack class itself actually creates a new ItemMeta if none exists, so it must be something like... CMI creates a new class that extends ItemStack, and they don't properly provide ItemMeta for that item. I can ask for more info if needed.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Here is the error
[19:58:27 ERROR]: Could not pass event BlockPlaceEvent to AngelChest v6.2.0
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at de.jeff_media.angelchest.jefflib.PDCUtils.has(PDCUtils.java:324) ~[AngelChest.jar:?]
        at de.jeff_media.angelchest.listeners.PlayerListener.onPlaceAngelChestItem(PlayerListener.java:879) ~[AngelChest.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor223.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-186]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.Zrips.CMI.Modules.Mirror.MirrorManager.MirrorPlace(MirrorManager.java:430) ~[CMI9.1.1.2 (1).jar:?]
        at com.Zrips.CMI.Modules.Mirror.MirrorListener.lambda$0(MirrorListener.java:26) ~[CMI9.1.1.2 (1).jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-186]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-186]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-186]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]



---

**Cmi Version (using`/cmi version`): 9,1,1,2** 

**Server Type (Spigot/Paperspigot/etc): Paper** 

**Server Version (using `/ver`): 1.18.1** 

**Relevant plugins (Delete if this isn't needed): CMI, AngelChest Plus**

**Comment by Zrips** [comment]
Error points to call of BlockPlaceEvent which simply fires one to check if player can place block in that location. Duno why that developer points to me when he can simply add NULL check for whatever reason there is one in his code. I wont be digging around his code but entire issue originates at `de.jeff_media.angelchest.jefflib.PDCUtils.has(PDCUtils.java:324)`
