### ISSUE TITLE
CMIFakeOperator It won't let you start another plugin

### ISSUE THREAD

**Issue by Blotcraft** [Zrips/CMI#6643]
The fake user "CMIFakeOperator" does not allow another plugin to start because it needs to collect graphical information about it via UUID. And since the UUID of the CMIFakeOperator does not exist, it causes the plugin to be corrupted and unable to run.

Could you activate an option so that the CMIFakeOperator can be removed?

```yaml
[17:20:52 WARN]: javax.imageio.IIOException: Can't get input stream from URL!
[17:20:52 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.formatting.string.ImageBreakdown.<init>(ImageBreakdown.java:111)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.formatting.string.ImageBreakdown.<init>(ImageBreakdown.java:183)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.data.service.PlayerSearch$1$1.<init>(PlayerSearch.java:64)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.data.service.PlayerSearch$1.lambda$new$0(PlayerSearch.java:64)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.task.RenderedTask$1$1.execute(RenderedTask.java:80)
[17:20:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:20:52 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[17:20:52 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:20:52 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.interfacing.OrdinalProcedure.lambda$process$1(OrdinalProcedure.java:68)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.data.service.AnnotationDiscovery.ifPresent(AnnotationDiscovery.java:146)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.interfacing.OrdinalProcedure.process(OrdinalProcedure.java:65)
[17:20:52 WARN]:        at Labyrinth.jar//com.github.sanctum.labyrinth.task.Task.run(Task.java:50)
[17:20:52 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[17:20:52 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:506)
[17:20:52 WARN]: Caused by: java.io.FileNotFoundException: https://minotar.net/avatar/CMI-Fake-Operator.png
[17:20:52 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1981)
[17:20:52 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[17:20:52 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[17:20:52 WARN]:        at java.base/java.net.URL.openStream(URL.java:1192)
[17:20:52 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405)
[17:20:52 WARN]:        ... 15 more
```

CMI VERSION
```yaml
[17:23:40 INFO]: --------------------------------------------------
[17:23:40 INFO]: CMI: 9.1.1.2 BungeeCord CMIB  SqLite
[17:23:40 INFO]: CMILib: 1.1.1.0
[17:23:40 INFO]: Server: Purpur 1.17.1-R0.1-SNAPSHOT
[17:23:40 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Disabled
[17:23:40 INFO]: Modules -> 55 enabled 1 disabled: tablist
[17:23:40 INFO]: --------------------------------------------------
```

**I look forward to your prompt response, Mr. Zrips. Or if you can also tell me how to fix it by modifying something in my other plugin.**

**Comment by CloudeLecaw** [comment]
Would that be a thing to ask the dev of thr Labyrinth plugin to just scan for existing users or use a default avatar (mostly  the steve Avatar) if no Account has been found on the site..

**Comment by Zrips** [comment]
@Blotcraft 
Will add option to no longer utilize fake operator if you dont really need that, you will find that option in config.yml under Optimizations.UseFakeOperator section. Keep in mind that you might still need to remove player data file which is named as ffffffff-ffff-ffff-ffff-fffffffffff0.dat  in your main world player data folder.
Side thing, this in general should have been fixed by Labyrinth plugin, but at same time others might want to disable that too, so we can have it as a feature from now on.
