### ISSUE TITLE
BUG CMI NTB ISPIGOT 1.8.8

### ISSUE THREAD

**Issue by Betob89** [Zrips/CMI#6647]
**Description of issue:**

player type ./home and the error show

[03:45:56 INFO]: Versión de CMI: 9.1.1.2
Base de Datos: SqLite
[03:45:56 INFO]: Versión de CMILib: 1.1.1.0
[03:45:56 INFO]: Versión del Servidor: iSpigot 1.8.8-R0.1-SNAPSHOT

[03:38:54 WARN]: java.lang.NullPointerException
[03:38:54 WARN]:        at net.Zrips.CMILib.NBT.CMINBT.HideFlag(CMINBT.java:948)
[03:38:54 WARN]:        at net.Zrips.CMILib.GUI.CMIGuiButton.hideItemFlags(CMIGuiButton.java:61)
[03:38:54 WARN]:        at com.Zrips.CMI.Modules.Homes.HomeManager.openComplexHomeGui(HomeManager.java:748)
[03:38:54 WARN]:        at com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:553)
[03:38:54 WARN]:        at com.Zrips.CMI.commands.list.homes.perform(homes.java:161)
[03:38:54 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.performCMICommand(CommandsHandler.java:105)
[03:38:54 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.performCMICommand(CommandsHandler.java:98)
[03:38:54 WARN]:        at com.Zrips.CMI.commands.list.home.perform(home.java:77)
[03:38:54 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[03:38:54 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[03:38:54 WARN]:        at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:92)
[03:38:54 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(SourceFile:717)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(SourceFile:1361)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(SourceFile:1173)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:54)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:14)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:21)
[03:38:54 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[03:38:54 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:18)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(SourceFile:938)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(SourceFile:502)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(SourceFile:868)
[03:38:54 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:769)
[03:38:54 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Zrips** [comment]
I'm not aware of iSpigot fork. Where could i get server file to test it?
