### ISSUE TITLE
Error in Armor Stand position options

### ISSUE THREAD

**Issue by EpicPlayerA10** [Zrips/CMI#6649]
**Description of issue:**

When I middle click on any option in position options then i get an error.

---

**ERROR:**
```
[20:54:44 ERROR]: Could not pass event InventoryClickEvent to CMILib v1.1.1.0
java.lang.ArithmeticException: / by zero
        at com.Zrips.CMI.Modules.AStand.ArmorStandManager.changeAngle(ArmorStandManager.java:1545) ~[CMI9.1.1.2.jar:?]
        at com.Zrips.CMI.Modules.AStand.ArmorStandManager.changeAngle(ArmorStandManager.java:1483) ~[CMI9.1.1.2.jar:?]
        at com.Zrips.CMI.Modules.AStand.ArmorStandManager$34.click(ArmorStandManager.java:1246) ~[CMI9.1.1.2.jar:?]
        at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:263) ~[CMILib1.1.1.0(1).jar:?]
        at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:220) ~[CMILib1.1.1.0(1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor151.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-187]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2842) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-187]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-187]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/62206933/153772451-48568e82-0ad4-49ff-9c68-7c399284f106.png)

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/62206933/153772484-5e2cadec-c009-4437-9d44-820530d5628f.png)

**Comment by Zrips** [comment]
Will be fixed with next version
