### ISSUE TITLE
Databases error

### ISSUE THREAD

**Issue by SbirTeo** [Zrips/CMI#6650]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
[00:02:44 WARN]: java.sql.SQLSyntaxErrorException: Table 'MAGIC_CMI_Vanilla.CMI_users' doesn't exist
[00:02:44 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[00:02:44 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[00:02:44 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[00:02:44 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
[00:02:44 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.getId(DBDAO.java:1114)
[00:02:44 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.getUserIds(DBDAO.java:1442)
[00:02:44 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:530)
[00:02:44 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:342)
[00:02:44 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[00:02:44 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[00:02:44 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:02:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:02:44 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:02:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---
Latest version of CMI and server 1.18.1

I created a new Database and happen this

**Comment by Zrips** [comment]
Check startup logs if server properly loaded up or not, this usually is a result of failed database table creation for one or another reason.

**Comment by SbirTeo** [comment]
The server startup log is clean. No errors. Database connection starter
successfully. This error happens later...

Il Mer 16 Feb 2022, 12:23 Zrips ***@***.***> ha scritto:

**Comment by Zrips** [comment]
Could you confirm that your database contains database with name of `MAGIC_CMI_Vanilla` and table with name of `CMI_users`?

**Comment by Zrips** [comment]
Ok, while checking code, it looks more like you have set table prefix to be "MAGIC_CMI_Vanilla.CMI_" in your dataBaseInfo.yml file. Is that correct?

**Comment by SbirTeo** [comment]
It doesn't create tables in the database. Mysql connection start witouth
errors but it doesn't create tables. In my others server it works fine.

Il Mer 16 Feb 2022, 12:33 Zrips ***@***.***> ha scritto:

**Comment by Zrips** [comment]
Check your dataBaseInfo.yml if its properly setup . But what i'm interested in would be to know what you have set for tablePrefix in dataBaseInfo.yml

**Comment by Zrips** [comment]
Could be caused by outdated MySQL database on your new server in general.
Could I see actual startup log for CMI? While there might not be actual errors, there still should be extra indicator when database is being created which might help out to figure out why its failing.

**Comment by SbirTeo** [comment]
[19:18:40] [Server thread/INFO]: [CMI] Enabling CMI v9.1.1.2
[19:18:41] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[19:18:41] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[19:18:41] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃
[19:18:41] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃
[19:18:41] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[19:18:41] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[19:18:41] [Server thread/INFO]:
_______________________________________________________
[19:18:41] [Server thread/INFO]:   Integrating PaperSpigot async methods
[19:18:41] [Server thread/INFO]:   55 Enabled and 1 Disabled modules
[19:18:41] [Server thread/INFO]:   Permission plugin: LuckPerms5.3.98
[19:18:41] [Server thread/INFO]:   Initialized Cipher256 AES
[19:18:41] [Server thread/INFO]:   Loaded (59) regular alias into memory.
Took 41ms
[19:18:41] [Server thread/INFO]:   Loaded (1) custom text's into memory.
Took 0ms
[19:18:41] [Server thread/INFO]:   Detected Java17
[19:18:41] [Server thread/INFO]:   5.5.5-10.3.32-MariaDB-0ubuntu0.20.04.1
data base type detected
[19:18:41] [Server thread/INFO]:   Started MySQL data base. Took 469ms
[19:18:41] [Server thread/INFO]:   Vault was found - Enabling capabilities.
Economy: CMIEconomy
[19:18:42] [Server thread/INFO]:   Loaded (7) holograms into memory. Took
15ms
[19:18:42] [Server thread/INFO]:   Loaded (5) warning categories into
memory. Took 0ms
[19:18:42] [Server thread/INFO]:   Loaded (3) warning commands into memory.
Took 0ms
[19:18:42] [Server thread/INFO]:   Loaded (138) custom mob heads into
memory. Took 14ms
[19:18:42] [Server thread/INFO]:   Loaded (0) cooldowns into memory. Took
20ms
[19:18:42] [Server thread/INFO]:   Enabling BungeeCord Support
[19:18:42] [Server thread/INFO]:   Initializing BungeeCord
[19:18:42] [Server thread/INFO]:   Loaded (5) kits into memory. Took 28ms
[19:18:42] [Server thread/INFO]:   Loaded (7) ranks into memory. Took 8ms
[19:18:42] [Server thread/INFO]:   Loaded (8) playtime rewards into memory.
Took 1ms
[19:18:42] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table
'MAGIC_CMI_BedWars.CMI_users' doesn't exist
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1211)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:587)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1516)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:18:42] [Server thread/WARN]: at
org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[19:18:42] [Server thread/WARN]: at
org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:18:42] [Server thread/WARN]: at
java.base/java.lang.Thread.run(Thread.java:833)
[19:18:42] [Server thread/INFO]:   Loaded (0) player data into memory. Took
6ms
[19:18:42] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table
'MAGIC_CMI_BedWars.CMI_playtime' doesn't exist
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayTimes(DBDAO.java:1235)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:610)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1516)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:18:42] [Server thread/WARN]: at
org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[19:18:42] [Server thread/WARN]: at
org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:18:42] [Server thread/WARN]: at
java.base/java.lang.Thread.run(Thread.java:833)
[19:18:42] [Server thread/WARN]: java.sql.SQLSyntaxErrorException: Table
'MAGIC_CMI_BedWars.CMI_playtimereward' doesn't exist
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[19:18:42] [Server thread/WARN]: at
com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadPlayerPlayTimeRewards(DBDAO.java:1369)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:611)
[19:18:42] [Server thread/WARN]: at
CMI.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1516)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:18:42] [Server thread/WARN]: at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:18:42] [Server thread/WARN]: at
org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564)
[19:18:42] [Server thread/WARN]: at
org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[19:18:42] [Server thread/WARN]: at
net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:18:42] [Server thread/WARN]: at
java.base/java.lang.Thread.run(Thread.java:833)
[19:18:42] [Server thread/INFO]:   Loaded (1) custom alias into memory.
Took 2ms
[19:18:42] [Server thread/INFO]:   Loaded (4) interactive commands into
memory. Took 2ms
[19:18:42] [Server thread/INFO]:   Registered events. Took 85ms
[19:18:42] [Server thread/INFO]:   Loaded (0) event action commands into
memory. Took 3ms
[19:18:42] [Server thread/INFO]:   Updated (EN) language file. Took 107ms
[19:18:42] [Server thread/INFO]:   Updated (IT) language file. Took 97ms
[19:18:42] [Server thread/INFO]:   Loaded (245) worth values into memory.
Took 38ms
[19:18:42] [Server thread/INFO]:   Vault permissions was found - Enabling
capabilities.
[19:18:42] [Server thread/INFO]: [PlaceholderAPI] Successfully registered
expansion: cmi [9.1.1.2]
[19:18:42] [Server thread/INFO]:   PlaceholderAPI hooked.
[19:18:42] [Server thread/INFO]:   PlaceholderAPI was found - Enabling
capabilities.
[19:18:42] [Server thread/INFO]:   Starting world timer.
[19:18:42] [Server thread/INFO]:   Initializing world manager.
[19:18:42] [Server thread/INFO]:   Loaded (5) schedules into memory. Took
7ms
[19:18:42] [Server thread/INFO]:   Loaded GeoIP
[19:18:42] [Server thread/INFO]:   Loaded (6) skin cache entries into
memory. Took 1ms
[19:18:42] [Server thread/INFO]:   Loaded (0) ArmorStand templates into
memory. Took 0ms
[19:18:42] [Server thread/INFO]:   Version 9.1.1.2 has been enabled
[19:18:42] [Server thread/INFO]:
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

Il giorno mer 16 feb 2022 alle ore 13:43 Zrips ***@***.***>
ha scritto:

**Comment by SbirTeo** [comment]
I changed TABLES_PREFIX to CMI_BEDWARS_ and it works, why???

Il giorno mer 16 feb 2022 alle ore 19:22 Teodoro Locorotondo <
***@***.***> ha scritto:

**Comment by Brickwrath** [comment]
Just ran into this on 1.18.1 with latest CMI; my TABLES_PREFIX was just `CMI_` causing this issue, despite the SCHEMA only being used by one server.
Was fixed by making my prefix `CMI_Hub_` or similar for servers.
