### ISSUE TITLE
CMI does not load the RU language file

### ISSUE THREAD

**Issue by ms0ur** [Zrips/CMI#6671]
**Description of issue:**

CMI does not load the RU language file. I did not open or change the language file itself in any way.
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_PL.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_ES.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_SK.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_SL.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_FR.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_NO.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_TR.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_IT.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_ZH.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_CN.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_LT.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_DE.yml file
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_CZ.yml file
[12:14:44] [Server thread/INFO]: [CMI] Updated (EN) language file. Took 99ms
[12:14:44] [Server thread/WARN]: org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
[12:14:44] [Server thread/WARN]:  in 'reader', line 1151, column 7:
[12:14:44] [Server thread/WARN]:           joined: '&eВы зашли в комнату: & ... 
[12:14:44] [Server thread/WARN]:           ^
[12:14:44] [Server thread/WARN]: expected <block end>, but found '<anchor>'
[12:14:44] [Server thread/WARN]:  in 'reader', line 1160, column 18:
[12:14:44] [Server thread/WARN]:           notOwner: '&4Только владелец чата может это ... 
[12:14:44] [Server thread/WARN]:                      ^
[12:14:44] [Server thread/WARN]: 
[12:14:44] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
[12:14:44] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[12:14:44] [Server thread/WARN]: 	at CMILib1.1.1.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:267)
[12:14:44] [Server thread/WARN]: 	at CMILib1.1.1.0.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:50)
[12:14:44] [Server thread/WARN]: 	at CMI9.1.1.3.jar//com.Zrips.CMI.Config.LoadLang(Config.java:506)
[12:14:44] [Server thread/WARN]: 	at CMI9.1.1.3.jar//com.Zrips.CMI.Config.reloadLanguage(Config.java:2733)
[12:14:44] [Server thread/WARN]: 	at CMI9.1.1.3.jar//com.Zrips.CMI.CMI$1.afterDownload(CMI.java:461)
[12:14:44] [Server thread/WARN]: 	at CMI9.1.1.3.jar//com.Zrips.CMI.utils.FileDownloader$1.lambda$0(FileDownloader.java:45)
[12:14:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:14:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:14:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1575)
[12:14:44] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[12:14:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1498)
[12:14:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1285)
[12:14:44] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[12:14:44] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:14:44] [Server thread/WARN]: Caused by: while parsing a block mapping
[12:14:44] [Server thread/WARN]:  in 'reader', line 1151, column 7:
[12:14:44] [Server thread/WARN]:           joined: '&eВы зашли в комнату: & ... 
[12:14:44] [Server thread/WARN]:           ^
[12:14:44] [Server thread/WARN]: expected <block end>, but found '<anchor>'
[12:14:44] [Server thread/WARN]:  in 'reader', line 1160, column 18:
[12:14:44] [Server thread/WARN]:           notOwner: '&4Только владелец чата может это ... 
[12:14:44] [Server thread/WARN]:                      ^
[12:14:44] [Server thread/WARN]: 
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:644)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:166)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[12:14:44] [Server thread/WARN]: 	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
[12:14:44] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:102)
[12:14:44] [Server thread/WARN]: 	... 15 more
[12:14:44] [Server thread/INFO]: Failed to load Locale_RU.yml! Backup have been saved into plugins/CMILib/FileBackups/2022-02-22 12-14-44 Locale_RU.yml
[12:14:44] [Server thread/INFO]: [CMI] SEVERE LOCALE FILE READ ERROR. Check your spelling! Changes will not be applied until you fix it or perform server restart which can result in locale file reset to default
[12:14:44] [Server thread/INFO]: [CMI] Downloaded Locale_RU.yml file
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Language file you want to use
Language: RU
```

---

**Cmi Version (using`/cmi version`):** 
```
CMI: 9.1.1.3 BungeeCord SqLite-> 9.1.2.0
CMILib: 1.1.1.0 -> 1.1.1.1
Server: Purpur 1.18.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
Modules -> 55 enabled 1 disabled: votifier
```

**Comment by CloudeLecaw** [comment]
you see your logfile that the RU file is coruppted in some lines. you need to check them and may take the fresh file aggain

**Comment by Zrips** [comment]
@ms0ur 
Updated default RU file and fixed issue. You can ether remove current Ru file and let it be downloaded again, download it manually from github or fix issue manually which is locate at line 1159 and ' is missing at end of the line ```nobody: '&4В чате никого нет'```
