### ISSUE TITLE
world unloaded

### ISSUE THREAD

**Issue by haroldrc** [Zrips/CMI#6681]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[18:26:21 WARN]: java.lang.IllegalArgumentException: World unloaded
[18:26:21 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[18:26:21 WARN]:        at org.bukkit.Location.getWorld(Location.java:112)
[18:26:21 WARN]:        at CMILib1.1.1.1.jar//net.Zrips.CMILib.Container.CMILocation.updateWorld(CMILocation.java:61)
[18:26:21 WARN]:        at CMILib1.1.1.1.jar//net.Zrips.CMILib.Container.CMILocation.recheck(CMILocation.java:56)
[18:26:21 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Homes.CmiHome.getLoc(CmiHome.java:33)
[18:26:21 WARN]:        at CMI.jar//com.Zrips.CMI.Containers.CMIUser.getHomesAsMap(CMIUser.java:1306)
[18:26:21 WARN]:        at CMI.jar//com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:936)
[18:26:21 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:717)
[18:26:21 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:476)
[18:26:21 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:342)
[18:26:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:26:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[18:26:21 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[18:26:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:26:21 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:26:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

[18:28:10 INFO]: Versione di CMI: 9.1.1.2 BungeeCord CMIB  SqLite-> 9.1.2.0
[18:28:10 INFO]: CMILib: 1.1.1.1 
[18:28:10 INFO]: Server: Pufferfish 1.18.1-R0.1-SNAPSHOT
[18:28:10 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
[18:28:10 INFO]: Modules -> 54 enabled 2 disabled: tablist, votifier

Previous version: git-Pufferfish-38 (MC: 1.18.1)

**Server Version (using `/ver`):** 

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should be fixed with next cmilib update
