### ISSUE TITLE
HOLOGRAMS

### ISSUE THREAD

**Issue by rafi67000** [Zrips/CMI#6699]
**Description of issue:**
When i click on hologram my server have crush and 
i'm cannot use the /cmi hologram
![image](https://user-images.githubusercontent.com/80040363/156025865-1b3b11c8-ffaa-4725-b0f3-e5d8d308253f.png)
but im still have visible old holograms
![image](https://user-images.githubusercontent.com/80040363/156025954-ea6fe771-ab08-4e52-9997-69f169e56b08.png)

---
and i have error on join (portal -> launchpad)
```
[17:33:47] [Server thread/INFO]: [Matrix] (Via) Player rafi67000 joined with (1.12.x/340) client
[17:33:51] [Server thread/WARN]: Excessive velocity set detected: tried to set velocity of entity #17 to (0.09301690384834244,1.794435844492636,-15.347789134976502).
[17:33:51] [Server thread/WARN]: java.lang.Exception: Stack trace
[17:33:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.dumpStack(Thread.java:1387)
[17:33:51] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.commands.list.launch.perform(launch.java:223)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[17:33:51] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1026)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:969)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:300)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:237)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:198)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Portals.CMIPortal.teleport(CMIPortal.java:130)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Portals.PortalListener.processMove(PortalListener.java:199)
[17:33:51] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Portals.PortalListener.onPlayerMove(PortalListener.java:110)
[17:33:51] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
[17:33:51] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:33:51] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[17:33:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[17:33:51] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[17:33:51] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:33:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[17:33:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:33:51] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[17:33:51] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:762)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701)
[17:33:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604)
[17:33:51] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```
---

CMI 9.1.2.0

Paperspigot/flamepaper and all forks

latest paperspigot version -> 1.8.8

-- AND  I HAVE ISSUE WITH HOLOGRAM ON 1.12.2 --

holograms.yml -> https://pastebin.com/K9wVPpPW
youtube (video with issue) -> https://youtu.be/9KlZVgfNBlw

**Comment by Zrips** [comment]
You have something weird going on with commands set on that hologram, from error message it looks to be related to player being launched at excessive speeds. Lower launch power for launch command and it should resolve your issue.
