### ISSUE TITLE
WARN messages spam in console (java.lang.NoClassDefFoundError: net/Zrips/CMILib/RawMessages/RawMessage)

### ISSUE THREAD

**Issue by smartmadio** [Zrips/CMI#6705]
**Description of issue:**
WARN messages spam in console:
```
[20:26:19 WARN]: [CMI] Plugin CMI v9.1.2.1 generated an exception while executing task 121782
java.lang.NoClassDefFoundError: net/Zrips/CMILib/RawMessages/RawMessage
        at com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:114) ~[CMI9.1.2.1.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:90) ~[CMI9.1.2.1.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:780) ~[CMI9.1.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-216]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-216]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-216]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.Zrips.CMILib.RawMessages.RawMessage
        ... 9 more
```

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[20:26:19 WARN]: [CMI] Plugin CMI v9.1.2.1 generated an exception while executing task 121782
java.lang.NoClassDefFoundError: net/Zrips/CMILib/RawMessages/RawMessage
        at com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:114) ~[CMI9.1.2.1.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:90) ~[CMI9.1.2.1.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager$3.run(TabListManager.java:780) ~[CMI9.1.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-216]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-216]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-216]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.Zrips.CMILib.RawMessages.RawMessage
        ... 9 more
```

---

**Cmi Version:** 
9.1.2.1
**Server Type :** 
Paperspigot
**Server Version:** 
Paperspigot(216) 1.18.1
**Relevant plugins:**
CMILib 1.1.1.2(The file name is 1.1.1.2 but it shows to be 1.1.1.1 in `cmi version`)

**Comment by smartmadio** [comment]
I've downloaded the latest version of CMILib in https://www.spigotmc.org/resources/cmilib.87610/
The file name is `CMILib1.1.1.2.jar`.

**Comment by smartmadio** [comment]
Problem disappeared after rolling back to CMI 9.1.2.0.

**Comment by Zrips** [comment]
Message like this usually gets caused by corrupted downloaded file, redownloading it usually resolves issue.
