### ISSUE TITLE
BIG BUG SPAM CONSOLE

### ISSUE THREAD

**Issue by Betob89** [Zrips/CMI#6709]
[21:15:04 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.AdvancementDataWorld
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:15:04 WARN]:        at java.lang.Class.forName0(Native Method)
[21:15:04 WARN]:        at java.lang.Class.forName(Class.java:264)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:248)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[21:15:04 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322)
[21:15:04 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:135)
[21:15:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:388)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:410)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:369)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:482)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:407)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:375)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:705)
[21:15:04 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:15:04 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Advancement$SerializedAdvancement
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:15:04 WARN]:        at java.lang.Class.forName0(Native Method)
[21:15:04 WARN]:        at java.lang.Class.forName(Class.java:264)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:256)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[21:15:04 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322)
[21:15:04 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:135)
[21:15:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:388)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:410)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:369)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:482)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:407)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:375)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:705)
[21:15:04 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:15:04 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.LootDeserializationContext
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:15:04 WARN]:        at java.lang.Class.forName0(Native Method)
[21:15:04 WARN]:        at java.lang.Class.forName(Class.java:264)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:261)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[21:15:04 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322)
[21:15:04 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:135)
[21:15:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:388)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:410)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:369)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:482)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:407)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:375)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:705)
[21:15:04 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:15:04 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Containers
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:15:04 WARN]:        at java.lang.Class.forName0(Native Method)
[21:15:04 WARN]:        at java.lang.Class.forName(Class.java:264)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:265)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[21:15:04 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322)
[21:15:04 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:135)
[21:15:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:388)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:410)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:369)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:482)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:407)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:375)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:705)
[21:15:04 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:15:04 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.DimensionManager
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[21:15:04 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[21:15:04 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[21:15:04 WARN]:        at java.lang.Class.forName0(Native Method)
[21:15:04 WARN]:        at java.lang.Class.forName(Class.java:264)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:319)
[21:15:04 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[21:15:04 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[21:15:04 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:15:04 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:322)
[21:15:04 WARN]:        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:135)
[21:15:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:388)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(SourceFile:410)
[21:15:04 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(SourceFile:369)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(SourceFile:482)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(SourceFile:407)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(SourceFile:375)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:389)
[21:15:04 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:705)
[21:15:04 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:15:05 INFO]: CMI hooked.

last version cmi lib and cmi   spigot 1.8.9

**Comment by Zrips** [comment]
CMILib1.1.2.2 should resolve your issue
