### ISSUE TITLE
Error CMILib1.1.2.0

### ISSUE THREAD

**Issue by ovski55** [Zrips/CMI#6715]
**Description of issue: When loading my server I get this error in the console about CmiLib

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## [12:04:04 INFO]: Enabling CMILib v1.1.2.0
[12:04:05 INFO]: Server version: v1_8_R3 - 1.8.8 - spigot
[12:04:05 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.AdvancementDataWorld
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.Class.forName0(Native Method)
[12:04:05 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:248)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[12:04:05 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[12:04:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:442)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:405)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:323)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:279)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:601)
[12:04:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:04:05 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Advancement$SerializedAdvancement
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.Class.forName0(Native Method)
[12:04:05 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:256)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[12:04:05 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[12:04:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:442)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:405)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:323)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:279)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:601)
[12:04:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:04:05 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.LootDeserializationContext
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.Class.forName0(Native Method)
[12:04:05 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:261)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[12:04:05 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[12:04:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:442)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:405)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:323)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:279)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:601)
[12:04:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:04:05 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Containers
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.Class.forName0(Native Method)
[12:04:05 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:265)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[12:04:05 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[12:04:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:442)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:405)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:323)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:279)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:601)
[12:04:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:04:05 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.DimensionManager
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[12:04:05 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[12:04:05 WARN]:        at java.lang.Class.forName0(Native Method)
[12:04:05 WARN]:        at java.lang.Class.forName(Unknown Source)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.getMinecraftClass(Reflections.java:504)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.initialize(Reflections.java:319)
[12:04:05 WARN]:        at net.Zrips.CMILib.Reflections.<init>(Reflections.java:129)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:81)
[12:04:05 WARN]:        at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:88)
[12:04:05 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327)
[12:04:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[12:04:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353)
[12:04:05 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:442)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:405)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:323)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:279)
[12:04:05 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:601)
[12:04:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[12:04:06 INFO]: CMI hooked.
[12:04:06 INFO]: Successfully registered expansion: cmil [1.1.2.0] ##
######################
``

---

**Cmi Version CMI9.1.3.0
**CMILib Version CMILib1.1.2.0

**Server Type (AtomSpigot:** 

**Server Version 1.8.8

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Updating to latest CMILib should resolve your issue
