### ISSUE TITLE
(CMI) NBT Error

### ISSUE THREAD

**Issue by DarrienNN** [Zrips/CMI#6722]
**Description of issue: Got this error randomly**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[19:13:21 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[19:13:21 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:561)
[19:13:21 WARN]:        at CMILib1.1.2.0.jar//net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:813)
[19:13:21 WARN]:        at CMILib1.1.2.0.jar//net.Zrips.CMILib.NBT.CMINBT.getList(CMINBT.java:409)
[19:13:21 WARN]:        at CMILib1.1.2.0.jar//net.Zrips.CMILib.NBT.CMINBT.getList(CMINBT.java:401)
[19:13:21 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.AllListeners.PlayerListeners.onInteractHead(PlayerListeners.java:480)
[19:13:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1181.execute(Unknown Source)
[19:13:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[19:13:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[19:13:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:13:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
[19:13:21 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[19:13:21 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
[19:13:21 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1841)
[19:13:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[19:13:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[19:13:21 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[19:13:21 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:13:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[19:13:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[19:13:21 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1416)
[19:13:21 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[19:13:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[19:13:21 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1393)
[19:13:21 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1386)
[19:13:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[19:13:21 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
[19:13:21 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1270)
[19:13:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[19:13:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[19:13:30 INFO]: [+] Eldrian123 joined the server
[19:13:36 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[19:13:36 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:561)
[19:13:36 WARN]:        at CMILib1.1.2.0.jar//net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:813)
[19:13:36 WARN]:        at CMILib1.1.2.0.jar//net.Zrips.CMILib.NBT.CMINBT.getList(CMINBT.java:409)
[19:13:36 WARN]:        at CMILib1.1.2.0.jar//net.Zrips.CMILib.NBT.CMINBT.getList(CMINBT.java:401)
[19:13:36 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.AllListeners.PlayerListeners.onInteractHead(PlayerListeners.java:480)
[19:13:36 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1181.execute(Unknown Source)
[19:13:36 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[19:13:36 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[19:13:36 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:13:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
[19:13:36 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[19:13:36 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:542)
[19:13:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1841)
[19:13:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[19:13:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[19:13:36 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[19:13:36 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:13:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[19:13:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[19:13:36 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1416)
[19:13:36 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[19:13:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[19:13:36 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1393)
[19:13:36 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1386)
[19:13:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[19:13:36 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1364)
[19:13:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1270)
[19:13:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:319)
[19:13:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/58543201/157549528-435b283b-2502-4d25-a179-30a76c24b653.png)

**Server Type (Spigot/Paperspigot/etc):** 
![image](https://user-images.githubusercontent.com/58543201/157549552-38a915e4-6a96-4dd1-bb00-3e78714eb2b4.png)

**Server Version (using `/ver`):** 
Pufferfish 1.18.1

**Comment by mrfloris** [comment]
Upgrading CMILib should resolve this I believe. If not, please feel free to update this ticket.
