### ISSUE TITLE
[1.18.2] /cmi placeholders

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6728]
**Description of issue:**
Was holding a sword with custom itemname and itemlore, and going through the pages of placeholders and on page 7 or 8 it seems to spit out an error

```
[12:07:01 INFO]: mrfloris issued server command: /cmi placeholders
[12:07:05 INFO]: mrfloris issued server command: /cmi placeholders -p:2
[12:07:08 INFO]: mrfloris issued server command: /cmi placeholders -p:3
[12:07:10 INFO]: mrfloris issued server command: /cmi placeholders -p:4
[12:07:13 INFO]: mrfloris issued server command: /cmi placeholders -p:5
[12:07:16 INFO]: mrfloris issued server command: /cmi placeholders -p:6
[12:07:20 INFO]: mrfloris issued server command: /cmi placeholders -p:7
[12:07:20 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Ranks.CMIRank.getNextRanks()" because the return value of "com.Zrips.CMI.Containers.CMIUser.getRank()" is null
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1298)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:880)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:725)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:627)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.list.placeholders.perform(placeholders.java:84)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[12:07:20 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:07:20 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:07:20 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:07:20 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[12:07:20 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:07:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:20 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Ranks.CMIRank.getNextRanks()" because the return value of "com.Zrips.CMI.Containers.CMIUser.getRank()" is null
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1298)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:880)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:725)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:59)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:643)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.list.placeholders.perform(placeholders.java:84)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[12:07:20 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:07:20 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:07:20 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:07:20 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[12:07:20 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:07:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:20 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Ranks.CMIRank.getNextValidRankUps(com.Zrips.CMI.Containers.CMIUser)" because the return value of "com.Zrips.CMI.Containers.CMIUser.getRank()" is null
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1112)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:880)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:725)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:627)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.list.placeholders.perform(placeholders.java:84)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[12:07:20 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:07:20 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:07:20 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:07:20 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[12:07:20 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:07:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:20 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Ranks.CMIRank.getNextValidRankUps(com.Zrips.CMI.Containers.CMIUser)" because the return value of "com.Zrips.CMI.Containers.CMIUser.getRank()" is null
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1112)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:880)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:725)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:59)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70)
[12:07:20 WARN]:        at PlaceholderAPI-2.11.2-DEV-148.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:643)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.list.placeholders.perform(placeholders.java:84)
[12:07:20 WARN]:        at CMI9.1.3.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396)
[12:07:20 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:07:20 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[12:07:20 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2297)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2108)
[12:07:20 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2089)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[12:07:20 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[12:07:20 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[12:07:20 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[12:07:20 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[12:07:20 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:07:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:07:24 INFO]: mrfloris issued server command: /cmi placeholders -p:8
[12:07:27 INFO]: mrfloris issued server command: /cmi placeholders -p:9
```
```
> cmi version
[12:16:43 INFO]: --------------------------------------------------
[12:16:43 INFO]: CMI plugin version: 9.1.3.0 SqLite
[12:16:43 INFO]: CMILib: 1.1.2.1
[12:16:43 INFO]: Server: Paper(241) 1.18.2-R0.1-SNAPSHOT
[12:16:43 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[12:16:43 INFO]: Modules -> 55 enabled 1 disabled: flightCharge
[12:16:43 INFO]: --------------------------------------------------
> ver
[12:16:43 INFO]: This server is running Paper version git-Paper-241 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: ea1efef)
You are running the latest version
```

**Comment by Zrips** [comment]
Will be fixed with next update
