### ISSUE TITLE
Error when player execute command while in afk mode

### ISSUE THREAD

**Issue by HeliosMY** [Zrips/CMI#6753]
**Description of issue:**
When player execute any command while he is on afk mode, console of PaperMC pop-up an error.
It happen if installed CMIB1.0.1.0 in BungeeCord (Waterfall). (If deleted CMIB it working fine)
Tested with clean new setup servers with only CMI and CMILib in PaperMC, and CMIB in BungeeCord (Waterfall).

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[17:37:19 WARN]: [CMI] Task #41 for CMI v9.1.3.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.Zrips.CMI.Modules.Afk.AfkInfo.getAfkFrom()" is null
        at com.Zrips.CMI.Containers.CMIUser$3.run(CMIUser.java:1717) ~[CMI9.1.3.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-267]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-267]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-267]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

---

**Cmi Version (using`/cmi version`):** 9.1.3.1

**Server Type (Spigot/Paperspigot/etc):** PaperMC

**Server Version (using `/ver`):** 1.18.2 Build 267

**Comment by Zrips** [comment]
Gets fix with next update
