### ISSUE TITLE
cmi error

### ISSUE THREAD

**Issue by BoolyStudy** [Zrips/CMI#6754]
[16:38:50 WARN]: [CMI] Task #1168435 for CMI v9.1.3.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.Zrips.CMI.Modules.Afk.AfkInfo.getAfkFrom()" is null
        at com.Zrips.CMI.Containers.CMIUser$3.run(CMIUser.java:1717) ~[CMI9.1.3.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1584) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1294) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1564]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Zrips** [comment]
Gets a fix with next update
