### ISSUE TITLE
Don't know why cmi doesn't work on my server

### ISSUE THREAD

**Issue by vlssu** [Zrips/CMI#6836]
**Description of issue:**

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[13:14:53 INFO]: [Vault] Enabling Vault v1.7.3-CMI
[13:14:53 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024
[13:14:53 WARN]:        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
[13:14:53 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222)
[13:14:53 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
[13:14:53 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
[13:14:53 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634)
[13:14:53 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[13:14:53 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[13:14:53 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[13:14:53 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[13:14:53 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[13:14:53 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[13:14:53 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[13:14:53 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
[13:14:53 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[13:14:53 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[13:14:53 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[13:14:53 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[13:14:53 WARN]:        at net.milkbowl.vault.Vault.loadEconomy(Vault.java:283)
[13:14:53 WARN]:        at net.milkbowl.vault.Vault.onEnable(Vault.java:140)
[13:14:53 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:14:53 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[13:14:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[13:14:53 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:499)
[13:14:53 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411)
[13:14:53 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
[13:14:53 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:774)
[13:14:53 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[13:14:53 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
```
```
[13:14:54 ERROR]: Error occurred while enabling CMIEInjector v1.0.2.3 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491) ~[plasmo_voice:?]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[plasmo_voice:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[forge:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[forge:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[forge:?]
        at com.Zrips.Injector.onEnable(Injector.java:52) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:499) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:774) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
```
[13:18:43 WARN]: Unexpected exception while parsing console command "cmi"
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v9.1.4.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:769) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:755) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:366) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
[13:18:44 WARN]: Unexpected exception while parsing console command "list"
org.bukkit.command.CommandException: Unhandled exception executing 'list' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(list)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:176) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:769) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:755) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:366) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: com/Zrips/CMI/Containers/Snd
        at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:198) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[forge:?]
        ... 8 more
```
```
[15:02:00 INFO]: [CMILib] Enabling CMILib v1.1.2.5
[15:02:01 INFO]: Server version: v1_16_R3 - 1.16.5 - spigot
[15:02:02 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024
[15:02:02 WARN]:        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
[15:02:02 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222)
[15:02:02 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
[15:02:02 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
[15:02:02 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634)
[15:02:02 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[15:02:02 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[15:02:02 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[15:02:02 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[15:02:02 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[15:02:02 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[15:02:02 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[15:02:02 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
[15:02:02 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[15:02:02 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
[15:02:02 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[15:02:02 WARN]:        at net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:267)
[15:02:02 WARN]:        at net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:50)
[15:02:02 WARN]:        at net.Zrips.CMILib.CMILibConfig.load(CMILibConfig.java:94)
[15:02:02 WARN]:        at net.Zrips.CMILib.CMILibConfig.load(CMILibConfig.java:72)
[15:02:02 WARN]:        at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:195)
[15:02:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[15:02:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[15:02:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[15:02:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:499)
[15:02:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411)
[15:02:02 WARN]:        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:430)
[15:02:02 WARN]:        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349)
[15:02:02 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220)
[15:02:02 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:774)
[15:02:02 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[15:02:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
[15:02:02 INFO]: CMI hooked.
[15:02:03 INFO]: [PlaceholderAPI] Successfully registered expansion: cmil [1.1.2.5]
[15:02:03 INFO]: PlaceholderAPI hooked.
[15:02:03 INFO]: Updated (EN) language file. Took 111ms
[15:02:03 INFO]: Updated (CN) language file. Took 33ms
[15:02:03 INFO]: [CMI] Enabling CMI v9.1.4.1
[15:02:04 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[15:02:04 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[15:02:04 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[15:02:04 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[15:02:04 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[15:02:04 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[15:02:04 INFO]: _______________________________________________________
[15:02:04 INFO]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@6bcd44b9
[15:02:05 INFO]:   56 Enabled and 0 Disabled modules
[15:02:06 INFO]:   Permission plugin: LuckPerms5.4.9
[authlib-injector] [INFO] Transformed [com.Zrips.CMI.utils.PrevNamesFetcher] with [Constant URL Transformer]
[15:02:06 INFO]:   Initialized Cipher256 AES
[15:02:08 INFO]:   Loaded (60) regular alias into memory. Took 85ms
[15:02:08 INFO]:   Loaded (1) custom text's into memory. Took 6ms
[15:02:08 WARN]: java.lang.ArrayIndexOutOfBoundsException
[15:02:08 ERROR]: Error occurred while enabling CMI v9.1.4.1 (Is it up to date?)
java.lang.NullPointerException: null
        at com.Zrips.CMI.Config.load(Config.java:775) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1465) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:499) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:411) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:430) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:774) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
[15:02:08 INFO]: [CMI] Disabling CMI v9.1.4.1
[15:02:08 INFO]: Server permissions file permissions.yml is empty, ignoring it
```
---

**Cmi Version (using`/cmi version`):** 
```
[13:21:36 WARN]: Unexpected exception while parsing console command "cmi version"
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v9.1.4.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:769) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:755) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:366) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:338) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1006) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
![image](https://user-images.githubusercontent.com/43847794/164608980-b443bb25-3de6-4263-8b2b-8aed165a7802.png)

**Server Type (Spigot/Paperspigot/etc):** 
[MohistMC](https://mohistmc.com/)
**Server Version (using `/ver`):** 
This server is running Mohist version 1.16.5-963 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.33)
**Relevant plugins (Delete if this isn't needed):**
Plugins (10): CoreProtect, LuckPerms, PlugMan, Vault, PlaceholderAPI, ProtocolLib, AncientGates, CMILib, CMI, CMIEInjector

**Comment by CloudeLecaw** [comment]
Maybe because cmi does not support forge?

**Comment by vlssu** [comment]
> AncientGates

Find the problem, it is the problem caused by the AncientGates plugin, it is normal to delete it.

**Comment by vlssu** [comment]
> Maybe because cmi does not support forge (Mohist Forge)?
> 
> `[15:02:01 INFO]: Server version: v1_16_R3 - 1.16.5 - spigot` May its not enough from mohist to authenicate itself to cmi as spigot.
> 
> Well in this case of not using spigot or paper we say "it can work, it can not. Its 50/50, but dont aspect support if your using a not supported server"
> 
> Try it with paper or Spigot you will see it loads fine.

Find the problem, it is the problem caused by the AncientGates plugin, it is normal to delete it.
