### ISSUE TITLE
Can send "\" in private message

### ISSUE THREAD

**Issue by coco0325** [Zrips/CMI#685]
**Description of issue or feature request:**
Players can't send "\" in private message.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
01.08 16:48:39 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.1.0
01.08 16:48:39 [Server] INFO org.bukkit.event.EventException: null
01.08 16:48:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
01.08 16:48:39 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
01.08 16:48:39 [Server] INFO Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
01.08 16:48:39 [Server] INFO at java.util.regex.Matcher.appendReplacement(Unknown Source) ~[?:1.8.0_171]
01.08 16:48:39 [Server] INFO at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_171]
01.08 16:48:39 [Server] INFO at java.lang.String.replaceAll(Unknown Source) ~[?:1.8.0_171]
01.08 16:48:39 [Server] INFO at com.Zrips.CMI.Modules.Alias.AliasManager.updateCommands(AliasManager.java:264) ~[?:?]
01.08 16:48:39 [Server] INFO at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:47) ~[?:?]
01.08 16:48:39 [Server] INFO at sun.reflect.GeneratedMethodAccessor1156.invoke(Unknown Source) ~[?:?]
01.08 16:48:39 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
01.08 16:48:39 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
01.08 16:48:39 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2-tw.jar:git-Spigot-642f6d2-57ab4cf]
01.08 16:48:39 [Server] INFO ... 16 more
```

**Cmi Version (using`/cmi version`):** 
8.0.1.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot 1.12.2
**Server Version (using `/ver`):** 
git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Will be fixed with next build.
