### ISSUE TITLE
CMI keeps reporting error

### ISSUE THREAD

**Issue by jack444410** [Zrips/CMI#6861]
**Description of issue:**
CMI keeps reporting this error to console.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[21:11:16 WARN]: java.sql.BatchUpdateException: Unknown column 'Options' in 'field list'
[21:11:16 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:11:16 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[21:11:16 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:11:16 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[21:11:16 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[21:11:16 WARN]:        at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
[21:11:16 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:167)
[21:11:16 WARN]:        at com.mysql.cj.util.Util.getInstance(Util.java:174)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:853)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:435)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:800)
[21:11:16 WARN]:        at CMI9.1.4.3.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:895)
[21:11:16 WARN]:        at CMI9.1.4.3.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:516)
[21:11:16 WARN]:        at CMI9.1.4.3.jar//com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:342)
[21:11:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[21:11:16 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[21:11:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[21:11:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:11:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:11:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:11:16 WARN]: Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'Options' in 'field list'
[21:11:16 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098)
[21:11:16 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:832)
[21:11:16 WARN]:        ... 11 more
```

---

**Cmi Version (using`/cmi version`): 9.1.4.3

**Server Type (Spigot/Paperspigot/etc): Paper

**Server Version (using `/ver`):** This server is running Paper version git-Paper-267 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: e7d928a)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Should get a fix with next version
