### ISSUE TITLE
error loading with MythicMobs

### ISSUE THREAD

**Issue by fillnati** [Zrips/CMI#6914]
### Description of Issue

When load CMi, CMiLib and MythicMobs, MythicLib. I recive  Error message MythicMobs

### Version Information

```shell
[13:19:01 INFO]: --------------------------------------------------
[13:19:01 INFO]: CMI: 9.1.4.7 SqLite
[13:19:01 INFO]: CMILib: 1.1.2.5 
[13:19:01 INFO]: Server: Paper(333) 1.18.2-R0.1-SNAPSHOT
[13:19:01 INFO]: CMI economy: Disabled CMI Chat: Disabled 
[13:19:01 INFO]: Modules -> 55 enabled 1 disabled: votifier
[13:19:01 INFO]: --------------------------------------------------
```

### Errors

```shell
[12:59:33 ERROR]: Error occurred while enabling MythicMobs v5.0.4-f1007ca3 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'javassist.d javassist.f.a(javassist.d)' the class loader 'MythicMobs-5.0.4.jar' @7c9508f1 of the current class, io/lumine/mythic/bukkit/utils/plugin/LuminePluginL10, and the class loader 'CMILib1.1.2.5.jar' @5aa600d8 for the method's defining class, javassist/f, have different Class objects for the type javassist/d used in the signature (io.lumine.mythic.bukkit.utils.plugin.LuminePluginL10 is in unnamed module of loader 'MythicMobs-5.0.4.jar' @7c9508f1, parent loader java.net.URLClassLoader @759ebb3d; javassist.f is in unnamed module of loader 'CMILib1.1.2.5.jar' @5aa600d8, parent loader java.net.URLClassLoader @759ebb3d)
        at io.lumine.mythic.bukkit.utils.plugin.LuminePluginL10.a(Unknown Source) ~[MythicMobs-5.0.4.jar:?]
        at io.lumine.mythic.bukkit.utils.plugin.LuminePlugin.onEnable(LuminePlugin.java) ~[MythicMobs-5.0.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-333]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-333]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-333]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Relevant Plugins

mythicmobs 5.0.4; MythicLib-1.3.1;

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
CMI or CMILib doesn't use anything relating to Mythic mobs plugin. You might want to give a shout to MythicMobs plugin dev as this one originates from that plugin.
