### ISSUE TITLE
is it a good? (9.1.4.3)

### ISSUE THREAD

**Issue by 2cGukEH** [Zrips/CMI#6916]
### Description of Issue

There seems to be a conflict with other plugins.
(I also contacted other developers related to the issue)

This is a problem that often occurred even after the previous CMI update.
It's still an old version, but I'll report it here in advance in case it happens again.

### Version Information

```shell
[20:28:02 INFO]: CMI plugin version: 9.1.4.3 BungeeCord CMIB  SqLite-> 9.1.4.7
[20:28:02 INFO]: CMILib: 1.1.2.5
[20:28:02 INFO]: Server: Purpur 1.18.2-R0.1-SNAPSHOT
[20:28:02 INFO]: CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled
[20:28:02 INFO]: Modules -> 55 enabled 1 disabled: votifier
```

### Errors

```shell
[20:13:10 WARN]:        at CMI9.1.4.3.jar//com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:434)
[20:13:10 WARN]:        at CMI9.1.4.3.jar//com.Zrips.CMI.Containers.CMIUser.getPlayer(CMIUser.java:417)
[20:13:10 WARN]:        at CMI9.1.4.3.jar//com.Zrips.CMI.Containers.CMIUser.isVanished(CMIUser.java:1936)
[20:13:10 WARN]:        at InteractiveChat-4.1.4.15.jar//com.loohp.interactivechat.utils.VanishUtils.isVanished(VanishUtils.java:75)
[20:13:10 WARN]:        at InteractiveChat-4.1.4.15.jar//com.loohp.interactivechat.modules.PlayernameDisplay.lambda$getNames$3(PlayernameDisplay.java:149)
[20:13:10 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[20:13:10 WARN]:        at InteractiveChat-4.1.4.15.jar//com.loohp.interactivechat.modules.PlayernameDisplay.getNames(PlayernameDisplay.java:148)
[20:13:10 WARN]:        at InteractiveChat-4.1.4.15.jar//com.loohp.interactivechat.modules.PlayernameDisplay.process(PlayernameDisplay.java:79)
[20:13:10 WARN]:        at InteractiveChat-4.1.4.15.jar//com.loohp.interactivechat.listeners.OutChatPacket.processPacket(OutChatPacket.java:268)
[20:13:10 WARN]:        at InteractiveChat-4.1.4.15.jar//com.loohp.interactivechat.listeners.OutChatPacket.access$100(OutChatPacket.java:77)
[20:13:10 WARN]:        at InteractiveChat-4.1.4.15.jar//com.loohp.interactivechat.listeners.OutChatPacket$1.lambda$onPacketSending$0(OutChatPacket.java:140)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Step one here would be to upgrade to the latest .7 release and see if it still happens.

I see the error msg also mentions vanish. You could try turning vanish module off in modules.yml as well.

**Comment by 2cGukEH** [comment]
> Step one here would be to upgrade to the latest .7 release and see if it still happens.
> 
> I see the error msg also mentions vanish. You could try turning vanish module off in modules.yml as well.

The CMI is now up to date and there are no issues so far.  If the problem occurs again, I will report it.
Thank you
