### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by mani1232** [Zrips/CMI#6925]
### Description of Issue

On edit kits in menu

### Version Information

```shell
[18:03:50 INFO]: --------------------------------------------------
[18:03:50 INFO]: Версия плагина CMI: 9.1.4.7 BungeeCord CMIB  SqLite
[18:03:50 INFO]: CMILib: 1.1.2.5 
[18:03:50 INFO]: Версия сервера: Purpur 1.18.2-R0.1-SNAPSHOT
[18:03:50 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMICMI Чат: Включено 
[18:03:50 INFO]: Модули -> 52 включено 4 отключено: deathMessages, tablist, votifier, holograms
[18:03:50 INFO]: --------------------------------------------------
```

### Errors

```shell
[17:59:34 ERROR]: Could not pass event InventoryClickEvent to CMILib v1.1.2.5
java.lang.NoSuchMethodError: 'void com.Zrips.CMI.Modules.Kits.KitsManager$46.<init>(com.Zrips.CMI.Modules.Kits.KitsManager, java.lang.Integer, org.bukkit.inventory.ItemStack, boolean, org.bukkit.entity.Player, com.Zrips.CMI.Modules.Kits.Kit)'
        at com.Zrips.CMI.Modules.Kits.KitsManager.openGuiEditorSettings(KitsManager.java:2653) ~[[DL]-CMI9.1.4.7.jar:?]
        at com.Zrips.CMI.Modules.Kits.KitsManager$22.click(KitsManager.java:2041) ~[[DL]-CMI9.1.4.7.jar:?]
        at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:263) ~[CMILib1.1.2.5.jar:?]
        at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:220) ~[CMILib1.1.2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1269.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1626]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2946) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Sorry for going off topic, but why is your cmi filename called `[[DL]-CMI9.1.4.7.jar`, that's not the default. Is that from some release group pirating cmi perhaps?

If you haven't pirated CMI, then my apologies for wondering. Remove the custom filename and re-download your licensed copy from spigotmc.org again and try it with that one. See if it still happens. 

I've tried a fresh install and made some kits, editing the kits with a command, and via the menu, it seems to be fine. I can't reproduce this.

**Comment by Zrips** [comment]
Redownload plugin file and it should fix this issue.
