### ISSUE TITLE
[issues] interactive commands - add block or entity

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#694]
i added a sign - (interactiv commands) that was hanging so an Entity (no block)

the intesting thing here..u just get the feedback you look at an entity..what entity?..no idea CMI does not tell me (even if i know i was targeting the sign) :3
![image](https://user-images.githubusercontent.com/12080017/43570030-9b14b59a-9639-11e8-8f0d-98569ed1afb6.png)
the other interest thing is the error u get if u click the wrong "button" of the two
nearly same happens if it is a block and you would click the addentity button in the GUI.
```
[09:43:51 INFO]: Cloude_Lecaw issued server command: /cmi ic addentity Test2
[09:43:54 INFO]: Cloude_Lecaw issued server command: /cmi ic addblock Test2
[09:43:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at net.minecraft.server.v1_13_R1.PlayerConnection.chat(PlayerConnection.java:1550) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at org.bukkit.craftbukkit.v1_13_R1.entity.CraftPlayer.chat(CraftPlayer.java:320) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at gyurix.chatcontrol.modules.LongerChat$1.run(LongerChat.java:53) [ChatControl_1.9Pre6.jar:?]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:877) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
        at com.Zrips.CMI.commands.list.ic.perform(ic.java:137) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-69774b3-8e87d03]
        ... 13 more
```
 ingame you just get this info:
![image](https://user-images.githubusercontent.com/12080017/43569939-5d373838-9639-11e8-9c47-ef369349f0c7.png)

**Comment by 4WithSun** [comment]
Same problem here!, hope it gets fixed, i really want to do an hologram shop.

**Comment by GrimPod** [comment]
Sign is a block, thou i have had trouble setting them recently too thou

**Comment by CloudeLecaw** [comment]
Sign is a block? not really.. like armorstand, itemframe or the picture ist an Entity.. all fine here ;)
