### ISSUE TITLE
from console: cmi chat create roomname causes exception error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#6961]
### Description of Issue

If you type in the console `cmi chat create testroom` it will spit out an exception error.
Happens on 1.18.2 server, and someone else on discord mentioned it too, i thought it was time to report it

### Version Information

```shell
> ver
[21:55:23 INFO]: Checking version, please wait...
[21:55:23 INFO]: This server is running Paper version git-Paper-379 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 276d830)
You are running the latest version
Previous version: git-Paper-378 (MC: 1.18.2)
> cmi version
[21:55:25 INFO]: --------------------------------------------------
[21:55:25 INFO]: CMI: 9.1.5.0 SqLite-> 9.2.0.0
[21:55:25 INFO]: CMILib: 1.1.2.6 -> 1.2.0.1
[21:55:25 INFO]: Server: Paper(379) 1.18.2-R0.1-SNAPSHOT
[21:55:25 INFO]: CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
[21:55:25 INFO]: Modules -> 55 enabled 1 disabled: flightCharge
[21:55:25 INFO]: --------------------------------------------------
>
```
```


### Errors

```shell
> cmi chat create testroom
[21:54:01 WARN]: Unexpected exception while parsing console command "cmi chat create testroom"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.1.5.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:510) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1456) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.CMIUser.getChatRoom()" because "<local11>" is null
        at com.Zrips.CMI.commands.list.chat.perform(chat.java:247) ~[CMI9.1.5.0.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:399) ~[CMI9.1.5.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 9 more
>
```
```


### Relevant Config Sections

_No response_

### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next build
