### ISSUE TITLE
Error CMILib

### ISSUE THREAD

**Issue by samparotony228** [Zrips/CMI#6963]
### Description of Issue

After updating the jar file to a new version of CMI and CMILib, I have the following error in the console.

### Version Information

```shell
CMI: 9.2.0.0
СMILib: 1.2.0.1
Server: Paper(1618) 1.12.2-R0.1-SNAPSHOT
Vault: 1.7.3-b
```

### Errors

```shell
[14:34:13] [Server thread/INFO]: [CMILib] Enabling CMILib v1.2.0.1
[14:34:14] [Server thread/INFO]: Server version: v1_12_R1 - 1.12.2 - paper
[14:34:14] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.NBTTagList.add(int, net.minecraft.server.v1_12_R1.NBTBase)
[14:34:14] [Server thread/WARN]: 	at java.lang.Class.getMethod(Unknown Source)
[14:34:14] [Server thread/WARN]: 	at net.Zrips.CMILib.NBT.CMINBT.<clinit>(CMINBT.java:237)
[14:34:14] [Server thread/WARN]: 	at net.Zrips.CMILib.Reflections.asNMSCopy(Reflections.java:1014)
[14:34:14] [Server thread/WARN]: 	at net.Zrips.CMILib.Reflections.getItemMinecraftName(Reflections.java:837)
[14:34:14] [Server thread/WARN]: 	at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:89)
[14:34:14] [Server thread/WARN]: 	at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:194)
[14:34:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:34:14] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[14:34:14] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:34:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[14:34:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[14:34:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[14:34:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[14:34:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[14:34:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[14:34:14] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[14:34:14] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[14:34:15] [Server thread/INFO]: CMI hooked.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Resolved
