### ISSUE TITLE
Error when trying to get data of some players that are offline. in 1.19

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6969]
### Description of Issue

Error apears when we look in other players inventory 

### Version Information

![image](https://user-images.githubusercontent.com/12080017/173414370-14c1b3da-4723-454b-8f92-4d3847b47828.png)

### Errors
```
[18:12:08 INFO]: Blueeyestar issued server command: /inv Nitro2
>....
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-382]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-382]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-382]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because "this.entity.s" is null
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.getWorld(CraftEntity.java:518) ~[paper-1.19.jar:git-Paper-382]
	at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.getLocation(CraftEntity.java:427) ~[paper-1.19.jar:git-Paper-382]
	at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:318) ~[CMI_9.2.0.0.jar:?]
	at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:207) ~[CMI_9.2.0.0.jar:?]
	at com.Zrips.CMI.Locale.Language.getMessage(Language.java:141) ~[CMI_9.2.0.0.jar:?]
	at com.Zrips.CMI.Locale.CMILC.getMsg(CMILC.java:258) ~[CMI_9.2.0.0.jar:?]
	at com.Zrips.CMI.Locale.CMILC.getLocale(CMILC.java:226) ~[CMI_9.2.0.0.jar:?]
		at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[paper-1.19.jar:git-Paper-382]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-382]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-382]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-382]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-382]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-382]
	at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.CreateGui(RegChestManager.java:470) ~[CMI_9.2.0.0.jar:?]
	at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.openInventory(RegChestManager.java:137) ~[CMI_9.2.0.0.jar:?]
	at com.Zrips.CMI.commands.list.inv.perform(inv.java:54) ~[CMI_9.2.0.0.jar:?]
	[18:12:08 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.2.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:399) ~[CMI_9.2.0.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 17 more
```

### Relevant Config Sections

none i aspect...

### Relevant Plugins

CMI, CMILib?....

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
After tries some command with that playername
We got it back to work...
May it was because that user wasnt online for over 140 days.. well i have no clue why it happend

**Comment by CloudeLecaw** [comment]
ggain with an other user that was just 6 days not there... so i reopen it

```
[21:23:25 INFO]: Cloude_Lecaw issued server command: /cmi inv SirBambuuus
>....
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-10]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
>....[21:23:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.2.0.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2376) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2147) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-10]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
```

**Comment by Zrips** [comment]
Its failing to recognize players current world, as new server got new worlds with new UUID which is used to determine where player is located at, as this one is missing it creates this error. In general error originates at Minecraft code level due to you copy/pasting old player data files which contains somewhat broken data at this point. Tp command should not really help you out here and it should not fix this issue.
Can't really offer any real fix here at the moment.
