### ISSUE TITLE
Holograms spam the server - Reason unknown

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#6970]
### Description of Issue

We made a shop with Holograms with hovering items
After updating to 1.19 our console got often spammed with code because of the holograms 

### Version Information

![image](https://user-images.githubusercontent.com/12080017/173442216-c63e6166-128c-4550-b61a-7c75618c389e.png)

### Errors

```shell
Craft Scheduler Thread - 430 - CMI: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:87)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:77)
	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:83)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:79)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.nextDouble(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	at net.minecraft.world.entity.item.ItemEntity.<init>(ItemEntity.java:67)
[22:37:44] [Craft Scheduler Thread - 430 - CMI/WARN]: 	... 8 more
[22:37:44] [Craft Scheduler Thread - 471 - CMI/ERROR]: Thread dumps: 
Craft Scheduler Thread - 471 - CMI: 
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:87)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:77)
	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: net.minecraft.ReportedException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.a(ThreadingDetector.java:83)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.c(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.j(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.entity.item.EntityItem.<init>(EntityItem.java:67)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.NBT.v1_19_R1.makeFloatingIcon(v1_19_R1.java:927)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at CMI_9.2.0.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1400)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: Caused by: java.lang.IllegalStateException: Accessing LegacyRandomSource from multiple threads
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.util.ThreadingDetector.makeThreadingException(ThreadingDetector.java:79)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.LegacyRandomSource.next(LegacyRandomSource.java:45)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.level.levelgen.BitRandomSource.nextDouble(BitRandomSource.java:54)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	at net.minecraft.world.entity.item.ItemEntity.<init>(ItemEntity.java:67)
[22:37:44] [Craft Scheduler Thread - 471 - CMI/WARN]: 	... 8 more
```

### Relevant Config Sections - Hologramms.yml:

```
CloudesTest:
  Loc: world;1734.42;67.55;1633.61
  LOSInterval: 0.1
  HoverParticles:
    Count: 1
  Range: 5
  RangeExtra: 5
  RequiresPermission: true
  Lines:
  - '&6Willkommen &f%cmi_user_name%'
  - '&6in der Köhlerei'
  - '&6von Cloude_Lecaw.'
ShopVotiverkauf:
  Loc: world;-39.5;65.5;325.5
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Votiverkauf [playerName]
  Lines:
  - ICON:GOLD_NUGGET-64
ShopRedstoneErz:
  Loc: world;-41.5;65.5;325.5
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Redstoneerz [playerName]
  Lines:
  - ICON:REDSTONE_ORE-64
ShopAntikerSchrott2:
  Loc: world;-37.5;65.5;325.25
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Antiker-Schrott [playerName]
  Lines:
  - ICON:NETHER_QUARTZ_ORE-64
ShopDiaErz:
  Loc: world;-33.5;65.5;318.5
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Diaerz [playerName]
  Lines:
  - ICON:DIAMOND_ORE-64
ShopSmaragd:
  Loc: world;-33.5;65.5;325.25
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Smaragderz [playerName]
  Lines:
  - ICON:EMERALD_ORE-64
ShopEisenerz:
  Loc: world;-37.5;65.5;318.5
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Eisenerz [playerName]
  Lines:
  - ICON:IRON_ORE-64
ShopKupfererz:
  Loc: world;-35.5;65.5;325.25
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Kupfererz [playerName]
  Lines:
  - ICON:COPPER_ORE-64
ShopLapizerz:
  Loc: world;-39.5;65.5;318.5
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Lapizerz [playerName]
  Lines:
  - ICON:LAPIS_ORE-64
TestHolo:
  Loc: world;1725.03;70.25;1633.24
  Interval: 0.5
  LOSInterval: 10.0
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  NewMethod: false
  Commands:
  - '!leftclick! item:stone-1?! msg! [playerName] LEFT'
  - '!rightclick! item:stone-2?! msg! [playerName] RIGHT'
  - '!shiftleftclick! item:stone-3?! msg! [playerName] SHIFT LEFT'
  - '!shiftrightclick! item:stone-4?! msg! [playerName] SHIFT RIGHT'
  Lines:
  - ICON:STONE-3
ShooterLulugames:
  Loc: LuluGames;-1128.48;161.62;-1549.52
  LOSInterval: 0.1
  HoverParticles:
    Count: 1
  Range: 16
  RangeExtra: 32
  Lines:
  - ICON:head:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjNiNzEwYjA4YjUyM2JiYTdlZmJhMDdjNjI5YmEwODk1YWQ2MTEyNmQyNmM4NmJlYjM4NDU2MDNhOTc0MjZjIn19fQ==
ShopGoldErz:
  Loc: world;-35.5;65.5;318.5
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Golderz [playerName]
  Lines:
  - ICON:GOLD_ORE-64
ShopAntikerSchrott:
  Loc: world;-37.5;65.5;325.25
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Antiker-Schrott [playerName]
  Lines:
  - ICON:ANCIENT_DEBRIS-64
ShopKohleErze:
  Loc: world;-41.5;65.5;318.5
  ShowParticles: false
  HoverParticles:
    ShowHover: false
    Count: 1
  Range: 16
  RangeExtra: 32
  Interactable: true
  Commands:
  - asConsole! shopkeeper remote Kohleerz [playerName]
  Lines:
  - ICON:COAL_ORE-64
```

### Relevant Plugins

Vault_1.7.3-Build131, CMI_9.2.0.0, CMIEInjector_1.0.2.3, CMILib_1.2.0.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
Edit; The Issue seems to come from the Floating Icons.

**Comment by CloudeLecaw** [comment]
Paper allready left the experimental status for 1.19,,,

but ok i will ask tem there an hope they can fix it from there site.

**Comment by MiniDigger** [comment]
Maybe I can chime in here as a paper dev:
CMI seems to be creating a new item entity outside of the main thread, which is unsafe and in this case even fails with an exception because there was a concurrent access to the random source. The fix here is to create the entity on the main thread.

**Comment by Zrips** [comment]
Will work on it and will make fix from my end. As this is issue from my end, its up to me to fix it.

**Comment by lynxplay** [comment]
Looking at it, at least I believe this might only be caused by the usage of the worlds random in the constructor of the ItemEntity which you are calling. The world random does not appear thread safe.

One possible solution here would be to switch the constructor you are calling, specifically
`new ItemEntity(Level arg0, double arg1, double arg2, double arg3, ItemStack arg4, double arg5, double arg6, double arg7)` (under mojang mappings).

The constructor uses the entities random instance, which in the case of paper, is a shared child of the java.util.Random class, which in term is thread safe.

Obviously I cannot really test this thesis, the plugin is closed source, but it might point you in a faster direction than having to completely jump to the main thread for entity creation.

**Comment by Zrips** [comment]
@lynxplay 
Thanks for a suggestion, will do some testing. In general this is only an issue with paper builds and only on 1.19 version, so something changed on that specific front, duno if this is actually a bug or intentional change on paper side, either way will play around with it.
