### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by LogGits** [Zrips/CMI#70]
Users were using /warp and it was causing this error:
Only happens with commands such as /warp and /tpa that are also in essentials when essentials is also installed.
```
04/03/2018 06:52:32
06:52:32 at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:498) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:110) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.Modules.Afk.AfkManager.setUserToAfk(AfkManager.java:186) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.Containers.CMIUser.tunOnAfk(CMIUser.java:1001) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.Containers.CMIUser.setAfk(CMIUser.java:987) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.commands.list.afk.perform(afk.java:31) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:209) ~[CMI7.3.17.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1329]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1329]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) ~[patched_1.12.2.jar:git-Paper-1329]
at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerCommandPreprocess(WorldEditListener.java:95) ~[worldedit-bukkit-6.1.9-SNAPSHOT-dist%20(1).jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1329]
... 25 more
ERROR 04/03/2018 06:52:32
06:52:32Could not pass event PlayerCommandPreprocessEvent to CMI v7.3.17.0
Console 04/03/2018 06:52:32
06:52:32java.lang.NoSuchFieldError: timings
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:540) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:444) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:70) ~[CMI7.3.17.0.jar:?]
at com.Zrips.CMI.AllListeners.onPreprocessCommand.onCommand(onPreprocessCommand.java:56) ~[CMI7.3.17.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor792.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1329]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1329]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1329]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1329]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1464) ~[patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1329]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1329]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1329]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by kikelkik** [comment]
This also happens when essentials is not installed, for instance with /gm 1 :
`[12:44:55] [Server thread/INFO]: kikelkik issued server command: /gm 1
[12:44:55] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v7.3.17.0
java.lang.NoSuchFieldError: timings
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:540) ~[CMI.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:444) ~[CMI.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:70) ~[CMI.jar:?]
	at com.Zrips.CMI.AllListeners.onPreprocessCommand.onCommand(onPreprocessCommand.java:56) ~[CMI.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor662.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1329]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1464) ~[patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1329]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1329]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

or when the plugin tries to set the player auto-AFK (error occurs every second): 
`[12:44:18] [Server thread/WARN]: [CMI] Task #110 for CMI v7.3.17.0 generated an exception
java.lang.NoSuchFieldError: timings
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:540) ~[CMI.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:498) ~[CMI.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:110) ~[CMI.jar:?]
	at com.Zrips.CMI.Modules.Afk.AfkManager.setUserToAfk(AfkManager.java:186) ~[CMI.jar:?]
	at com.Zrips.CMI.Containers.CMIUser.tunOnAfk(CMIUser.java:1001) ~[CMI.jar:?]
	at com.Zrips.CMI.Containers.CMIUser.setAfk(CMIUser.java:987) ~[CMI.jar:?]
	at com.Zrips.CMI.Modules.Afk.AfkManager$1.run(AfkManager.java:148) ~[CMI.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1329]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]`

I think it has got to do wether the alias of a command is used. If you type in /cmi warp or /cmi gm 1 it works without any problem. 
In previous versions there weren't any troubles with aliases.

**Comment by LogGits** [comment]
@Zrips said this is fixed in the next update.
