### ISSUE TITLE
Spamming error on latest CMI version (8.0.4.0)

### ISSUE THREAD

**Issue by Gasha666** [Zrips/CMI#700]
I'm currently getting spamming error from CMI
Using latest CMI version (8.0.4.0)
Also i'm getting error from using latest version of your Jobs Reborn plugin 
That error from jobs is caused by your 1.13 update (materials are causing errors)
Thats why i needed to use some previous versions (previous versions are working fine)
My Server is PaperSpigot 1.12.2 (latest)

https://hastebin.com/wequtiraco.cs

@LogGits told me to open new thread for new reports in future
My previous thread with bugs & suggestions that i opend 16 days ago --> https://github.com/Zrips/CMI/issues/621

**Comment by C4BR3R4** [comment]
Iden.

```
[Server thread/ERROR]: Could not pass event ServerCommandEvent to CMI v8.0.4.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.executeCommand(CommandBlockListenerAbstract.java:186) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.executeSafely(CommandBlockListenerAbstract.java:166) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:121) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.BlockCommand.a(BlockCommand.java:95) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.BlockCommand.b(BlockCommand.java:81) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:773) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:312) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_171]
	at com.Zrips.CMI.Modules.Alias.AliasManager.getAliasForCommand(AliasManager.java:123) ~[?:?]
	at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:31) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-2cf50f0-2b93d83]
	... 15 more
```
-----------------------
_**Version CMI: 8.0.4.0**
Version  Server: Spigot 1.12.2-R0.1-SNAPSHOT #1573c | CraftBukkit version git-Spigot-2086bb0-1988d7f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Version Vault: 1.6.6-b67_

**Comment by C4BR3R4** [comment]
The same goes for version 8.0.4.3

**Comment by C4BR3R4** [comment]
The error persists in the version 8.0.8.0
