### ISSUE TITLE
Interact event error

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#702]
Server version: 1.12.2
CMI version: latest (8.0.4.0)

`java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
    at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70)
    at com.Zrips.CMI.AllListeners.PlayerListeners.findTeleportLocation(PlayerListeners.java:1134)
    at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1097)
    at sun.reflect.GeneratedMethodAccessor295.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
    at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
    at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951)
    at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
    at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
    at java.lang.Thread.run(Thread.java:748)
org.bukkit.event.EventException: Could not pass event PlayerInteractEvent to CMI v8.0.4.0
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
    at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
    at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458)
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951)
    at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
    at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
    at java.lang.Thread.run(Thread.java:748)`

**Comment by Momshroom** [comment]
Confirming that I also get this error when attempting to use elevators on Spigot 1.13 and the newest CMI (purchased as PearlPoseidon).

**Comment by Rukes** [comment]
Fixed with latest (8.0.8.1) version
