### ISSUE TITLE
cant use info/inv for offline player

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#7030]
### Description of Issue

you cant use for example info or inv for offline player

### Version Information

```shell
9.2.1.1 CMI
1.2.1.0 CMIlib
```

### Errors

```shell
first error
[15:50:46 WARN]: [CMI] Task #96419 for CMI v9.2.1.1 generated an exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because "this.entity.s" is null
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.getWorld(CraftEntity.java:512) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.Zrips.CMI.Modules.Homes.HomeManager.getReSpawnLocation(HomeManager.java:393) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.Modules.Homes.HomeManager.getReSpawnLocation(HomeManager.java:388) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.commands.list.info$1.lambda$0(info.java:226) ~[CMI9.2.1.1.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

nd error
[15:55:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.2.1.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because "this.entity.s" is null
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.getWorld(CraftEntity.java:512) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftEntity.getLocation(CraftEntity.java:421) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:318) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:207) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.Locale.Language.getMessage(Language.java:141) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.Locale.CMILC.getMsg(CMILC.java:259) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.Locale.CMILC.getLocale(CMILC.java:227) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.CreateGui(RegChestManager.java:470) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.openInventory(RegChestManager.java:137) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.commands.list.inv.perform(inv.java:54) ~[CMI9.2.1.1.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:396) ~[CMI9.2.1.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Is this an issue on a player who never joined after update to 1.18 server version or maybe you have worlds which no longer actually exist where this player could have been located at?

**Comment by dan28000** [comment]
It's fine now so idk what happened there
