### ISSUE TITLE
Advanced Alias to add additional homes does not work

### ISSUE THREAD

**Issue by Mikirae** [Zrips/CMI#7073]
### Description of Issue

This alias, straight from the wiki, has this:

ptarget:$1! lp user $1 permission set cmi.command.sethome.%cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+1%

### Version Information

```shell
[20:11:32] [Server thread/INFO] [Console/]: --------------------------------------------------
[20:11:32] [Server thread/INFO] [Console/]: CMI: 9.2.1.4 SqLite
[20:11:32] [Server thread/INFO] [Console/]: CMILib: 1.2.1.0 -> 1.2.1.2
[20:11:32] [Server thread/INFO] [Console/]: Server: 1.16.5 1.16.5-R0.1-SNAPSHOT
[20:11:32] [Server thread/INFO] [Console/]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
[20:11:32] [Server thread/INFO] [Console/]: Modules -> 44 enabled 12 disabled: spawnerProximity, schedule, disabledEnchants, ranks, moneyCheque, afk, skin, spawners, spawnerCharge, silentChest, warmup, bossBarCompass
[20:11:32] [Server thread/INFO] [Console/]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
[20:06:44] [Server thread/INFO] [Console/]: [Youngster] Mikirae: ptarget:$1! lp user $1 permission set cmi.command.sethome.%cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+1%
[20:06:49] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: Mikirae issued server command: /cmil rmc -4264387565130117087
> addhome Mikirae
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]: net.Zrips.CMILib.Equations.ParseError: Semantic Error, expected function or variable or constant or '('
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.U(Parser.java:377)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.F(Parser.java:329)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.T(Parser.java:319)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.H(Parser.java:301)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.G(Parser.java:287)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.E(Parser.java:273)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.S(Parser.java:258)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.getTree(Parser.java:109)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.Zrips.CMILib.Equations.Parser.getValue(Parser.java:437)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1695)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:881)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:726)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:617)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:507)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:53)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.minecraft.server.dedicated.DedicatedServer.redirect$ban000$arclight$serverCommandEvent(DedicatedServerMixin.java:653)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServerMixin.java:312)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:292)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1899)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
[20:06:55] [Server thread/INFO] [STDERR/]: [com.Zrips.CMI.Modules.Placeholders.Placeholder:getValue:1697]:  at java.base/java.lang.Thread.run(Thread.java:834)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Small mistake from my end. Actual command should look like `asConsole! ptarget:$1! lp user $1 permission set cmi.command.sethome.%cmi_equationint_{cmi_user_maxperm_cmi.command.sethome_1}+1%` and there was small bug relating to equation solver which should not be resolved.
