### ISSUE TITLE
CMIB error in proxy console

### ISSUE THREAD

**Issue by Ceddix** [Zrips/CMI#7078]
### Description of Issue

I get following an on my proxy server that occurs quite often. I'm not sure, when it happens.

### Version Information

```shell
CMI: `9.2.1.4`
CMILib: `1.2.1.0`
CMIB: `1.0.1.0`
```

### Errors

```shell
https://pastebin.com/RF9Wu6Ym
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by Ceddix** [comment]
This seems to  occur, when I switch the server 🤔

**Comment by mrfloris** [comment]
I see this is waterfall, a fork off of bungeechord. Could be why it goes wrong. Thank you for reporting. Hopefully it's a somewhat easy fix for zrips.

**Comment by Ceddix** [comment]
The error has only been occurring for a few days :)

**Comment by Ceddix** [comment]
No I get this stacktrace and the player is kicked directly when connecting
```
java.lang.IllegalArgumentException: Team CIT-a37e6865ceb5 already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:248) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[latest.waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:fc30291:498]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Zrips** [comment]
@Ceddix 
Will make a fix for CMIB and CMI with tomorrows update which will resolve your issue.
