### ISSUE TITLE
CMI + Magma

### ISSUE THREAD

**Issue by bvc0115** [Zrips/CMI#7086]
**CMI LIB compatible with Magma:**

---

Hello,
I was wondering if you could add support for Magma so we can use the plugin on a plugin/mod server, that would be awesome because your plugin has lots of features for our server. I am leaving this text in case you need it:

--- ERROR
[09:48:05] [Server thread/WARN] [/]: java.lang.NoClassDefFoundError: net/minecraft/nbt/NBTBase
[09:48:05] [Server thread/WARN] [/]:    at java.base/java.lang.Class.forName0(Native Method)
[09:48:05] [Server thread/WARN] [/]:    at java.base/java.lang.Class.forName(Class.java:375)
[09:48:05] [Server thread/WARN] [/]:    at com.Zrips.CMI.CMI.onEnable(CMI.java:1350)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.1.54/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.1.54/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.1.54/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.1.54/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:434)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.1.54/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:348)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:448)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:357)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:244)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:757)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:253)
[09:48:05] [Server thread/WARN] [/]:    at java.base/java.lang.Thread.run(Thread.java:833)
[09:48:05] [Server thread/WARN] [/]: Caused by: java.lang.ClassNotFoundException: net.minecraft.nbt.NBTBase
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.1.54/org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147)
[09:48:05] [Server thread/WARN] [/]:    at TRANSFORMER/forge@40.1.54/org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[09:48:05] [Server thread/WARN] [/]:    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[09:48:05] [Server thread/WARN] [/]:    ... 14 more

---

**Cmi Version (latest version):** 

**Server Type (Magma Version: 4ef8c970):** 

**Server Version (using `/ver` 1.18.2):**

**Comment by CloudeLecaw** [comment]
well i think this will not come.

the Support is only for spigot and paper

no forks are supported. the wiki and description also told you about.

**Comment by mrfloris** [comment]
Magma and Mohist - or - modded servers, will very likely get no support. It's made for spigot/paper. Anything modded runs "as is".
