### ISSUE TITLE
CMI PlayerInteractEvent Error

### ISSUE THREAD

**Issue by SrT3ddy** [Zrips/CMI#7089]
### Description of Issue

The error is spamming the console

### Version Information

```shell
CMI: 9.2.2.0
CMILib: 1.2.2.0
Mohist version 1.12.2-321 (MC: 1.12.2)
```

### Errors

```shell
[16:28:23 ERROR]: Could not pass event PlayerInteractEvent to CMI v9.2.2.0
 java.lang.NoClassDefFoundError: Could not initialize class net.Zrips.CMILib.Container.CMIBlock$1
        at net.Zrips.CMILib.Container.CMIBlock.getFacing(CMIBlock.java:211) ~[?:?]
        at com.Zrips.CMI.Modules.Animations.AnimationManager.isValidChairBlock(AnimationManager.java:500) ~[?:?]
        at com.Zrips.CMI.Modules.Animations.AnimationSitListener.PlayerTeleportEvent(AnimationSitListener.java:155) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1025.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) ~[CraftEventFactory.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:501) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1151) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This gets fixed with next CMILib update
