### ISSUE TITLE
[Bug] '/cmi toast' with wood icon doesn't work

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#710]
**Description of issue or feature request:**
When I try to make a toast using WOOD as an icon, I get returned an internal error

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
04.08 00:58:46 [Server] ERROR null
04.08 00:58:46 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.4.1
04.08 00:58:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1475) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1280) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
04.08 00:58:46 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
04.08 00:58:46 [Server] INFO Caused by: com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'minecraft:acacia_planks'
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.ChatDeserializer.b(SourceFile:124) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.ChatDeserializer.i(SourceFile:135) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.AdvancementDisplay.a(SourceFile:104) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.AdvancementDisplay.a(SourceFile:91) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.Advancement$SerializedAdvancement.a(Advancement.java:194) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.AdvancementDataWorld$1.a(AdvancementDataWorld.java:43) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.AdvancementDataWorld$1.deserialize(AdvancementDataWorld.java:47) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:492) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:517) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at net.minecraft.server.v1_12_R1.ChatDeserializer.a(SourceFile:537) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO at com.Zrips.CMI.NBT.v1_12_R1.loadAdvancement(v1_12_R1.java:1659) ~[?:?]
04.08 00:58:46 [Server] INFO at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.add(CMIAdvancement.java:137) ~[?:?]
04.08 00:58:46 [Server] INFO at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.show(CMIAdvancement.java:122) ~[?:?]
04.08 00:58:46 [Server] INFO at com.Zrips.CMI.commands.list.toast.perform(toast.java:98) ~[?:?]
04.08 00:58:46 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
04.08 00:58:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1524]
04.08 00:58:46 [Server] INFO ... 15 more
```

**Cmi Version (using`/cmi version`):** 
8.0.4.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
Paper-1520 (1.12.2)

**Comment by Zrips** [comment]
Should be fixed with latest builds.
