### ISSUE TITLE
Urgent issue: Placing and breaking heads will drop them as steve heads

### ISSUE THREAD

**Issue by OceaniaCraft** [Zrips/CMI#7102]
### Description of Issue

If a player were to place down a head of any kind then break them, the item drops as a default steve head. This is happening on a blank purpur server with nothing but CMI, head database and dependencies loaded. Also tested with paper and got the same results.

### Version Information

```shell
30/07/2022 [21:20:15]: CMI: 9.2.3.0 SqLite
[21:20:15]: CMILib: 1.2.3.1 
[21:20:15]: Server: Purpur 1.19.1-R0.1-SNAPSHOT
30/07/2022 [21:20:15]: CMI economy: Enabled Vault: 1.7.3-b(CMIEInjector) CMI Chat: Enabled 
30/07/2022 [21:20:15]: Modules -> 40 enabled 16 disabled: spawnerProximity, hpBossBar, mirror, tablist, moneyCheque, noTarget, spawners, paintingEditor, dynamicSigns, pla
yerChatTag, coloredArmor, flightCharge, disabledEnchants, spawnerCharge, vanish, namePlates
```

### Errors

```shell
No errors given at startup or on placement/break.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by OceaniaCraft** [comment]
**Some new information:** 

Disabling the CMI headdrops module does solve this issue.

**Comment by xpvtryanx** [comment]
@OceaniaCraft I have this exact issue. What fixed it for me was disabling the Mob Heads from my config file

**Comment by xpvtryanx** [comment]
[14:07:24 INFO]: --------------------------------------------------
[14:07:24 INFO]: CMI: *.*.*.* SqLite
[14:07:24 INFO]: CMILib: *.*.*.*
[14:07:24 INFO]: Server: Paper(94) 1.19.1-R0.1-SNAPSHOT
[14:07:24 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
[14:07:24 INFO]: Modules - 56 enabled 0 disabled:
[14:07:24 INFO]: --------------------------------------------------

**Comment by xpvtryanx** [comment]
![image](https://user-images.githubusercontent.com/36307438/182032378-d6909808-b6d6-4f69-8215-71f4ea12d332.png)

**Comment by emerysteele** [comment]
Same issue for me. I am getting an error tho when I break a mob head.

```
ERROR13:43:54
Could not pass event BlockBreakEvent to CMI v9.2.3.0
Console13:43:54
java.lang.IllegalStateException: Tile is null, asynchronous access? CraftBlock{pos=BlockPosition{x=340, y=-52, z=8027},type=PLAYER_WALL_HEAD,data=Block{minecraft:player_wall_head}[facing=east],fluid=net.minecraft.world.level.material.FluidTypeEmpty@2e5d7f39}
at com.google.common.base.Preconditions.checkState(Preconditions.java:590) ~[guava-31.0.1-jre.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:92) ~[paper-1.19.1.jar:git-Paper-97]
at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates$BlockEntityStateFactory.createBlockState(CraftBlockStates.java:78) ~[paper-1.19.1.jar:git-Paper-97]
at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:278) ~[paper-1.19.1.jar:git-Paper-97]
at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:236) ~[paper-1.19.1.jar:git-Paper-97]
at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlockStates.getBlockState(CraftBlockStates.java:221) ~[paper-1.19.1.jar:git-Paper-97]
at org.bukkit.craftbukkit.v1_19_R1.block.CraftBlock.getState(CraftBlock.java:329) ~[paper-1.19.1.jar:git-Paper-97]
at com.Zrips.CMI.Modules.DynamicSigns.SignListener.onPlayerMoveExtendedRnage(SignListener.java:102) ~[CMI9.2.3.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor256.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-97]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:292) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1880) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.1.jar:git-Paper-97]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.1.jar:git-Paper-97]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.1.jar:git-Paper-97]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.1.jar:git-Paper-97]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.1.jar:git-Paper-97]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.1.jar:git-Paper-97]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.19.1.jar:git-Paper-97]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-97]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by OceaniaCraft** [comment]
We are now noticing that there is still a small chance to drop steve heads when mob heads are broken, even with the module disabled. Does not happen with player heads. With module enabled, they drop as steve heads 100% of the time.

**Comment by OceaniaCraft** [comment]
bump.

**Comment by OceaniaCraft** [comment]
@Zrips

**Comment by Zrips** [comment]
Noticed small issue while getting players head. Tho this should not really be related to actual issue you experience currently. Try updating paper/purpur to latest version as there was some issues relating to tile entities as you have seen in error message you shown here. This should be gone with latest versions of minecraft. 
If issue persists with next CMILib update and having latest server version, let me know, will revisit this issue.

**Comment by emerysteele** [comment]
Confirm issue resolved after updating Paper + CMI to latest versions

```
--------------------------------------------------
CMI: 9.2.3.3 SqLite
CMILib: 1.2.3.2 -> 1.2.3.3
Server: Paper(113) 1.19.2-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Enabled
Modules -> 55 enabled 1 disabled: votifier
--------------------------------------------------
```

**Comment by OceaniaCraft** [comment]
Yep, issue resolved. Thanks!
