### ISSUE TITLE
Problem with FakeOperator - 1.19.1

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7122]
### Description of Issue

Hello, for some reason on 1.19.1 server tries to look up for CMI-Fake-Operator after server startup and throws authlib warn about it. I have tried disabling FakeOperator via **UseFakeOperator: false**, but it didnt help at all. As i dont plan on using FakeOperator at all, i would expect that this feature would be completely disabled by switiching UseFakeOperator to false.

### Version Information

```shell
[14:31:50 INFO]: CMI: 9.2.3.1 SqLite
[14:31:50 INFO]: CMILib: 1.2.3.2 
[14:31:50 INFO]: Server: Paper(99) 1.19.1-R0.1-SNAPSHOT
[14:31:50 INFO]: CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Disabled 
[14:31:50 INFO]: Modules -> 56 enabled 0 disabled: 
[14:31:50 INFO]: --------------------------------------------------
```

### Errors

```shell
[14:27:52 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@264ca7bf[id=ffffffff-ffff-ffff-ffff-fffffffffff0,name=CMI-Fake-Operator,properties={},legacy=false]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.11.49.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:203) ~[authlib-3.11.49.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.19.1.jar:git-Paper-99]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:175) ~[authlib-3.11.49.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.19.1.jar:git-Paper-99]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:229) ~[paper-1.19.1.jar:git-Paper-99]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:223) ~[paper-1.19.1.jar:git-Paper-99]
        at com.destroystokyo.paper.profile.PlayerProfile.complete(PlayerProfile.java:167) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:git-Paper-99]
        at xyz.jpenilla.wanderingtrades.util.ProfileCompleter.run(ProfileCompleter.java:36) ~[WanderingTrades-1.7.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-99]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.1.jar:git-Paper-99]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Relevant Config Sections

```yaml
Have completely default configs (only enabled Economy and disabled FakeOperator).
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by 1ntent1on** [comment]
Well, apparently its caused by this plugin https://www.spigotmc.org/resources/wandering-trades-easily-customize-wandering-traders-1-16-1-19.79068/ having it together with CMI will cause that issue.

**Comment by Zrips** [comment]
Will check this, but generally it needs to be addressed by wanderingTraders plugin as this error originates from that plugin due to fake-OP object not being real player and not having all the data usual player object has.
