### ISSUE TITLE
 Could not pass event AsyncPlayerChatEvent to CMI 

### ISSUE THREAD

**Issue by Antonekkk** [Zrips/CMI#7137]
### Description of Issue

It keeps throwing me errors in the console.

### Version Information

```shell
I have version 1.19.2 on my server and CMI v9.2.3.3
```

### Errors

```shell
[ERROR] Could not pass event AsyncPlayerChatEvent to CMI v9.2.3.3
java.util.UnknownFormatConversionException: Conversion = '&'
at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:105) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:181) ~[CMI9.2.3.3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor761.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-112]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[paper-1.19.2.jar:git-Paper-112]
at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:96) ~[paper-1.19.2.jar:git-Paper-112]
at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2404) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2585) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2230) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Check your chat format as it looks to be invalid and cause relates to "&" symbol in your setup. You might have extra one where it should not be one. If issue repeats I will need actual chat options section from your config file. Closing this ticket for now.
