### ISSUE TITLE
Maxplayers error on 1.19.2

### ISSUE THREAD

**Issue by XXY233** [Zrips/CMI#7158]
### Description of Issue

maxplayers error on 1.19.2

### Version Information

```shell
[17:58:01 INFO]: --------------------------------------------------
[17:58:01 INFO]: CMI plugin version: 9.2.3.4 BungeeCord  SqLite
[17:58:01 INFO]: CMILib: 1.2.3.3
[17:58:01 INFO]: Server: Paper(125) 1.19.2-R0.1-SNAPSHOT
[17:58:01 INFO]: CMI economy: enabled Vault: 1.7.3-CMI CMI Chat: enabled 
[17:58:01 INFO]: Modules -> 52 enabled 4 disabled: tablist, playerCombat, votifier, headDrop
[17:58:01 INFO]: --------------------------------------------------
```

### Errors

```shell
> maxplayers 30
[13:06:34 WARN]: java.lang.IllegalArgumentException: Can not set static final net.minecraft.network.chat.IChatBaseComponent field net.minecraft.server.player
s.PlayerList.f to (int)30
[13:06:34 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[13:06:34 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:191)
[13:06:34 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.setInt(UnsafeQualifiedStaticObjectFieldAccessorImpl.ja
va:114)
[13:06:34 WARN]:        at java.base/java.lang.reflect.Field.setInt(Field.java:984)
[13:06:34 WARN]:        at CMI9.2.3.4.jar//com.Zrips.CMI.Reflections.changePlayerLimit(Reflections.java:267)
[13:06:34 WARN]:        at CMI9.2.3.4.jar//com.Zrips.CMI.commands.list.maxplayers.perform(maxplayers.java:34)
[13:06:34 WARN]:        at CMI9.2.3.4.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[13:06:34 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[13:06:34 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[13:06:34 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911)
[13:06:34 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:874)
[13:06:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:473)
[13:06:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[13:06:34 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1416)
[13:06:34 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[13:06:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[13:06:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
