### ISSUE TITLE
 /cmi design new ERROR

### ISSUE THREAD

**Issue by M4rtyn4** [Zrips/CMI#717]
**Description of issue or feature request:**
/cmi design new

####################
[00:06:52 ERROR]: null
####################

#####################################
`[00:06:52 INFO]: M4rtyn4 issued server command: /cmi design new
[00:06:52 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:692) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
        at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70) ~[?:?]
        at com.Zrips.CMI.Modules.DynamicSigns.CMISign.getArea(CMISign.java:96) ~[?:?]
        at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addPlayersNearSign(SignManager.java:414) ~[?:?]
        at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addSign(SignManager.java:81) ~[?:?]
        at com.Zrips.CMI.commands.list.dsign.perform(dsign.java:260) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        ... 15 more
[00:09:34 INFO]: M4rtyn4 issued server command: /cmi getbook rules.txt [playerName]
[00:10:02 INFO]: M4rtyn4 issued server command: /cmi getbook rules [playerName]
[00:10:14 INFO]: M4rtyn4 issued server command: /cmi getbook rules
[00:10:51 ERROR]: Could not pass event BlockPlaceEvent to GriefPrevention v16.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:153) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.ItemStack.placeItem(ItemStack.java:200) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:499) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/bukkit/permission/RegionPermissionModel
        at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:36) ~[?:?]
        at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:863) ~[?:?]
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:285) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor391.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        ... 18 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.bukkit.permission.RegionPermissionModel
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at me.ryanhamshire.GriefPrevention.WorldGuardWrapper.canBuild(WorldGuardWrapper.java:36) ~[?:?]
        at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:863) ~[?:?]
        at me.ryanhamshire.GriefPrevention.BlockEventHandler.onBlockPlace(BlockEventHandler.java:285) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor391.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        ... 18 more`
#####################################

**Cmi Version (using`/cmi version`):** 
8.0.4.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
Spigot 1.13-R0.1-SNAPSHOT

**Comment by CloudeLecaw** [comment]
Isnt dsign fixed allready? Pls try latest cmi version..
