### ISSUE TITLE
Elevator signs broke in 1.13?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#719]
when i create and try t ouse them in latest CMI i got this error:

[10:55:03] [Server thread/INFO]: [Cloude_Lecaw: Teleported Cloude_Lecaw to NouLex]
```
[10:55:38] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.0.4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
	at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.findTeleportLocation(PlayerListeners.java:1134) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1097) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	... 17 more
[10:55:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.0.4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
	at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.findTeleportLocation(PlayerListeners.java:1134) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1097) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	... 17 more
[10:55:47] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to CMI v8.0.4.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:452) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
	at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.findTeleportLocation(PlayerListeners.java:1155) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerInteractEvent(PlayerListeners.java:1097) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-1503de9-cfc6796]
	... 17 more
```

**Comment by Momshroom** [comment]
It's not just 1.13.  It's also reported in 1.12 in this thread: #702

**Comment by mercurialmusic** [comment]
Also getting the same in 1.12.2 with CMI 8.0.4.3. Error was not present in 8.0.2.0.
https://pastebin.com/D33YLMZj

**Comment by LogGits** [comment]
Should be resolved in the latest updates. If you are still experiencing this please let me know 🙂

**Comment by Zrips** [comment]
This is fixed in latest versions
