### ISSUE TITLE
unable to load CMI

### ISSUE THREAD

**Issue by dan28000** [Zrips/CMI#7193]
### Description of Issue

CMI can't load after latest update

### Version Information

```shell
latest version both CMI and CMILib
```

### Errors

```shell
[17:25:59 ERROR]: Error occurred while enabling CMI v9.2.3.7 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.inventory.Recipe net.Zrips.CMILib.Recipes.CMIRecipe.createRecipe(net.Zrips.CMILib.Recipes.CMIRecipeType, org.bukkit.inventory.ItemStack, java.util.HashMap, net.Zrips.CMILib.Recipes.CMIRecipeCraftData, java.lang.String)'
        at com.Zrips.CMI.Modules.Recipes.RecipeManager.addRecipe(RecipeManager.java:95) ~[CMI9.2.3.7.jar:?]
        at com.Zrips.CMI.Modules.Recipes.RecipeManager.loadRecipes(RecipeManager.java:392) ~[CMI9.2.3.7.jar:?]
        at com.Zrips.CMI.Modules.Recipes.RecipeManager.<init>(RecipeManager.java:58) ~[CMI9.2.3.7.jar:?]
        at com.Zrips.CMI.CMI.getRecipeManager(CMI.java:603) ~[CMI9.2.3.7.jar:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1717) ~[CMI9.2.3.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1141) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1761]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
One sec, will post new CMILib version which should resolve this issue
