### ISSUE TITLE
Error dynamicSign

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#722]
[23:07:02] [Server thread/INFO]: Starnos issued server command: /cmi dsign new
[23:07:03] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.4.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
	at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70) ~[?:?]
	at com.Zrips.CMI.Modules.DynamicSigns.CMISign.getArea(CMISign.java:96) ~[?:?]
	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addPlayersNearSign(SignManager.java:414) ~[?:?]
	at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addSign(SignManager.java:81) ~[?:?]
	at com.Zrips.CMI.commands.list.dsign.perform(dsign.java:260) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-latest.jar:git-Spigot-1503de9-53d3ac0]
	... 15 more

**Comment by CloudeLecaw** [comment]
i agree this is since Spigot 1.13 but also with existing dynamtic signs

**Comment by ValerianV** [comment]
I have the same error on spigot 1.13

**Comment by CloudeLecaw** [comment]
Lets se what the 1.13.1 fix inclused that will come today. Zrips said it also caintain a lot of bugfixes :)

**Comment by Baktus79** [comment]
```
02.09 05:07:15 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.8.0
02.09 05:07:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
02.09 05:07:15 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
02.09 05:07:15 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.Dispenser
02.09 05:07:15 [Server] INFO at com.Zrips.CMI.Containers.CMIBlock.getFacing(CMIBlock.java:70) ~[?:?]
02.09 05:07:15 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.CMISign.getArea(CMISign.java:96) ~[?:?]
02.09 05:07:15 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addPlayersNearSign(SignManager.java:414) ~[?:?]
02.09 05:07:15 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addSign(SignManager.java:81) ~[?:?]
02.09 05:07:15 [Server] INFO at com.Zrips.CMI.commands.list.dsign.perform(dsign.java:260) ~[?:?]
02.09 05:07:15 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
02.09 05:07:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-fe3ab0d-162bda9]
02.09 05:07:15 [Server] INFO ... 15 more
```
I am still getting this error on **CMI 8.0.8.0**

**Comment by CloudeLecaw** [comment]
Jup dsigns are not fixed yet.
