### ISSUE TITLE
/cmi setworth internal error on custom item

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#7252]
### Description of Issue

```
[22:14:15 INFO]: mrfloris issued server command: /cmi itemname {#gold} test
[22:14:20 INFO]: mrfloris issued server command: /cmi itemlore {#gold} test
[22:14:24 INFO]: mrfloris issued server command: /cmi enchant unbreaking 3
[22:14:33 INFO]: mrfloris issued server command: /cmi itemcmdata set 4411991
[22:14:37 INFO]: mrfloris issued server command: /cmi setworth
[22:14:37 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.2.4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-172]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2293) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2247) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1465) ~[paper-1.19.2.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Worth.WorthItem.getModelData()" because "<local3>" is null
        at com.Zrips.CMI.Modules.Worth.WorthManager.openWorthGui(WorthManager.java:428) ~[CMI9.2.4.3.jar:?]
        at com.Zrips.CMI.commands.list.setworth.perform(setworth.java:82) ~[CMI9.2.4.3.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[CMI9.2.4.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
>
```
<img width="1043" alt="Screen-Shot 2022-09-24 at 22 16 19" src="https://user-images.githubusercontent.com/28841349/192116856-76622936-4291-4297-851d-20ed9968e423.png">

### Version Information

```shell
see above screenshot
```

### Relevant Config Sections

```yaml
Worth:
  # Defines lore that will prevent an item from being sold using /cmi sell.
  # Color codes and capitalization are being ignored
  BadLore:
  - right click to open /menu
  # If enabled any item with custom name will not be allowed to be sold with /cmi sell command
  CustomNameBlocking: true
  # If enabled any item with custom lore will not be allowed to be sold with /cmi sell command
  LoreBlocking: true
  # When enabled we will not allow to sell items which are not fully repaired
  RequireFullDurability: false
  # When enabled items which doesnt have full durability will be worth less. 30% left durability will result in items worth going down by 70%
  # This only works while RequireFullDurability is disabled
  DevalueByDurability: true
  AutoGenerate:
    # Value in percentages in how much more we should add to end product while auto calculating items price based on its ingredient worth
    # For example one stick is worth 0.1 and diamond 44 then end result as diamond_hoe will be worth 88.2 and with extra 2% this will be changed to 89.96
    # Value can be negative
    PriceIncrease: 2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Someone on discord wanted to learn about selling custom items via /setworth and /sell .. i can't test it because I get an exception error, woops.

**Comment by Zrips** [comment]
Will be fixed with next update
