### ISSUE TITLE
"Cannot invoke "com.Zrips.CMI.CMI.getHologramManager()"

### ISSUE THREAD

**Issue by Darkseno** [Zrips/CMI#7265]
### Description of Issue

Hello,

My ComplexeTurret plugin does not work anymore since the installation of CMI on my server.
https://www.spigotmc.org/resources/complexturrets-defend-yourself-using-turrets-1-8-1-19.92756/

### Version Information

```shell
[18:27:06 INFO]: --------------------------------------------------
[18:27:06 INFO]: CMI: 9.2.4.3 SqLite
[18:27:06 INFO]: CMILib: 1.2.3.6 
[18:27:06 INFO]: Server: Purpur 1.19.2-R0.1-SNAPSHOT
[18:27:06 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[18:27:06 INFO]: Modules -> 25 enabled 32 disabled: spawnerProximity, tablist, moneyCheque, skin, noTarget, elytraBoost, eventCommands, elytraLaunch, bossBarCompass, playerCombat, votifier, shulkerBackpack, headDrop, attachedCommands, spawnerCharge, interactiveCommands, hpBossBar, launchPad, portals, holograms, anvilRenameColor, spawners, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, kits, flightCharge, deathMessages, schedule, ranks, silentChest
[18:27:06 INFO]: --------------------------------------------------
```

### Errors

```shell
[18:23:58 INFO]: [ComplexTurrets] Enabling ComplexTurrets v3.6.2
[18:23:58 ERROR]: Error occurred while enabling ComplexTurrets v3.6.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.CMI.getHologramManager()" because the return value of "com.Zrips.CMI.CMI.getInstance()" is null
        at ct.ajneb97.managers.holograms.CMIManager.createInformationHologram(CMIManager.java:31) ~[ComplexTurrets.jar:?]
        at ct.ajneb97.managers.holograms.HologramsManager.createInformationHologram(HologramsManager.java:123) ~[ComplexTurrets.jar:?]
        at ct.ajneb97.managers.holograms.HologramsManager.reloadHolograms(HologramsManager.java:222) ~[ComplexTurrets.jar:?]
        at ct.ajneb97.ComplexTurrets.onEnable(ComplexTurrets.java:92) ~[ComplexTurrets.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596) ~[purpur-1.19.2.jar:git-Purpur-1799]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510) ~[purpur-1.19.2.jar:git-Purpur-1799]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1799]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1799]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1799]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1799]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1799]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
From error message my best guess would be that ComplexeTurret isint loading after CMI but before it and tries to use its API while its not being initialized yet. Isint really an issue with CMI in this case.  Could be (guessing) fixed by modifying ComplexTurret file by opening it and adding or modifying appropriate line to be something like 
`softdepend: [CMI]`
inside plugin.yml file
