### ISSUE TITLE
Illegal Entity Teleport - while riding an Entity

### ISSUE THREAD

**Issue by MelonCraftDE** [Zrips/CMI#7329]
### Description of Issue

Teleporting with Entities worked before but in latest releases it throws an error

Before we were able to teleport with an mob while riding it

### Version Information

```shell
[17:05:38 INFO]: --------------------------------------------------
[17:05:38 INFO]: CMI Plugin Version: 9.2.4.8 SqLite
[17:05:38 INFO]: CMILib: 1.2.3.7
[17:05:38 INFO]: Server: Paper(235) 1.19.2-R0.1-SNAPSHOT
[17:05:38 INFO]: CMI economy: Aktiviert Vault: 1.7.3-CMI CMI Chat: Aktiviert
[17:05:38 INFO]: Modules -> 57 enabled 0 disabled:
[17:05:38 INFO]: ---------------------------------------------
```

### Errors

```shell
[16:59:34 WARN]: Illegal Entity Teleport EntityChicken['Chicken'/1011389, uuid='7b0f3b01-9fb1-47cc-a2f1-76f87bc756c3', l='ServerLevel[Farm]', x=228.50, y=89.20, z=1376.03, cpos=[14, 86], tl=11704, v=false] to ServerLevel[Towny]:net.minecraft.core.Position@7c05350e
java.lang.Throwable: null
        at net.minecraft.world.entity.Entity.teleportTo(Entity.java:3335) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:577) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:546) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:651) ~[paper-1.19.2.jar:git-Paper-235]
        at com.Zrips.CMI.AllListeners.PlayerListeners$4.run(PlayerListeners.java:1036) ~[CMI-9.2.4.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-235]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next version, if issue persists let me know. Any additional information will help too, mainly about source and target worlds, their types and which plugin controls those.

**Comment by MelonCraftDE** [comment]
Error is still there

[17:21:21 WARN]: Illegal Entity Teleport EntityPig['Pig'/10321, uuid='2fd6d732-c7e3-43ab-8c30-0e1145064eb8', l='ServerLevel[Farm]', x=-2125.50, y=67.50, z=-24.50, cpos=[-133, -2], tl=157, v=false] to ServerLevel[Towny]:net.minecraft.core.Position@5582a8d9
java.lang.Throwable: null
        at net.minecraft.world.entity.Entity.teleportTo(Entity.java:3335) ~[paper-1.19.2.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:577) ~[paper-1.19.2.jar:git-Paper-237]
        at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:546) ~[paper-1.19.2.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:651) ~[paper-1.19.2.jar:git-Paper-237]
        at com.Zrips.CMI.AllListeners.PlayerListeners$4.run(PlayerListeners.java:1040) ~[CMI-9.2.5.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-237]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-237]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-237]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]


multiverse-core latest release
but doing a cmi warp while riding the pig
we have a world for building and one for farming. these 2 are "normal" worlds
the target world is not unloaded.

let me know if you need further information
i also reported it to paper, but they say they cant help because CMI is closed source,
