### ISSUE TITLE
Receiving warning about holograms

### ISSUE THREAD

**Issue by Threshian** [Zrips/CMI#7348]
### Description of Issue

Hi, I don't remember since wich version of cmi this warn appeared but even after recreating the hologram, I keep having this warn in the console. These warns are random and it happen only for my top time hologram.

### Version Information

```shell
CMI: 9.2.5.1
CMILib: 1.2.3.7
Server: Paper(256) 1.19.2-R01-Snapshot
```

### Errors

```shell
[15:41:25 WARN]: java.util.ConcurrentModificationException
[15:41:25 WARN]:        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
[15:41:25 WARN]:        at java.base/java.util.TreeMap$ValueIterator.next(TreeMap.java:1531)
[15:41:25 WARN]:        at CMI-9.2.5.1.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1854)
[15:41:25 WARN]:        at CMI-9.2.5.1.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:915)
[15:41:25 WARN]:        at CMI-9.2.5.1.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:758)
[15:41:25 WARN]:        at CMI-9.2.5.1.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:660)
[15:41:25 WARN]:        at CMI-9.2.5.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.checkText(CMIHologramLine.java:239)
[15:41:25 WARN]:        at CMI-9.2.5.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:215)
[15:41:25 WARN]:        at CMI-9.2.5.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1688)
[15:41:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:41:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:41:25 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:41:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:41:25 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:41:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Threshian** [comment]
I also have this error showing in the console : [19:57:50 INFO]: [CMI] Inccorrect placeholder format for %cmi_playtimetop_time_3%
The config: 
![notepad++_QdOdv97EZ4](https://user-images.githubusercontent.com/67510777/199579215-1b3d7454-f804-40c6-a549-5801c01aec2f.png)

**Comment by CloudeLecaw** [comment]
why the hologramm has this empty line? at least changed it  to something like '&f '

**Comment by Zrips** [comment]
@Threshian 
Should be fixed with next version. If issue persists check console as more information should be printed out in case it fails, which should help out to identify cause of this issue.

**Comment by Threshian** [comment]
Hi, the error still appear

![brave_H9vfD15hnb](https://user-images.githubusercontent.com/67510777/199813877-fc045901-ff46-496b-9c34-30d86913150a.png)

**Comment by CloudeLecaw** [comment]
> Hi, the error still appear
> 
> ![brave_H9vfD15hnb](https://user-images.githubusercontent.com/67510777/199813877-fc045901-ff46-496b-9c34-30d86913150a.png)

we also have a toplist on a wall with balance top 10 and it is all fine with it. we see all top 10 so it looks more like an internal issues why your placeholder does get this error. have you checked your /cni baltop itself?

**Comment by Threshian** [comment]
It's about top time not baltop and the holograms is set exactly the same way as my other holograms, there's only this one who make errors

**Comment by CloudeLecaw** [comment]
i know. send us a list of /cmi playtimetop

**Comment by CloudeLecaw** [comment]
well ok the placeholder seems to be broken maybe...
try `cmi placeholder parse %cmi_playtimetop_time_10%`
it will tell you..
```
[21:17:35] [Server thread/INFO]: --------------------------------------------------
[21:17:35] [Server thread/INFO]: Es wurde kein Spieler mit diesem Namen gefunden! (placeholders -> null)
[21:17:35] [Server thread/INFO]: %%cmi_playtimetop_time_10%% by CMI result |26d:23h 17m 35s|
```

**Comment by Threshian** [comment]
![Screenshot_2022-11-03-21-27-07-20_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/67510777/199827160-4b65c2a9-9253-4003-a1fd-c4f2a4c4c64c.jpg)

It return me this, so from what you say, the problem is on our side .. but how and what?

**Comment by Threshian** [comment]
![brave_jnVb3vcCgX](https://user-images.githubusercontent.com/67510777/200051926-a0623486-1d2b-490d-958f-0d3a67affc39.png)

I just got this error and I've deleted my top time holograms so it's not related to that holo
