### ISSUE TITLE
Re: Receiving warning about holograms

### ISSUE THREAD

**Issue by Threshian** [Zrips/CMI#7353]
### Description of Issue

Hi, the issue is still the same as https://github.com/Zrips/CMI/issues/7348

PS: I saw that you have fixed something in holograms for the baltop but my problem is for the Top Time ^^

### Version Information

```shell
CMI: 9.2.5.1
CMILib: 1.2.3.7
Server: Paper(256) 1.19.2-R01-Snapshot
```

### Errors

```shell
[20:13:14 INFO]: [CMI] Inccorrect placeholder format for %cmi_playtimetop_time_10%
[20:13:14 WARN]: java.util.ConcurrentModificationException
[20:13:14 WARN]:        at java.base/java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486)
[20:13:14 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1522)
[20:13:14 WARN]:        at java.base/java.util.TreeMap$EntryIterator.next(TreeMap.java:1517)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.buildFromSorted(TreeMap.java:2879)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.buildFromSorted(TreeMap.java:2903)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.buildFromSorted(TreeMap.java:2871)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.buildFromSorted(TreeMap.java:2903)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.buildFromSorted(TreeMap.java:2871)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.buildFromSorted(TreeMap.java:2871)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.buildFromSorted(TreeMap.java:2828)
[20:13:14 WARN]:        at java.base/java.util.TreeMap.<init>(TreeMap.java:202)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Statistics.StatsManager.getTimeByPlace(StatsManager.java:397)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1907)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:915)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.translateOwnPlaceHolder(Placeholder.java:758)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:660)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.checkText(CMIHologramLine.java:239)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramLine.getText(CMIHologramLine.java:215)
[20:13:14 WARN]:        at CMI-9.2.5.2.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram$1.run(CMIHologram.java:1688)
[20:13:14 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:13:14 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:13:14 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:13:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:13:14 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:13:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Threshian** [comment]
![brave_UYaIZnQBtc](https://user-images.githubusercontent.com/67510777/200055901-9d6ca922-8951-40e7-9503-004f48f3b8b8.png)

I've deleted my top time holo but the errors are still here and now I even got errors from the baltop holo : [19:50:06 INFO]: [CMI] Inccorrect placeholder format for %cmi_baltop_money_6%

**Comment by Threshian** [comment]
![brave_mtxSdHIl6B](https://user-images.githubusercontent.com/67510777/200180933-5f6a895e-2412-47a1-9947-9347e87d2da5.png)

New errors ^^

**Comment by Zrips** [comment]
How many players do you have online usually when those errors appear?

**Comment by Threshian** [comment]
One, two or three, but it appears pretty randomly
