### ISSUE TITLE
ChunkIOExecutor

### ISSUE THREAD

**Issue by SrT3ddy** [Zrips/CMI#7360]
### Description of Issue

Console error

### Version Information

```shell
[15:44:43 INFO]: --------------------------------------------------
[15:44:43 INFO]: CMI: 9.2.5.2 BungeeCord  MySQL
[15:44:43 INFO]: CMILib: 1.2.3.7 
[15:44:43 INFO]: Server: Mohist 1.12.2-R0.1-SNAPSHOT
[15:44:43 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[15:44:43 INFO]: Modules -> 57 enabled 0 disabled: 
[15:44:43 INFO]: --------------------------------------------------
```

### Errors

```shell
[15:42:19 WARN]: [CMI] Task #578792 for CMI v9.2.5.2 generated an exception
 java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_12_R1/chunkio/ChunkIOExecutor
        at com.Zrips.CMI.NBT.v1_12_R1.unloadData(v1_12_R1.java:172) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.unloadData(CMIUser.java:2718) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser$1.run(CMIUser.java:426) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[CraftTask.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422) [CraftScheduler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next version. Tho keep in mind that moded servers are not supported officially.
