### ISSUE TITLE
Many functions cannot be used normally

### ISSUE THREAD

**Issue by 849025143** [Zrips/CMI#7367]
### Description of Issue

Text cannot be displayed normally
It seems that those who use Json cannot work normally
relevant:
/kiteditor
/attachcommand
and more

### Version Information

```shell
[07:50:48] [Client thread/INFO]: [CHAT] ["",{"text":"","extra":[{"color":"yellow","text":"CMI 插件版本: "},{"color":"gold","text":"9.2.5.2 "},{"color":"gray","text":"SqLite"}]}]
[07:50:48] [Client thread/INFO]: [CHAT] ["",{"text":"","extra":[{"color":"yellow","text":"CMILib: "},{"color":"gold","text":"1.2.3.7 "}]}]
[07:50:48] [Client thread/INFO]: [CHAT] Server: 46 (MC: 1.7.10) 1.7.10-R0.1-SNAPSHOT
[07:50:48] [Client thread/INFO]: [CHAT] CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[07:50:48] [Client thread/INFO]: [CHAT] Modules -> 56 enabled 1 disabled: votifier
```

### Errors

```shell
[07:49:10 WARN]: java.lang.NullPointerException
[07:49:10 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessageManager.send(RawMessageManager.java:184)
[07:49:10 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:628)
[07:49:10 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:660)
[07:49:10 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:654)
[07:49:10 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:711)
[07:49:10 WARN]:        at net.Zrips.CMILib.Chat.ChatMessageListEdit.print(ChatMessageListEdit.java:258)
[07:49:10 WARN]:        at com.Zrips.CMI.commands.list.attachcommand.perform(attachcommand.java:175)
[07:49:10 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[07:49:10 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[07:49:10 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[07:49:10 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:741)
[07:49:10 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1298)
[07:49:10 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1035)
[07:49:10 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[07:49:10 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[07:49:10 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[07:49:10 WARN]:        at net.minecraft.network.NetworkSystem.networkTick2(NetworkSystem.java:181)
[07:49:10 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java)
[07:49:10 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1017)
[07:49:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:437)
[07:49:10 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:835)
[07:49:10 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
[07:49:10 WARN]:        at java.lang.Thread.run(Unknown Source)
```

### Relevant Config Sections

```yaml
default, I haven't made any changes
```

### Relevant Plugins

Valut-1.7.3 CMI-9.2.5.2

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by 849025143** [comment]
> What type of server do you have?


> 

Mohist

**Comment by Zrips** [comment]
Modded servers are not officially supported, especially ones from 8 years. There are too many different variables at play when it comes to modded servers, so support is limited as it gets.
