### ISSUE TITLE
invsee causes bug since 9.2.6.0

### ISSUE THREAD

**Issue by nhanledev** [Zrips/CMI#7416]
### Description of Issue

`/cmi inv <playername>` crash and kick you out if inventory has a items with model id (attached the player data below)

[9c096a25-acce-3188-867d-c96aba9b5678.dat.txt](https://github.com/Zrips/CMI/files/10138227/9c096a25-acce-3188-867d-c96aba9b5678.dat.txt)

### Version Information

```shell
[11:37:08 INFO]: --------------------------------------------------
[11:37:08 INFO]: CMI: 9.2.6.0 BungeeCord CMIB  MySQL
[11:37:08 INFO]: CMILib: 1.2.3.7
[11:37:08 INFO]: Server: Paper(300) 1.19.2-R0.1-SNAPSHOT
[11:37:08 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
[11:37:08 INFO]: Modules -> 19 enabled 38 disabled: spawnerProximity, cuffed, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, elytraBoost, cmiPlaytime, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, headDrop, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, homeInteractions, launchPad, armorstand, portals, anvilRenameColor, jail, spawners, paintingEditor, dynamicSigns, durabilityLoss, flightCharge, disabledEnchants, firstJoinMessages, selection, silentChest, warmup, totemBehavior
[11:37:08 INFO]: --------------------------------------------------
```

### Errors

```shell
[11:32:54] [Server thread/INFO]: tester02 issued server command: /cmi inv tester01
[11:32:54] [Netty Epoll Server IO #3/ERROR]: Packet encoding of packet ID 45 threw (skippable? false)
java.lang.IllegalArgumentException: Can't find id for 'null' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Experimental)]
	at net.minecraft.network.FriendlyByteBuf.writeId(FriendlyByteBuf.java:139) ~[?:?]
	at net.minecraft.network.protocol.game.ClientboundOpenScreenPacket.write(ClientboundOpenScreenPacket.java:30) ~[?:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:41) ~[paper-1.19.2.jar:git-Paper-300]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[paper-1.19.2.jar:git-Paper-300]
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.util.viaversion.CustomPipelineUtil.callEncode(CustomPipelineUtil.java:79) ~[AntiPopup-4.6.jar:?]
	at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:58) ~[AntiPopup-4.6.jar:?]
	at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:90) ~[AntiPopup-4.6.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.github.repooper.packetevents.Vulcan_mw.write(Vulcan_mw.java:60) ~[Vulcan-2.7.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at me.neznamy.tab.bridge.bukkit.BukkitBridge$CustomChannelDuplexHandler.write(BukkitBridge.java:124) ~[TAB-Bridge v2.0.7.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:86) ~[TradeSystem_v2.1.3_Hotfix-2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:86) ~[TradeSystem_v2.1.3_Hotfix-2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at com.ticxo.modelengine.nms.v1_19_1_R1.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:65) ~[Model-Engine-Demo-R3.1.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib-b605.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib-b605.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:460) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib-b605.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:32:54] [Server thread/INFO]: tester02 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'null' in map Registry[ResourceKey[minecraft:root / minecraft:menu] (Experimental)]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Custommodel data will not have real effect here. Error doesn't really mentions CMI in general. General issue looks to be from com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.util.viaversion.CustomPipelineUtil.callEncode you might want to report this to this developer as this needs to be fixed from his end.
