### ISSUE TITLE
NPE error

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#7420]
### Description of Issue

NPE error. No idea why. No one performed a command.
Stopped after about 50 of these.

### Version Information

```shell
CMI: 9.2.6.0 MySQL
CMILib: 1.2.3.7
Server: Purpur 1.19.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Enabled
Modules -> 31 enabled 26 disabled: cuffed, mirror, tablist, versionCheck, armorEffects, moneyCheque, noTarget, elytraBoost, eventCommands, coloredArmor, playerCombat, votifier, attachedCommands, spawnerCharge, namePlates, launchPad, armorstand, portals, holograms, dynamicSigns, playerChatTag, flightCharge, disabledEnchants, worldLimitsElytra, ranks, selection
```

### Errors

```shell
[Server thread/WARN]: [CMI] Task #693474 for CMI v9.2.6.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "<local2>[0]" is null
	at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.getCraftingInventory(RegChestManager.java:647) ~[CMI-9.2.6.0.jar:?]
	at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.updateWatcherInventory(RegChestManager.java:266) ~[CMI-9.2.6.0.jar:?]
	at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.lambda$0(RegChestManager.java:169) ~[CMI-9.2.6.0.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1857]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
And this times 50

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with todays update
