### ISSUE TITLE
Tfly error

### ISSUE THREAD

**Issue by TheTopCz** [Zrips/CMI#743]
```
>cmi tfly M1skoooSK 0
[00:55:44 WARN]: Unexpected exception while parsing console command "cmi tfly M1skoooSK 0"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.4.6
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchServerCommand(CraftServer.java:679) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.DedicatedServer.aW(DedicatedServer.java:453) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:412) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.commands.list.tfly.perform(tfly.java:118) ~[CMI8.0.4.6.jar:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[CMI8.0.4.6.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
... 8 more
>cmi tfly M1skoooSK 0 
[00:56:15 WARN]: Unexpected exception while parsing console command "cmi tfly M1skoooSK 0 "
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.4.6
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:694) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchServerCommand(CraftServer.java:679) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.DedicatedServer.aW(DedicatedServer.java:453) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:412) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.commands.list.tfly.perform(tfly.java:118) ~[CMI8.0.4.6.jar:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[CMI8.0.4.6.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-2b0e71c-4a24108]
... 8 more
```

This server is running CraftBukkit version git-Spigot-2b0e71c-4a24108 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

--------------------------------------------------
Version CMI: 8.0.4.6
Version server: Spigot 1.13-R0.1-SNAPSHOT
Version Vault: 1.6.10(+)
--------------------------------------------------

**Comment by Zrips** [comment]
Should be fixed with latest builds.
