### ISSUE TITLE
Warning when right-clicking a playerhead

### ISSUE THREAD

**Issue by MC-MrBirdy** [Zrips/CMI#7431]
### Description of Issue

When right-clicking a (placed down) playerhead the server returns a warning regarding java.lang.NoSuchMethodException. This happens on the (current) latest build of paper (324) for minecraft 1.19.3.

### Version Information

```shell
[14:55:29 INFO]: --------------------------------------------------
[14:55:29 INFO]: CMI: 9.3.0.0 SqLite
[14:55:29 INFO]: CMILib: 1.2.4.0
[14:55:29 INFO]: Server: Paper(324) 1.19.3-R0.1-SNAPSHOT
[14:55:29 INFO]: CMI economy: Disabled CMI Chat: Disabled
[14:55:29 INFO]: Modules -> 56 enabled 1 disabled: votifier
[14:55:29 INFO]: --------------------------------------------------
```

### Errors

```shell
[14:52:30 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.level.block.entity.TileEntitySkull.aa_()
[14:52:30 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[14:52:30 WARN]:        at CMILib1.2.4.0.jar//net.Zrips.CMILib.NBT.CMINBT.getNbt(CMINBT.java:1067)
[14:52:30 WARN]:        at CMILib1.2.4.0.jar//net.Zrips.CMILib.NBT.CMINBT.<init>(CMINBT.java:284)
[14:52:30 WARN]:        at CMI-9.3.0.0.jar//com.Zrips.CMI.AllListeners.PlayerListeners.onInteractHead(PlayerListeners.java:493)
[14:52:30 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor349.execute(Unknown Source)
[14:52:30 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:52:30 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:52:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:52:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672)
[14:52:30 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545)
[14:52:30 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:528)
[14:52:30 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1963)
[14:52:30 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[14:52:30 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[14:52:30 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[14:52:30 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[14:52:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[14:52:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[14:52:30 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[14:52:30 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[14:52:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[14:52:30 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[14:52:30 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[14:52:30 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[14:52:30 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[14:52:30 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[14:52:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:52:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:52:30 WARN]: [CMILib] Loaded class com.Zrips.CMI.Containers.Snd from CMI v9.3.0.0 which is not a depend or softdepend of this plugin.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
