### ISSUE TITLE
[TryMe] TryMe 7.1.0.3 AsyncPlayerChatEvent Error on player join 

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#7432]
### Description of Issue

Getting this error in console when players join. Players get "An internal error occurred while attempting to perform this command" when using "/answ" and cannot answer questions.

https://gist.github.com/mercurialmusic/d05f6bafc9be03bf4127652f44d8ceeb

Thanks!

### Version Information

```shell
TryMe 7.1.0.3
CMILib: 1.2.4.0 
Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will post new fixed version.

**Comment by mercurialmusic** [comment]
Thanks! I saw the update notes said "invalid answer setup" - do I have something misconfigured? Would prefer to correct it and avoid future problems if possible.

**Comment by mercurialmusic** [comment]
Yeahhh, @Zrips something is wonky. It's doing different things now. Not accepting any answers, and /tryme info returns the following whether on your original questions or our custom ones:

https://gyazo.com/82e929bfb7cf7143e86502b4f0f54155
https://gyazo.com/3bd39ca8d6b708688944ccd80b4d69b3

Also with Hangman Mode it returns the following:
```
[21:36:54 WARN]: [TryMe] Task #2693157 for TryMe v7.1.0.4 generated an exception
java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
        at me.Zrips.TryMe.gameModes.HangManMode.hideLetters(HangManMode.java:169) ~[TryMe7.1.0.4.jar:?]
        at me.Zrips.TryMe.gameModes.HangManMode.internalRun(HangManMode.java:39) ~[TryMe7.1.0.4.jar:?]
        at me.Zrips.TryMe.gameModes.HangManMode.runMode(HangManMode.java:87) ~[TryMe7.1.0.4.jar:?]
        at me.Zrips.TryMe.gameModes.GameModesUtil.processGameInitialization(GameModesUtil.java:337) ~[TryMe7.1.0.4.jar:?]
        at me.Zrips.TryMe.gameModes.HangManMode.initializeMode(HangManMode.java:101) ~[TryMe7.1.0.4.jar:?]
        at me.Zrips.TryMe.gameModes.AllMode.internalRun(AllMode.java:36) ~[TryMe7.1.0.4.jar:?]
        at me.Zrips.TryMe.gameModes.AllMode.access$0(AllMode.java:25) ~[TryMe7.1.0.4.jar:?]
        at me.Zrips.TryMe.gameModes.AllMode$1.run(AllMode.java:45) ~[TryMe7.1.0.4.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

But that's the only error I've seen so far on any of them. 

My configs are default except for the Questions.yml which has my own questions. Did the format change? Currently:

**Comment by Zrips** [comment]
Should be ok with new version, sorry for inconvenience

**Comment by mercurialmusic** [comment]
No worries dude! You do amazing work. Thanks for everything!
