### ISSUE TITLE
CMI-Bungee don't work in velocity

### ISSUE THREAD

**Issue by smartmadio** [Zrips/CMI#7436]
### Description of Issue

When I put CMIB.jar into velocity plugin folder and start velocity, I got an error message like this:
```
[09:03:33] [main/ERROR]: Unable to load plugin plugins/CMIB-1.0.2.2.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file CMIB-1.0.2.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:61) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:92) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
```

### Version Information

```shell
CMIB-1.0.2.2
velocity-3.1.2-SNAPSHOT-200
```

### Errors

```shell
[09:03:33] [main/ERROR]: Unable to load plugin plugins/CMIB-1.0.2.2.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file CMIB-1.0.2.2.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.getSerializedPluginInfo(JavaPluginLoader.java:151) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:61) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:92) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:343) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:224) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
	at com.velocitypowered.proxy.Velocity.main(Velocity.java:64) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
```
```


### Relevant Config Sections

_No response_

### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by notpivan** [comment]
Because it is not meant to

**Comment by enten** [comment]
@smartmadio 
I met the same issue and I figured that CMIB.jar isn't implemented to work with paper.

My usecase is to be able to connect a player to another server.

By reading doc about bungee plugin messaging channel, I learned how bungeecord channel works to connect player to another server :
https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/#connect

Finally I wrote a minimal plugin which exposes command `/connect <server>`  (`<server>` is a server name to connect the player).
With that plugin, I can use `asPlayer! connect <server>` in some cmi config files.

Maybe these few lines of code can help someone to achieve bungeecord command with CMI on Paper behind Velocity.

```java
// src/main/java/fr/modesurvie/bungeecord/Connect.java

package fr.modesurvie.bungeecord;

import com.google.common.io.ByteStreams;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.jetbrains.annotations.NotNull;

public class Connect extends JavaPlugin {

    // public static final String BUNGEECORD_CHANNEL = "bungeecord:main"; // bungeecord modern channel name
    public static final String BUNGEECORD_CHANNEL = "BungeeCord"; // bungeecord legacy channel name

    @Override
    public void onEnable() {
        getServer().getMessenger().registerOutgoingPluginChannel(this, BUNGEECORD_CHANNEL);
    }

    @Override
    public void onDisable() {
        getServer().getMessenger().unregisterOutgoingPluginChannel(this, BUNGEECORD_CHANNEL);
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        if (sender instanceof Player player && "connect".equals(command.getName()) && args.length == 1) {
            final var outputData = ByteStreams.newDataOutput();
            outputData.writeUTF("Connect");
            outputData.writeUTF(args[0]);

            player.sendPluginMessage(this, BUNGEECORD_CHANNEL, outputData.toByteArray());

            return true;
        }

        return false;
    }
}
```

```yml
# src/main/resources/plugin.yml

name: bungeecord-connect
version: 0.0.1
description: BungeeCord Connect command for Paper.
api-version: 1.19
load: POSTWORLD
main: fr.modesurvie.bungeecord.Connect
author: enten
website: https://github.com/Zrips/CMI/issues/7436

commands:
  connect:
    usage: /<command> <server>
```

**Comment by the456gamer** [comment]
These seem like 2 different issues:the first is an already open feature request for cmib to support velocity (which it doesn't atm)
Here is the most highly voted suggestion on the feature request tracker
https://github.com/Zrips/CMI/discussions/2515


The second was not being able to use bungees server switch command, probably as /server is injected at the proxy level to the player.
Cmi server should still work tho

**Comment by enten** [comment]
> The second was not being able to use bungees server switch command, probably as /server is injected at the proxy level to the player.

I confirm that's exactly what I observed. When a player send a chat command on a Paper server configured behind Velocity proxy: Velocity can handle some commands like `/server` (see [ServerCommand.java](https://github.com/PaperMC/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/command/builtin/ServerCommand.java#L42) in [Velocity](https://github.com/PaperMC/Velocity) codebase).

On a Paper server, if a plugin triggers a command (see [Server::dispatchCommand](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#dispatchCommand(org.bukkit.command.CommandSender,java.lang.String))), the server must have a command listener to handle it. 

So, if we trigger command `/server <name>` (through plugin like CMI) , the Paper server doesn't have command listener to handle it: because the command listener to handle command `/server <name>` exists in Velocity proxy.
