### ISSUE TITLE
9.3.0.3 console error

### ISSUE THREAD

**Issue by thewickening** [Zrips/CMI#7487]
### Description of Issue

This is getting spammed in console, it did not exist on the previous version.

`[17:02:19] [Server thread/WARN] [CMI/]: Task #19180 for CMI v9.3.0.3 generated an exception
java.lang.NullPointerException: null
        at com.Zrips.CMI.AllListeners.WorldLimits.lambda$2(WorldLimits.java:127) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:400) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.handler$baa000$arclight$runScheduler(MinecraftServerMixin.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}`

### Version Information

```shell
[17:04:09] [Server thread/INFO] [Console/]: --------------------------------------------------
[17:04:09] [Server thread/INFO] [Console/]: SYSTEM »  CMI: 9.3.0.3SYSTEM »  BungeeCord SYSTEM »  MySQLSYSTEM »  -> 9.3.0.2
[17:04:09] [Server thread/INFO] [Console/]: CMILib: 1.2.4.1 
[17:04:09] [Server thread/INFO] [Console/]: SYSTEM »  Server: 1.16.5 1.16.5-R0.1-SNAPSHOT
[17:04:09] [Server thread/INFO] [Console/]: SYSTEM »  CMI economy: Enabled SYSTEM »  Vault: 1.7.3-CMI SYSTEM »  CMI Chat: Enabled 
[17:04:09] [Server thread/INFO] [Console/]: SYSTEM »  Modules -> 38 enabled 19 disabled: cuffed, hpBossBar, moneyCheque, portals, holograms, noTarget, spawners, eventCommands, playerChatTag, rideAnimation, durabilityLoss, flightCharge, schedule, ranks, headDrop, spawnerCharge, warmup, namePlates, homeInteractions
```

### Errors

```shell
`[17:02:19] [Server thread/WARN] [CMI/]: Task #19180 for CMI v9.3.0.3 generated an exception
java.lang.NullPointerException: null
        at com.Zrips.CMI.AllListeners.WorldLimits.lambda$2(WorldLimits.java:127) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:400) ~[arclight:arclight-1.16.5-1.0.25-SNAPSHOT-eea2c2bb] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftSchedulerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.handler$baa000$arclight$runScheduler(MinecraftServerMixin.java:2160) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}`
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try new version 9.3.0.4 but your should not have gotten this error in this place. And your server version would be nice to know too as its not being reported back properly in /cmi version as it looks like.
