### ISSUE TITLE
Player is kicked after a world change

### ISSUE THREAD

**Issue by Weyl1** [Zrips/CMI#7488]
### Description of Issue

I upgraded CMI to 1.19.3 and since then when a player changes world it is disconnected and a warn is displayed

### Version Information

```shell
[18:46:53 INFO]: CMI: 9.3.0.4 BungeeCord MySQL-> 9.3.0.2
[18:46:53 INFO]: CMILib: 1.2.4.1
[18:46:53 INFO]: Server: Purpur 1.19.3-R0.1-SNAPSHOT
[18:46:53 INFO]: CMI economy: Activé Vault: 1.7.3-CMI CMI Chat: Activé
[18:46:53 INFO]: Modules -> 54 enabled 3 disabled: deathMessages, versionCheck, votifier
[18:46:53 INFO]: --------------------------------------------------
```

### Errors

```shell
[18:43:59 WARN]: [CMI] Task #40525 for CMI v9.3.0.4 generated an exception
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.worldFlyState.isFlyEnabled()" because "<local3>" is null
at com.Zrips.CMI.AllListeners.WorldLimits.lambda$2(WorldLimits.java:120) ~[CMI-9.3.0.4.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1883]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1883]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1883]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1883]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1883]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1883]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1883]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try out new 9.3.0.5 version
