### ISSUE TITLE
Problem with the order /vanish

### ISSUE THREAD

**Issue by BEBOUHHHH** [Zrips/CMI#7491]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####
The /vanish command does not work when we want to make ourselves invisible.. finally it works but with a chat and console error
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
[11:32:24 INFO]: TRAFIQUINTEE issued server command: /cmi placeholders vanish
[11:35:12 INFO]: TRAFIQUINTEE issued server command: /vanish
[11:35:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.3.0.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getPotionEffect(Lorg/bukkit/potion/PotionEffectType;)Lorg/bukkit/potion/PotionEffect;
at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:187) ~[?:?]
at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:165) ~[?:?]
at com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:157) ~[?:?]
at com.Zrips.CMI.Containers.CMIUser.setVanished(CMIUser.java:1996) ~[?:?]
at com.Zrips.CMI.commands.list.vanish.perform(vanish.java:81) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:399) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-db6de12-18fbb24]
... 15 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

![image](https://user-images.githubusercontent.com/94754258/210536907-2d386f28-f01a-4317-8b94-21031024688a.png)

**Spigot 1.8.8** 

**![image](https://user-images.githubusercontent.com/94754258/210536993-43fcac13-1874-490f-804e-3bba3b756cc1.png)** 

**![image](https://user-images.githubusercontent.com/94754258/210537241-2dec6b63-78f0-4a62-8d1d-eb8c9f0a38e1.png)**

**Comment by Zrips** [comment]
Will be fixed with next update
