### ISSUE TITLE
Weird economy error

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7561]
### Description of Issue

Hello, today ive got this completely random economy error in my console. Never seen it before, prolly somehow related to latest build. Also there was noone online on the server when it happened.

### Version Information

```shell
[02:39:43 INFO]: CMI plugin version: 9.3.1.2 SqLite
[02:39:43 INFO]: CMILib: 1.2.4.1 -> 1.2.4.3
[02:39:43 INFO]: Server: Pufferfish 1.19.3-R0.1-SNAPSHOT
[02:39:43 INFO]: CMI economy: enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: enabled
[02:39:43 INFO]: Modules -> 33 enabled 24 disabled: cuffed, mirror, launchPad, tablist, armorstand, versionCheck, armorEffects, moneyCheque, skin, noTarget, jail, paintingEditor, dynamicSigns, playerChatTag, bossBarCompass, coloredArmor, deathMessages, ranks, votifier, shulkerBackpack, attachedCommands, spawnerCharge, vanish, timedCommands
```

### Errors

```shell
[00:00:00 WARN]: java.io.IOException: Stream closed
[00:00:00 WARN]:        at java.base/java.io.BufferedWriter.ensureOpen(BufferedWriter.java:107)
[00:00:00 WARN]:        at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:117)
[00:00:00 WARN]:        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:256)
[00:00:00 WARN]:        at CMI-9.3.1.2.jar//com.Zrips.CMI.Modules.Economy.EconomyManager.moneyLog(EconomyManager.java:1038)
[00:00:00 WARN]:        at CMI-9.3.1.2.jar//com.Zrips.CMI.Modules.Economy.CMIEconomyAcount$1.run(CMIEconomyAcount.java:80)
[00:00:00 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[00:00:00 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[00:00:00 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:00:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[00:00:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[00:00:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will make a fix for it, but you can generally ignore it as it should not cause any issues for general performance of the plugin.
