### ISSUE TITLE
/list error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7569]
### Description of Issue

When I type /list while using https://www.spigotmc.org/resources/fakeplayers-1-8-1-19-fully-customizable.61054/ (https://github.com/herby2212/FakePlayers/tree/snapshot) I get error below. Also there's issue when using cmi_user_nickname on these players, it doesn't show nothing even when these players have UUID, it should show their name like on the real players?

Regarding it's UUIDS, author said, may this can be a problem? But even after restart when the plugin reuses the same UUIDs, players don't have any nickname & aren't in the /list (still same players with still same UUIDS (but may assigned a little bit after join).
![image](https://user-images.githubusercontent.com/18662086/216711638-5b529a91-5597-4fb6-bdeb-7abebb15c972.png)

### Version Information

```shell
[21:08:39 INFO]: --------------------------------------------------
[21:08:39 INFO]: CMI: 9.3.1.3 SqLite
[21:08:39 INFO]: CMILib: 1.2.4.4 -> 1.2.4.5
[21:08:39 INFO]: Server: Purpur 1.19.3-R0.1-SNAPSHOT
[21:08:39 INFO]: CMI economy: Disabled CMI Chat: Disabled 
[21:08:39 INFO]: Modules -> 56 enabled 1 disabled: votifier
[21:08:39 INFO]: --------------------------------------------------
```

### Errors

```shell
[21:07:30 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.3.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:981) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:321) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2339) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1906]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.CMIUser.isVanished()" because "<local17>" is null
        at com.Zrips.CMI.commands.list.list.perform(list.java:114) ~[CMI-9.3.1.3.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:399) ~[CMI-9.3.1.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

### Relevant Plugins

https://github.com/herby2212/FakePlayers/tree/snapshot

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
