### ISSUE TITLE
Paper Circular dependencies detected with CMI

### ISSUE THREAD

**Issue by PuppyNomNom** [Zrips/CMI#7611]
### Description of Issue

I'm able to bypass this issue with a start up flag but the Flag may be removed in the future according to paper.
[Logs.txt](https://github.com/Zrips/CMI/files/10777743/Logs.txt)

The server is unable to start due to circular dependencies with Cmi relying on Jobs, relying on MM relying on CMI.

### Version Information

```shell
CMI version 9.3.1.5
```

### Relevant Config Sections

```yaml
[19.02 12:23:30] [Server] [ERROR] [ConfiguredOrderedProviderStorage] Circular dependencies detected!
[19.02 12:23:30] [Server] [ERROR] [ConfiguredOrderedProviderStorage] You have a plugin that is depending on a plugin which refers back to that plugin. Your server will shut down until these are resolved, or the strategy is changed.
[19.02 12:23:30] [Server] [ERROR] [ConfiguredOrderedProviderStorage] Circular dependencies:
[19.02 12:23:30] [Server] [ERROR] [ConfiguredOrderedProviderStorage] CMI depends on Jobs depends on MythicMobs depends on CMI...
[19.02 12:23:30] [Server] [ERROR] [ConfiguredOrderedProviderStorage] SiegeWar depends on TownyResources depends on SiegeWar...
[19.02 12:23:30] [Server] [ERROR] [ConfiguredOrderedProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [x] I have searched the github and asked around before making this report.

**Comment by PuppyNomNom** [comment]
Like I said above, it can be fixed with a start up flag but that might not work in the future

**Comment by benpryde** [comment]
I have similar problem, it causes server crash but can be fixed via the same flag. But i dont think it's a  long term solution.

`[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] Circular plugin loading detected!
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] Circular load order:
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage]   CMI -> Jobs -> MythicMobs -> CMI
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage]   CMI -> Jobs -> MyPet -> Lands -> MythicMobs -> CMI
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage]   CMI -> Jobs -> MyPet -> Lands -> CMI
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage]   CMI -> Jobs -> MyPet -> PremiumVanish -> CMI
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage]   CMI -> Jobs -> MyPet -> MythicMobs -> CMI
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[10:51:20 ERROR]: [io.papermc.paper.plugin.storage.SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[10:51:20 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins CMI, CMI, CMI, CMI, CMI
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:70) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:37) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:443) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:51:20 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-02-25_10.51.20-server.txt
[10:51:20 INFO]: Stopping server
[10:51:20 INFO]: Saving players
[10:51:20 INFO]: Saving worlds
[10:51:20 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[10:51:20 INFO]: Flushing Chunk IO
>....2023-02-25 10:51:20,675 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
[10:51:20 INFO]: Closing Thread Pool
[10:51:20 INFO]: Closing Server
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.`

**Comment by CloudeLecaw** [comment]
well updating to latest paper 1.19.3 or 1.19.4 should solve this issue. because paper went back to support legacy plugins.

**Comment by Zrips** [comment]
Should be resolved with latest versions of CMILib CMI and/or paper builds
