### ISSUE TITLE
tpallworld does not work

### ISSUE THREAD

**Issue by altcraftovich** [Zrips/CMI#7626]
### Description of Issue

Hello,

I need to delete the old world, but I can't do it without tpall the players. There were no problems with this command before.

/cmi tpallworld world_farm_1 world;-4129;66;2227;-17;-0.5 -a

### Version Information

```shell
[11:38:57 INFO]: --------------------------------------------------
[11:38:57 INFO]: Версия плагина CMI: 9.3.1.5 BungeeCord  SqLite
[11:38:57 INFO]: CMILib: 1.2.4.5
[11:38:57 INFO]: Версия сервера: Purpur 1.19.3-R0.1-SNAPSHOT
[11:38:57 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-b131(CMIEInjector)C
[11:38:57 INFO]: Модули -> 28 включено 29 отключено: spawnerProximity, mirror, t
s, hpBossBar, launchPad, armorstand, anvilRenameColor, spawners, dynamicSigns, p
[11:38:57 INFO]: --------------------------------------------------
```

### Errors

```shell
[03:55:27 WARN]: [CMI] Plugin CMI v9.3.1.5 generated an exception while executing task 8459
net.minecraft.server.v1_16_R3.ReportedException: Loading NBT data
        at net.minecraft.server.v1_16_R3.NBTTagCompound.b(NBTTagCompound.java:483) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound.access$200(NBTTagCompound.java:33) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound$1.b(NBTTagCompound.java:59) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound$1.b(NBTTagCompound.java:44) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound.b(NBTTagCompound.java:476) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound.access$200(NBTTagCompound.java:33) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound$1.b(NBTTagCompound.java:59) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound$1.b(NBTTagCompound.java:44) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:180) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:149) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:62) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.Zrips.CMI.NBT.v1_16_R3.getNBTTagC(v1_16_R3.java:219) ~[?:?]
        at com.Zrips.CMI.NBT.v1_16_R3.getWorldName(v1_16_R3.java:246) ~[?:?]
        at com.Zrips.CMI.commands.list.tpallworld.lambda$0(tpallworld.java:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245) ~[?:?]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:271) ~[?:?]
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:343) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
        at net.minecraft.server.v1_16_R3.NBTTagString$1.b(NBTTagString.java:17) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagString$1.b(NBTTagString.java:13) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagList$1.b(NBTTagList.java:38) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagList$1.b(NBTTagList.java:20) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.NBTTagCompound.b(NBTTagCompound.java:476) ~[patched_1.16.5.jar:git-Purpur-1171]
        ... 19 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Ikdan08** [comment]
Ку

**Comment by mrfloris** [comment]
The other week I had to remove an event world, afterward I went to /spawn, and typed /cmi tpallworld eventworldname, and then run it again but with -a, it seems to have moved those users. I kept an eye on it and the first three that logged in again were all at spawn.

**Comment by Zrips** [comment]
Should be resolved with next version
