### ISSUE TITLE
Json in chat

### ISSUE THREAD

**Issue by TaxosTV** [Zrips/CMI#7639]
**Description of issue or feature request:** When a player sends a message to the chat, it is sent in JSON format.

---

**ERROR:**
```
[15:49:02 WARN]: java.lang.NullPointerException
[15:49:02 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessageManager.send(RawMessageManager.java:184)
[15:49:02 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:625)
[15:49:02 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:657)
[15:49:02 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:651)
[15:49:02 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:708)
[15:49:02 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.help(CommandsHandler.java:552)
[15:49:02 WARN]:        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:174)
[15:49:02 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:49:02 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188)
[15:49:02 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:702)
[15:49:02 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1381)
[15:49:02 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1118)
[15:49:02 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[15:49:02 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[15:49:02 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
[15:49:02 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
[15:49:02 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
[15:49:02 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[15:49:02 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842)
[15:49:02 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
[15:49:02 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

---

**Cmi Version (using`/cmi version`):** 9.3.1.5 SqLite
**Cmi LIB Version:** 1.2.4.5

**Server Version (using `/ver`):** This server is running Thermos | https://github.com/CyberdyneCC/Thermos | 1.7.10-R0.1-SNAPSHOT | 1.7.10-5.4 (MC: 1.7.10)

**Comment by mrfloris** [comment]
CMI is made for Spigot / Paper, any other outdated and unofficial forks and server engines are technically not supported. 

Did 1.7.10 even have support for json content?

Anyway, is this regular chat you're trying to make work, or are you trying to use /cmi ctellraw command?

**Comment by Zrips** [comment]
Modded servers are not supported and having 7+ years old one doesn't help here either.

**Comment by Kantets** [comment]
Hey, may be your give source for CMI?  So that I can fix such problems myself? For what did I actually give the money for, if on the site itself it says that there is support for 1.7.10
