### ISSUE TITLE
But the bug is triggered when the player sends a message java.lang.NullPointerException

### ISSUE THREAD

**Issue by MakesYT** [Zrips/CMI#7655]
### Description of Issue

But the bug is triggered when the player sends a message
![image](https://user-images.githubusercontent.com/42534870/223145783-ef6624b8-d5b6-4dff-9cbc-26ff4adc720b.png)
![image](https://user-images.githubusercontent.com/42534870/223145884-d89ad2e4-08c1-4b0a-b34f-04cd9ed366d5.png)

### Version Information

```shell
[22:52:27 INFO]: --------------------------------------------------
[22:52:27 INFO]: CMI: 9.3.1.5 SqLite-> 9.3.1.6
[22:52:27 INFO]: CMILib: 1.2.4.5 
[22:52:27 INFO]: Server: 1614.UNOFFICIAL (MC: 1.7.10) 1.7.10-R0.1-SNAPSHOT
[22:52:27 INFO]: CMI economy: Disabled CMI Chat: Disabled 
[22:52:27 INFO]: Modules -> 56 enabled 1 disabled: votifier
[22:52:27 INFO]: --------------------------------------------------
https://github.com/GTNewHorizons/Thermos/releases/tag/1.0-GTNH
```

### Errors

```shell
java.lang.NullPointerException
[22:48:41 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessageManager.send(RawMessageManager.java:184)
[22:48:41 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:625)
[22:48:41 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:657)
[22:48:41 WARN]:        at net.Zrips.CMILib.RawMessages.RawMessage.show(RawMessage.java:651)
[22:48:41 WARN]:        at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:193)
[22:48:41 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:48:41 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:48:41 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:48:41 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[22:48:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[22:48:41 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:48:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[22:48:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:489)
[22:48:41 WARN]:        at net.minecraft.network.NetHandlerPlayServer.chat(NetHandlerPlayServer.java:1234)
[22:48:41 WARN]:        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1158)
[22:48:41 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[22:48:41 WARN]:        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[22:48:41 WARN]:        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:137)
[22:48:41 WARN]:        at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:353)
[22:48:41 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[22:48:41 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:220)
[22:48:41 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:47)
[22:48:41 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[22:48:41 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[22:48:41 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[22:48:41 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[22:48:41 WARN]:        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[22:48:41 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[22:48:41 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100)
[22:48:41 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480)
[22:48:41 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447)
[22:48:41 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341)
[22:48:41 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
[22:48:41 WARN]:        at java.lang.Thread.run(Unknown Source)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You are using unsupported modded server and with 1.20 minecraft release we will be completely dropping 1.7.10 support as its just too outdated at this point even for vanilla servers.
