### ISSUE TITLE
[ISSUE] Persistent staff chat is broken

### ISSUE THREAD

**Issue by impmallet** [Zrips/CMI#766]
When peforming /staff toggle you are given a message indicating that persistent staff chat is enabled, but when you type into chat it just produces an unformatted vanilla style message that everyone can see.

CMI plugin version: 8.0.7.0
Server version: Spigot 1.13-R0.1-SNAPSHOT

**Server Type:  (Spigot

This server is running CraftBukkit version git-Spigot-fe3ab0d-3418f8d (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version

**Comment by CloudeLecaw** [comment]
you forgot to post the error itself

```
[12:05:20] [Server thread/INFO]: Cloude_Lecaw issued server command: /cmi staffmsg toggle
[12:05:28] [Netty Server IO #2/ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v8.0.7.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at net.minecraft.server.v1_13_R1.PlayerConnection.chat(PlayerConnection.java:1556) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.craftbukkit.v1_13_R1.entity.CraftPlayer.chat(CraftPlayer.java:320) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at gyurix.chatcontrol.modules.LongerChat.onPacketIN(LongerChat.java:58) [ChatControl_1.9Pre6.jar:?]
	at gyurix.protocol.Protocol.dispatchPacketInEvent(Protocol.java:41) [SpigotLib_8.0.1.jar:?]
	at gyurix.protocol.manager.ProtocolImpl$ClientChannelHook.channelRead(ProtocolImpl.java:170) [SpigotLib_8.0.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) [ProtocolLib_4.3.0-Build415.jar:4.4.0-SNAPSHOT-b415]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:692) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:577) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	at com.Zrips.CMI.utils.RawMessage.show(RawMessage.java:504) ~[?:?]
	at com.Zrips.CMI.utils.RawMessage.show(RawMessage.java:490) ~[?:?]
	at com.Zrips.CMI.commands.list.staffmsg.perform(staffmsg.java:78) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
	at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:43) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-82f4b3b]
	... 53 more
```

**Comment by impmallet** [comment]
Yes, it definitely should be fixed because the feature just doesn't work :P

**Comment by Zrips** [comment]
Will be fixed with next update.
