### ISSUE TITLE
Error occurred while enabling CMI v9.3.2.0

### ISSUE THREAD

**Issue by MrAnrehah** [Zrips/CMI#7676]
### Description of Issue

With the kernel update, the plugin stopped running.

### Version Information

```shell
[06:25:48 WARN]: Unexpected exception while parsing console command "cmi version"
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v9.3.2.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:925) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:888) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:542) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:489) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Errors

```shell
java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.CMILib.getReflectionManager()" because the return value of "net.Zrips.CMILib.CMILib.getInstance()" is null
	at com.Zrips.CMI.commands.CommandsHandler.<init>(CommandsHandler.java:74) ~[CMI-9.3.2.0.jar:?]
	at com.Zrips.CMI.CMI.getCommandManager(CMI.java:937) ~[CMI-9.3.2.0.jar:?]
	at com.Zrips.CMI.Modules.ModuleHandling.CMIModuleManager.load(CMIModuleManager.java:53) ~[CMI-9.3.2.0.jar:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1402) ~[CMI-9.3.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:574) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:485) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1933]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Relevant Plugins

CMI-9.3.2.0.jar CMILib1.2.4.6.jar purpur-1.19.3-1933.jar

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Cannot execute command 'cmi' in plugin CMI v9.3.2.0 -

Your error shows you're running 9.3, not 9.4.

**Comment by CloudeLecaw** [comment]
@MrAnreha might worth to update to 9.5.0.1 and check cmilib is also up to date.
You could run into issue using this old vesion with latest cmilib on 1.19.3+
