### ISSUE TITLE
Newst verion of CMI doesnt start up

### ISSUE THREAD

**Issue by MrCatFishek** [Zrips/CMI#7677]
### Description of Issue

Hello,
The newest version of CMI doesnt start up on AtomSpigot jar. (Floris said that i need to report here)
Jar: AtomSpigot
Ver: 1.8.8
Java 8

### Version Information

```shell
It doesnt display command because it doesnt start.
```

### Errors

```shell
[23:36:06 ERROR]: Error occurred while enabling CMI v9.4.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/level/World
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_312]
        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1472) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:327) ~[server.jar:git-AtomSpigot-unknown]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [server.jar:git-AtomSpigot-unknown]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [server.jar:git-AtomSpigot-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:353) [server.jar:git-AtomSpigot-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:312) [server.jar:git-AtomSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:442) [server.jar:git-AtomSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:405) [server.jar:git-AtomSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:323) [server.jar:git-AtomSpigot-unknown]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:279) [server.jar:git-AtomSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:601) [server.jar:git-AtomSpigot-unknown]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.World
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[server.jar:git-AtomSpigot-unknown]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[server.jar:git-AtomSpigot-unknown]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 16 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will make some changes with todays update, if issue persists let me know.
