### ISSUE TITLE
[9.4.0.1] Level World 1.12.2

### ISSUE THREAD

**Issue by SrT3ddy** [Zrips/CMI#7679]
### Description of Issue

The plugin does not load.

### Version Information

```shell
The plugin does not load the command n works.

Version: 9.4.0.1
Server Version: Mohist 1.12.2
```

### Errors

```shell
[02:31:56 INFO]: Enabling CMI v9.4.0.1
[02:31:56 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[02:31:56 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[02:31:56 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[02:31:56 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[02:31:56 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[02:31:56 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[02:31:56 INFO]: _______________________________________________________
[02:31:56 INFO]: Disconnecting Player: Server is still starting! Please wait before reconnecting.
[02:31:56 INFO]:   Citizens found.
[02:31:57 INFO]:   21 Enabled and 36 Disabled modules
[02:31:57 INFO]:   Permission plugin: LuckPerms5.4.61
[02:31:57 INFO]:   Initialized Cipher256 AES
[02:31:57 ERROR]: Error occurred while enabling CMI v9.4.0.1 (Is it up to date?)
 java.lang.NoClassDefFoundError: net/minecraft/world/level/World
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at com.mohistmc.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:22) ~[ProxyClass.class:?]
        at com.mohistmc.bukkit.nms.proxy.ProxyClass.forName(ProxyClass.java:17) ~[ProxyClass.class:?]
        at com.Zrips.CMI.commands.CommandsHandler.getClass(CommandsHandler.java:679) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.fillCommands(CommandsHandler.java:642) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1472) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.World
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[PluginClassLoader.class:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110) ~[PluginClassLoader.class:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        ... 16 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by DIDIRUS4** [comment]
+1

**Comment by Zrips** [comment]
Will make some changes with today's update, if issue repeats let me know.
