### ISSUE TITLE
Error when opening customrecipe menu

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7682]
### Description of Issue

Hello, after updating to newest version, i started getting this error every time i open customrecipe menu.

### Version Information

```shell
[16:42:09 INFO]: CMI plugin version: 9.4.0.2 SqLite
[16:42:09 INFO]: CMILib: 1.2.5.1 -> 1.2.5.2
[16:42:09 INFO]: Server: PufferfishPlus 1.19.3-R0.1-SNAPSHOT
[16:42:09 INFO]: CMI economy: enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: enabled
[16:42:09 INFO]: Modules -> 33 enabled 24 disabled: cuffed, mirror, launchPad, tablist, armorstand, versionCheck, armorEffects, moneyCheque, skin, noTarget, jail, paintingEditor, dynamicSigns, playerChatTag, bossBarCompass, coloredArmor, deathMessages, ranks, votifier, shulkerBackpack, attachedCommands, spawnerCharge, vanish, timedCommands
```

### Errors

```shell
[16:40:22 INFO]: Tikka_1 issued server command: /cmi customrecipe
[16:40:24 WARN]: java.lang.NoSuchFieldException: bP
[16:40:24 WARN]:        at java.base/java.lang.Class.getField(Class.java:2117)
[16:40:24 WARN]:        at CMILib1.2.5.1.jar//net.Zrips.CMILib.Reflections.getActiveContainerId(Reflections.java:1246)
[16:40:24 WARN]:        at CMILib1.2.5.1.jar//net.Zrips.CMILib.Reflections.updateInventoryTitle(Reflections.java:1393)
[16:40:24 WARN]:        at CMILib1.2.5.1.jar//net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:493)
[16:40:24 WARN]:        at CMILib1.2.5.1.jar//net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:462)
[16:40:24 WARN]:        at CMILib1.2.5.1.jar//net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:113)
[16:40:24 WARN]:        at CMI-9.4.0.2.jar//com.Zrips.CMI.commands.list.customrecipe.openSubMenu(customrecipe.java:526)
[16:40:24 WARN]:        at CMI-9.4.0.2.jar//com.Zrips.CMI.commands.list.customrecipe.openSubMenu(customrecipe.java:202)
[16:40:24 WARN]:        at CMI-9.4.0.2.jar//com.Zrips.CMI.commands.list.customrecipe$1.click(customrecipe.java:90)
[16:40:24 WARN]:        at CMILib1.2.5.1.jar//net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:273)
[16:40:24 WARN]:        at CMILib1.2.5.1.jar//net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:222)
[16:40:24 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor993.execute(Unknown Source)
[16:40:24 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[16:40:24 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[16:40:24 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:40:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:674)
[16:40:24 WARN]:        at net.minecraft.server.network.PlayerConnection.a()
[16:40:24 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a()
[16:40:24 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a()
[16:40:24 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1()
[16:40:24 WARN]:        at net.minecraft.server.TickTask.run()
[16:40:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d()
[16:40:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d()
[16:40:24 WARN]:        at net.minecraft.server.MinecraftServer.b()
[16:40:24 WARN]:        at net.minecraft.server.MinecraftServer.d()
[16:40:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x()
[16:40:24 WARN]:        at net.minecraft.server.MinecraftServer.bh()
[16:40:24 WARN]:        at net.minecraft.server.MinecraftServer.x()
[16:40:24 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c()
[16:40:24 WARN]:        at net.minecraft.server.MinecraftServer.i_()
[16:40:24 WARN]:        at net.minecraft.server.MinecraftServer.w()
[16:40:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0()
[16:40:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Update CMILib to the latest version.
