### ISSUE TITLE
issue with cmi on attached command in 1.19.4

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7690]
### Description of Issue

when i use the attached command from on the 1.19+4 paper testserver i get this error.

i reported this issue also to the dev of the plugin
permission timer because the command that tried to be executed is a commamd of the plugin permission timer.

### Version Information

```shell
9.4.0.2
```

### Errors

```shell
[01:47:18] [Server thread/ERROR]: [VKLib] [31m[VKLib] The file E:\Software\Spiele Patches&Clients\Serverbackup\__TestServer_\plugins\PermissionTimer\userdata\f24df990-9c6b-4f32-938a-4c91a26d31f4.yml is broken, it has been renamed to E:\Software\Spiele Patches&Clients\Serverbackup\__TestServer_\plugins\PermissionTimer\userdata\f24df990-9c6b-4f32-938a-4c91a26d31f4.yml.broken.1679186838636[0m
org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at com.vk2gpz.permissiontimer.m.T.O.f(O.java:115) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.j(H.java:184) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.t(H.java:177) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.remove(PermissionTimer.java:142) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.apply(PermissionTimer.java:244) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.f(R.java:297) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.K(R.java:204) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.onCommand(R.java:38) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.w.onCommand(w.java:138) ~[PermissionTimer_7.2.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1114) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1053) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:729) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:725) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:721) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.processInteract(CustomNBTListener.java:265) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:55) ~[CMI_9.4.0.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor414.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-457]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-457]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:488) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2007) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-457]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[01:47:18] [Server thread/ERROR]: [VKLib] [31m[VKLib] The file E:\Software\Spiele Patches&Clients\Serverbackup\__TestServer_\plugins\PermissionTimer\userdata\f24df990-9c6b-4f32-938a-4c91a26d31f4.yml is broken, it has been renamed to E:\Software\Spiele Patches&Clients\Serverbackup\__TestServer_\plugins\PermissionTimer\userdata\f24df990-9c6b-4f32-938a-4c91a26d31f4.yml.broken.1679186838636[0m
org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at com.vk2gpz.permissiontimer.m.T.O.f(O.java:115) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.j(H.java:184) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.t(H.java:177) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.remove(PermissionTimer.java:142) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.apply(PermissionTimer.java:244) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.f(R.java:297) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.K(R.java:204) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.onCommand(R.java:38) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.w.onCommand(w.java:138) ~[PermissionTimer_7.2.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1114) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1053) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:729) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:725) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:721) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.processInteract(CustomNBTListener.java:265) ~[CMI_9.4.0.2.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:55) ~[CMI_9.4.0.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor414.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-457]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-457]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[paper-1.19.4.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:488) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2007) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.4.jar:git-Paper-457]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-457]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
well you didnt understood. it was working fine in 1.19.2 so i cMe here too and also informed the dev of the permission timer plugin

**Comment by MC-MrBirdy** [comment]
So have you tried running that command for a player without the _ (an underscore) in their name?

Updates can break things, sadly that does not make it better or easier for server admins. Running any attached command with the _ (and underscore) or other special characters in it does not result in errors on my own test server (using the above mentioned versions). However do note that I do not own and thus run the (or a) "permission timer" plugin.

_I am not trying to insult you nor telling in anyway that you do not know how to use things. It's just curiosity, regarding the issue you are experiencing, since I am using some attached commands myself. Being able to reproduce an issue like this with different cases might help others understand better what is going on and what they may do to prevent said issues._

**Comment by Zrips** [comment]
@CloudeLecaw 
This looks to be fully an issue with vk2gpz.permissiontimer plugin, CMI only triggers command and rest of it goes over to this plugin which then tries to load file or something with funky path name.

**Comment by CloudeLecaw** [comment]
thank you for pointing this out :)
