### ISSUE TITLE
Is it compatible with 1.13.1?

### ISSUE THREAD

**Issue by shawngiese** [Zrips/CMI#771]
Cannot start plugin.

**ERROR**
```
[CMI] Enabling CMI v8.0.7.0
[15:56:33 INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_13_R2
[15:56:33 ERROR]: Error occurred while enabling CMI v8.0.7.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
This server is running CraftBukkit version git-Spigot-2440e18-d0bb0a1 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
```

**Cmi Version (using`/cmi version`):** 
8.0.7.0

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.13.1

**Comment by CloudeLecaw** [comment]
```
[21:41:12] [Server thread/ERROR]: Error occurred while enabling CMI v8.0.7.0 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:413) ~[spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:130) ~[spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:126) ~[spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at com.Zrips.CMI.Modules.Afk.AfkManager.tasker(AfkManager.java:134) ~[?:?]
	at com.Zrips.CMI.Modules.Afk.AfkManager.<init>(AfkManager.java:25) ~[?:?]
	at com.Zrips.CMI.CMI.getAfkManager(CMI.java:770) ~[?:?]
	at com.Zrips.CMI.CMI.onDisable(CMI.java:1150) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1212) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.1.jar:git-Spigot-2440e18-997d378]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by cdmvirt** [comment]
can confirm this issue on Spigot 1.13.1 (MC 1.13_R2)

**Comment by shawngiese** [comment]
The www.spigotmc.org news on 1.13.1 said it would probably break a lot of plugins. They also said if you ran Spigot 1.13 that when you updated from that you would have to use an old version of your world. Doesn't sound like they are making it easy on developers but trying to move as fast as they can.

**Comment by cdmvirt** [comment]
@shawngiese I don't understand your comment, old world? I have 1.13 world forceUpgrade to 1.13.1 no issues whats so ever, the issue is that its now v_1_13_R2 instead of R1 all plugins locked to R1 won't work on R2

**Comment by shawngiese** [comment]
Sorry,
In my case I read the notes on the Spigot 1.13 and it looked like they were going to move all development to 1.13.1. I considered staying in 1.13 to keep compatible with more plugins but the note on the Spigot front page said this about the 1.13 version..."You may use this version to test conversion of your world, but you will NEED to restore your world from a 1.12.2 backup before moving onto the second wave." 

So, I was just pointing out that it "appears" that we should be using 1.13.1 but that they also said it would break a lot of plugins.

**Comment by shawngiese** [comment]
Updated to the latest 1.13.1 and still a block...

> This server is running CraftBukkit version git-Spigot-2440e18-6304ccd (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
Unexpected exception while parsing console command "cmi"
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v8.0.7.0 - plugin is disabled.

**Comment by cdmvirt** [comment]
yes, seems cmi is locked to the highest spigot version of v_1_13_R1 and since 1.13.1 is v_1_13_R2 cmi disables itself.

**Comment by RustyDagger** [comment]
really Frustrating as a premium resource I own like 3 of Zrips and Its not just Limited to CMI, but selection vis as well. Its the only plugin of 30 I use that is not working Iv paid money to now have this Pain in my backside. Its times like this I question my sanity and Wonder why i didn't just stick with some version of essentials. Atleast thats updated.

**Comment by CloudeLecaw** [comment]
wait wait clam down Rusty..Did u ever thought that a dev also has a private reallife and may also can go on Holidays? 🥉 
Im Pretty sure when he is back the 1.13.1 support will be one of the first steps.

**Comment by RustyDagger** [comment]
Yeah Im aware that sometimes real life takes over but iv been left Hung by this for like a week now, Its an issue I could really do with out.

**Comment by CloudeLecaw** [comment]
we all wait since the 1.13.1 release for the fix for it. Our Server has the same Problem that we still Keep on 1.13 because CMI is not Ready Jet. And yes..we all Paid for it ;) Else we would be here...
All we can do is waiting and inform the players that we Need to stay at 1.13 until "all" essential pluigins are Ready for the 1.13.1
