### ISSUE TITLE
Special Charakter in name let some CustomAliases fail...

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7716]
### Description of Issue

Some Players on Our Server using `_` or `__` in their names.
We created a custom alias that works fine if these are not part of the players names.
But if the player has them the alias seems to fail the execution

The Players name where we noticed this is called
Glorbo__Florbo    and i also Noticed it once with Cloude_Lecaw

The Custom Alias `/vip give Glorbo__Florbo test` was executed.
The Internal CMI part looks fine but when it should set the $1 for an other plugin in the custom alias it
failed and tells Special charakters are not allowed....

The command calls an other command of PermissionTimer that executes the following thing:

```
  TestVIP:
    expire: 1h
    given_msg: "&2[&aLululand-Service&2]&r Du hast von einem Staffler den Rang &4[&5%commonname%&4]&r fÃ¼r &c1 Stunde&r bekommen. Das bedeutet Du hast 10 Homepunkte, kannst mit der Feder in der Hand unendlich lange fliegen mit der Elytra, kannst einen reitbaren Drachen mit dem Drachenstock rufen, hast keinen Durst, hast einen Discount auf Mysteryboxen und Gadgets, und kannst die Fledermaus und Lohe als Haustier nutzen."
    expire_msg: "&2[&aLululand-Service&2]&r Dein Rang &4[&e%commonname%&4]&r ist gerade abgelaufen."
    limit_msg: "&2[&aLululand-Service&2]&r Du hast das Limit Ã¼berschritten."
    pre_cmd:
      - "pex user %player% group add TestVIP"
    post_cmd:
      - "pex user %player% group remove TestVIP"
    online: false
```

### Version Information

```shell
[11:41:28 INFO]: --------------------------------------------------
[11:41:28 INFO]: CMI Pluginversion: 9.5.0.1 MySQL
[11:41:28 INFO]: CMILib: 1.2.5.2 
[11:41:28 INFO]: Server: Paper(307) 1.19.2-R0.1-SNAPSHOT
[11:41:28 INFO]: CMI Economy: Aktiviert Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Aktiviert 
[11:41:28 INFO]: Module -> 58 aktiviert 0 deaktiviert: 
[11:41:28 INFO]: --------------------------------------------------
```

### Errors

```shell
[11:19:16] [Server thread/INFO]: Blueeyestar issued server command: /vip give Glorbo__Florbo test
[11:19:17] [Server thread/INFO]: User "a222941c-442d-4385-9167-f45a3dec7ce1/Glorbo__Florbo" added to group "TestVIP"!
[11:20:21] [Server thread/ERROR]: [VKLib] [31m[VKLib] The file /var/lib/pufferpanel/servers/8758dfcc/plugins/PermissionTimer/userdata/a222941c-442d-4385-9167-f45a3dec7ce1.yml is broken, it has been renamed to /var/lib/pufferpanel/servers/8758dfcc/plugins/PermissionTimer/userdata/a222941c-442d-4385-9167-f45a3dec7ce1.yml.broken.1680168021413[0m
org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.vk2gpz.permissiontimer.m.T.O.f(O.java:115) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.j(H.java:184) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.t(H.java:177) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.remove(PermissionTimer.java:142) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.apply(PermissionTimer.java:244) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.f(R.java:297) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.K(R.java:204) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.onCommand(R.java:38) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.w.onCommand(w.java:138) ~[PermissionTimer_7.2.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1114) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1053) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:729) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:725) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:721) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.processInteract(CustomNBTListener.java:265) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:55) ~[CMI_9.5.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor927.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:488) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2758) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:20:21] [Server thread/ERROR]: [VKLib] [31m[VKLib] The file /var/lib/pufferpanel/servers/8758dfcc/plugins/PermissionTimer/userdata/a222941c-442d-4385-9167-f45a3dec7ce1.yml is broken, it has been renamed to /var/lib/pufferpanel/servers/8758dfcc/plugins/PermissionTimer/userdata/a222941c-442d-4385-9167-f45a3dec7ce1.yml.broken.1680168021413[0m
org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:204) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:169) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:164) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:119) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1229) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:345) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:263) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:235) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:185) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:175) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:159) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:559) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.vk2gpz.permissiontimer.m.T.O.f(O.java:115) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.j(H.java:184) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.H.t(H.java:177) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.remove(PermissionTimer.java:142) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.PermissionTimer.apply(PermissionTimer.java:244) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.f(R.java:297) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.K(R.java:204) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.R.onCommand(R.java:38) ~[PermissionTimer_7.2.0.jar:?]
	at com.vk2gpz.permissiontimer.P.w.onCommand(w.java:138) ~[PermissionTimer_7.2.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1114) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1053) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:729) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:725) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:721) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.processInteract(CustomNBTListener.java:265) ~[CMI_9.5.0.1.jar:?]
	at com.Zrips.CMI.Modules.AttachedCommands.CustomNBTListener.playerInteractCommand(CustomNBTListener.java:55) ~[CMI_9.5.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor927.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-307]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:492) ~[paper-1.19.2.jar:git-Paper-307]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:488) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2758) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-307]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Relevant Config Sections

```yaml
CustomAlias:
  vip:
    Cmds:
    - check:$1==null|info! check:$2==null! msg! [playerName] &6Gültigkeit Deiner VIP-Ränge
    - check:$1==null|info! check:$2==null! msg! [playerName] &6===========================
    - check:$1==null|info! check:$2==null! msg! [playerName] &6 &6
    - check:$1==null|info! check:$2==null! msg! [playerName] &aRang &a:&b     &eläuft ab in
    - check:$1==null|info! check:$2==null! msg! [playerName] &6 &6
    - check:$1==null|info! check:$2==null! msg! [playerName] %pt_perm_TestVIP%
    - check:$1==null|info! check:$2==null! msg! [playerName] %pt_perm_VIPmini%
    - check:$1==null|info! check:$2==null! msg! [playerName] %pt_perm_VIP%
    - check:$1==info! check:$2!=null! check:$3==null! perm:cmi.customalias.vip.info! ptimer info $2
    - check:$1==info! check:$2!=null! check:$3==big|mini|test! perm:cmi.customalias.vip.info! perm:cmi.customalias.vip.give@! msg! [playerName] &c Du hast nicht die Berechtigung die Befehlsargumente big&c|&fmini&c|&ftest&c zu benutzen.
    - check:$1==info! check:$2!=null! check:$3==big|mini|test! perm:cmi.customalias.vip.info! perm:cmi.customalias.vip.give! msg! [playerName] &c Die Befehlsargumente big&c|&fmini&c|&ftest&c funktionieren nur mit dem give Argument. \n Benutzung&c:&c &4/&4vip give &4[&4Spielername&4] &4[&4big&4|&4mini&4|&4test&4] \n &f Es wird der normale Infobefehl ausgeführ    
    - check:$1==info! check:$2!=null! check:$3!=null|big|mini|test! perm:cmi.customalias.vip.info! ptimer info $2
    - check:$1==info! check:$2!=null! perm:cmi.customalias.vip.info@! msg! [playerName] &c Du hast nicht Berechtigung die VIP Info anderer Spieler auszulesen.
    - check:$1==give! check:§2==null! perm:cmi.customalias.vip.give@! msg! [playerName] &c Du hast nicht Berechtigung das give Argument zu benutzen.
    - check:$1==give! check:$2==null! perm:cmi.customalias.vip.give! msg! [playerName] &c Du hast vergessen einen Spielernamen anzugeben! Benutzung&c:&c &4/&4vip give &4[&4Spielername&4] &4[&4big&4|&4mini&4|&4test&4]
    - check:$1==give! check:$2!=null! check:$3!=big|mini|test! perm:cmi.customalias.vip.give! msg! [playerName] &c Du musst einen gültigen VIP Rang eingeben. Benutzung&c:&c &4/&4vip give &4[&4Spielername&4] &4[&4big&4|&4mini&4|&4test&4]    
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! asConsole! cmi kit VIP $2 -s
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! ptimer give $2 VIP
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! msg! $2 &e Als Dank für deine Spende hast Du &b&l100 Votis &ein dein Inventar bekommen.&4 &c&4
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big! msg! [playerName] &e Du hast &2&l$2 &b&l10 Votebarren &ein das Inventar gegeben.
    - check:$1==give! check:$2!=null! check:$3==big! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.big@! msg! [playerName] &c Du hast nicht die Berechtigung den VIPRang zu vergeben.
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! asConsole! cmi kit miniVIP $2 -s
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! ptimer give $2 VIPmini
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! msg! $2 &e Als Dank für deine Spende hast Du &b&l50 Votis &ein dein Inventar bekommen.&4 &c&4
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini! msg! [playerName] &eDu hast &2&l$2 &b&l5 Votebarren &ein das Inventar gegeben.
    - check:$1==give! check:$2!=null! check:$3==mini! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.mini@! msg! [playerName] &c Du hast nicht die Berechtigung den Mini-VIPRang zu vergeben.
    - check:$1==give! check:$2!=null! check:$3==test! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.test! ptimer give $2 TestVIP
    - check:$1==give! check:$2!=null! check:$3==test! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.test! msg! [playerName] &eDu hast &2&l$2 &eden Rang &bTestVIP &efür eine Stunde gegeben.
    - check:$1==give! check:$2!=null! check:$3==test! perm:cmi.customalias.vip.give! perm:cmi.customalias.vip.give.test@! msg! [playerName] &c Du hast nicht die Berechtigung den Test-VIPRang zu vergeben.
    Perm: true
    Tab: true
    CustomTabs:
    - 'info,give, [playername], big,mini,test'
```

### Relevant Plugins

PermissionTimer 7.2.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
I closed this ticket after you could point this out.

Thank you for take an eye on the error <3
