### ISSUE TITLE
Error when using and using the bed

### ISSUE THREAD

**Issue by ZelefRU** [Zrips/CMI#7718]
### Description of Issue

When the player lies down on the bed, this error occurs.

### Version Information

```shell
[15:04:55 INFO]: --------------------------------------------------
[15:04:55 INFO]: Версия плагина CMI: 9.4.0.2 SqLite-> 9.5.0.1
[15:04:55 INFO]: CMILib: 1.2.5.2 
[15:04:55 INFO]: Версия сервера: Pufferfish 1.19.3-R0.1-SNAPSHOT
```

### Errors

```shell
[15:03:03 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.level.storage.loot.LootTableRegistry net.minecraft.server.MinecraftServer.aH()'
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1817)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:188)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:172)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:109)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:85)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Messages.CMIMultiMessage.show(CMIMultiMessage.java:228)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Messages.CMIMessages.broadcastMessage(CMIMessages.java:168)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Messages.CMIMessages.broadcastMessage(CMIMessages.java:146)
[15:03:03 WARN]:        at CMI-9.4.0.2.jar//com.Zrips.CMI.AllListeners.PlayerListeners.PlayerBedEnterEvent(PlayerListeners.java:254)
[15:03:03 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor557.execute(Unknown Source)
[15:03:03 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[15:03:03 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[15:03:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:03:03 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[15:03:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[15:03:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[15:03:03 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:281)
[15:03:03 WARN]:        at net.minecraft.server.level.EntityPlayer.startSleepInBed(EntityPlayer.java:1370)
[15:03:03 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1523)
[15:03:03 WARN]:        at net.minecraft.world.level.block.BlockBed.a(BlockBed.java:114)
[15:03:03 WARN]:        at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:1061)
[15:03:03 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:572)
[15:03:03 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960)
[15:03:03 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[15:03:03 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[15:03:03 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[15:03:03 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1343)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1320)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1313)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1291)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:03:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:03:03 WARN]: java.lang.NoSuchMethodError: 'net.minecraft.world.level.storage.loot.LootTableRegistry net.minecraft.server.MinecraftServer.aH()'
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1817)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:188)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:172)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:127)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:85)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Messages.CMIMultiMessage.show(CMIMultiMessage.java:228)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Messages.CMIMessages.broadcastMessage(CMIMessages.java:168)
[15:03:03 WARN]:        at CMILib1.2.5.2.jar//net.Zrips.CMILib.Messages.CMIMessages.broadcastMessage(CMIMessages.java:146)
[15:03:03 WARN]:        at CMI-9.4.0.2.jar//com.Zrips.CMI.AllListeners.PlayerListeners.PlayerBedEnterEvent(PlayerListeners.java:254)
[15:03:03 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor557.execute(Unknown Source)
[15:03:03 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[15:03:03 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[15:03:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:03:03 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[15:03:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[15:03:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[15:03:03 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:281)
[15:03:03 WARN]:        at net.minecraft.server.level.EntityPlayer.startSleepInBed(EntityPlayer.java:1370)
[15:03:03 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1523)
[15:03:03 WARN]:        at net.minecraft.world.level.block.BlockBed.a(BlockBed.java:114)
[15:03:03 WARN]:        at net.minecraft.world.level.block.state.BlockBase$BlockData.a(BlockBase.java:1061)
[15:03:03 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:572)
[15:03:03 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960)
[15:03:03 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[15:03:03 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[15:03:03 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[15:03:03 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1343)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1320)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1313)
[15:03:03 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1291)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
[15:03:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[15:03:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:03:03 ERROR]: Could not pass event PlayerBedEnterEvent to CMI v9.4.0.2
java.lang.IllegalArgumentException: advancement
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:2544) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.grant(CMIAdvancement.java:197) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:173) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:127) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Advancements.AdvancementManager.sendToast(AdvancementManager.java:85) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Messages.CMIMultiMessage.show(CMIMultiMessage.java:228) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Messages.CMIMessages.broadcastMessage(CMIMessages.java:168) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Messages.CMIMessages.broadcastMessage(CMIMessages.java:146) ~[CMILib1.2.5.2.jar:?]
        at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerBedEnterEvent(PlayerListeners.java:254) ~[CMI-9.4.0.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor557.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:git-Pufferfish-61]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:281) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.level.ServerPlayer.startSleepInBed(ServerPlayer.java:1370) ~[?:?]
        at net.minecraft.world.entity.player.Player.startSleepInBed(Player.java:1523) ~[?:?]
        at net.minecraft.world.level.block.BedBlock.use(BedBlock.java:114) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1061) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:572) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try using latest #61 Puferfish version if you want to stick with 1.19.3 server as that one doesn't seem to have any issues with this. UpdateCMILib to the latest version to. If that doesn't help, for time being update your info.sleepersRequired locale line to not use toast type messages.
