### ISSUE TITLE
Unable to Leave Chat Room (or use some other commands)

### ISSUE THREAD

**Issue by DoubleYouCash** [Zrips/CMI#7741]
### Description of Issue

After creating a chat room, I was able to join it and chat within it, but when I tried to leave the chat room, I was getting an error in console and was unable to leave. I had to kick myself from the chat room using `chat kick <myself>`. I am setting up chat rooms for players to use and I don't want to make players be kicked by the owner of the chat room as the only way for them to leave. Also, I was able to add someone to a chat room using the command `/chat join <chatroom> <username>` and it did add them to the chat, but threw the same error in the console. 

Also, I have not updated my server to 1.19.4 yet due to other plugins needs to update, so I do not have the most up-to-date version of CMI but I did search all of the changelogs on spigot and there was nothing mentioned for any fixes with the chatrooms. I don't believe that this should be an issue, but let me know if I have overlooked that and I will do some testing with the plugin on a newer version.

Thanks!

### Version Information

```shell
--------------------------------------------------
CMI plugin version: 9.4.0.2 SqLite-> 9.5.0.2
CMILib: 1.2.5.2
Server: Paper(448) 1.19.3-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b(CMIEInjector) CMI Chat: Enabled
Modules -> 52 enabled 5 disabled: customMessages, playerCombat, votifier, moneyCheque, headDrop
--------------------------------------------------
```

### Errors

```shell
[00:42:24] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.4.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-448]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class com.Zrips.CMI.Containers.CMIUser cannot be cast to class org.bukkit.command.CommandSender (com.Zrips.CMI.Containers.CMIUser is in unnamed module of loader 'CMI-9.4.0.2.jar' @76d392e1; org.bukkit.command.CommandSender is in unnamed module of loader java.net.URLClassLoader @66cd51c3)
        at net.Zrips.CMILib.Messages.CMIMessages.sendMessage(CMIMessages.java:129) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Messages.CMIMessages.sendMessage(CMIMessages.java:102) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Messages.CMIMessages.sendMessage(CMIMessages.java:98) ~[CMILib1.2.5.2.jar:?]
        at net.Zrips.CMILib.Messages.CMIMessages.sendMessage(CMIMessages.java:94) ~[CMILib1.2.5.2.jar:?]
        at com.Zrips.CMI.Containers.CMIUser.sendMessage(CMIUser.java:3022) ~[CMI-9.4.0.2.jar:?]
        at com.Zrips.CMI.Modules.ChatFormat.CMIChatRoom.informLeave(CMIChatRoom.java:170) ~[CMI-9.4.0.2.jar:?]
        at com.Zrips.CMI.commands.list.chat.perform(chat.java:374) ~[CMI-9.4.0.2.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:399) ~[CMI-9.4.0.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

### Relevant Config Sections

```yaml
Chat:
  # Will try to modify chat to display it in defined format
  ModifyChatFormat: true
  # When set to true, regular and private messages (excludes clean messages) will have additional information when hovering over it (PlaceHolderAPI supported) and can be clicked for quick reply option
  # To change default hover over messages seen on sent message, go to your locale file to Chat section
  ClickHoverMessages: false
  DiscordSRV:
    # Enables support for DiscordSRV plugin
    Enabled: false
    # Defines name of global chat channel in discordsrv
    GlobalChannel: global
    # Indicator which can be used as {discord} in chat format to indicate that message came from discord and not ingame
    Label: '&2[&7D&2]'
    UnlinkedLabel: '&4[&cD&4]'
    # When enabled and you have ranged messages enabled, we will send all of them to DiscordSRV
    # When disabled, only shouts and messages sent by players with cmi.chat.rangebypass permission node will be visible in discord
    RangedMessages: true
  # Enables support for DynMap web chat
  DynMapChat: false
  # When set to false, each time you will use /r you will reply to person you previously sent message directly or to person who sent you message if there is none you have conversion before
  # When this set to true, players with /r will reply to person who last sent private message. This can result in confusion when using /r while getting private messages from multiple players
  ReplyToLastMessenger: true
  # If ReplyToLastMessenger is set to false, then timeOut will be taken into consideration to who you should reply
  # If you had conversation in last 120 seconds (default) then even receiving message from 3rd person, you will still reply to original player
  # If you had conversation in longer then 120 seconds period, then you will reply to latest person who send you a message
  LastMessengerTimeOut: 120
  # When set to true players will need to have cmi.command.msg.[groupname].send where [groupName] is receivers main permission group
  PrivateMessagesGroups: false
  # When set to false, web pge links in a chat will not get shortened to default [LINK] format
  TranslateLink: true
  # Defines regex when replacing url in chat with short word
  # Examples:
  # (https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9]\.[^\s]{2,})
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?
  # ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s]+)
  LinkRegex: ((http|https|ftp|ftps)\:\/\/)?[a-zA-Z0-9\-]+\.[a-zA-Z]{2,3}(\/\S*)?([^\s]+)
  # When set to true, particular variables in chat will be translated into items player are holding. List of variables belove
  HoverItems: true
  # Defines regex when replacing item line in chat with players item in hand information. Only works when CMI hover over chat format is enabled
  ItemRegex:
  - (\%item\%)
  - (\[item\])
  - (\%i\%)
  Bungee:
    # Attention! This will require you to have CMI Bungee plugin which can be found at zrips.net
    # Or direct download https://www.zrips.net/cmi/
    # Do you want to enable private messaging over bungeecord
    Messages: false
    # Do you want to enable public messaging over bungeecord
    # Player needs to have cmi.bungee.publicmessages.[servername] permission node to be able to send messages to target server
    PublicMessages: false
    # Do you want to enable staff messaging over bungeecord
    StaffMessages: false
  # Used for simple chat messages. Optional variables: {displayName} {world} {prefix} {suffix} {group} {shout} {message}. Supporting PlaceHolderAPI variables like %player_server%
  # ATTENTION! Dont use gradient colors for {message} variable, if you want to apply gradient for it, utilize GeneralMessageFormat section
  GeneralFormat: '&8LIMBO!&0 {displayName}:&8 {message}'
  # Will define message format itself, this allows to have gradients in messages
  # It NEEDS to contain {message} otherwise we will ignore this setup
  # For 1.16+ servers you can use color gradients like '{#b3a28f>}{message}{#d7b8e6<}'
  # You can have more than 2 colors in gradient. To define it repeat {message} variable. For example '{#b3a28f>}{message}{#5c6999<>}{message}{#d7b8e6<}'
  GeneralMessageFormat: '{message}'
  Ranged:
    # Defines range of regular messages to travel
    # Set to -1 to disable range restriction
    General: -1
    # Defines range of shout messages to travel
    # Shout messages should start with ! and player should have cmi.chat.shout permission
    # GeneralRange should be enabled
    # set to 0 to shout across all worlds, -1 to disable
    Shout: 0
    # Defines cost for each shout message
    ShoutCost: 0
    # List of message range limits
    # Player count fallowed by range
    # Player amount defines from how many we should use this range
    Dynamic:
      Use: false
      Limits:
      - 1-0
      - 10-1000
      - 20-500
      - 30-400
      - 40-300
      - 50-200
  # Prefix used to indicate that message should be sent to public chat instead of current players chat room
  # Set it to empty field if you want this feature to be disabled
  ChatRoomShout: '!'
  # Time in seconds you want to keep chat rooms alive before removing them
  # This only applies to empty rooms after last user leaves it
  ChatRoomLife: 3600
  # Defines suggested commands when you click on public, private and similar messages. [playerName], [playerDisplayName] and [playerNickName]  can be used to include players name
  ClickSuggestions:
    pubmsg: '/msg [playerDisplayName] '
    privmsg: '/msg [playerDisplayName] '
    staffmsg: '/msg [playerDisplayName] '
    helpop: '/msg [playerDisplayName] '
    chatroom: '/msg [playerDisplayName] '
    discord: '/msg [playerDisplayName] '
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatgroup.[id] permnission node to use
  # Permission example: cmi.chatgroup.2

  # ATTENTION! Dont use gradient colors for {message} variable, if you want to apply gradient for it, utilize GroupMessageFormat section
  GroupFormat:
    '1': '&f[&8Guest&f]{prefix}{#AAAAAA}{displayName}&f: &7{suffix}{message}'
    '2': '&f[&8Mi&7ner&f]{prefix}{#AAAAAA}{displayName}&f: &7{suffix}{message}'
    '3': '&f[&7Ex&8pl&7or&8er&f]{prefix}{#AAAAAA}{displayName}&f: &7{suffix}{message}'
    '4': '&f[Citizen]{prefix}{#AAAAAA}{displayName}&f: &7{suffix}{message}'
    '5': '&f[&fEl&7ite&f]{prefix}{#AAAAAA}{displayName}&f: &7{suffix}{message}'
    '6': '&f[&aVIP&f]{prefix}{#55FF55}{displayName}&f: &6{suffix}{message}'
    '7': '&f[&6&lVIP&4&l+&f]{prefix}{#00AA00}{displayName}&f: &6{suffix}{message}'
    '8': '&f[&dGuide&f]{prefix}{#FFFF55}{displayName}&f: &9{suffix}{message}'
    '9': '&f[&dPre&9Mod&f]{prefix}{#e64545>}{displayName}{#e66245<}&f: &c{suffix}{message}'
    '10': '&f[&9Mod&f]{prefix}{#e60000>}{displayName}{#e66117<}&f: &c{suffix}{message}'
    '11': '&f[&5Mod&4+&f]{prefix}{displayName}&f: &c{suffix}{message}'
    '12': '&f[{#5995c9}&lC{#34c1e0}&lo{#07f6fa}&lu{#0fedf6}&ln{#2ccae4}&lc{#4aa7d2}&li{#5995c9}&ll&f]{prefix}&b{displayName}&f:
      &3{suffix}{message}'
    '13': '&f[{#5995c9}&lELEMENT&f]{prefix}&b{displayName}&f: {#5995c9}{suffix}{message}'
    '14': '&f[&6&lPotato&f]{prefix}&6{displayName}&f:&9 {suffix}{message}'
    '15': '&f[&5&lCouncil&f]{prefix}&b{displayName}&f:&4 {suffix}{message}'
  # Use numeric increments to separate groups from each other. If player has more than one, then line with higher number will be used
  # Add as many lines as you need too
  # cmi.chatmessagegroup.[id] permnission node to use
  # Permission example: cmi.chatmessagegroup.2
  GroupMessageFormat:
    '1': '{message}'
    '2': '{message}'
    '3': '{message}'
  Colors:
    # If set to true then all public messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.publicmessage.[colorName]
    # Colors: black(&0), darkblue(&1), darkgreen(&2), darkaqua(&3), darkred(&4), darkpurple(&5), gold(&6), gray(&7), darkgray(&8), blue(&9), green(&a), aqua(&b), red(&c), lightpurple(&d), yellow(&e), white(&f), magic(&k), bold(&l), strikethrough(&m), underline(&n), italic(&o), reset(&r)
    PublicMessage: true
    PrivateMessage: true
    # If set to true then /me messages will be filtered from color codes and will allow to colorize them with appropriate permission node
    # cmi.colors.me.[colorName]
    me: true
    # If set to true, then color codes will get removed from text instead of leaving them if player dont have appropriate permission node for that color
    CleanUp:
      publicmessage: true
      privatemessage: true
      me: true
      signs: false
      books: false
      itemname: true
      itemlore: true
      # List of strings to ignore when checking chat for color codes player cant use.
      # This will bypass players colorcode restrictions and will allow usage of particular chat formats
      # Applies only for public and private messages
      WhiteList:
      - '&c❤&7'
    # If set to true then nickName will be filtered from color codes when player changes it
    # cmi.colors.nickname.[colorName]
    NickName: true
  # If set to true, players public message who is in your ignore list will not be shown
  IgnorePublicMessage: true
  Tag:
    # Enable or not tag system. This will inform player with his name mentioning in public chat if name have @ in front of it
    Enabled: false
    # When this is set to true, any player mentionings in public messages will be colorized and player will get informed as usual
    # This is allot more heavier on server than usual tagging with @, so enable if you know what you are doing
    HardCoreMode: false
    # Determines color of taged user name in chat with @ in front of name/nickname. Sender should have cmi.tag.color
    Color: '&c'
    # Commands to be performed when player is tagged
    # Variables like [playerName] will be replaced with tagged player name
    # You can use [senderName] to include player name who tagged
    CommandsOnTag:
    - asConsole! cmi sound BLOCK_NOTE_HARP:3:1 [playerName] -s
    - asConsole! cmi sound BLOCK_NOTE_HARP:3:1 [playerName] -s
    # Will performd tag commands only when player is afk
    OnlyWhenAfk: false
    # When set to true, @ simbol will be removed
    RemoveEta: false
```

### Agreements

- [X] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by DoubleYouCash** [comment]
I was able to test with 1.19.4 and see that this issue is no longer occuring as far as I can tell.
