### ISSUE TITLE
Double Chat + Error - v9.5.0.4

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#7749]
### Description of Issue

Every chat message is shown twice in-game and a (double) error appears on the console per player message sent

### Version Information

```shell
CMI: 9.5.0.4 BungeeCord CMIB SqLite
CMILib: 1.2.5.2
Server: Purpur 1.19.4-R0.1-SNAPSHOT
CMI economy: EnabledVault: 1.7.3-b CMI Chat: Enabled
Modules -> 25 enabled 33 disabled: cuffed, mirror, tablist, versionCheck, armorEffects, moneyCheque, noTarget, elytraBoost, eventCommands, rideAnimation, elytraLaunch, coloredArmor, playerCombat, votifier, cooldown, attachedCommands, spawnerCharge, interactiveCommands, namePlates, launchPad, armorstand, portals, holograms, jail, dynamicSigns, playerChatTag, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, ranks, selection, warmup
```

### Errors

```shell
[07:56:59] [Async Chat Thread - #5/ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v9.5.0.4
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.destroy(org.bukkit.entity.Player)" because "this.tDisplay" is null
	at com.Zrips.CMI.Modules.Chat.CMIChatBubble.initialRecheckReceivers(CMIChatBubble.java:113) ~[CMI-9.5.0.4.jar:?]
	at com.Zrips.CMI.Modules.Chat.CMIChatBubble.<init>(CMIChatBubble.java:39) ~[CMI-9.5.0.4.jar:?]
	at com.Zrips.CMI.Modules.Chat.ChatBubbleManager.showBubble(ChatBubbleManager.java:92) ~[CMI-9.5.0.4.jar:?]
	at com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:202) ~[CMI-9.5.0.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor639.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1953]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2487) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2643) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$18(ServerGamePacketListenerImpl.java:2321) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:56:59] [Async Chat Thread - #5/ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v9.5.0.4
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.destroy(org.bukkit.entity.Player)" because "this.tDisplay" is null
	at com.Zrips.CMI.Modules.Chat.CMIChatBubble.initialRecheckReceivers(CMIChatBubble.java:113) ~[CMI-9.5.0.4.jar:?]
	at com.Zrips.CMI.Modules.Chat.CMIChatBubble.<init>(CMIChatBubble.java:39) ~[CMI-9.5.0.4.jar:?]
	at com.Zrips.CMI.Modules.Chat.ChatBubbleManager.showBubble(ChatBubbleManager.java:92) ~[CMI-9.5.0.4.jar:?]
	at com.Zrips.CMI.Modules.Chat.ChatBubbleListener.AsyncPlayerChatEvent(ChatBubbleListener.java:24) ~[CMI-9.5.0.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor458.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1953]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[purpur-1.19.4.jar:git-Purpur-1953]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2487) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2643) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$18(ServerGamePacketListenerImpl.java:2321) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Relevant Config Sections

```yaml
Player:
  Options:
    Defaults:
      chatbubble: true
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Darkseno** [comment]
Same problem here ! on my side I put the chatbuble on false and I had no more error and double message BUT the factions are not displayed correctly in the chat

**Comment by andy3559167** [comment]
Same problem

**Comment by mrfloris** [comment]
Can confirm, had this too, temp solution is to replace .4 with .3 jar of cmi. 
I've poked zrips, hopefully he has time friday before eaeter weekend.

**Comment by CloudeLecaw** [comment]
an other option that helped many was disabling the chat Chatbubble in chat.yml with 9.5.0.4

**Comment by x1p** [comment]
> an other option that helped many was disabling the chat Chatbubble in chat.yml with 9.5.0.4

Eh unfortunately: no.
I decided to update (again) to 9.5.0.4 and disable ChatBubbles via the Modules file but the error keeps appearing.
So it seems that disabling the ChatBubble module doesn't even disable ChatBubbles entirely.

**Comment by CloudeLecaw** [comment]
maybe
We never said "disable it in modules.yml"
we said "disable it in chat.yml!"

**Comment by CloudeLecaw** [comment]
> maybe
> We never said "disable it in modules.yml"
> we said "disable it in chat.yml!"

maybe
We never said "disable it in modules.yml"
we said "disable it in chat.yml!"  

But our right.. it should be disabled completl if disbled in modules.yml   but for not disable it in chat.yml ;)

**Comment by CloudeLecaw** [comment]
> maybe We never said "disable it in modules.yml" we said "disable it in chat.yml!"
> 
> But our right.. it should be disabled completl if disbled in modules.yml but for not disable it in chat.yml ;)

maybe
We never said "disable it in modules.yml"
we said "disable it in chat.yml!"

But our right.. it should be disabled completl if disbled in modules.yml but for not disable it in chat.yml ;)

**Comment by Zrips** [comment]
Should be fixed with .5 update
