### ISSUE TITLE
incompatible with Paper 1.13.1

### ISSUE THREAD

**Issue by kemmeo** [Zrips/CMI#775]
**Description of issue or feature request:**

The plugin disables itself on 1.13.1

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
27.08 06:30:21 [Server] INFO [CMI] Enabling CMI v8.0.6.0
27.08 06:30:21 [Server] INFO Your server version is not compatible with this plugins version! Plugin will be disabled: v1_13_R2
27.08 06:30:21 [Server] ERROR Error occurred while enabling CMI v8.0.6.0 (Is it up to date?)
27.08 06:30:21 [Server] INFO org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
27.08 06:30:21 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:488) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:150) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:146) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at com.Zrips.CMI.Modules.Afk.AfkManager.tasker(AfkManager.java:134) ~[?:?]
27.08 06:30:21 [Server] INFO at com.Zrips.CMI.Modules.Afk.AfkManager.<init>(AfkManager.java:25) ~[?:?]
27.08 06:30:21 [Server] INFO at com.Zrips.CMI.CMI.getAfkManager(CMI.java:770) ~[?:?]
27.08 06:30:21 [Server] INFO at com.Zrips.CMI.CMI.onDisable(CMI.java:1150) ~[?:?]
27.08 06:30:21 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at com.Zrips.CMI.CMI.onEnable(CMI.java:1212) ~[?:?]
27.08 06:30:21 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:576) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:433) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:784) ~[patched_1.13.1.jar:git-Paper-180]
27.08 06:30:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Cmi Version (using`/cmi version`):**
CMI version: 8.0.7.0 

**Server Type (Spigot/Paperspigot/etc):** 
Paper(Spigot)

**Server Version (using `/ver`):** 
Minecraft 1.13.1

**Comment by CloudeLecaw** [comment]
Doublepost: this issues is reported 3 threads ago allready. Pls keep your eyes open next time.
https://github.com/Zrips/CMI/issues/771

**Comment by CloudeLecaw** [comment]
by the way.. did you really use PaperSpigot?
27.08 06:30:21 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:488) ~[patched_1.13.1.jar:git-Paper-180]….
Looks more like a PaperClip Version :3

**Comment by kemmeo** [comment]
Its called Paper...
PaperClip is the patcher they use to avoid distributing code that could get them in legal trouble.

**Comment by the456gamer** [comment]
Ok then, sorry for the mistake

**Comment by cdmvirt** [comment]
its not just paper, so title needs to be updated - spigot 1.13.1 (MC 1.13R2)

**Comment by kemmeo** [comment]
Just reporting what I tested. But yeah, it stands to reason that any Bukkit derivative would have the same problem..
