### ISSUE TITLE
NullPointerException Error in CMI ChatBubbleManager

### ISSUE THREAD

**Issue by jason920612** [Zrips/CMI#7753]
### Description of Issue

Encountering a NullPointerException error related to the ChatBubbleManager in CMI plugin. The error occurs when attempting to invoke a method on a null object (this.tDisplay).

### Version Information

```shell
[17:45:13 INFO]: --------------------------------------------------
[17:45:13 INFO]: CMI 插件版本: 9.5.0.4 SqLite
[17:45:13 INFO]: CMILib: 1.2.5.2
[17:45:13 INFO]: 伺服器: Paper(478) 1.19.4-R0.1-SNAPSHOT
[17:45:13 INFO]: CMI economy: 啟用 Vault: 1.7.3-CMI CMI 聊天: 禁用
[17:45:13 INFO]: 模塊 -> 57 已開起 1 已關閉: votifier
[17:45:13 INFO]: --------------------------------------------------
```

### Errors

```shell

[17:40:32 ERROR]: Could not pass event AsyncPlayerChatEvent to CMI v9.5.0.4
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.destroy(org.bukkit.entity.Player)" because "this.tDisplay" is null
        at com.Zrips.CMI.Modules.Chat.CMIChatBubble.initialRecheckReceivers(CMIChatBubble.java:113) ~[CMI-9.5.0.4.jar:?]
        at com.Zrips.CMI.Modules.Chat.CMIChatBubble.<init>(CMIChatBubble.java:39) ~[CMI-9.5.0.4.jar:?]
        at com.Zrips.CMI.Modules.Chat.ChatBubbleManager.showBubble(ChatBubbleManager.java:92) ~[CMI-9.5.0.4.jar:?]
        at com.Zrips.CMI.Modules.Chat.ChatBubbleListener.AsyncPlayerChatEvent(ChatBubbleListener.java:24) ~[CMI-9.5.0.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor298.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-478]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-478]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-478]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[paper-1.19.4.jar:git-Paper-478]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[paper-1.19.4.jar:git-Paper-478]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2385) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2541) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2220) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
can be closed becaused of duplication from this
https://github.com/Zrips/CMI/issues/7749

**Comment by Zrips** [comment]
Should be fixed with .5 update
