### ISSUE TITLE
CMI Crashing & lagging server with PM

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#777]
**Description of issue or feature request:**
I am using venturechat. When a player PMs another player /msg it showed this error in chat  Async with thread: Craft Scheduler Thread - 53

Then I received lag & my TPS dropped from 20TPS to 19TPS constant. Now all of my custom alias's are broken as well. A large error appeared in chat below.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
> [04:25:02 INFO]: Royaltiies issued server command: /msg Equalled hey
> [04:25:05 INFO]: Royaltiies issued server command: /vmessage Equalled hey
> [04:25:06 WARN]: Royaltiies moved too quickly! -14.24136481192977,7.5,0.9061493492483805
> [04:25:06 WARN]: TCC moved too quickly! -15.720496007141264,-0.6319031399820005,-4.11576331592255
> [04:25:12 INFO]: [MysqlPlayerDataBridge] Saving online players data...
> [04:25:14 INFO]: [MysqlPlayerDataBridge] Data save complete for 3 players in 2040 ms.
> [04:25:18 INFO]: Royaltiies issued server command: /r i asvdfavsd
> [04:25:26 INFO]: Royaltiies issued server command: /r words
> [04:25:42 INFO]: TCC issued server command: /kick royaltiies
> [04:25:42 INFO]: Royaltiies lost connection: §7
§5§lWatchdog §8§l» §fYou were kicked.
§7
§5Reason §8» §7No Reason Specified
§7
> [04:25:42 WARN]: handleDisconnection() called twice
> [04:25:47 INFO]: UUID of player Royaltiies is eae7ec24-8eb2-48b8-a326-15c7806b687d
> [04:25:48 INFO]: Royaltiies[/96.55.184.33:36656] logged in with entity id 826947 at ([spawnworld]-2041.2116246086837, 94.04289683901332, -1719.6206076991966)
> [04:25:48 INFO]: Async with thread: Craft Scheduler Thread - 53
> [04:25:50 INFO]: TCC issued server command: /op royaltiies
> [04:26:07 INFO]: Royaltiies issued server command: /particles
> [04:26:07 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.7.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'bs' in plugin BossShopPro v1.9.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
Caused by: java.lang.NullPointerException
at org.black_ixx.bossshop.managers.CommandManager.playerCommandOpenShop(CommandManager.java:195) ~[?:?]
at org.black_ixx.bossshop.managers.CommandManager.onCommand(CommandManager.java:169) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
> [04:26:11 INFO]: TCC issued server command: /particles
> [04:26:11 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.7.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'bs' in plugin BossShopPro v1.9.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
Caused by: java.lang.NullPointerException
at org.black_ixx.bossshop.managers.CommandManager.playerCommandOpenShop(CommandManager.java:195) ~[?:?]
at org.black_ixx.bossshop.managers.CommandManager.onCommand(CommandManager.java:169) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
> [04:26:12 INFO]: [MysqlPlayerDataBridge] Saving online players data...
> [04:26:15 INFO]: [MysqlPlayerDataBridge] Data save complete for 3 players in 2487 ms.
> [04:27:12 INFO]: [MysqlPlayerDataBridge] Saving online players data...
> [04:27:14 INFO]: [MysqlPlayerDataBridge] Data save complete for 3 players in 2005 ms.
> [04:27:54 INFO]: Royaltiies issued server command: /particles
> [04:27:54 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.7.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'bs' in plugin BossShopPro v1.9.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
Caused by: java.lang.NullPointerException
at org.black_ixx.bossshop.managers.CommandManager.playerCommandOpenShop(CommandManager.java:195) ~[?:?]
at org.black_ixx.bossshop.managers.CommandManager.onCommand(CommandManager.java:169) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
> [04:28:04 INFO]: TCC issued server command: /cmi
> [04:28:09 INFO]: TCC issued server command: /menu
> [04:28:09 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMI v8.0.7.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1389) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'bs' in plugin BossShopPro v1.9.8
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
Caused by: java.lang.NullPointerException
at org.black_ixx.bossshop.managers.CommandManager.playerCommandOpenShop(CommandManager.java:195) ~[?:?]
at org.black_ixx.bossshop.managers.CommandManager.onCommand(CommandManager.java:169) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:568) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:468) ~[?:?]
at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:77) ~[?:?]
at com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:61) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-latest.jar:git-Spigot-642f6d2-57ab4cf]
... 16 more
```

**Cmi Version (using`/cmi version`):**  8.0.7.0

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):**  1.12.2

**EDIT: Downgrading to CMI 8.0.4.0 fixed this issue, but I would like to use the latest.**

**Comment by Zrips** [comment]
Will be fixed with next build, tho it seems to originate from another plugin
