### ISSUE TITLE
Error whilst using /cmi scan r g h

### ISSUE THREAD

**Issue by Maftyyn** [Zrips/CMI#7806]
### Description of Issue

Hello so, im facing issue, where im trying to scan classic vanilla world in 1.16.5 server without any special generator.
Im using latest CMI & CmiLib

So basically.. when im scanning around 3.3mil chunks after few minutes im at 330K chunks scanned, everything is okay but after i reach around 400K it stops and throws me error i showed below.. if i try to scan some random item by putting it like 1K blocks away from me it normally works, but this world scanning is kinda not working for me and dont know what could causing it to scan 266 Y, please help me i would be grateful.

### Version Information

```shell
[02:20:18 INFO]: --------------------------------------------------
[02:20:18 INFO]: CMI plugin version: 9.5.0.8 BungeeCord SqLite
[02:20:18 INFO]: CMILib: 1.2.5.3
[02:20:18 INFO]: Server: Airplane 1.16.5-R0.1-SNAPSHOT
[02:20:18 INFO]: CMI economy: Disabled Vault: 1.7.1-b91 CMI Chat: Disabled
[02:20:18 INFO]: Modules -> 8 enabled 50 disabled: spawnerProximity, customMessages, moneyCheque, elytraBoost, eventCommands, bossBarCompass, coloredArmor, votifier, cooldown, headDrop, interactiveCommands, vanish, timedCommands, homeInteractions, launchPad, portals, jail, spawners, paintingEditor, dynamicSigns, playerChatTag, flightCharge, deathMessages, disabledEnchants, selection, sitAnimation, totemBehavior, cuffed, mirror, tablist, versionCheck, skin, noTarget, cmiPlaytime, rideAnimation, elytraLaunch, playerCombat, attachedCommands, spawnerCharge, armorstand, afk, anvilRenameColor, durabilityLoss, kits, schedule, worldLimitsElytra, worldLimits, firstJoinMessages, silentChest, warmup
[02:20:18 INFO]: --------------------------------------------------
```

### Errors

```shell
02:16:45 WARN]: [CMI] Task #27205 for CMI v9.5.0.8 generated an exception
java.lang.IllegalArgumentException: y out of range (expected 0-255, got 256)
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at org.bukkit.craftbukkit.v1_16_R3.CraftChunk.validateChunkCoordinates(CraftChunk.java:363) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at org.bukkit.craftbukkit.v1_16_R3.CraftChunk.getBlock(CraftChunk.java:100) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at com.Zrips.CMI.Modules.Scan.Scan$1.run(Scan.java:160) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1494) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-"bcf74e2"]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Relevant Config Sections

```yaml
Dont know any which could cause this, ask me more details if u need to.
```

### Relevant Plugins

Vault 1.7.1-b91

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Maftyyn** [comment]
When i do /scan continue its continue where it ended last time, which seems fine but its saying 2 900 424 chunks left (0 seconds) the chunks are moving so lets see what happends, but dont seem really as it should be.

**Comment by Zrips** [comment]
Will be fixed with next update
