### ISSUE TITLE
Hologram Warns

### ISSUE THREAD

**Issue by beeng9** [Zrips/CMI#781]
**Description of issue or feature request:**
When I place the hologram, This logs are appeal very oftenly

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## [01:40:11] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set boolean field net.minecraft.server.v1_11_R1.EntityArmorStand.bB to java.lang.Integer
[01:40:11] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[01:40:11] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
[01:40:11] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.UnsafeBooleanFieldAccessorImpl.set(Unknown Source)
[01:40:11] [Server thread/WARN]: 	at java.base/java.lang.reflect.Field.set(Unknown Source)
[01:40:11] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_11_R1.createStand(v1_11_R1.java:1385)
[01:40:11] [Server thread/WARN]: 	at com.Zrips.CMI.NBT.v1_11_R1.spawnHologram(v1_11_R1.java:1394)
[01:40:11] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.Holograms.CMIHologram$1$1.run(CMIHologram.java:243)
[01:40:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[01:40:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[01:40:11] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
[01:40:11] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[01:40:11] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[01:40:11] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[01:40:11] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source) ##
####################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

**Cmi Version (using`/cmi version`):** 
8.0.7.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
This server is running CraftBukkit version git-Spigot-f950f8e-0a81101 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Next version should have this one fixed
