### ISSUE TITLE
Home error

### ISSUE THREAD

**Issue by 1ntent1on** [Zrips/CMI#7819]
### Description of Issue

Hello, get this error after player used /home, its Bedrock player (ik that Bedrock isnt completely supported by CMI, but it never happened before)

### Version Information

```shell
[22:24:23 INFO]: CMI plugin version: 9.5.0.8 SqLite-> 9.5.0.9
[22:24:23 INFO]: CMILib: 1.2.5.3 
[22:24:23 INFO]: Server: PufferfishPlus 1.19.4-R0.1-SNAPSHOT
[22:24:23 INFO]: CMI economy: enabled Vault: 1.7.3-CMI CMI Chat: enabled
[22:24:23 INFO]: Modules -> 34 enabled 24 disabled: cuffed, mirror, launchPad, tablist, armorstand, versionCheck, armorEffects, moneyCheque, skin, noTarget, jail, paintingEditor, dynamicSigns, playerChatTag, bossBarCompass, coloredArmor, deathMessages, ranks, votifier, shulkerBackpack, attachedCommands, spawnerCharge, vanish, timedCommands
```

### Errors

```shell
[21:58:51 WARN]: java.util.NoSuchElementException
[21:58:51 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap$ValueIterator.next(ConcurrentHashMap.java:3480)
[21:58:51 WARN]:        at CMI-9.5.0.8.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.getLinesByPlayerPage(CMIHologram.java:306)
[21:58:51 WARN]:        at CMI-9.5.0.8.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$2(CMIHologram.java:1297)
[21:58:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run()
[21:58:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run()
[21:58:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()
[21:58:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[21:58:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[21:58:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Small issue with holograms which doesn't have set hologram text lines. Should be resolved with next update.
