### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by jieunhyo** [Zrips/CMI#7823]
Errors are periodically output to the console. What's the reason? Can you fix it?

[20:44:16 WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap$ValueIterator.next(ConcurrentHashMap.java:3480)
[20:44:16 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.getLinesByPlayerPage(CMIHologram.java:306)
[20:44:16 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$2(CMIHologram.java:1297)
[20:44:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[20:44:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:44:16 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:44:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:44:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:44:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by CloudeLecaw** [comment]
can you post your Holograms.yml may a pastebin?
