### ISSUE TITLE
Severe save error while resetting money

### ISSUE THREAD

**Issue by ChanceSD** [Zrips/CMI#7829]
### Description of Issue

While trying to reset everyone's money to 100 (money set alloffline 100) I get this error for some players related to them being jailed I guess.
After running the command it shows everyone's balance in the /baltop as 100 as it should, however after a server restart a bunch of players are back with their previous balance.

### Version Information

```shell
CMI: 9.5.0.9 SqLite
CMILib: 1.2.5.3 
Server: Paper(524) 1.19.4-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Enabled 
Modules -> 56 enabled 2 disabled: playerCombat, votifier
```

### Errors

```shell
[CMI]  SEVERE SAVE ERROR WHILE SAVING Hak PLAYER DATA (Jail)
[17:20:51 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Jail.CMIJailCell.getJail()" because the return value of "com.Zrips.CMI.Containers.CMIUser.getCell()" is null
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1091)
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:709)
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:481)
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:345)
[17:20:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:20:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:20:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:20:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[17:20:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[17:20:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[17:20:51 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Jail.CMIJailCell.getJail()" because the return value of "com.Zrips.CMI.Containers.CMIUser.getCell()" is null
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:1091)
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:709)
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:481)
[17:20:51 WARN]:        at CMI-9.5.0.9.jar//com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:345)
[17:20:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[17:20:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:20:51 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:20:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[17:20:51 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[17:20:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Got fixed in recent updates
