### ISSUE TITLE
cmi info nouser

### ISSUE THREAD

**Issue by kireevm96** [Zrips/CMI#7872]
### Description of Issue

[00:46:46 INFO]: Kireevm issued server command: /cmi info nouser
[00:46:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.5.1.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[ssspigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[ssspigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[ssspigot-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2267) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:198) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[ssspigot-1.19.4.jar:SSSpigot2-1.19.4-20230515-01d34cb]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.CMIUser.isOnline()" because "<local8>" is null
        at com.Zrips.CMI.CMI.getUser(CMI.java:1982) ~[CMI-9.5.1.3.jar:?]
        at com.Zrips.CMI.CMI.getUser(CMI.java:1972) ~[CMI-9.5.1.3.jar:?]
        at com.Zrips.CMI.CMI.getTarget(CMI.java:1949) ~[CMI-9.5.1.3.jar:?]
        at com.Zrips.CMI.CMI.getTarget(CMI.java:1945) ~[CMI-9.5.1.3.jar:?]
        at com.Zrips.CMI.CMI.getTarget(CMI.java:1933) ~[CMI-9.5.1.3.jar:?]
        at com.Zrips.CMI.commands.list.info.perform(info.java:162) ~[CMI-9.5.1.3.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:399) ~[CMI-9.5.1.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[ssspigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 23 more

### Version Information

```shell
cmi 9.5.1.3
CMILib: 1.2.5.5
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Updating to latest CMI version should resolve this issue for you
