### ISSUE TITLE
The enchantment recovery is not compatible with other enchantment plugins and cannot be used.

### ISSUE THREAD

**Issue by NEIKI19914** [Zrips/CMI#7904]
### Description of Issue

I see other server administrators in 1.18 does not seem to have problems, and support more enchantment-related plug-in recycling.
More enchantment plugins I use are EcoEnchants v10.20.1.

### Version Information

```shell
CMI 插件版本: 9.6.0.4 BungeeCord CMIB  MySQL
CMILib: 1.3.0.3 
服务器版本: Pufferfish 1.20.1-R0.1-SNAPSHOT
CMI 经济: 启用 经济: 1.7.3-b131(CMIEInjector) CMI 聊天: 启用 
模块 -> 56 已启用 2 已禁用: tablist, votifier
```

### Errors

```shell
[08:22:27 INFO]: NEIKI issued server command: /cmi scavenge
[08:22:28 WARN]: [CMI] Task #19660 for CMI v9.6.0.4 generated an exception
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at com.Zrips.CMI.Modules.Scavenger.CMIScavengeItem.getIngredients(CMIScavengeItem.java:207) ~[CMI-9.6.0.4.jar:?]
        at com.Zrips.CMI.Modules.Scavenger.CMIScavengeItem.getIngredients(CMIScavengeItem.java:181) ~[CMI-9.6.0.4.jar:?]
        at com.Zrips.CMI.Modules.Scavenger.CMIScavengeItem.canScavenge(CMIScavengeItem.java:58) ~[CMI-9.6.0.4.jar:?]
        at com.Zrips.CMI.Modules.Scavenger.ScavengeManager.updateExtractor(ScavengeManager.java:279) ~[CMI-9.6.0.4.jar:?]
        at com.Zrips.CMI.Modules.Scavenger.ScavengeManager.updateExtractor(ScavengeManager.java:258) ~[CMI-9.6.0.4.jar:?]
        at com.Zrips.CMI.Modules.Scavenger.ScavengeManager.access$1(ScavengeManager.java:257) ~[CMI-9.6.0.4.jar:?]
        at com.Zrips.CMI.Modules.Scavenger.ScavengeManager$1$1.run(ScavengeManager.java:207) ~[CMI-9.6.0.4.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-8]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[pufferfish-1.20.1.jar:git-Pufferfish-8]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1482) ~[pufferfish-1.20.1.jar:git-Pufferfish-8]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.20.1.jar:git-Pufferfish-8]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[pufferfish-1.20.1.jar:git-Pufferfish-8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[pufferfish-1.20.1.jar:git-Pufferfish-8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.1.jar:git-Pufferfish-8]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update. If issue persists let me know.
