### ISSUE TITLE
Console error when you have too much mail

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#7917]
### Description of Issue

When a player has  too long of total messages and receives a mail that pushes them over the limit, using MariaDB for storage, there is a console error due to the field being too long to store.  Perhaps this could be fixed simply by truncating the mail list before sending to the db, or by checking the length and sending an error to the sender that the mailbox is full rather than trying to send it.

Note, some of this is guessing at the cause, but the error appears when I send a long message (testing from console) to a player with a very full mailbox.   It occurred due to messages piling up from a test of the scheduling issue and had the server cmi mailing me long messages frequently on my test server, but I can easily see this happening with intentional mail spam in game.

### Version Information

```shell
[17:20:51 INFO]: --------------------------------------------------
[17:20:51 INFO]: CMI plugin version: 9.6.0.6 MySQL
[17:20:51 INFO]: CMILib: 1.3.0.3 
[17:20:51 INFO]: Server: Paper(43) 1.20.1-R0.1-SNAPSHOT
[17:20:51 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[17:20:51 INFO]: Modules -> 50 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[17:20:51 INFO]: --------------------------------------------------
```

### Errors

```shell
[17:19:17 WARN]: java.sql.BatchUpdateException: Data truncation: Data too long for column 'Mail' at row 1
[17:19:17 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
[17:19:17 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:816)
[17:19:17 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:418)
[17:19:17 WARN]:        at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:795)
[17:19:17 WARN]:        at CMI-9.6.0.6.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.executeTempBatch(DBDAO.java:896)
[17:19:17 WARN]:        at CMI-9.6.0.6.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:522)
[17:19:17 WARN]:        at CMI-9.6.0.6.jar//com.Zrips.CMI.Modules.DataBase.DBManager$1$1.run(DBManager.java:345)
[17:19:17 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:19:17 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:19:17 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:19:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[17:19:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[17:19:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:19:17 WARN]: Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'Mail' at row 1
[17:19:17 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
[17:19:17 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[17:19:17 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
[17:19:17 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:795)
[17:19:17 WARN]:        ... 11 more
```

### Relevant Config Sections

```yaml
I'm not sure what would be relevant, other than that I am using MariaDB for storage.
```

### Relevant Plugins

N/A

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will introduce some changes and some general limitations how many mails user can have at one time to avoid issue like this one with future updates.
