### ISSUE TITLE
Launch cmi warning and player login session warning

### ISSUE THREAD

**Issue by aml2023529** [Zrips/CMI#7939]
### Description of Issue

My cmi will show this warning every time he starts I don't know why I bought it through spigotmc and the player login will also show the following warning I don't know how to solve it I have gone to the discordant server and asked them to let me come to you

### Version Information

```shell
> cmi version
[02:56:17 INFO]: --------------------------------------------------
[02:56:17 INFO]: CMI 插件版本: 9.6.0.9 SqLite
[02:56:17 INFO]: CMILib: 1.3.1.1
[02:56:17 INFO]: 服务器版本: Paper(65) 1.20.1-R0.1-SNAPSHOT
[02:56:17 INFO]: CMI 经济: 启用 经济: 1.7.3-b131(CMIEInjector) CMI 聊天: 启用
[02:56:17 INFO]: 模块 -> 54 已启用 4 已禁用: mirror, tablist, ranks, votifier
[02:56:17 INFO]: --------------------------------------------------
>
```

### Errors

```shell
[02:46:58 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[02:46:58 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[02:46:58 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃
[02:46:58 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃
[02:46:58 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[02:46:58 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[02:46:58 INFO]: _______________________________________________________
[02:46:58 INFO]:   Integrating PaperSpigot async methods
[02:46:58 INFO]:   55 Enabled and 3 Disabled modules
[02:46:59 INFO]:   Permission plugin: LuckPerms5.4.89
[02:46:59 INFO]:   Initialized Cipher256 AES
[02:46:59 INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared will fetch UUIDs in groups of 200
[02:46:59 INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared has cached 100.0% of UUIDs
[02:46:59 INFO]: [PlotSquared/BukkitPlatform] (UUID) PlotSquared has cached all UUIDs
[02:46:59 INFO]:   Loaded (61) regular alias into memory. Took 53ms
[02:46:59 INFO]:   Loaded (1) custom text's into memory. Took 9ms
[02:46:59 INFO]:   3.42.0 data base type detected
[02:46:59 INFO]:   Started SqLite data base. Took 201ms
[02:46:59 INFO]:   Vault was found - Enabling capabilities. Economy: CMIEconomy
[02:46:59 INFO]:   Loaded (3) holograms into memory. Took 32ms
[02:47:00 INFO]:   Loaded (5) warning categories into memory. Took 0ms
[02:47:00 INFO]:   Loaded (3) warning commands into memory. Took 0ms
[02:47:00 INFO]:   Loaded (144) custom mob heads into memory. Took 28ms
[02:47:00 INFO]:   Loaded (2) cooldowns into memory. Took 45ms
[02:47:00 INFO]:   Loaded (4) warmups into memory. Took 0ms
[02:47:00 INFO]:   Initializing BungeeCord
[02:47:00 INFO]:   Loaded (4) kits into memory. Took 25ms
[02:47:00 INFO]:   Loaded (7) ranks into memory. Took 20ms
[02:47:00 INFO]:   Loaded (8) playtime rewards into memory. Took 11ms
[02:47:00 INFO]:   Loaded (71) player data into memory. Took 35ms
[02:47:00 INFO]:   Loaded (0) playtime records into memory. Took 0ms
[02:47:00 INFO]:   Loaded (0) playtime reward records into memory. Took 0ms
[02:47:00 INFO]:   Loaded (0) custom alias into memory. Took 9ms
[02:47:00 INFO]:   Registered events. Took 118ms
[02:47:00 INFO]:   Loaded (1) jails into memory. Took 9ms
[02:47:00 INFO]:   Loaded (0) event action commands into memory. Took 12ms
[02:47:00 INFO]:   Updated (EN) language file. Took 118ms
[02:47:00 INFO]:   Updated (CN) language file. Took 81ms
[02:47:00 WARN]: java.lang.NumberFormatException: empty String
[02:47:00 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
[02:47:00 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[02:47:00 WARN]:        at java.base/java.lang.Double.parseDouble(Double.java:792)
[02:47:00 WARN]:        at [基础]CMI-9.6.0.9.jar//com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:236)
[02:47:00 WARN]:        at [基础]CMI-9.6.0.9.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1668)
[02:47:00 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[02:47:00 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[02:47:00 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[02:47:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[02:47:00 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:639)
[02:47:00 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:550)
[02:47:00 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[02:47:00 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[02:47:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[02:47:00 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[02:47:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[02:47:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[02:47:00 INFO]:   Failed to load worth for: QUARTZ_BLOCK
[02:47:00 INFO]:   Loaded (248) worth values into memory. Took 108ms
[02:47:00 INFO]:   Loaded (7) warps into memory. Took 9ms
[02:47:00 INFO]:   Vault permissions was found - Enabling capabilities.
[02:47:00 INFO]: [PlaceholderAPI] Successfully registered expansion: cmi [9.6.0.9]
[02:47:00 INFO]:   PlaceholderAPI hooked.
[02:47:00 INFO]:   PlaceholderAPI was found - Enabling capabilities.
[02:47:00 INFO]:   McMMO was found - Enabling capabilities.
[02:47:00 INFO]:   Initializing world manager.
[02:47:00 INFO]:   Loaded (5) schedules into memory. Took 18ms
[02:47:00 INFO]:   Loaded GeoIP
[02:47:00 INFO]:   Loaded (3) holograms into memory. Took 4ms
[02:47:00 INFO]:   Loaded (44) skin cache entries into memory. Took 12ms
[02:47:00 INFO]:   Loaded (0) ArmorStand templates into memory. Took 0ms
[02:47:00 INFO]:   Version 9.6.0.9 has been enabled

[02:47:50 INFO]: Dawn >>> 欢迎 yansheng 加入游戏
[02:47:50 INFO]: yansheng[/182.243.195.233:24982] logged in with entity id 270 at ([sc]623.8887499634193, 72.0, 1074.0166405134614)
[02:47:57 INFO]: [Authy] Player yansheng logged in with ip 182.243.195.233 and UUID e0ed582d-3440-309e-a125-b0a901517a57
[02:47:57 WARN]: java.net.SocketException: Connection reset
[02:47:57 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:313)
[02:47:57 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340)
[02:47:57 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789)
[02:47:57 WARN]:        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1025)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:477)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[02:47:57 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[02:47:57 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:587)
[02:47:57 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[02:47:57 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
[02:47:57 WARN]:        at [基础]CMI-9.6.0.9.jar//com.Zrips.CMI.utils.PrevNamesFetcher.getUUID(PrevNamesFetcher.java:199)
[02:47:57 WARN]:        at [基础]CMI-9.6.0.9.jar//com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:94)
[02:47:57 WARN]:        at [基础]CMI-9.6.0.9.jar//com.Zrips.CMI.Modules.Skin.SkinListener$1$1.run(SkinListener.java:37)
[02:47:57 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[02:47:57 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:47:57 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:47:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[02:47:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[02:47:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[02:48:00 INFO]: UUID of player ge_jsxl is e0fee190-9b32-37d0-9fd0-5648d3c52d5d
[02:48:01 INFO]: Dawn >>> 欢迎 ge_jsxl 加入游戏
```

### Relevant Plugins

1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You can ignore second error, but will hide it from now on. For the first one, will fix issue with it, tho double check your worth file for the lines which are empty and doesn't provide worth for the items, you can remove those entirely. Either way, should be fixed with next update
