### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7940]
### Description of Issue

Hi, I've noticed the error in the console.

### Version Information

```shell
[16:52:14 INFO]: --------------------------------------------------
[16:52:14 INFO]: CMI: 9.6.1.0 MySQL-> 9.6.0.9
[16:52:14 INFO]: CMILib: 1.3.1.2 
[16:52:14 INFO]: Server: Purpur 1.19.4-R0.1-SNAPSHOT
[16:52:14 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[16:52:14 INFO]: Modules -> 46 enabled 12 disabled: deathMessages, disabledEnchants, customMessages, mirror, tablist, ranks, firstJoinMessages, playerCombat, votifier, skin, namePlates, playerChatTag
```

### Errors

```shell
[16:51:01 WARN]: java.util.ConcurrentModificationException
[16:51:01 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[16:51:01 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:65)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[16:51:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:51:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:51:01 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:51:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:51:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:51:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:51:01 WARN]: java.util.ConcurrentModificationException
[16:51:01 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[16:51:01 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:65)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[16:51:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:51:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:51:01 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:51:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:51:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:51:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:51:01 WARN]: java.util.ConcurrentModificationException
[16:51:01 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[16:51:01 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:65)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[16:51:01 WARN]:        at CMI-9.6.1.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[16:51:01 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[16:51:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:51:01 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:51:01 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:51:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:51:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:51:01 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
