### ISSUE TITLE
InventoryClickEvent Error 9.6.1.0

### ISSUE THREAD

**Issue by SrT3ddy** [Zrips/CMI#7945]
### Description of Issue

It is showing "Could not pass event InventoryClickEvent to CMI v9.6.1.0" in the server console

### Version Information

```shell
[15:02:06 INFO]: CMI: 9.6.1.0 BungeeCord  MySQL
[15:02:06 INFO]: CMILib: 1.3.1.2 
[15:02:06 INFO]: Server: Mohist 1.12.2-R0.1-SNAPSHOT
[15:02:06 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled
```

### Errors

```shell
[14:58:28 ERROR]: Could not pass event InventoryClickEvent to CMI v9.6.1.0
 java.lang.NoSuchMethodError: org.bukkit.Material.isAir()Z
        at com.Zrips.CMI.AllListeners.PlayerListeners.hatPlacement(PlayerListeners.java:679) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor910.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2121) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with 9.6.1.1 version which got posted right now.
