### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#7966]
### Description of Issue

Hi, I receive this error in the console. I think it's related to this https://github.com/Zrips/CMI/issues/7940

### Version Information

```shell
[15:48:33 INFO]: CMI: 9.6.1.3 MySQL-> 9.6.1.2
[15:48:33 INFO]: CMILib: 1.4.0.1 
[15:48:33 INFO]: Server: Purpur 1.19.4-R0.1-SNAPSHOT
[15:48:33 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[15:48:33 INFO]: Modules -> 46 enabled 12 disabled: deathMessages, disabledEnchants, customMessages, mirror, tablist, ranks, firstJoinMessages, playerCombat, votifier, skin, namePlates, playerChatTag
```

### Errors

```shell
`
3:56 WARN]: java.util.ConcurrentModificationException
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:66)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:33:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:33:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:33:56 WARN]: java.util.ConcurrentModificationException
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:66)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:33:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:33:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:33:56 WARN]: java.util.ConcurrentModificationException
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:66)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:33:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:33:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:33:56 WARN]: java.util.ConcurrentModificationException
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:66)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:33:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:33:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:33:56 WARN]: java.util.ConcurrentModificationException
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:66)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:33:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:33:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:33:56 WARN]: java.util.ConcurrentModificationException
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:33:56 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:66)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[15:33:56 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[15:33:56 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:33:56 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:33:56 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:33:56 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:33:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
`

`
[15:46:43 WARN]: java.util.ConcurrentModificationException
[15:46:43 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
[15:46:43 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
[15:46:43 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologramPage.calculateWidth(CMIHologramPage.java:66)
[15:46:43 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updatePages(CMIHologram.java:345)
[15:46:43 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.update(CMIHologram.java:581)
[15:46:43 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.interfaces.externalhooks.holograms.cmi.ZripsHologramNew.c(ZripsHologramNew.java:35)
[15:46:43 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.holograms.DynamicHologram.a(DynamicHologram.java:45)
[15:46:43 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.crates.options.CHologram.f(CHologram.java:182)
[15:46:43 WARN]:        at SpecializedCrates-3.3.6.jar//me.PM2.customcrates.SpecializedCrates$3.run(SpecializedCrates.java:481)
[15:46:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[15:46:43 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:46:43 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:46:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:46:43 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:46:43 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
`
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
what you try to display in the hologram from SpecializedCrates?

**Comment by Zrips** [comment]
Will issue another fix for this one, looks like previous fix didn't had desired effect.
