### ISSUE TITLE
Jailed player info throws error (after server has restarted)

### ISSUE THREAD

**Issue by MC-MrBirdy** [Zrips/CMI#7967]
### Description of Issue

After a server restart the `/cmi jaillist` does not show who and how many players are jailed. When checking a jailed player with `/cmi info <player>` it does not show a jailed status and throws an error in the console.

Steps to reproduce:
1. Jail a player
2. Restart the server
3. Check the jaillist, it should now be empty
4. Check the players info, it should now no longer show a "jailed" tag
    Player info only shows: `| Banned Muted Cuffed Alert Chatroom`

Tested this on a fresh install of paper and CMI.

### Version Information

```shell
[20:32:20 INFO]: --------------------------------------------------
[20:32:20 INFO]: CMI: 9.6.1.3 SqLite-> 9.6.1.2
[20:32:20 INFO]: CMILib: 1.4.0.1
[20:32:20 INFO]: Server: Paper(81) 1.20.1-R0.1-SNAPSHOT
[20:32:20 INFO]: CMI economy: Disabled CMI Chat: Disabled
[20:32:20 INFO]: Modules -> 57 enabled 1 disabled: votifier
[20:32:20 INFO]: --------------------------------------------------
```

### Errors

```shell
[20:31:09 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Jail.CMIJailCell.getJail()" because "<local52>" is null
[20:31:09 WARN]:        at CMI-9.6.1.3.jar//com.Zrips.CMI.commands.list.info$1.lambda$0(info.java:366)
[20:31:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[20:31:09 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[20:31:09 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[20:31:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[20:31:09 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[20:31:09 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[20:31:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[20:31:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by MC-MrBirdy** [comment]
Problem seems to be solved with the latest update: 9.6.2.4
