### ISSUE TITLE
[Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v9.6.1.3

### ISSUE THREAD

**Issue by minercract** [Zrips/CMI#7974]
### Description of Issue

The error appears when server is starting.

### Version Information

```shell
9.6.1.3
```

### Errors

```shell
17.07 07:42:44 [Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v9.6.1.3
17.07 07:42:44 [Server] INFO java.util.UnknownFormatConversionException: Conversion = ' '
17.07 07:42:44 [Server] INFO at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:105) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
17.07 07:42:44 [Server] INFO at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:215) ~[CMI-9.6.1.3.jar:?]
17.07 07:42:44 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor394.execute(Unknown Source) ~[?:?]
17.07 07:42:44 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
17.07 07:42:44 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:git-Paper-17]
17.07 07:42:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
17.07 07:42:44 [Server] INFO at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.jar:git-Paper-17]
17.07 07:42:44 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.jar:git-Paper-17]
17.07 07:42:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
17.07 07:42:44 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[paper-1.20.jar:git-Paper-17]
17.07 07:42:44 [Server] INFO at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[paper-1.20.jar:git-Paper-17]
17.07 07:42:44 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2403) ~[?:?]
17.07 07:42:44 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2559) ~[?:?]
17.07 07:42:44 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$17(ServerGamePacketListenerImpl.java:2232) ~[?:?]
17.07 07:42:44 [Server] INFO at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
17.07 07:42:44 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
17.07 07:42:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
17.07 07:42:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
17.07 07:42:44 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Snewmy** [comment]
Bump, same issue here. Chat formatting does not work anymore. On 1.20.1.
