### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024

### ISSUE THREAD

**Issue by Guyao146** [Zrips/CMI#7994]
### Description of Issue

When I am using the mohist server core, sometimes this error occurs. However, deleting the cmi and cmiLib folders can fix this bug. However, how about deleting this and not being able to use cmi? Please ask for help

### Version Information

```shell
cmi version 9.6.1.3
cmiLib verison 1.4.0.1
Mohist 1.16.5-1157
```

### Errors

```shell
[13:11:08 INFO]: [CMI] Enabling CMI v9.6.1.3
[13:11:09 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[13:11:09 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[13:11:09 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃
[13:11:09 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃
[13:11:09 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[13:11:09 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[13:11:09 INFO]: _______________________________________________________
[13:11:10 INFO]:   Citizens found.
[13:11:10 INFO]:   58 Enabled and 0 Disabled modules
[13:11:10 INFO]:   Permission plugin: LuckPerms5.3.74
> [authlib-injector] [INFO] Transformed [com.Zrips.CMI.utils.PrevNamesFetcher] with [Constant URL Transformer]
[13:11:10 INFO]:   Initialized Cipher256 AES
[13:11:11 INFO]:   Loaded (61) regular alias into memory. Took 76ms
[13:11:12 INFO]:   Loaded (1) custom text's into memory. Took 4ms
[13:11:12 INFO]:   3.34.0 data base type detected
[13:11:12 INFO]:   UserTable creating CREATE TABLE `users` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_uuid` text, `username` text, `nickname` text, `LogOutLocation` text, `DeathLocation` text, `TeleportLocation` text, `Homes` text, `LastLoginTime` bigint, `LastLogoffTime` bigint, `TotalPlayTime` bigint, `tFly` bigint, `tGod` bigint, `Glow` text, `Ips` text, `Cuffed` boolean, `AlertUntil` bigint, `AlertReason` text, `JoinedCounter` boolean, `LockedIps` text, `pTime` bigint, `Kits` text, `Charges` text, `Cooldowns` mediumtext, `Balance` double, `Notes` text, `Rank` text, `BannedUntil` bigint, `BannedAt` bigint, `BannedBy` text, `BanReason` text, `Ignores` text, `Vanish` text, `Economy` text, `Mail` mediumtext, `FlightCharge` double, `UserMeta` text, `Flying` boolean, `Votifier` int, `Jail` text, `JailedUntil` bigint, `FakeAccount` boolean, `PlaytimeOptimized` bigint, `flightChargeEnabled` boolean, `JailReason` text, `Skin` text, `Collision` boolean, `NamePrefix` text, `NameSuffix` text, `Warnings` text, `NameColor` text, `Muted` text, `AFRecharge` text, `DisplayName` text, `Options` text, `ChatColor` text);
[13:11:12 INFO]:   InvTable creating CREATE TABLE `inventories` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `inventories` longtext);
[13:11:12 INFO]:   PlayTime creating CREATE TABLE `playtime` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `date` int, `h0` bigint, `h1` bigint, `h2` bigint, `h3` bigint, `h4` bigint, `h5` bigint, `h6` bigint, `h7` bigint, `h8` bigint, `h9` bigint, `h10` bigint, `h11` bigint, `h12` bigint, `h13` bigint, `h14` bigint, `h15` bigint, `h16` bigint, `h17` bigint, `h18` bigint, `h19` bigint, `h20` bigint, `h21` bigint, `h22` bigint, `h23` bigint);
[13:11:12 INFO]:   PlayTimeReward creating CREATE TABLE `playtimereward` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `player_id` int, `repeatable` text, `onetime` longtext);
[13:11:12 INFO]:   Started SqLite data base. Took 116ms
[13:11:12 INFO]: [CMI] Vault was found but economy engine is missing. Use one from list provided in https://dev.bukkit.org/bukkit-plugins/vault/
[13:11:12 INFO]: [CMI] Alternatively you can enable CMI economy in config.yml file
[13:11:12 INFO]:   Vault was found but not economy plugin, you will have limited economy support
> [authlib-injector] [INFO] Transformed [com.Zrips.CMI.Modules.Skin.SkinManager] with [Constant URL Transformer]
[13:11:12 INFO]:   Loaded (5) warning categories into memory. Took 1ms
[13:11:12 INFO]:   Loaded (3) warning commands into memory. Took 0ms
[13:11:12 INFO]:   Loaded (135) custom mob heads into memory. Took 28ms
[13:11:12 INFO]:   Loaded (0) cooldowns into memory. Took 97ms
[13:11:12 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024
[13:11:12 WARN]:        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
[13:11:12 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222)
[13:11:12 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
[13:11:12 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
[13:11:12 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634)
[13:11:12 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[13:11:12 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[13:11:12 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[13:11:12 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[13:11:12 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[13:11:12 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[13:11:12 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[13:11:12 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
[13:11:12 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[13:11:12 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:60)
[13:11:12 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[13:11:12 WARN]:        at net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:266)
[13:11:12 WARN]:        at net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:49)
[13:11:12 WARN]:        at net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
[13:11:12 WARN]:        at com.Zrips.CMI.Config.getConfig(Config.java:2775)
[13:11:12 WARN]:        at com.Zrips.CMI.Modules.DeathMessages.DeathMessageManager.loadConfig(DeathMessageManager.java:68)
[13:11:12 WARN]:        at com.Zrips.CMI.Modules.DeathMessages.DeathMessageManager.load(DeathMessageManager.java:54)
[13:11:12 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1531)
[13:11:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:11:12 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[13:11:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[13:11:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:502)
[13:11:12 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414)
[13:11:12 WARN]:        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:427)
[13:11:12 WARN]:        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:347)
[13:11:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220)
[13:11:12 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:768)
[13:11:12 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267)
[13:11:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[13:11:12 ERROR]: Error occurred while enabling CMI v9.6.1.3 (Is it up to date?)
java.lang.NullPointerException: null
        at com.Zrips.CMI.Modules.DeathMessages.DeathMessageManager.loadConfig(DeathMessageManager.java:70) ~[?:?]
        at com.Zrips.CMI.Modules.DeathMessages.DeathMessageManager.load(DeathMessageManager.java:54) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1531) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:502) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:427) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:347) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:768) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
[13:11:12 INFO]: [CMI] Disabling CMI v9.6.1.3
```

### Relevant Config Sections

```yaml
Original Config
```

### Relevant Plugins

CoreProtect, LuckPerms, PlaceholderAPI, QiMengPlayerChest, CMILib, Tpr, ChestSort, EClean, Dantiao, DeluxeTags, RandomPlacer, TrChat, PistonMOTD, Yum, CommandCode, TreeGravity, Vault, PvPManager, TitleManager, WTF, DecentHolograms, VeinMiner, PlayerPoints, Multiverse-Core, TrMenu, VipSystem, Citizens, ChestCommands, AdvancedAchievements, CommandNPC, AuthMe, Signin, CMI, Residence, Plan, LockettePro

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Guyao146** [comment]
when I del authmereloaded plugin，error change [14:11:24 INFO]: [CMI] Enabling CMI v9.6.1.3
[14:11:25 INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[14:11:25 INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[14:11:25 INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃
[14:11:25 INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃
[14:11:25 INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[14:11:25 INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[14:11:25 INFO]: _______________________________________________________
[14:11:26 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1024
[14:11:26 WARN]:        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:136)
[14:11:26 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1222)
[14:11:26 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:308)
[14:11:26 WARN]:        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:248)
[14:11:26 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:634)
[14:11:26 WARN]:        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165)
[14:11:26 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59)
[14:11:26 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45)
[14:11:26 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140)
[14:11:26 WARN]:        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:214)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:314)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:305)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:286)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:188)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115)
[14:11:26 WARN]:        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
[14:11:26 WARN]:        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151)
[14:11:26 WARN]:        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:491)
[14:11:26 WARN]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416)
[14:11:26 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:60)
[14:11:26 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[14:11:26 WARN]:        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[14:11:26 WARN]:        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:191)
[14:11:26 WARN]:        at com.Zrips.CMI.CMI.defaultLocaleDownloader(CMI.java:441)
[14:11:26 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1427)
[14:11:26 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:11:26 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[14:11:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[14:11:26 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:502)
[14:11:26 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414)
[14:11:26 WARN]:        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:427)
[14:11:26 WARN]:        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:347)
[14:11:26 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220)
[14:11:26 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:768)
[14:11:26 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267)
[14:11:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[14:11:26 INFO]:   Citizens found.
[14:11:27 INFO]:   58 Enabled and 0 Disabled modules
[14:11:27 INFO]:   Permission plugin: LuckPerms5.3.74
> [authlib-injector] [INFO] Transformed [com.Zrips.CMI.utils.PrevNamesFetcher] with [Constant URL Transformer]
[14:11:27 INFO]:   Initialized Cipher256 AES
[14:11:28 INFO]:   Loaded (61) regular alias into memory. Took 60ms
[14:11:28 INFO]:   Loaded (1) custom text's into memory. Took 5ms
[14:11:28 WARN]: java.lang.ArrayIndexOutOfBoundsException
[14:11:28 ERROR]: Error occurred while enabling CMI v9.6.1.3 (Is it up to date?)
java.lang.NullPointerException: null
        at com.Zrips.CMI.Config.exportChatSection(Config.java:756) ~[?:?]
        at com.Zrips.CMI.Config.load(Config.java:782) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1527) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:502) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:427) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:347) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:220) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:768) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
[14:11:28 INFO]: [CMI] Disabling CMI v9.6.1.3

**Comment by Zrips** [comment]
Looks to be some sort of issue with main config file. Can you send it to me when it fails to load? In general it looks to be issue with snakeyaml file reader and not CMI directly, but still need to determine why it failed and how we could fix it.

**Comment by Guyao146** [comment]
Thanks Yours Answer

What can I do?

Send my server log ?

**Comment by Guyao146** [comment]
Let me provide a detailed description. This problem can occur without any symptoms, sometimes when restarting, and sometimes not. If it is a snakeyml conflict, I don't know which plugin conflicts and there are no errors reported

**Comment by Zrips** [comment]
It fails when it tries to read config.yml file, we need to know what changes in it when this happens. There might be some weird entries created which causes this issue. So when this error happens it would be nice to get that config.yml file for investigation and determination what went wrong.

**Comment by Guyao146** [comment]
ok，this is my server confiig.yml，I change yml to txt
[config.txt](https://github.com/Zrips/CMI/files/12193269/config.txt)

**Comment by Zrips** [comment]
Is this the one which causes load error for you?

**Comment by Guyao146** [comment]
I don't know how this problem arose

**Comment by Zrips** [comment]
Should beresolved.
