### ISSUE TITLE
Economy Injector Error on Shutdown

### ISSUE THREAD

**Issue by Ew9304** [Zrips/CMI#80]
Spigot 1.8.8 - I got this error today when shutting down my server?

```
[08:22:05] [Server thread/INFO]: [CMIEInjector][Economy] CMI Economy unhooked.
[08:22:05] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.
[08:22:05] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:22:05] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:22:05] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:22:05] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:382)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:4751)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4345)
[08:22:05] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1564)
[08:22:05] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBConnection.closeConnection(DBConnection.java:34)
[08:22:05] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBConnectionPool.closeConnection(DBConnectionPool.java:44)
[08:22:05] [Server thread/WARN]: 	at com.Zrips.CMI.Modules.DataBase.DBDAO.closeConnections(DBDAO.java:411)
[08:22:05] [Server thread/WARN]: 	at com.Zrips.CMI.CMI.onDisable(CMI.java:1005)
[08:22:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
[08:22:05] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
[08:22:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
[08:22:05] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
[08:22:05] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336)
[08:22:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460)
[08:22:05] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593)
[08:22:05] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Ew9304** [comment]
I haven't been able to reproduce this problem again so maybe it was just a one time bug.

**Comment by Zrips** [comment]
Yea, this will not effect plugin work, random error, tho will add code to avoid error messages like this just avoid scaring people :)
