### ISSUE TITLE
Hologram bugs on CMI ver. 9.6.2.0

### ISSUE THREAD

**Issue by Adreez** [Zrips/CMI#8006]
### Description of Issue

New hologram method that uses display entity is throwing `java.lang.NullPointerException`. Can't really tell when it happens because it is not that often.

### Version Information

```shell
[16:25:23 INFO]: --------------------------------------------------
[16:25:23 INFO]: CMI plugin version: 9.6.2.0 BungeeCord CMIB  MySQL-> 9.6.1.3
[16:25:23 INFO]: CMILib: 1.4.0.1 
[16:25:23 INFO]: Server: Purpur 1.20.1-R0.1-SNAPSHOT
[16:25:23 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Enabled 
[16:25:23 INFO]: Modules -> 56 enabled 2 disabled: tablist, votifier
[16:25:23 INFO]: --------------------------------------------------
```

### Errors

```shell
[15:54:53 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn#>
[15:55:10 WARN]: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "st" is null
[15:55:10 WARN]:        at CMILib.jar//net.Zrips.CMILib.FileHandler.ConfigReader.convertUnicode(ConfigReader.java:397)
[15:55:10 WARN]:        at CMILib.jar//net.Zrips.CMILib.FileHandler.ConfigReader.get(ConfigReader.java:472)
[15:55:10 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.HologramManager.saveHolograms(HologramManager.java:774)
[15:55:10 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.HologramManager.access$1(HologramManager.java:687)
[15:55:10 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.HologramManager$3.run(HologramManager.java:681)
[15:55:10 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:55:10 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[15:55:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[15:55:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:55:10 WARN]: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "st" is null
[15:55:10 WARN]:        at CMILib.jar//net.Zrips.CMILib.FileHandler.ConfigReader.convertUnicode(ConfigReader.java:397)
[15:55:10 WARN]:        at CMILib.jar//net.Zrips.CMILib.FileHandler.ConfigReader.get(ConfigReader.java:472)
[15:55:10 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.HologramManager.saveHolograms(HologramManager.java:774)
[15:55:10 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.HologramManager.access$1(HologramManager.java:687)
[15:55:10 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.HologramManager$3.run(HologramManager.java:681)
[15:55:10 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:55:10 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1507)
[15:55:10 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[15:55:10 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[15:55:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:55:33 INFO]: Adr3ez_ issued server command: /colorpicker
[15:55:34 WARN]: java.lang.NullPointerException
[15:55:34 WARN]: java.lang.NullPointerException
[15:55:48 INFO]: Adr3ez_ issued server command: /cmil rmc -2074883291630176405
[15:55:48 INFO]:                        --^-- /cmi colorpicker 1
[15:55:50 WARN]: java.lang.NullPointerException
[15:55:50 WARN]: java.lang.NullPointerException
[15:55:51 INFO]: [Not Secure] ᴀᴅᴍɪɴ Adr3ez_: 
[15:56:03 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn#>
[15:56:15 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn#>
[15:56:22 WARN]: java.lang.NullPointerException
[15:56:22 WARN]: java.lang.NullPointerException
[15:56:29 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn#>
[15:56:30 INFO]: [ExcellentCrates] Auto-save: Saved 1 online users | 0 offline users.
[15:56:45 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn#>
[15:56:52 INFO]: Adr3ez_ issued server command: /cmi hologram
[15:56:52 WARN]: java.lang.NullPointerException
[15:56:54 INFO]: Adr3ez_ issued server command: /cmil rmc -1976539384724815368
[15:56:55 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn#<
[15:57:10 INFO]: Adr3ez_ issued server command: /cmi hologram
[15:57:21 INFO]: Adr3ez_ issued server command: /cmi hologram
[15:57:22 INFO]: Adr3ez_ issued server command: /cmil rmc 9216688491311478945
[15:57:23 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:57:28 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:57:39 WARN]: java.lang.NullPointerException
[15:57:39 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:57:50 INFO]: Adr3ez_ issued server command: /cmi hologram
[15:57:52 INFO]: Adr3ez_ issued server command: /cmil rmc -8411050903610460303
[15:57:53 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:57:58 WARN]: java.lang.NullPointerException
[15:58:07 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:58:13 WARN]: java.lang.NullPointerException
[15:58:25 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:58:28 WARN]: java.lang.NullPointerException
[15:58:44 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:58:44 WARN]: java.lang.NullPointerException
[15:59:03 WARN]: java.lang.NullPointerException
[15:59:17 INFO]: [Not Secure] ᴀᴅᴍɪɴ Adr3ez_: asd
[15:59:39 INFO]: Adr3ez_ issued server command: /cmi hologram
[15:59:41 INFO]: Adr3ez_ issued server command: /cmil rmc -4688074875728249110
[15:59:42 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[15:59:58 WARN]: java.lang.NullPointerException
[16:00:13 WARN]: java.lang.NullPointerException
[16:00:14 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:00:30 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:00:30 WARN]: java.lang.NullPointerException
[16:00:48 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:00:50 INFO]: Adr3ez_ issued server command: /cmil rmc -2996200807792528741
[16:00:51 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:00:53 WARN]: java.lang.NullPointerException
[16:00:58 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:01:13 WARN]: java.lang.NullPointerException
[16:02:29 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:02:32 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:02:33 INFO]: Adr3ez_ issued server command: /cmil rmc -1978790998297704343
[16:02:34 INFO]: Adr3ez_ issued server command: /cmi hologram gui froggie
[16:02:47 INFO]: Adr3ez_ issued server command: /cmi hologram gui froggie
[16:02:50 WARN]: java.lang.NullPointerException
[16:02:50 WARN]: java.lang.NullPointerException
[16:03:06 WARN]: java.lang.NullPointerException
[16:03:06 WARN]: java.lang.NullPointerException
[16:03:23 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:03:25 INFO]: Adr3ez_ issued server command: /cmil rmc -7259251456002292766
[16:03:26 INFO]: Adr3ez_ issued server command: /cmi hologram gui diaulomky
[16:03:41 WARN]: java.lang.NullPointerException
[16:03:41 WARN]: java.lang.NullPointerException
[16:03:41 WARN]: java.lang.NullPointerException
[16:03:42 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:03:43 INFO]: Adr3ez_ issued server command: /cmil rmc -1660220476475089905
[16:03:44 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:03:54 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:04:00 WARN]: java.lang.NullPointerException
[16:04:00 WARN]: java.lang.NullPointerException
[16:04:00 WARN]: java.lang.NullPointerException
[16:04:00 WARN]: java.lang.NullPointerException
[16:04:00 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:04:17 WARN]: java.lang.NullPointerException
[16:04:17 WARN]: java.lang.NullPointerException
[16:04:17 WARN]: java.lang.NullPointerException
[16:04:17 WARN]: java.lang.NullPointerException
[16:04:23 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:04:30 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:04:32 WARN]: java.lang.NullPointerException
[16:04:32 WARN]: java.lang.NullPointerException
[16:04:32 WARN]: java.lang.NullPointerException
[16:04:32 WARN]: java.lang.NullPointerException
[16:04:40 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:04:50 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:04:58 WARN]: java.lang.NullPointerException
[16:04:58 WARN]: java.lang.NullPointerException
[16:04:58 WARN]: java.lang.NullPointerException
[16:04:58 WARN]: java.lang.NullPointerException
[16:05:05 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:05:21 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:05:22 WARN]: java.lang.NullPointerException
[16:05:22 WARN]: java.lang.NullPointerException
[16:05:22 WARN]: java.lang.NullPointerException
[16:05:22 WARN]: java.lang.NullPointerException
[16:05:27 INFO]: Adr3ez_ issued server command: /cmi hologram gui Trznice
[16:05:37 WARN]: java.lang.NullPointerException
[16:05:37 WARN]: java.lang.NullPointerException
[16:05:37 WARN]: java.lang.NullPointerException
[16:05:37 WARN]: java.lang.NullPointerException
[16:06:51 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:06:52 INFO]: Adr3ez_ issued server command: /cmil rmc 714483877293602805
[16:06:53 INFO]: Adr3ez_ issued server command: /cmi hologram gui diaulomky_tezebni
[16:07:03 INFO]: Adr3ez_ issued server command: /cmi hologram gui diaulomky_tezebni
[16:07:09 WARN]: java.lang.NullPointerException
[16:07:09 WARN]: java.lang.NullPointerException
[16:07:09 WARN]: java.lang.NullPointerException
[16:07:09 WARN]: java.lang.NullPointerException
[16:07:09 WARN]: java.lang.NullPointerException
[16:10:35 INFO]: Adr3ez_ issued server command: /pl
[16:13:00 INFO]: ᴀғᴋ • Adr3ez_ je AFK
[16:14:00 INFO]: Adr3ez_ issued server command: /cmi worth
[16:14:00 INFO]: ᴀғᴋ • Adr3ez_ je zpět
[16:14:03 INFO]: Adr3ez_ issued server command: /cmi worth
[16:15:48 INFO]: Adr3ez_ issued server command: /cmi setworth
[16:16:30 INFO]: [ExcellentCrates] Auto-save: Saved 1 online users | 0 offline users.
[16:16:35 INFO]: Adr3ez_ issued server command: /zshop
[16:18:03 INFO]: Adr3ez_ issued server command: /cmi hologram gui lod
[16:18:04 INFO]: Adr3ez_ issued server command: /cmi hologram gui lod1
[16:18:10 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn
[16:18:17 INFO]: Adr3ez_ issued server command: /cmi hologram gui spawn
[16:18:28 WARN]: java.lang.NullPointerException
[16:18:28 WARN]: java.lang.NullPointerException
[16:18:28 WARN]: java.lang.NullPointerException
[16:18:28 WARN]: java.lang.NullPointerException
[16:18:28 WARN]: java.lang.NullPointerException
[16:18:59 INFO]: Adr3ez_ issued server command: /version cmi
[16:19:42 INFO]: Adr3ez_ issued server command: /cmi version
[16:20:24 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:20:26 INFO]: Adr3ez_ issued server command: /cmil rmc 4099598000962503080
[16:20:36 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:20:54 WARN]: java.lang.NullPointerException
[16:20:54 WARN]: java.lang.NullPointerException
[16:20:54 WARN]: java.lang.NullPointerException
[16:20:54 WARN]: java.lang.NullPointerException
[16:20:54 WARN]: java.lang.NullPointerException
asd
[16:21:01 INFO]: Unknown command. Type "/help" for help.
[16:21:16 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:21:17 INFO]: Adr3ez_ issued server command: /cmil rmc 7905695598614744218
[16:21:20 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:21:31 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:21:32 INFO]: Adr3ez_ issued server command: /cmil rmc 6271837745637733958
[16:21:34 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
[16:21:39 WARN]: java.lang.NullPointerException
[16:21:39 WARN]: java.lang.NullPointerException
[16:21:39 WARN]: java.lang.NullPointerException
[16:21:39 WARN]: java.lang.NullPointerException
[16:21:39 WARN]: java.lang.NullPointerException
[16:22:02 INFO]: Adr3ez_ issued server command: /cmi hologram
[16:22:03 INFO]: Adr3ez_ issued server command: /cmil rmc 4420182280772733055
[16:22:04 INFO]: Adr3ez_ issued server command: /cmi hologram gui dungeonzoneportal
```

### Relevant Config Sections

```yaml
Holograms.yml:

dungeonzoneportal:
  Loc: world;4588.51;114.45;-278.11
  HoverParticles:
    Count: 1
  Range: 8
  RangeExtra: 32
  Spacing: 0.24
  NewDisplay: true
  ND:
    Bill: FIXED
    Align: CENTER
    TAlpha: 255
    Shadow: true
    Yaw: 125
    Pitch: 20
    Double: true
    BColor: Black
    BAlpha: 0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try out new CMILib version, should resolve your issue

**Comment by Adreez** [comment]
I will get this error when new player loads the hologram:
`[10:58:30 WARN]: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Colors.CMIChatColor.getRGBColor()" because the return value of "com.Zrips.CMI.Modules.Holograms.CMIHologram.getBackgroundColor()" is null
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updateDisplaySettings(CMIHologram.java:1568)
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:1559)
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1511)
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$2(CMIHologram.java:1615)
[10:58:30 WARN]:        at CMILib.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:36)
[10:58:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:58:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:58:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:58:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:58:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:58:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:58:30 WARN]: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Colors.CMIChatColor.getRGBColor()" because the return value of "com.Zrips.CMI.Modules.Holograms.CMIHologram.getBackgroundColor()" is null
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updateDisplaySettings(CMIHologram.java:1568)
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:1559)
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1511)
[10:58:30 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$2(CMIHologram.java:1615)
[10:58:30 WARN]:        at CMILib.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:36)
[10:58:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[10:58:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:58:30 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:58:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[10:58:30 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[10:58:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Zrips** [comment]
@Adreez 
Will issue a fix with next CMI version, just double check that you have correct hologram background color saved or in case you tried to use something more special and it failed to properly save or load, could you provide example of that one?

**Comment by Adreez** [comment]
Yep, sure!
This is my hologram with custom color (Second one is the same just with different YAW)
`spawn_skills:
  Loc: world;4618.49;107.37;-317.27
  HoverParticles:
    Count: 1
  Range: 8
  RangeExtra: 32
  Spacing: 0.24
  NewDisplay: true
  ND:
    Bill: FIXED
    Align: CENTER
    TAlpha: 230
    Shadow: true
    Yaw: 10
    Pitch: 10
    Double: true
    BColor: 6b483c
    BAlpha: 50`

All other holograms that had color `Black` in the configuration worked fine, but I have two with the same color (6b483c) and they throw an exception.

There are 2 times I used `/cmi reload` to reload holograms that one without an exception is with BColor set to `Black`.

**Comment by Zrips** [comment]
Thanks, this helped out to figure out what went wrong, will be fixed with next version.
