### ISSUE TITLE
Need help please! having some issues with the Plugin!

### ISSUE THREAD

**Issue by DaXenox** [Zrips/CMI#801]
**Description of issue or feature request:**

**ERROR (DELETE IF YOU HAVE NO ERROR):**
ERROR Description:
`````````````````````````````````
/////////////////////////////////////////////////////////////////////////////////////////
|   i changed some option in the config, and now it like the plugin doesnt work.        |
|   also i am getting an error with the Ultra Permission plugin (mentions cmi in error) |
|   almost every command doesnt work and if it does then it says something like:        |
|   command.clear.success or command.generic.usage,                                     |
|   also error when the games tries to tab-complete :                                   |
|   aninternal error occurred while attempting to tab-completethis command.             |
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

 ####################
## PASTE ERROR HERE ##
 ####################

    (Error 1)
-=````````````=-

[13:01:35 ERROR]: Error occurred while enabling CMI v8.0.8.1 (Is it up to date?)

java.lang.NoClassDefFoundError: org/bukkit/scoreboard/Team$Option
        at com.Zrips.CMI.Containers.CMIUser.applyCollision(CMIUser.java:2052) ~[
?:?]
        at com.Zrips.CMI.Containers.CMIUser.setCollision(CMIUser.java:2027) ~[?:
?]
        at com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1373) ~
[?:?]
        at com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1061) ~[
?:?]
        at com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:437) ~[?:?]
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1350) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[s
pigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:340) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:357) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:317) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:74
1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot.jar:git-Spigot-db6d
e12-18fbb24]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
25) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServe
r.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(Craf
tServer.java:627) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:
412) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
75) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.scoreboard.Team$Option
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:91) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:86) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 22 more
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

    (Error 2)
-=`````````````=-

[13:01:35 WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
[13:01:35 WARN]:        at com.Zrips.CMI.Modules.Permissions.UltraPermissions3Ha
ndler.getMainGroup(UltraPermissions3Handler.java:33)
[13:01:35 WARN]:        at com.Zrips.CMI.Modules.Permissions.PermissionsManager.
getMainGroup(PermissionsManager.java:572)
[13:01:35 WARN]:        at com.Zrips.CMI.Containers.CMIUser.updateGroup(CMIUser.
java:488)
[13:01:35 WARN]:        at com.Zrips.CMI.Containers.CMIUser.updatePermissions(CM
IUser.java:431)
[13:01:35 WARN]:        at com.Zrips.CMI.Containers.CMIUser.<init>(CMIUser.java:
203)
[13:01:35 WARN]:        at com.Zrips.CMI.PlayerManager.getUser(PlayerManager.jav
a:404)
[13:01:35 WARN]:        at com.Zrips.CMI.Modules.PlayTime.PlayTimeManager.update
PlayTimes(PlayTimeManager.java:252)
[13:01:35 WARN]:        at com.Zrips.CMI.Modules.PlayTime.PlayTimeManager$1.run(
PlayTimeManager.java:240)
[13:01:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.ru
n(CraftTask.java:71)
[13:01:35 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftSchedul
er.mainThreadHeartbeat(CraftScheduler.java:350)
[13:01:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(Minecr
aftServer.java:723)
[13:01:35 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(Dedica
tedServer.java:374)
[13:01:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(Minecr
aftServer.java:654)
[13:01:35 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(Mine
craftServer.java:557)
[13:01:35 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

    (Error 3)
-=`````````````=-

[05:02:44 ERROR]: Exception when DaXenox attempted to tab complete /prewards
org.bukkit.command.CommandException: Unhandled exception executing tab-completer
for 'prewards ' in com.Zrips.CMI.Containers.CommandReg$ReflectCommand(prewards)

at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java
:217) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.tabCompleteCommand(CraftSe
rver.java:1595) [spigot.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.tabComplete(CraftServer.ja
va:1579) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.tabCompleteCommand(Minec
raftServer.java:1095) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:1915) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInTabComplete.a(SourceFile:46)
[spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInTabComplete.a(SourceFile:10)
[spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot.jar:git-Spigot-db6de12-18fbb24]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown
Source) [?:?]
at java.base/java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar
:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
15) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.Containers.CommandReg.onTabComplete(CommandReg.java:133
) ~[?:?]
at com.Zrips.CMI.Containers.CommandReg$ReflectCommand.tabComplete(Comman
dReg.java:71) ~[?:?]
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java
:213) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
... 15 more

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


**Cmi Version (using`/cmi version`):** 
``````````````````````````````````````````````````````````````
8.0.8.1

**Server Type (Spigot/Paperspigot/etc):** 
`````````````````````````````````````````````````````````````````````
SPIGOT

**Server Version (using `/ver`):** 
```````````````````````````````````````````````````````
this server is running CraftBukkit version git-spigot (MC: 1.8.8) (think its 1.3.1 the newest)

**Comment by Zrips** [comment]
Should be ok with latest builds.
