### ISSUE TITLE
Event error

### ISSUE THREAD

**Issue by SrT3ddy** [Zrips/CMI#8093]
### Description of Issue

Could not pass event

### Version Information

```shell
CMI: 9.6.2.5 BungeeCord  MySQL
CMILib: 1.4.1.0 -> 1.4.1.1
Server: Mohist 1.12.2-R0.1-SNAPSHOT
CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled
```

### Errors

```shell
[01:08:23 ERROR]: Could not pass event PlayerAdvancementDoneEvent to CMI v9.6.2.5
 java.lang.NoSuchMethodError: org.bukkit.advancement.Advancement.getDisplay()Lorg/bukkit/advancement/AdvancementDisplay;
        at com.Zrips.CMI.Modules.EventActions.EventActionListener1_12.PlayerAdvancementDoneEvent(EventActionListener1_12.java:26) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor790.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:223) ~[np.class:?]
        at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:31) ~[p$a.class:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.func_192486_a(SourceFile:158) ~[al$a.class:?]
        at net.minecraft.advancements.critereon.InventoryChangeTrigger.func_192208_a(SourceFile:69) ~[al.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71111_a(EntityPlayerMP.java:1222) ~[oq.class:?]
        at net.minecraft.inventory.Container.func_75142_b(Container.java:189) ~[afr.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2195) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
