### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yuankun1** [Zrips/CMI#8098]
### Description of Issue

error

### Version Information

```shell
[23:05:08] [Server thread/INFO]: CMI 插件版本: 9.6.2.5 SqLite
[23:05:08] [Server thread/INFO]: CMILib: 1.4.1.1
[23:05:08] [Server thread/INFO]: 服务器版本: 98eabb0e (MC: 1.16.5) 1.16.5-R0.1-SNAPSHOT
[23:05:08] [Server thread/INFO]: CMI 经济: Enabled 经济: 1.7.3-b131(CMIEInjector) CMI 聊天: Disabled
[23:05:08] [Server thread/INFO]: 模块 -> 58 已启用 1 已禁用: votifier
```

### Errors

```shell
[22:55:36] [Server thread/ERROR]: Could not pass event PlayerAdvancementDoneEvent to CMI v9.6.2.5
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
        at catserver.server.CatServerEventHandler.onAdvancementEvent(CatServerEventHandler.java:109) ~[forge:1.16.5-98eabb0e]
        at net.minecraftforge.eventbus.ASMEventHandler_143_CatServerEventHandler_onAdvancementEvent_AdvancementEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:303) ~[CatServer-1.16.5-98eabb0e-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[CatServer-1.16.5-98eabb0e-server.jar:?]
        at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1069) ~[forge:?]
        at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:218) ~[?:?]
        at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35) ~[?:?]
        at net.minecraft.advancements.criterion.AbstractCriterionTrigger.func_235959_a_(SourceFile:72) ~[?:?]
        at net.minecraft.advancements.criterion.PositionTrigger.func_192215_a(SourceFile:31) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:566) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:290) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1074) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
Caused by: java.lang.NoSuchMethodError: org.bukkit.advancement.Advancement.getDisplay()Lorg/bukkit/advancement/AdvancementDisplay;
        at com.Zrips.CMI.Modules.EventActions.EventActionListener1_12.PlayerAdvancementDoneEvent(EventActionListener1_12.java:26) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
        ... 23 more
[22:55:39] [Server thread/INFO]: yuan_kun issued server command: /tps
[22:56:32] [Server thread/ERROR]: Could not pass event PlayerAdvancementDoneEvent to CMI v9.6.2.5
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
        at catserver.server.CatServerEventHandler.onAdvancementEvent(CatServerEventHandler.java:109) ~[forge:1.16.5-98eabb0e]
        at net.minecraftforge.eventbus.ASMEventHandler_143_CatServerEventHandler_onAdvancementEvent_AdvancementEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:303) ~[CatServer-1.16.5-98eabb0e-server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[CatServer-1.16.5-98eabb0e-server.jar:?]
        at net.minecraftforge.common.ForgeHooks.onAdvancement(ForgeHooks.java:1069) ~[forge:?]
        at net.minecraft.advancements.PlayerAdvancements.func_192750_a(PlayerAdvancements.java:218) ~[?:?]
        at net.minecraft.advancements.ICriterionTrigger$Listener.func_192159_a(SourceFile:35) ~[?:?]
        at net.minecraft.advancements.criterion.AbstractCriterionTrigger.func_235959_a_(SourceFile:72) ~[?:?]
        at net.minecraft.advancements.criterion.PositionTrigger.func_192215_a(SourceFile:31) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:566) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:290) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:238) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1074) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:336) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:943) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:775) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
Caused by: java.lang.NoSuchMethodError: org.bukkit.advancement.Advancement.getDisplay()Lorg/bukkit/advancement/AdvancementDisplay;
        at com.Zrips.CMI.Modules.EventActions.EventActionListener1_12.PlayerAdvancementDoneEvent(EventActionListener1_12.java:26) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
        ... 23 more
```

### Relevant Config Sections

```yaml
no
```

### Relevant Plugins

1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
