### ISSUE TITLE
com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by kortakai** [Zrips/CMI#8109]
### Description of Issue

CMI uses an outdated mysql connector line to be able to access mysql databases. if you use anything in the 8.0x branch or above of mariadb or mysql it requires this line with the jdbc. I also searched in discord and saw that last year this was reported, and that a ticket was created here as well with the same identical issue and it was closed stating it is a database connection issue (wrong username etc).

Should be something like:

jdbc:mysql://localhost:3306/db?allowPublicKeyRetrieval=true&useSSL=false

### Version Information

```shell
CMI: 9.6.2.6 SqLite
CMILib: 1.4.1.1
Server: Paper(169) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 58 enabled 1 disabled: votifier
```

### Errors

```shell
at CMI-9.6.2.6.jar//com.Zrips.CMI.Modules.DataBase.DBManager.startMysql(DBManager.java:231)
at CMI-9.6.2.6.jar//com.Zrips.CMI.Modules.DataBase.DBManager.load(DBManager.java:145)
at CMI-9.6.2.6.jar//com.Zrips.CMI.Config.load(Config.java:800)
at CMI-9.6.2.6.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1487)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: com.mysql.cj.exceptions.CJException: Public Key Retrieval is not allowed
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:123)
at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:153)
at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:443)
at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:213)
at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1430)
at com.mysql.cj.NativeSession.connect(NativeSession.java:134)
at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:839)
... 25 more
Caused by: com.mysql.cj.exceptions.UnableToConnectException: Public Key Retrieval is not allowed
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:86)
at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:130)
... 31 more
```

### Relevant Config Sections

```yaml
DataBaseInfo.yml
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Thanks for info, will be fixed with next update
