### ISSUE TITLE
/invsee Is not working on newest update.

### ISSUE THREAD

**Issue by Michael-A-Sloan** [Zrips/CMI#8113]
### Description of Issue

So when I run /invsee <playernamehere> 

It starts to error out my console and not open anything.

This wasn't an issue with the last month update but seems to be an issue now.

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.2.6 SqLite
CMILib: 1.4.1.1
Server: Paper(171) 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
Modules -> 48 enabled 11 disabled: deathMessages, customMessages, chatBubble, firstJoinMessages, playerCombat, portals, headDrop, sitAnimation, namePlates, playerChatTag, timedCommands
--------------------------------------------------
```

### Errors

```shell
Player
14:59:31
Pup_Shadow issued server command: /invsee .aparkour

Console
14:59:46
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.6.2.6
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1007) ~[paper-1.20.1.jar:git-Paper-171]
at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-171]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2354) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]
at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-171]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-171]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-171]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-171]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-171]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-171]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-171]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-171]
at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.World.getWorld()" because the return value of "net.minecraft.world.entity.Entity.dI()" is null
at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.getWorld(CraftEntity.java:554) ~[paper-1.20.1.jar:git-Paper-171]
at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.getLocation(CraftEntity.java:463) ~[paper-1.20.1.jar:git-Paper-171]
at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:469) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:355) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.Locale.Language.getLMessage(Language.java:200) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.Locale.Language.getMessage(Language.java:116) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.Locale.CMILC.getMsg(CMILC.java:278) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.Locale.CMILC.getLocale(CMILC.java:246) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.createGui(RegChestManager.java:483) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager.openInventory(RegChestManager.java:103) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.commands.list.inv.perform(inv.java:54) ~[CMI-9.6.2.6.jar:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[CMI-9.6.2.6.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
... 23 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Michael-A-Sloan** [comment]
Update: Found this issue to happen if the player your trying to access the inventory for is offline.

**Comment by Zrips** [comment]
Should be fixed with next update
