### ISSUE TITLE
Gamerule gui error 1.8.8

### ISSUE THREAD

**Issue by Barpadzik** [Zrips/CMI#8156]
### Description of Issue

After entering the /gamerule command, the gamerule gui opens, but when you try to change anything to a different value or page, nothing happens. The server console displays the errors shown below.

### Version Information

```shell
CMI: 9.6.5.1 SqLite
CMILib: 1.4.2.0
Server: PaperSpigot 1.8.8-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled
Modules -> 58 enabled 1 disabled: votifier
```

### Errors

```shell
[22:27:28] [Server thread/WARN]: [CMILib] Task #92 for CMILib v1.4.2.0 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.6.5.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:111) ~[?:?]
	at net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:95) ~[?:?]
	at net.Zrips.CMILib.GUI.GUIManager.lambda$processClick$0(GUIManager.java:268) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.Location org.bukkit.inventory.Inventory.getLocation()'
	at net.Zrips.CMILib.GUI.GUIManager.validInventory(GUIManager.java:477) ~[?:?]
	at net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:488) ~[?:?]
	at net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:464) ~[?:?]
	at net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114) ~[?:?]
	at com.Zrips.CMI.commands.list.gamerule.openGui(gamerule.java:243) ~[?:?]
	at com.Zrips.CMI.commands.list.gamerule.perform(gamerule.java:109) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	... 13 more
[22:27:29] [Server thread/ERROR]: Could not pass event InventoryClickEvent to CMILib v1.4.2.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.Location org.bukkit.inventory.Inventory.getLocation()'
	at net.Zrips.CMILib.GUI.GUIManager.validInventory(GUIManager.java:477) ~[?:?]
	at net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:488) ~[?:?]
	at net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:464) ~[?:?]
	at net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114) ~[?:?]
	at com.Zrips.CMI.commands.list.gamerule.openGui(gamerule.java:243) ~[?:?]
	at com.Zrips.CMI.commands.list.gamerule.access$0(gamerule.java:114) ~[?:?]
	at com.Zrips.CMI.commands.list.gamerule$1.pageChange(gamerule.java:127) ~[?:?]
	at net.Zrips.CMILib.GUI.CMIGui$3.click(CMIGui.java:501) ~[?:?]
	at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:274) ~[?:?]
	at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:226) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	... 16 more
```

### Relevant Config Sections

```yaml
Default Config
```

### Relevant Plugins

ViaVersion 4.8.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should get a fix with next CMILib update
