### ISSUE TITLE
Bug when hit mobs

### ISSUE THREAD

**Issue by Quentin-L-Inge** [Zrips/CMI#8165]
### Description of Issue

Hello, I'm having console warning when someone hit a mob (or a player get hit). I put the error in the error section. 

Havev a good day

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.5.2 SqLite
CMILib: 1.4.2.1 
Server: Paper(484) 1.19.4-R0.1-SNAPSHOT
CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Disabled 
Modules -> 53 enabled 6 disabled: deathMessages, tablist, ranks, firstJoinMessages, votifier, durabilityLoss
--------------------------------------------------
```

### Errors

```shell
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: java.lang.NoClassDefFoundError: org/bukkit/entity/TextDisplay$TextAlignment
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at CMI-9.6.5.2.jar//com.Zrips.CMI.Modules.Display.CMITextAlignment.getTextAlignment(CMITextAlignment.java:13)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at CMI-9.6.5.2.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.updateDisplaySettings(CMIHologram.java:2050)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at CMI-9.6.5.2.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2042)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at CMI-9.6.5.2.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1670)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at CMI-9.6.5.2.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$6(CMIHologram.java:2076)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at CMILib1.4.2.1.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:36)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.TextDisplay$TextAlignment
[16:19:14] [Craft Scheduler Thread - 22 - CMILib/WARN]: 	... 12 more
```

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Tho, update your server as you are quite behind latest paper version.

**Comment by Quentin-L-Inge** [comment]
> Tho, update your server as you are quite behind latest paper version.

Thank you, Yes I will
