### ISSUE TITLE
CMI with forge 1.20.2-48.0.30

### ISSUE THREAD

**Issue by zordixL** [Zrips/CMI#8179]
### Description of Issue

Hello, I tried to launch CMI with the new versions of Forge, but it didn't work. Do you have any ideas about what could be causing this issue? Thank you, and have a good day.

### Version Information

```shell
> cmi version
[18:56:35 WARN]: Unexpected exception while parsing console command "cmi version"
org.bukkit.command.CommandException: Cannot execute command 'cmi' in plugin CMI v9.6.6.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:881) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:897a0a23-71b0135cc-a0f3d486-48.0.30]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchServerCommand(CraftServer.java:865) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:897a0a23-71b0135cc-a0f3d486-48.0.30]
        at net.minecraft.server.dedicated.DedicatedServer.m_139665_(DedicatedServer.java:364) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:342) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1073) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:903) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Errors

```shell
java.lang.NoClassDefFoundError: net/Zrips/CMILib/Version/Version
        at com.Zrips.CMI.CMI.onEnable(CMI.java:1355) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:346) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:481) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:545) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:897a0a23-71b0135cc-a0f3d486-48.0.30]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:458) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:897a0a23-71b0135cc-a0f3d486-48.0.30]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:434) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:336) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:849) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:276) ~[server-1.20.2-20230921.100330-srg.jar%23190!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.Zrips.CMILib.Version.Version
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:198) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[forge-1.20.2-48.0.30-universal.jar%23195!/:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more
```

### Relevant Plugins

CMILib1.4.2.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by zordixL** [comment]
I'm using the latest version of mohist 1.20.2

**Comment by CloudeLecaw** [comment]
cmi is offical not supporting mohist or forge.   Just paper/spigot/bungeecode and may some little others.
but official just these three grand full support.
for all other forks - if an issue appears - it appears.  its a 50/50 an allways depending on how really far away the forks codes is from the offical supported. in case of mohist or forge that supprot mods too i aspect this distance is a bit farer..

So at least feel free to report - but pls dont asume a fix from cmis site.

**Comment by zordixL** [comment]
Thanks you !
