### ISSUE TITLE
Players disconnect, show as connected, and cannot reconnect

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#818]
1.13.1 paper spigot build 245
CMI 8.0.9.0

I'm having a hard time finding exactly what is causing this. Players will disconnect "kicked for spamming" when they are not spamming (and we don't have any auto-kicks). They will show as still connected to the server, they can even still get kicked for the afk timer. But they are still there. We cannot interact with them, tp them, or anything and they cannot log back in unless the server restarts. 

```
[15:12:34] [Netty Epoll Server IO #3/ERROR]: Could not pass event PlayerQuitEvent to CMI v8.0.9.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-245]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.1.jar:git-Paper-245]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-245]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:428) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1447) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.PlayerConnection.disconnect(PlayerConnection.java:275) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.PlayerConnection.disconnect(PlayerConnection.java:246) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:516) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:36) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.PacketPlayInTabComplete.a(SourceFile:9) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:147) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:136) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:358) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.NetworkManager.channelRead0(NetworkManager.java:31) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:275) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.13.1.jar:git-Paper-245]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.13.1.jar:git-Paper-245]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: Asynchronous player tracker update!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:352) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.EntityTracker.a(EntityTracker.java:213) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.EntityPlayer.C(EntityPlayer.java:1369) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.EntityPlayer.updateAbilities(EntityPlayer.java:1232) ~[patched_1.13.1.jar:git-Paper-245]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.setAllowFlight(CraftPlayer.java:1575) ~[patched_1.13.1.jar:git-Paper-245]
	at com.Zrips.CMI.Containers.CMIUser.setFlying(CMIUser.java:1827) ~[?:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerQuitEvent(PlayerListeners.java:814) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor955.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-245]
	... 60 more
```

**Comment by Baktus79** [comment]
I second this. This is something that happes very often.

**Comment by Kbryst** [comment]
Do your players get stuck too?

**Comment by Baktus79** [comment]
Yes, they get kicked out for spamming, but their player get stuck in the game. No matter what I do will remove them. The only way to deal with it is to restart the server. I hope this can get fixed :D

**Comment by Baktus79** [comment]
No, I do not use Towny atm

**Comment by Kbryst** [comment]
What about chat control pro?

**Comment by Baktus79** [comment]
Nope. I have thrown Chatcontrol Pro out for CMI 🙂

**Comment by Zrips** [comment]
Will push out new version with some slight changes. Currently cant determine exactly how to reproduce that issue so i could fix it not going in blind mode. This is paperspigot thing and its doing with async mode. Please check out new 8.0.12.0 version and reopen or make new ticket if issue persists.
