### ISSUE TITLE
/baltop big issue

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#821]
**Description of issue or feature request:**
Everytime a player types /baltop the server start to crash each time player types the command I use:
Vault1.6.11
####################
####################
```
[17:53:39] [Server thread/INFO]: HackeR133 issued server command: /baltop
[17:53:45] [Async Chat Thread - #1/INFO]: [Nowicjusz]Emeryt: Znowu ?
[17:53:49] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:53:49] [Paper Watchdog Thread/ERROR]: The server has not responded for 10 seconds! Creating thread dump
[17:53:49] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:49] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:53:49] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:49] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:53:49] [Paper Watchdog Thread/ERROR]: 	PID: 21 | Suspended: false | Native: false | State: RUNNABLE
[17:53:49] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:53:49] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.list.baltop.perform(baltop.java:71)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1768)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2311/883789671.run(Unknown Source)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1012)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838)
[17:53:49] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[17:53:49] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:49] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:53:49] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:53] [Async Chat Thread - #1/INFO]: [Nowicjusz]4ofkind: test
[17:53:53] [Async Chat Thread - #1/INFO]: [Nowicjusz]GrzeBitte: xD
[17:53:54] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:53:54] [Paper Watchdog Thread/ERROR]: The server has not responded for 15 seconds! Creating thread dump
[17:53:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:54] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:53:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:54] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:53:54] [Paper Watchdog Thread/ERROR]: 	PID: 21 | Suspended: false | Native: false | State: RUNNABLE
[17:53:54] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:53:54] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.list.baltop.perform(baltop.java:71)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1768)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2311/883789671.run(Unknown Source)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1012)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838)
[17:53:54] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[17:53:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:54] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:53:54] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:57] [Async Chat Thread - #1/INFO]: [Nowicjusz]Stormiak: lol
[17:53:59] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:53:59] [Paper Watchdog Thread/ERROR]: The server has not responded for 20 seconds! Creating thread dump
[17:53:59] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:59] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:53:59] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:59] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:53:59] [Paper Watchdog Thread/ERROR]: 	PID: 21 | Suspended: false | Native: false | State: RUNNABLE
[17:53:59] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:53:59] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap.successor(TreeMap.java:2154)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1212)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap$EntryIterator.next(TreeMap.java:1247)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap$EntryIterator.next(TreeMap.java:1242)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.list.baltop.perform(baltop.java:71)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1768)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2311/883789671.run(Unknown Source)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1012)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838)
[17:53:59] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[17:53:59] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:53:59] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:53:59] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:03] [User Authenticator #1/INFO]: UUID of player spartakus314 is a7bd4076-b15f-35fe-b766-d772db0bc462
[17:54:04] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:54:04] [Paper Watchdog Thread/ERROR]: The server has not responded for 25 seconds! Creating thread dump
[17:54:04] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:04] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:54:04] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:04] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:54:04] [Paper Watchdog Thread/ERROR]: 	PID: 21 | Suspended: false | Native: false | State: RUNNABLE
[17:54:04] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:54:04] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap.successor(TreeMap.java:2154)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1212)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap$EntryIterator.next(TreeMap.java:1247)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		java.util.TreeMap$EntryIterator.next(TreeMap.java:1242)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.list.baltop.perform(baltop.java:71)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1768)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2311/883789671.run(Unknown Source)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1012)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838)
[17:54:04] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[17:54:04] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:04] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:54:04] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:06] [Async Chat Thread - #1/INFO]: [Nowicjusz]_Papciolek_: lag?
[17:54:09] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:54:09] [Paper Watchdog Thread/ERROR]: The server has not responded for 30 seconds! Creating thread dump
[17:54:09] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:09] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[17:54:09] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:09] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[17:54:09] [Paper Watchdog Thread/ERROR]: 	PID: 21 | Suspended: false | Native: false | State: RUNNABLE
[17:54:09] [Paper Watchdog Thread/ERROR]: 	Stack:
[17:54:09] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.list.baltop.perform(baltop.java:71)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:726)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1768)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$2311/883789671.run(Unknown Source)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1012)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838)
[17:54:09] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:748)
[17:54:09] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:09] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[17:54:09] [Paper Watchdog Thread/ERROR]: ------------------------------
[17:54:14] [User Authenticator #1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@7c6d5581[id=21222e0b-204e-32cb-9128-dca5c79f110a,name=snajper263,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[patched_1.13.1.jar:git-Paper-245]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) ~[patched_1.13.1.jar:git-Paper-245]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:35) ~[patched_1.13.1.jar:git-Paper-245]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) ~[patched_1.13.1.jar:git-Paper-245]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:28) ~[patched_1.13.1.jar:git-Paper-245]
	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:177) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.LoginListener$LoginHandler.fireEvents(LoginListener.java:291) ~[patched_1.13.1.jar:git-Paper-245]
	at net.minecraft.server.v1_13_R2.LoginListener$1.run(LoginListener.java:197) ~[patched_1.13.1.jar:git-Paper-245]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

**Cmi Version (using`/cmi version`):** 
8.0.9.0/8.0.1.0
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot 1.13.1
**Server Version (using `/ver`):** 
1.13.1

**Comment by Baktus79** [comment]
Same happens to me. The server may crash when using the /cmi baltop command.

**Comment by Tazkee** [comment]
Try to update Vault to the 1.7.1 version, link: https://www.spigotmc.org/resources/vault.34315/

**Comment by arturek1666** [comment]
But than I think I need CMIInjector for money to work

**Comment by arturek1666** [comment]
Even if I switched to the 1.7.1 vault and added  economy injector it still crash my server. Fun Fact it crash only if player types a command. If an OP types it's fine

**Comment by Tazkee** [comment]
Try to add specific permissions that work in similiar situations, for example: cmi.command.baltop

**Comment by arturek1666** [comment]
I already had that permission.

**Comment by Zrips** [comment]
@arturek1666 
How many users do you have in your database?

**Comment by Zrips** [comment]
Test out new version and report if issue still persists.

**Comment by arturek1666** [comment]
For data I use sqlite.  Not sure how many users i have there is about 50 players every day maybe 300 users our more

**Comment by Zrips** [comment]
@arturek1666 
Thanks for info, as suspected, its not due to user amount but possibly due to cache over sizing over time as old data was not been removed properly when updating only one player bal top value in cache. Anyhow, if you have opportunity, test it out and would be best to test it out after similar period of time as previously it was causing issues, just to be sure that this was fixed. If not, report back, will have to recheck entire code for that feature.

**Comment by arturek1666** [comment]
Ok  thank you for a support

**Comment by Zrips** [comment]
8.0.13.0 Should solve this one once and for all.
