### ISSUE TITLE
Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#8211]
### Description of Issue

Recently I updated my server to version 1.20.2. After the update none of the inventory menus work as they should, plus they give an error message in the console. Examples of this are `/cmi homes`, `/cmi armorstand`, `/cmi invcheck`, etc.

### Version Information

```shell
[05:08:34 INFO]: --------------------------------------------------
[05:08:34 INFO]: CMI plugin versjon: 9.6.7.3 Velocity CMIB  MySQL
[05:08:34 INFO]: CMILib: 1.4.2.2 
[05:08:34 INFO]: Server: Paper(249) 1.20.2-R0.1-SNAPSHOT
[05:08:34 INFO]: CMI økonomi: Aktivert Vault: 1.7.3-CMI CMI Chat: Aktivert 
[05:08:34 INFO]: Moduler -> 56 aktivert 3 deaktivert: chatBubble, tablist, vanish
[05:08:34 INFO]: --------------------------------------------------
```

### Errors

```shell
[04:59:15 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "nmsStack" is null
[04:59:15 WARN]:        at CMILib1.4.2.2.jar//net.Zrips.CMILib.NBT.CMINBT.HideFlag(CMINBT.java:1258)
[04:59:15 WARN]:        at CMILib1.4.2.2.jar//net.Zrips.CMILib.GUI.CMIGuiButton.hideItemFlags(CMIGuiButton.java:60)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Homes.HomeManager.openComplexHomeGui(HomeManager.java:798)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:566)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.commands.list.homes.perform(homes.java:168)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[04:59:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[04:59:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[04:59:15 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[04:59:15 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[04:59:15 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[04:59:15 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[04:59:15 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[04:59:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[04:59:15 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:59:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[04:59:15 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148)
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659)
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:60)
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftInventory.setItem(CraftInventory.java:99)
[04:59:15 WARN]:        at CMILib1.4.2.2.jar//net.Zrips.CMILib.GUI.GUIManager.generateInventory(GUIManager.java:407)
[04:59:15 WARN]:        at CMILib1.4.2.2.jar//net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:446)
[04:59:15 WARN]:        at CMILib1.4.2.2.jar//net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Homes.HomeManager.openComplexHomeGui(HomeManager.java:911)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:566)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.commands.list.homes.perform(homes.java:168)
[04:59:15 WARN]:        at CMI.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[04:59:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[04:59:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[04:59:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[04:59:15 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[04:59:15 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[04:59:15 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[04:59:15 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[04:59:15 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[04:59:15 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[04:59:15 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[04:59:15 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[04:59:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[04:59:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Looks to be issue with paper servers in general as of #247 update, just downgrade your server to #246 until paper team can make a fix for it

**Comment by Baktus79** [comment]
Thanks for the respond :) 
I see that this has already been discovered at PaperMC, and they have a patch ready. This will probably be fixed shortly. To others who are struggling with the same problem: [https://github.com/PaperMC/Paper/issues/9875](https://github.com/PaperMC/Paper/issues/9875)

**Comment by Baktus79** [comment]
There was a Paper update today and I can confirm that this solved the issue.
