### ISSUE TITLE
CMIV getHostAddress() error

### ISSUE THREAD

**Issue by Adreez** [Zrips/CMI#8215]
### Description of Issue

This error happens to me on every server switch.

### Version Information

```shell
cmiv 1.0.0.0

>....[15:50:36 INFO]: Velocity 3.2.0-SNAPSHOT (git-81b183ac-b276)
```

### Errors

```shell
`[14:10:37 ERROR]: Couldn't pass ServerPostConnectEvent to cmiv
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
        at net.Zrips.ServerEvents.onServerPostConnectEvent(ServerEvents.java:33) ~[?:?]
        at net.Zrips.Lmbda$37.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Baktus79** [comment]
#8216

**Comment by Zrips** [comment]
Should be fixed with next CMIV update
