### ISSUE TITLE
CMIV Couldn't pass ServerConnectedEvent to cmiv

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#8216]
### Description of Issue

Error when players switch between servers
Happened multiple times today

### Version Information

```shell
CMIV-1.0.0.0
Velocity 3.2.0-SNAPSHOT (git-81b183ac-b276)
```

### Errors

```shell
[18:45:55 ERROR]: Couldn't pass ServerConnectedEvent to cmiv
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:143) ~[?:?]
at net.Zrips.ServerEvents.sendServerSwitchEvent(ServerEvents.java:100) ~[?:?]
at net.Zrips.ServerEvents.onServerConnectEvent(ServerEvents.java:67) ~[?:?]
at net.Zrips.Lmbda$24.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Relevant Plugins

CMIV-1.0.0.0

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Baktus79** [comment]
I have a similar issue.
```
[02:22:08 ERROR]: Couldn't pass ServerPostConnectEvent to cmiv
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
        at net.Zrips.ServerEvents.onServerPostConnectEvent(ServerEvents.java:33) ~[?:?]
        at net.Zrips.Lmbda$38.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-81145e45-b288)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-81145e45-b288)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-81145e45-b288)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Zrips** [comment]
Both issues should be fixed with next CMIV update
