### ISSUE TITLE
Guis of CMI and Jobs dont work with newest CMILib version

### ISSUE THREAD

**Issue by JustJP2K** [Zrips/CMI#8252]
### Description of Issue

The title is a very good description.

It seems that CMILib is messing with all plugins Guis required to have CMILib such as CMI and Jobs. 

### Version Information

```shell
CMI: 9.6.8.0
CMILib: 1.4.3.0
Jobs: 5.2.1.2
```

### Errors

```shell
`[2023-11-13 09:24:16] [INFO]: JustJP2K issued server command: /homes
[2023-11-13 09:24:16] [WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.profile.PlayerProfile.getTextures()" because "ownerProfile" is null
[2023-11-13 09:24:16] [WARN]: at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:148)
[2023-11-13 09:24:16] [WARN]: at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:659)
[2023-11-13 09:24:16] [WARN]: at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:60)
[2023-11-13 09:24:16] [WARN]: at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftInventory.setItem(CraftInventory.java:99)
[2023-11-13 09:24:16] [WARN]: at CMILib1.4.3.0.jar//net.Zrips.CMILib.GUI.GUIManager.generateInventory(GUIManager.java:407)
[2023-11-13 09:24:16] [WARN]: at CMILib1.4.3.0.jar//net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:446)
[2023-11-13 09:24:16] [WARN]: at CMILib1.4.3.0.jar//net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114)
[2023-11-13 09:24:16] [WARN]: at CMI-9.6.8.0.jar//com.Zrips.CMI.Modules.Homes.HomeManager.openComplexHomeGui(HomeManager.java:911)
[2023-11-13 09:24:16] [WARN]: at CMI-9.6.8.0.jar//com.Zrips.CMI.Modules.Homes.HomeManager.openHomeGui(HomeManager.java:566)
[2023-11-13 09:24:16] [WARN]: at CMI-9.6.8.0.jar//com.Zrips.CMI.commands.list.homes.perform(homes.java:168)
[2023-11-13 09:24:16] [WARN]: at CMI-9.6.8.0.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[2023-11-13 09:24:16] [WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[2023-11-13 09:24:16] [WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[2023-11-13 09:24:16] [WARN]: at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[2023-11-13 09:24:16] [WARN]: at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[2023-11-13 09:24:16] [WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[2023-11-13 09:24:16] [WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[2023-11-13 09:24:16] [WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[2023-11-13 09:24:16] [WARN]: at java.base/java.lang.Thread.run(Thread.java:840)`
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by JustJP2K** [comment]
> Need output from /cmi version to get better idea what server version you have

Paper (249) 1.20.2-R0.1-SNAPSHOT+

**Comment by Zrips** [comment]
Update to latest build (paper 291) as there was bug in few versions around yours with player heads in inventories
