### ISSUE TITLE
Typing on signs throwing error

### ISSUE THREAD

**Issue by EagL3-GIT** [Zrips/CMI#8265]
### Description of Issue

When you type on signs it throws error.

### Version Information

```shell
CMI plugin version: 9.6.8.0 SqLite-> 9.6.8.1
CMILib: 1.4.3.1
Server: Paper(292) 1.20.2-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 26 enabled 33 disabled: spawnerProximity, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, elytraBoost, elytraLaunch, bossBarCompass, coloredArmor, chatBubble, shulkerBackpack, headDrop, spawnerCharge, namePlates, hpBossBar, launchPad, portals, holograms, anvilRenameColor, jail, paintingEditor, dynamicSigns, durabilityLoss, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, ranks, selection
```

### Errors

```shell
[17:37:05 ERROR]: Could not pass event SignChangeEvent to CMI v9.6.8.0
java.lang.IndexOutOfBoundsException: No group 2
at java.util.regex.Matcher.group(Matcher.java:646) ~[?:?]
at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandListener.onSignChangeEvent(InteractiveCommandListener.java:175) ~[CMI-9.6.8.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor491.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-292]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-292]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-292]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.level.block.entity.SignBlockEntity.setMessages(SignBlockEntity.java:227) ~[?:?]
at net.minecraft.world.level.block.entity.SignBlockEntity.lambda$updateSignText$4(SignBlockEntity.java:188) ~[?:?]
at net.minecraft.world.level.block.entity.SignBlockEntity.updateText(SignBlockEntity.java:202) ~[?:?]
at net.minecraft.world.level.block.entity.SignBlockEntity.updateSignText(SignBlockEntity.java:187) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.updateSignText(ServerGamePacketListenerImpl.java:3388) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleSignUpdate$25(ServerGamePacketListenerImpl.java:3369) ~[?:?]
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-292]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-292]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-292]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-292]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-292]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-292]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-292]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-292]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
Yeah this Sign stuff still hasn't been resolved and it's getting a bit frustrating. I've had to disable the shift edit toggle/abilities entirely for everyone since with it they're all still able to edit any sign even when protected. Personally I think editing Signs in Residence should be under the build/place/break flags (which is how WorldGuard did it) instead of `Use` and the shift edit should be removed from CMI entirely since it's a bit redundant now on 1.20+. CMI still has `/cmi se` for anyone who still needs that on older versions. CMI should not be breaking vanilla mechanics.

**Comment by Zrips** [comment]
@EagL3-GIT 
Will be fixed with next update

**Comment by Zrips** [comment]
@mercurialmusic 
I was considering to move sign edit to another flag, so yea, I can agree on that one.
But could you elaborate more on your statement that you can still edit signs even in protected areas? As this should not really be a thing in 1.20+ servers as we no longer opening UI, now we are just preventing its opening in case player doesn't have appropriate permission node which on itself could still be blocked by different plugin if needed.
And /cmi se is there for more quicker sign edits where you can quickly change specific sign lines or set all of them in one go.

**Comment by mercurialmusic** [comment]
> @mercurialmusic I was considering to move sign edit to another flag, so yea, I can agree on that one. But could you elaborate more on your statement that you can still edit signs even in protected areas? As this should not really be a thing in 1.20+ servers as we no longer opening UI, now we are just preventing its opening in case player doesn't have appropriate permission node which on itself could still be blocked by different plugin if needed. And /cmi se is there for more quicker sign edits where you can quickly change specific sign lines or set all of them in one go.

I think the protected areas thing would be fixed by moving the flag, so that point may be moot. Currently anyone with the USE flag in a Residence (needed for many things including the elevators and IC currently) plus the cmi.signs.shiftedit are able to edit any sign anywhere regardless of build permission (and I double checked that it was indeed cmi.signs.shiftedit as opposed to cmi.signs.shifteditbypass). In order to prevent that we had to negate cmi.signs.shiftedit for everyone, which now also prevents the vanilla behavior anywhere. 

Even with the IC I was getting a bunch of messed up signs after people used them unless I specifically set sign lines in the configs for each one then waxed them all.
