### ISSUE TITLE
big cmi modules hologram

### ISSUE THREAD

**Issue by livxbox5** [Zrips/CMI#8273]
### Description of Issue

holograms don't work and always spam an error to the console

### Version Information

```shell
[13:08:12 INFO]: --------------------------------------------------
[13:08:12 INFO]: Версия плагина CMI: 9.6.8.1 Velocity CMIB  SqLite
[13:08:12 INFO]: CMILib: 1.4.3.2
[13:08:12 INFO]: Версия сервера: Paper(297) 1.20.2-R0.1-SNAPSHOT-
[13:08:12 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMI(CMIEInjector)CMI Чат: Включено
[13:08:12 INFO]: Модули -> 58 включено 1 отключено: votifier
[13:08:12 INFO]: --------------------------------------------------
```

### Errors

```shell
>
[13:10:02 WARN]: java.lang.IllegalStateException: EntityTeleportEvent may only be triggered synchronously.
[13:10:02 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[13:10:02 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:10:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:10:02 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[13:10:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:611)
[13:10:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:579)
[13:10:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:573)
[13:10:02 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:35)
[13:10:02 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2057)
[13:10:02 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1678)
[13:10:02 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$6(CMIHologram.java:2093)
[13:10:02 WARN]:        at CMILib1.4.3.2.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:36)
[13:10:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101)
[13:10:02 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:10:02 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:10:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:10:02 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:10:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Relevant Plugins

vault 1.7,3-cmi

### Agreements

- [x] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next CMILib and CMI update.

**Comment by livxbox5** [comment]
and when will the next update be?

**Comment by Zrips** [comment]
Should be out today
