### ISSUE TITLE
cmi chat error

### ISSUE THREAD

**Issue by livxbox5** [Zrips/CMI#8274]
### Description of Issue

когда игрок\игроки пишут в чат в консоли спамить ошибки 

### Version Information

```shell
[12:50:18 INFO]: --------------------------------------------------
[12:50:18 INFO]: Версия плагина CMI: 9.6.8.1 SqLite
[12:50:18 INFO]: CMILib: 1.4.3.2
[12:50:18 INFO]: Версия сервера: Paper(297) 1.20.2-R0.1-SNAPSHOT-
[12:50:18 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMI(CMIEInjector)CMI Чат: Включено
[12:50:18 INFO]: Модули -> 57 включено 2 отключено: votifier, holograms
[12:50:18 INFO]: --------------------------------------------------
```

### Errors

```shell
[12:45:27 WARN]: java.lang.IllegalStateException: EntityTeleportEvent may only be triggered synchronously.
[12:45:27 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[12:45:27 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:45:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[12:45:27 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[12:45:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:611)
[12:45:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:579)
[12:45:27 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity.teleport(CraftEntity.java:573)
[12:45:27 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:35)
[12:45:27 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.generateDisplay(CMIChatBubble.java:162)
[12:45:27 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.<init>(CMIChatBubble.java:41)
[12:45:27 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.Chat.ChatBubbleManager.showBubble(ChatBubbleManager.java:95)
[12:45:27 WARN]:        at CMI-9.6.8.1.jar//com.Zrips.CMI.Modules.NickName.NickNameListener.AsyncPlayerChatEventRawConverter(NickNameListener.java:220)
[12:45:27 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor405.execute(Unknown Source)
[12:45:27 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[12:45:27 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[12:45:27 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:45:27 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[12:45:27 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:45:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[12:45:27 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416)
[12:45:27 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102)
[12:45:27 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2313)
[12:45:27 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2442)
[12:45:27 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChat$16(PlayerConnection.java:2142)
[12:45:27 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[12:45:27 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[12:45:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:45:27 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:45:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Relevant Config Sections

```yaml
cmi\setting\chat.yml
```

### Relevant Plugins

vault 1.7,3-cmi

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This should be fixed with next CMILib and CMI update

**Comment by livxbox5** [comment]
thank you for the fix
