### ISSUE TITLE
Error when using /customrecipe

### ISSUE THREAD

**Issue by Nephalem0** [Zrips/CMI#8286]
### Description of Issue

Hi! I've been getting this huge chunk of error code whenever working with /customrecepie, the actual command seems to work fine and I don't get any issues in terms of making the command run. But it does flood the console and I am not sure what is the issue

### Version Information

```shell
CMI: 9.6.8.4 SqLite
CMILib: 1.4.3.4
Server: 1.20.1 1.20.1-R0.1-SNAPSHOT+
```

### Errors

```shell
[20:06:36 ERROR] [STDERR]: java.lang.ClassCastException: Cannot cast java.util.HashMap to net.minecraft.world.inventory.AbstractContainerMenu
[20:06:36 ERROR] [STDERR]:      at java.base/java.lang.Class.cast(Class.java:3889)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.Reflections.getActiveContainerId(Reflections.java:1335)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.Reflections.updateInventoryTitle(Reflections.java:1428)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:507)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:465)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114)
[20:06:36 ERROR] [STDERR]:      at com.Zrips.CMI.commands.list.customrecipe.openSubMenu(customrecipe.java:526)
[20:06:36 ERROR] [STDERR]:      at com.Zrips.CMI.commands.list.customrecipe.openSubMenu(customrecipe.java:202)
[20:06:36 ERROR] [STDERR]:      at com.Zrips.CMI.commands.list.customrecipe$1.click(customrecipe.java:90)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:276)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:226)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3390)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.md7e0417$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[20:06:36 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:842)
[20:06:36 ERROR] [STDERR]: java.lang.IllegalArgumentException
[20:06:36 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:06:36 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:06:36 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:06:36 ERROR] [STDERR]:      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:06:36 ERROR] [STDERR]:      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.Reflections.updateInventoryTitle(Reflections.java:1428)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:507)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:465)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114)
[20:06:36 ERROR] [STDERR]:      at com.Zrips.CMI.commands.list.customrecipe.openSubMenu(customrecipe.java:526)
[20:06:36 ERROR] [STDERR]:      at com.Zrips.CMI.commands.list.customrecipe.openSubMenu(customrecipe.java:202)
[20:06:36 ERROR] [STDERR]:      at com.Zrips.CMI.commands.list.customrecipe$1.click(customrecipe.java:90)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:276)
[20:06:36 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:226)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.1-c3fc1d3/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3390)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.md7e0417$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074)
[20:06:36 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[20:06:36 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:842)
```

### Relevant Config Sections

```yaml
I am using arclight which I know it isn't directly supported but it does seem to run fine
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
From discord chat:

New server, not an upgrade.

![image](https://github.com/Zrips/CMI/assets/28841349/ad03d414-b382-428b-a682-ea79dd720744)

![image](https://github.com/Zrips/CMI/assets/28841349/dda42cc4-47b2-44b9-8032-6308b3772570)

![image](https://github.com/Zrips/CMI/assets/28841349/c23fec5d-ec93-45cf-a37c-b5c337d79144)

**Comment by Zrips** [comment]
@Nephalem0 
Try to update your server to the latest 1.0.2 arclight version as you are still on older one. This should resolve your issue.

**Comment by Nephalem0** [comment]
I'm unable to find any version of Arclight for mc 1.20.1 other than 1.0.0 and 1.0.1
