### ISSUE TITLE
when use /armorstand,some error

### ISSUE THREAD

**Issue by YuanYuanOwO** [Zrips/CMI#8304]
### Description of Issue

It happens with the command related to /armorstand, but I'm not sure how to reproduce it  
It doesn't work when saving adjusted armour stand  
but I'm sure it was working before one of the plugin update  

### Version Information

```shell
[21:26:18 INFO]: --------------------------------------------------
[21:26:18 INFO]: CMI 插件版本(Plugin Version): 9.6.8.6 SqLite
[21:26:18 INFO]: CMILib: 1.4.3.5 
[21:26:18 INFO]: 服务器版本(Server Version): Paper(318) 1.20.2-R0.1-SNAPSHOT-
[21:26:18 INFO]: CMI 经济: 禁用(CMI Economy is disabled) 经济(Vault): 1.7.3-b131 CMI 聊天(Chat): 禁用 (disabled)
[21:26:18 INFO]: 模块 -> 55 已启用 4 已禁用: tablist, votifier, moneyCheque, playerChatTag
[21:26:18 INFO]: --------------------------------------------------
```

### Errors

```shell
[21:17:53 ERROR]: Could not pass event CreatureSpawnEvent to CMI v9.6.8.6
java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Items.CMIItemStack.getItemStack()" because "<local8>" is null
        at com.Zrips.CMI.Modules.AStand.ArmorStandSave.apply(ArmorStandSave.java:408) ~[CMI-9.6.8.6.jar:?]
        at com.Zrips.CMI.Modules.AStand.ArmorStandListener.processArmorStand(ArmorStandListener.java:205) ~[CMI-9.6.8.6.jar:?]
        at com.Zrips.CMI.Modules.AStand.ArmorStandListener.armorStandSpawnEvent(ArmorStandListener.java:113) ~[CMI-9.6.8.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor618.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:793) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:695) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1690) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1598) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:12) ~[?:?]
        at net.minecraft.world.item.ArmorStandItem.useOn(ArmorStandItem.java:61) ~[?:?]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:370) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:598) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1908) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1410) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by YuanYuanOwO** [comment]
It only seems to happen with leather armor.
