### ISSUE TITLE
cmi 9.6.8.6 spamm errors in console for new holograms on 1.20.1 server

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8305]
### Description of Issue

We updated yesterday to cmi 9.6.8.6

since this time when we move to a hologramm with new disaplay methide the console spamms us.
When we move away to the holograms they are not shown.
when we are enough far away from the holograms the spawm stops.

Downgrading to 9.6.8.5 (and cmilib 1.4.3.4 with autoupdate disabled in cmilib config) fixes the issue for now..
i hope a solution could be found.

### Version Information
![Snag_48598b](https://github.com/Zrips/CMI/assets/12080017/68354bf6-ab51-4b18-a702-dfc109870b00)

### Errors

```shell
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity net.minecraft.world.entity.Entity.getBukkitEntity()'
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at CMI_9.6.8.6.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.show(CMIDisplay.java:240)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at CMI_9.6.8.6.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.show(CMIDisplay.java:232)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at CMI_9.6.8.6.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1679)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at CMI_9.6.8.6.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$6(CMIHologram.java:2091)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at CMILib_1.4.3.5.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:36)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:56:51] [Craft Scheduler Thread - 315 - CMILib/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
looking at this line
```
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.v1_20_R2.entity.CraftEntity net.minecraft.world.entity.Entity.getBukkitEntity()
```
make me feel like cmi or cmilib tried to search for 1.20.2 code that does not exist when your using a 1.20.1 server...

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with today's update
