### ISSUE TITLE
Bug Report with events on join

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/CMI#8316]
### Description of Issue

Errors on Join

### Version Information

```shell
[18:01:53 INFO]: --------------------------------------------------
[18:01:53 INFO]: CMI Plugin Version: 9.6.9.2 Unknown  SqLite
[18:01:53 INFO]: CMILib: 1.4.4.1
[18:01:53 INFO]: Server: Purpur(2062) 1.20.1-R0.1-SNAPSHOT-
[18:01:53 INFO]: CMI economy: Deaktiviert CMI Chat: Aktiviert
[18:01:53 INFO]: Modules -> 47 enabled 12 disabled: hpBossBar, tablist, ranks, playerCombat, votifier, shulkerBackpack, moneyCheque, afk, headDrop, jail, cmiPlaytime, kits
```

### Errors

```shell
[17:49:57] [Server thread/INFO]: PabloKateee[/83.221.90.176:33817] logged in with entity id 7 at ([world]-441.3129835374971, -9.0, -382.4833412309649)
[17:49:57] [Server thread/INFO]: [Client] PabloKateee joined using Optifine!
[17:49:58] [Server thread/INFO]: Du hast die Laufgeschwindigkeit von PabloKateee (Online) auf 1.0 gesetzt.
[17:49:58] [Server thread/INFO]: Spielt entity_mooshroom_convert in world -442:-9:-383 
[17:49:58] [Server thread/INFO]: Höhe: 1.0 Lautstärke: 1.0
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:108)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1169)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1058)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:112)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1169)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1058)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:108)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1063)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1171)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1058)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:112)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1063)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1171)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1058)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:108)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1169)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1071)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:112)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1169)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1071)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:108)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1063)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1171)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1071)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: java.lang.NoSuchMethodError: 'net.minecraft.server.ScoreboardServer net.minecraft.server.MinecraftServer.aH()'
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:1946)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[17:50:00] [Server thread/WARN]: 	at CMILib1.4.4.1.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:112)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1063)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1171)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1071)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338)
[17:50:00] [Server thread/WARN]: 	at CMI-9.6.9.2.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:50:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1506)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:486)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1420)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1191)
[17:50:00] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[17:50:00] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:50:00] [Server thread/WARN]: [CMI] Task #173 for CMI v9.6.9.2 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.6.9.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1063) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1171) ~[CMI-9.6.9.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1071) ~[CMI-9.6.9.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:404) ~[CMI-9.6.9.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.access$2(SpecializedCommandManager.java:338) ~[CMI-9.6.9.2.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager$3.run(SpecializedCommandManager.java:397) ~[CMI-9.6.9.2.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: advancement
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:2769) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.Zrips.CMILib.Advancements.CMIAdvancement.grant(CMIAdvancement.java:277) ~[CMILib1.4.4.1.jar:?]
	at net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:254) ~[CMILib1.4.4.1.jar:?]
	at com.Zrips.CMI.commands.list.toast.perform(toast.java:112) ~[CMI-9.6.9.2.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[CMI-9.6.9.2.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 16 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
