### ISSUE TITLE
/cmi tpallworld throws error and does not work

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#8323]
### Description of Issue

/cmi tpallworld does not work, throws error, example use:
```
/cmi tpallworld event PirateCraft_1;0;150;0
```

Throws this in console
```
[21:53:48] [Craft Scheduler Thread - 4450 - CMI/WARN]: [CMI] Plugin CMI v9.6.8.4 generated an exception while executing task 2684254
java.lang.NullPointerException: Cannot read the array length because "<local5>" is null
	at com.Zrips.CMI.commands.list.tpallworld.lambda$0(tpallworld.java:97) ~[CMI-9.6.8.4.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

![image](https://github.com/Zrips/CMI/assets/144046/bd402f2b-fdd6-4cd1-87b9-c610da566d6e)

### Version Information

```shell
See up, cant attach images in here.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by TomLewis** [comment]
Bumping as this issue still exists 2 years later!
```
[09:48:20] [Craft Scheduler Thread - 2295 - CMI/WARN]: [CMI] Plugin CMI v9.7.12.3 generated an exception while executing task 11656630
java.lang.NullPointerException: Cannot read the array length because "<local5>" is null
	at com.Zrips.CMI.commands.list.tpallworld.lambda$0(tpallworld.java:99) ~[CMI-9.7.12.3.jar:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[CMILib1.5.4.2.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
