### ISSUE TITLE
1.16.5 Death drop requires setting every time the server is restarted

### ISSUE THREAD

**Issue by yuxi7712** [Zrips/CMI#8329]
### Description of Issue

There was an error when I entered/gamerule keepInventory true.

After opening the entire world without dropping death, the next time the server is opened, it needs to be operated again

### Version Information

```shell
server mohist-1.16.5-1197-server
```

### Errors

```shell
05:01:23] [Server thread/WARN] [/]: java.lang.IllegalArgumentException
[05:01:23] [Server thread/WARN] [/]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:01:23] [Server thread/WARN] [/]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[05:01:23] [Server thread/WARN] [/]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[05:01:23] [Server thread/WARN] [/]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[05:01:23] [Server thread/WARN] [/]: 	at net.Zrips.CMILib.Reflections.updateInventoryTitle(Reflections.java:1450)
[05:01:23] [Server thread/WARN] [/]: 	at net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:507)
[05:01:23] [Server thread/WARN] [/]: 	at net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:465)
[05:01:23] [Server thread/WARN] [/]: 	at net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114)
[05:01:23] [Server thread/WARN] [/]: 	at com.Zrips.CMI.commands.list.gamerule.openGui(gamerule.java:244)
[05:01:23] [Server thread/WARN] [/]: 	at com.Zrips.CMI.commands.list.gamerule.access$0(gamerule.java:114)
[05:01:23] [Server thread/WARN] [/]: 	at com.Zrips.CMI.commands.list.gamerule$1.pageChange(gamerule.java:127)
[05:01:23] [Server thread/WARN] [/]: 	at net.Zrips.CMILib.GUI.CMIGui$3.click(CMIGui.java:501)
[05:01:23] [Server thread/WARN] [/]: 	at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:276)
[05:01:23] [Server thread/WARN] [/]: 	at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:226)
[05:01:23] [Server thread/WARN] [/]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[05:01:23] [Server thread/WARN] [/]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[05:01:23] [Server thread/WARN] [/]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[05:01:23] [Server thread/WARN] [/]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[05:01:23] [Server thread/WARN] [/]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[05:01:23] [Server thread/WARN] [/]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:01:23] [Server thread/WARN] [/]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:2308)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:936)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:174)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:919)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:913)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:899)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:819)
[05:01:23] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:267)
[05:01:23] [Server thread/WARN] [/]: 	at java.lang.Thread.run(Unknown Source)
```

### Agreements

- [X] My server is supported by CMI.
- [x] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by yuxi7712** [comment]
@Zrips
