### ISSUE TITLE
Unable to use command  /give playerhead

### ISSUE THREAD

**Issue by dildcc** [Zrips/CMI#8331]
### Description of Issue

Unable to use command  /give playerhead

### Version Information

```shell
09:26:46 INFO]: ------------------------------------------------------
[09:26:46 INFO]: CMI plug-in version: 9.6.8.5 SqLite-> 9.6.9.3
[09:26:46 INFO]: CMILib: 1.4.2.3 -> 1.4.4.2
[09:26:46 INFO]: Service service version: Leaves 1.20.2-R0.1-SNAPSHOT-
[09:26:46 INFO]: CMI economy：Starting:1.7.3-b CMI Talk: Starting
[09:26:46 INFO]: Modules -> 55 already used: tablist, ranks, votifier, namePlates
[09:26:46 INFO]: --------------------------------------------------------
```

### Errors

```shell
null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.6.8.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[leaves-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[leaves-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:996) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[leaves-1.20.2.jar:git-Leaves-"eb
05f46"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[leaves-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2218) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2178) ~[?
:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1350) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1298) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[leaves-1.20.2.jar:git-Leaves-"eb05f46"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.Zrips.CMILib.Items.CMIItemStack net.Zrips.CMILib.Items.CMIItemStack.deserialize(java.lang.Strin
g, net.Zrips.CMILib.Items.CMIAsyncHead)'
        at com.Zrips.CMI.commands.list.give.processNewMethod(give.java:180) ~[CMI-9.6.8.5[tinksp.cn].jar:?]
        at com.Zrips.CMI.commands.list.give.perform(give.java:267) ~[CMI-9.6.8.5[tinksp.cn].jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:398) ~[CMI-9.6.8.5[tinksp.cn].jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Upgrade, I cannot reproduce this on 1.21 and latest cmi/cmilib, please test again
