### ISSUE TITLE
[Bug] ClassCastExcveption - Scheduler not working

### ISSUE THREAD

**Issue by thomas-ej-worm** [Zrips/CMI#8340]
### Description of Issue

The CMI load process reports a class cast exception:
So the YAML parser isn't able to read the scheduler configuration.

### Version Information

```shell
* PaperMC 1.20.2
* CMILib1.4.4.2
* CMI-9.6.9.3.jar
```

### Errors

```shell
[11:09:44 WARN]: org.bukkit.configuration.InvalidConfigurationException: java.lang.ClassCastException: class org.yaml.snakeyaml.events.CommentEvent cannot be cast to class org.yaml.snakeyaml.events.NodeEvent (org.yaml.snakeyaml.events.CommentEvent and org.yaml.snakeyaml.events.NodeEvent are in unnamed module of loader java.net.URLClassLoader @675d3402)
[11:09:44 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111)
[11:09:44 WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[11:09:44 WARN]: 	at CMILib1.4.4.2.jar//net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:266)
[11:09:44 WARN]: 	at CMILib1.4.4.2.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:49)
[11:09:44 WARN]: 	at CMILib1.4.4.2.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
[11:09:44 WARN]: 	at CMI-9.6.9.3.jar//com.Zrips.CMI.Modules.Sheduler.SchedulerManager.load(SchedulerManager.java:70)
[11:09:44 WARN]: 	at CMI-9.6.9.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1707)
[11:09:44 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[11:09:44 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[11:09:44 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[11:09:44 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[11:09:44 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644)
[11:09:44 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[11:09:44 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[11:09:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:09:44 WARN]: Caused by: java.lang.ClassCastException: class org.yaml.snakeyaml.events.CommentEvent cannot be cast to class org.yaml.snakeyaml.events.NodeEvent (org.yaml.snakeyaml.events.CommentEvent and org.yaml.snakeyaml.events.NodeEvent are in unnamed module of loader java.net.URLClassLoader @675d3402)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:200)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:359)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:344)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:277)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
[11:09:44 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
[11:09:44 WARN]: 	... 18 more
[11:09:44 INFO]: Failed to load Schedules.yml! Backup have been saved into plugins/CMILib/FileBackups/2023-12-22 11-09-44 Schedules.yml
[11:09:44 WARN]: org.bukkit.configuration.InvalidConfigurationException: java.lang.ClassCastException: class org.yaml.snakeyaml.events.CommentEvent cannot be cast to class org.yaml.snakeyaml.events.NodeEvent (org.yaml.snakeyaml.events.CommentEvent and org.yaml.snakeyaml.events.NodeEvent are in unnamed module of loader java.net.URLClassLoader @675d3402)
[11:09:44 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111)
[11:09:44 WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[11:09:44 WARN]: 	at CMILib1.4.4.2.jar//net.Zrips.CMILib.FileHandler.ConfigReader.getyml(ConfigReader.java:266)
[11:09:44 WARN]: 	at CMILib1.4.4.2.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:49)
[11:09:44 WARN]: 	at CMILib1.4.4.2.jar//net.Zrips.CMILib.FileHandler.ConfigReader.<init>(ConfigReader.java:40)
[11:09:44 WARN]: 	at CMI-9.6.9.3.jar//com.Zrips.CMI.Modules.Sheduler.SchedulerManager.load(SchedulerManager.java:70)
[11:09:44 WARN]: 	at CMI-9.6.9.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1707)
[11:09:44 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[11:09:44 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[11:09:44 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[11:09:44 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[11:09:44 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644)
[11:09:44 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[11:09:44 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
[11:09:44 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[11:09:44 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:09:44 WARN]: Caused by: java.lang.ClassCastException: class org.yaml.snakeyaml.events.CommentEvent cannot be cast to class org.yaml.snakeyaml.events.NodeEvent (org.yaml.snakeyaml.events.CommentEvent and org.yaml.snakeyaml.events.NodeEvent are in unnamed module of loader java.net.URLClassLoader @675d3402)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:200)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:359)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:344)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:277)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
[11:09:44 WARN]: 	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575)
[11:09:44 WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104)
[11:09:44 WARN]: 	... 18 more
[11:09:44 ERROR]: Cannot load plugins/CMI/Settings/Schedules.yml
org.bukkit.configuration.InvalidConfigurationException: java.lang.ClassCastException: class org.yaml.snakeyaml.events.CommentEvent cannot be cast to class org.yaml.snakeyaml.events.NodeEvent (org.yaml.snakeyaml.events.CommentEvent and org.yaml.snakeyaml.events.NodeEvent are in unnamed module of loader java.net.URLClassLoader @675d3402)
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at com.Zrips.CMI.Modules.Sheduler.SchedulerManager.load(SchedulerManager.java:129) ~[CMI-9.6.9.3.jar:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1707) ~[CMI-9.6.9.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-226]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-226]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-226]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-226]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-226]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.yaml.snakeyaml.events.CommentEvent cannot be cast to class org.yaml.snakeyaml.events.NodeEvent (org.yaml.snakeyaml.events.CommentEvent and org.yaml.snakeyaml.events.NodeEvent are in unnamed module of loader java.net.URLClassLoader @675d3402)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:200) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeKeyNode(Composer.java:359) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:344) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:277) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157) ~[snakeyaml-2.2.jar:?]
	at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.2.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	... 17 more
```
```


### Relevant Config Sections

```yaml
AnnounceServerQuests:
  Enabled: true
  MinPlayers: 1
  FeedBack: true
  Delay: 1200
  Repeat: true
  Randomize: false
  Commands:
  - broadcast! {#pizza} Server Quests:
  - broadcast! {#pizza}================
  - broadcast! {#pizza}
  - broadcast! {#chileanfire}1. Die Welt bevölkern
  - broadcast! {#sundance}Zwei Zombie-Villager in der
  - broadcast! {#sundance}Community-Bauwelt heilen
  - broadcast! {#sundance}und Nachwuchs erzeugen.
  - broadcast! {#forestgreen}Belohnung: {#earlsgreen}Freischaltung des Community-Spawn
  - broadcast! {#pizza}
  - broadcast! {#chileanfire}2. Aufbruch ins End
  - broadcast! {#sundance}12 Enderaugen sammeln und
  - broadcast! {#sundance}einen gemeinsamen Sieg über
  - broadcast! {#sundance}den Enderdrachen organisieren.
  - broadcast! {#forestgreen}Belohnung: {#earlsgreen}Freischaltung der End-Farmwelt.
  - broadcast! {#forestgreen}Belohnung: {#earlsgreen}Bruchstück des Dracheneis für jeden Kampfteilnehmer.
```
```


### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by thomas-ej-worm** [comment]
Sorry, it was my fault.
I use color codes in the commands. The parser of SnakeYAML interprets them as comments. Surrounding commands with quotes works.
