### ISSUE TITLE
Warning at server startup

### ISSUE THREAD

**Issue by xPoyraz** [Zrips/CMI#8341]
### Description of Issue

Cmi sends a warning at server startup

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.9.3 BungeeCord CMIB  MySQL
CMILib: 1.4.4.2
Sunucu: Purpur(2107) 1.20.4-R0.1-SNAPSHOT-
CMI ekonomisi: Devre dışı Kasa: 1.7.3-CMI CMI sohbeti: Devre dışı
Modüller -> 26 Etkin 33 Devre dışı: spawnerProximity, cuffed, customMessages, mirror, tablist, moneyCheque, skin, noTarget, elytraBoost, cmiPlaytime, bossBarCompass, playerCombat, votifier, shulkerBackpack, headDrop, spawnerCharge, namePlates, timedCommands, homeInteractions, launchPad, portals, anvilRenameColor, jail, spawners, paintingEditor, playerChatTag, kits, flightCharge, deathMessages, worldLimitsElytra, worldLimits, ranks, firstJoinMessages
--------------------------------------------------
```

### Errors

```shell
java.lang.NoSuchFieldException: byKey
  	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Reflections.manageEnchantment(Reflections.java:345)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Modules.Enchants.EnchantManager.disableEnchantsOnLoad(EnchantManager.java:103)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1726)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
  	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
  	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562)
  	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676)
  	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
  	at java.base/java.lang.Thread.run(Thread.java:842)
  java.lang.NoSuchFieldException: byName
  	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Reflections.manageEnchantment(Reflections.java:362)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Modules.Enchants.EnchantManager.disableEnchantsOnLoad(EnchantManager.java:103)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1726)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
  	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
  	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562)
 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676)
  	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
  	at java.base/java.lang.Thread.run(Thread.java:842)
  java.lang.NoSuchFieldException: byKey
  	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Reflections.manageEnchantment(Reflections.java:345)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Modules.Enchants.EnchantManager.disableEnchantsOnLoad(EnchantManager.java:103)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1726)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
  	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
  	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562)
  	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676)
  	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
  	at java.base/java.lang.Thread.run(Thread.java:842)
  java.lang.NoSuchFieldException: byName
  	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Reflections.manageEnchantment(Reflections.java:362)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.Modules.Enchants.EnchantManager.disableEnchantsOnLoad(EnchantManager.java:103)
  	at CMI-9.6.9.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1726)
  	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
  	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
  	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
  	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651)
  	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562)
  	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676)
  	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
  	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
  	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1146)
  	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
  	at java.base/java.lang.Thread.run(Thread.java:842)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Resolved with latest builds. By "resolved" I mean that disabling enchants isn't possible anymore on newer server versions due to Minecraft code change, we might come up with solution down the road, but for now its at disabled stage.
