### ISSUE TITLE
CMIHologram issued with mythicdungeons.

### ISSUE THREAD

**Issue by Ecilpse** [Zrips/CMI#8342]
### Description of Issue

i use mythicdungeon plugin which create instance dungeon world.
When dungeon ends, mythicdungeon deletes the world.
after delete world, other plugin output errors about cmi holograms.

### Version Information

```shell
9.6.9.1
1.4.4.0
purpur 1.20.2 RO.1 SNAPSHOT
```

### Errors

```shell
[01:15:32] [Server thread/WARN]: [MythicLib] Task #1743301 for MythicLib v1.6.2-SNAPSHOT generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getName()" because the return value of "com.Zrips.CMI.Modules.Holograms.CMIHologram.getWorld()" is null
	at com.Zrips.CMI.Modules.Holograms.HologramManager.removeChunkRecords(HologramManager.java:190) ~[CMI-9.6.9.1.jar:?]
	at com.Zrips.CMI.Modules.Holograms.HologramManager.removeHolo(HologramManager.java:968) ~[CMI-9.6.9.1.jar:?]
	at io.lumine.mythic.lib.hologram.factory.CMIHologramFactory$CMIHologram.despawn(CMIHologramFactory.java:66) ~[MythicLib-dist-1.6.2-20231127.001116-28.jar:?]
	at io.lumine.mythic.lib.listener.option.GameIndicators$1.run(GameIndicators.java:91) ~[MythicLib-dist-1.6.2-20231127.001116-28.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1497) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should get a fix with next update
