### ISSUE TITLE
warn cmi

### ISSUE THREAD

**Issue by livxbox5** [Zrips/CMI#8377]
### Description of Issue

![cmi big](https://github.com/Zrips/CMI/assets/76809274/8fbf8193-c189-46c6-a45e-14018053f928)

### Version Information

```shell
[13:13:05 INFO]: --------------------------------------------------
[13:13:05 INFO]: Версия плагина CMI: 9.6.9.6 Velocity CMIB  SqLite
[13:13:05 INFO]: CMILib: 1.4.4.4
[13:13:05 INFO]: Версия сервера: Paper(381) 1.20.4-R0.1-SNAPSHOT-
[13:13:05 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMI(CMIEInjector)CMI Чат: Включено
[13:13:05 INFO]: Модули -> 58 включено 1 отключено: votifier
[13:13:05 INFO]: --------------------------------------------------
```

### Errors

```shell
[13:11:21 WARN]: Couldn't look up profile properties for a0cbf343-08b3-3087-a852-a684fe0bc94e
com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 429
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfileUncached(YggdrasilMinecraftSessionService.java:201) ~[authlib-6.0.52.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfile(YggdrasilMinecraftSessionService.java:171) ~[authlib-6.0.52.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fetchProfile(PaperMinecraftSessionService.java:35) ~[paper-1.20.4.jar:git-Paper-381]
        at org.bukkit.craftbukkit.v1_20_R3.profile.CraftPlayerProfile.getUpdatedProfile(CraftPlayerProfile.java:141) ~[paper-1.20.4.jar:git-Paper-381]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Plugins

Vault v1.7.3-CMI Information

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [ ] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Error message doesn't mention CMI, so this could be caused by quite few things, including server itself failing to lookup players information for one or the other reason. Can't do much here without knowing exact cause of this error. Error like this should not affect your gameplay.
