### ISSUE TITLE
Open GUI error

### ISSUE THREAD

**Issue by Reaviik** [Zrips/CMI#8387]
### Description of Issue

`[13:50:18 ERROR] [STDERR]:      at java.base/java.lang.Class.cast(Class.java:3921)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.Reflections.getActiveContainerId(Reflections.java:1324)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.Reflections.updateInventoryTitle(Reflections.java:1417)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:519)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:466)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114)
[13:50:18 ERROR] [STDERR]:      at com.Zrips.CMI.Modules.Kits.KitsManager.openGuiEditorMain(KitsManager.java:2232)
[13:50:18 ERROR] [STDERR]:      at com.Zrips.CMI.Modules.Kits.KitsManager$5.click(KitsManager.java:1231)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:277)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:226)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.2-730181a4/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.2-730181a4/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.2-730181a4/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3396)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.md0f8c6e$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[13:50:18 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[13:50:18 ERROR] [STDERR]: java.lang.IllegalArgumentException: java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
[13:50:18 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:75)
[13:50:18 ERROR] [STDERR]:      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:50:18 ERROR] [STDERR]:      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.Reflections.updateInventoryTitle(Reflections.java:1417)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.updateContent(GUIManager.java:519)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.openGui(GUIManager.java:466)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.CMIGui.open(CMIGui.java:114)
[13:50:18 ERROR] [STDERR]:      at com.Zrips.CMI.Modules.Kits.KitsManager.openGuiEditorMain(KitsManager.java:2232)
[13:50:18 ERROR] [STDERR]:      at com.Zrips.CMI.Modules.Kits.KitsManager$5.click(KitsManager.java:1231)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIManager.processClick(GUIManager.java:277)
[13:50:18 ERROR] [STDERR]:      at net.Zrips.CMILib.GUI.GUIListener.onInventoryClick(GUIListener.java:226)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.2-730181a4/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.2-730181a4/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.2-730181a4/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerPlayNetHandlerMixin.java:3396)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.md0f8c6e$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:770)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:161)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:753)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:747)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:733)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2074)
[13:50:18 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[13:50:18 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[13:50:18 ERROR] [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because the return value of "sun.invoke.util.ValueConversions.primitiveConversion(sun.invoke.util.Wrapper, Object, boolean)" is null
[13:50:18 ERROR] [STDERR]:      at java.base/sun.invoke.util.ValueConversions.unboxInteger(ValueConversions.java:81)
[13:50:18 ERROR] [STDERR]:      at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[13:50:18 ERROR] [STDERR]:      ... 30 more`

### Version Information

```shell
[13:51:59 INFO] [Console]: --------------------------------------------------
[13:51:59 INFO] [Console]: CMI: 9.6.9.3 SqLite-> 
[13:51:59 INFO] [Console]: CMILib: 1.4.4.5 -> 1.4.4.6
[13:51:59 INFO] [Console]: Server: 1.20.1 1.20.1-R0.1-SNAPSHOT-
[13:51:59 INFO] [Console]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[13:51:59 INFO] [Console]: Modules -> 50 enabled 9 disabled: deathMessages, disabledEnchants, customMessages, tablist, ranks, versionCheck, firstJoinMessages, moneyCheque, jail
[13:51:59 INFO] [Console]: --------------------------------------------------
```

### Errors

```shell
error on open kit's gui
```

### Relevant Plugins

1.7.3-b131

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
