### ISSUE TITLE
1.17 NBT bug

### ISSUE THREAD

**Issue by 1470429149** [Zrips/CMI#8392]
### Description of Issue

cmi does not handle nbt correctly and will change the item's nbt

More importantly, when the following error occurs, cmi may modify my nbt data, causing some of my backpack items to not be superimposed.

https://github.com/Zrips/CMI/assets/96332168/59107b13-3ce4-44a8-bcae-c75fd93f7953

### Version Information

```shell
[14:12:41 INFO]: --------------------------------------------------
[14:12:41 INFO]: CMI 插件版本: 9.6.9.8 SqLite
[14:12:41 INFO]: CMILib: 1.4.4.6 
[14:12:41 INFO]: 服务器版本: Paper(408) 1.17.1-R0.1-SNAPSHOT-
[14:12:41 INFO]: CMI 经济: 启用 经济: 1.7.3-CMI CMI 聊天: 禁用 
[14:12:41 INFO]: 模块 -> 58 已启用 1 已禁用: votifier
[14:12:41 INFO]: --------------------------------------------------
```

### Errors

```shell
[10:51:03] [Server thread/WARN]: TouHouCirnosuki moved too quickly! -90.45499999999993,-17.0,-105.46999999999935
[10:51:16] [Server thread/INFO]: Opening the menu main.yml to TouHouCirnosuki.
[10:51:19] [User Authenticator #3/INFO]: UUID of player weihuabinggan is 97140ce4-4f23-3d57-9449-413d824f23c7
[10:51:19] [Server thread/INFO]: weihuabinggan joined the game
[10:51:19] [Server thread/INFO]: weihuabinggan[/113.65.31.179:44667] logged in with entity id 989 at ([world]4933.5186, 51.0, 5049.379)
[10:51:20] [Craft Scheduler Thread - 28 - CMILib/WARN]: [CMILib] Plugin CMILib v1.4.4.6 generated an exception while executing task 14248
java.lang.NoClassDefFoundError: com/Zrips/CMI/NBT/v1_17_R1$2
	at com.Zrips.CMI.NBT.v1_17_R1.updatePlayerViaPackets(v1_17_R1.java:1092) ~[CMI-9.6.9.8.jar:?]
	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:129) ~[CMI-9.6.9.8.jar:?]
	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:106) ~[CMI-9.6.9.8.jar:?]
	at com.Zrips.CMI.Modules.Skin.SkinListener.lambda$1(SkinListener.java:38) ~[CMI-9.6.9.8.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-408]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-408]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.NBT.v1_17_R1$2
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-408]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 10 more
[10:51:20] [Server thread/INFO]: Opening the menu main.yml to lianhua.
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:20] [Server thread/WARN]: TouHouCirnosuki moved too quickly! 119.51200000000063,0.0625,-6.212999999999738
[10:51:23] [Server thread/INFO]: Opening the menu main.yml to lianhua.
[10:51:27] [Server thread/INFO]: Named entity EntityZombie['[普通] 腐朽村民'/995, uuid='a6e220cd-c515-4b02-a97a-e4fb2f8b1f62', l='ServerLevel[world]', x=10044.50, y=4.00, z=10040.50, cpos=[627, 627], tl=14, v=true, rR=null] died: [普通] 腐朽村民 was slain by TouHouCirnosuki using [太阳之光战斧 ]
```

### Relevant Config Sections

```yaml
null
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by 1470429149** [comment]
Please wait a moment. There are other errors. I can only vaguely understand that this is an nbt error.
------------------------------------------------------------------------------------------------------------
[10:51:45] [Server thread/INFO]: [MMOItems] Successfully gave 巨龙的弧  to lianhua.
[10:51:45] [Server thread/INFO]: [MMOItems] Successfully gave 善变的鱼竿  to lianhua.
[10:51:45] [Server thread/INFO]: weihuabinggan issued server command: /cmi skin weihuabinggan
[10:51:45] [Craft Scheduler Thread - 28 - CMI/WARN]: [CMI] Plugin CMI v9.6.9.8 generated an exception while executing task 15394
java.lang.NoClassDefFoundError: com/Zrips/CMI/NBT/v1_17_R1$2
	at com.Zrips.CMI.NBT.v1_17_R1.updatePlayerViaPackets(v1_17_R1.java:1092) ~[CMI-9.6.9.8.jar:?]
	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:129) ~[CMI-9.6.9.8.jar:?]
	at com.Zrips.CMI.Modules.Skin.SkinManager.applySkin(SkinManager.java:106) ~[CMI-9.6.9.8.jar:?]
	at com.Zrips.CMI.commands.list.skin$3.run(skin.java:135) ~[CMI-9.6.9.8.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-408]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-408]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-408]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.Zrips.CMI.NBT.v1_17_R1$2
	... 10 more
----------------------------------------------------------------------------------------------------------------------

**Comment by 1470429149** [comment]
![image](https://github.com/Zrips/CMI/assets/96332168/d2dea569-1e86-4d04-92ce-974f53537e79)
I noticed that my video might not open properly, so I took a screenshot and you can see that the items cannot be overlaid.

**Comment by 1470429149** [comment]
I have tried using the itemnbt command to check which nbt data has been modified by cmi, but because the nbt is too long, the display is incomplete and I cannot perform manual comparison. I am very sorry.

**Comment by 1470429149** [comment]
I know this bug exists in CMI 9.6.9.6 - CMI 9.6.9.8
I did not encounter this error when using CMI9.2.5.1

**Comment by Zrips** [comment]
Should be resolved with next update
