### ISSUE TITLE
toast command bug

### ISSUE THREAD

**Issue by 1470429149** [Zrips/CMI#8393]
### Description of Issue

Unable to use cmi toast command

### Version Information

```shell
[14:31:20 INFO]: --------------------------------------------------
[14:31:20 INFO]: CMI 插件版本: 9.6.9.8 SqLite
[14:31:20 INFO]: CMILib: 1.4.4.6 
[14:31:20 INFO]: 服务器版本: Paper(408) 1.17.1-R0.1-SNAPSHOT-
[14:31:20 INFO]: CMI 经济: 启用 经济: 1.7.3-CMI CMI 聊天: 禁用 
[14:31:20 INFO]: 模块 -> 58 已启用 1 已禁用: votifier
```

### Errors

```shell
> cmi toast all qoqoqo
[14:29:27 WARN]: java.lang.NoClassDefFoundError: net/minecraft/world/level/storage/loot/LootDataManager
[14:29:27 WARN]:        at CMILib1.4.4.6.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:2047)
[14:29:27 WARN]:        at CMILib1.4.4.6.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[14:29:27 WARN]:        at CMILib1.4.4.6.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[14:29:27 WARN]:        at CMI-9.6.9.8.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:108)
[14:29:27 WARN]:        at CMI-9.6.9.8.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:403)
[14:29:27 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:29:27 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:29:27 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[14:29:27 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832)
[14:29:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:529)
[14:29:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:491)
[14:29:27 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[14:29:27 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[14:29:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[14:29:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:29:27 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.storage.loot.LootDataManager
[14:29:27 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[14:29:27 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[14:29:27 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[14:29:27 WARN]:        ... 15 more
[14:29:27 WARN]: java.lang.NoClassDefFoundError: net/minecraft/world/level/storage/loot/LootDataManager
[14:29:27 WARN]:        at CMILib1.4.4.6.jar//net.Zrips.CMILib.Reflections.loadAdvancement(Reflections.java:2047)
[14:29:27 WARN]:        at CMILib1.4.4.6.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.add(CMIAdvancement.java:268)
[14:29:27 WARN]:        at CMILib1.4.4.6.jar//net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:253)
[14:29:27 WARN]:        at CMI-9.6.9.8.jar//com.Zrips.CMI.commands.list.toast.perform(toast.java:112)
[14:29:27 WARN]:        at CMI-9.6.9.8.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:403)
[14:29:27 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:29:27 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:29:27 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869)
[14:29:27 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832)
[14:29:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:529)
[14:29:27 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:491)
[14:29:27 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[14:29:27 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[14:29:27 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[14:29:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:29:27 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.storage.loot.LootDataManager
[14:29:27 WARN]:        ... 15 more
[14:29:27 WARN]: Unexpected exception while parsing console command "cmi toast all qoqoqo"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.6.9.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-408]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-408]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: advancement
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141) ~[patched_1.17.1.jar:git-Paper-408]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:2152) ~[patched_1.17.1.jar:git-Paper-408]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.grant(CMIAdvancement.java:277) ~[CMILib1.4.4.6.jar:?]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:254) ~[CMILib1.4.4.6.jar:?]
        at com.Zrips.CMI.commands.list.toast.perform(toast.java:112) ~[CMI-9.6.9.8.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:403) ~[CMI-9.6.9.8.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-408]
        ... 9 more
[14:29:27 INFO]: Named entity EntityGiantZombie['巨人'/32110, uuid='ee8c1b21-7c88-4c9b-9da1-25aff5f72a07', l='ServerLevel[he5]', x=640.36, y=85.00, z=3.80, cpos=[40, 0], tl=18, v=true, rR=null] died: 巨人 was slain by lianhua using [弗雷德的战斧 ]
```

### Relevant Config Sections

```yaml
null
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by 1470429149** [comment]
I know this bug exists in CMI 9.6.9.6 - CMI 9.6.9.8
I did not encounter this error when using CMI9.2.5.1

**Comment by Zrips** [comment]
Should get a fix with next CMILib update
