### ISSUE TITLE
ReportedNbtException / IOException: Invalid tag id

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#8426]
### Description of Issue

When using the command /cmi playtime [player] it shows 0 seconds playtime, and there is an error message in the console/logs.

### Version Information

```shell
--------------------------------------------------
CMI plugin versjon: 9.6.9.9 BungeeCord CMIB  MySQL
CMILib: 1.4.4.7 
Server: Paper(393) 1.20.4-R0.1-SNAPSHOT-
CMI økonomi: Aktivert Vault: 1.7.3-CMI CMI Chat: Aktivert 
Moduler -> 58 aktivert 1 deaktivert: chatBubble
--------------------------------------------------
```

### Errors

```shell
[17:36:08] [Server thread/WARN]: net.minecraft.nbt.ReportedNbtException: Loading NBT data
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:388)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NBTCompressedStreamTools.c(NBTCompressedStreamTools.java:376)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:306)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:296)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.NBT.v1_20_R3.getNBTTagC(v1_20_R3.java:238)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.NBT.v1_20_R3.getTickLived(v1_20_R3.java:492)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.Containers.CMIUser.getTotalPlayTime(CMIUser.java:1086)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.commands.list.playtime.perform(playtime.java:39)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:403)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[17:36:08] [Server thread/WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:435)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2231)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$16(PlayerConnection.java:2191)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[17:36:08] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1452)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1429)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1352)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1330)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1220)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[17:36:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[17:36:08] [Server thread/WARN]: Caused by: java.io.IOException: Invalid tag id: 31
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.TagType$1.createException(TagType.java:39)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.TagType$1.load(TagType.java:44)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.TagType$1.c(TagType.java:37)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:382)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.readUnnamedTag(NbtIo.java:376)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.read(NbtIo.java:306)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.nbt.NbtIo.read(NbtIo.java:296)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.NBT.v1_20_R3.getNBTTagC(v1_20_R3.java:238)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.NBT.v1_20_R3.getTickLived(v1_20_R3.java:492)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.Containers.CMIUser.getTotalPlayTime(CMIUser.java:1086)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.commands.list.playtime.perform(playtime.java:39)
[17:36:08] [Server thread/WARN]: 	at CMI.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:403)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987)
[17:36:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[17:36:08] [Server thread/WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:435)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:336)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.commands.Commands.performCommand(Commands.java:323)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2231)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2191)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59)
[17:36:08] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1452)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1429)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1352)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1330)
[17:36:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220)
[17:36:08] [Server thread/WARN]: 	... 2 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should get a fix with next update
