### ISSUE TITLE
Problem with metacreator from mythicdungeons - Hologram

### ISSUE THREAD

**Issue by dmgimpact** [Zrips/CMI#8427]
### Description of Issue

Problem with editor MythicDungeons with holograms from CMI

### Version Information

```shell
[18:28:15 INFO]: CMI: 9.6.9.9 SqLite
[18:28:15 INFO]: CMILib: 1.4.4.7 
[18:28:15 INFO]: Server: Purpur(2127) 1.20.4-R0.1-SNAPSHOT-
[18:28:15 INFO]: CMI economy: Włączone Vault: 1.7.3-CMI CMI Chat: Wyłączone 
[18:28:15 INFO]: Modules -> 48 enabled 11 disabled: spawnerProximity, cuffed, tablist, ranks, playerCombat, votifier, spawners, spawnerCharge, playerChatTag, bossBarCompass, totemBehavior
```

### Errors

```shell
[18:20:52 WARN]: [CMI] Task #3501 for CMI v9.6.9.9 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R3.CraftWorld.getHandle()" because the return value of "org.bukkit.Location.getWorld()" is null
        at com.Zrips.CMI.NBT.v1_20_R3.createStand(v1_20_R3.java:658) ~[CMI-9.6.9.9 (1).jar:?]
        at com.Zrips.CMI.NBT.v1_20_R3.spawnHologram(v1_20_R3.java:698) ~[CMI-9.6.9.9 (1).jar:?]
        at com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$5(CMIHologram.java:1954) ~[CMI-9.6.9.9 (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1667) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1546) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2127]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
