### ISSUE TITLE
Circular plugin loading from plugins CMI

### ISSUE THREAD

**Issue by YuanYuanOwO** [Zrips/CMI#8447]
### Description of Issue

Install EcoEnchants Jobs-Reborn CMI in same time.

### Version Information

```shell
cmi version
[15:52:33 INFO]: --------------------------------------------------
[15:52:33 INFO]: CMI: 9.6.10.1 SqLite
[15:52:33 INFO]: CMILib: 1.4.5.0
[15:52:33 INFO]: Server: Paper(405) 1.20.4-R0.1-SNAPSHOT+
[15:52:33 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled
[15:52:33 INFO]: Modules -> 58 enabled 1 disabled: votifier
[15:52:33 INFO]: --------------------------------------------------
```

### Errors

```shell
``
[23:54:09] [Server thread/ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[23:54:09] [Server thread/ERROR]: [SimpleProviderStorage] Circular load order:
[23:54:09] [Server thread/ERROR]: [SimpleProviderStorage]   CMI -> Jobs -> EcoEnchants -> CMI
[23:54:09] [Server thread/ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[23:54:09] [Server thread/ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[23:54:09] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins CMI
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.20.4.jar:git-Paper-405]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:42) ~[paper-1.20.4.jar:git-Paper-405]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-405]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:505) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-405]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-405]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[23:54:10] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2024-01-29_23.54.10-server.txt
``
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update

**Comment by DeEthria** [comment]
It's available again now in connection with Lands
