### ISSUE TITLE
[Error] /toast

### ISSUE THREAD

**Issue by GrimPod** [Zrips/CMI#846]
**ERROR (DELETE IF YOU HAVE NO ERROR):**

**/toast -**
errors when setting an icon to any item with an underscore
E.g. Diamond_Pickaxe, Crafting_Table etc...

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
`[14:15:36 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.8.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-209]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-209]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:725) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1768) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-209]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-209]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: net.minecraft.server.v1_13_R2.ResourceKeyInvalidException: Non [a-z0-9/._-] character in path of location: minecraft:diamond pickaxe
        at net.minecraft.server.v1_13_R2.MinecraftKey.<init>(SourceFile:38) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.MinecraftKey.<init>(SourceFile:43) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.ChatDeserializer.b(SourceFile:127) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.ChatDeserializer.i(SourceFile:140) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:110) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.AdvancementDisplay.a(SourceFile:97) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.Advancement$SerializedAdvancement.a(Advancement.java:323) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.AdvancementDataWorld.lambda$static$0(AdvancementDataWorld.java:30) ~[patched_1.13.1.jar:git-Paper-209]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:497) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:522) ~[patched_1.13.1.jar:git-Paper-209]
        at net.minecraft.server.v1_13_R2.ChatDeserializer.a(SourceFile:542) ~[patched_1.13.1.jar:git-Paper-209]
        at com.Zrips.CMI.NBT.v1_13_R2.loadAdvancement(v1_13_R2.java:1686) ~[?:?]
        at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.add(CMIAdvancement.java:137) ~[?:?]
        at com.Zrips.CMI.Modules.Advancements.CMIAdvancement.show(CMIAdvancement.java:122) ~[?:?]
        at com.Zrips.CMI.commands.list.toast.perform(toast.java:108) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-209]
        ... 15 more`

**Cmi Version (using`/cmi version`):** 
8.0.10.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
git-paper-209

**Comment by Zrips** [comment]
Will be fixed with next build.
