### ISSUE TITLE
This plugin caused a BungeCord error. When installing CMI and CMILIB, if the number of servers is greater than 1, it will cause other players to be unable to enter the server.

### ISSUE THREAD

**Issue by Zxblll843192** [Zrips/CMI#8464]
### Description of Issue

This plugin caused a BungeCord error. When installing CMI and CMILIB, if the number of servers is greater than 1, it will cause other players to be unable to enter the server.

### Version Information

```shell
CMI Version : 9.6.9.8
```

### Errors

```shell
The error message for BungeCord is as follows:
java.lang.IllegalArgumentException: Team CMINP0 already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:281) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:129) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at me.taucu.reconnect.net.DownstreamInboundHandler.channelRead(DownstreamInboundHandler.java:155) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-559.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:4a3846a:559]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Do you have any plugins on bungee side which controls players teams? You could try resolving this issue by disabling team management from CMI in its config file on all servers. But as of testing this issue doesn't exist on a clean waterfall setup with CMI
