### ISSUE TITLE
delay! %cmi_random_1_120% in schedule causes error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#8476]
### Description of Issue

Hi, there's error in console on server startup.

### Version Information

```shell
[01:01:25 INFO]: CMI: 9.6.10.4 Unknown  SqLite
[01:01:25 INFO]: CMILib: 1.4.4.0 -> 1.4.5.0
[01:01:25 INFO]: Server: Purpur(2062) 1.20.1-R0.1-SNAPSHOT-
[01:01:25 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[01:01:25 INFO]: Modules -> 46 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, deathMessages, disabledEnchants, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[01:01:25 INFO]: --------------------------------------------------
```

### Errors

```shell
[00:57:49] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "%cmi_random_1_120%"
[00:57:49] [Server thread/WARN]: 	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[00:57:49] [Server thread/WARN]: 	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[00:57:49] [Server thread/WARN]: 	at java.base/java.lang.Double.parseDouble(Double.java:651)
[00:57:49] [Server thread/WARN]: 	at CMI-9.6.10.4.jar//com.Zrips.CMI.Modules.Sheduler.Schedule.setCommands(Schedule.java:132)
[00:57:49] [Server thread/WARN]: 	at CMI-9.6.10.4.jar//com.Zrips.CMI.Modules.Sheduler.SchedulerManager.load(SchedulerManager.java:269)
[00:57:49] [Server thread/WARN]: 	at CMI-9.6.10.4.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1687)
[00:57:49] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[00:57:49] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[00:57:49] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[00:57:49] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[00:57:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656)
[00:57:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567)
[00:57:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640)
[00:57:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439)
[00:57:49] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[00:57:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1116)
[00:57:49] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[00:57:49] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```
```


### Relevant Config Sections

```yaml
in scheduler
test:
  Enabled: true
  MinPlayers: 0
  FeedBack: true
  Repeat: true
  Delay: 585
  Commands:
  - delay! %cmi_random_1_120%
  - say test
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update. And keep up to date with CMILib and CMI
