### ISSUE TITLE
very lag in mspt

### ISSUE THREAD

**Issue by imtorich** [Zrips/CMI#8485]
### Description of Issue

For the umpteenth time I've complained about CMI's performance, but, they kind of hear me, just like last time with the kits. Also look, something is not normal on the new CMI versions.

Spark report: https://spark.lucko.me/0ycwcsHYPr

### Version Information

```shell
[21:17:58 INFO]: --------------------------------------------------
[21:17:58 INFO]: CMI plugin version: 9.6.10.5 SqLite
[21:17:58 INFO]: CMILib: 1.4.5.1 
[21:17:58 INFO]: Server version: Purpur(2149) 1.20.4-R0.1-SNAPSHOT-
[21:17:58 INFO]: CMI Economy: On Vault Version: 1.7.3-CMICMI Chat: Off 
[21:17:58 INFO]: Modules -> 23 enabled 36 disabled: spawnerProximity, cuffed, customMessages, mirror, tablist, armorEffects, moneyCheque, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, chatBubble, votifier, shulkerBackpack, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, signEdit, hpBossBar, holograms, anvilRenameColor, jail, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, disabledEnchants, worldLimitsElytra, ranks, firstJoinMessages, silentChest
[21:17:58 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by imtorich** [comment]
was measured over 100 ticks, based on tickmonitor.

**Comment by imtorich** [comment]
and bug
`> sudo Kamilla1967 c:wd
[14:06:08 ERROR]: [ru.brikster.chatty.chat.executor.LegacyEventExecutor] Cannot handle chat event
java.lang.IllegalStateException: ChattyMessageEvent may only be triggered asynchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at ru.brikster.chatty.chat.executor.LegacyEventExecutor.handleFinishedEarlyContextEvent(LegacyEventExecutor.java:204) ~[Chatty-3.0.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1070.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2149]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2389) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.chat(CraftPlayer.java:676) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at com.Zrips.CMI.commands.list.sudo.perform(sudo.java:57) ~[CMI-9.6.10.5.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401) ~[CMI-9.6.10.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:998) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:541) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1548) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2149]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
> `

**Comment by Zrips** [comment]
Error message isn't really issue with CMI, its issue with ru.brikster.chatty.chat which fails to perform chat command. We are just triggering basic Player@chat(message) method and after that all is taken and done by server itself and then your chat plugin intercept that event and fails to process it.
Performance issue should be mitigated with next version.
