### ISSUE TITLE
issue with interactive commands

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8514]
### Description of Issue

Some of our interactive commands stops working and throw an error in console

![Snag_123800](https://github.com/Zrips/CMI/assets/12080017/98810a71-e688-4dcd-83bc-86cee55dfb78)

### Version Information

```shell
6.9.10.7
```

### Errors

```shell
[00:54:43] [Server thread/WARN]: [CMI] Task #21179390 for CMI v9.6.10.7 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing 'minecraft:fill 36 63 282 40 63 286 minecraft:air replace minecraft:bookshelf' in org.bukkit.craftbukkit.v1_20_R3.command.VanillaCommandWrapper(fill)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-436]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1094) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1209) ~[CMI_9.6.10.7.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1009) ~[CMI_9.6.10.7.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:424) ~[CMI_9.6.10.7.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:324) ~[CMI_9.6.10.7.jar:?]
	at com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:278) ~[CMI_9.6.10.7.jar:?]
	at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandListener$2.run(InteractiveCommandListener.java:137) ~[CMI_9.6.10.7.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-436]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-436]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-436]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.PlayerConnection.a(net.minecraft.network.protocol.Packet, net.minecraft.network.PacketSendListener)" because "this.c" is null
	at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:2087) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.sendSystemMessage(ServerPlayer.java:2082) ~[?:?]
	at net.minecraft.commands.CommandSourceStack.sendFailure(CommandSourceStack.java:384) ~[?:?]
	at net.minecraft.commands.CommandSourceStack.sendFailure(CommandSourceStack.java:379) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:352) ~[?:?]
	at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:318) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) ~[paper-1.20.4.jar:git-Paper-436]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 16 more
```

### Relevant Config Sections

```yaml
interactive commands.yml

ZauberTischLevel1:
  Locations:
  - world;35;65;286
  Commands:
  - asFakeOp! minecraft:fill 36 63 282 40 63 286 minecraft:air replace minecraft:bookshelf
  - delay! 0.5
  - asFakeOp! minecraft:fill 36 63 286 37 63 286 minecraft:bookshelf replace minecraft:air
  - asFakeOp! minecraft:fill 36 63 285 36 63 285 minecraft:bookshelf replace minecraft:air
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
tring a bit arround shows that this happens now in the follow case:
`asFakeOp! minecraft:fill 36 63 282 40 63 286 minecraft:air replace minecraft:bookshelf`

the command tries to set these bookshelfs replace all found with air.
problem now comes if no bookshelfs were found resulting in nothing was replaced.
therefor CMI now throws this error :§

This was not happening before

**Comment by Zrips** [comment]
issue is with server trying to send that error message to player which doesn't really exist and creates this error message. Can't say I have a working solution here.

**Comment by CloudeLecaw** [comment]
we found a workarround
We added an extra line of bookshelfs that allways get set or reseted.
so it never is the case that no bookshelfs can be found that would be replaced with air.
the extra row bookshelfs is hidden so the player does not see them :)
