### ISSUE TITLE
/kill & /suicide error cmi is laster ver

### ISSUE THREAD

**Issue by Jyun5978** [Zrips/CMI#8535]
### Description of Issue

The server software I'm using is LeavesMC, which is a fork of Paper.
More information
https://github.com/LeavesMC/Leaves

![image](https://github.com/Zrips/CMI/assets/22559124/efc66802-716f-4d31-8646-b389a419fb95)

### Version Information

```shell
[01:10:28 INFO]: --------------------------------------------------
[01:10:28 INFO]: CMI Plugin Version: 9.6.10.9 SqLite
[01:10:28 INFO]: CMILib: 1.4.5.2
[01:10:28 INFO]: Server: Paper 1.20.4-R0.1-SNAPSHOT-
[01:10:28 INFO]: CMI economy: Vault enabled: 1.7.3-CMI(CMIEInjector) CMI chat: enabled
[01:10:28 INFO]: Modules -> 58 opened 1 closed: votifier
[01:10:28 INFO]: --------------------------------------------------]
```

### Errors

```shell
[01:12:28 INFO]: NikolaJyun_ issued server command: /kill
[01:12:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.6.10.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:992) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2244) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$13(ServerGamePacketListenerImpl.java:2204) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1500) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/damage/DamageType
	at com.Zrips.CMI.commands.list.suicide.perform(suicide.java:62) ~[CMI-9.6.10.9.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401) ~[CMI-9.6.10.9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.damage.DamageType
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at com.Zrips.CMI.commands.list.suicide.perform(suicide.java:62) ~[CMI-9.6.10.9.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401) ~[CMI-9.6.10.9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more
```

### Relevant Config Sections

```yaml
[01:13:28 INFO]: NikolaJyun_ issued server command: /suicide
[01:13:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.6.10.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:992) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2244) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$13(ServerGamePacketListenerImpl.java:2204) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1500) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"c8ddbee"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/damage/DamageType
	at com.Zrips.CMI.commands.list.suicide.perform(suicide.java:62) ~[CMI-9.6.10.9.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401) ~[CMI-9.6.10.9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.damage.DamageType
	at com.Zrips.CMI.commands.list.suicide.perform(suicide.java:62) ~[CMI-9.6.10.9.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401) ~[CMI-9.6.10.9.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more
```

### Relevant Plugins

Vault1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This generally should be solved by updating your server, with paper builds any later version will not have this issue, with your custom fork it might need some time before this issue is fixed or I will need to make special exception for it to just avoid error messages for time being

**Comment by Jyun5978** [comment]
For certain reasons, the server needs to use LeavesMC, so switching to Paper is not an option. If possible, I hope there will be time to help fix this issue!

**Comment by Jyun5978** [comment]
I have updated LeavesMC to the latest version, and the issue has been resolved!
