### ISSUE TITLE
Error with PlaceholderAPI expansion OtherPlayer in customaliases.

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8540]
### Description of Issue
When i use my custom/checkplayer without any arugment i get a bit error in console.
The command itself seems to work fine.

i could fine out this doesnt happen when i remove the last line from my custom alias.
interesting point maybe: the last line is normaly for /checkplayer NAME
so it normaly should not be touched?
with the full Custom Alias it oarses this error when /checkaccount is used   while no error appear when i use /checkaccount NAME

### Version Information
![Snag_158dbdf](https://github.com/Zrips/CMI/assets/12080017/68e0b47d-0206-4cff-8a71-0aa8516430c8)

### Errors
```shell
[00:56:18] [Server thread/INFO]: Cloude_Lecaw issued server command: /checkplayer
[00:56:18] [Server thread/INFO]: Papi OtherPlayer Expansion: Parsing error occured. Likely due to invalid use of a placeholder
[00:56:18] [Server thread/INFO]: Identifier string received: uuid_
[00:56:18] [Server thread/INFO]: Stacktrace to follow error msg: Index 1 out of bounds for length 0
[00:56:18] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
[00:56:18] [Server thread/WARN]: 	at com.extendedclip.papi.expansion.otherplayer.OtherPlayerExpansion.getUUID(OtherPlayerExpansion.java:671)
[00:56:18] [Server thread/WARN]: 	at com.extendedclip.papi.expansion.otherplayer.OtherPlayerExpansion.onRequest(OtherPlayerExpansion.java:206)
[00:56:18] [Server thread/WARN]: 	at PlaceholderAPI_2.11.6-Build189.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[00:56:18] [Server thread/WARN]: 	at PlaceholderAPI_2.11.6-Build189.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[00:56:18] [Server thread/WARN]: 	at PlaceholderAPI_2.11.6-Build189.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:703)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:801)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:241)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:156)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:152)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:200)
[00:56:18] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor467.execute(Unknown Source)
[00:56:18] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:56:18] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[00:56:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:56:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:56:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:56:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2206)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[00:56:18] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1455)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1432)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1355)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1506)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[00:56:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[00:56:18] [Server thread/INFO]: Papi OtherPlayer Expansion: Parsing error occured. Likely due to invalid use of a placeholder
[00:56:18] [Server thread/INFO]: Identifier string received: uuid_
[00:56:18] [Server thread/INFO]: Stacktrace to follow error msg: Index 1 out of bounds for length 0
[00:56:18] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
[00:56:18] [Server thread/WARN]: 	at com.extendedclip.papi.expansion.otherplayer.OtherPlayerExpansion.getUUID(OtherPlayerExpansion.java:671)
[00:56:18] [Server thread/WARN]: 	at com.extendedclip.papi.expansion.otherplayer.OtherPlayerExpansion.onRequest(OtherPlayerExpansion.java:206)
[00:56:18] [Server thread/WARN]: 	at PlaceholderAPI_2.11.6-Build189.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[00:56:18] [Server thread/WARN]: 	at PlaceholderAPI_2.11.6-Build189.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[00:56:18] [Server thread/WARN]: 	at PlaceholderAPI_2.11.6-Build189.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:99)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.Placeholders.Placeholder.updatePlaceHolders(Placeholder.java:703)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:801)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:241)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:156)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processAliasCmdsAsPlayer(SpecializedCommandManager.java:152)
[00:56:18] [Server thread/WARN]: 	at CMI_9.6.10.9.jar//com.Zrips.CMI.Modules.Alias.onPreprocessCommand.onCommand(onPreprocessCommand.java:200)
[00:56:18] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor467.execute(Unknown Source)
[00:56:18] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:56:18] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[00:56:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:56:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:56:18] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:56:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2206)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[00:56:18] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1455)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1432)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1355)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1506)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1216)
[00:56:18] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[00:56:18] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Relevant Config Sections
**CustomAlias.yml**
```yaml
CustomAlias:
  checkplayer:
    Cmds:
    - check:$1==null! msg! [playerName] &6Informationen zu [playerName]
    - check:$1!=null! msg! [playerName] &6Informationen zu $1
    - msg! [playerName] &6=========================================
    - check:$1==null! cmi balance [playerName]
    - check:$1!=null! cmi balance $1
    - check:$1==null! cmi playtime [playerName]
    - check:$1!=null! cmi playtime $1
    - check:$1==null! cmi pos [playerName]
    - check:$1!=null! cmi pos $1
    - check:$1==null! cmi votes [playerName]
    - check:$1!=null! cmi votes $1
    - check:$1==null! cmi seen [playerName]
    - check:$1!=null! cmi seen $1
    - check:$1==null! cmi ctellraw [playerName] <T> &fUUID ist&f:&f %cmi_user_uuid%</T><H>SHIFT+LINKSKLICKEN um Deine UUID in den Chat zu kopieren</H><SI>%cmi_user_uuid%</SI>
    - check:$1!=null! cmi ctellraw [playerName] <T> &fUUID ist&f:&f %otherplayer_uuid_$1%</T><H>SHIFT+LINKSKLICKEN um die UUID von $1 in den Chat zu kopieren</H><SI>%otherplayer_uuid_$1%</SI>
    Perm: true
    Tab: true
    CustomTabs:
    - '[playerName]'
```

### Relevant Plugins
- PlaceholderAPI_2.11.6-Build189
- PAPI-Expansion-OtherPlayer_2.1.0

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Due to how specialized commands are being processed it causes some issues with plugins which are not processing malformed placeholders properly. Will add new placeholder as %cmi_user_uuid_$1% which will provide your desired functionality without creating that error message.
