### ISSUE TITLE
Could not pass event PlayerBedEnterEvent

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#8545]
### Description of Issue

There is an error message in the console when players go to bed, so the night will not go faster. The problem must have appeared after version 9.6.10.9, because it worked perfectly fine on 9.6.10.9.

### Version Information

```shell
--------------------------------------------------
CMI plugin versjon: 9.6.11.0 BungeeCord CMIB  MySQL
CMILib: 1.4.5.2 
Server: Paper(450) 1.20.4-R0.1-SNAPSHOT-
CMI økonomi: Aktivert Vault: 1.7.3-CMI CMI Chat: Aktivert 
Moduler -> 58 aktivert 1 deaktivert: chatBubble
--------------------------------------------------
```

### Errors

```shell
[16:15:46] [Server thread/ERROR]: Could not pass event PlayerBedEnterEvent to CMI v9.6.11.0
java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Version.Schedulers.CMITask.cancel()" because the return value of "com.Zrips.CMI.Containers.CMISunMover.getTimeMoverTask()" is null
	at com.Zrips.CMI.utils.TimeManager.moveSun(TimeManager.java:280) ~[CMI.jar:?]
	at com.Zrips.CMI.Containers.SleepStats.onBedEnter(SleepStats.java:250) ~[CMI.jar:?]
	at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerBedEnterEvent(PlayerListeners.java:210) ~[CMI.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor626.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-450]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-450]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-450]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:316) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.level.ServerPlayer.startSleepInBed(ServerPlayer.java:1433) ~[?:?]
	at net.minecraft.world.entity.player.Player.startSleepInBed(Player.java:1555) ~[?:?]
	at net.minecraft.world.level.block.BedBlock.use(BedBlock.java:123) ~[?:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1297) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:581) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1935) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-450]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-450]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Relevant Config Sections

```yaml
Sleeping:
  Speedup:
    Enabled: true
    Worlds: []
    OnlyDurringNight: true
    InfoType: title
    ExcludeAfk: true
    BaseSpeed: 100
    MinSpeed: 5
    MinBeforeSpeeding: 10%
    Inform: true
    InformDelay: 30
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
