### ISSUE TITLE
[Folia] java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by roggy666** [Zrips/CMI#8609]
### Description of Issue

Error on playerjoin on folia

[[20:35:13 INFO]: UUID of player GZDro4ka is 305b7807-2aa9-37c7-8a33-02e3f494eb29
[20:35:13 WARN]: java.lang.UnsupportedOperationException
[20:35:13 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:208)
[20:35:13 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Containers.CMIUser.reapplyNamePlate(CMIUser.java:2667)
[20:35:13 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.AllListeners.UserEvents.processPlayerLogin(UserEvents.java:451)
[20:35:13 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:436)
[20:35:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor576.execute(Unknown Source)
[20:35:13 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[20:35:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[20:35:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:35:13 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:35:13 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[20:35:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[20:35:13 WARN]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:430)
[20:35:13 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.lambda$handleConfigurationFinished$1(ServerConfigurationPacketListenerImpl.java:160)
[20:35:13 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504)
[20:35:13 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434)
[20:35:13 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263)
[20:35:13 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1621)
[20:35:13 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[20:35:13 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[20:35:13 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[20:35:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[20:35:13 INFO]: GZDro4ka[/195.18.12.118:50980] logged in with entity id 1802 at ([world]63.32056611083917, 78.02442408821369, 259.21520262605594)
[20:35:15 INFO]: [CombatLogX] Using non-NMS Paper EntityHandler

### Version Information

```shell
> cmi version
[20:34:34 INFO]: --------------------------------------------------
[20:34:34 INFO]: CMI: 9.7.0.4 SqLite
[20:34:34 INFO]: CMILib: 1.4.6.1 
[20:34:34 INFO]: Server: Folia 1.20.4-R0.1-SNAPSHOT-
[20:34:34 INFO]: CMI economy: Disabled Vault: 1.7.3-b0-folia CMI Chat: Disabled 
[20:34:34 INFO]: Modules -> 58 enabled 1 disabled: votifier
[20:34:34 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be resolved with next update
