### ISSUE TITLE
Folia Error 9.7.0.4

### ISSUE THREAD

**Issue by Speedspencer** [Zrips/CMI#8610]
### Description of Issue

First, on player join, this error pops up. It does nothing.
Second, Respawn Priority doesn't work. 
I suppose this was due to the folia api break playerrespawnevent <- it did not call at all. 
as stated by PaperMC

```Current broken API
Most API that interacts with portals / respawning players / some player login API is broken.
ALL scoreboard API is considered broken (this is global state that I've not figured out how to properly implement yet)
World loading/unloading
Entity#teleport. This will NEVER UNDER ANY CIRCUMSTANCE come back, use teleportAsync
```

### Version Information

```shell
[01:56:33 INFO]: --------------------------------------------------
[01:56:33 INFO]: CMI: 9.7.0.4 SqLite-> 9.7.0.3
[01:56:33 INFO]: CMILib: 1.4.6.1 
[01:56:33 INFO]: Server: Folia 1.20.4-R0.1-SNAPSHOT-
[01:56:33 INFO]: CMI economy: Disabled Vault: 1.7.3-b0-folia CMI Chat: Disabled 
[01:56:33 INFO]: Modules -> 58 enabled 1 disabled: votifier
[01:56:33 INFO]: --------------------------------------------------
```

### Errors

```shell
[01:54:26 WARN]: java.lang.UnsupportedOperationException
[01:54:26 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:208)
[01:54:26 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Containers.CMIUser.reapplyNamePlate(CMIUser.java:2667)
[01:54:26 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.AllListeners.UserEvents.processPlayerLogin(UserEvents.java:451)
[01:54:26 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.AllListeners.UserEvents.onPlayerLogin(UserEvents.java:436)
[01:54:26 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor437.execute(Unknown Source)
[01:54:26 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[01:54:26 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[01:54:26 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[01:54:26 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[01:54:26 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[01:54:26 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[01:54:26 WARN]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:430)
[01:54:26 WARN]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.lambda$handleConfigurationFinished$1(ServerConfigurationPacketListenerImpl.java:160)
[01:54:26 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504)
[01:54:26 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434)
[01:54:26 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263)
[01:54:26 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1621)
[01:54:26 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[01:54:26 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[01:54:26 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[01:54:26 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)```
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Speedspencer** [comment]
another found problem on this version

```[01:38:15 WARN]: java.lang.UnsupportedOperationException
[01:38:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scoreboard.CraftScoreboard.registerNewTeam(CraftScoreboard.java:208)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Containers.CMIUser.reapplyNamePlate(CMIUser.java:2667)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:311)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:179)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Modules.Vanish.VanishManager.applyVanish(VanishManager.java:175)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Containers.CMIUser.setVanished(CMIUser.java:1879)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.Containers.CMIUser.setVanished(CMIUser.java:1859)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.commands.list.vanish.perform(vanish.java:82)
[01:38:15 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401)
[01:38:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:38:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[01:38:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042)
[01:38:15 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[01:38:15 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[01:38:15 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[01:38:15 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[01:38:15 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[01:38:15 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[01:38:15 WARN]:        at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[01:38:15 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[01:38:15 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[01:38:15 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[01:38:15 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2285)
[01:38:15 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2245)
[01:38:15 WARN]:        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173)
[01:38:15 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636)
[01:38:15 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[01:38:15 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[01:38:15 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[01:38:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)```

this happen when unvanish

**Comment by Speedspencer** [comment]
another problem with bed leaving from speedup night

```[02:15:00 ERROR]: Could not pass event PlayerBedEnterEvent to CMI v9.7.0.4
java.lang.IllegalStateException: Cannot modify server settings off of the global region
        at io.papermc.paper.threadedregions.RegionizedServer.ensureGlobalTickThread(RegionizedServer.java:105) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.setGameRuleValue(CraftWorld.java:2083) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at com.Zrips.CMI.utils.TimeManager.cancelSunMove(TimeManager.java:252) ~[CMI-9.7.0.4.jar:?]
        at com.Zrips.CMI.utils.TimeManager.cancelSunMove(TimeManager.java:242) ~[CMI-9.7.0.4.jar:?]
        at com.Zrips.CMI.Containers.SleepStats.onBedEnter(SleepStats.java:245) ~[CMI-9.7.0.4.jar:?]
        at com.Zrips.CMI.AllListeners.PlayerListeners.PlayerBedEnterEvent(PlayerListeners.java:210) ~[CMI-9.7.0.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:git-Folia-"e97b1ee"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:315) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.level.ServerPlayer.startSleepInBed(ServerPlayer.java:1869) ~[?:?]
        at net.minecraft.world.entity.player.Player.startSleepInBed(Player.java:1555) ~[?:?]
        at net.minecraft.world.level.block.BedBlock.use(BedBlock.java:123) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1297) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:581) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1983) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:102) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Speedspencer** [comment]
Error when loading data from playtime stats (I assume)

this happened first time only when using playtime top

```
[02:26:32 ERROR]: Thread Region Scheduler Thread #8 failed main thread check: Dispatching command async
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1031) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:680) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at com.Zrips.CMI.Modules.Statistics.StatsManager.lambda$2(StatsManager.java:496) ~[CMI-9.7.0.4.jar:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$runTask$0(CMIFoliaImpl.java:37) ~[CMILib1.4.6.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[02:26:32 WARN]: [CMILib] Global task for CMILib v1.4.6.1 generated an exception
java.lang.IllegalStateException: Dispatching command async
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1031) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:680) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at com.Zrips.CMI.Modules.Statistics.StatsManager.lambda$2(StatsManager.java:496) ~[CMI-9.7.0.4.jar:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$runTask$0(CMIFoliaImpl.java:37) ~[CMILib1.4.6.1.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Speedspencer** [comment]
Error when try to tpopos 

```
[16:38:40 WARN]: java.lang.UnsupportedOperationException: Must use teleportAsync while in region threading
[16:38:40 WARN]:        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:906)
[16:38:40 WARN]:        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:899)
[16:38:40 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.NBT.v1_20_R3.forceTeleport(v1_20_R3.java:917)
[16:38:40 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.commands.list.tpopos.perform(tpopos.java:183)
[16:38:40 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401)
[16:38:40 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:38:40 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[16:38:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042)
[16:38:40 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[16:38:40 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[16:38:40 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:32)
[16:38:40 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[16:38:40 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[16:38:40 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[16:38:40 WARN]:        at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:101)
[16:38:40 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[16:38:40 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[16:38:40 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[16:38:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2285)
[16:38:40 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2245)
[16:38:40 WARN]:        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173)
[16:38:40 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636)
[16:38:40 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[16:38:40 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[16:38:40 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[16:38:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Speedspencer** [comment]
```
[18:09:07 WARN]: java.lang.NoSuchFieldException: currentTick
[18:09:07 WARN]:        at java.base/java.lang.Class.getField(Class.java:2117)
[18:09:07 WARN]:        at CMILib1.4.6.1.jar//net.Zrips.CMILib.Reflections.getCurrentTick(Reflections.java:452)
[18:09:07 WARN]:        at CMI-9.7.0.4.jar//com.Zrips.CMI.AllListeners.PlayerListeners.onTeleportWithEntity(PlayerListeners.java:916)
[18:09:07 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor254.execute(Unknown Source)
[18:09:07 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[18:09:07 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[18:09:07 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:09:07 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:09:07 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[18:09:07 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[18:09:07 WARN]:        at net.minecraft.server.network.PlayerConnection.teleport(PlayerConnection.java:1752)
[18:09:07 WARN]:        at net.minecraft.server.network.PlayerConnection.teleport(PlayerConnection.java:1721)
[18:09:07 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1717)
[18:09:07 WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:3021)
[18:09:07 WARN]:        at net.minecraft.world.entity.Entity.n(Entity.java:2892)
[18:09:07 WARN]:        at net.minecraft.world.entity.animal.horse.EntityHorseAbstract.f(EntityHorseAbstract.java:560)
[18:09:07 WARN]:        at net.minecraft.world.entity.animal.camel.Camel.b(Camel.java:360)
[18:09:07 WARN]:        at net.minecraft.world.entity.EntityInsentient.a(EntityInsentient.java:1360)
[18:09:07 WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1131)
[18:09:07 WARN]:        at net.minecraft.server.network.PlayerConnection$3.performInteraction(PlayerConnection.java:2819)
[18:09:07 WARN]:        at net.minecraft.server.network.PlayerConnection$3.a(PlayerConnection.java:2839)
[18:09:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$d.a(PacketPlayInUseEntity.java:131)
[18:09:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[18:09:07 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2780)
[18:09:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[18:09:07 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[18:09:07 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[18:09:07 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$2(PlayerConnectionUtils.java:102)
[18:09:07 WARN]:        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173)
[18:09:07 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636)
[18:09:07 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407)
[18:09:07 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[18:09:07 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[18:09:07 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

Not sure how this error happen but seems to be after player logout sometimes

**Comment by Zrips** [comment]
All error messages should be fixed with next update
