### ISSUE TITLE
Velocity server, when I logout it will warning me this )

### ISSUE THREAD

**Issue by 121579905** [Zrips/CMI#8612]
### Description of Issue

[11:03:20 WARN]: [CMILib] Task #5801 for CMILib v1.4.5.2 generated an exception
java.lang.NoSuchFieldError: NOCOLLISIONBOX
        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.fill(TeleportHandler.java:610) ~[CMI-9.7.0.2.jar:?]
        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.<init>(TeleportHandler.java:51) ~[CMI-9.7.0.2.jar:?]
        at com.Zrips.CMI.CMI.getTeleportHandler(CMI.java:740) ~[CMI-9.7.0.2.jar:?]
        at com.Zrips.CMI.Containers.CMIUser.cacheClear(CMIUser.java:205) ~[CMI-9.7.0.2.jar:?]
        at com.Zrips.CMI.AllListeners.PlayerListeners.lambda$6(PlayerListeners.java:1116) ~[CMI-9.7.0.2.jar:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTask$0(CMIBukkitImpl.java:26) ~[CMILib1.4.5.2.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-464]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-464]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-464]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-464]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-464]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-464]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Version Information

```shell
[11:09:00 INFO]: --------------------------------------------------
[11:09:00 INFO]: CMI: 9.7.0.2 SqLite-> 9.7.0.4
[11:09:00 INFO]: CMILib: 1.4.5.2 -> 1.4.6.1
[11:09:00 INFO]: Server: Paper(464) 1.20.4-R0.1-SNAPSHOT-
[11:09:00 INFO]: CMI economy: Disabled CMI Chat: Disabled 
[11:09:00 INFO]: Modules -> 58 enabled 1 disabled: votifier
[11:09:00 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Updating CMILib will resolve this issue
