### ISSUE TITLE
/baltop not working :( 

### ISSUE THREAD

**Issue by arturek1666** [Zrips/CMI#863]
After use /baltop the command stop working :( ahh

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```
[23:06:13] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.13.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-301]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1770) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1574) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-301]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_144]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[patched_1.13.1.jar:git-Paper-301]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.13.1.jar:git-Paper-301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.util.NoSuchElementException
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1209) ~[?:1.8.0_144]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1247) ~[?:1.8.0_144]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1242) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2559) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2583) ~[?:1.8.0_144]
	at java.util.TreeMap.buildFromSorted(TreeMap.java:2508) ~[?:1.8.0_144]
	at java.util.TreeMap.<init>(TreeMap.java:200) ~[?:1.8.0_144]
	at com.Zrips.CMI.Modules.Economy.EconomyManager.getBalTopMap(EconomyManager.java:208) ~[?:?]
	at com.Zrips.CMI.commands.list.baltop.perform(baltop.java:58) ~[?:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:222) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-301]
	... 15 more
```


**Cmi Version (using`/cmi version`):** 
8.0.13.0
**Server Type (Spigot/Paperspigot/etc):** 
paperspigot
**Server Version (using `/ver`):** 
1.13.1

**Comment by Zrips** [comment]
Everyday something new. Will change things around, tho cant reproduce issue. Will post new version today.
