### ISSUE TITLE
Console warning world null on player login.

### ISSUE THREAD

**Issue by EchocallingEarth** [Zrips/CMI#8630]
### Description of Issue

Updated to latest build and on login I see the warning in console. Happens no matter if the 1st or repeated login attempt. Affects any player logging in. But only shows in console.

if further info is needed, please do not hesitate to contact me here or ping me in the discord. 
(User name: echocallingearth)

### Version Information

```shell
[Server] INFO --------------------------------------------------
11.04 20:36:06 [Server] INFO CMI: 9.7.0.5 SqLite
11.04 20:36:06 [Server] INFO CMILib: 1.4.6.1 
11.04 20:36:06 [Server] INFO Server: Purpur(2160) 1.20.4-R0.1-SNAPSHOT+
11.04 20:36:06 [Server] INFO CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
11.04 20:36:06 [Server] INFO Modules -> 57 enabled 2 disabled: deathMessages, votifier
11.04 20:36:06 [Server] INFO --------------------------------------------------
```

### Errors

```shell
[Server] WARN java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getMinHeight()" because "world" is null
11.04 20:33:10 [Server] WARN at CMILib1.4.6.1.jar//net.Zrips.CMILib.Container.CMIWorld.getMinHeight(CMIWorld.java:74)
11.04 20:33:10 [Server] WARN at CMI-9.7.0.5.jar//com.Zrips.CMI.Containers.CMIHitBox.getHeightAtLocation(CMIHitBox.java:82)
11.04 20:33:10 [Server] WARN at CMI-9.7.0.5.jar//com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$5(TeleportHandler.java:162)
11.04 20:33:10 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
11.04 20:33:10 [Server] WARN at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
11.04 20:33:10 [Server] WARN at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
11.04 20:33:10 [Server] WARN at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
11.04 20:33:10 [Server] WARN at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
11.04 20:33:10 [Server] WARN at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
11.04 20:33:10 [Server] WARN at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
