### ISSUE TITLE
[Folia] Items doesn't drop on ground with /give and full inventory

### ISSUE THREAD

**Issue by roggy666** [Zrips/CMI#8631]
### Description of Issue

Items doesn't drop on ground with /give and full inventory

### Version Information

```shell
[13:38:01 INFO]: Версия плагина CMI: 9.7.0.5 Unknown  SqLite
[13:38:01 INFO]: CMILib: 1.4.6.1 
[13:38:01 INFO]: Server: Folia 1.20.4-R0.1-SNAPSHOT-
[13:38:01 INFO]: CMI economy: Disabled Vault: 1.7.3-b0-folia CMI Chat: Disabled 
[13:38:01 INFO]: Modules -> 56 enabled 3 disabled: tablist, votifier, holograms
```

### Errors

```shell
> cmi give MasterGlitch941 dirt 2014
[13:37:51 WARN]: Unexpected exception while parsing console command "cmi give MasterGlitch941 dirt 2014"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.0.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:993) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:296) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "captureDrops" because the return value of "net.minecraft.server.level.WorldServer.getCurrentWorldData()" is null
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1879) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1807) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.dropItem(CraftWorld.java:724) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.dropItem(CraftWorld.java:710) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at com.Zrips.CMI.Containers.CMIUser.dropItemNearPlayer(CMIUser.java:3071) ~[CMI-9.7.0.5.jar:?]
        at com.Zrips.CMI.Containers.CMIPlayerInventory.addItem(CMIPlayerInventory.java:130) ~[CMI-9.7.0.5.jar:?]
        at com.Zrips.CMI.Containers.CMIPlayerInventory.addItem(CMIPlayerInventory.java:80) ~[CMI-9.7.0.5.jar:?]
        at com.Zrips.CMI.commands.list.give.processNewItem(give.java:241) ~[CMI-9.7.0.5.jar:?]
        at com.Zrips.CMI.commands.list.give.processNewMethod(give.java:190) ~[CMI-9.7.0.5.jar:?]
        at com.Zrips.CMI.commands.list.give.perform(give.java:266) ~[CMI-9.7.0.5.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401) ~[CMI-9.7.0.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
