### ISSUE TITLE
reload twice create error after config-change of TimeSpeed setting

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8641]
### Description of Issue
Well i didn't really made much changes in config. just tried to enable a world in the TimeSpeed settings.

- i set one value in TimeSpeed Settings (a world) from false to true  and did / cmi reload  -> an error appeared in console.
- i did agggain /cmi reload  -> seems to be finde
- a thrid time /cmi reload -> the error appeared aggain.

- Now i set this setting back from false to true and did /cmi reload -> all fine
- /cmi reload aggain -> all fine
- /cmi reload aggain -> all fine

i redid the whole thing twice with same result. So it looks like there is an error if you wanne enable varrious timespeed for a world if it was disabled before and try to reload cmi.

### Version Information
![image](https://github.com/Zrips/CMI/assets/12080017/3df3c656-7660-47d1-991f-e1c37b9b05cb)

### Errors
```shell
>....
[15:35:38 WARN]: Unexpected exception while parsing console command "cmi reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.0.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-484]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:984) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-484]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
	at com.Zrips.CMI.utils.TimeManager.loadConfig(TimeManager.java:90) ~[CMI_9.7.0.6.jar:?]
	at com.Zrips.CMI.Config.load(Config.java:1682) ~[CMI_9.7.0.6.jar:?]
	at com.Zrips.CMI.Config.reload(Config.java:1734) ~[CMI_9.7.0.6.jar:?]
	at com.Zrips.CMI.commands.list.reload.perform(reload.java:21) ~[CMI_9.7.0.6.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:401) ~[CMI_9.7.0.6.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 9 more
>....
```

### Relevant Config Sections
Before: - value of Farmwelt is false
```yaml
  TimeSpeed:
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    world:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 600
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 90
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 420
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 90
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    Farmwelt:
      Enabled: false
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 1200
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 60
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 480
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 60
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
```

after: - value of Farmwelt is set true
```yaml
  TimeSpeed:
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    world:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 600
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 90
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 420
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 90
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
    Farmwelt:
      Enabled: true
      # Default value: 600 Starts from tick: 0 Ends at tick: 12000
      day: 1200
      # Default value: 90 Starts from tick: 12000 Ends at tick: 13800
      sunset: 60
      # Default value: 420 Starts from tick: 13800 Ends at tick: 22200
      night: 480
      # Default value: 90 Starts from tick: 22200 Ends at tick: 24000
      sunrise: 60
    # Time is defined in seconds. Vanilla 24 hour ingame duration is 1200 seconds of real time
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
