### ISSUE TITLE
CMILib Error 1.4.7.1

### ISSUE THREAD

**Issue by Ganm10** [Zrips/CMI#8661]
### Description of Issue

It generates this error when I log in to the server as well as when I restart the server

### Version Information

```shell
CMILib 1.4.7.1
```

### Errors

```shell
[05:15:32 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "this.nmsChatSerializer" is null
[05:15:32 WARN]:        at CMILib1.4.7.1.jar//net.Zrips.CMILib.Reflections.textToIChatBaseComponent(Reflections.java:474)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:132)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:105)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListManager.updateTabListSync(TabListManager.java:737)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:445)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:417)
[05:15:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[05:15:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[05:15:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:15:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[05:15:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:15:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[05:15:32 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "this.nmsChatSerializer" is null
[05:15:32 WARN]:        at CMILib1.4.7.1.jar//net.Zrips.CMILib.Reflections.textToIChatBaseComponent(Reflections.java:474)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:137)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:105)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListManager.updateTabListSync(TabListManager.java:737)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:445)
[05:15:32 WARN]:        at CMI-9.7.2.0.jar//com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:417)
[05:15:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[05:15:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[05:15:32 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:15:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[05:15:32 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:15:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[05:15:32 ERROR]: Error 
java.lang.IllegalArgumentException: java.lang.ClassCastException@46ac69fd
        at jdk.internal.reflect.GeneratedConstructorAccessor131.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:139) ~[CMI-9.7.2.0.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListHeaderFooterHandler.send(TabListHeaderFooterHandler.java:105) ~[CMI-9.7.2.0.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager.updateTabListSync(TabListManager.java:737) ~[CMI-9.7.2.0.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:445) ~[CMI-9.7.2.0.jar:?]
        at com.Zrips.CMI.Modules.TabList.TabListManager.updateTabList(TabListManager.java:417) ~[CMI-9.7.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Relevant Plugins

CMILib 1.4.7.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mrfloris** [comment]
Latest CMILib .2 released
`Fixing an issue with 1.17 - 1.19 servers experiencing issues due to missing libraries`

**Comment by Ganm10** [comment]
Excellent The issue has already been fixed without any problem
