### ISSUE TITLE
Player Event

### ISSUE THREAD

**Issue by WhiteProject1** [Zrips/CMI#8667]
### Description of Issue

![image](https://github.com/Zrips/CMI/assets/103301275/9cbd4e2e-b068-48e0-901c-5f9ccaf1afdc)

when doing  block block place block etc.

### Version Information

```shell
CMI: 9.7.2.0
CMILIB: 1.4.7.2
```

### Errors

```shell
[16:09:26] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[16:09:26] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.EnumAnimation.e(java.lang.String)
[16:09:26] [Server thread/WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2405)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:1413)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.NBT.CMINBT.getString(CMINBT.java:618)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.GUI.GUIListener.clearIconItems(GUIListener.java:48)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.GUI.GUIListener.onPlayerDeathEvent(GUIListener.java:59)
[16:09:26] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:09:26] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587)
[16:09:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:927)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:896)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1541)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:955)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1051)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.level.block.BlockMagma.a(BlockMagma.java:33)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.a(Entity.java:926)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:2889)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:2823)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1628)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1617)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.n_(EntityLiving.java:3352)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.n_(EntityHuman.java:552)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:2999)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.l(EntityHuman.java:281)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.m(EntityPlayer.java:735)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.d(PlayerConnection.java:344)
[16:09:26] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.b(NetworkManager.java:428)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:181)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1459)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
[16:09:26] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[16:09:26] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.item.EnumAnimation.e(java.lang.String)
[16:09:26] [Server thread/WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2405)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:1413)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.NBT.CMINBT.getString(CMINBT.java:618)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.GUI.GUIListener.clearIconItems(GUIListener.java:48)
[16:09:26] [Server thread/WARN]:        at net.Zrips.CMILib.GUI.GUIListener.onPlayerDeathEvent(GUIListener.java:59)
[16:09:26] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[16:09:26] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600)
[16:09:26] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587)
[16:09:26] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:927)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:896)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1541)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:955)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1051)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.level.block.BlockMagma.a(BlockMagma.java:33)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.Entity.a(Entity.java:926)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:2889)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:2823)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:1628)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1617)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.n_(EntityLiving.java:3352)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.n_(EntityHuman.java:552)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:2999)
[16:09:26] [Server thread/WARN]:        at net.minecraft.world.entity.player.EntityHuman.l(EntityHuman.java:281)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.level.EntityPlayer.m(EntityPlayer.java:735)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.d(PlayerConnection.java:344)
[16:09:26] [Server thread/WARN]:        at net.minecraft.network.NetworkManager.b(NetworkManager.java:428)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:181)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1459)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064)
[16:09:26] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
[16:09:26] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with latest CMILib builds
