### ISSUE TITLE
CMI Error in log latest version

### ISSUE THREAD

**Issue by Heriptik** [Zrips/CMI#8691]
### Description of Issue

Hi, i have updated cmi to 9.7.2.4 and i have error in my log

### Version Information

```shell
CMI : 9.7.2.4
CMILib : 1.4.7.4
Spigot version : Catserver 1.12.2
```

### Errors

```shell
[02:37:22] [Server thread/ERROR] [Minecraft]: Could not pass event EntityTeleportEvent to CMI v9.7.2.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [SimplePluginManager.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [SimplePluginManager.class:git-CatServer-1.12.2-8d58cdb8]
	at net.minecraft.entity.ai.EntityAIFollowOwner.func_75246_d(EntityAIFollowOwner.java:124) [xc.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(EntityAITasks.java:105) [xf.class:?]
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity4Interactions.updateEntityActionStateAlt(Entity4Interactions.java:625) [Entity4Interactions.class:1.12.2-8.4.3]
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity4Interactions.func_70636_d(Entity4Interactions.java:583) [Entity4Interactions.class:1.12.2-8.4.3]
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity6Moves.func_70636_d(Entity6Moves.java:275) [Entity6Moves.class:1.12.2-8.4.3]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2512) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:332) [vq.class:?]
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity1Base.func_70071_h_(Entity1Base.java:490) [Entity1Base.class:1.12.2-8.4.3]
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity2Client.func_70071_h_(Entity2Client.java:438) [Entity2Client.class:1.12.2-8.4.3]
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity3HasStats.func_70071_h_(Entity3HasStats.java:317) [Entity3HasStats.class:1.12.2-8.4.3]
	at com.pixelmonmod.pixelmon.entities.pixelmon.Entity4Interactions.func_70071_h_(Entity4Interactions.java:334) [Entity4Interactions.class:1.12.2-8.4.3]
	at com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon.func_70071_h_(EntityPixelmon.java:383) [EntityPixelmon.class:1.12.2-8.4.3]
	at net.minecraft.world.World.func_72866_a(World.java:2307) [amu.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:2261) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2031) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:984) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:834) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException
	at com.Zrips.CMI.AllListeners.GlicthListeners.EntityTeleportEvent(GlicthListeners.java:90) ~[?:?]
	at catserver.server.executor.asm.generated.GeneratedEventExecutor781.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-8d58cdb8]
	... 24 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
