### ISSUE TITLE
1.20.6 Bugs  [Mutiple] 

### ISSUE THREAD

**Issue by SonnenPingu** [Zrips/CMI#8693]
### Description of Issue

the /clear command does not yet work 

### Version Information

```shell
cmi version
[09:08:47 INFO]: --------------------------------------------------
[09:08:47 INFO]: CMI Plugin Version: 9.7.2.4 SqLite
[09:08:47 INFO]: CMILib: 1.4.7.4 
[09:08:47 INFO]: Server: Paper(41) 1.20.6-R0.1-SNAPSHOT-
[09:08:47 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[09:08:47 INFO]: Modules -> 58 enabled 1 disabled: votifier
[09:08:47 INFO]: --------------------------------------------------
```

### Errors

```shell
[09:07:23 INFO]: Sonnenpingu issued server command: /clear
[09:07:25 INFO]: Sonnenpingu issued server command: /cmi clear Sonnenpingu -confirmed
[09:07:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.6.jar:git-Paper-41]
        at org.bukkit.craftbukkit.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.6.jar:git-Paper-41]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:429) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2200) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1515) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1492) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1415) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1381) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242) ~[paper-1.20.6.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-41]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: itemjoin name
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:117) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at CMILib1.4.7.4.jar/net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.getKey(CMIPersistentDataContainer.java:53) ~[CMILib1.4.7.4.jar:?]
        at CMILib1.4.7.4.jar/net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.hasKey(CMIPersistentDataContainer.java:59) ~[CMILib1.4.7.4.jar:?]
        at CMILib1.4.7.4.jar/net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:1275) ~[CMILib1.4.7.4.jar:?]
        at CMI-9.7.2.4.jar/com.Zrips.CMI.commands.list.clear.isExcluded(clear.java:306) ~[CMI-9.7.2.4.jar:?]
        at CMI-9.7.2.4.jar/com.Zrips.CMI.commands.list.clear.perform(clear.java:195) ~[CMI-9.7.2.4.jar:?]
        at CMI-9.7.2.4.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.2.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 27 more
```

### Relevant Plugins

CMI 9.7.2.4 and CMILIB 1.4.7.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
