### ISSUE TITLE
jail leads to internal error

### ISSUE THREAD

**Issue by angushushu** [Zrips/CMI#8697]
### Description of Issue

We are using cmi in a folia server. When we run jail command (e.g., /jail playername 5m test 1 r:reason), an internal error happens.

### Version Information

```shell
[10:46:05 INFO]: --------------------------------------------------
[10:46:05 INFO]: CMI: 9.7.2.4 SqLite
[10:46:05 INFO]: CMILib: 1.4.7.4
[10:46:05 INFO]: Server: Folia 1.20.4-R0.1-SNAPSHOT-
[10:46:05 INFO]: CMI economy: enabled Vault: 1.7.3-b(CMIEInjector) CMI Chat: enabled
[10:46:05 INFO]: Modules -> 58 enabled 1 disabled: votifier
[10:46:05 INFO]: --------------------------------------------------
```

### Errors

```shell
[10:27:59] [Region Scheduler Thread #0/INFO]: angushushu issued server command: /jail Dragonass 5m test 1 r:fuc
[10:27:59] [Region Scheduler Thread #0/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.2.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1042) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2285) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2245) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1646) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at java.lang.Thread.run(Thread.java:898) ~[?:?]
Caused by: java.lang.UnsupportedOperationException: Must use teleportAsync while in region threading
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1312) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1261) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
	at com.Zrips.CMI.Modules.Jail.JailManager.placePlayerIntoJail(JailManager.java:656) ~[CMI-9.7.2.4.jar:?]
	at com.Zrips.CMI.Containers.CMIUser.jail(CMIUser.java:2338) ~[CMI-9.7.2.4.jar:?]
	at com.Zrips.CMI.commands.list.jail.perform(jail.java:126) ~[CMI-9.7.2.4.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.2.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 20 more
```

### Relevant Config Sections

```yaml
No relevant config sections, used default setting.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
