### ISSUE TITLE
Hologram. latest version, issue

### ISSUE THREAD

**Issue by Gojan1** [Zrips/CMI#870]
**Description of issue or feature request:**

https://gyazo.com/4064c620346b47f4b607949b1461f3e9
Tried setting up a hologram showing a icon, but it doesnt show it at all.

```
####################
## [21:32:56 WARN]: [CMI] Task #2591 for CMI v8.0.16.0 generated an exception
java.lang.NullPointerException
	at com.Zrips.CMI.Modules.Holograms.CMIHologram$1$1.run(CMIHologram.java:251) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-d97e08b-880a532]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]##
####################
```

**Cmi Version (using`/cmi version`):** 
[23:36:47] [Client thread/INFO]: [CHAT] --------------------------------------------------
[23:36:47] [Client thread/INFO]: [CHAT] §eCMI§e §eplugin§e §eversion:§e §e§68.0.16.0
[23:36:47] [Client thread/INFO]: [CHAT] Server version: Spigot 1.8.8-R0.1-SNAPSHOT
[23:36:47] [Client thread/INFO]: [CHAT] --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
spigot 1.8.8

**Server Version (using `/ver`):** 
[23:34:06] [Client thread/INFO]: [CHAT] This server is running CraftBukkit version git-Spigot-d97e08b-880a532 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[23:34:06] [Client thread/INFO]: [CHAT] Checking version, please wait...
[23:34:06] [Client thread/INFO]: [CHAT] You are 1230 version(s) behind

**Comment by Zrips** [comment]
Sadly floating icons are not supported on 1.8 servers as they don't have needed methods to handle them.
Tho will fix errors you are getting.
