### ISSUE TITLE
Unable to use the toast command in paper1.12.2 version

### ISSUE THREAD

**Issue by polang233** [Zrips/CMI#8708]
### Description of Issue

An error occurred when I entered the command

### Version Information

```shell
[16:43:36 INFO]: --------------------------------------------------
[16:43:36 INFO]: CMI版本:9.7.2.5 SqLite
[16:43:36 INFO]: CMILib版本:1.4.7.6-> 1.4.7.7
[16:43:36 INFO]: 服务器版本:Paper(1620) 1.12.2-R0.1-SNAPSHOT-
[16:43:36 INFO]: CMI经济系统:禁用Vault版本:1.7.3-b131CMI聊天系统:禁用
[16:43:36 INFO]: 模块 -> 58 已启用 1 已禁用:votifier
[16:43:36 INFO]: --------------------------------------------------
```

### Errors

```shell
[16:37:39 INFO]: Polang_ issued server command: /toast Polang_ -t:challenge -icon:stone testtest
[16:37:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.2.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_401]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_401]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_401]
Caused by: java.lang.IllegalArgumentException: advancement
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.getAdvancementProgress(CraftPlayer.java:1753) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.grant(CMIAdvancement.java:280) ~[?:?]
        at net.Zrips.CMILib.Advancements.CMIAdvancement.show(CMIAdvancement.java:260) ~[?:?]
        at com.Zrips.CMI.commands.list.toast.perform(toast.java:118) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 15 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next CMILib update
