### ISSUE TITLE
shulkerBackpack giving error on 1.20.6 (Paper 61)

### ISSUE THREAD

**Issue by MC-MrBirdy** [Zrips/CMI#8715]
### Description of Issue

When opening a shulkerbox as a backpack an error/warning is given, the shulkerbox does not open.

### Version Information

```shell
[23:54:41 INFO]: CMI: 9.7.2.6 SqLite
[23:54:41 INFO]: CMILib: 1.4.7.8
[23:54:41 INFO]: Server: Paper(61) 1.20.6-R0.1-SNAPSHOT+
[23:54:41 INFO]: CMI economy: Disabled CMI Chat: Disabled
[23:54:41 INFO]: Modules -> 58 enabled 1 disabled: votifier
```

### Errors

```shell
[23:52:38 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[23:52:38 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:572)
[23:52:38 WARN]:        at CMILib1.4.7.8.jar//net.Zrips.CMILib.NBT.CMINBT.set(CMINBT.java:1197)
[23:52:38 WARN]:        at CMI-9.7.2.6.jar//com.Zrips.CMI.Reflections.tryToMakeShulkerBox(Reflections.java:1034)
[23:52:38 WARN]:        at CMI-9.7.2.6.jar//com.Zrips.CMI.Modules.ShulkerBoxInventory.ShulkerBoxListener.PlayerInteractEvent(ShulkerBoxListener.java:194)
[23:52:38 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor203.execute(Unknown Source)
[23:52:38 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[23:52:38 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[23:52:38 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:52:38 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[23:52:38 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[23:52:38 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
[23:52:38 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
[23:52:38 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549)
[23:52:38 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[23:52:38 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:540)
[23:52:38 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1993)
[23:52:38 WARN]:        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:39)
[23:52:38 WARN]:        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10)
[23:52:38 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[23:52:38 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:52:38 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[23:52:38 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[23:52:38 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1515)
[23:52:38 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:198)
[23:52:38 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[23:52:38 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1492)
[23:52:38 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1415)
[23:52:38 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[23:52:38 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1381)
[23:52:38 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1242)
[23:52:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[23:52:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Relevant Config Sections

```yaml
Modules.yml
# Handles shulker box as backpacks
# Applies for servers from 1.11.x and up
shulkerBackpack: true


Config.yml
ShulkerBoxes:
  # When set to true, players will not have option to open shulker boxes while in combat
  # Combat timer can be defined under combat section
  PreventInCombat: true
  # Money cost to open shulker box, if player doesn't have enough money then we will not allow to open shulker box from inventory
  # Setting this to 0 will disable money requirement
  # This can be bypassed with cmi.openshulker.free permission node
  CostToOpen: 0.0
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next CMI and CMILib updates
