### ISSUE TITLE
1.12.2paper /recipe command cannot be used and reports an error

### ISSUE THREAD

**Issue by polang233** [Zrips/CMI#8718]
### Description of Issue

Most items attempted in 1.12.2 were unable to use this command

### Version Information

```shell
> cmi version
[11:17:14 INFO]: --------------------------------------------------
[11:17:14 INFO]: CMI版本:9.7.2.6 SqLite
[11:17:14 INFO]: CMILib版本:1.4.7.8
[11:17:14 INFO]: 服务器版本:Paper(1620) 1.12.2-R0.1-SNAPSHOT-
[11:17:14 INFO]: CMI经济系统:启用Vault版本:1.7.3-b131(CMIEInjector)CMI聊天系统:禁用
[11:17:14 INFO]: 模块 -> 58 已启用 1 已禁用:votifier
[11:17:14 INFO]: --------------------------------------------------
```

### Errors

```shell
[11:15:27 INFO]: Polang_ issued server command: /cmi recipe
[11:15:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.2.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_401]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_401]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_401]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getRecipe(Lorg/bukkit/NamespacedKey;)Lorg/bukkit/inventory/Recipe;
        at com.Zrips.CMI.Modules.Recipes.RecipeManager.openRecipeUI(RecipeManager.java:691) ~[?:?]
        at com.Zrips.CMI.Modules.Recipes.RecipeManager.openRecipeUI(RecipeManager.java:481) ~[?:?]
        at com.Zrips.CMI.commands.list.recipe.perform(recipe.java:72) ~[?:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 15 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next version
