### ISSUE TITLE
Fully broken CMI v9.7.2.8 on 1.18.2 because of Chat Bubbles update

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#8725]
### Description of Issue

Trying to update to 9.7.2.8 to fix the commands with warmups being broken, and now CMI wont boot at all because of the chat bubbles update, im using 1.18.2 and the chat bubbles thing looks like its 1.20+ only.

Even tho I have the chat bubbles module disabled.

### Version Information

```shell
Cant it wont boot, its v9.7.2.8 on PurPur 1.18.2.
```

### Errors

```shell
[10:31:22] [Server thread/ERROR]: Error occurred while enabling CMI v9.7.2.8 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.Color org.bukkit.Color.fromARGB(int, int, int, int)'
	at com.Zrips.CMI.Modules.Chat.ChatBubbleManager.loadConfig(ChatBubbleManager.java:78) ~[CMI-9.7.2.8.jar:?]
	at com.Zrips.CMI.Modules.Chat.ChatManager.loadConfig(ChatManager.java:191) ~[CMI-9.7.2.8.jar:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1515) ~[CMI-9.7.2.8.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[10:31:22] [Server thread/INFO]: [CMI] Disabling CMI v9.7.2.8
```
```


### Relevant Config Sections

_No response_

### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with todays update
