### ISSUE TITLE
Thread limit exceeded replacing blocked worker

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#8750]
### Description of Issue

> [13:49:57 WARN]: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2000)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3737)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3723)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
> [13:49:57 WARN]:        at CMI-9.7.2.10.jar//com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$1(TeleportHandler.java:96)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
> [13:49:57 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

### Version Information

```shell
[16:09:56 INFO]: -------------------------------------------
[16:09:56 INFO]: CMI: 9.7.2.10 SqLite
[16:09:56 INFO]: CMILib: 1.4.7.11
[16:09:56 INFO]: Server: Purpur(2176) 1.20.4-R0.1-SNAPSHOT-
[16:09:56 INFO]: CMI economy: enabled Vault: 1.7.3-CMI CMI Chat: disabled
[16:09:56 INFO]: Modules -> 42 enabled 17 disabled: spawnerProximity, tablist, moneyCheque, skin, jail, spawners, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, chatBubble, playerCombat, votifier, shulkerBackpack, spawnerCharge, namePlates
[16:09:56 INFO]: -------------------------------------------
```

### Relevant Plugins

Vault 1.7.3-CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update, if issue repeats, please let me know.
