### ISSUE TITLE
Error in console with dragon attack

### ISSUE THREAD

**Issue by Achent007** [Zrips/CMI#8755]
### Description of Issue

When a player enter on this type of attack (see the screen below) i got the error on the console during all the time the player is standing on.

![image](https://github.com/Zrips/CMI/assets/29687072/78484584-3a1f-44b2-a389-71bd8e267160)

### Version Information

```shell
CMI: 9.7.2.10 Unknown  MySQL
CMILib: 1.4.7.9 
Server: Paper(1620) 1.12.2-R0.1-SNAPSHOT-
CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Enabled 
Modules -> 43 enabled 16 disabled: hpBossBar, launchPad, tablist, moneyCheque, skin, noTarget, jail, elytraBoost, dynamicSigns, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, votifier, headDrop, vanish
```

### Errors

```shell
[09:12:19] [Server thread/ERROR]: Could not pass event AreaEffectCloudApplyEvent to CMI v9.7.2.10
java.lang.NoSuchMethodError: 'org.bukkit.potion.PotionType org.bukkit.entity.AreaEffectCloud.getBasePotionType()'
	at com.Zrips.CMI.Modules.Afk.AfkListener1_9.onLingeringEffectApply(AfkListener1_9.java:66) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor315.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callAreaEffectCloudApplyEvent(CraftEventFactory.java:1130) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.EntityAreaEffectCloud.B_(EntityAreaEffectCloud.java:314) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.World.h(World.java:1767) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1574) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:682) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:921) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
