### ISSUE TITLE
CMILib1.4.7.11 cannot start normally on 1.12.2 paper

### ISSUE THREAD

**Issue by polang233** [Zrips/CMI#8761]
### Description of Issue

Only normal before 1.4.7.9

### Version Information

```shell
Unable to start, so unable to input command
```

### Errors

```shell
[09:49:00] [Server thread/INFO]: [CMILib] Enabling CMILib v1.4.7.11
[09:49:01] [Server thread/INFO]: Server version: v1_12_R1 - 1.12.2 - paper  git-Paper-1620 (MC: 1.12.2)
[09:49:01] [Server thread/ERROR]: Error occurred while enabling CMILib v1.4.7.11 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Vibration$Destination
	at net.Zrips.CMILib.CMILib.getReflectionManager(CMILib.java:90) ~[?:?]
	at net.Zrips.CMILib.Version.Version.<clinit>(Version.java:72) ~[?:?]
	at net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:77) ~[?:?]
	at net.Zrips.CMILib.CMILib.onEnable(CMILib.java:215) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_401]
Caused by: java.lang.ClassNotFoundException: org.bukkit.Vibration$Destination
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_401]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_401]
	... 15 more
[09:49:01] [Server thread/INFO]: [CMILib] Disabling CMILib v1.4.7.11
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Resolved with latest CMILib update
