### ISSUE TITLE
Issue with books in Kits

### ISSUE THREAD

**Issue by FarkieBear1** [Zrips/CMI#8767]
### Description of Issue

Hey there! I'm having an issue on Spigot-Paper 1.20.6, Java version 21, where when I add a pre-written book (ie. Rules Book) to a Kit, all Kits break and remove themselves from the kit list. Here's my console on startup: https://pastebin.com/uQgRSuns

### Version Information

```shell
cmi version
[23:38:48 INFO]: --------------------------------------------------
[23:38:48 INFO]: CMI: 9.7.2.10 SqLite
[23:38:48 INFO]: CMILib: 1.4.7.11 
[23:38:48 INFO]: Server: Paper 1.20.6-R0.1-SNAPSHOT+
[23:38:48 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Disabled 
[23:38:48 INFO]: Modules -> 59 enabled 0 disabled: 
[23:38:48 INFO]: --------------------------------------------------
```

### Errors

```shell
[23:31:07 ERROR]: Cannot load plugins/CMI/Kits/Kits.yml
org.bukkit.configuration.InvalidConfigurationException: Global tag is not allowed: tag:yaml.org,2002:net.minecraft.network.chat.MutableComponent
 in 'reader', line 15, column 11:
            - !!net.minecraft.network.chat.Mut ... 
              ^
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:111) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at CMI-9.7.2.10.jar/com.Zrips.CMI.Modules.Kits.KitsManager.load(KitsManager.java:450) ~[CMI-9.7.2.10.jar:?]
        at CMI-9.7.2.10.jar/com.Zrips.CMI.CMI.onEnable(CMI.java:1534) ~[CMI-9.7.2.10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1139) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-86-9bf4855]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: org.yaml.snakeyaml.composer.ComposerException: Global tag is not allowed: tag:yaml.org,2002:net.minecraft.network.chat.MutableComponent
 in 'reader', line 15, column 11:
            - !!net.minecraft.network.chat.Mut ... 
              ^
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:304) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:277) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:207) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:369) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:348) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:323) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:209) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.Yaml.compose(Yaml.java:575) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:104) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 17 more
[23:31:07 INFO]: Loaded (0) kits into memory. Took 1ms
```

### Relevant Config Sections

```yaml
market:
  CommandName: market
  Enabled: true
  Delay: 10
  Items:
    '28':
      v: 3839
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: How to buy&sell
        author: FarkieBear
        pages:
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
    OffHand:
      v: 3839
      type: AIR
      amount: 0
rules:
  CommandName: rules
  Enabled: true
  Delay: 10
  Items:
    '28':
      v: 3839
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: RULES
        author: FarkieBear
        pages:
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
claim:
  CommandName: claim
  Enabled: true
  Delay: 10
  Items:
    '28':
      v: 3839
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: How to Claim Land
        author: BigScary
        pages:
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
    '29':
      v: 3839
      type: GOLDEN_SHOVEL
Newbie:
  CommandName: Newbie
  Enabled: true
  Delay: 10
  Items:
    '1':
      v: 3839
      type: GOLDEN_SHOVEL
    '2':
      v: 3839
      type: OAK_BOAT
    '3':
      v: 3839
      type: SADDLE
    '28':
      v: 3839
      type: IRON_SWORD
    '29':
      v: 3839
      type: IRON_AXE
    '30':
      v: 3839
      type: IRON_PICKAXE
    '31':
      v: 3839
      type: IRON_SHOVEL
    '34':
      v: 3839
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: How to buy&sell
        author: FarkieBear
        pages:
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
    '35':
      v: 3839
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: RULES
        author: FarkieBear
        pages:
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
    '36':
      v: 3839
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: How to Claim Land
        author: BigScary
        pages:
        - !!net.minecraft.network.chat.MutableComponent {}
        - !!net.minecraft.network.chat.MutableComponent {}
    Helmet:
      v: 3839
      type: CHAINMAIL_HELMET
    Chest:
      v: 3839
      type: CHAINMAIL_CHESTPLATE
    Legs:
      v: 3839
      type: CHAINMAIL_LEGGINGS
    Boots:
      v: 3839
      type: CHAINMAIL_BOOTS
    OffHand:
      v: 3839
      type: SHIELD
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Try updating to the latest paper builds and use kits file which doesn't contain `!!net.minecraft.network.chat.MutableComponent {}` lines in it, as this looks to be broken part, quite likely result trying to upgrade from older minecraft server versions to new one.
Normally book save section should look like
```
      v: 3839
      type: WRITTEN_BOOK
      meta:
        ==: ItemMeta
        meta-type: BOOK_SIGNED
        title: Rule book
        author: Zrips
        pages:
        - '{"text":"","extra":[{"text":"Some rules here","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"dark_green","bold":false}]}'
        resolved: true
```
If issue persists after that, let me know. Closing ticket for now.
