### ISSUE TITLE
Error with? Hologram? Reason unknown

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8771]
### Description of Issue
This error appeared today on our server once for an unknown reason.
it popped into the console and i dont know what the reason casued it.
Also i am not sure if it really is an hologramm issue.
I asked in the CMI Discord and they recomment to report it so i do.

### Version Information
![24-05-2024_00-59-12](https://github.com/Zrips/CMI/assets/12080017/37f525fd-bafe-4807-9daf-ac5d2a2294be)

### Errors
```shell
[00:21:17 WARN]: java.util.ConcurrentModificationException
[00:21:17 WARN]:     at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
[00:21:17 WARN]:     at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628)
[00:21:17 WARN]:     at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:337)
[00:21:17 WARN]:     at java.base/java.util.HashSet.<init>(HashSet.java:121)
[00:21:17 WARN]:     at CMI_9.7.2.11.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$17(CMIHologram.java:2692)
[00:21:17 WARN]:     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[00:21:17 WARN]:     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[00:21:17 WARN]:     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:21:17 WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[00:21:17 WARN]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[00:21:17 WARN]:     at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
