### ISSUE TITLE
An error occurred during transmission, Y coordinate anomaly

### ISSUE THREAD

**Issue by polang233** [Zrips/CMI#8783]
### Description of Issue

An error occurred when entering the/warp command，1.12.2paper，Using JDK8

### Version Information

```shell
[17:38:03 INFO]: --------------------------------------------------
[17:38:03 INFO]: CMI版本:9.7.2.12 MySQL
[17:38:03 INFO]: CMILib版本:1.4.7.14
[17:38:03 INFO]: 服务器版本:Paper(1620) 1.12.2-R0.1-SNAPSHOT-
[17:38:03 INFO]: CMI经济系统:已启用Vault版本:1.7.3-b131(CMIEInjector)CMI聊天系统:已禁用
[17:38:03 INFO]: 模块 -> 58 已启用 1 已禁用:votifier
[17:38:03 INFO]: --------------------------------------------------
```

### Errors

```shell
[17:29:25 WARN]: java.lang.NullPointerException
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.getBlockType(TeleportHandler.java:143)
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$7(TeleportHandler.java:253)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
[17:29:25 WARN]: java.lang.NullPointerException
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.getBlockType(TeleportHandler.java:149)
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$7(TeleportHandler.java:253)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
[17:29:25 WARN]: java.lang.NullPointerException
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.getBlockType(TeleportHandler.java:143)
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$7(TeleportHandler.java:253)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
[17:29:25 WARN]: java.lang.NullPointerException
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.getBlockType(TeleportHandler.java:149)
[17:29:25 WARN]:        at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$7(TeleportHandler.java:253)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
[17:29:25 WARN]:        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
[17:29:25 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next update
