### ISSUE TITLE
Java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by JuergenUniVie** [Zrips/CMI#8784]
### Description of Issue

[11:42:28] [Server thread/WARN]: java.lang.NoClassDefFoundError: be/maximvdw/placeholderapi/PlaceholderReplacer
[11:42:28] [Server thread/WARN]: 	at CMI-9.7.2.12.jar//com.Zrips.CMI.Modules.Hooks.CMIHookType$7.update(CMIHookType.java:138)
[11:42:28] [Server thread/WARN]: 	at CMI-9.7.2.12.jar//com.Zrips.CMI.Modules.Hooks.CMIHookType.init(CMIHookType.java:214)
[11:42:28] [Server thread/WARN]: 	at CMI-9.7.2.12.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1688)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[11:42:28] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[11:42:28] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[11:42:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[11:42:28] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: be.maximvdw.placeholderapi.PlaceholderReplacer
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[11:42:28] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[11:42:28] [Server thread/WARN]: 	... 15 more

### Version Information

```shell
9.7.2.12
```

### Errors

```shell
[11:42:28] [Server thread/WARN]: java.lang.NoClassDefFoundError: be/maximvdw/placeholderapi/PlaceholderReplacer
[11:42:28] [Server thread/WARN]: 	at CMI-9.7.2.12.jar//com.Zrips.CMI.Modules.Hooks.CMIHookType$7.update(CMIHookType.java:138)
[11:42:28] [Server thread/WARN]: 	at CMI-9.7.2.12.jar//com.Zrips.CMI.Modules.Hooks.CMIHookType.init(CMIHookType.java:214)
[11:42:28] [Server thread/WARN]: 	at CMI-9.7.2.12.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1688)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[11:42:28] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[11:42:28] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136)
[11:42:28] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[11:42:28] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[11:42:28] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: be.maximvdw.placeholderapi.PlaceholderReplacer
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[11:42:28] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[11:42:28] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[11:42:28] [Server thread/WARN]: 	... 15 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by JuergenUniVie** [comment]
https://ci.extendedclip.com/view/Plugins/job/PlaceholderAPI/lastBuild/
2.11.6

**Comment by Zrips** [comment]
Make sure that you are using [PlaceholderAPI-2.11.6.jar](https://ci.extendedclip.com/view/Plugins/job/PlaceholderAPI/197/artifact/build/libs/PlaceholderAPI-2.11.6.jar) file. If you are, then I will need to know output from /cmi version to have better idea what system you are running. But as of testing everything looks to be working correctly with 2.11.6 version.

**Comment by Zrips** [comment]
Check startup logs for any other errors before CMI one, as this error issint happening on same test server, so another option would be that PAPI itself failed to load in for some reason
