### ISSUE TITLE
Error from console when simultaneous players rtp

### ISSUE THREAD

**Issue by JericNisperos** [Zrips/CMI#8788]
### Description of Issue

I created a portal which has the command to random teleport the player using the cmi rt command. 

But for some reason, if 2 players simoultaneously enter the portal, it shows an error message from the console and the rt no longer works until restart.

### Version Information

```shell
CMI: 9.7.2.12
CMILib: 1.4.7.14
MC Server: Paper 1.20.6
```

### Errors

```shell
[Tue 10:27:26 WARN] java.lang.InterruptedException
[Tue 10:27:26 WARN]     at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[Tue 10:27:26 WARN]     at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[Tue 10:27:26 WARN]     at CMI-9.7.2.12.jar//com.Zrips.CMI.Modules.Teleportations.RandomTeleportationManager.lambda$14(RandomTeleportationManager.java:510)
[Tue 10:27:26 WARN]     at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[Tue 10:27:26 WARN]     at java.base/java.lang.Thread.run(Thread.java:1583)
[Tue 10:27:26 INFO] Could not find correct teleport location, please wait 10 min  and try again.
```

### Relevant Config Sections

```yaml
N/A
```

### Relevant Plugins

N/A

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
