### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by Heriptik** [Zrips/CMI#8792]
### Description of Issue

I have no particules when player use teleport command (/home, /warp ...)

### Version Information

```shell
CMI : 9.7.2.4
CMILib : 1.4.7.14
Server Spigot 1.12.2
```

### Errors

```shell
[17:41:01] [Craft Scheduler Thread - 4/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5811
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 4/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5812
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 17/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5813
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 17/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5815
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 4/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5816
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 4/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5817
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 17/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5818
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 4/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5820
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 17/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5819
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 17/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5823
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[17:41:01] [Craft Scheduler Thread - 4/WARN] [net.Zrips.CMILib.CMILib]: [CMILib] Plugin CMILib v1.4.7.14 generated an exception while executing task 5824
java.lang.NullPointerException: null
	at com.Zrips.CMI.NBT.v1_12_R1.playEffect(v1_12_R1.java:1083) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIPECircle.render(CMIPECircle.java:143) ~[?:?]
	at com.Zrips.CMI.Modules.Particl.CMIVisualEffect.lambda$2(CMIVisualEffect.java:118) ~[?:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-8d58cdb8]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-8d58cdb8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should have been fixed with CMILib 1.4.7.15 update
