### ISSUE TITLE
Cmi Mirror NBT(NULL) issue

### ISSUE THREAD

**Issue by dryter97** [Zrips/CMI#8800]
### Description of Issue

when using cmi mirror fonction and placing down block.
every one block i place using mirror result in non placing copy of the block and this error into the console.

using few default plugins

This server is running Paper version 1.20.6-129-master@0513374 (2024-05-31T15:53:34Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

1 version behind. the issue was appening when i was up to day has well.

Server Plugins (15):
Bukkit Plugins:

CMI, CMILib, CrateReloaded, FastAsyncWorldEdit, LoneLibs, LuckPerms, cMMO, PlugManX, ProtocolLib, SelectionVisualizer
Vault, ViaBackwards, ViaRewind, ViaVersion, WorldGuard
[CMILib]: Task #1189 for CMILib v1.4.7.15 generated an exception

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.2.12 SqLite
CMILib: 1.4.7.15
Server: Paper(129) 1.20.6-R0.1-SNAPSHOT+
CMI economy: Disabled CMI Chat: Disabled
Modules -> 58 enabled 1 disabled: votifier
--------------------------------------------------
```

### Errors

```shell
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "net.Zrips.CMILib.NBT.CMINBT.getNbt()" is null
at CMI-9.7.2.12.jar/com.Zrips.CMI.Containers.CMIPlayerInventory.matches(CMIPlayerInventory.java:362) ~[CMI-9.7.2.12.jar:?]
at CMI-9.7.2.12.jar/com.Zrips.CMI.Containers.CMIPlayerInventory.getTotalAmount(CMIPlayerInventory.java:275) ~[CMI-9.7.2.12.jar:?]
at CMI-9.7.2.12.jar/com.Zrips.CMI.Modules.Mirror.MirrorManager.lambda$2(MirrorManager.java:421) ~[CMI-9.7.2.12.jar:?]
at CMILib1.4.7.15.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtLocation$2(CMIBukkitImpl.java:78) ~[CMILib1.4.7.15.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-129-0513374]
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-129-0513374]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-129-0513374]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-129-0513374]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-129-0513374]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-129-0513374]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-129-0513374]
at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Relevant Config Sections

```yaml
N/A Not modified yet. new install from a blank server.
```

### Relevant Plugins

CMI and CMILIB

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
