### ISSUE TITLE
Constant errors 

### ISSUE THREAD

**Issue by SonnenPingu** [Zrips/CMI#8806]
### Description of Issue

```diff
! [Wed 12:49:39 WARN ] 	at CMI-9.7.2.12.jar//com.Zrips.CMI.AllListeners.PlayerListeners.onInteractBeeHive(PlayerListeners.java:502)
! [Wed 12:49:39 WARN ] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor601.execute(Unknown Source)
! [Wed 12:49:39 WARN ] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
! [Wed 12:49:39 WARN ] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
! [Wed 12:49:39 WARN ] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
! [Wed 12:49:39 WARN ] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
! [Wed 12:49:39 WARN ] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
! [Wed 12:49:39 WARN ] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
! [Wed 12:49:39 WARN ] 	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
! [Wed 12:49:39 WARN ] 	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:531)
! [Wed 12:49:39 WARN ] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1931)
! [Wed 12:49:39 WARN ] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44)
! [Wed 12:49:39 WARN ] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11)
! [Wed 12:49:39 WARN ] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
! [Wed 12:49:39 WARN ] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
! [Wed 12:49:39 WARN ] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)```

No idea what exactly the error is 

### Version Information

```shell
[Wed 13:00:14 INFO ] --------------------------------------------------
  [Wed 13:00:14 INFO ] CMI Plugin Version: 9.7.2.12 Velocity CMIB  SqLite
  [Wed 13:00:14 INFO ] CMILib: 1.4.7.15 
  [Wed 13:00:14 INFO ] Server: Paper(134) 1.20.6-R0.1-SNAPSHOT-
  [Wed 13:00:14 INFO ] CMI economy: Aktiviert Vault: 1.7.3-CMI CMI Chat: Aktiviert 
  [Wed 13:00:14 INFO ] Modules -> 53 enabled 6 disabled: tablist, ranks, votifier, shulkerBackpack, holograms, jail
  [Wed 13:00:14 INFO ] --------------------------------------------------
```

### Errors

```shell
https://mclo.gs/PkKtZyn#L1021
```

### Relevant Plugins

 AcceptTheRules, AdvancedRegionMarket, AutomaticBroadcast, BlueBridgeCore, BlueBridgeWG, BlueMap, BlueMapCustomSkinProvider, BlueMapDeathMarkers, BlueMapFloodgate, BlueMapOfflinePlayerMarkers [21:05:19 INFO]: ChestShop, ChestShopNotifier, ChestShopTools, Chunky, CMI, CMILib, DeathChest, DiscordSRV, FastAsyncWorldEdit, FileGUI [21:05:19 INFO]: floodgate, Geyser-Spigot, Jobs, LuckPerms, MCGBluemapEssentialsPlus, Multiverse-Core, PlaceholderAPI, SmoothTimber, spark, Spartan [21:05:19 INFO]: UltimateStatistics, Vault, ViaBackwards, ViaVersion, Votifier, VotingPlugin, WorldEditSUI, WorldGuard, WorldGuard, WorldGuardExtraFlags 

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
This will be resolved with next update
