### ISSUE TITLE
Cheque's

### ISSUE THREAD

**Issue by QuestalNetwork** [Zrips/CMI#8807]
### Description of Issue

Making cheques is still possible. Just claiming the cheque is not possible. An error will appear in the console.

### Version Information

```shell
[17:05:45 INFO]: CMI: 9.7.2.12 SqLite
[17:05:45 INFO]: CMILib: 1.4.7.15 
[17:05:45 INFO]: Server: Paper(137) 1.20.6-R0.1-SNAPSHOT+
[17:05:45 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[17:05:45 INFO]: Modules -> 56 enabled 3 disabled: spawnerProximity, spawners, spawnerCharge
```

### Errors

```shell
[17:02:35 WARN]: java.lang.NumberFormatException: Cannot parse null string
[17:02:35 WARN]:        at java.base/java.lang.Long.parseLong(Long.java:672)
[17:02:35 WARN]:        at java.base/java.lang.Long.parseLong(Long.java:832)
[17:02:35 WARN]:        at CMI-9.7.2.12.jar//com.Zrips.CMI.Modules.MoneyCheque.MoneyChequeListener.playerInteractOneTime(MoneyChequeListener.java:62)
[17:02:35 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor444.execute(Unknown Source)
[17:02:35 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:02:35 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[17:02:35 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:02:35 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:02:35 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[17:02:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627)
[17:02:35 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
[17:02:35 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549)
[17:02:35 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[17:02:35 WARN]:        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:540)
[17:02:35 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1993)
[17:02:35 WARN]:        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:39)
[17:02:35 WARN]:        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10)
[17:02:35 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[17:02:35 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:02:35 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[17:02:35 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:02:35 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
[17:02:35 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[17:02:35 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[17:02:35 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
[17:02:35 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)
[17:02:35 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[17:02:35 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)
[17:02:35 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
[17:02:35 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[17:02:35 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next CMILib update
