### ISSUE TITLE
Issue with Eggs

### ISSUE THREAD

**Issue by SlimeCody** [Zrips/CMI#8809]
### Description of Issue

Running a give command with spawn eggs throws an error.

### Version Information

```shell
[01:15:54 INFO]: --------------------------------------------------
[01:15:54 INFO]: CMI plugin version: 9.7.3.1 Velocity CMIB  SqLite-> 9.7.2.12
[01:15:54 INFO]: CMILib: 1.4.7.15
[01:15:54 INFO]: Server: Paper(137) 1.20.6-R0.1-SNAPSHOT-
[01:15:54 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Disabled
[01:15:54 INFO]: Modules -> 56 enabled 8 disabled: coloredArmor, cuffed, tablist, ranks, votifier, moneyCheque, spawnerCharge, durabilityLoss
[01:15:54 INFO]: --------------------------------------------------
```

### Errors

```shell
[01:11:41 INFO]: DerpyCody issued server command: /cmi give DerpyCody villagerspawnegg 2
[01:11:41 ERROR]: Command exception: /cmi give MissAna156 villagerspawnegg 2
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.3.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getMaxStackSize()" because the return value of "net.Zrips.CMILib.Items.CMIItemStack.getItemStack()" is null
        at CMI-9.7.3.1.jar/com.Zrips.CMI.commands.list.give.processNewItem(give.java:226) ~[CMI-9.7.3.1.jar:?]
        at CMI-9.7.3.1.jar/com.Zrips.CMI.commands.list.give.processNewMethod(give.java:191) ~[CMI-9.7.3.1.jar:?]
        at CMI-9.7.3.1.jar/com.Zrips.CMI.commands.list.give.perform(give.java:267) ~[CMI-9.7.3.1.jar:?]
        at CMI-9.7.3.1.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.3.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with todays update
