### ISSUE TITLE
console error message from /itemcmdata (when it's not custom model item)

### ISSUE THREAD

**Issue by Lia-LV** [Zrips/CMI#8810]
### Description of Issue

If /itemcmdata is used for items that do not have CustomModelData, the console will receive an error message.

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.3.1 SqLite
CMILib: 1.4.7.15
Server: Paper(2218) 1.20.6-R0.1-SNAPSHOT+
CMI economy: enabled Vault: 1.7.3-CMI CMI Chat: disabled
Modules -> 57 enabled 7 disabled: tablist, firstJoinMessages, votifier, moneyCheque, headDrop, holograms, jail
--------------------------------------------------

(using Purpur, but it displayed as Paper)
```

### Errors

```shell
[17:52:58 ERROR]: Command exception: /cmi itemcmdata
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.3.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:450) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.Commands.performCommand(Commands.java:357) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.Commands.performCommand(Commands.java:344) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.commands.Commands.performCommand(Commands.java:339) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2282) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2256) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: We don't have CustomModelData! Check hasCustomModelData first!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.inventory.CraftMetaItem.getCustomModelData(CraftMetaItem.java:1183) ~[purpur-1.20.6.jar:1.20.6-2218-ec1b4fa]
        at CMI-9.7.3.1.jar/com.Zrips.CMI.commands.list.itemcmdata.perform(itemcmdata.java:109) ~[CMI-9.7.3.1.jar:?]
        at CMI-9.7.3.1.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.3.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with todays update
