### ISSUE TITLE
playtimetop

### ISSUE THREAD

**Issue by PLESOP** [Zrips/CMI#8826]
### Description of Issue

When the player enters /playtimetop, the console returns this error

### Version Information

```shell
[20:27:22 INFO]: --------------------------------------------------
[20:27:22 INFO]: CMI plugin version: 9.7.3.2 SqLite
[20:27:22 INFO]: CMILib: 1.4.7.16 
[20:27:22 INFO]: Server: Pufferfish(45) 1.20.4-R0.1-SNAPSHOT-
[20:27:22 INFO]: CMI economy: Disabled CMI Chat: Enabled 
[20:27:22 INFO]: Modules -> 58 enabled 6 disabled: armorstand, votifier, shulkerBackpack, anvilRenameColor, jail, kits
[20:27:22 INFO]: --------------------------------------------------
```

### Errors

```shell
[19:56:59 INFO]: Player issued server command: /playtimetop
[19:56:59 WARN]: [CMILib] Plugin CMILib v1.4.7.16 generated an exception while executing task 360035
java.lang.IllegalStateException: PlayerCommandPreprocessEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfishplus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:111) ~[CMILib1.4.7.16.jar:?]
        at net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:97) ~[CMILib1.4.7.16.jar:?]
        at net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:83) ~[CMILib1.4.7.16.jar:?]
        at net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:77) ~[CMILib1.4.7.16.jar:?]
        at com.Zrips.CMI.CMI.performCommand(CMI.java:1964) ~[CMI-9.7.3.2.jar:?]
        at com.Zrips.CMI.Modules.Statistics.StatsManager.lambda$0(StatsManager.java:496) ~[CMI-9.7.3.2.jar:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:38) ~[CMILib1.4.7.16.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-45]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run() ~[pufferfishplus-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by ScrapMetalGolem** [comment]
Same result here. The command always works fine the second time it is used, but never works the first time, and always generates this error. (slightly different error as I'm on a different server jar)


```
12:09:09 [WARN] [CMILib] Plugin CMILib v1.5.0.1 generated an exception while executing task 633298
java.lang.IllegalStateException: PlayerCommandPreprocessEvent may only be triggered synchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at CMILib1.5.0.1.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:111) ~[CMILib1.5.0.1.jar:?]
        at CMILib1.5.0.1.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:97) ~[CMILib1.5.0.1.jar:?]
        at CMILib1.5.0.1.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:83) ~[CMILib1.5.0.1.jar:?]
        at CMILib1.5.0.1.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:77) ~[CMILib1.5.0.1.jar:?]
        at CMI-9.7.4.0.jar/com.Zrips.CMI.CMI.performCommand(CMI.java:1968) ~[CMI-9.7.4.0.jar:?]
        at CMI-9.7.4.0.jar/com.Zrips.CMI.Modules.Statistics.StatsManager.lambda$0(StatsManager.java:496) ~[CMI-9.7.4.0.jar:?]
        at CMILib1.5.0.1.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$1(CMIBukkitImpl.java:38) ~[CMILib1.5.0.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Zrips** [comment]
Will be fixed with next update
