### ISSUE TITLE
Break Spawner Silk Touch

### ISSUE THREAD

**Issue by Siqued** [Zrips/CMI#8828]
### Description of Issue

The Break Spawner feature appears to be malfunctioning again. This issue has been tested on both the production and test servers, with the same result.

Currently, the spawner is not dropping as expected; it is simply being destroyed.

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.3.3 SqLite
CMILib: 1.4.7.16
Server: Paper(137) 1.20.6-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
Modules -> 63 enabled 1 disabled: votifier
--------------------------------------------------
```

### Errors

```shell
ERROR21.16.07
Could not pass event BlockBreakEvent to CMI v9.7.3.3
Console21.16.07
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: publicbukkitvalues.slimefun:slimefun_item
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:117) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at CMILib1.4.7.16.jar/net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.getKey(CMIPersistentDataContainer.java:120) ~[CMILib1.4.7.16.jar:?]
at CMILib1.4.7.16.jar/net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.hasKey(CMIPersistentDataContainer.java:126) ~[CMILib1.4.7.16.jar:?]
at CMILib1.4.7.16.jar/net.Zrips.CMILib.NBT.CMINBT.hasNBT(CMINBT.java:1315) ~[CMILib1.4.7.16.jar:?]
at CMILib1.4.7.16.jar/net.Zrips.CMILib.NBT.CMINBT.getString(CMINBT.java:603) ~[CMILib1.4.7.16.jar:?]
at CMI-9.7.3.3.jar/com.Zrips.CMI.Modules.SpawnerCharge.SpawnerChargeManager.getSpawnerDropChance(SpawnerChargeManager.java:339) ~[CMI-9.7.3.3.jar:?]
at CMI-9.7.3.3.jar/com.Zrips.CMI.Modules.SpawnerCharge.SpawnerChargeListener.BlockBreakEventFull(SpawnerChargeListener.java:96) ~[CMI-9.7.3.3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor312.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-137-bd5867a]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1845) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Config Sections

```yaml
FullDisable: false
  Break:
    Enabled: true
    RequiresExactPermission: false
    DropExp: false
    SilkTouchLevel: 1
    BaseDropChance: 100

  Place:
    Enabled: true
    RequiresPermission: false
    RequiresExactPermission: false
```

### Relevant Plugins

CMI Vault

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by charlieslost** [comment]
Confirmed last night, same issue on same versions as OP

**Comment by Strahilchu** [comment]
Also having this issue, can break spawners with bare hand though

**Comment by OverCrave** [comment]
This is fixed in the newest versions of CMI and CMILib for 1.21
