### ISSUE TITLE
CMI & CMILib do not startup with Paper-1.21

### ISSUE THREAD

**Issue by OstlerDev** [Zrips/CMI#8841]
### Description of Issue

I am testing the latest experimental build of Paper 1.21 (build 1 & 2 tested) for compatibility, and both CMILib and CMI refuse to startup. They are crashing with this specific error, looks like an issue with the version number reported in a function by CMILib.

Caused by: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Version.Version.toString()" because "net.Zrips.CMILib.Version.Version.current" is null

### Version Information

```shell
CMI v9.7.3.3
CMILib v1.4.7.16

(Unable to run `/cmi version` command)
```

### Errors

```shell
[17:13:39 INFO]: [CMILib] Enabling CMILib v1.4.7.16
[17:13:39 ERROR]: Error occurred while enabling CMILib v1.4.7.16 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at 87610.jar/net.Zrips.CMILib.Items.ItemManager.load(ItemManager.java:77) ~[87610.jar:?]
        at 87610.jar/net.Zrips.CMILib.CMILib.onEnable(CMILib.java:215) ~[87610.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Version.Version.toString()" because "net.Zrips.CMILib.Version.Version.current" is null
        at 87610.jar/net.Zrips.CMILib.Version.Version.<clinit>(Version.java:68) ~[87610.jar:?]
        ... 14 more
[17:13:39 INFO]: [CMILib] Disabling CMILib v1.4.7.16


[17:13:42 INFO]: [CMI] Enabling CMI v9.7.3.3
[17:13:42 ERROR]: Error occurred while enabling CMI v9.7.3.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/Zrips/CMILib/Version/Version
        at CMI-9.7.3.3.jar/com.Zrips.CMI.CMI.onEnable(CMI.java:1350) ~[CMI-9.7.3.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-1-21c9a7c]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.Zrips.CMILib.Version.Version
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 13 more
[17:13:42 INFO]: [CMI] Disabling CMI v9.7.3.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by gerardvanschip** [comment]
Confirmed with both paper and spigot.

**Comment by OstlerDev** [comment]
Issue has now been resolved, and CMI/CMILib appears to function as expected.

Issue confirmed fixed with versions:
- Paper 1.21 Experimental Build 4
- CMI-9.7.4.0
- CMILib1.5.0.1
