### ISSUE TITLE
(([Hologram bug]))   [WARN]: java.lang.NullPointerException  

### ISSUE THREAD

**Issue by IllyaVasilev1** [Zrips/CMI#8845]
### Description of Issue

It is very common for the console to write errors when the player appears next to any hologram that does not even use the call of his name and this kind of thing. Just text with additional effects.
throws a mistake 3 times for 1 hologram.

I'll throw the config below what configuration I have for the hologram...

I also deleted one hologram from my world (there were all holograms on the spawn and they were in sight)

So, I decided to check with a friend why there are so many errors in the console. I asked the gpt chat and he said that there are such errors in the CMI plugin. And I noticed that such an error occurs when the player on the spawn teleports. And CMI is used on spawn only for holograms.disappeared every time I deleted one hologram at a time.  I began to delete one hologram at a time, and 3 lines of errors. I caused these errors just by teleporting to the spawn. Each time there were 3 fewer errors when I deleted one hologram

Even a regular hologram with a simple text "Привет" causes an error... Perhaps because my text is Cyrillic? Well, written in shit russian

### Version Information

```shell
[08:35:58 INFO]: Версия плагина CMI: 9.7.4.0 SqLite
[08:35:58 INFO]: CMILib: 1.4.7.16 -> 1.5.0.1
[08:35:58 INFO]: Версия сервера: Paper(147) 1.20.6-R0.1-SNAPSHOT-
[08:35:58 INFO]: CMI Экономика: Disabled Версия Vault: 1.7.3-CMICMI Чат: Enabled
[08:35:58 INFO]: Модули -> 65 включено 1 отключено: votifier
[08:35:58 INFO]: --------------------------------------------------


My server also uses the following plugins:
[08:41:23 INFO]: Server Plugins (51):
[08:41:23 INFO]: Bukkit Plugins:
[08:41:23 INFO]:  - ajParkour, AnimatedScoreboard, AuctionHouse, AuthMe, AutoMessage, BedrockPlayerManager, BetterCommandSpy, Brewery, ChestCommands, CMI
[08:41:23 INFO]:  CMILib, CoreProtect, DiscordSRV, dynmap, Dynmap-Towny, FastAsyncWorldEdit, Geyser-Spigot, GeyserHacks, InteractiveChat, InteractiveChatDiscordSrvAddon
[08:41:23 INFO]:  KotlinLIBS, LuckPerms, MapTowny, MoneyFromMobs, NBTAPI, PL-Hide, PlaceholderAPI, PlugManX, ProtocolLib, PvPManager
[08:41:23 INFO]:  QualityArmory, RealisticSeasons, SelectionVisualizer, SkinsRestorer, TAB, Towny, TownyChat, TownyCombat, TownyCultures, TownyResources
[08:41:23 INFO]:  UltraRegions, Vault, Vegas, Vehicles, ViaBackwards, ViaRewind, ViaVersion, Vulcan, WorldGuard, WorldGuard-Towny
[08:41:23 INFO]:  XConomy
```

### Errors

```shell
[08:13:38 INFO]: Mar1mba issued server command: /world spawn
[08:13:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerHandle(Reflections.java:747)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:769)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2179)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1762)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$15(CMIHologram.java:2244)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[08:13:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerHandle(Reflections.java:747)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:769)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2179)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1762)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$15(CMIHologram.java:2244)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[08:13:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerHandle(Reflections.java:747)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:769)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2179)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1762)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$15(CMIHologram.java:2244)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerHandle(Reflections.java:747)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:769)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIInteractionEntity.<init>(CMIInteractionEntity.java:9)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.addInteractionCheck(CMIHologram.java:1821)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.newUpdate(CMIHologram.java:1805)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$15(CMIHologram.java:2244)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[08:13:42 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerHandle(Reflections.java:747)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:769)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2179)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$8(CMIHologram.java:1773)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtLocation$2(CMIBukkitImpl.java:79)
[08:13:42 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[08:13:42 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699)
[08:13:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[08:13:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerHandle(Reflections.java:747)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:769)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.createDisplay(CMIHologram.java:2179)
[08:13:42 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$8(CMIHologram.java:1773)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[08:13:42 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[08:13:42 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtLocation$2(CMIBukkitImpl.java:79)
[08:13:42 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101)
[08:13:42 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699)
[08:13:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231)
[08:13:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[08:13:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[08:13:42 WARN]: java.lang.NullPointerException
[08:13:42 WARN]: java.lang.NullPointerException
[08:14:01 WARN]: java.lang.NullPointerException
[08:14:01 WARN]: java.lang.NullPointerException
[08:14:01 WARN]: java.lang.NullPointerException
[08:14:03 INFO]: Mar1mba issued server command: /setspawn
```

### Relevant Config Sections

```yaml
OutpvpArena:
  Loc: spawn;16186.5;94.5;6149.53
  Range: 8
  RangeExtra: 16
  NewDisplay: true
  ND:
    Bill: FIXED
    Shadow: false
    Yaw: 270
    BColor: '{#Red}'
    ScaleW: 3.19
    ScaleH: 2.99
  Lines:
  - '&6[&aPVP-Арена&6]'
  - '&aВход'
spawnToWorld:
  Loc: spawn;16165.83;125.12;6138.57
  Interval: 24.29
  HoverParticles:
    Effect: END_ROD
    Spacing: 0.05
    Count: 10
    Stabilize: true
    ExtraHeight: 1.5
    ExtraWidth: 0.9
    OffsetY: -1.0
  Range: 1
  RangeExtra: 30
  Interactable: true
  NewDisplay: true
  ND:
    Bill: FIXED
    TAlpha: 255
    Shadow: false
    Yaw: 45
    Double: true
    BColor: '{#Blue}'
    BAlpha: 255
    ScaleW: 1.3
    SL: 15
    BL: 15
    IYaw: 4
  Lines:
  - '&fТелепорт в обычный мир'
InpvpArena:
  Loc: spawn;16186.5;94.5;6149.43
  HoverParticles:
    Stabilize: true
  Range: 1
  RangeExtra: 109
  NewDisplay: true
  ND:
    Bill: FIXED
    Shadow: false
    Yaw: 90
    BColor: '{#Dark_Green}'
    ScaleW: 3.19
    ScaleH: 2.99
  Lines:
  - '&6[&cPVP-Арена&6]'
  - '&cВыход'
'&d/rtp':
  Loc: world;-466.83;115.35;-2091.69
  Range: 8
  RangeExtra: 16
  NewDisplay: true
  ND:
    Bill: VERTICAL
    BColor: '{#Black}'
  Lines:
  - '&d/rtp - рандом телепорт'
AlicizationWorld:
  Loc: spawn;16160.26;147.06;6114.92
  Range: 128
  RangeExtra: 128
  NewDisplay: true
  ND:
    Bill: FIXED
    Double: true
    BColor: '{#Gray}'
    BAlpha: 0
    ScaleW: 22.09
    ScaleH: 26.09
    SL: 15
    BL: 15
  Lines:
  - '&7Alicization&dWorld'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Updating to latest CMILib 1.5.0.0+ should resolve your issue
