### ISSUE TITLE
 Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null

### ISSUE THREAD

**Issue by th3re4lillusi0n** [Zrips/CMI#8853]
### Description of Issue

Console Spam this WARN

### Version Information

```shell
CMI 9.7.4.0 CMILib 1.5.0.1
```

### Errors

```shell
[11:31:03 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getClass()" because "player" is null
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerHandle(Reflections.java:747)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:769)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.generateDisplay(CMIChatBubble.java:166)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.<init>(CMIChatBubble.java:57)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.ChatBubbleManager.showBubble(ChatBubbleManager.java:110)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.ChatBubbleListener.AsyncPlayerChatEvent(ChatBubbleListener.java:31)
[11:31:03 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor258.execute(Unknown Source)
[11:31:03 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:31:03 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:31:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:31:03 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:31:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[11:31:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[11:31:03 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378)
[11:31:03 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85)
[11:31:03 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2318)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.nms.V1_20_3.chatAsPlayerAsync(V1_20_3.java:507)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:75)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$3(RedispatchSignedPacket.java:87)
[11:31:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:31:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:31:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:31:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:31:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:31:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[11:31:03 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[11:31:03 WARN]:        at java.base/java.lang.reflect.Field.checkAccess(Field.java:1103)
[11:31:03 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:423)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.getPlayerConnection(Reflections.java:780)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.generateDisplay(CMIChatBubble.java:166)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.<init>(CMIChatBubble.java:57)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.ChatBubbleManager.showBubble(ChatBubbleManager.java:110)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.ChatBubbleListener.AsyncPlayerChatEvent(ChatBubbleListener.java:31)
[11:31:03 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor258.execute(Unknown Source)
[11:31:03 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:31:03 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:31:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:31:03 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:31:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[11:31:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[11:31:03 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378)
[11:31:03 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85)
[11:31:03 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2318)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.nms.V1_20_3.chatAsPlayerAsync(V1_20_3.java:507)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:75)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$3(RedispatchSignedPacket.java:87)
[11:31:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:31:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:31:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:31:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:31:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:31:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[11:31:03 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[11:31:03 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:561)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPacket(Reflections.java:915)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.sendPlayerPacket(Reflections.java:909)
[11:31:03 WARN]:        at CMILib1.4.7.16.jar//net.Zrips.CMILib.Reflections.superficialEntityTeleport(Reflections.java:1565)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.<init>(CMIDisplay.java:175)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Display.CMITextDisplay.<init>(CMITextDisplay.java:26)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.generateDisplay(CMIChatBubble.java:166)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.<init>(CMIChatBubble.java:57)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.ChatBubbleManager.showBubble(ChatBubbleManager.java:110)
[11:31:03 WARN]:        at CMI-9.7.4.0.jar//com.Zrips.CMI.Modules.Chat.ChatBubbleListener.AsyncPlayerChatEvent(ChatBubbleListener.java:31)
[11:31:03 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor258.execute(Unknown Source)
[11:31:03 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:31:03 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:31:03 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:31:03 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:31:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[11:31:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[11:31:03 WARN]:        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378)
[11:31:03 WARN]:        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85)
[11:31:03 WARN]:        at net.minecraft.server.network.PlayerConnection.chat(PlayerConnection.java:2318)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.nms.V1_20_3.chatAsPlayerAsync(V1_20_3.java:507)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.utils.PlayerUtils.chatAsPlayer(PlayerUtils.java:75)
[11:31:03 WARN]:        at InteractiveChat-4.2.10.2.jar//com.loohp.interactivechat.listeners.RedispatchSignedPacket$1.lambda$onPacketReceiving$3(RedispatchSignedPacket.java:87)
[11:31:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[11:31:03 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[11:31:03 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:31:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[11:31:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[11:31:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
```

### Relevant Plugins

Vault 1.7.3 CMIEconomy

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Update CMILib to the latest version, while you reported it to be 1.5.0.1, from the logs it indicates to be 1.4.7.16
