### ISSUE TITLE
[Mob Farm Manager] [1.18.2] Could not pass event CreatureSpawnEvent to MobFarmManager v3.0.0.1

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#8865]
### Description of Issue

```
[15:11:36] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobFarmManager v3.0.0.1
java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.World.getChunkAt(int, int, boolean)'
	at com.MobFarmManager.Zrips.Util.CleanerManager.getEntitiesFromChunksSync(CleanerManager.java:668) ~[MobFarmManager3.0.0.1.jar:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.checkEntitiesSync(CleanerManager.java:205) ~[MobFarmManager3.0.0.1.jar:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.cleanOnEntitySpawn(CleanerManager.java:179) ~[MobFarmManager3.0.0.1.jar:?]
	at com.MobFarmManager.Zrips.Listeners.EntityListener.onCreatureSpawnEventAsync(EntityListener.java:55) ~[MobFarmManager3.0.0.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor680.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:748) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:653) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1506) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1415) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:295) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:212) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:182) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1034) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:910) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1621) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Version Information

```shell
MobFarmManager v3.0.0.1
```

### Errors

```shell
See above
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by NoltoxGit** [comment]
Hello @TomLewis,
Please report this on the good repository.
-> https://github.com/Zrips/MobFarmManager/issues

**Comment by Zrips** [comment]
Should be resolved with next update

**Comment by TomLewis** [comment]
I updated and its still not working.
```
[10:42:03] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobFarmManager v3.0.1.2
java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.World.getChunkAt(int, int, boolean)'
	at com.MobFarmManager.Zrips.Util.CleanerManager.getEntitiesFromChunksSync(CleanerManager.java:666) ~[MobFarmManager3.0.1.2.jar:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.checkEntitiesSync(CleanerManager.java:208) ~[MobFarmManager3.0.1.2.jar:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.cleanOnEntitySpawn(CleanerManager.java:197) ~[MobFarmManager3.0.1.2.jar:?]
	at com.MobFarmManager.Zrips.Listeners.EntityListener.onCreatureSpawnEventAsync(EntityListener.java:57) ~[MobFarmManager3.0.1.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor683.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:748) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:653) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1506) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1415) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:295) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:212) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:182) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1034) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:910) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1621) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[10:42:03] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobFarmManager v3.0.1.2
java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.World.getChunkAt(int, int, boolean)'
	at com.MobFarmManager.Zrips.Util.CleanerManager.getEntitiesFromChunksSync(CleanerManager.java:666) ~[MobFarmManager3.0.1.2.jar:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.checkEntitiesSync(CleanerManager.java:208) ~[MobFarmManager3.0.1.2.jar:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.cleanOnEntitySpawn(CleanerManager.java:197) ~[MobFarmManager3.0.1.2.jar:?]
	at com.MobFarmManager.Zrips.Listeners.EntityListener.onCreatureSpawnEventAsync(EntityListener.java:57) ~[MobFarmManager3.0.1.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor683.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:748) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:653) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1506) ~[?:?]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1415) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:295) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:212) ~[?:?]
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:182) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1034) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:910) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1621) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
