### ISSUE TITLE
ItemStack error with Realistic survival

### ISSUE THREAD

**Issue by jan-osicka** [Zrips/CMI#8872]
### Description of Issue

Hello, 

while loading plugins CMI alongside with Realistic survival the server is unable to start. The issue started appearing on version 1.20.6. There was no issues with 1.20.4 versions or prior. 
Both plugins works great when separate even with another plugins. However together CMI is giving error below and server is not starting. 

### Version Information

```shell
[13:10:55 INFO]: --------------------------------------------------
[13:10:55 INFO]: CMI plugin version: 9.7.4.1 SqLite
[13:10:55 INFO]: CMILib: 1.5.0.2 
[13:10:55 INFO]: Server: Paper(2233) 1.20.6-R0.1-SNAPSHOT-
[13:10:55 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[13:10:55 INFO]: Modules -> 66 enabled 0 disabled: 
[13:10:55 INFO]: --------------------------------------------------
```

### Errors

```shell
[13:12:29 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.NullPointerException: Cannot invoke "com.mojang.datafixers.types.Type.everywhere(com.mojang.datafixers.TypeRewriteRule, com.mojang.datafixers.functions.PointFreeRule, boolean, boolean)" because "type" is null
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.TaggedChoice$TaggedChoiceType.all(TaggedChoice.java:146) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Named$NamedType.all(Named.java:83) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Check$CheckType.all(Check.java:121) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Check$CheckType.everywhere(Check.java:129) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.families.RecursiveTypeFamily.everywhere(RecursiveTypeFamily.java:143) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.RecursivePoint$RecursivePointType.everywhere(RecursivePoint.java:148) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Tag$TagType.all(Tag.java:119) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Sum$SumType.all(Sum.java:128) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Product$ProductType.all(Product.java:154) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$All.rewrite(TypeRewriteRule.java:194) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.cap1(TypeRewriteRule.java:86) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Seq.rewrite(TypeRewriteRule.java:76) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewrite(Type.java:189) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.everywhere(Type.java:88) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.TypeRewriteRule$Everywhere.rewrite(TypeRewriteRule.java:250) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.Type.rewriteOrNop(Type.java:55) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.types.templates.Named$NamedType.all(Named.java:83) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.DataFix.writeFixAndRead(DataFix.java:62) ~[datafixerupper-7.0.14.jar:?]
        at net.minecraft.util.datafix.fixes.EmptyItemInVillagerTradeFix.makeRule(EmptyItemInVillagerTradeFix.java:17) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at com.mojang.datafixers.DataFix.getRule(DataFix.java:119) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.DataFixerUpper.lambda$getRule$1(DataFixerUpper.java:124) ~[datafixerupper-7.0.14.jar:?]
        at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:454) ~[fastutil-8.5.12.jar:?]
        at it.unimi.dsi.fastutil.longs.Long2ObjectMaps$SynchronizedMap.computeIfAbsent(Long2ObjectMaps.java:466) ~[fastutil-8.5.12.jar:?]
        at com.mojang.datafixers.DataFixerUpper.getRule(DataFixerUpper.java:116) ~[datafixerupper-7.0.14.jar:?]
        at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:78) ~[datafixerupper-7.0.14.jar:?]
        at org.bukkit.craftbukkit.util.CraftMagicNumbers.getMaterial(CraftMagicNumbers.java:267) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:571) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264) ~[snakeyaml-2.2.jar:?]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247) ~[snakeyaml-2.2.jar:?]
        at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:309) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at CMI-9.7.4.1.jar/com.Zrips.CMI.Modules.Kits.KitsManager.load(KitsManager.java:451) ~[CMI-9.7.4.1.jar:?]
        at CMI-9.7.4.1.jar/com.Zrips.CMI.CMI.onEnable(CMI.java:1535) ~[CMI-9.7.4.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:678) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Plugins

Realistic Survival 1.2.8

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Some issue with Kits.yml file loading, you might want to double check if it contains something funky which was created by using Realistic Survival plugin and remove that to allow for servers startup
