### ISSUE TITLE
Error with console abut portals in 9.7.4.1

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8876]
### Description of Issue
an error shown in console.. for... portals exsting in the world?.... well im not sure the error came up in console when i walked the way to the portals

### Version Information
![30-06-2024_19-36-21](https://github.com/Zrips/CMI/assets/12080017/26f42830-acfd-4e8b-a5d9-15bb129c1185)

### Errors
```shell
[19:33:56] [Server thread/ERROR]: Could not pass event PortalCreateEvent to CMI v9.7.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.levelgen.feature.EndPlatformFeature.createEndPlatform(EndPlatformFeature.java:67) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.world.level.block.BlockEnderPortal.a(BlockEnderPortal.java:101) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.world.entity.PortalProcessor.a(SourceFile:33) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.world.entity.Entity.bP(Entity.java:2734) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.world.entity.Entity.postTick(Entity.java:610) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:890) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.world.level.World.a(World.java:684) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.level.WorldServer.lambda$tick$2(WorldServer.java:459) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:439) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1472) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:406) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4245-Spigot-0a642bd-aac911d]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
	at java.base/java.util.Objects.checkIndex(Objects.java:365) ~[?:?]
	at java.base/java.util.ArrayList.get(ArrayList.java:428) ~[?:?]
	at com.Zrips.CMI.AllListeners.PortalCreationListener.getMiddleBlock(PortalCreationListener.java:197) ~[?:?]
	at com.Zrips.CMI.AllListeners.PortalCreationListener.proccessEvent(PortalCreationListener.java:156) ~[?:?]
	at com.Zrips.CMI.AllListeners.PortalCreationListener.PortalCreateEvent(PortalCreationListener.java:40) ~[?:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	... 19 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be fixed with next build
