### ISSUE TITLE
Error Loadig 8.0.17

### ISSUE THREAD

**Issue by Gnoarn** [Zrips/CMI#888]
Ok. was putting together a new 1.13R2 server. got the newest version of playervaults and on load i got the following stacktrace.
```
Error occurred while enabling CMI v8.0.17.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/drtshock/playervaults/vaultmanagement/UUIDVaultManager
	at com.Zrips.CMI.CMI.setupPlayerVaults(CMI.java:1692) ~[?:?]
	at com.Zrips.CMI.CMI.onEnable(CMI.java:1536) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: com.drtshock.playervaults.vaultmanagement.UUIDVaultManager
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar:git-Spigot-2440e18-4228a56]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
	... 13 more
```
**Cmi Version (using`/cmi version`):** 
8.0.17
**Server Type (Spigot/Paperspigot/etc):** 
Spigot 
**Server Version (using `/ver`):** 
1.13 R2

**Comment by CloudeLecaw** [comment]
is your playervaults also up to dat eand working well with the newest 1.13.1? :3

**Comment by Gnoarn** [comment]
yes i have the newest. its straight off the nbt link on CMI spigot. works as it should. and even in the newest cmi 8.0.20 cmi still has the error with it.

**Comment by CloudeLecaw** [comment]
Well the plugin needs Vault (from CMI Seite) or Vault + CMIInjector (from CMI Seite) player vault is not realyy listet as compatible

**Comment by Gnoarn** [comment]
yeah its just listed as optional as with vault. while i use vault i have economy turned off in cmi. if there was a setting to turn off linking with playervaults would be great. at the moment it is i either use cmi or i use player vaults. 

https://pastebin.com/m6Mf7Ebz

**Comment by Zrips** [comment]
Would be nice to know which version exactly are you using? As there seems to be 3 of them, 2 free and 1 premium.

**Comment by Gnoarn** [comment]
the last i was using was 8.0.20 and all should have been premium since they were downloaded from the premium page.

**Comment by Gnoarn** [comment]
Oh. ok. i went from the free version to the premium version about this time. PlayerVaults would have been the premium version 4.0.6-vk-3.0.1

**Comment by Zrips** [comment]
Is this still an issue with latest builds? As latest ones doesnt throw any error message and simply ignores that plugin for time being.

**Comment by LogGits** [comment]
I am assuming this was resolved as there was no response. If you are still experiencing this issue please reopen a ticket.
