### ISSUE TITLE
1.21 Error on startup

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#8897]
### Description of Issue

Hello,
I've updated CM, CMILib and my server version (Purpur), all to the latest version available and i see CMI have an error on the server startup. See the error in the "Errors" section.

Here is my latest.log: https://mclo.gs/WgEcmHp

And also, it's weird the `/cmi version` command show Paper while I'm using Purpur :/

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.4.3 SqLite
CMILib: 1.5.0.5
Server: Paper(2255) 1.21-R0.1-SNAPSHOT-
CMI economy: Disabled CMI Chat: Disabled
Modules -> 65 enabled 1 disabled: votifier
--------------------------------------------------
```

### Errors

```shell
[07:04:46 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "<parameter1>" is null
[07:04:46 WARN]: at CMI-9.7.4.3.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1190)
[07:04:46 WARN]: at CMI-9.7.4.3.jar//com.Zrips.CMI.utils.Util.fixItemStackFile(Util.java:1216)
[07:04:46 WARN]: at CMI-9.7.4.3.jar//com.Zrips.CMI.Modules.SavedItems.SavedItemManager.load(SavedItemManager.java:133)
[07:04:46 WARN]: at CMI-9.7.4.3.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1541)
[07:04:46 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[07:04:46 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[07:04:46 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[07:04:46 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[07:04:46 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643)
[07:04:46 WARN]: at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592)
[07:04:46 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:755)
[07:04:46 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:517)
[07:04:46 WARN]: at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361)
[07:04:46 WARN]: at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233)
[07:04:46 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332)
[07:04:46 WARN]: at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by illyrius666** [comment]
i have the same issue

**Comment by Zrips** [comment]
New version is out to address this small issue
