### ISSUE TITLE
Loading issues of saved items and kits in 1.21 (paper)

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#8909]
### Description of Issue
An error in the Kits and Saved items on loadup on 1.21

### Version Information
![06-07-2024_17-08-31](https://github.com/Zrips/CMI/assets/12080017/b8857d11-4a5f-4ee6-ae60-8afe114dbdb4)
```

### Errors
```shell
[18:11:16] [Server thread/INFO]: [CMI] Enabling CMI v9.7.4.4
[18:11:16] [Server thread/INFO]: _______________________________________________________
[18:11:16] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[18:11:16] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[18:11:16] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[18:11:16] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[18:11:16] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[18:11:16] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[18:11:16] [Server thread/INFO]: _______________________________________________________
[18:11:17] [Server thread/INFO]: Integrating PaperSpigot async methods
[18:11:17] [Server thread/INFO]: Vault found. (Loaded: true)
[18:11:17] [Server thread/INFO]: Citizens found. (Loaded: true)
[18:11:17] [Server thread/INFO]: 66 Enabled and 0 Disabled modules
[18:11:17] [Server thread/INFO]: Votifier found. (Loaded: false)
[18:11:18] [Server thread/INFO]: Loaded (92) portals into memory. Took 194ms
[18:11:18] [Server thread/INFO]: Loaded (8) dynamic signs into memory. Took 22ms
[18:11:18] [Server thread/INFO]: ProtocolLib found. (Loaded: true)
[18:11:18] [Server thread/INFO]: Permission plugin: PEX permission1.23.5
[18:11:18] [Server thread/INFO]: Initialized Cipher256 AES
[18:11:20] [Server thread/INFO]: Loaded (61) regular alias into memory. Took 75ms
[18:11:20] [Server thread/INFO]: Loaded (27) custom text's into memory. Took 13ms
[18:11:20] [Server thread/INFO]: Detected Java22
[18:11:25] [Server thread/INFO]: 8.0.27 data base type detected
[18:11:31] [Server thread/INFO]: Started MySQL data base. Took 11301ms
[18:11:31] [Server thread/INFO]: Vault was found - Enabling capabilities. Economy: CMIEconomy
[18:11:32] [Server thread/INFO]: Loaded (32) warning categories into memory. Took 1ms
[18:11:32] [Server thread/INFO]: Loaded (10) warning commands into memory. Took 0ms
[18:11:32] [Server thread/INFO]: Loaded (0) cooldowns into memory. Took 0ms
[18:11:32] [Server thread/INFO]: Loaded (144) custom mob heads into memory. Took 19ms
[18:11:32] [Server thread/WARN]: java.util.ConcurrentModificationException
[18:11:32] [Server thread/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023)
[18:11:32] [Server thread/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:1058)
[18:11:32] [Server thread/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:1055)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1194)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.fixItemStackFile(Util.java:1222)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.Modules.Kits.KitsManager.load(KitsManager.java:444)
[18:11:32] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1535)
[18:11:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[18:11:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[18:11:32] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[18:11:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[18:11:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629)
[18:11:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578)
[18:11:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[18:11:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514)
[18:11:32] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327)
[18:11:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219)
[18:11:32] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[18:11:32] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[18:11:33] [Server thread/INFO]: Loaded (56) kits into memory. Took 96ms
[18:11:33] [Server thread/INFO]: Loaded (0) ranks into memory. Took 14ms
[18:11:33] [Server thread/WARN]: java.util.ConcurrentModificationException
[18:11:33] [Server thread/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023)
[18:11:33] [Server thread/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:1058)
[18:11:33] [Server thread/WARN]: 	at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:1055)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1194)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.replaceInternalWithCustom(Util.java:1198)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.utils.Util.fixItemStackFile(Util.java:1222)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.Modules.SavedItems.SavedItemManager.load(SavedItemManager.java:133)
[18:11:33] [Server thread/WARN]: 	at CMI_9.7.4.4.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1541)
[18:11:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[18:11:33] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[18:11:33] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[18:11:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[18:11:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629)
[18:11:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578)
[18:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[18:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514)
[18:11:33] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327)
[18:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219)
[18:11:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[18:11:33] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1570)
[18:11:33] [Server thread/INFO]: Loaded (74) saved items into memory. Took 40ms
[18:11:33] [Server thread/INFO]: Loaded (2) playtime rewards into memory. Took 6ms
[18:11:33] [Server thread/INFO]: Loaded (1) jails into memory. Took 3ms
[18:11:34] [Server thread/INFO]: Loaded (11901) player data into memory. Took 1590ms
[18:11:35] [Server thread/INFO]: Loaded (8313) playtime records into memory. Took 936ms
[18:11:35] [Server thread/INFO]: Loaded (764) playtime reward records into memory. Took 35ms
[18:11:35] [Server thread/INFO]: Loaded (160) custom alias into memory. Took 27ms
[18:11:36] [Server thread/INFO]: Loaded (175) interactive commands into memory. Took 15ms
[18:11:36] [Server thread/INFO]: dynmap found. (Loaded: true)
[18:11:36] [Server thread/INFO]: Registered events. Took 263ms
[18:11:36] [Server thread/INFO]: Loaded (151) event action commands into memory. Took 12ms
[18:11:36] [Server thread/INFO]: Loaded (EN) language file into memory. Took 137ms
[18:11:36] [Server thread/INFO]: Loaded (DE) language file into memory. Took 120ms
[18:11:36] [Server thread/INFO]: Loaded (92) warps into memory. Took 16ms
[18:11:36] [Server thread/INFO]: VaultPermissions found. (Loaded: true)
[18:11:36] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: cmi [9.7.4.4]
[18:11:36] [Server thread/INFO]: PlaceholderAPI hooked.
[18:11:36] [Server thread/INFO]: PlaceholderAPI found. (Loaded: true)
[18:11:36] [Server thread/INFO]: Jobs found. (Loaded: false)
[18:11:36] [Server thread/INFO]: Starting world timer.
[18:11:36] [Server thread/INFO]: Initializing world manager.
[18:11:36] [Server thread/INFO]: Loaded (27) schedules into memory. Took 45ms
[18:11:36] [Server thread/INFO]: Loaded GeoLiteCity
[18:11:36] [Server thread/INFO]: Loaded (49) holograms into memory. Took 112ms
[18:11:36] [Server thread/INFO]: Loaded (2404) skin cache entries into memory. Took 112ms
[18:11:36] [Server thread/INFO]: Loaded (43) custom recipes into memory. Took 65ms
[18:11:36] [Server thread/INFO]: Loaded (3) ArmorStand templates into memory. Took 14ms
[18:11:36] [Server thread/INFO]: Version 9.7.4.4 has been enabled
[18:11:37] [Server thread/INFO]: _______________________________________________________
[18:11:37] [Server thread/INFO]: [CMIEInjector][Economy] CMI Economy hooked.
```

### Relevant Config Sections
Link to kits.yml and saveditems.yml:
Here the 1.21 versions
https://www.file-upload.net/download-15356342/Kits.yml.html
https://www.file-upload.net/download-15356343/SavedItems.yml.html

If you need the old 1.24.0 files from the live server here they are 
https://www.file-upload.net/download-15356389/Kits.yml.html
https://www.file-upload.net/download-15356390/SavedItems.yml.html

### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
well giving me some saved items showed me they lost all attached commands even if i take a backup from our 1.20.4 server where all files are fine..

**Comment by CloudeLecaw** [comment]
If you need the old 1.24.0 files from the live server here they are 

https://www.file-upload.net/download-15356389/Kits.yml.html
https://www.file-upload.net/download-15356390/SavedItems.yml.html

**Comment by Zrips** [comment]
For attached commands to load in you might want to rename "internal" section to "custom" which got renamed with 1.21 update for some reason. Tho that said it should have been updated automatically with latest CMI versions. Will do some testing on monday, but you can just perform that renaming manually if you want it working sooner.

**Comment by CloudeLecaw** [comment]
i can agree that changing all "internal" names to "custom" in the files kits,yml and saveditems.yml solves this issue on our testing server.

But i dont know if everyone wants to change this manually.

**Comment by Momshroom** [comment]
Noting here that I had the same issue on 1.20.6 and changing "internal" to "custom" in my saveditems.yml fixed *most* of my items as well.  Ty for the report!

I still have issues with some HDB head based items, for which I will file a separate report.

**Comment by Momshroom** [comment]
I'm using CMI 9.7.5.0, and the files were still not automatically converted.

**Comment by CloudeLecaw** [comment]
> I'm using CMI 9.7.5.0, and the files were still not automatically converted.
i know. lucklie you just need to convert manually max one time to the new format.

**Comment by CloudeLecaw** [comment]
Closes because issue was solved thank to the advice infos from Zrips how to fix it.
