### ISSUE TITLE
the armor stand is not made invisible with gui

### ISSUE THREAD

**Issue by RemForever0** [Zrips/CMI#8910]
### Description of Issue

When I try to make the armor stand invisible, it doesn't work and writes an error to the console

### Version Information

```shell
Paper 1.12.2-R0.1-SNAPSHOT Java 11
Vault 1.7.3
CMI 9.7.4.3 CMILib 1.5.0.5
```

### Errors

```shell
[20:14:20 WARN]: [CMILib] Task #217895 for CMILib v1.5.0.5 generated an exception
java.lang.NoSuchMethodError: 'boolean org.bukkit.entity.ArmorStand.isInvisible()'
        at com.Zrips.CMI.Modules.AStand.ArmorStandManager$19.lambda$0(ArmorStandManager.java:814) ~[?:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtEntity$3(CMIBukkitImpl.java:158) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update. I mean, button will be hidden, as this option should only be available from 1.13 version.
