### ISSUE TITLE
Exception when player using teleport commands in Folia 1.20.6

### ISSUE THREAD

**Issue by ClayCoffee** [Zrips/CMI#8913]
### Description of Issue

Exception when player using teleport commands in Folia (sometimes, then the server will crash if the player quits the server afterwards.)

### Version Information

```shell
[16:27:40 INFO]: --------------------------------------------------
[16:27:40 INFO]: CMI: 9.7.4.4 SqLite
[16:27:40 INFO]: CMILib: 1.5.0.5
[16:27:40 INFO]: Server: Folia 1.20.6-R0.1-SNAPSHOT-
[16:27:40 INFO]: CMI economy: Enabled Vault: 1.7.3-b0-folia(CMIEInjector) CMI Chat: Disabled 
[16:27:40 INFO]: Modules -> 65 enabled 1 disabled: votifier
[16:27:40 INFO]: --------------------------------------------------
```

### Errors

```shell
https://paste.ubuntu.com/p/jzKhW2VbBv/
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by ClayCoffee** [comment]
Crash Log:
[19:53:28] [Region Scheduler Thread #5/INFO]: JauneMaxWell lost connection: Disconnected
[19:53:28] [Region Scheduler Thread #5/ERROR]: Thread Region Scheduler Thread #5 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:25) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:10) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftEntity.isInsideVehicle(CraftEntity.java:600) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftEntity.getVehicle(CraftEntity.java:615) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.removePassenger(Entity.java:3101) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.removeVehicle(Entity.java:3055) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.stopRiding(Entity.java:3066) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.stopRiding(Entity.java:3062) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.ejectPassengers(Entity.java:3040) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.level.ServerPlayer.disconnect(ServerPlayer.java:2394) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2139) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2119) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2106) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:947) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:519) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1896) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[19:53:28] [Region Scheduler Thread #5/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #26765 centered at chunk [138, -277] in world 'world_nether' failed to tick:
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:25) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftTextDisplay.getHandle(CraftTextDisplay.java:10) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftEntity.isInsideVehicle(CraftEntity.java:600) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftEntity.getVehicle(CraftEntity.java:615) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.removePassenger(Entity.java:3101) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.removeVehicle(Entity.java:3055) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.stopRiding(Entity.java:3066) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.stopRiding(Entity.java:3062) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.world.entity.Entity.ejectPassengers(Entity.java:3040) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.level.ServerPlayer.disconnect(ServerPlayer.java:2394) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2139) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2119) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2106) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:947) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:519) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1896) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1699) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by ClayCoffee** [comment]
@Zrips
