### ISSUE TITLE
cmi openbook still not working and maybe crashing server

### ISSUE THREAD

**Issue by ScuroK** [Zrips/CMI#8940]
### Description of Issue

The latest version of cmi still has problems with openbook and getbook. aftert i tried it the server even crashed

### Version Information

```shell
[11:02:47] [Server thread/INFO]: --------------------------------------------------
[11:02:47] [Server thread/INFO]: CMI plugin version: 9.7.4.5 SqLite
[11:02:47] [Server thread/INFO]: CMILib: 1.5.0.7 
[11:02:47] [Server thread/INFO]: Server: Paper(148) 1.20.6-R0.1-SNAPSHOT+
[11:02:47] [Server thread/INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[11:02:47] [Server thread/INFO]: Modules -> 48 enabled 18 disabled: hpBossBar, mirror, moneyCheque, skin, noTarget, elytraBoost, paintingEditor, playerChatTag, elytraLaunch, durabilityLoss, bossBarCompass, coloredArmor, disabledEnchants, votifier, shulkerBackpack, headDrop, spawnerCharge, totemBehavior
[11:02:47] [Server thread/INFO]: --------------------------------------------------

```

### Errors

```shell
[10:37:31] [Server thread/INFO]: ScuroK issued server command: /cmi getbook Willkommen
[10:37:31] [Server thread/ERROR]: Command exception: /cmi getbook Willkommen
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.4.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 15 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.1.jar:?]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:68) ~[bungeecord-chat-1.20-R0.2-deprecated+build.18.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.Modules.CustomText.CText.convertToBook(CText.java:258) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.list.getbook.perform(getbook.java:88) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.4.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 26 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 15 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.1.jar:?]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:68) ~[bungeecord-chat-1.20-R0.2-deprecated+build.18.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.Modules.CustomText.CText.convertToBook(CText.java:258) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.list.getbook.perform(getbook.java:88) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.4.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 26 more
[10:38:47] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1790) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.world.entity.EntityType cannot be cast to class net.minecraft.world.item.enchantment.Enchantment (net.minecraft.world.entity.EntityType and net.minecraft.world.item.enchantment.Enchantment are in unnamed module of loader java.net.URLClassLoader @1cf4f579)
	at net.minecraft.world.item.enchantment.EnchantmentHelper.getAvailableEnchantmentResults(EnchantmentHelper.java:354) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.selectEnchantment(EnchantmentHelper.java:308) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.enchantItem(EnchantmentHelper.java:284) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.entity.Mob.enchantSpawnedWeapon(Mob.java:1387) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.entity.Mob.populateDefaultEquipmentEnchantments(Mob.java:1371) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.entity.monster.AbstractSkeleton.finalizeSpawn(AbstractSkeleton.java:152) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:293) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:207) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:177) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:634) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:486) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:874) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1779) ~[paper-1.20.6.jar:1.20.6-148-20f5165]
	... 5 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by ScuroK** [comment]
crash report: https://pastebin.com/UFXLq1zn
