### ISSUE TITLE
/cmi openbook error

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/CMI#8941]
### Description of Issue

error on perform cmd /cmi openbook

### Version Information

```shell
CMI Plugin 9.7.4.5
CMILib: 1.5.0.7
Server: Paper(2258) 1.21-R0.1-SNAPCHOT
```

### Errors

```shell
[13:36:12] [Server thread/ERROR]: Command exception: /cmi openbook browser
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.4.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1505) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1512) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1357) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2258-ff19bcc]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.1.jar:?]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:68) ~[bungeecord-chat-1.20-R0.2-deprecated+build.18.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.Modules.CustomText.CText.convertToBook(CText.java:258) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.list.openbook.perform(openbook.java:90) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.4.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	... 27 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.1.jar:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.1.jar:?]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[gson-2.10.1.jar:?]
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:68) ~[bungeecord-chat-1.20-R0.2-deprecated+build.18.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.Modules.CustomText.CText.convertToBook(CText.java:258) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.list.openbook.perform(openbook.java:90) ~[CMI-9.7.4.5.jar:?]
	at CMI-9.7.4.5.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.4.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	... 27 more
[13:36:31] [Server thread/INFO]: Markopolooo issued server command: /ec
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
