### ISSUE TITLE
CMI IC Error

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#895]
Random error happened when I couldn't find the IC name for an entity which was there after a reboot. Then tried re-creating the IC it gave me that error & the IC could not be created.

#### DELETE IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
 [04:56:17 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.18.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.1.jar:git-Paper-317]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-317]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1769) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1573) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-317]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-317]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-317]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at com.Zrips.CMI.Modules.InteractiveCommand.CitizensManager.getEntityUUID(CitizensManager.java:55) ~[?:?]
at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandManager.checkCitizens(InteractiveCommandManager.java:136) ~[?:?]
at com.Zrips.CMI.Modules.InteractiveCommand.InteractiveCommandManager.getByUUID(InteractiveCommandManager.java:126) ~[?:?]
at com.Zrips.CMI.commands.list.ic.perform(ic.java:154) ~[?:?]
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-317]
... 15 more
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

**Cmi Version (using`/cmi version`):**   8.0.18.0

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  1.13.1

**Comment by 0xC1A551C** [comment]
The error was somehow fixed after a reboot. Not sure what happened there.

**Comment by Zrips** [comment]
Will be fixed with next build.
