### ISSUE TITLE
/maxplayers not being set

### ISSUE THREAD

**Issue by EntNZ** [Zrips/CMI#8965]
### Description of Issue

When you set Max Players for example **/maxplayers 25 (while having 9 set)** command will "work" but: 
in chat: 
Changed max allowed players from 9 to 9. Online #. 

### Version Information

```shell
CMI: 9.7.4.7
CMILib: 1.5.0.9
Server: Paper(103) 1.21-R0.1-SNAPSHOT+
CMI Economy: Enabled 
Vault: 1.7.3-CMI 
CMI Chat: Enabled
Modules: 62 Enabled, 4 disabled (SpawnerProx, Votifier, Spawners, SpawnerChange
```

### Errors

```shell
[Sat 18:41:34 INFO  Server/ServerGamePacketListenerImpl] EntNZ issued server command: /maxplayers 25
! [Sat 18:41:34 WARN ] java.lang.NoSuchFieldException: h
! [Sat 18:41:34 WARN ]     at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
! [Sat 18:41:34 WARN ]     at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90)
 
! [Sat 18:41:34 WARN ]     at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source)
! [Sat 18:41:34 WARN ]     at CMI-9.7.4.7.jar//com.Zrips.CMI.Reflections.changePlayerLimit(Reflections.java:318)
! [Sat 18:41:34 WARN ]     at CMI-9.7.4.7.jar//com.Zrips.CMI.commands.list.maxplayers.perform(maxplayers.java:36)
! [Sat 18:41:34 WARN ]     at CMI-9.7.4.7.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400)
! [Sat 18:41:34 WARN ]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
! [Sat 18:41:34 WARN ]     at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
! [Sat 18:41:34 WARN ]     at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.Commands.performCommand(Commands.java:350)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.Commands.performCommand(Commands.java:337)
! [Sat 18:41:34 WARN ]     at net.minecraft.commands.Commands.performCommand(Commands.java:332)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.TickTask.run(TickTask.java:18)
! [Sat 18:41:34 WARN ]     at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
! [Sat 18:41:34 WARN ]     at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
! [Sat 18:41:34 WARN ]     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506)
! [Sat 18:41:34 WARN ]     at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317)
! [Sat 18:41:34 WARN ]     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
! [Sat 18:41:34 WARN ]     at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
