### ISSUE TITLE
PlayerTeleportEvent

### ISSUE THREAD

**Issue by Baleroo** [Zrips/CMI#8969]
### Description of Issue

When a player teleport somewhere

### Version Information

```shell
Cmi 9.7.4.7
CmiLib 1.5.0.9
```

### Errors

```shell
[08:10:08 ERROR]: Could not pass event PlayerTeleportEvent to CMI v9.7.4.7
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getBlockX()" because "<local4>" is null
        at CMI-9.7.4.7.jar/com.Zrips.CMI.Modules.DynamicSigns.SignListener.onPlayerMoveExtendedRnage(SignListener.java:64) ~[CMI-9.7.4.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor452.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2273-61b63b1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1413) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.world.entity.Entity.handlePortal(Entity.java:3326) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:898) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:447) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.world.entity.Entity.tick(Entity.java:871) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3200) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:854) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.network.Connection.tick(Connection.java:647) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1859) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2273-61b63b1]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update

**Comment by tumasov69** [comment]
Time has passed and it has not been fixed

[04:03:18 ERROR]: Could not pass event PlayerTeleportEvent to CMI v9.7.4.9
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because the return value of "org.bukkit.event.player.PlayerTeleportEvent.getTo()" is null
        at CMI-9.7.4.9.jar/com.Zrips.CMI.Modules.Holograms.HologramListener.onPlayerMoveExtendedRnage(HologramListener.java:186) ~[CMI-9.7.4.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor612.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2276-72ccfbd]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1413) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.world.entity.Entity.handlePortal(Entity.java:3326) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:898) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:447) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.world.entity.Entity.tick(Entity.java:871) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3200) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:854) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.network.Connection.tick(Connection.java:647) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1859) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2276-72ccfbd]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
