### ISSUE TITLE
Could not pass event ServerCommandEvent to CMI v9.7.4.7

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#8979]
### Description of Issue

Write in console: **ver**

### Version Information

```shell
[05:16:56 INFO]: -------------------------------------------
[05:16:56 INFO]: CMI: 9.7.4.7 SqLite
[05:16:56 INFO]: CMILib: 1.5.0.8 -> 1.5.0.9
[05:16:56 INFO]: Server: Purpur(2176) 1.20.4-R0.1-SNAPSHOT-
[05:16:56 INFO]: CMI economy: Disabled Vault: 1.7.3-CMI CMI Chat: Disabled
[05:16:56 INFO]: Modules -> 49 enabled 17 disabled: spawnerProximity, tablist, moneyCheque, skin, jail, spawners, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, chatBubble, playerCombat, votifier, shulkerBackpack, spawnerCharge, namePlates
[05:16:56 INFO]: -------------------------------------------
```

### Errors

```shell
> ver
[04:57:05 ERROR]: Could not pass event ServerCommandEvent to CMI v9.7.4.7
java.lang.StringIndexOutOfBoundsException: Range [5, 3) out of bounds for length 3
        at jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.lang.String.substring(String.java:2834) ~[?:?]
        at java.lang.String.substring(String.java:2807) ~[?:?]
        at com.Zrips.CMI.Modules.Alias.onServerPreprocessCommand.onConsoleCommand(onServerPreprocessCommand.java:34) ~[CMI-9.7.4.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor263.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:536) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[04:57:05 INFO]: Checking version, please wait...
[04:57:06 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2174 (MC: 1.20.4)
* You are running the latest version
```

### Relevant Plugins

Vault 1.7.3-CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
