### ISSUE TITLE
Type in tpo and it'll crash.

### ISSUE THREAD

**Issue by HYDeath** [Zrips/CMI#8980]
### Description of Issue

Core: luminol 1.20.4 (belonging to folia)
tp command can't show player's name, only cmi tp can show player's name (but direct tp enter is there after the command), then use tpo player, input the command person will be kicked out of the server due to: Internal Server Error, after 1 minute the server will be restarted due to timeout.
![QQ_1721887744402](https://github.com/user-attachments/assets/dd5bf8ef-e621-462a-a9e6-863211fe434d)

### Version Information

```shell
[14:09:44 INFO]: --------------------------------------------------
[14:09:44 INFO]: CMI 插件版本: 9.7.4.7 SqLite
[14:09:44 INFO]: CMILib: 1.5.0.9
[14:09:44 INFO]: Server: Folia 1.20.4-R0.1-SNAPSHOT-
[14:09:44 INFO]: CMI economy: 启用 Vault: 1.7.3-CMI CMI Chat: 禁用
[14:09:44 INFO]: Modules ➦ 64 enabled 2 disabled: tablist, votifier
[14:09:44 INFO]: --------------------------------------------------
```

### Errors

```shell
[14:02:39 INFO]: HuYa_Death issued server command: /tpo xianzhe414
[14:02:39 ERROR]: Thread Region Scheduler Thread #16 failed main thread check: Cannot move entity off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:526) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:893) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5637) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5597) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.moveTo(Entity.java:2126) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1821) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1779) ~[?:?]
        at com.Zrips.CMI.NBT.v1_20_R3.forceTeleport(v1_20_R3.java:910) ~[[C][基础插件]CMI-9.7.4.7.jar:?]
        at com.Zrips.CMI.commands.list.tpo.perform(tpo.java:79) ~[[C][基础插件]CMI-9.7.4.7.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[[C][基础插件]CMI-9.7.4.7.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1043) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2295) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2255) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1648) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:02:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.4.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1043) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2295) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2255) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1648) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot move entity off-main
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:526) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:893) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5637) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5597) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.moveTo(Entity.java:2126) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1821) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1779) ~[?:?]
        at com.Zrips.CMI.NBT.v1_20_R3.forceTeleport(v1_20_R3.java:910) ~[[C][基础插件]CMI-9.7.4.7.jar:?]
        at com.Zrips.CMI.commands.list.tpo.perform(tpo.java:79) ~[[C][基础插件]CMI-9.7.4.7.jar:?]
        at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[[C][基础插件]CMI-9.7.4.7.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 20 more
[14:02:39 ERROR]: Thread Region Scheduler Thread #16 failed main thread check: Cannot move entity off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:526) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:893) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5637) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPos(Entity.java:792) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.move(Entity.java:1188) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3025) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2959) ~[?:?]
        at net.minecraft.world.entity.player.Player.travel(Player.java:1690) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.travel(ServerPlayer.java:2197) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3541) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:570) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3133) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:274) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:905) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:357) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:657) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:529) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1870) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:02:39 WARN]: [io.papermc.paper.threadedregions.RegionizedWorldData] Failed to handle packet for /IP:56140
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:991) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:357) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:657) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:529) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1870) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot move entity off-main
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:526) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:893) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5637) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPos(Entity.java:792) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.move(Entity.java:1188) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3025) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2959) ~[?:?]
        at net.minecraft.world.entity.player.Player.travel(Player.java:1690) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.travel(ServerPlayer.java:2197) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3541) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:570) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3133) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:274) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:905) ~[?:?]
        ... 10 more
[14:02:40 INFO]: HuYa_Death lost connection: Internal server error
[14:02:40 ERROR]: Thread Region Scheduler Thread #16 failed main thread check: Cannot move entity off-main
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:71) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:526) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:893) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5637) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPos(Entity.java:792) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.move(Entity.java:1188) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3025) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2959) ~[?:?]
        at net.minecraft.world.entity.player.Player.travel(Player.java:1690) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.travel(ServerPlayer.java:2197) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3541) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:570) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3133) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:274) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:905) ~[?:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:882) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:864) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2153) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2131) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:903) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:516) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1870) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[14:02:40 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1024885 centered at chunk [43, -41] in world 'world' failed to tick:
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:991) ~[?:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:882) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:864) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2153) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2131) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:903) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:516) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1870) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot move entity off-main
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:72) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:526) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:893) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5637) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.setPos(Entity.java:792) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.Entity.move(Entity.java:1188) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3025) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:2959) ~[?:?]
        at net.minecraft.world.entity.player.Player.travel(Player.java:1690) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.travel(ServerPlayer.java:2197) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3541) ~[?:?]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:570) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3133) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:274) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:905) ~[?:?]
        ... 14 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Tpo error should be fixed with next update
