### ISSUE TITLE
Backend error.

### ISSUE THREAD

**Issue by chenshupe** [Zrips/CMI#8988]
### Description of Issue

Backend error.

### Version Information

```shell
CMI版本:9.7.4.8 SqLite
[11:31:07 INFO]: CMILib版本:1.5.0.9
[11:31:07 INFO]: 服务器版本:Paper 1.21-R0.1-SNAPSHOT+
[11:31:07 INFO]: CMI经济系统:已启用Vault版本:1.7.3-CMICMI聊天系统:已禁用
[11:31:07 INFO]: 模块 -> 65 已启用 1 已禁用:votifier
```

### Errors

```shell
[11:27:46 ERROR]: Could not pass event PlayerRespawnEvent to CMI v9.7.4.8
java.util.NoSuchElementException: null
        at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1607) ~[?:?]
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
        at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
        at CMI-9.7.4.8.jar/com.Zrips.CMI.utils.SpawnUtil.getSpawnPoint(SpawnUtil.java:206) ~[CMI-9.7.4.8.jar:?]
        at CMI-9.7.4.8.jar/com.Zrips.CMI.Modules.Homes.HomeManager.getReSpawnLocation(HomeManager.java:491) ~[CMI-9.7.4.8.jar:?]
        at CMI-9.7.4.8.jar/com.Zrips.CMI.AllListeners.PlayerListeners.onRespawnSetLocation(PlayerListeners.java:150) ~[CMI-9.7.4.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor131.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayer.findRespawnPositionAndUseSpawnBlock(ServerPlayer.java:1301) ~[?:?]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:885) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:839) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleClientCommand(ServerGamePacketListenerImpl.java:2969) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.handle(ServerboundClientCommandPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundClientCommandPacket.a(ServerboundClientCommandPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:35) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1499) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1478) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1471) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1574) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1263) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.jar:1.21-DEV-1952e41]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next build
