### ISSUE TITLE
Item attributes with /give doesn't working in 1.21

### ISSUE THREAD

**Issue by MaHl111** [Zrips/CMI#8992]
### Description of Issue

Trying to give `diamond_sword` with any modification of attributes (as per [this](https://www.zrips.net/cmi/commands/icwol/)) does not modify attributes and instead results in console warning. Item is given, name, lore and enchants are being applied properly, attributes are not.

Example: `/give diamondsword;&4&lOP_Sword;l{};AttackDamage:15:multiply:Mainhand`

### Version Information

```shell
CMI: 9.7.4.4 SqLite-> 9.7.4.8
CMILib: 1.5.0.9
Server: Paper(44) 1.21-R0.1-SNAPSHOT+
CMI economy: Enabled Vault: 1.7.3-CMI CMIChat: Enabled
Modules -> 65 enabled 1 disabled: votifier
```

### Errors

```shell
[18:49:57 WARN]: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.set(String, String)" because the return value of "net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.get(Object)" is null
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.NBT.CMINBT.setString(CMINBT.java:939)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Reflections.addAttributes(Reflections.java:2265)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemStack.addAttributes(CMIItemStack.java:167)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.applyAttributes(CMIItemSerializer.java:851)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.deserialize(CMIItemSerializer.java:555)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemStack.deserialize(CMIItemStack.java:901)
[18:49:57 WARN]:        at CMI-9.7.4.4.jar//com.Zrips.CMI.commands.list.give.processNewMethod(give.java:124)
[18:49:57 WARN]:        at CMI-9.7.4.4.jar//com.Zrips.CMI.commands.list.give.perform(give.java:268)
[18:49:57 WARN]:        at CMI-9.7.4.4.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400)
[18:49:57 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:49:57 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[18:49:57 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[18:49:57 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[18:49:57 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[18:49:57 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[18:49:57 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[18:49:57 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[18:49:57 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147)
[18:49:57 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121)
[18:49:57 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:49:57 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[18:49:57 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1541)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[18:49:57 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1518)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1511)
[18:49:57 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1470)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1477)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1322)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[18:49:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[18:49:57 WARN]: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.set(String, String)" because the return value of "net.Zrips.CMILib.PersistentData.CMIPersistentDataContainer.get(Object)" is null
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.NBT.CMINBT.setString(CMINBT.java:939)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Reflections.addAttributes(Reflections.java:2265)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemStack.addAttributes(CMIItemStack.java:167)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.applyAttributes(CMIItemSerializer.java:851)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemSerializer.deserialize(CMIItemSerializer.java:555)
[18:49:57 WARN]:        at CMILib1.5.0.9.jar//net.Zrips.CMILib.Items.CMIItemStack.deserialize(CMIItemStack.java:913)
[18:49:57 WARN]:        at CMI-9.7.4.4.jar//com.Zrips.CMI.commands.list.give.processNewMethod(give.java:181)
[18:49:57 WARN]:        at CMI-9.7.4.4.jar//com.Zrips.CMI.commands.list.give.perform(give.java:268)
[18:49:57 WARN]:        at CMI-9.7.4.4.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400)
[18:49:57 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:49:57 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[18:49:57 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[18:49:57 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[18:49:57 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[18:49:57 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[18:49:57 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[18:49:57 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[18:49:57 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[18:49:57 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147)
[18:49:57 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121)
[18:49:57 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:49:57 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[18:49:57 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1541)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[18:49:57 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1518)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1511)
[18:49:57 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1470)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1477)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1322)
[18:49:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[18:49:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
