### ISSUE TITLE
CMI will detect fake players and report errors！

### ISSUE THREAD

**Issue by TH2403y** [Zrips/CMI#8999]
### Description of Issue

![QQ_1722408399656](https://github.com/user-attachments/assets/9173eec3-f7a9-4eda-b49b-dbf56eddd074)
CMI cannot be used with MoDispenserMechanics and will keep reporting errors in my server console，If MoDispenserMechanics is removed, CMI will not report an error, but I need MoDispenserMechanics QAQ

### Version Information

```shell
--------------------------------------------------
[14:43:57 INFO]: CMI版本:9.7.4.8 SqLite
[14:43:57 INFO]: CMILib版本:1.5.0.9
[14:43:57 INFO]: 服务器版本:Paper 1.21-R0.1-SNAPSHOT-
[14:43:57 INFO]: CMI经济系统:EnabledVault版本:1.7.3-CMICMI聊天系统:Enabled
[14:43:57 INFO]: 模块 -> 50 已启用 16 已禁用:cuffed, hpBossBar, tablist, versionCheck, moneyCheque, afk, skin, noTarget, jail, cmiPlaytime, eventCommands, playerChatTag, ranks, playerCombat, votifier, homeInteractions
[14:43:57 INFO]: --------------------------------------------------
```

### Errors

```shell
Can't keep up! Is the server overloaded? Running 6204ms or 124 ticks behind
[11:07:38 WARN]: [CMILib] Task #357 for CMILib v1.5.0.9 generated an exception
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.CMIUser.addFlyToCache(String, boolean, boolean)" because "<local2>" is null
        at CMI-9.7.4.8.jar/com.Zrips.CMI.AllListeners.WorldLimits.lambda$0(WorldLimits.java:115) ~[CMI-9.7.4.8.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1733) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:525) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1615) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:07:38 INFO]: [MythicMobs] Loading ProtocolLib listeners...
[11:07:39 WARN]: [MythicMobs] Could not find required Ammo lore line for item pistol_1
[11:07:39 WARN]: [MythicMobs] Could not find required Ammo lore line for item rifle_1
[11:07:39 INFO]: [MythicMobs] Attached traits to items.
[11:07:39 INFO]: [MythicMobs] Loaded 35 items.
[11:07:39 WARN]: [CMILib] Plugin CMILib v1.5.0.9 generated an exception while executing task 378
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Containers.CMIUser.getOptionState(com.Zrips.CMI.Modules.PlayerOptions.PlayerOption)" because the return value of "com.Zrips.CMI.Containers.CMIUser.getUser(org.bukkit.entity.Player)" is null
        at CMI-9.7.4.8.jar/com.Zrips.CMI.Modules.Holograms.HologramManager.lambda$7(HologramManager.java:423) ~[CMI-9.7.4.8.jar:?]
        at CMILib1.5.0.9.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[CMILib1.5.0.9.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaf-1.21.jar:1.21-DEV-729c6ac]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaf-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) ~[?:?]
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:329) ~[?:?]
```

### Relevant Config Sections

```yaml
He should have nothing to do with the configuration
```

### Relevant Plugins

CMI 9.7.4.8 CMIlib 1.5.0.9 MoDispenserMechanics 1.10.1

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Both errors will be fixed with next update, if you notice any new ones, let me know.

**Comment by TH2403y** [comment]
The error still exists

**Comment by TH2403y** [comment]
> 这两个错误都将在下次更新时修复，如果您发现任何新的错误，请告诉我。

The error still exists

**Comment by TH2403y** [comment]
CMI版本:9.7.4.9 SqLite
[16:46:37 INFO]: CMILib版本:1.5.1.0
[16:46:37 INFO]: 服务器版本:Paper 1.21-R0.1-SNAPSHOT-
[16:46:37 INFO]: CMI经济系统:已启用Vault版本:1.7.3-CMICMI聊天系统:已启用
[16:46:37 INFO]: 模块 -> 50 已启用 16 已禁用:cuffed, hpBossBar, tablist, versionCheck, moneyCheque, afk, skin, noTarget, jail, cmiPlaytime, eventCommands, playerChatTag, ranks, playerCombat, votifier, homeInteractions

**Comment by TH2403y** [comment]
https://paste.gg/p/anonymous/8c29f2c4587743339c653038f4b8365d

**Comment by Zrips** [comment]
New error than previous one, but will be fixed with next update

**Comment by TH2403y** [comment]
Thank you for your help! The problem has been solved!
