### ISSUE TITLE
Error with hologram (CMILib)

### ISSUE THREAD

**Issue by Nunchakin** [Zrips/CMI#9002]
### Description of Issue

I got this error when I had about 20+ players on my server. I experience issues with CMI holograms in 1.21, some do not load and I have to do /cmi reload couple times but then other holograms do not load. Anyways I got this error:
https://pastebin.com/1Kn6BNsB

### Version Information

```shell
[00:58:36 INFO]: --------------------------------------------------
>....
[00:58:36 INFO]: CMI plugin version: 9.7.4.9 SqLite
>....
[00:58:36 INFO]: CMILib: 1.5.1.0
>....
[00:58:36 INFO]: Server: Paper(123) 1.21-R0.1-SNAPSHOT-
>....
[00:58:36 INFO]: CMI economy: Zapnuté Vault: 1.7.3-CMI CMI Chat: Zapnuté
>....
[00:58:36 INFO]: Modules -> 56 enabled 10 disabled: spawnerProximity, flightCharge, hpBossBar, chatBubble, tablist, selection, votifier, spawners, spawnerCharge, nightSpeedup
>....
[00:58:36 INFO]: --------------------------------------------------
```

### Errors

[23:40:35] [Craft Scheduler Thread - 16 - CMILib/WARN]: [CMILib] Plugin CMILib v1.5.1.0 generated an exception while executing task 169037
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
	at CMI-9.7.4.9.jar/com.Zrips.CMI.Modules.Holograms.HologramManager.getAllInRangeByLoc(HologramManager.java:356) ~[CMI-9.7.4.9.jar:?]
	at CMI-9.7.4.9.jar/com.Zrips.CMI.Modules.Holograms.HologramManager.lambda$7(HologramManager.java:399) ~[CMI-9.7.4.9.jar:?]
	at CMILib1.5.1.0.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[CMILib1.5.1.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-123-0a1be9a]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Error will be fixed with next update. If you still have issues with holograms, please make a ticket with as much information about it as you can, including holograms in area which is in question, their type, their content. And include output from **/cmi version** command for better understanding which server in particular is in question.
