### ISSUE TITLE
CMI.Modules.Holograms.HologramManager

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#9026]
### Description of Issue

Error in console

### Version Information

```shell
CMI: 9.7.5.0 SqLite
CMILib: 1.5.1.0
Server: Purpur(2176) 1.20.4-R0.1-SNAPSHOT-
```

### Errors

```shell
[14:45:45 WARN]: [CMILib] Plugin CMILib v1.5.1.0 generated an exception while executing task 9439397
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
        at com.Zrips.CMI.Modules.Holograms.HologramManager.recheckInteractableHolograms(HologramManager.java:1050) ~[CMI-9.7.5.0.jar:?]
        at com.Zrips.CMI.Modules.Holograms.HologramManager.rechecInteractableHolograms(HologramManager.java:1039) ~[CMI-9.7.5.0.jar:?]
        at com.Zrips.CMI.Modules.Holograms.HologramManager.addNearHolo(HologramManager.java:1081) ~[CMI-9.7.5.0.jar:?]
        at com.Zrips.CMI.Modules.Holograms.HologramManager.lambda$7(HologramManager.java:431) ~[CMI-9.7.5.0.jar:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[CMILib1.5.1.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
