### ISSUE TITLE
[MobFarmManager] Error on Ver 3.01.9

### ISSUE THREAD

**Issue by Strahilchu** [Zrips/CMI#9052]
### Description of Issue

[20:37:50 WARN]: java.lang.InterruptedException
[20:37:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[20:37:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[20:37:50 WARN]:        at MobFarmManager3.0.1.9.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:299)
[20:37:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[20:37:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:37:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[20:37:50 WARN]:        at org.bukkit.craftbukkit.CraftWorld.lambda$getChunkAtAsync$14(CraftWorld.java:2474)
[20:37:50 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:37:50 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[20:37:50 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[20:37:50 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544)
[20:37:50 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1503)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1510)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1355)
[20:37:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[20:37:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Version Information

```shell
[20:43:57 INFO]: CMI: 9.7.5.3 SqLite
[20:43:57 INFO]: CMILib: 1.5.1.1 
[20:43:57 INFO]: Server: Paper(2295) 1.21.1-R0.1-SNAPSHOT+
[20:43:57 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled
```

### Errors

```shell
[20:43:50 WARN]: java.lang.InterruptedException
[20:43:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[20:43:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[20:43:50 WARN]:        at MobFarmManager3.0.1.9.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:299)
[20:43:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[20:43:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:43:50 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[20:43:50 WARN]:        at org.bukkit.craftbukkit.CraftWorld.lambda$getChunkAtAsync$14(CraftWorld.java:2474)
[20:43:50 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:43:50 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[20:43:50 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[20:43:50 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1574)
[20:43:50 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[20:43:50 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[20:43:50 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1551)
[20:43:50 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1544)
[20:43:50 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[20:43:50 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1666)
[20:43:50 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335)
[20:43:50 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[20:43:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
Confirming the same on Paper 1.21.1-39-master@3271119 with MFM 3.0.1.9
Error: https://gist.github.com/mercurialmusic/80881dc094c9c1e460d55a71f6437568

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/MobFarmManager/issues

**Comment by Zrips** [comment]
Update to new 3.0.2.0 version which should resolve your issues
