### ISSUE TITLE
error with cmi lib

### ISSUE THREAD

**Issue by elhadesgamer97** [Zrips/CMI#9086]
### Description of Issue

A new version of the cmi lib came out and when updating it, a CMI lib error started to appear. I would like to know if there is a way to fix this error since it appears every time you write in the chat.

### Version Information

```shell
CMI version: 9.7.5.4
Cmi lib version: 1.5.1.1
```

### Errors

```shell
[01:36:02 WARN]: [CMILib] Plugin CMILib v1.5.1.1 generated an exception while executing task 4519
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.setWidth(double)" because "this.tDisplay" is null
        at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.updateLooks(CMIChatBubble.java:159) ~[CMI-9.7.5.4.jar:?]
        at CMI-9.7.5.4.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.lambda$2(CMIChatBubble.java:88) ~[CMI-9.7.5.4.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by elhadesgamer97** [comment]
I'll be waiting because with the new one they released I still get the error every time they write something in the chat:

USER hadesgamer97: nice
[20:39:19 WARN]: [CMILib] Plugin CMILib v1.5.1.1 generated an exception while executing task 18408
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.update(org.bukkit.entity.Player, boolean)" because "this.tDisplay" is null
        at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.lambda$2(CMIChatBubble.java:90) ~[CMI-9.7.5.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
