### ISSUE TITLE
Chat bubbles still causing errors on paper 1.21.1 on CMI 9.7.5.5

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#9089]
### Description of Issue

When talking to players close enough to them that chat bubbles appear, there is a console error.  The chat bubbles do work.

### Version Information

```shell
:59:34 INFO]: --------------------------------------------------
[15:59:34 INFO]: CMI plugin version: 9.7.5.5 MySQL-> 9.7.5.4
[15:59:34 INFO]: CMILib: 1.5.1.1 
[15:59:34 INFO]: Server: Paper(40) 1.21.1-R0.1-SNAPSHOT+
[15:59:34 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[15:59:34 INFO]: Modules -> 58 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[15:59:34 INFO]: --------------------------------------------------
```

### Errors

```shell
[15:47:32 WARN]: [CMILib] Plugin CMILib v1.5.1.1 generated an exception while executing task 102921
java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Display.CMITextDisplay.update(org.bukkit.entity.Player, boolean)" because "this.tDisplay" is null
        at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.Chat.CMIChatBubble.lambda$2(CMIChatBubble.java:90) ~[CMI-9.7.5.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-40-2fdb2e9]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]                                                                                                                                       
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]   ```
```

### Relevant Config Sections

```yaml
# Defines default states for player options
    # This will not have any effect if player already edited his options with /cmi options command
    Defaults:
      visibleHolograms: true
      shiftSignEdit: true
      totemBossBar: true
      bossBarCompass: true
      tagSound: true
      # !Strongly not recommended to be enabled!
      chatSpy: false
      # !Strongly not recommended to be enabled!
      cmdSpy: false
      # !Strongly not recommended to be enabled!
      signSpy: false
      acceptingPM: true
      acceptingTPA: true
      acceptingMoney: true
      chatbubble: true
      pmSound: true
      rideMe: true
      pveDamageNumbers: true
      pvpDamageNumbers: true
      InformDurability: true```
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Momshroom** [comment]
Fixed in 9.7.5.6
