### ISSUE TITLE
This makes DeluxeMenus unusable.

### ISSUE THREAD

**Issue by NEIKI19914** [Zrips/CMI#9103]
### Description of Issue

[07:54:09] [Server thread/INFO]: MagicMakes issued server command: /cd
[07:54:09] [Craft Scheduler Thread - 38 - DeluxeMenus/WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.14.0-Release generated an exception while executing task 9679
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "com.Zrips.CMI.Containers.CMIUser.getWarnings()" is null
	at CMI-9.7.5.7.jar/com.Zrips.CMI.Modules.Placeholders.Placeholder.getValue(Placeholder.java:1041) ~[CMI-9.7.5.7.jar:?]
	at CMI-9.7.5.7.jar/com.Zrips.CMI.Modules.Placeholders.Placeholder.translatePAPIPlaceHolder(Placeholder.java:809) ~[CMI-9.7.5.7.jar:?]
	at CMI-9.7.5.7.jar/com.Zrips.CMI.Modules.Placeholders.PlaceholderAPIHook.onPlaceholderRequest(PlaceholderAPIHook.java:53) ~[CMI-9.7.5.7.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
	at DeluxeMenus-1.14.0-Release.jar/com.extendedclip.deluxemenus.menu.MenuHolder.setPlaceholders(MenuHolder.java:95) ~[DeluxeMenus-1.14.0-Release.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at DeluxeMenus-1.14.0-Release.jar/com.extendedclip.deluxemenus.menu.MenuItem.getItemStack(MenuItem.java:298) ~[DeluxeMenus-1.14.0-Release.jar:?]
	at DeluxeMenus-1.14.0-Release.jar/com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$5(Menu.java:418) ~[DeluxeMenus-1.14.0-Release.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Version Information

```shell
CMI-9.7.5.7
CMILib1.5.1.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
