### ISSUE TITLE
EntityDamageEvent error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9105]
### Description of Issue

Hello, sometimes this error appears, it's caused by DeadlyDisasters, but it would be good to have some protection on CMI side as well, to prevent these errors by other plugins?

It's happening for a few versions already

### Version Information

```shell
[17:30:30 INFO]: CMI: 9.7.5.5 SqLite-> 9.7.5.7
[17:30:30 INFO]: CMILib: 1.5.1.0 -> 1.5.1.3
[17:30:30 INFO]: Server: Paper(2298) 1.21.1-R0.1-SNAPSHOT-
[17:30:30 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[17:30:30 INFO]: Modules -> 53 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
```

### Errors

```shell
[12:58:52] [Server thread/ERROR]: Could not pass event EntityDamageEvent to CMI v9.7.5.5
java.lang.NullPointerException: Cannot invoke "org.bukkit.event.entity.EntityDamageEvent$DamageCause.equals(Object)" because the return value of "org.bukkit.event.entity.EntityDamageEvent.getCause()" is null
	at CMI-9.7.5.5.jar/com.Zrips.CMI.AllListeners.LaunchPadListener.EntityDamageEvent(LaunchPadListener.java:38) ~[CMI-9.7.5.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2298-a61db94]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at DeadlyDisastersPRO-V14.7.jar/com.github.jewishbanana.deadlydisasters.utils.Utils.pureDamageEntity(Utils.java:718) ~[DeadlyDisastersPRO-V14.7.jar:?]
	at DeadlyDisastersPRO-V14.7.jar/com.github.jewishbanana.deadlydisasters.utils.Utils.pureDamageEntity(Utils.java:748) ~[DeadlyDisastersPRO-V14.7.jar:?]
	at DeadlyDisastersPRO-V14.7.jar/com.github.jewishbanana.deadlydisasters.items.VoidTear$1.run(VoidTear.java:77) ~[DeadlyDisastersPRO-V14.7.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Plugins

DeadlyDisasters (but can happen to other plugins too)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
