### ISSUE TITLE
Interactable holograms error 1.16 & 1.17

### ISSUE THREAD

**Issue by deHasher** [Zrips/CMI#9117]
### Description of Issue

When creating an Interactable hologram, an error is spammed into the console (by the way, when getting the CMI version via the /cmi version command too :D)

### Version Information

```shell
31.08 23:11:23 [Server] WARN java.lang.NoSuchMethodException: org.bukkit.Bukkit.getVersionMessage()
31.08 23:11:23 [Server] WARN at java.base/java.lang.Class.getMethod(Class.java:2395)
31.08 23:11:23 [Server] WARN at com.Zrips.CMI.commands.list.version.lambda$0(version.java:63)
31.08 23:11:23 [Server] WARN at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48)
31.08 23:11:23 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
31.08 23:11:23 [Server] WARN at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
31.08 23:11:23 [Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
31.08 23:11:23 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
31.08 23:11:23 [Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
31.08 23:11:23 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:1583)
31.08 23:11:23 [Server] INFO --------------------------------------------------
31.08 23:11:23 [Server] INFO CMI: 9.7.5.9 SqLite
31.08 23:11:23 [Server] INFO CMILib: 1.5.1.3
31.08 23:11:23 [Server] INFO Server: Purpur(1171) 1.16.5-R0.1-SNAPSHOT-
31.08 23:11:23 [Server] INFO CMI economy: Включено Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Включено
31.08 23:11:23 [Server] INFO --------------------------------------------------
```

### Errors

```shell
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: java.lang.IllegalAccessError: class com.Zrips.CMI.NBT.v1_16_R3 tried to access protected field com.Zrips.CMI.Modules.Packets.PacketHandler.fakeEntities (com.Zrips.CMI.NBT.v1_16_R3 and com.Zrips.CMI.Modules.Packets.PacketHandler are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @4932ce)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.Zrips.CMI.NBT.v1_16_R3.spawnClickable(v1_16_R3.java:777)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.Zrips.CMI.Modules.Holograms.CMIHologram.oldUpdate(CMIHologram.java:2224)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$15(CMIHologram.java:2313)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[23:02:19] [ForkJoinPool.commonPool-worker-5/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
```


### Relevant Config Sections

_No response_

### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Both issues will be fixed with next update
