### ISSUE TITLE
Dispatch error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9121]
### Description of Issue

Hello, I'm getting the mentioned error below.

### Version Information

```shell
[14:37:29 INFO]: CMI: 9.7.5.5 SqLite-> 9.7.5.9
[14:37:29 INFO]: CMILib: 1.5.1.0 -> 1.5.1.3
[14:37:29 INFO]: Server: Paper(2298) 1.21.1-R0.1-SNAPSHOT-
[14:37:29 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[14:37:29 INFO]: Modules -> 53 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
[14:37:29 INFO]: --------------------------------------------------
```

### Errors

```shell
[14:18:18] [Server thread/WARN]: [CMILib] Task #42502644 for CMILib v1.5.1.0 generated an exception
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.5.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1014) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1205) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1104) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:418) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:324) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.processCmds(SpecializedCommandManager.java:262) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Containers.CommandReg$ReflectCommand.execute(CommandReg.java:256) ~[CMI-9.7.5.5.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1014) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.dispatch(SpecializedCommandManager.java:1205) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.executeCmd(SpecializedCommandManager.java:1104) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.process(SpecializedCommandManager.java:418) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.Modules.SpecializedCommands.SpecializedCommandManager.lambda$1(SpecializedCommandManager.java:413) ~[CMI-9.7.5.5.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.network.ServerGamePacketListenerImpl.send(net.minecraft.network.protocol.Packet)" because "this.connection" is null
	at net.minecraft.server.level.ServerPlayer.setPlayerWeather(ServerPlayer.java:2958) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at net.minecraft.server.level.ServerPlayer.resetPlayerWeather(ServerPlayer.java:3002) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at org.bukkit.craftbukkit.entity.CraftPlayer.resetPlayerWeather(CraftPlayer.java:1766) ~[purpur-1.21.1.jar:1.21.1-2298-a61db94]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.commands.list.pweather.perform(pweather.java:102) ~[CMI-9.7.5.5.jar:?]
	at CMI-9.7.5.5.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:400) ~[CMI-9.7.5.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	... 24 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Something weird/invalid triggering specialized commands, this either happens from console or remote console (rcon). Will make some changes relating to this and add more debug messages in case it repeats just to have better idea what happen in your case. If issue persists with next update let me know with new error messages which should include performed command so that you could more easily track back which place triggers it.
