### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by asygames** [Zrips/CMI#9149]
### Description of Issue

I se this in console when I open chests on vanish

### Version Information

```shell
[18:05:08 INFO]: CMI: 9.7.6.1 SqLite
[18:05:08 INFO]: CMILib: 1.5.1.3 
[18:05:08 INFO]: Server: Folia(5) 1.20.6-R0.1-SNAPSHOT-
[18:05:08 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Enabled 
[18:05:08 INFO]: Modules -> 62 enabled 4 disabled: chatBubble, tablist, votifier, skin
```

### Errors

```shell
[18:03:42 WARN]: [CMILib] Global task for CMILib v1.5.1.3 generated an exception
java.lang.IllegalStateException: Cannot read world asynchronously
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:58) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at org.bukkit.craftbukkit.block.CraftBlock.getNMS(CraftBlock.java:80) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:247) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at org.bukkit.craftbukkit.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at org.bukkit.craftbukkit.block.CraftBlock.getState(CraftBlock.java:349) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at CMI-9.7.6.1.jar/com.Zrips.CMI.Modules.SilentChest.silentChestListener.lambda$2(silentChestListener.java:442) ~[CMI-9.7.6.1.jar:?]
        at CMILib1.5.1.3.jar/net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$runTaskLater$2(CMIFoliaImpl.java:74) ~[CMILib1.5.1.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.6.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-5-d797082]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
