### ISSUE TITLE
Téléportation /tp console error !

### ISSUE THREAD

**Issue by Proemmis** [Zrips/CMI#9152]
### Description of Issue

Hi,
every time I teleport with /tp or something else, a console error appears: https://pastebin.com/GcF4ScPN

### Version Information

```shell
[11:30:41] [Server thread/INFO]: --------------------------------------------------
[11:30:41] [Server thread/INFO]: CMI: 9.7.6.1 SqLite
[11:30:41] [Server thread/INFO]: CMILib: 1.5.1.3
[11:30:41] [Server thread/INFO]: Serveur: Spigot 1.12.2-R0.1-SNAPSHOT-
[11:30:41] [Server thread/INFO]: CMI economy: Activé Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Activé
[11:30:41] [Server thread/INFO]: Modules -> 58 activés 8 désactivés: deathMessages, chatBubble, tablist, ranks, playerCombat, votifier, headDrop, jail
[11:30:41] [Server thread/INFO]: --------------------------------------------------
```

### Errors

```shell
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Asynchronous player tracker update!
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: Caused by: java.lang.IllegalStateException: Asynchronous player tracker update!
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:423)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at net.citizensnpcs.nms.v1_12_R1.util.PlayerlistTrackerEntry.func_73117_b(PlayerlistTrackerEntry.java:44)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at net.minecraft.entity.EntityTracker.func_180245_a(EntityTracker.java:332)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at net.minecraft.entity.player.EntityPlayerMP.func_175135_B(EntityPlayerMP.java:1671)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at net.minecraft.entity.player.EntityPlayerMP.func_71016_p(EntityPlayerMP.java:1493)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setFlying(CraftPlayer.java:1293)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$21(TeleportHandler.java:561)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
[11:26:41] [ForkJoinPool.commonPool-worker-21/WARN]: ... 6 more
[11:26:46] [Server thread/INFO]: Proemmis issued server command: /arenes
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Asynchronous player tracker update!
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:975)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: Caused by: java.lang.IllegalStateException: Asynchronous player tracker update!
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:423)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at net.citizensnpcs.nms.v1_12_R1.util.PlayerlistTrackerEntry.func_73117_b(PlayerlistTrackerEntry.java:44)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at net.minecraft.entity.EntityTracker.func_180245_a(EntityTracker.java:332)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at net.minecraft.entity.player.EntityPlayerMP.func_175135_B(EntityPlayerMP.java:1671)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at net.minecraft.entity.player.EntityPlayerMP.func_71016_p(EntityPlayerMP.java:1493)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setFlying(CraftPlayer.java:1293)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$21(TeleportHandler.java:561)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
[11:26:50] [ForkJoinPool.commonPool-worker-14/WARN]: ... 6 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
