### ISSUE TITLE
Error when /spaen

### ISSUE THREAD

**Issue by pepters** [Zrips/CMI#9158]
### Description of Issue

Sometimes wen player write /spawn this error appears, this started happening after update

### Version Information

```shell
[10:19:27] [Server thread/INFO]: Версия плагина CMI: 9.7.6.2 SqLite
[10:19:27] [Server thread/INFO]: CMILib: 1.5.1.3 
[10:19:27] [Server thread/INFO]: Версия сервера: Paper(794) 1.16.5-R0.1-SNAPSHOT-
[10:19:27] [Server thread/INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMICMI Чат: Включено 
[10:19:27] [Server thread/INFO]: Модули -> 31 включено 35 отключено: spawnerProximity, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, elytraBoost, eventCommands, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, headDrop, spawnerCharge, namePlates, timedCommands, homeInteractions, signEdit, armorstand, anvilRenameColor, spawners, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, ranks, warmup, totemBehavior
```

### Errors

```shell
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: java.util.concurrent.CompletionException: java.lang.IllegalStateException: PlayerTeleportEvent may only be triggered synchronously.
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.AsyncTeleportPaper.teleportAsync(AsyncTeleportPaper.java:15)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.Environment.teleport(Environment.java:38)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.PaperLib.teleportAsync(PaperLib.java:98)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.finalizeTeleportation(TeleportHandler.java:449)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at com.Zrips.CMI.Modules.Teleportations.TeleportHandler.lambda$19(TeleportHandler.java:534)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: Caused by: java.lang.IllegalStateException: PlayerTeleportEvent may only be triggered synchronously.
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:898)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at net.Zrips.CMILib.Version.PaperMethods.AsyncTeleportPaper.lambda$teleportAsync$0(AsyncTeleportPaper.java:15)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[10:16:47] [ForkJoinPool.commonPool-worker-1/WARN]: 	... 14 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
