### ISSUE TITLE
Unknown warn (latest)

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9159]
### Description of Issue

Warn in console:

```
[12:59:17 WARN]: java.lang.NullPointerException: Cannot invoke "com.Zrips.CMI.Modules.Afk.AfkInfo.getAfkFrom()" because the return value of "com.Zrips.CMI.Modules.Afk.AfkManager.getAfkInfo(java.util.UUID)" is null
[12:59:17 WARN]:        at CMI-9.7.6.2.jar//com.Zrips.CMI.Modules.Afk.AfkManager.isAfk(AfkManager.java:50)
[12:59:17 WARN]:        at CMI-9.7.6.2.jar//com.Zrips.CMI.Containers.CMIUser.isAfk(CMIUser.java:1640)
[12:59:17 WARN]:        at CMI-9.7.6.2.jar//com.Zrips.CMI.Modules.Afk.AfkManager.lambda$3(AfkManager.java:603)
[12:59:17 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[12:59:17 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[12:59:17 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:59:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[12:59:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[12:59:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Version Information

```shell
[13:04:28 INFO]: Версия плагина CMI: 9.7.6.2 SqLite
[13:04:28 INFO]: CMILib: 1.5.1.3 
[13:04:28 INFO]: Версия сервера: Paper(2304) 1.21.1-R0.1-SNAPSHOT-
[13:04:28 INFO]: CMI Экономика: Вкл Версия Vault: 1.7.3-CMICMI Чат: Выкл 
[13:04:28 INFO]: Модули -> 31 включено 35 отключено: spawnerProximity, cuffed, customMessages, mirror, tablist, armorEffects, moneyCheque, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, elevator, chatBubble, votifier, shulkerBackpack, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, signEdit, hpBossBar, anvilRenameColor, jail, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, disabledEnchants, worldLimitsElytra, ranks, silentChest
```
```


### Errors

_No response_

### Relevant Config Sections

_No response_

### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by GG-MD** [comment]
I'm assuming it's a problem accessing Mojang's servers.

**Comment by GG-MD** [comment]
@Zrips ...

**Comment by Zrips** [comment]
Will be fixed with next update
