### ISSUE TITLE
CMILib v1.5.1.3 generated an exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by smscentras** [Zrips/CMI#9166]
### Description of Issue

CMILib v1.5.1.3 generated an exception java.lang.NullPointerException

### Version Information

```shell
CMI: 9.7.6.2 SqLite
CMILib: 1.5.1.3
Server: Paper(2284) 1.21-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled
Modules -> 49 enabled 17 disabled: spawnerProximity, tablist, moneyCheque, skin, jail, spawners, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, worldLimits, chatBubble, playerCombat, votifier, shulkerBackpack, spawnerCharge, namePlates
```

### Errors

```shell
[CMILib] Task #8492887 for CMILib v1.5.1.3 generated an exception
java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Version.Schedulers.CMITask.cancel()" because "this.schedId" is null
        at CMI-9.7.6.2.jar/com.Zrips.CMI.Modules.Holograms.CMIHologram.lambda$16(CMIHologram.java:2707) ~[CMI-9.7.6.2.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1762) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

### Relevant Plugins

Vault 1.7.3-CMI

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be addressed with next update

**Comment by SawHute** [comment]
in the CMILib config, set "false" to auto update

**Comment by smscentras** [comment]
I have allways:
AutoUpdate: false

Problem not in this setting.
