### ISSUE TITLE
Incorrect hint for shout chat in cross-server case

### ISSUE THREAD

**Issue by YTTRR** [Zrips/CMI#9201]
### Description of Issue

Player in other server received my shout message(start with !), however CMI still hint me "Nobody hear you, write ! before message for global chat"
![(B~K$F0BVXQ@NIZKB(IQ5X0](https://github.com/user-attachments/assets/c9756f18-ecea-46da-a1c3-43c819603a3a)

### Version Information

```shell
[03:08:07 INFO]: --------------------------------------------------
[03:08:07 INFO]: CMI: 9.7.6.5 BungeeCord CMIB  SqLite-> 9.7.6.4
[03:08:07 INFO]: CMILib: 1.5.1.4
[03:08:07 INFO]: Server: Paper(196) 1.20.1-R0.1-SNAPSHOT-
[03:08:07 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Enabled
[03:08:07 INFO]: Modules -> 65 enabled 1 disabled: votifier
[03:08:07 INFO]: --------------------------------------------------
```

### Relevant Config Sections

```yaml
Chat:
  Ranged:
    # Defines range of regular messages to travel
    # Set to -1 to disable range restriction
    General: 100
    # Defines range of shout messages to travel
    # Shout messages should start with ! and player should have cmi.chat.shout permission
    # GeneralRange should be enabled
    # set to 0 to shout across all worlds, -1 to disable
    Shout: 0
    # Defines cost for each shout message
    ShoutCost: 2
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by YTTRR** [comment]
When send message at the first time after server start up, there is a warn:

[03:59:30 INFO]: [Not Secure] [S]HelloWorld: .
[03:59:30 WARN]: java.lang.NoSuchFieldException: c
[03:59:30 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[03:59:30 WARN]:        at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.initPassengerPacket(CMIDisplay.java:353)
[03:59:30 WARN]:        at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.Display.CMIDisplay.addAsPassenger(CMIDisplay.java:367)
[03:59:30 WARN]:        at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.Chat.CMIChatBubble.lambda$3(CMIChatBubble.java:80)
[03:59:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[03:59:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[03:59:30 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
[03:59:30 WARN]:        at CMILib1.5.1.4.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runAtLocation$2(CMIBukkitImpl.java:124)
[03:59:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[03:59:30 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[03:59:30 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1479)
[03:59:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[03:59:30 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1393)
[03:59:30 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1170)
[03:59:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[03:59:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Zrips** [comment]
Both issues will be fixed with next version
