### ISSUE TITLE
Error dispatching event PluginMessageEvent(super=TargetedEvent when loading cmi bungee when player joins

### ISSUE THREAD

**Issue by TechnicolorDev** [Zrips/CMI#9205]
### Description of Issue

[11:23:56 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@47758a0b, receiver=Harenoty), cancelled=false, tag=cmib:fromserver) to listener net.Zrips.MessageListener@345d641e
java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null
        at net.Zrips.MessageListener.getSenderServer(MessageListener.java:25) ~[?:?]
        at net.Zrips.MessageListener.on(MessageListener.java:203) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at net.md_5.bungee.event.EventBus.post(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at net.md_5.bungee.connection.DownstreamBridge.handle(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at net.md_5.bungee.protocol.packet.PluginMessage.handle(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at s.channelRead(Unknown Source) ~[bungeecord.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at net.md_5.bungee.protocol.MinecraftDecoder.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source) ~[bungeecord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
        at java.lang.Thread.run(Thread.java:1583) [?:?]

### Version Information

```shell
Proxy version: X-Cord latest
Cmi version: 9.7.6.5
Server version: Paper - 1.20.4
```

### Relevant Plugins

Vault - 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
New version is out of CMIB, you can download it.
