### ISSUE TITLE
SEVERE SAVE ERROR WHILE SAVING PLAYER DATA (Homes)

### ISSUE THREAD

**Issue by gaRt3n** [Zrips/CMI#9209]
### Description of Issue

I got kicked several times after that error occures. Server already restarted.

### Version Information

```shell
[02:23:46 INFO]: --------------------------------------------------
[02:23:46 INFO]: CMI Plugin Version: 9.7.6.5 Velocity CMIB  MySQL
[02:23:46 INFO]: CMILib: 1.5.1.4 
[02:23:46 INFO]: Server: Purpur(2315) 1.21.1-R0.1-SNAPSHOT-
[02:23:46 INFO]: CMI economy: Deaktiviert Vault: 1.7.3-CMI CMI Chat: Deaktiviert 
[02:23:46 INFO]: Modules -> 48 enabled 18 disabled: spawnerProximity, mirror, tablist, nightSpeedup, paintingEditor, eventCommands, playerChatTag, flightCharge, deathMessages, elevator, ranks, firstJoinMessages, shulkerBackpack, headDrop, spawnerCharge, interactiveCommands, timedCommands, homeInteractions

[02:23:46 INFO]: --------------------------------------------------version
[02:23:49 INFO]: Checking version, please wait...
[02:23:49 INFO]: Current Purpur Version: 1.21.1-2315-2a50638 (MC: 1.21.1)*
* You are 8 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-82-1348e44 (MC: 1.21.1)
```

### Errors

```shell
[02:21:41 INFO]: [CMI]  SEVERE SAVE ERROR WHILE SAVING gaRt3n PLAYER DATA (Homes)
[02:21:41 WARN]: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Container.CMILocation.recheck()" because "this.loc" is null
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.Homes.CmiHome.getLoc(CmiHome.java:36)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:964)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayerRecord(DBDAO.java:747)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:689)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:479)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBManager.lambda$0(DBManager.java:411)
[02:21:41 WARN]: 	at CMILib1.5.1.4.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48)
[02:21:41 WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[02:21:41 WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:21:41 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:21:41 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[02:21:41 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[02:21:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.Homes.CmiHome.getLoc(CmiHome.java:36)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayerRecord(DBDAO.java:747)
[02:21:41 WARN]: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Container.CMILocation.recheck()" because "this.loc" is null
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.PlayerManager.savePlayerToDB(PlayerManager.java:964)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.updatePlayer(DBDAO.java:689)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBManager.saveBatch(DBManager.java:479)
[02:21:41 WARN]: 	at CMI-9.7.6.5.jar//com.Zrips.CMI.Modules.DataBase.DBManager.lambda$0(DBManager.java:411)
[02:21:41 WARN]: 	at CMILib1.5.1.4.jar//net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48)
[02:21:41 WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[02:21:41 WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[02:21:41 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:21:41 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[02:21:41 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[02:21:41 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Fixed with latest version, some additional small fixes will come out with next update
