### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by AlphaAlphaAlpha** [Zrips/CMI#9248]
### Description of Issue

[19:42:10] [Server thread/INFO]: [CMI] Permission plugin: LuckPerms5.4.121
[19:42:10] [Server thread/WARN]: [CMILib] Task #38 for CMILib v1.5.2.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getEnvironment()" because "<local2>" is null
	at CMI-9.7.7.1.jar/com.Zrips.CMI.utils.TimeManager.runDayTimer(TimeManager.java:187) ~[CMI-9.7.7.1.jar:?]
	at CMI-9.7.7.1.jar/com.Zrips.CMI.utils.TimeManager.lambda$2(TimeManager.java:152) ~[CMI-9.7.7.1.jar:?]
	at CMILib1.5.2.0.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTask$0(CMIBukkitImpl.java:33) ~[CMILib1.5.2.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Version Information

```shell
--------------------------------------------------
CMI Plugin Version: 9.7.7.1 BungeeCord CMIB  MySQL-> 9.7.6.11
CMILib: 1.5.2.0 
Server: Purpur(2324) 1.21.1-R0.1-SNAPSHOT-
CMI economy: Aktiviert Vault: 1.7.3-b131(CMIEInjector) CMI Chat: Deaktiviert 
Modules -> 41 enabled 26 disabled: customMessages, tablist, moneyCheque, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, chatBubble, playerCombat, votifier, shulkerBackpack, attachedCommands, interactiveCommands, timedCommands, homeInteractions, portals, dynamicSigns, playerChatTag, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, firstJoinMessages, selection, sitAnimation, warmup
--------------------------------------------------
```

### Errors

```shell
[19:42:10] [Server thread/INFO]: [CMI] Permission plugin: LuckPerms5.4.121
[19:42:10] [Server thread/WARN]: [CMILib] Task #38 for CMILib v1.5.2.0 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getEnvironment()" because "<local2>" is null
	at CMI-9.7.7.1.jar/com.Zrips.CMI.utils.TimeManager.runDayTimer(TimeManager.java:187) ~[CMI-9.7.7.1.jar:?]
	at CMI-9.7.7.1.jar/com.Zrips.CMI.utils.TimeManager.lambda$2(TimeManager.java:152) ~[CMI-9.7.7.1.jar:?]
	at CMILib1.5.2.0.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTask$0(CMIBukkitImpl.java:33) ~[CMILib1.5.2.0.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Config Sections

```yaml
idk
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
