### ISSUE TITLE
Could not pass event InventoryClickEvent to CMI v9.7.7.1 & startup error

### ISSUE THREAD

**Issue by TomLewis** [Zrips/CMI#9250]
### Description of Issue

Thousands of errors in console

### Version Information

```shell
[22:34:34] [Server thread/INFO]: --------------------------------------------------
[22:34:34] [Server thread/INFO]: CMI: 9.7.7.1 Velocity CMIB  MySQL
[22:34:34] [Server thread/INFO]: CMILib: 1.5.2.0 
[22:34:34] [Server thread/INFO]: Server: Purpur(1632) 1.18.2-R0.1-SNAPSHOT-
[22:34:34] [Server thread/INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[22:34:34] [Server thread/INFO]: Modules -> 45 enabled 22 disabled: spawnerProximity, hpBossBar, customMessages, mirror, tablist, moneyCheque, skin, anvilRenameColor, noTarget, elytraBoost, dynamicSigns, playerChatTag, elytraLaunch, flightCharge, disabledEnchants, worldLimits, chatBubble, votifier, shulkerBackpack, attachedCommands, namePlates, homeInteractions
[22:34:34] [Server thread/INFO]: --------------------------------------------------
```

### Errors

```shell
Startup errors:

[22:19:04] [Server thread/INFO]: _______________________________________________________
[22:19:04] [Server thread/INFO]: ┏━━━┓ ┏━┓┏━┓ ┏━━┓
[22:19:04] [Server thread/INFO]: ┃┏━┓┃ ┃ ┗┛ ┃ ┗┫┣┛
[22:19:04] [Server thread/INFO]: ┃┃ ┗┛ ┃┏┓┏┓┃  ┃┃ 
[22:19:04] [Server thread/INFO]: ┃┃ ┏┓ ┃┃┃┃┃┃  ┃┃ 
[22:19:04] [Server thread/INFO]: ┃┗━┛┃ ┃┃┃┃┃┃ ┏┫┣┓
[22:19:04] [Server thread/INFO]: ┗━━━┛ ┗┛┗┛┗┛ ┗━━┛
[22:19:04] [Server thread/INFO]: _______________________________________________________
[22:19:04] [Server thread/INFO]: Integrating PaperSpigot async methods
[22:19:04] [Server thread/INFO]: Vault found. (Loaded: true)
[22:19:04] [Server thread/INFO]: Citizens found. (Loaded: false)
[22:19:04] [Server thread/INFO]: Loaded (67) 45 Enabled and 22 Disabled modules into memory. Took 50ms
[22:19:04] [Server thread/INFO]: Votifier found. (Loaded: true)
[22:19:04] [Server thread/INFO]: Loaded (46) portals into memory. Took 27ms
[22:19:04] [Server thread/INFO]: ProtocolLib found. (Loaded: true)
[22:19:04] [Server thread/INFO]: Initialized Cipher256 AES
[22:19:04] [Server thread/INFO]: Loaded (61) regular alias into memory. Took 23ms
[22:19:04] [Server thread/INFO]: Loaded (130) custom text's into memory. Took 9ms
[22:19:04] [Server thread/INFO]: (RandomTeleportation) Can't find world with (locker) name
[22:19:04] [Server thread/INFO]: (RandomTeleportation) Can't find world with (Halloween2020) name
[22:19:04] [Server thread/INFO]: (RandomTeleportation) Can't find world with (xmas) name
[22:19:04] [Server thread/INFO]: (RandomTeleportation) Can't find world with (Event) name
[22:19:04] [Server thread/INFO]: (RandomTeleportation) Can't find world with (PirateCraft_1_nether2) name
[22:19:04] [Server thread/INFO]: (RandomTeleportation) Can't find world with (winter) name
[22:19:04] [Server thread/INFO]: (RandomTeleportation) Can't find world with (autumn2024) name
[22:19:04] [Server thread/INFO]: Detected Java17
[22:19:04] [Server thread/INFO]: 5.5.5-10.6.19-MariaDB-deb11 data base type detected
[22:19:04] [Server thread/INFO]: Loaded (-) MySQL into memory. Took 216ms
[22:19:04] [Server thread/WARN]: [CMI] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend or softdepend of this plugin.
[22:19:04] [Server thread/INFO]: Vault was found - Enabling capabilities. Economy: EssentialsX Economy
[22:19:04] [Server thread/INFO]: Loaded (5) warning categories into memory. Took 0ms
[22:19:04] [Server thread/INFO]: Loaded (3) warning commands into memory. Took 1ms
[22:19:04] [Server thread/INFO]: Loaded (14) cooldowns into memory. Took 0ms
[22:19:04] [Server thread/INFO]: Loaded (142) custom mob heads into memory. Took 11ms
[22:19:04] [Server thread/INFO]: Loaded (6) warmups into memory. Took 0ms
[22:19:05] [Server thread/INFO]: Initializing BungeeCord
[22:19:05] [Server thread/INFO]: Loaded (99) kits into memory. Took 239ms
[22:19:05] [Server thread/INFO]: Loaded (8) ranks into memory. Took 11ms
[22:19:05] [Server thread/INFO]: Loaded (2) saved items into memory. Took 1ms
[22:19:05] [Server thread/INFO]: Loaded (151) playtime rewards into memory. Took 13ms
[22:19:05] [Server thread/INFO]: Loaded (2) jails into memory. Took 1ms
[22:19:07] [Server thread/WARN]: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.ArrayList (java.lang.String and java.util.ArrayList are in module java.base of loader 'bootstrap')
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1820)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1242)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:587)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1568)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[22:19:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[22:19:07] [Server thread/WARN]: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.ArrayList (java.lang.String and java.util.ArrayList are in module java.base of loader 'bootstrap')
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1820)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1242)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:587)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1568)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[22:19:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[22:19:07] [Server thread/WARN]: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.ArrayList (java.lang.String and java.util.ArrayList are in module java.base of loader 'bootstrap')
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1820)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1242)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:587)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1568)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[22:19:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[22:19:07] [Server thread/WARN]: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.ArrayList (java.lang.String and java.util.ArrayList are in module java.base of loader 'bootstrap')
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadUserFromDb(PlayerManager.java:1820)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.Modules.DataBase.DBDAO.loadAllUsers(DBDAO.java:1242)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.PlayerManager.loadData(PlayerManager.java:587)
[22:19:07] [Server thread/WARN]: 	at CMI-9.7.7.1.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1568)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[22:19:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[22:19:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[22:19:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[22:19:09] [Server thread/WARN]: java.lang.ClassCastException
[22:19:11] [Server thread/WARN]: java.lang.ClassCastException
[22:19:12] [Server thread/WARN]: java.lang.ClassCastException
[22:19:12] [Server thread/WARN]: java.lang.ClassCastException
[22:19:12] [Server thread/WARN]: java.lang.ClassCastException
[22:19:13] [Server thread/WARN]: [CMILib] Loaded class com.Zrips.CMI.Containers.Snd from CMI v9.7.7.1 which is not a depend or softdepend of this plugin.
[22:19:13] [Server thread/WARN]: java.lang.ClassCastException
[22:19:13] [Server thread/WARN]: java.lang.ClassCastException
[22:19:13] [Server thread/WARN]: java.lang.ClassCastException
[22:19:18] [Server thread/INFO]: 
```

Thousands of these being spammed constatntly
.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
	at com.Zrips.CMI.AllListeners.HatListeners.hatPlacement(HatListeners.java:58) ~[CMI-9.7.7.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor691.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2947) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by TomLewis** [comment]
Ive had to backdate, as its spamming the console so much that the wrapper thinks theres an issue and keeps rebooting the server.

**Comment by kikelkik** [comment]
Same here for the newest version 9.7.7.2

**Comment by Zrips** [comment]
Listener issue got resolved with .3 and load error will be resolved with next update
