### ISSUE TITLE
[19:39:45 ERROR]: Could not pass event InventoryCreativeEvent to CMI v9.7.7.2

### ISSUE THREAD

**Issue by boringwolf** [Zrips/CMI#9255]
### Description of Issue

/warp command use and console loop error

### Version Information

```shell
[19:42:13 INFO]: --------------------------------------------------
[19:42:13 INFO]: CMI 插件版本: 9.7.7.2 SqLite-> 9.7.7.1
[19:42:13 INFO]: CMILib: 1.5.2.0 
[19:42:13 INFO]: 伺服器: Paper 1.20.4-R0.1-SNAPSHOT-
[19:42:13 INFO]: CMI economy: 禁用 CMI 聊天: 禁用 
[19:42:13 INFO]: 模塊 -> 66 已開起 1 已關閉: votifier
[19:42:13 INFO]: --------------------------------------------------
```

### Errors

```shell
[19:39:45 ERROR]: Could not pass event InventoryCreativeEvent to CMI v9.7.7.2
java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
        at com.Zrips.CMI.AllListeners.HatListeners.hatPlacement(HatListeners.java:55) ~[CMI-9.7.7.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor632.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[wolfmc-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[wolfmc-api-1.20.4-R0.1-SNAPSHOT.jar:git-WolfMC-"70a0fd8"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[wolfmc-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[wolfmc-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCreativeModeSlot(ServerGamePacketListenerImpl.java:3330) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:18) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundSetCreativeModeSlotPacket.handle(ServerboundSetCreativeModeSlotPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1516) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[wolfmc-1.20.4.jar:git-WolfMC-"70a0fd8"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fully resolved with next update
