### ISSUE TITLE
Problem with /chat

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [Zrips/CMI#926]
**Description of issue or feature request:**
When player1 type /chat player2 and start chatting it seems like this: http://prntscr.com/l2y2yd First line is regular chat and second line is bug
---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

---

**Cmi Version (using`/cmi version`):** 
8.0.19.0
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.13.1 335b

**Comment by Kryniowesegryderiusz** [comment]
`06.10 19:53:55 [Server] ERROR Could not pass event AsyncPlayerChatEvent to CMI v8.0.19.0
06.10 19:53:55 [Server] INFO org.bukkit.event.EventException: null
06.10 19:53:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1657) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1572) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
06.10 19:53:55 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
06.10 19:53:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
06.10 19:53:55 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
06.10 19:53:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
06.10 19:53:55 [Server] INFO Caused by: java.lang.IllegalStateException: Asynchronous command dispatch!
06.10 19:53:55 [Server] INFO at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:651) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO at com.Zrips.CMI.utils.RawMessage.show(RawMessage.java:508) ~[?:?]
06.10 19:53:55 [Server] INFO at com.Zrips.CMI.utils.RawMessage.show(RawMessage.java:489) ~[?:?]
06.10 19:53:55 [Server] INFO at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:264) ~[?:?]
06.10 19:53:55 [Server] INFO at com.Zrips.CMI.Modules.ChatFormat.ChatFormatManager.sendMessage(ChatFormatManager.java:194) ~[?:?]
06.10 19:53:55 [Server] INFO at com.Zrips.CMI.commands.list.msg.perform(msg.java:94) ~[?:?]
06.10 19:53:55 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
06.10 19:53:55 [Server] INFO at com.Zrips.CMI.Modules.ChatFormat.ChatFormatListener.AsyncPlayerChatEvent(ChatFormatListener.java:37) ~[?:?]
06.10 19:53:55 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor602.execute(Unknown Source) ~[?:?]
06.10 19:53:55 [Server] INFO at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-1.13.1-b335.jar:git-Paper-335]
06.10 19:53:55 [Server] INFO ... 11 more
`
