### ISSUE TITLE
error for new player

### ISSUE THREAD

**Issue by pepters** [Zrips/CMI#9270]
### Description of Issue

when new player joins sometimes plugin give this error 

### Version Information

```shell
[12:53:17 INFO]: --------------------------------------------------
[12:53:17 INFO]: Версия плагина CMI: 9.7.7.5 SqLite
[12:53:17 INFO]: CMILib: 1.5.2.1 
[12:53:17 INFO]: Версия сервера: Paper(794) 1.16.5-R0.1-SNAPSHOT-
[12:53:17 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMICMI Чат: Включено 
[12:53:17 INFO]: Модули -> 31 включено 36 отключено: spawnerProximity, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, elytraBoost, eventCommands, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, shulkerBackpack, headDrop, spawnerCharge, namePlates, timedCommands, homeInteractions, signEdit, armorstand, anvilRenameColor, spawners, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, ranks, warmup, totemBehavior
[12:53:17 INFO]: --------------------------------------------------
```

### Errors

```shell
[12:51:11 INFO]: UUID of player BubLik57 is 11c28722-62ff-3908-8a8a-1833ced78ba4
[12:51:11 ERROR]: Could not pass event PlayerJoinEvent to CMI v9.7.7.5
java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
        at com.Zrips.CMI.Containers.CMIPermissionPlayerData.updatePrefix(CMIPermissionPlayerData.java:79) ~[?:?]
        at com.Zrips.CMI.Containers.CMIPermissionPlayerData.getPrefix(CMIPermissionPlayerData.java:116) ~[?:?]
        at com.Zrips.CMI.Containers.CMIUser.getPrefix(CMIUser.java:632) ~[?:?]
        at com.Zrips.CMI.Locale.Language.replacePlayer(Language.java:459) ~[?:?]
        at com.Zrips.CMI.Locale.Language.replaceUser(Language.java:495) ~[?:?]
        at com.Zrips.CMI.Locale.Language.updateSnd(Language.java:326) ~[?:?]
        at com.Zrips.CMI.Locale.Language.getLMessage(Language.java:201) ~[?:?]
        at com.Zrips.CMI.Locale.Language.getMessage(Language.java:116) ~[?:?]
        at com.Zrips.CMI.Locale.CMILC.getMsg(CMILC.java:291) ~[?:?]
        at com.Zrips.CMI.Locale.CMILC.getLocale(CMILC.java:254) ~[?:?]
        at com.Zrips.CMI.AllListeners.CustomMessagesListener.onJoin(CustomMessagesListener.java:133) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor259.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1520) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[12:51:11 INFO]: BubLik57 joined the game
[12:51:11 INFO]: BubLik57[/83.139.159.139:49020] logged in with entity id 310514 at ([world]-106.16, 60.0, -242.53)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by pepters** [comment]
https://pastebin.com/vHhPiFnv

**Comment by pepters** [comment]
this day it happened 14 times

**Comment by Zrips** [comment]
Will be fixed with next version
