### ISSUE TITLE
resetback error?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#9285]
### Description of Issue

Hello, I'm getting the error mentioned below on resetback cmd.

### Version Information

```shell
[13:37:18 INFO]: --------------------------------------------------
[13:37:18 INFO]: CMI: 9.7.7.8 SqLite
[13:37:18 INFO]: CMILib: 1.5.2.2 
[13:37:18 INFO]: Server: Purpur(2329) 1.21.1-R0.1-SNAPSHOT-
[13:37:18 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
[13:37:18 INFO]: Modules -> 54 enabled 13 disabled: customMessages, mirror, tablist, skin, playerChatTag, disabledEnchants, chatBubble, ranks, firstJoinMessages, playerCombat, votifier, sitAnimation, namePlates
```

### Errors

```shell
cmi resetback The_Revenge_x -s -death
[13:35:21 WARN]: Unexpected exception while parsing console command "cmi resetback The_Revenge_x -s -death"
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.7.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:178) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1015) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:1000) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:566) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:514) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Container.CMILocation.getWorldName()" because "<parameter1>" is null
        at CMI-9.7.7.8.jar/com.Zrips.CMI.Containers.CMIUser.setDeathLoc(CMIUser.java:474) ~[CMI-9.7.7.8.jar:?]
        at CMI-9.7.7.8.jar/com.Zrips.CMI.commands.list.resetback.perform(resetback.java:55) ~[CMI-9.7.7.8.jar:?]
        at CMI-9.7.7.8.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:413) ~[CMI-9.7.7.8.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
