### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by pepters** [Zrips/CMI#9309]
### Description of Issue

this happens quite often

### Version Information

```shell
[12:42:57 INFO]: --------------------------------------------------
[12:42:57 INFO]: Версия плагина CMI: 9.7.7.10 SqLite
[12:42:57 INFO]: CMILib: 1.5.2.2 
[12:42:57 INFO]: Версия сервера: Paper(794) 1.16.5-R0.1-SNAPSHOT-
[12:42:57 INFO]: CMI Экономика: Включено Версия Vault: 1.7.3-CMICMI Чат: Включено 
[12:42:57 INFO]: Модули -> 31 включено 36 отключено: spawnerProximity, mirror, tablist, versionCheck, armorEffects, moneyCheque, skin, noTarget, elytraBoost, eventCommands, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, playerCombat, shulkerBackpack, headDrop, spawnerCharge, namePlates, timedCommands, homeInteractions, signEdit, armorstand, anvilRenameColor, spawners, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, flightCharge, disabledEnchants, worldLimitsElytra, worldLimits, ranks, warmup, totemBehavior
[12:42:57 INFO]: --------------------------------------------------
```

### Errors

```shell
[12:37:33 WARN]: [CMI] Plugin CMI v9.7.7.10 generated an exception while executing task 7105806
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
        at java.util.HashMap.putMapEntries(HashMap.java:511) ~[?:?]
        at java.util.HashMap.<init>(HashMap.java:484) ~[?:?]
        at com.Zrips.CMI.Modules.Portals.PortalManager.lambda$1(PortalManager.java:90) ~[?:?]
        at net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTaskAsynchronously$1(CMIBukkitImpl.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next version
