### ISSUE TITLE
On startup; error setting worth for potions

### ISSUE THREAD

**Issue by SkeletonAce** [Zrips/CMI#9312]
### Description of Issue

Worth of Instant Healing potions not being set on server startup
https://mcpaste.com/b6f2a4de002511b3dad77e4cc833b28a
When the server is running and the plugin is reloaded it works normally
https://mcpaste.com/ddfc4461969892cfd2d71336baaeb9b7

### Version Information

```shell
[13:23:53 INFO]: CMI: 9.7.7.10 SqLite
[13:23:53 INFO]: CMILib: 1.5.2.2 
[13:23:53 INFO]: Server: Purpur(2329) 1.21.1-R0.1-SNAPSHOT+
[13:23:53 INFO]: CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
[13:23:53 INFO]: Modules -> 30 enabled 37 disabled: spawnerProximity, cuffed, customMessages, mirror, tablist, moneyCheque, skin, noTarget, elytraBoost, eventCommands, bossBarCompass, playerCombat, shulkerBackpack, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, homeInteractions, hpBossBar, launchPad, anvilRenameColor, jail, spawners, dynamicSigns, playerChatTag, durabilityLoss, flightCharge, deathMessages, schedule, disabledEnchants, worldLimitsElytra, worldLimits, firstJoinMessages, selection, sitAnimation, totemBehavior
```

### Errors

```shell
[06:01:08] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[06:01:08] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:28)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:536)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:199)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:163)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1693)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[06:01:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[06:01:08] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[06:01:08] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:28)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:536)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:199)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:163)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1693)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[06:01:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[06:01:08] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[06:01:08] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:28)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:536)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:199)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:163)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1693)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[06:01:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[06:01:08] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[06:01:08] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:28)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:536)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:199)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:163)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1693)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[06:01:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[06:01:08] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[06:01:08] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:28)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:536)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:199)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:163)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1693)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[06:01:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[06:01:08] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[06:01:08] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:28)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:536)
[06:01:08] [Server thread/WARN]: 	at CMILib1.5.2.2.jar//net.Zrips.CMILib.Items.ItemManager.getItem(ItemManager.java:199)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.Modules.Worth.WorthManager.load(WorthManager.java:163)
[06:01:08] [Server thread/WARN]: 	at CMI-9.7.7.10.jar//com.Zrips.CMI.CMI.onEnable(CMI.java:1693)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[06:01:08] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655)
[06:01:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:366)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230)
[06:01:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[06:01:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

### Relevant Config Sections

```yaml
POTION>NIGHT_VISION-false-false: 54.25
    POTION>NIGHT_VISION-false-true: 67.25
    POTION>INVISIBILITY-false-false: 66.75
    POTION>INVISIBILITY-false-true: 79.75
    POTION>JUMP-false-false: 94.25
    POTION>JUMP-false-true: 107.25
    POTION>JUMP-true-false: 96.75
    POTION>FIRE_RESISTANCE-false-false: 52.75
    POTION>FIRE_RESISTANCE-false-true: 65.75
    POTION>SPEED-false-false: 13.25
    POTION>SPEED-false-true: 26.25
    POTION>SPEED-true-false: 15.75
    POTION>SLOW-false-false: 25.75
    POTION>SLOW-false-true: 38.75
    POTION>SLOW-true-false: 28.25
    POTION>WATER_BREATHING-false-false: 18.25
    POTION>WATER_BREATHING-false-true: 31.25
    POTION>HEAL-false-false: 48.75
    POTION>HEAL-true-false: 51.25
    POTION>HARM-false-false: 25.25
    POTION>HARM-true-false: 27.75
    POTION>POISON-false-false: 12.75
    POTION>POISON-false-true: 25.75
    POTION>POISON-true-false: 15.25
    POTION>REGENERATION-false-false: 210.25
    POTION>REGENERATION-false-true: 223.25
    POTION>REGENERATION-true-false: 212.75
    POTION>INCREASE_DAMAGE-false-false: 32.75
    POTION>INCREASE_DAMAGE-false-true: 45.75
    POTION>INCREASE_DAMAGE-true-false: 35.25
    POTION>WEAKNESS-false-false: 15.75
    POTION>WEAKNESS-false-true: 28.75
    POTION>SLOW_FALLING-false-false: 160.25
    POTION>SLOW_FALLING-false-true: 173.25
    SPLASH_POTION>NIGHT_VISION-false-false: 60.75
    SPLASH_POTION>NIGHT_VISION-false-true: 73.75
    SPLASH_POTION>INVISIBILITY-false-false: 73.25
    SPLASH_POTION>INVISIBILITY-false-true: 86.25
    SPLASH_POTION>JUMP-false-false: 100.75
    SPLASH_POTION>JUMP-false-true: 113.75
    SPLASH_POTION>JUMP-true-false: 103.25
    SPLASH_POTION>FIRE_RESISTANCE-false-false: 59.25
    SPLASH_POTION>FIRE_RESISTANCE-false-true: 72.25
    SPLASH_POTION>SPEED-false-false: 19.75
    SPLASH_POTION>SPEED-false-true: 32.75
    SPLASH_POTION>SPEED-true-false: 22.25
    SPLASH_POTION>SLOW-false-false: 32.25
    SPLASH_POTION>SLOW-false-true: 45.25
    SPLASH_POTION>SLOW-true-false: 34.75
    SPLASH_POTION>WATER_BREATHING-false-false: 24.75
    SPLASH_POTION>WATER_BREATHING-false-true: 37.75
    SPLASH_POTION>HEAL-false-false: 55.25
    SPLASH_POTION>HEAL-true-false: 57.75
    SPLASH_POTION>HARM-false-false: 31.75
    SPLASH_POTION>HARM-true-false: 34.25
    SPLASH_POTION>POISON-false-false: 19.25
    SPLASH_POTION>POISON-false-true: 32.25
    SPLASH_POTION>POISON-true-false: 21.75
    SPLASH_POTION>REGENERATION-false-false: 216.75
    SPLASH_POTION>REGENERATION-false-true: 229.75
    SPLASH_POTION>REGENERATION-true-false: 219.25
    SPLASH_POTION>INCREASE_DAMAGE-false-false: 39.25
    SPLASH_POTION>INCREASE_DAMAGE-false-true: 52.25
    SPLASH_POTION>INCREASE_DAMAGE-true-false: 41.75
    SPLASH_POTION>WEAKNESS-false-false: 22.25
    SPLASH_POTION>WEAKNESS-false-true: 35.25
    SPLASH_POTION>SLOW_FALLING-false-false: 166.75
    SPLASH_POTION>SLOW_FALLING-false-true: 179.75
    LINGERING_POTION>NIGHT_VISION-false-false: 70.75
    LINGERING_POTION>NIGHT_VISION-false-true: 83.75
    LINGERING_POTION>INVISIBILITY-false-false: 83.25
    LINGERING_POTION>INVISIBILITY-false-true: 96.25
    LINGERING_POTION>JUMP-false-false: 62.75
    LINGERING_POTION>JUMP-false-true: 75.75
    LINGERING_POTION>JUMP-true-false: 65.25
    LINGERING_POTION>FIRE_RESISTANCE-false-false: 46.75
    LINGERING_POTION>FIRE_RESISTANCE-false-true: 59.75
    LINGERING_POTION>SPEED-false-false: 29.75
    LINGERING_POTION>SPEED-false-true: 42.75
    LINGERING_POTION>SPEED-true-false: 32.25
    LINGERING_POTION>SLOW-false-false: 42.25
    LINGERING_POTION>SLOW-false-true: 55.25
    LINGERING_POTION>SLOW-true-false: 44.75
    LINGERING_POTION>WATER_BREATHING-false-false: 34.75
    LINGERING_POTION>WATER_BREATHING-false-true: 47.75
    LINGERING_POTION>HEAL-false-false: 65.25
    LINGERING_POTION>HEAL-true-false: 67.75
    LINGERING_POTION>HARM-false-false: 41.75
    LINGERING_POTION>HARM-true-false: 44.25
    LINGERING_POTION>POISON-false-false: 29.25
    LINGERING_POTION>POISON-false-true: 42.25
    LINGERING_POTION>POISON-true-false: 31.75
    LINGERING_POTION>REGENERATION-false-false: 226.75
    LINGERING_POTION>REGENERATION-true-false: 229.25
    LINGERING_POTION>REGENERATION-false-true: 239.75
    LINGERING_POTION>INCREASE_DAMAGE-false-false: 49.25
    LINGERING_POTION>INCREASE_DAMAGE-false-true: 62.25
    LINGERING_POTION>INCREASE_DAMAGE-true-false: 51.75
    LINGERING_POTION>WEAKNESS-false-false: 32.25
    LINGERING_POTION>WEAKNESS-false-true: 45.25
    LINGERING_POTION>SLOW_FALLING-false-false: 176.75
    LINGERING_POTION>SLOW_FALLING-false-true: 189.75
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next CMILib update. Tho you might need to reset some potions, mainly the ones which involves values with "true" in them.
