### ISSUE TITLE
/cmi importfrom essentials warp - not being saved?

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#935]
Issue: It seems after importing Warps from essentials that after server restart the warps are not saved?
Posted here; https://www.spigotmc.org/threads/20-off-sale-cmi-240-commands-insane-kits-portals-essentials-economy-mysql-sqlite-much.48111/page-262#post-3171768

---

**ERROR **
```
[20:13:20 INFO]: mrfloris issued server command: /cmi importfrom essentials warp
[20:13:20 WARN]: java.lang.NullPointerException
[20:13:20 WARN]:     at com.Zrips.CMI.Modules.Warps.WarpManager$10.run(WarpManager.java:597)
[20:13:20 WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[20:13:20 WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:13:20 WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:13:20 WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:13:20 WARN]:     at java.lang.Thread.run(Thread.java:748)
>
```

After import which appears to be going fine, minus the console msg, the /cmi warp will load with the warps. Then you /save-all, and /stop, start the server, once connect again and /cmi warp, and it is empty. 

---

**Cmi Version (using`/cmi version`):**  8.0.15.0

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** ```>ver
[06:01:25 INFO]: This server is running CraftBukkit version git-Spigot-2cf50f0-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[06:01:25 INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
>```

We can't wait to upgrade from CMI 7 to CMI 8, but it seems the same issue happens in CMI 8. Unfortn. Hoping to have a solution soon?

**Comment by xion87** [comment]
I already reported this on https://github.com/Zrips/CMI/issues/923

**Comment by mrfloris** [comment]
The current version 8.2.x seems to work for me. We no longer have anything to import, so I can not confirm it. But we have what we wanted now, we got a successful import and are happy.

I just cannot confirm I can import again, or from another source etc. I dont know if it's fixed for everybody or I just got lucky.

**Comment by mrfloris** [comment]
We've been using this for a while now and haven't had any issues since, when we're importing. I think we can close this - especially after today's comment in another issue ticket that old-locations will remain in the system as well.
