### ISSUE TITLE
[11:50:41 ERROR]: Could not pass event PlayerItemDamageEvent to CMI v9.7.7.12

### ISSUE THREAD

**Issue by Volkraft** [Zrips/CMI#9357]
### Description of Issue

[11:50:41 ERROR]: Could not pass event PlayerItemDamageEvent to CMI v9.7.7.12

### Version Information

```shell
[11:51:28 INFO]: --------------------------------------------------
[11:51:28 INFO]: CMI версия плагина: 9.7.7.12 SqLite-> 9.7.8.1
[11:51:28 INFO]: CMILib: 1.5.2.4 
[11:51:28 INFO]: Server: Paper(196) 1.20.1-R0.1-SNAPSHOT-
[11:51:28 INFO]: CMI economy: Включено Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Выключено 
[11:51:28 INFO]: Modules -> 61 enabled 6 disabled: spawnerProximity, tablist, votifier, skin, spawners, spawnerCharge
[11:51:28 INFO]: --------------------------------------------------
```

### Errors

```shell
[11:50:41 ERROR]: Could not pass event PlayerItemDamageEvent to CMI v9.7.7.12
java.lang.NoSuchMethodError: 'short net.Zrips.CMILib.Items.CMIItemStack.getDurability()'
        at com.Zrips.CMI.AllListeners.PlayerItemDamageListener.itemDurabilityLoss(PlayerItemDamageListener.java:42) ~[CMI-9.7.7.12.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor632.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.item.ItemStack.hurt(ItemStack.java:620) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.item.ItemStack.hurtAndBreak(ItemStack.java:658) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.item.DiggerItem.lambda$mineBlock$1(DiggerItem.java:50) ~[?:?]
        at net.minecraft.world.item.ItemStack.mineBlock(ItemStack.java:711) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:440) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1927) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [ ] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Update CMI to the latest version or downgrade CMILib to previous one
