### ISSUE TITLE
recipe bundle [ERROR]

### ISSUE THREAD

**Issue by GG-MD** [Zrips/CMI#9358]
### Description of Issue

using cmd /recipe on 1.21.1 version.
error console..

<img width="323" alt="image" src="https://github.com/user-attachments/assets/56d0fe3f-ddd7-4f30-a071-7ea175e13a4b" />

### Version Information

```shell
[15:04:06 INFO]: --------------------------------------------------
[15:04:06 INFO]: Версия плагина CMI: 9.7.8.1 SqLite
[15:04:06 INFO]: CMILib: 1.5.2.4 
[15:04:06 INFO]: Версия сервера: Purpur(2358) 1.21.3-R0.1-SNAPSHOT-
[15:04:06 INFO]: CMI Экономика: Вкл Версия Vault: 1.7.3-CMICMI Чат: Выкл 
[15:04:06 INFO]: Модули -> 32 включено 35 отключено: spawnerProximity, cuffed, customMessages, mirror, tablist, armorEffects, moneyCheque, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, coloredArmor, elevator, chatBubble, votifier, shulkerBackpack, attachedCommands, spawnerCharge, interactiveCommands, namePlates, timedCommands, signEdit, hpBossBar, anvilRenameColor, jail, paintingEditor, dynamicSigns, playerChatTag, durabilityLoss, deathMessages, disabledEnchants, worldLimitsElytra, ranks, silentChest
[15:04:06 INFO]: --------------------------------------------------
```
```


### Errors

```shell
[15:03:19 INFO]: MDucke issued server command: /recipe
[15:03:19 ERROR]: Command exception: /cmi recipe
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.8.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:363) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2320) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2294) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1624) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1601) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1594) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1545) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1555) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1391) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.Zrips.CMILib.Container.CMINamespacedKey.getKey()" because the return value of "net.Zrips.CMILib.Container.CMINamespacedKey.getKey(org.bukkit.inventory.Recipe)" is null
        at CMI-9.7.8.1.jar/com.Zrips.CMI.Modules.Recipes.RecipeManager.openRecipeUI(RecipeManager.java:532) ~[CMI-9.7.8.1.jar:?]
        at CMI-9.7.8.1.jar/com.Zrips.CMI.commands.list.recipe.perform(recipe.java:95) ~[CMI-9.7.8.1.jar:?]
        at CMI-9.7.8.1.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:413) ~[CMI-9.7.8.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 27 more
> 
```
```


### Relevant Config Sections

_No response_

### Relevant Plugins

_No response_

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update
