### ISSUE TITLE
[17:43:43 ERROR]: Could not pass event PlayerItemDamageEvent to CMI v9.7.7.12

### ISSUE THREAD

**Issue by Volkraft** [Zrips/CMI#9359]
### Description of Issue

[17:43:43 ERROR]: Could not pass event PlayerItemDamageEvent to CMI v9.7.7.12

### Version Information

```shell
[17:58:39 INFO]: CMI версия плагина: 9.7.7.12 SqLite-> 9.7.8.1
[17:58:39 INFO]: CMILib: 1.5.2.4 
[17:58:39 INFO]: Server: Paper(196) 1.20.1-R0.1-SNAPSHOT-
[17:58:39 INFO]: CMI economy: Включено Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Выключено 
[17:58:39 INFO]: Modules -> 61 enabled 6 disabled: spawnerProximity, tablist, votifier, skin, spawners, spawnerCharge
```

### Errors

```shell
[17:43:43 ERROR]: Could not pass event PlayerItemDamageEvent to CMI v9.7.7.12
java.lang.NoSuchMethodError: 'short net.Zrips.CMILib.Items.CMIItemStack.getDurability()'
        at com.Zrips.CMI.AllListeners.PlayerItemDamageListener.itemDurabilityLoss(PlayerItemDamageListener.java:42) ~[CMI-9.7.7.12.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor418.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.item.ItemStack.hurt(ItemStack.java:620) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.item.ItemStack.hurtAndBreak(ItemStack.java:658) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.item.SwordItem.hurtEnemy(SwordItem.java:50) ~[?:?]
        at net.minecraft.world.item.ItemStack.hurtEnemy(ItemStack.java:702) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1413) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2168) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.a(ServerGamePacketListenerImpl.java:2913) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2837) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Plugins

Vault 1.7.3

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Upgrading CMI or downgrading CMILib by one version will resolve this issue
