### ISSUE TITLE
When using serviceio instead of vault, cmi reports an error when using other economic plugins.

### ISSUE THREAD

**Issue by JellyBubb1e** [Zrips/CMI#9361]
### Description of Issue

When using serviceio instead of vault, cmi reports an error when using other economic plugins.

### Version Information

```shell
CMI v9.7.8.1
```

### Errors

```shell
https://mclo.gs/KaT5Bjl
```

### Relevant Config Sections

```yaml
[16:03:57] [Server thread/ERROR]: Error occurred while enabling CMI v9.7.8.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "org.bukkit.plugin.PluginDescriptionFile.getDescription()" is null
	at CMI-9.7.8.1.jar/com.Zrips.CMI.Modules.Economy.VaultManager.setupVault(VaultManager.java:45) ~[CMI-9.7.8.1.jar:?]
	at CMI-9.7.8.1.jar/com.Zrips.CMI.Modules.Economy.EconomyManager.<init>(EconomyManager.java:90) ~[CMI-9.7.8.1.jar:?]
	at CMI-9.7.8.1.jar/com.Zrips.CMI.CMI.getEconomyManager(CMI.java:649) ~[CMI-9.7.8.1.jar:?]
	at CMI-9.7.8.1.jar/com.Zrips.CMI.Config.load(Config.java:640) ~[CMI-9.7.8.1.jar:?]
	at CMI-9.7.8.1.jar/com.Zrips.CMI.CMIOnEnable.init(CMIOnEnable.java:306) ~[CMI-9.7.8.1.jar:?]
	at CMI-9.7.8.1.jar/com.Zrips.CMI.CMI.onEnable(CMI.java:1306) ~[CMI-9.7.8.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:773) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:535) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1252) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:345) ~[purpur-1.21.4.jar:1.21.4-2372-73dae7f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Plugins

ServiceIO (2.1.0) Economist (0.1.0)

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by JellyBubb1e** [comment]
TheNextLvl-net/service-io#55

**Comment by mrfloris** [comment]
And you have disabled CMI economy?

**Comment by JellyBubb1e** [comment]
Yes. I have disabled CMI economy in the config.yml.

**Comment by hershate** [comment]
A solution can be found here [CMI cannot be used when other economic plugins are present TheNextLvl-net/service-io#55](https://github.com/TheNextLvl-net/service-io/issues/55)
