### ISSUE TITLE
Could not pass event PlayerItemDamageEvent to CMI v9.7.8.0

### ISSUE THREAD

**Issue by Ricano707** [Zrips/CMI#9365]
### Description of Issue

The error appears when I deal or take damage from mobs

[07:07:29] [Server thread/ERROR]: Could not pass event PlayerItemDamageEvent to CMI v9.7.8.0
java.lang.NoSuchMethodError: 'short net.Zrips.CMILib.Items.CMIItemStack.getDurability()'
 at CMI-9.7.8.0.jar/com.Zrips.CMI.AllListeners.PlayerItemDamageListener.itemDurabilityLoss(PlayerItemDamageListener.java:42) ~[CMI-9.7.8.0.jar:?]
 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor166.execute(Unknown Source) ~[?:?]
 at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
 at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
 at net.minecraft.world.item.ItemStack.hurtAndBreak(ItemStack.java:715) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.item.ItemStack.hurtAndBreak(ItemStack.java:804) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.item.ItemStack.hurtAndBreak(ItemStack.java:789) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.LivingEntity.doHurtEquipment(LivingEntity.java:2266) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.player.Player.hurtArmor(Player.java:1011) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2468) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.player.Player.actuallyHurt(Player.java:1050) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.LivingEntity.hurtServer(LivingEntity.java:1526) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.player.Player.hurtServer(Player.java:957) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.level.ServerPlayer.hurtServer(ServerPlayer.java:1466) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.Entity.hurtOrSimulate(Entity.java:2363) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:480) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:387) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:346) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:314) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:356) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.AbstractArrow.stepMoveAndHit(AbstractArrow.java:312) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:274) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1305) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.level.Level.guardEntityTick(Level.java:1489) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:812) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:794) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1876) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1330) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
 at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Version Information

```shell
CMI v9.7.8.0
CMILib 1.5.2.5

[07:43:51 INFO]: CMI plugin version: 9.7.8.0 SqLite-> 9.7.8.2
[07:43:51 INFO]: CMILib: 1.5.2.5 
[07:43:51 INFO]: Server version: Paper(81) 1.21.3-R0.1-SNAPSHOT-
[07:43:51 INFO]: CMI Economy: Enabled CMI Chat: Disabled 
[07:43:51 INFO]: Modules -> 66 enabled 1 disabled: votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
You will need to either downgrade CMILib by 2 versions or to upgrade CMI to 9.7.8.1+ version
