### ISSUE TITLE
Could not pass event PlayerItemDamageEvent to CMI v9.7.8.2

### ISSUE THREAD

**Issue by enci4167** [Zrips/CMI#9370]
### Description of Issue

java.lang.NoSuchMethodError: 'int net.Zrips.CMILib.Items.CMIItemStack.getDurability()'
        at CMI-9.7.8.2.jar/com.Zrips.CMI.AllListeners.PlayerItemDamageListener.itemDurabilityLoss(PlayerItemDamageListener.java:42) ~[CMI-9.7.8.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor239.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2324-e12a4de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at AdvancedEnchantments-9.14.3-1734749036855.jar/net.advancedplugins.ae.impl.utils.ItemDurability.damageItem(ItemDurability.java:79) ~[AdvancedEnchantments-9.14.3-1734749036855.jar:?]
        at AdvancedEnchantments-9.14.3-1734749036855.jar/net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:508) ~[AdvancedEnchantments-9.14.3-1734749036855.jar:?]
        at AdvancedEnchantments-9.14.3-1734749036855.jar/net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:87) ~[AdvancedEnchantments-9.14.3-1734749036855.jar:?]
        at AdvancedEnchantments-9.14.3-1734749036855.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:129) ~[AdvancedEnchantments-9.14.3-1734749036855.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2425.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2324-e12a4de]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1934) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Version Information

```shell
[11:22:26 INFO]: --------------------------------------------------
[11:22:26 INFO]: CMI 插件版本: 9.7.8.2 SqLite
[11:22:26 INFO]: CMILib: 1.5.1.1 -> 1.5.2.5
[11:22:26 INFO]: 伺服器: Paper(2324) 1.21.1-R0.1-SNAPSHOT+
[11:22:26 INFO]: CMI economy: 啟用 Vault: 1.7.3-CMI CMI 聊天: 啟用 
[11:22:26 INFO]: 模塊 -> 61 enable 6 disable: tablist, ranks, firstJoinMessages, votifier, cooldown, sitAnimation
[11:22:26 INFO]: --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
CMILib is out of date, please update it and error will go away
