### ISSUE TITLE
Plugin CMI v9.7.8.2 generated an exception while executing task 18233

### ISSUE THREAD

**Issue by DimaSergeew** [Zrips/CMI#9376]
### Description of Issue

spam warn in console

### Version Information

```shell
cmi 9.7.8.2, cmi lib: 1.5.2.5
```

### Errors

```shell
[17:16:21] [Craft Scheduler Thread - 53 - CMI/WARN]: [CMI] Plugin CMI v9.7.8.2 generated an exception while executing task 18233
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
	at java.util.HashMap.putMapEntries(HashMap.java:519) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:492) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.lambda$0(PortalManager.java:93) ~[CMI-9.7.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"725ca75"]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-UniverseSpigot-"725ca75"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:git-UniverseSpigot-"725ca75"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:16:27] [Craft Scheduler Thread - 37 - CMI/WARN]: [CMI] Plugin CMI v9.7.8.2 generated an exception while executing task 18233
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
	at java.util.HashMap.putMapEntries(HashMap.java:519) ~[?:?]
	at java.util.HashMap.<init>(HashMap.java:492) ~[?:?]
	at com.Zrips.CMI.Modules.Portals.PortalManager.lambda$0(PortalManager.java:93) ~[CMI-9.7.8.2.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[?:git-UniverseSpigot-"725ca75"]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[?:git-UniverseSpigot-"725ca75"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[?:git-UniverseSpigot-"725ca75"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Relevant Config Sections

```yaml
-
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
We also have this one

```
[19:45:04 WARN]: [CMI] Plugin CMI v9.7.8.2 generated an exception while executing task 36870
java.util.ConcurrentModificationException: null
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
at java.base/java.util.HashMap.putMapEntries(HashMap.java:519) ~[?:?]
at java.base/java.util.HashMap.<init>(HashMap.java:492) ~[?:?]
at CMI_9.7.8.2.jar/com.Zrips.CMI.Modules.Portals.PortalManager.lambda$0(PortalManager.java:93) ~[CMI_9.7.8.2.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

![27-12-2024_19-51-32](https://github.com/user-attachments/assets/2438a5e9-0327-4d6d-852a-0e5558ef249f)

Lucky its not Spammed for us. but sometimes its thrown out to console.
The Reason for the trigger is unknown.

**Comment by Zrips** [comment]
Should be addressed with next CMI update
