### ISSUE TITLE
Error with Portals in CMI 9.7.8.3

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#9383]
### Description of Issue
Wenn i enter /cmi portals or click on the portal list ingame i get this error in the console.
nothign happens ingame the Portaleditor itself does not open..
### Version Information
![05-01-2025_01-23-23](https://github.com/user-attachments/assets/ad9cfc2f-95fb-4400-a919-e753c5df2f3e)
### Errors
```shell
[01:22:02] [Server thread/INFO]: Cloude_Lecaw issued server command: /cmi portals
[01:22:04] [Server thread/INFO]: Cloude_Lecaw issued server command: /cmil rmc 3375453215796498960
[01:22:04] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMILib v1.5.2.6
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.8.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1015) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at org.bukkit.craftbukkit.entity.CraftPlayer.performCommand(CraftPlayer.java:786) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:116) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:97) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:83) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:77) ~[CMILib_1.5.2.6.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.CMI.performCommand(CMI.java:1480) ~[CMI_9.7.8.3.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.list.portals$2.onClick(portals.java:247) ~[CMI_9.7.8.3.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.Chat.ChatMessageObjectEdit$2.run(ChatMessageObjectEdit.java:111) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.RawMessages.RawMessageManager.perform(RawMessageManager.java:88) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.RawMessages.RawMessageListener.onShadowCommand(RawMessageListener.java:55) ~[CMILib_1.5.2.6.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2183) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2170) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:118) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1383) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.setHideTooltip(boolean)" because "miscInfoMeta" is null
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.GUI.CMIGui.addEmptyButton(CMIGui.java:335) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.GUI.CMIGui.fillEmptyButtons(CMIGui.java:305) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.GUI.CMIGui.fillEmptyButtons(CMIGui.java:297) ~[CMILib_1.5.2.6.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.list.portals.openUI(portals.java:1113) ~[CMI_9.7.8.3.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.list.portals.perform(portals.java:322) ~[CMI_9.7.8.3.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:413) ~[CMI_9.7.8.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	... 32 more
[01:22:05] [Server thread/INFO]: Cloude_Lecaw issued server command: /cmil rmc -3226411967720874257
[01:22:05] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to CMILib v1.5.2.6
org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v9.7.8.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1015) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at org.bukkit.craftbukkit.entity.CraftPlayer.performCommand(CraftPlayer.java:786) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:116) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:97) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:83) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.commands.CMICommand.performCommand(CMICommand.java:77) ~[CMILib_1.5.2.6.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.CMI.performCommand(CMI.java:1480) ~[CMI_9.7.8.3.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.list.portals$2.onClick(portals.java:247) ~[CMI_9.7.8.3.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.Chat.ChatMessageObjectEdit$2.run(ChatMessageObjectEdit.java:111) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.RawMessages.RawMessageManager.perform(RawMessageManager.java:88) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.RawMessages.RawMessageListener.onShadowCommand(RawMessageListener.java:55) ~[CMILib_1.5.2.6.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2183) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2170) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1379) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-75-9f90b4c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.setHideTooltip(boolean)" because "miscInfoMeta" is null
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.GUI.CMIGui.addEmptyButton(CMIGui.java:335) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.GUI.CMIGui.fillEmptyButtons(CMIGui.java:305) ~[CMILib_1.5.2.6.jar:?]
	at CMILib_1.5.2.6.jar/net.Zrips.CMILib.GUI.CMIGui.fillEmptyButtons(CMIGui.java:297) ~[CMILib_1.5.2.6.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.list.portals.openUI(portals.java:1113) ~[CMI_9.7.8.3.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.list.portals.perform(portals.java:322) ~[CMI_9.7.8.3.jar:?]
	at CMI_9.7.8.3.jar/com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:413) ~[CMI_9.7.8.3.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
	... 33 more
```
### Agreements
- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
any news about this one? :3

**Comment by CloudeLecaw** [comment]
i hope this can be fixed with 9.7.8.4.
Currently we just can edit Portals by modifie the Portals.yml file directly. :3

**Comment by Zrips** [comment]
Will be fixed with next CMILib update
