### ISSUE TITLE
Portals warning in console

### ISSUE THREAD

**Issue by PovilasLT** [Zrips/CMI#9384]
### Description of Issue

```
[06:30:25] [Craft Scheduler Thread - 61 - CMI/WARN]: [CMI] Plugin CMI v9.7.8.3 generated an exception while executing task 3526626
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628) ~[?:?]
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:337) ~[?:?]
	at java.base/java.util.HashSet.<init>(HashSet.java:121) ~[?:?]
	at CMI-9.7.8.3.jar/com.Zrips.CMI.Modules.Portals.PortalManager.showParticlesForPortal(PortalManager.java:143) ~[CMI-9.7.8.3.jar:?]
	at CMI-9.7.8.3.jar/com.Zrips.CMI.Modules.Portals.PortalManager.lambda$1(PortalManager.java:97) ~[CMI-9.7.8.3.jar:?]
	at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
	at CMI-9.7.8.3.jar/com.Zrips.CMI.Modules.Portals.PortalManager.lambda$0(PortalManager.java:97) ~[CMI-9.7.8.3.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.3.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Version Information

```shell
CMI: 9.7.8.3 Velocity CMIB  MySQL
CMILib: 1.5.2.6
Server: Paper(82) 1.21.3-R0.1-SNAPSHOT-
CMI economy: Įjungtas Vault: 1.7.3-CMI CMI Chat: Įjungtas
Modules -> 61 enabled 6 disabled: hpBossBar, tablist, ranks, firstJoinMessages, playerCombat, votifier
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Should be resolved with next update
