### ISSUE TITLE
I can't ban any players or use /ban command

### ISSUE THREAD

**Issue by AshleyFOXXX** [Zrips/CMI#9385]
### Description of Issue

When I type /ban <player> I get this error in console and can't ban any players 
![Screenshot 2024-12-31 120008](https://github.com/user-attachments/assets/b79a24f6-c573-4b32-929e-f3688f22d5fe)

### Version Information

```shell
CMI Version 9.7.8.3
CMILib version 1.5.2.6
```

### Errors

```shell
[04:12:30 WARN]: [CMI] Task #660831122 for CMI v9.7.8.2 generated an exception
java.lang.UnsupportedOperationException: Do not cast to com.destroystokyo.paper.profile.PlayerProfile
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.getId(CraftPlayerProfile.java:304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.ban.CraftProfileBanList.addBan(CraftProfileBanList.java:50) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.ban.CraftProfileBanList.addBan(CraftProfileBanList.java:19) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at CMI-9.7.8.2.jar/com.Zrips.CMI.Containers.CMIBanRecords.setBanned(CMIBanRecords.java:103) ~[CMI-9.7.8.2.jar:?]
        at CMI-9.7.8.2.jar/com.Zrips.CMI.Containers.CMIUser.setBanned(CMIUser.java:1701) ~[CMI-9.7.8.2.jar:?]
        at CMI-9.7.8.2.jar/com.Zrips.CMI.Containers.CMIUser.setBanned(CMIUser.java:1697) ~[CMI-9.7.8.2.jar:?]
        at CMI-9.7.8.2.jar/com.Zrips.CMI.commands.list.ban.lambda$1(ban.java:85) ~[CMI-9.7.8.2.jar:?]
        at CMILib1.5.2.5.jar/net.Zrips.CMILib.Version.Schedulers.CMIBukkitImpl.lambda$runTask$0(CMIBukkitImpl.java:33) ~[CMILib1.5.2.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[04:12:30 INFO]: UUID of player .GoodGamerz2365 is 00000000-0000-0000-0009-01f171f71a53
[04:12:30 INFO]: [floodgate] Floodgate player logged in as .GoodGamerz2365 joined (UUID: 00000000-0000-0000-0009-01f171f71a53)
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Flestiz** [comment]
Fixed in 9.7.8.3
