### ISSUE TITLE
Issue: Whois for players

### ISSUE THREAD

**Issue by Phyther** [Zrips/CMI#946]
**Description of issue or feature request:**
Doing /whois causes an error in console

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
07.10 20:00:36 [Server] INFO Phyther issued server command: /whois dte
07.10 20:00:36 [Server] WARN [CMI] Task #108239 for CMI v8.0.19.0 generated an exception
07.10 20:00:36 [Server] INFO java.lang.NullPointerException: null
07.10 20:00:36 [Server] INFO at com.Zrips.CMI.Modules.Homes.HomeManager.getReSpawnLocation(HomeManager.java:171) ~[?:?]
07.10 20:00:36 [Server] INFO at com.Zrips.CMI.commands.list.info$1$1.run(info.java:165) ~[?:?]
07.10 20:00:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.1.jar:git-Paper-332]
07.10 20:00:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.1.jar:git-Paper-332]
07.10 20:00:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.1.jar:git-Paper-332]
07.10 20:00:36 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-332]
07.10 20:00:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-332]
07.10 20:00:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-332]
07.10 20:00:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Cmi Version (using`/cmi version`):** 
8.0.19.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
git-paper-332 MC:1.13.1

**Comment by LogGits** [comment]
Are you still experiencing this issue?
