### ISSUE TITLE
CMI invalid world portal issue

### ISSUE THREAD

**Issue by 9922954** [Zrips/CMI#958]
**Description of issue or feature request:** CMI has errors when loading a portal with an invalid(in my case deleted) world.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Failed to load portal (tonewspawn)! Reason:null Error Log:
ERROR 10/10/2018 15:46:13
15:46:13[com.Zrips.CMI.Modules.Portals.PortalManager]: null
Console 10/10/2018 15:46:13
15:46:13java.lang.NullPointerException: null
at com.Zrips.CMI.Modules.Portals.PortalManager.recalculateChunks(PortalManager.java:195) ~[?:?]
at com.Zrips.CMI.Modules.Portals.PortalManager.addPortal(PortalManager.java:183) ~[?:?]
at com.Zrips.CMI.Modules.Portals.PortalManager.loadMap(PortalManager.java:410) ~[?:?]
at com.Zrips.CMI.Modules.Portals.PortalManager.load(PortalManager.java:352) ~[?:?]
at com.Zrips.CMI.Modules.Portals.PortalManager.<init>(PortalManager.java:61) ~[?:?]
at com.Zrips.CMI.CMI.getPortalManager(CMI.java:655) ~[?:?]
at com.Zrips.CMI.CMI.onEnable(CMI.java:1229) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1568]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1568]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1568]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1568]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1568]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1568]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1568]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1568]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1568]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1568]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

---

**Cmi Version (using`/cmi version`):** 8.0.14.0

**Server Type (Spigot/Paperspigot/etc):** paperspigot

**Server Version (using `/ver`):** 1.12.2 build 1568

**Comment by CloudeLecaw** [comment]
paper...so much mork to make in compatible aggain @.@
---so pls better you delet and crcreate this Portal,,would be faster then adding papersupport for this :§
