### ISSUE TITLE
[Bug] MySQL Error - Duplicate column name 'Rank'

### ISSUE THREAD

**Issue by momoservertw** [Zrips/CMI#984]
New server also get this problem (only has plugin CMI and Vault)

CMI plugin version: 8.0.19.0
Server version: Spigot 1.12.2-R0.1-SNAPSHOT
--
```
[21:43:41 INFO]: [CMI] Creating culumn |ALTER TABLE `momo_users` ADD COLUMN `Rank` text;|
[21:43:41 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate column name 'Rank'
[21:43:41 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:43:41 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:43:41 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:43:41 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:43:41 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[21:43:41 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:408)
[21:43:41 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
[21:43:41 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[21:43:41 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[21:43:41 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[21:43:41 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[21:43:41 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
[21:43:41 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552)
[21:43:41 WARN]:        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607)
[21:43:41 WARN]:        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480)
[21:43:41 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBMySQL.addCollumn(DBMySQL.java:207)
[21:43:41 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.checkDefaultUserCollumns(DBDAO.java:1416)
[21:43:41 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBDAO.setUp(DBDAO.java:475)
[21:43:41 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBMySQL.initialize(DBMySQL.java:27)
[21:43:41 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.startMysql(DBManager.java:127)
[21:43:41 WARN]:        at com.Zrips.CMI.Modules.DataBase.DBManager.start(DBManager.java:76)
[21:43:41 WARN]:        at com.Zrips.CMI.Config.load(Config.java:614)
[21:43:41 WARN]:        at com.Zrips.CMI.Config.load(Config.java:596)
[21:43:41 WARN]:        at com.Zrips.CMI.CMI.onEnable(CMI.java:1341)
[21:43:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:43:41 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:43:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[21:43:41 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[21:43:41 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[21:43:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[21:43:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[21:43:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[21:43:41 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:43:41 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:43:41 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by Zrips** [comment]
Will change table structure check to more robust one and avoid errors like this one with next update.

**Comment by Zrips** [comment]
FYI This is not dangerous error, its simply exists because you have no entries in database, as soon as some one logs into server, it should disappear.
