### ISSUE TITLE
Unknown world error?

### ISSUE THREAD

**Issue by 0xC1A551C** [Zrips/CMI#987]
Unknown world & inventory save error?

```
[04:16:53 ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
at org.bukkit.Location.deserialize(Location.java:1014) ~[patched_1.13.1.jar:git-Paper-368]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:79) ~[patched_1.13.1.jar:git-Paper-368]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:119) ~[patched_1.13.1.jar:git-Paper-368]
at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:197) ~[patched_1.13.1.jar:git-Paper-368]
at org.bukkit.util.io.BukkitObjectInputStream.resolveObject(BukkitObjectInputStream.java:48) ~[patched_1.13.1.jar:git-Paper-368]
at java.io.ObjectInputStream.checkResolve(ObjectInputStream.java:1621) ~[?:1.8.0_181]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[?:1.8.0_181]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~[?:1.8.0_181]
at java.util.HashMap.readObject(HashMap.java:1409) ~[?:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170) ~[?:1.8.0_181]
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178) ~[?:1.8.0_181]
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069) ~[?:1.8.0_181]
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573) ~[?:1.8.0_181]
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431) ~[?:1.8.0_181]
at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.deserialize(SavedInventoryManager.java:360) ~[?:?]
at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.loadInventories(SavedInventoryManager.java:195) ~[?:?]
at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.loadInventories(SavedInventoryManager.java:175) ~[?:?]
at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.getInventories(SavedInventoryManager.java:164) ~[?:?]
at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.saveInv(SavedInventoryManager.java:242) ~[?:?]
at com.Zrips.CMI.Modules.SavedInv.SavedInventoryManager.saveInv(SavedInventoryManager.java:226) ~[?:?]
at com.Zrips.CMI.Modules.SavedInv.SaveInvListener.onPlayerDeath(SaveInvListener.java:63) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor457.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-368]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-368]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-368]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-368]
at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:459) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:514) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:824) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:654) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityInsentient.B(EntityInsentient.java:1247) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityZombie.B(EntityZombie.java:287) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.a(SourceFile:124) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.e(SourceFile:116) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.PathfinderGoalZombieAttack.e(SourceFile:28) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(SourceFile:129) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:675) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityLiving.k(EntityLiving.java:2334) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityInsentient.k(EntityInsentient.java:511) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityMonster.k(EntityMonster.java:22) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityZombie.k(EntityZombie.java:203) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2182) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:249) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityMonster.tick(EntityMonster.java:26) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.EntityZombie.tick(EntityZombie.java:170) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1619) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.World.g(World.java:1586) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1393) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:614) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1092) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-368]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-368]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Cmi Version (using`/cmi version`):**  8.0.19.0

**Server Type (Spigot/Paperspigot/etc):**  paper

**Server Version (using `/ver`):**  1.13.1

**Comment by Zrips** [comment]
This happens when you have saved inventories in worlds which no longer exist. Will think about some work around to avoid those error messages.
