### ISSUE TITLE
Error con el comando /cmi dsign new

### ISSUE THREAD

**Issue by MechaYT** [Zrips/CMI#992]
**Description of issue or feature request:**

Al intentar usar el comando "/cmi dsign new" me aparece un error.
Dejare aquí el mensaje que me muestra: "An internal error occurred while attempting to perform this command"

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####
Este error lo he tenido con todas las versiones que he usado del CMI.
Asi que no he tenido la oportunidad de usar esa gran caracteristica.

Este es el error mostrado por la consola.
```
17.10 20:49:32 [Server] INFO Mecha_YT issued server command: /cmi dsign new Test
17.10 20:49:32 [Server] ERROR null
17.10 20:49:32 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'cmi' in plugin CMI v8.0.20.0
17.10 20:49:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
17.10 20:49:32 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
17.10 20:49:32 [Server] INFO Caused by: java.lang.NullPointerException
17.10 20:49:32 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.CMISign.getArea(CMISign.java:99) ~[?:?]
17.10 20:49:32 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addPlayersNearSign(SignManager.java:414) ~[?:?]
17.10 20:49:32 [Server] INFO at com.Zrips.CMI.Modules.DynamicSigns.SignManager.addSign(SignManager.java:81) ~[?:?]
17.10 20:49:32 [Server] INFO at com.Zrips.CMI.commands.list.dsign.perform(dsign.java:260) ~[?:?]
17.10 20:49:32 [Server] INFO at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:244) ~[?:?]
17.10 20:49:32 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-dcd1643-e60fc34]
17.10 20:49:32 [Server] INFO ... 15 more
```

---

**Cmi Version (using`/cmi version`):** 8.0.20.0

**Server Type (Spigot/Paperspigot/etc):** Spigot 1.12.2-R0.1-SNAPSHOT

**Server Version (using `/ver`):** This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):** CMI

**Comment by Zrips** [comment]
This should be fixed in latest versions
